### ISSUE TITLE
Mega Man Battle Network 4/Rockman EXE 4 - Woodman Scenario Crash

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#10]
During the Woodman scenario, Woodman does some mean stuff, like making these wooden spikes come out of the ground to attack you.  This is nefarious, yes, but, his evil knows no bounds.  After a virus battle in the spike filled battlefield, the game will hang.

I've provided a savestate for the japanese version of the game right before the spike filled area.  hold down/left to activate the cutscene, then get into a virus battle in the area.  The game will black screen after you run away or win (hit L then A to runaway)

I was going to attach a screenshot of the game frozen, but it's just a black screen.

https://dl.dropboxusercontent.com/u/484730/RockmanEXE4.ss1

This game is known to have serious issues on original Nintendo DSes as well according to various postings around the web.

**Comment by grantgalitz** [comment]
It's reading from unmapped memory, and relies on a specific value to be returned from said unmapped memory.

**Comment by endrift** [comment]
Seems to be fixed now.
