### ISSUE TITLE
Sonic X (GBA Video) crashes on Wii

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#1001]
A regression but I could not reproduce on Windows, only on Wii. I also tested the Pokemon one to see if it's a common issue with video carts but it starts fine.

First broken nightly e2f4fdbdac57da87cbf500a9c32109e7162d5230
Last working nightly 821c8988a385025f2f5c741d279ea0e745f47c0c

**Comment by endrift** [comment]
Do you have the same crash with Pokémon FireRed?

**Comment by SuperrSonic** [comment]
No
