### ISSUE TITLE
No more 64-bit builds on the website

### ISSUE THREAD

**Issue by CharlesCorrin** [mgba-emu/mgba#1004]
It's been a fairly long time since the site generated a 64-bit build. The last one was 5031-c8dacbb and that one had no 32-bit build. 5030-eafd265 was the last one with both 32-bit and 64-bit builds. Is this an error in the code or in the builder? Or will there no longer be 64-bit builds?

**Comment by endrift** [comment]
This is due to problems with the builder. There are similar problems with the Wii build right now too.

**Comment by endrift** [comment]
Fixed now.
