### ISSUE TITLE
Building fails on Debian stable

### ISSUE THREAD

**Issue by kargaroc** [mgba-emu/mgba#1007]
On both the versions of Clang and GCC provided with Debian 9  (GCC 6.3, Clang 3.8.1), I get this error when building the latest master.

The GCC version
```
/home/terus/Desktop/mgba-master/src/platform/qt/Window.cpp: In member function ‘void QGBA::Window::openSettingsWindow()’:
/home/terus/Desktop/mgba-master/src/platform/qt/Window.cpp:415:57: error: ‘m_libraryView’ was not declared in this scope
  connect(settingsWindow, &SettingsView::libraryCleared, m_libraryView, &LibraryController::clear);
                                                         ^~~~~~~~~~~~~
/home/terus/Desktop/mgba-master/src/platform/qt/Window.cpp:415:73: error: incomplete type ‘QGBA::LibraryController’ used in nested name specifier
  connect(settingsWindow, &SettingsView::libraryCleared, m_libraryView, &LibraryController::clear);
                                                                         ^~~~~~~~~~~~~~~~~
[ 98%] Building CXX object qt/CMakeFiles/mgba-qt.dir/AudioProcessorQt.cpp.o
/home/terus/Desktop/mgba-master/src/platform/qt/Window.cpp: In member function ‘void QGBA::Window::setController(QGBA::CoreController*, const QString&)’:
/home/terus/Desktop/mgba-master/src/platform/qt/Window.cpp:1833:6: error: ‘m_gdbController’ was not declared in this scope
  if (m_gdbController) {
      ^~~~~~~~~~~~~~~
/home/terus/Desktop/mgba-master/src/platform/qt/Window.cpp:1837:6: error: ‘m_console’ was not declared in this scope
  if (m_console) {
      ^~~~~~~~~
qt/CMakeFiles/mgba-qt.dir/build.make:1338: recipe for target 'qt/CMakeFiles/mgba-qt.dir/Window.cpp.o' failed
make[2]: *** [qt/CMakeFiles/mgba-qt.dir/Window.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:216: recipe for target 'qt/CMakeFiles/mgba-qt.dir/all' failed
make[1]: *** [qt/CMakeFiles/mgba-qt.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```
This does not happen when building 0.6.1

**Comment by endrift** [comment]
Let me know if you hit any other build failures and I'll reopen the bug.

**Comment by kargaroc** [comment]
Now building fails with
`[ 71%] Linking C executable mgba
[ 72%] Building CXX object qt/CMakeFiles/mgba-qt.dir/AboutScreen.cpp.o
[ 72%] Building CXX object qt/CMakeFiles/mgba-qt.dir/main.cpp.o
../libmgba.so.0.7.0: undefined reference to `mDebuggerSymbolAdd'
collect2: error: ld returned 1 exit status
sdl/CMakeFiles/mgba-sdl.dir/build.make:231: recipe for target 'sdl/mgba' failed
make[2]: *** [sdl/mgba] Error 1
CMakeFiles/Makefile2:159: recipe for target 'sdl/CMakeFiles/mgba-sdl.dir/all' failed
make[1]: *** [sdl/CMakeFiles/mgba-sdl.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 73%] Building CXX object qt/CMakeFiles/mgba-qt.dir/AssetTile.cpp.o
[ 73%] Building CXX object qt/CMakeFiles/mgba-qt.dir/AssetView.cpp.o
[ 74%] Building CXX object qt/CMakeFiles/mgba-qt.dir/AudioProcessor.cpp.o
[ 74%] Building CXX object qt/CMakeFiles/mgba-qt.dir/CheatsModel.cpp.o
^Cqt/CMakeFiles/mgba-qt.dir/build.make:282: recipe for target 'qt/CMakeFiles/mgba-qt.dir/CheatsModel.cpp.o' failed
make[2]: *** [qt/CMakeFiles/mgba-qt.dir/CheatsModel.cpp.o] Interrupt
qt/CMakeFiles/mgba-qt.dir/build.make:234: recipe for target 'qt/CMakeFiles/mgba-qt.dir/AssetView.cpp.o' failed
make[2]: *** [qt/CMakeFiles/mgba-qt.dir/AssetView.cpp.o] Interrupt
qt/CMakeFiles/mgba-qt.dir/build.make:258: recipe for target 'qt/CMakeFiles/mgba-qt.dir/AudioProcessor.cpp.o' failed
make[2]: *** [qt/CMakeFiles/mgba-qt.dir/AudioProcessor.cpp.o] Interrupt
CMakeFiles/Makefile2:216: recipe for target 'qt/CMakeFiles/mgba-qt.dir/all' failed
make[1]: *** [qt/CMakeFiles/mgba-qt.dir/all] Interrupt
Makefile:149: recipe for target 'all' failed
`

**Comment by endrift** [comment]
See if 3443c141692ccd12240b2f69b6d7b14083f8d149 helps.

**Comment by kargaroc** [comment]
It works now!  Even the static build works, which I've had problems with before.
