### ISSUE TITLE
Vertical sprite mosaic bug

### ISSUE THREAD

**Issue by CaptainCaffeine** [mgba-emu/mgba#1008]
When comparing mosaic output between mGBA and my own emulator, I noticed that the bottom block of vertical mosaic sprites would sometimes render incorrectly in mGBA. Below are pictures of Tonc's mos_demo.gba running on hardware and in mGBA, with a horizontal mosaic of 2 and a vertical mosaic of 15. The yellow fangs of the metroid on the left should be half the length of the blue fangs of the metroid on the right, but on mGBA they're the same length.
![mgba_tonc_mos_demo_bug](https://user-images.githubusercontent.com/4934864/37192137-a04b8938-2318-11e8-9850-13cddd741b6f.png)
![mos_demo_hardware](https://user-images.githubusercontent.com/4934864/37192224-34482cea-2319-11e8-8a34-b29014eeba3e.jpg)

The demo can be downloaded from www.coranac.com/files/tonc-bin.zip. You can use the d-pad to adjust the mosaic of the sprite, and A+d-pad to adjust the mosaic of the background.

**Comment by endrift** [comment]
This appears to affect the intro cutscene in Aria of Sorrow:

![a2ce-8](https://user-images.githubusercontent.com/605502/37194568-b389cb3a-2323-11e8-8c6f-eac66b0652a1.png) (old behavior) vs ![a2ce-7](https://user-images.githubusercontent.com/605502/37194569-b3a47f84-2323-11e8-9807-fdf95231ddaf.png) (fixed behavior)

Compared against hardware: 
<img width="697" alt="screen shot 2018-03-08 at 10 51 35 pm" src="https://user-images.githubusercontent.com/605502/37194598-dbed0754-2323-11e8-999c-46b384d9f796.png">

Unfortunately my fix appears to break the Minish Cap test, so I'll need to take a closer look at it when I have more time.

**Comment by endrift** [comment]
Finally figured out how to fix this properly. Thanks for finding it!
