### ISSUE TITLE
Fullscreen command line not working correctly

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#101]
![Command Line](http://i.imgur.com/F4OxH9u.png)

The window size from the last use is retained.

**Comment by endrift** [comment]
This is known to work on OS X. I can try on Windows 7 and Linux, but I don't have any Windows newer than 7.

**Comment by bentley** [comment]
I can reproduce the issue on OpenBSD with SDL.

    <bentley`> endrift: hm, i just tried mgba -f and it didn't run at fullscreen, just windowed 1x

**Comment by endrift** [comment]
@bentley That's a different issue: fullscreen is not currently implemented in the SDL 1.2 build.

**Comment by tony971** [comment]
7 users do get a free upgrade to 10. Not sure you're willing to make that jump, though.

**Comment by karasuhebi** [comment]
I thought -f just didn't work on Qt?
[16:59:18]  <endrift> shoot, doesn't work on the Qt port
[16:59:21]  <endrift> only the SDL one
[16:59:22]  <endrift> yeah
[16:59:34]  <endrift> mGBA: invalid option -- f

**Comment by endrift** [comment]
The main SDL build is 2.0, not 1.2; I don't support 1.2 as well as I do 2.0.

**Comment by tony971** [comment]
If you do end up finding this valid and working on the code, it might be economical to implement this old enhancement at the same time. https://endrift.com/mgba/bugs/show_bug.cgi?id=208

**Comment by tony971** [comment]
Actually, fixed.
