### ISSUE TITLE
GB Audio: sound inaccuracies in many games (volume/pitch-related?)

### ISSUE THREAD

**Issue by bryc** [mgba-emu/mgba#1016]
mGBA's GB audio emulation always seemed a bit off to me, yet it was so minor that I was never too sure.  However in a few games it is more obviously borked:

#### Banishing Racer (GB)
[mGBA](https://instaud.io/1Vcr) / [SameBoy](https://instaud.io/1Vcs) / [Gambatte](https://instaud.io/1Vcv) / [BGB](https://instaud.io/1Vcw)

mGBA struggles with the tremolo/vibrato effect in Banishing Racer, over-exaggerating it, while the others seem consistent. SameBoy is much more 'clicky' on the arpeggio in Channel 2 though.

#### Adventures of Lolo (GB)
[mGBA](https://instaud.io/1Vci) / [SameBoy](https://instaud.io/1Vcm) / [Gambatte](https://instaud.io/1Vco) / [BGB](https://instaud.io/1Vcp)

mGBA seems to struggle with the volume macro used in Channel 1 which has a bit of a decay envelope. Sounds almost granular, like a buffer underflow. Could be just processing the volume changes too slowly, but that's just a guess.

A couple other games that had audible artifacts (but were minor) worth mentioning:

Momotarou Dengeki 2 (GB)
Mega Man V (SGB)
Kirby's Dream Land 2 (SGB)
Quest RPG - Brian's Journey (GBC)
Wario Land 3 (GBC)
Tomb Raider: Curse of the Sword (GBC)

**Comment by DavisOlivier** [comment]
I have also noticed some volume inconsistences in Pokémon FR/LG, most notably on the song "Wild Pokémon Battle" at 00:04 compared to other players and some youtube videos.
