### ISSUE TITLE
Edit Shortcuts window setting "0" for "Fast forward (held)" gamepad bind after you clear it

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#102]
Happens as of the latest nightly, 1624cd9, on Windows 8.1 Pro x64

**Comment by endrift** [comment]
The problem was actually switching between keyboard and gamepad shortcuts at the bottom. Fixed now, regardless.

**Comment by karasuhebi** [comment]
Oh OK cool. Thanks for looking into this!
