### ISSUE TITLE
Force starting Super Mario Land 2 DX in GBC mode

### ISSUE THREAD

**Issue by xadox-1st** [mgba-emu/mgba#1025]
Playing [Super Mario Land 2 DX](http://www.romhacking.net/hacks/3784/) is not possible on 3DS/2DS.
Since mGBA starts the rom in GB mode and not in GBC mode:

![img_20180327_112530](https://user-images.githubusercontent.com/13217841/37958891-071d6940-31b2-11e8-8649-1dc21613fb07.jpg)

**Comment by TurdPooCharger** [comment]
I'm using an mGBA 0.7.0 nightly. This is what I
![sml2_6gc_dx](https://user-images.githubusercontent.com/35666439/37971268-81357a38-31a3-11e8-9a4e-55915edc0c43.png)
'm getting.

**Comment by xadox-1st** [comment]
Yeah you are right. Found my problem. Started the game first without bios properly set.
After setting the bios forgot about the Auto-State feature, so the B/W state was always loading again automaticly.

After deleting the state or disabling the load feature the game is loading the right way.
