### ISSUE TITLE
Graphical glitches in Castlevania Legends

### ISSUE THREAD

**Issue by kurayami6** [mgba-emu/mgba#1029]
What the title says

mGBA version 0.7-5061-36de596f.  All settings default.
Windows 7
i5
GTX 970

![capture](https://user-images.githubusercontent.com/31968468/38128167-2cb6823c-3445-11e8-937d-dc45ca880db0.PNG)

**Comment by endrift** [comment]
Noted in #223, but having this split out is fine.
