### ISSUE TITLE
[Feature Request] 'Apply' button on the Settings window

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#103]
Volume changes don't take effect right away and being able to apply the changes without having to press 'OK' (which closes the window) and then having to re-open it again would be very nice while you're trying to dial in your ideal volume level.

Thanks!

**Comment by karasuhebi** [comment]
Thanks for this, much appreciated. Is there a way to make it so Apply starts off grayed out and only becomes usable once the user makes a change though? I think that would be better UX-wise. For example I know that sometimes I go into a Settings menu and think I clicked on something but can't be sure so I look at the status of the Apply button for confirmation.

**Comment by endrift** [comment]
That would be much more difficult, but I can look into it.
