### ISSUE TITLE
Communication error when trying link cable emulation

### ISSUE THREAD

**Issue by PureTryOut** [mgba-emu/mgba#1031]
I'm trying to link Pokémon Emerald and Sapphire together so I can trade over some Pokémons, but the moment the characters walk into the room, the game reports a communication error and I have to reset the game. Initiating connection seems to work fine.

![output](https://user-images.githubusercontent.com/1565836/38164725-e1e85a2c-3508-11e8-8e7c-7326f7340891.gif)

This happens using mGBA 0.6.1.

**Comment by PureTryOut** [comment]
@endrift I see you are the main developer of this project, do you have any clue what's going on here?

**Comment by PureTryOut** [comment]
This bug is still present in the latest git master :disappointed:

**Comment by AyanamiRei1** [comment]
Yep same issue here.

**Comment by endrift** [comment]
This was fixed by @kakashidinho in bb37a60765fafdce9db1aeb0f70f951c29522777.
