### ISSUE TITLE
(libretro) Medusa libretro core?

### ISSUE THREAD

**Issue by orbea** [mgba-emu/mgba#1033]
This is more of a question than a request, but would it be possible that medusa will implement a libretro port similar to the mgba master? I think even if its only hooked up with a cmake build it would be valuable to have. I looked at the other issues and haven't seen anyone publicly discuss this before?

Obviously this currently results in a build failure.
https://pastebin.com/ttujDSkd

**Comment by endrift** [comment]
This is because of colorspace issues. mGBA uses 565 for libretro because the GBA has 15-bit color, but the DS has 18-bit color (6bpc) and the component order libretro supports does not work well with mGBA's internal representation.

**Comment by endrift** [comment]
I believe mGBA uses XBGR internally for 32-bit color. I can see about switching that to XRGB for the libretro core, but it will take some work.

**Comment by orbea** [comment]
Cool! Thanks for the reply, its fully understandable if it can't be done trivially.

**Comment by orbea** [comment]
@endrift I'm really not sure this is worth doing anymore, feel free to close if you want.
