### ISSUE TITLE
Audio volume very low and sound pops in GB(C) games

### ISSUE THREAD

**Issue by profi200** [mgba-emu/mgba#1036]
The audio volume is way lower than it should be (not sure when this was introduced).

GB(C) games have sound pops every time a new track is loaded/played by games. Also noticeable at game boot with and without BIOS.

mGBA 0.6.2
N3DS 11.6.0-39 with Luma3DS 9.0

**Comment by endrift** [comment]
Related to #1016

**Comment by endrift** [comment]
The changes involved have been reverted in the 0.6 branch and won't be an issue in 0.6.3--that said, they were not reverted in master because I'm not sure they're wrong--they're just smoothed out on hardware.

**Comment by orbea** [comment]
Could it mean there is something missing from the current solution in hardware?

**Comment by orbea** [comment]
Could it mean there is something missing from the current solution in the master?

**Comment by endrift** [comment]
yeah, that's what I'm hoping, but I haven't looked into it yet.

**Comment by endrift** [comment]
Does this still reproduce? It may a little but it should be a bunch better now.

**Comment by orbea** [comment]
I can still reproduce this with Pokemon Crystal, the pops when booting the game are worse and the actual gameplay is better and almost absent.

**Comment by endrift** [comment]
I'm pretty sure this is fixed, per other closed issues.

**Comment by profi200** [comment]
It is.
