### ISSUE TITLE
Pokémon Kristall (DE) graphics corruption on title screen

### ISSUE THREAD

**Issue by profi200** [mgba-emu/mgba#1040]
A white rect is displayed on the title screen which doesn't belong there.
![](https://dl.dropboxusercontent.com/s/82wit45fookj8um/Pokemon%20-%20Kristall-Edition%20%28D%29-0.png "")

mGBA 0.6.2
N3DS 11.6.0-39 with Luma3DS 9.0

**Comment by orbea** [comment]
This was fixed somewhere between `0.6.2` and the current master.

**Comment by endrift** [comment]
Fixed in 4deec102daedb767b64a082ffd69cdc89f84f805.
