### ISSUE TITLE
0.6.2 crashes on startup on MacOS, due to old QT version

### ISSUE THREAD

**Issue by megakode** [mgba-emu/mgba#1041]
In the crash log i see the following message:

"requires version 5.9.0 or later, but QtMultimedia provides version 5.6.0"

Mac OS version: High Sierra (10.13.3)

I have no clue how i got the current QT version, and if it was bundled with MacOS or was installed as a part of a BREW package. Anyway, running "brew upgrade QT" upgraded the QT library to 5.10.1, which fixed the problem.

**Comment by endrift** [comment]
Should be fixed now, can you download a dev build and let me know?

**Comment by endrift** [comment]
The fix is in 0.6.3 as well.
