### ISSUE TITLE
Saving to battery causes an automatic crash on MacOS High Sierra 10.13.4

### ISSUE THREAD

**Issue by sam98brown** [mgba-emu/mgba#1049]
I've been using mGBA on my Macbook to play Mother 3 and have been experiencing some issues. I can load my save fine, and savestates are working, but when I go to save ingame, as soon as it begins saving mGBA crashes instantly. This is frustrating as I'm quite far into the game and I really need to be able to save ingame, so that when I die I can return to my savepoint. This isn't possible with savestates as I will lose my level progress.

I tried downloading the latest mGBA but I get this message when running:

Check with the developer to make sure mGBA works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS

I'm running MacOS High Sierra 10.13.4.

I have also tried loading the savestate, then moving the .sav file outside of the folder so mGBA would create a new one, just in case it was an issue with that save file. It did not work.

**Comment by endrift** [comment]
Does this happen in the dev builds too? Or do you have the same error?

**Comment by endrift** [comment]
It's been a few years. Does this still reproduce?
