### ISSUE TITLE
Player numbers don't update

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#105]
If you open up a multiplayer window (Player 2 of 2) and then close the original window, Player 2 keeps the second controller's bindings (which isn't necessarily a bad thing). However, if you open a multiplayer window again, both the original Player 2 and the new window list themselves as "Player 2 of 2." The new window will correctly (or incorrectly) use the first controller, but neither of them will be "Player 1 of 2"

**Comment by endrift** [comment]
This is a known issue, but it would take a bit of work that I never got around to doing.

**Comment by endrift** [comment]
I fixed this yesterday.
