### ISSUE TITLE
Link's Awakening (regular and DX) is missing its hud and start menu

### ISSUE THREAD

**Issue by NarryG** [mgba-emu/mgba#1051]
0.6.2 stable (mGBA-0.6.2-2018-04-04-win32), Windows 10 Fall Creator's Update

From the very start of the game, the HUD and the start screen fail to draw in both Link's Awakening and Link's Awakening DX.

This issue does not exist in 0.6.1 stable so it appears to be a regression since then.

mGBA 0.6.2
![image](https://user-images.githubusercontent.com/3047793/38654132-d3ef1416-3ddb-11e8-8f14-3cb1dc6e8289.png)
![image](https://user-images.githubusercontent.com/3047793/38654162-ef75f3e4-3ddb-11e8-9f6b-bd2a9590f1d8.png)
![image](https://user-images.githubusercontent.com/3047793/38654208-24968a34-3ddc-11e8-858b-5205001b6ff5.png)

Gamebatte:
![image](https://user-images.githubusercontent.com/3047793/38654102-bd210c6c-3ddb-11e8-96fd-8c98b9087707.png)
![image](https://user-images.githubusercontent.com/3047793/38654170-f7046fd2-3ddb-11e8-884e-a0fc7d3c2beb.png)
![image](https://user-images.githubusercontent.com/3047793/38654221-38148eee-3ddc-11e8-924d-e106b677086a.png)

**Comment by endrift** [comment]
Same bug as #1040, which has since been fixed. Use a dev build in the meantime.
