### ISSUE TITLE
[GBA] Yu-Gi-Oh! World Championship Tournament 2004 - Stuck on "Loading" (mGBA for 3DS)

### ISSUE THREAD

**Issue by ShadCanard** [mgba-emu/mgba#1053]
The title is pretty explicit. I tried to launch the .gba file for this game, and it's stuck for 3 or 4 minutes on a black screen with only "Loading..." written on the bottom screen of the 3DS.

**Comment by endrift** [comment]
Can't reproduce. It may have been fixed, please retest.

**Comment by endrift** [comment]
Closing due to lack of reply. Will reopen if I get more info and it still reproduces.
