### ISSUE TITLE
GBA: Sprites flicker or disappear while rewinding

### ISSUE THREAD

**Issue by dobyrch** [mgba-emu/mgba#1062]
Bisected to ec25074cec84.

![flicker](https://user-images.githubusercontent.com/2789460/39111156-aaa2be76-4706-11e8-95e9-e068a277b28e.gif)

**Comment by endrift** [comment]
SHOULD be fixed by 279862261b36565995894eca7cc08061e808978f, let me know.

**Comment by dobyrch** [comment]
Yup, that did the trick!
