### ISSUE TITLE
Updated retroarch/libretro .cia?

### ISSUE THREAD

**Issue by Dial0118999** [mgba-emu/mgba#1065]
I saw that the last available release for mGBA (.cia version) for Retroarch/Libretro is version 0.1.1 (https://github.com/libretro/mgba/releases), and that's not even an actual release.

I was just wondering if there would ever be an update for the .cia and the .core, since the latest release is from 2015. Libretro also seem to have stopped including mGBA in their .cia releases, but this one is absolutely perfect, so that's why I'm asking.

**Comment by endrift** [comment]
Please file this on libretro/mgba--they're the ones who manage those releases.
