### ISSUE TITLE
Nettou KOF 95/96: Works as 2P controller.

### ISSUE THREAD

**Issue by litaniast** [mgba-emu/mgba#1067]
I know mGBA doesn't have two or more controllers setting, but Nettou KOF95 and 96 are responding as 2P controller, so, controller is working but hidden character cheat (press SELECT button rapidly when the Takara logo shown) doesn't work and play as 2nd player instead of 1st.

Of course that bug is with SGB mode.

**Comment by endrift** [comment]
Sorry about that, should be fixed now
