### ISSUE TITLE
Qt: Gray out "New multiplayer window" after four windows

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#107]
It's already disabled. There's just no visual representation of it being disabled.

**Comment by waddlesplash** [comment]
Can I take a stab at this?

**Comment by endrift** [comment]
Yeah, sure! Two things to take note of:

1. There's a `MAX_GBAS` macro floating around, I think it's in sio.h
2. The wireless adapter supports more than 4 systems, so this might need to be reworked later.
