### ISSUE TITLE
mGBA (X)Ubuntu problems

### ISSUE THREAD

**Issue by fancymelonub** [mgba-emu/mgba#1070]
1. mGBA in Ubuntu repo hasn't been updated since 0.5.2
2. Trying to install the latest dev version of mGBA via .deb says libelfg0 is required but you can't install the dependency

**Comment by endrift** [comment]
1. is handled by @sergiobenrocha2 and the Debian maintainers. Sergio told me he's updated them but the Debian maintainers have been lax.
2. I'll fix right now.
