### ISSUE TITLE
[3DS CIA] Placing the cursor over mGBA crashes the 3DS.

### ISSUE THREAD

**Issue by PalomBM** [mgba-emu/mgba#1071]
The latest nightlies have no banner appearing on the top screen once they have been installed, but they can still boot, but only at that point. After viewing System Settings or closing the 3DS, it crashes when you move the cursor over mGBA. This happens on both O3DS and N3DS.

**Comment by endrift** [comment]
fixed in https://github.com/mgba-emu/dependencies/commit/11cfa3bb9b1190ddbdcd178b2a7ec4950f6036fe
