### ISSUE TITLE
Unable to save after loading temporary save file

### ISSUE THREAD

**Issue by dogtopus** [mgba-emu/mgba#1072]
The in-game saving works fine without using the temporary save. However, if I load a save file other than the main save file using "Load temporary save", neither the temporary save nor the main save will be updated when I save in-game. (oddly the timestamp of the temporary save got updated but not the data)

**Comment by endrift** [comment]
I'm not sure what you were expecting this feature to do; that's its intended behavior.

**Comment by dogtopus** [comment]
I thought it treats the save file as an alternative file other than the main one (in read-write, not read-only). Also the mtime of the alternative save got updated for some reason (as I mentioned previously). IMO it should't do this if the save file was intended to be read-only (I saw the mtime updated and thought that it saves properly, and later found out that I lost my progress)

**Comment by endrift** [comment]
Yeah I'm not sure why the mtime was updated. I can add a load alternate save feature; should be pretty trivial.

**Comment by endrift** [comment]
I added the load alternate feature as well as fixing the mtime issue (in separate commits).
