### ISSUE TITLE
Pokemon Gold/Silver/Crystal: Glitchy serialization

### ISSUE THREAD

**Issue by dobyrch** [mgba-emu/mgba#1073]
Rewinding or saving in any of the GBC Pokemon games results in unpredictable behavior−resetting, hanging, graphical glitches, incorrect palettes, glitchy music, etc.

The most reliable way to trigger a glitch is to open a menu during battle, then rewind.  Fast-forwarding while rewinding also seems to make things worse.

![glitch](https://user-images.githubusercontent.com/2789460/39564478-000f2c68-4ee7-11e8-8dab-236b126015a5.gif) ![glitch1](https://user-images.githubusercontent.com/2789460/39564526-288a733c-4ee7-11e8-9d11-f1e0bdde3089.png)
![glitch2](https://user-images.githubusercontent.com/2789460/39564528-2a328026-4ee7-11e8-8676-8621a5a4880f.png) ![glitch3](https://user-images.githubusercontent.com/2789460/39564743-0a328aae-4ee8-11e8-9a3d-c54299fb8600.png)

I can reproduce this as far back as I can compile mGBA (ebbc51f23c423) on both qt and retroarch.  I've attached a sav file for convenience, along with good (ss1) and bad (ss2 - corrupted music; ss3 - corrupted graphics) save states.

[Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).zip](https://github.com/mgba-emu/mgba/files/1970044/Pokemon.-.Silver.Version.USA.Europe.SGB.Enhanced.GB.Compatible.zip)

**Comment by endrift** [comment]
I'm having trouble reproducing this. What's your configuration file look like?

**Comment by dobyrch** [comment]
I removed `~/.config/mgba` and can still reproduce it with the default settings (and rewind enabled).  

After experimenting a bit more, I think I might be experiencing two separate issues: one with Qt and one with RetroArch.  With the Qt version, I get glitches in every game I've tried by rewinding and using fast forward at the same time.  The effects are random and unpredictable (the gif/screenshots from my first comment were also taken with Qt):
![scrambled](https://user-images.githubusercontent.com/2789460/39798204-1e0af152-5392-11e8-9298-34c3c5b3304a.gif)

On RetroArch, I don't experience the same class of glitches.  Everything works fine with most games (even with rewind+fast-forward), but when something goes wrong the weirdness is more subtle:

1) In Pokemon Silver, after saving or rewinding during a battle, sometimes the items in your pack are all all named "?".  Exiting that menu causes the game to crash, but if you never open your pack the game plays normally.

![pokemon - silver version usa europe sgb enhanced gb compatible -180509-144956](https://user-images.githubusercontent.com/2789460/39799843-430911e2-5355-11e8-91cf-fcb9481a64db.png) ![pokemon - silver version usa europe sgb enhanced gb compatible -180509-145004](https://user-images.githubusercontent.com/2789460/39799846-4620260e-5355-11e8-817d-302d55348c8d.png)

2) In Super Mario Land 2: 6 Golden Coins, rewinding causes Mario to slide backwards without a walking animation; the timer continues to count down while rewinding, and enemies continue moving normally.  Rewinding after dying also causes all sorts of strangeness.

While attempting to capture a save state of Pokemon Silver, I noticed that the current state of the game affects the loaded state (on both RetroArch and Qt):
- Loading the state during the boot ROM causes a short buzz, then the game silently hangs on a solid pink screen.  Even after resetting, the game has lots of graphical glitches and everything uses a pink and purple palette.
- Entering a battle, opening the "PACK" menu, loading the state, then opening your pack again shows a bunch of question marks like the screenshot above.
- Entering a battle and loading the state _without_ opening any menus seems to succeed with no negative side effects.

[Pokemon - Silver Version (USA, Europe) (SGB Enhanced) (GB Compatible).zip](https://github.com/mgba-emu/mgba/files/1986800/Pokemon.-.Silver.Version.USA.Europe.SGB.Enhanced.GB.Compatible.zip)

**Comment by endrift** [comment]
Does this still reproduce?

**Comment by dobyrch** [comment]
Unfortunately yes, I just tried with the latest master (0d25e807) on RetroArch 1.7.4. I'm having trouble recording with RetroArch, but rewinding Super Mario Land 2 is the probably the easiest way to reproduce.

**Comment by endrift** [comment]
Ok, I can reproduce in SML2 but not in the SDL version.

**Comment by endrift** [comment]
Fixed in Qt version in 91eb813e564f9ddd1b60dfc371b2a6c793e46e14 and libretro in 8be2e10c877b45fad6bb6751a42e9b3d9fcf9050.

**Comment by endrift** [comment]
That's what I get for only testing on a DMG game. Please file a new bug and I'll try to find time to look into it today.
