### ISSUE TITLE
By default, GameBoy and Gameboy colour games are the wrong aspect ratio 

### ISSUE THREAD

**Issue by kurayami6** [mgba-emu/mgba#1074]
Load a game, it looks like this. 

![capture](https://user-images.githubusercontent.com/31968468/39596769-cb41d1b4-4f56-11e8-9144-e9ced8b99d44.PNG)

Changing the frame size automatically fixes it. Whatever size you change it to, it'll be the correct aspect ratio.

![capture2](https://user-images.githubusercontent.com/31968468/39596836-fe011218-4f56-11e8-8c68-42dc44797953.PNG)

Windows 7. i5. GTX 970. mGBA version 0.7-5100-82e620df

**Comment by endrift** [comment]
Does this still reproduce? It seems to be fixed for me.

**Comment by themalu866** [comment]
The problem still not fixed.
[ScreenRecorderProject1.zip](https://github.com/mgba-emu/mgba/files/2972632/ScreenRecorderProject1.zip)
