### ISSUE TITLE
3DS release download blocked by Windows Defender

### ISSUE THREAD

**Issue by Ickerday** [mgba-emu/mgba#1075]
_The build you are using_: 0.6.3
_The operating system you're using_: Windows 10 Pro
_Your CPU and graphics card (usually not necessary)_: n/a
_Browser_: Chrome (latest stable)

This issue is exclusive to the 3DS binary, all the other ones are just fine for Windows Defender:
![3ds_trojan_whut](https://user-images.githubusercontent.com/12597189/39597794-d3368b84-4f16-11e8-89d6-2f98d599541a.jpg)

@endrift If you require further details, ask and I'll do what I can, this error seems really dumb.

**Comment by endrift** [comment]
Is this still the case with the latest build?

**Comment by Ickerday** [comment]
Yeah, I'm referring to the 0.6.3 3DS release. I haven't compiled from source, so I can't tell if it's fixed yet, but I'll gladly test with all my devices if you'd be able to compile it though! :)

**Comment by Ickerday** [comment]
I checked the latest AWS build on the same PC I used to download the 0.6.3 GitHub release - the issue seems fixed apparently, no Windows Defender prompts of any sort! 👍

**Comment by JMC47** [comment]
Virus Scanners do this once in a while, the only thing to do is to submit the file to them so they can clear it.
