### ISSUE TITLE
[3DS] Warioware: Twisted lags horribly

### ISSUE THREAD

**Issue by AceAttorneyGod** [mgba-emu/mgba#1076]
Tile screen lags, games lag, menu lags...hoping for every inch of lag gone in new update. Glad to know the gyro is usable. This is on the 3DS using mGBA

**Comment by endrift** [comment]
Unfortunately this is just the 3DS being too slow. There's not much I can do here; I've tried optimizing mGBA but there's a limit to how much I can do that. Sorry.
