### ISSUE TITLE
Mortal Kombat - Tournament Edition (U) Character glitches 3ds mgba

### ISSUE THREAD

**Issue by Dodain47** [mgba-emu/mgba#1078]
I found a bug in Mortal Kombat - Tournament Edition (USA).

I checked the Wii and PC Version. This only occures in the 3DS Version V.0.6.1, 0.6.2, 0.6.3.
I didn´t check the Nightly. 
![mortal kombat - tournament edition usa en fr de es it -0](https://user-images.githubusercontent.com/32525512/39726488-7ea7a8be-524f-11e8-9eda-fdf034a6e087.png)

**Comment by endrift** [comment]
I did. It doesn't reproduce.
