### ISSUE TITLE
[Feature Request] Wii U Gamepad Support (Wii Version).

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#1079]
For WiiVC Injector on Wii U.

**Comment by endrift** [comment]
I thought I already had this. Maybe I'm not building against the right version of libogc.

**Comment by billy-acuna** [comment]
> 
> 
> I thought I already had this. Maybe I'm not building against the right version of libogc.

libogc does not include wiiu gamepad support, for it you need FIX's libwiidrc:
https://github.com/FIX94/libwiidrc

Hope you are still interested on add it

**Comment by endrift** [comment]
Yeah, I confused gamepad an pro controller support when I said that

**Comment by endrift** [comment]
Could have sworn I searched for this but this got forward-duped to #1423 by mistake, which has since been implemented for 0.9.
