### ISSUE TITLE
3DS: Sound quality

### ISSUE THREAD

**Issue by dakotaaesoph** [mgba-emu/mgba#108]
With the 3DS, the audio chip's quality is subpar, so having the sample rate at 44,100 is kind of pointless. I'd like to see if running it at 32,000 would make the sound run smoother.

**Comment by endrift** [comment]
The native sample rate of the 3DS is 32768Hz, which is the same as that of the GBA. I had a while ago tried to just feed it as-is to both ends of the resampling and ran into problems. Right now I'm using the vsync as sort of a "clock" for audio. The GBA's framerate is ~59.73fps, whereas the 3DS is ~59.83, which was leading to issues, so I'm only very slightly resampling it on both ends. Trust me, I've tried a lot of things, and verrrry slightly decreasing the expected audio rate a bit was the best approach I'd found so far. I can try tweaking it more, but the biggest hindrance at the moment is when games aren't full speed.

**Comment by dakotaaesoph** [comment]
Gotcha. Makes sense. I was thinking that the sample rate would affect the frame rate more drastically than it probably does.

**Comment by purpasmart96** [comment]
Although this might not be generally same issue, but the frame skip option is not improving the emulated speed as to be desired, it's doing practically nothing, making all the games unplayable

**Comment by endrift** [comment]
Turns out that if graphics aren't the bottleneck, then skipping frame generation doesn't help that much. It will vary from game to game. Also the O3DS is just too damn slow.

**Comment by purpasmart96** [comment]
Yeah but here is the thing, on the DSTwo the on board cpu could get better frames then this does, I mean something inst adding up... perhaps the only solution is having the sprites rendered on the gpu, which was done blargSnes I believe.

**Comment by endrift** [comment]
I landed DSP audio, which is the only thing remaining that's going to be able to improve audio quality short of huge speedups, which are out of the scope of this bug.
