### ISSUE TITLE
mGBA Freezing when Losing Focus/Go to another Program and Come Back

### ISSUE THREAD

**Issue by TradeDraft** [mgba-emu/mgba#1080]
When I go to another Program when Game Loaded up I comeback and quite often the Game Freezes up and Have to Turn it Off and Load it back up To Contunue. Happens in all Games I have Tried.

How is this be Fixed?

Tried last Offical mGBA 0.6.3 and Nightly Version from 7th

**Comment by endrift** [comment]
What OS are you on?

**Comment by TradeDraft** [comment]
I am on Windows 10

**Comment by TradeDraft** [comment]
When I play Zoids Legacy on mGBA.

When I save the Game I lose the Sounds. Not every time but nearly Every Time.

Leave on Default. Tried SDL but too much Static in the Sound Qt Multimedia loses the Sound on Save.

How can I fix this Problem?

**Comment by JMC47** [comment]
Your other issue has all the same information, so I'm closing this one.

for reference - https://github.com/mgba-emu/mgba/issues/1132
