### ISSUE TITLE
FFVI Advance - sound crackles in certain places

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#1087]
Starts in fc53fc9647353e3757a8538c01d6fd1e9a0ed3ca and last time it worked was  016e1596f7a526f1f9d6b1f13a8906aa11735693

Tested on ed99f8b9257e407a6b3a1191af4360d221d812e2 win32 and wii.
Both normal EUR rom, and the sound patch.

When loading the save, entering the town above (Kohlingen) is an easy way to hear the crackling consistently.
[Final Fantasy VI Advance.zip](https://github.com/mgba-emu/mgba/files/2040166/Final.Fantasy.VI.Advance.zip)

**Comment by endrift** [comment]
Can you see if the same commit range is what breaks Golden Sun: The Lost Age's intro music too?

**Comment by SuperrSonic** [comment]
Yeah, it starts in the same commit. I tested all the way to the first scene with the characters in the lighthouse. It was constantly crackling but a bit buried in the music, it was more apparent in the name selection screen.

**Comment by endrift** [comment]
This confirms that it's a major regression. I'll try to find some time to look into it this weekend.
