### ISSUE TITLE
pokemon gold problem

### ISSUE THREAD

**Issue by toastedbacon** [mgba-emu/mgba#1088]
i have a problem with pokemon gold it's lag when you make a command in the game for example: talking with people it lags when you press A to read more and i didn't tested in other game boy color games and also on the battle when select a command the game lag when you selected the command this is always annoying

**Comment by RafaelTrepaUnCarballo** [comment]
@toastedbacon Are you talking about the final version of Pokemon Gold or the recently leaked demo/beta?

I tested both, the first goes well, the latter lags a lot, but it does on every emulator because it's a poorly programmed beta. It's not mgba's fault.

**Comment by endrift** [comment]
Closing due to lack of additional info.
