### ISSUE TITLE
White screen on all games

### ISSUE THREAD

**Issue by smurdd** [mgba-emu/mgba#109]
After I updated to 3.0 I can no longer run any game. It just goes to a white screen with no sound. I tried changing around settings and installing and reinstalling. I am running arch.

**Comment by endrift** [comment]
What are the Audio and Display drivers in settings?

**Comment by smurdd** [comment]
Audio driver is SDL and display is OpenGL..

**Comment by endrift** [comment]
Have you tried deleting or moving your settings file? It's in `~/.config/mgba`.

**Comment by smurdd** [comment]
Oh, yea that fixed it. I forgot to try that.

**Comment by endrift** [comment]
If you still have the old file, I'm kinda curious what in it is what broke, but otherwise don't worry about it.

**Comment by smurdd** [comment]
Sorry I already deleted it.

**Comment by shubhakarv** [comment]
i have the same problem, could u please tell me where i can find the settings file

**Comment by endrift** [comment]
On Linux: ~/.config/mgba/config.ini
On Windows: %APPDATA%/mGBA/config.ini

**Comment by Animepurush** [comment]
I have same problem i try moving file but it does not work.
how you solved your problem?

**Comment by Testsr** [comment]
Send the config file.

**Comment by Animepurush** [comment]
![Screenshot 2022-10-12 095854](https://user-images.githubusercontent.com/115605623/195250391-6b333ba3-1f54-40d7-a6c1-a04589d8f7fe.png)
