### ISSUE TITLE
mGBA can't run Pokemon Gold Spaceworld 1997 Demo (Debug).sgb

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#1097]
The game freezes in a white screen. The log shows this message:

**Hit illegal opcode at address 4006:F4**

This rom can't be executed on bgb either, but VBA-M can emulate it.

**Comment by GerbilSoft** [comment]
Have you fixed the ROM header to have the correct mapper type? $147 in the released ROM is set to $03 (MBC1+RAM+BATT), but the actual cartridge has mapper $10 (MBC3+TIMER+RAM+BATT). [or it might be $13, MBC3+RAM+BATT; not sure if the RTC was in use at this point]

**Comment by fancymelonub** [comment]
There is a Header Fixed version in the 7z file. Use that.
