### ISSUE TITLE
Class QAction error when trying to compile

### ISSUE THREAD

**Issue by johnny-mac** [mgba-emu/mgba#1100]
Hello, I am getting errors about Class QAction when trying to compile Medusa-emu.
It was git-cloned from master

Running Artix Linux & Void Linux MUSL, this is the output from Artix, I'll let you know if I encounter the same errors in Void.

Build output:
https://pastebin.com/h2g1vjvC

PKGBUILD:
https://pastebin.com/JDt1MBQv

**Comment by endrift** [comment]
Please cherry-pick 7f41dd354176b720c8e3310553c6b772278b9dca.

**Comment by johnny-mac** [comment]
But this is with the latest git clone? Sorry I forgot to mention that originally, I editted it in right after.. you reply fast.

**Comment by endrift** [comment]
Yeah, I haven't updated that branch yet.

**Comment by johnny-mac** [comment]
Ohh ok, when do you think it'll be updated?

**Comment by endrift** [comment]
Don't know. I want to do more of the input revamp first. In the meantime the pkgbuild should be updated with that patch.

**Comment by johnny-mac** [comment]
Oh my bad, I messed it up then, the description is probably copied from medusa-emu-fresh because I just copy the most similar PKGBUILD and then make the necessary changes. Its one of the first PKGBUILDs I've ever made all by myself.

**Comment by endrift** [comment]
Should have been fixed by a2b8c4ae807ae92103e14961fd34377b28cbe219

**Comment by johnny-mac** [comment]
I tried applying the fixes in that commit, but its still giving me the same error when building..
