### ISSUE TITLE
Losing Sound and Sometimes Crashes when Saving

### ISSUE THREAD

**Issue by TradeDraft** [mgba-emu/mgba#1101]
Found Recently that when I save a Game sometimes it Loses Sounds and even Freezing

Bit Annoying but hopefully something easily fixed

Using Windows 10

**Comment by endrift** [comment]
Which version of mGBA are you using?

**Comment by TradeDraft** [comment]
0.6.3 Version

**Comment by TradeDraft** [comment]
Tried the Latest Version with Pokemon Sapphire when I leave a Dungon and then it just Freezes just after I leave it

**Comment by JMC47** [comment]
Are you sure that you're using a properly dumped ROM?  If Pokemon Sapphire were failing like this, I'm pretty sure there would be more issues reported.

**Comment by TradeDraft** [comment]
I used from No-Intro Packs

**Comment by endrift** [comment]
When you say crashing do you mean the game or mGBA itself?

**Comment by TradeDraft** [comment]
When I save it just locks up. Not Sure if Rom or Emulator

**Comment by TradeDraft** [comment]
Think I have found the Solution.

https://i.postimg.cc/sg63Vh74/m_GBA_Sound_Fix.jpg
