### ISSUE TITLE
[GBA] Multiplayer Frezees

### ISSUE THREAD

**Issue by Nzecro** [mgba-emu/mgba#1102]
When i start a new multiplayer window and load a ROM it give a white screen then i try to fix it now it give me a black screen how can i fix it? the current version that I'm using is 0.6.1 please help me fix it
![capture](https://user-images.githubusercontent.com/40139925/41200928-35617b20-6ce0-11e8-9245-83c0931e6321.PNG)

**Comment by fancymelonub** [comment]
Try using 0.6.3 or the latest dev version and see if it fixes your problem.

**Comment by Kerman** [comment]
turning off audio and video sync fixed the "white screen" issue for me

**Comment by JMC47** [comment]
It sounds like you're just in general having problems setting up multiplayer.  I recommend looking up some guides - as I setup a bunch of multiplayer games for a get-together using mGBA and only experienced freezing when I connected things incorrectly.

**Comment by furrytwat** [comment]
I was having the same issue and I actually found a way to make it work without touching any settings.

When you open the second window and it gets stuck at a white or black screen, go back to the first window and go downstairs with your character, then the second window continues normally.

**Comment by endrift** [comment]
This is stale and was never retested. A lot has changed so it probably doesn't reproduce, at least as is.
