### ISSUE TITLE
3DS: Displays all files other than just ROMs

### ISSUE THREAD

**Issue by Alex4nder001** [mgba-emu/mgba#1103]
It's really annoying for me that it takes forever to scroll through my folder with my roms in it, because in the file browser it shows all my roms, plus all the saves, states, BIOS files and other junk (so the file list is three times as big as it should be). Can you make the file browser just display .gba/.gbc/.gb files only please
Alternatively, make it so that files I make hidden in Windows won't show up

**Comment by endrift** [comment]
It now blacklists .ss*, .sav, .png, .ini. I may change it to a whitelist eventually.
