### ISSUE TITLE
Super Game Boy enhancement not working for Pokemon Yellow.

### ISSUE THREAD

**Issue by bslenul** [mgba-emu/mgba#1104]
Hey!

* Pokemon Yellow seems to be the only Game Boy game with both Game Boy Color AND Super Game Boy enhancements.
* GBC enhancement works fine as you can see on the screen below, SGB enhancement however doesnt work and that's the issue.
* With `Game Boy Color model` set to `Autodetect` in the settings no problem, the game runs like a GBC game:

![pokemon - yellow version - special pikachu edition usa europe gbc sgb enhanced -180619-000655](https://user-images.githubusercontent.com/33353403/41564986-14c2acd8-7355-11e8-9373-55b6627b8c8a.png)

(same behavior with the option set to `Game Boy Color` or `Game Boy Advance`)
* With the option set to `Game Boy` again no problem the game runs like a GB game:

![pokemon - yellow version - special pikachu edition usa europe gbc sgb enhanced -180619-000729](https://user-images.githubusercontent.com/33353403/41565030-4547f50c-7355-11e8-96d1-7b1962d16b9c.png)

* But with the option set to `Super Game Boy`, instead of having colors and SGB borders [**like this**](http://i47.tinypic.com/vziw02.png), the game is in black and white and borders are white:

![pokemon - yellow version - special pikachu edition usa europe gbc sgb enhanced -180619-000802](https://user-images.githubusercontent.com/33353403/41565085-7d4bb89e-7355-11e8-8370-cd9253f2a791.png)

* SGB enhancement works perfectly fine on other games like Pokemon Red/Blue. I guess this is because of the GBC enhancement of Yellow?

![pokemon - red version usa europe sgb enhanced -180619-005305](https://user-images.githubusercontent.com/33353403/41568922-e3c4a8c0-7368-11e8-847f-1499bfcbdbe5.png)

Screens taken from RetroArch but results are the same with `mGBA-build-2018-06-03-win32-5135-f8759a8760f4af6bd12188beeae82fb4e2ea5585` on Windows 10.

**Comment by endrift** [comment]
Hmm, seems to work fine with the SDL port. Looking into the Qt one now.

**Comment by endrift** [comment]
Seems like Pokémon Yellow asks for 2-controller mode, then increments which controller it's asking for 8 times (which goes back to the first controller) and since it sees it's the first controller again assumes it's not a SGB...

**Comment by endrift** [comment]
I think this might be a timing issue. I think it swaps the controller every frame, but it takes too many frames and winds up being an even number of frames (8) instead of an odd number (5 in BGB unless I miscounted).

**Comment by MapleStoryPSN** [comment]
Bumping this up just to point out that the base Japanese rom (Pocket Monsters: Pikachu) has no trouble whatsoever with Super Game Boy enhancements. Borders and color work perfectly. It seems that every revision and regional release that followed is affected by the bug.

**Comment by CharlesCorrin** [comment]
MapleStoryPSN, that could have something to do with the first Japanese version having no Game Boy Color support.

Pokemon Yellow was sold as a regular Game Boy game in all regions. But it had Game Boy Color features anyway. The first Japanese version was older, seemingly too early to get the GBC features. They added the GBC support in the 1.1 version. All other regional versions were based on the Japanese 1.1 or newer. This makes me think the problem might have SOMETHING to do with the GBC support. But I'm certainly no expert.

There's a byte/some bytes in the header that tells the GBC when the game has GBC support, but I don't remember where.

**Comment by endrift** [comment]
No, I don't think that's related. Though I'm not sure what the problem is yet.

**Comment by rodrigoomuller** [comment]
Any new development on this issue? I noticed the same thing yesterday. Some Tetris game has the same problem, I believe Tetris 2.a

**Comment by ISSOtm** [comment]
[This is the relevant code](https://github.com/pret/pokeyellow/blob/67229ff7571f7216d899f81b5cacd55d476cd6f6/engine/palettes.asm#L610-L656), which is identical to the code in Pokémon Red except for the sending of the MLT_REQ packets, which are shielded by `di` in Red. (Yellow sets the variable that prevents joypad polling in the caller function instead.)
