### ISSUE TITLE
[GBA] Chu Chu Rocket! and Cable Link Issues blocking Single Player modes.

### ISSUE THREAD

**Issue by Maesejesus** [mgba-emu/mgba#1105]
Hello. I'd like to report a problem. I'm using the Wii version of a 0.6.3 nightly.

In Chu Chu Rocket, there are two Multiplayer Modes, called Battle and Team Battle. You can choose to "Start Immediately" or "Start after set up". The last one lets you change options and customize matches, the first one throws you directly to a match.

The normal behavior of the game is that it would let you play those modes with CPUs no problem when you didn't have a Cable Link connected. But running the game on mGBA, the game thinks there's a Cable Link connected, and will try to connect to another non-existent system; **blocking** you completely from being able to play these modes in Single Player, no matter the option you choose or what you try.

The simple steps to reproduce this problem are:
Run the game (If it's the first time you run it, a SRAM file will be created (you also need to choose a language).
Let the splash screens come and go and press Start.
Choose one of the two Multiplayer modes, and any of the two options there to start a game.
The Connection Error appears.

After looking around, I found out that this seems like an issue that has existed for a very, very long on Visual Boy Advance too. Does this mean it has no solution possible? I would understand it, although it would be incredibly sad too, as it is a rather important part of the game. 

I haven't found this issue in any other title I tried before.

**Comment by endrift** [comment]
Fixed.

**Comment by Maesejesus** [comment]
** Already?! Woah, You're great!**
I thought it would be something hard to do, seeing how long this has been existing on VBA.
Thank you so much, Endrift.

**Comment by endrift** [comment]
Reopening because my fix was incorrect.

**Comment by endrift** [comment]
Hm, I thought I reverted that change. Regardless, it's definitely working now.
