### ISSUE TITLE
[Wii] unable to change aspect ratio in config.ini file

### ISSUE THREAD

**Issue by WaffleJames** [mgba-emu/mgba#1106]
Before I was able to put "stretchHeight" or "stretchWidth" under [ports.wii] in the config.ini file to change the aspect ratio to my liking, and now it is not possible to do this. The emulator just defaults at some gross aspect ratio when any value is put after the stretchHeight or stretchWidth. I would like this fixed so I can play at perfect 3:2 aspect ratio again

**Comment by SuperrSonic** [comment]
dc753d8 first broken nightly
c8dacbb last working

There are two Wii commits in-between.

**Comment by WaffleJames** [comment]
Will this be fixed in 0.7.0? Because this feature was what made mgba my favorite emulator on the Wii.
Also is there a page to view all the commits? Thank you

**Comment by WaffleJames** [comment]
Nevermind on the list. I found the list of nightlies.
What do you mean two commits in-between?

**Comment by SuperrSonic** [comment]
Because the first nightly broken has nothing to do with the Wii port, but two commits before it are Wii related. It was a minor side note.

Posting which commit breaks it might help get it fixed depending on the issue.

**Comment by endrift** [comment]
That's odd, the two Wii commits are just build fixes. Might be a dkPPC regression.

**Comment by endrift** [comment]
Which screen mode are you using? Pixel accurate?

**Comment by WaffleJames** [comment]
I’m using stretched, pixel accurate isn’t affected by the stretchWidth/stretchHeight in the config.ini file.

**Comment by endrift** [comment]
Yes, you're correct. In Dolphin it still seems to work as intended, so I might have to break out my actual Wii.

**Comment by WaffleJames** [comment]
I haven’t tested the most recent nightly from today, but it’s not working on my Wii in 0.6.3 and the last nightly from yesterday.
