### ISSUE TITLE
Audio channels not always cut off on rewind

### ISSUE THREAD

**Issue by NarryG** [mgba-emu/mgba#1107]
In certain games (Mario & Luigi Superstar Saga being the example I have), it appears that rewind isn't properly cutting off certain audio channels.

This issue exists in both the 0.6.x branch (including 0.6.3 stable) as well as the 0.7.x branch

Here's a clip demonstrating the issue:
https://streamable.com/muc4b

**Comment by endrift** [comment]
Can reproduce. Channel 3 is the faulty one here.

**Comment by NarryG** [comment]
Could this be backported to 0.6.X so it can be merged into Bizhawk?

**Comment by endrift** [comment]
Yup, though hopefully 0.7 comes out soon so they can adopt it.

**Comment by endrift** [comment]
Done.
