### ISSUE TITLE
[GBC] mgba can't play demo video on the homebrew gbvideoplayer

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#1113]
I found a video player for GBC. The author included the Pokemon anime intro as a demo/test of his homebrew.

It runs flawlessly on bgb, Higan 0.97 and SameBoy, but it can't be played on mgba.

Demo:
https://github.com/LIJI32/GBVideoPlayer/releases
Info:
https://github.com/LIJI32/GBVideoPlayer
On a real GBC:
https://www.youtube.com/watch?v=c5HfmaDCVsY

**Comment by endrift** [comment]
Looks like most of the issues are that audio is missing and that the leftmost pixel is wrong?

**Comment by endrift** [comment]
Fixed with some guidance from LIJI.
