### ISSUE TITLE
Emulation should continue normally after the debugger console is closed

### ISSUE THREAD

**Issue by eToThePi-i** [mgba-emu/mgba#1116]
When the debugger console is opened (```Tools > Open debugger console...```), the emulator continues to run as normal. But once the ```help``` command is run, the emulation pauses. This makes sense, but what doesn't make sense is that the emulation doesn't resume normally once the debugger is closed.

Even though one can continue command execution using the ```continue``` command, it should unpause when the debugger console is closed, or at the very least allow unpausing using the standard ```ctrl-p``` shortcut.

I'm running Windows 8.1.

**Comment by endrift** [comment]
The command is called `continue`

**Comment by eToThePi-i** [comment]
@endrift I think you may have read the original issue text, but missed the revision. I realized the ```continue``` would do what I'm after, but it still seems like a bit of unexpected behavior to not reallow pausing when the debugger console is closed.

I think the more general issue is that the behavior between the debugger console and the general emulator is not well forecasted to the unfamiliar user. When I was first messing around, I tried to doing the normal ```ctrl-n``` and ```ctrl-p``` navigation after closing the debuggerto no avail. Maybe instead of my original suggestion, the emulator could instead broadcast a message saying "Frame advance is not allowed while execution is paused. Use ```continue``` to unpause execution." (or some variation) when unavailable keyboard shortcuts are used.

But honestly, reconsidering, it's probably not that worthwhile to work on it unless you get a real itch to; it's only really a minor issue after all, and it's more about user confusion than about something not working. It seems like this would require some restructuring of overall emulator command listening routines, which might not be worth the effort to modify. Then again, a reexamination of the relationship between the debugger console and emulator may be useful at some point.

**Comment by endrift** [comment]
I'm not sure you noticed that I deleted my comment after I noticed that the text had been updated 😛 That said, the debugger console is probably going away in 0.7 since I'm working on the actual debugger UI now.

**Comment by eToThePi-i** [comment]
Oh well. I was drafting my comment when you deleted it, and didn't bother to reload before posting.

I think a debugger UI would be great.

**Comment by eToThePi-i** [comment]
@endrift Could you close this so I could merge this with my debugger console master list? Or would you prefer to keep this as a separate issue? (I assume you don't want the issues split out more, since it's probably useful to have all the suggestions in one place for the in-development UI.)

**Comment by endrift** [comment]
I actually do want things split out (for this at least) so I can close them one by one. Not sure what to do with this one though.

**Comment by endrift** [comment]
I didn't notice yet that you'd made a master issue, which included this though. I guess I can close this.

**Comment by eToThePi-i** [comment]
Do you still want me to split them out? Obviously, some of them may become obsolete if you eschew keeping the debug console, but I do believe about half of them are relevant to the UI version.

Does the checklist have enough ease for partial issue fix commits?

**Comment by endrift** [comment]
So, many of them apply to the SDL debugger too (which was just kinda crammed into the Qt version), but not all of them, so I want to keep the list even if I remove it from the Qt version. The thing is, not all of them I plan to do. But we'll see.

**Comment by eToThePi-i** [comment]
Apologies for my unfamiliarity, but what does SDL stand for (or what is it)?

**Comment by endrift** [comment]
Yup, the SDL version is a simple frontend meant for things where you don't need or want the full UI. You can pass -d to get the same debugger that's in the debug console.
