### ISSUE TITLE
Supplementary files are erroniously empty

### ISSUE THREAD

**Issue by eToThePi-i** [mgba-emu/mgba#1119]
Some of the files in my mGBA 0.6.3 folder seem to erroneously empty. To ensure I hadn't accidentally deleted the file contents, I redownloaded the Windows 0.6.3 (32 bit and 64 bit) ```.7z```s, and they still have the problems I list below.

```CHANGES.txt```:

[empty]

```README.html```:

```
<meta charset="UTF-8">


```

```README_DE.html```:

```
<meta charset="UTF-8">


```

**Comment by endrift** [comment]
This has already been fixed in future builds, but won't be fixed for 0.6.3.

**Comment by eToThePi-i** [comment]
Oh, sorry, I should have checked the development build. I'll just update from there.
