### ISSUE TITLE
File list doesn't show last item.

### ISSUE THREAD

**Issue by FayneAldan** [mgba-emu/mgba#112]
It's all in the title. I'm using the nightly 3DS version.

**Comment by FayneAldan** [comment]
This bug seems to be present in alpha 1 as well.

**Comment by FayneAldan** [comment]
And then I notice the files aren't in alphabetical order...

**Comment by endrift** [comment]
They should be, I definitely sort them. But it's a case-sensitive sort so uppercase will come before lowercase.

**Comment by FayneAldan** [comment]
Yup. That would explain it.

**Comment by endrift** [comment]
I'll fix this for the next nightly.
