### ISSUE TITLE
[3DS] Stuck on Loading Rom

### ISSUE THREAD

**Issue by redpigbird** [mgba-emu/mgba#1121]
Installed the cia file of newest version. App seems to load fine, but when I attempt to load a rom file (.gba or .gbc) it just says "Loading" and never finishes.

I am using an old 3ds with Gateway Emunand 11.7U

**Comment by morrae** [comment]
Having the same issue

**Comment by endrift** [comment]
Is this still an issue with the latest dev builds?

**Comment by endrift** [comment]
Closing due to lack of reply. Will reopen if more info is provided.
