### ISSUE TITLE
[GBA] Volume of audio channels changes frequently

### ISSUE THREAD

**Issue by LimitCrown** [mgba-emu/mgba#1122]
Compared to mGBA 0.6.3, the development build's volume for GBA games seems to frequently change in an odd way, causing some of the audio channels to sound louder than usual in comparison for brief moments. This can be noticed in games like the Sonic Advance games.

Also, the following is probably unrelated to this issue, but the fps counter in the development build indicates that the fps is hovering around 65.6 fps even though I have the target fps set to the native amount.

**Comment by endrift** [comment]
I've changed a lot of audio stuff recently, please retest on 0.7 b1 or newer.

**Comment by endrift** [comment]
Old issue, closing due to lack of reply. Will reopen if it's still present.
