### ISSUE TITLE
[GBA][VITA][PSP2] Save file not serialized when mGBA is terminated by launching another app.

### ISSUE THREAD

**Issue by r0bbyboy** [mgba-emu/mgba#1123]
Rom: Aria of Sorrow (US)
Platform: Vita 0.6.3

I had been playing for several hours without quitting mGBA (I did suspend the Vita several times in that time) and had saved and reloaded many times (after dying and returning to main menu but without unloading the rom). After about 4 hours in game I returned to the Vita OS and booted another application which prompted me with the "The following application will close." warning. Since my game was back on the main menu I went ahead and confirmed the warning and let mGBA be closed. After booting mGBA later I found that my save file had reverted to a much much earlier state. My assumption is that it was the state from before my previous session. I have repeated similar steps but have yet to reproduce the bug so I'm not 100% sure what caused the issue but closing by launching another application was the only thing I could think of that might have caused the issue.

**Comment by anilanar** [comment]
Can confirm that if mGba crashes, save files are not flushed.
