### ISSUE TITLE
Metroid Zero Mission: Glitchy HUD when using Power Bombs

### ISSUE THREAD

**Issue by Ckosmick** [mgba-emu/mgba#1126]
![1370 - metroid - zero mission u](https://user-images.githubusercontent.com/11250976/42604801-34087efa-853a-11e8-8603-d8e0eb711b43.gif)

When a power bomb passes through the HUD it temporarily messes it up. This happens on mGBA with OpenGL, Bizhawk using mGBA core with D3D, but not on VBA. I have confirmation this happens on all renderers and is not a windows-specific issue.

**Comment by CharlesCorrin** [comment]
Could you please supply a save file or save state to that point? One of those might help Endrift fix the problem faster. :3

**Comment by endrift** [comment]
It seems to be scanlines 1-5 have OBJ disabled inside of WIN1, but none of the other scanlines (0, 6-159). Very strange.
