### ISSUE TITLE
[Bug] Games don't start paused if the emulator is paused.

### ISSUE THREAD

**Issue by eToThePi-i** [mgba-emu/mgba#1129]
If the emulator is paused when a game is started (i.e. retaining the pause from a previous running game), the emulator doesn't recognize that it's paused immediately. The emulator registers the pause only after clicking the file menu.

The preferable expected behavior is that the game execution will start paused because the user has to _explicitly_ activate pause for the emulator to be paused (i.e. the emulator can't start in a paused state on its own).  Less preferable but still consistent would be for the emulator to always unpause when starting a game.

**Comment by endrift** [comment]
The emulator can't be paused when a game is started; the option is disabled. How are you toggling that?

**Comment by eToThePi-i** [comment]
It's paused from exiting a game paused. I can record a video if you want.

**Comment by endrift** [comment]
That sounds like the actual bug, though starting paused would be a good feature

**Comment by eToThePi-i** [comment]
Sorry for not describing the occurrence conditions more clearly, I'll edit the original post.

**Comment by endrift** [comment]
Fixed in 2f5624e74ac94b7065b10568c1f6378d3d1bc4a4
