### ISSUE TITLE
3DS: Scaling should be improved

### ISSUE THREAD

**Issue by FayneAldan** [mgba-emu/mgba#113]

**Comment by endrift** [comment]
Can't be done while keeping sf2dlib. I want to dump sf2dlib so that shouldn't be a problem, but for now it's not a thing that I can fix. Trust me, I'm well aware of this issue.

**Comment by FayneAldan** [comment]
That wouldn't happen to be what xerpi/sf2dlib@6e06a59161faa9063c299a32ba0b2aa86bc82bad was for, would it...?

**Comment by endrift** [comment]
Nope, that was for initializing the memory in the first place, not for the scaling filter. I'd have to add another PR for that.

**Comment by endrift** [comment]
This will be taken care of when #120 gets merged.

**Comment by endrift** [comment]
#120 has been merged.
