### ISSUE TITLE
Donkey Kong Country GBC (UE) game freezes at the exit of the first mine cart level.

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#1131]
Donkey Kong Country GBC (UE) game freezes at the exit of the first mine cart level.

I used the nightly mGBA-build-2018-07-14-wii-5175-d571d8921fed313733803973629780633e3d5774
for the Nintendo Wii.

Attached the save state and a picture.

[Donkey Kong Country (USA, Europe) (En,Fr,De,Es,It).zip](https://github.com/mgba-emu/mgba/files/2196229/Donkey.Kong.Country.USA.Europe.En.Fr.De.Es.It.zip)

![donkey kong country usa europe en fr de es it -0](https://user-images.githubusercontent.com/32525512/42739423-68a07e00-8897-11e8-9c0e-1487523f3d6a.png)

**Comment by JMC47** [comment]
Can confirm the game freezes from your savestate on Windows 10, latest mGBA nightly.

**Comment by endrift** [comment]
I can't reproduce this from save, only from savestate.

**Comment by endrift** [comment]
I can't even reproduce it from that specific version.

**Comment by Dodain47** [comment]
I retested Donkey Kong Country with the 0.7.1 beta for the Nintendo Wii. 
I can´t recreate the issue aswell. Maybe this already got fixed?
