### ISSUE TITLE
[3DS] Unable to access config/settings

### ISSUE THREAD

**Issue by Dial0118999** [mgba-emu/mgba#1133]
Is it at all possible to access the config on the 3ds .cia version (0.6.3)? The display scale is off by quite a bit and I would like to fix it.
Whatever button combination it may be, I simply can't work out how to access the settings/config. Or do you have to modify a file on the SD card or something like that?

**Comment by endrift** [comment]
It should just be X.

**Comment by canitzp** [comment]
When I press X on my new 3ds xl while I'm in the choose a game menu then mGBA crashes back to the 3ds home menu. I just downloaded the newest version

**Comment by ajs91** [comment]
Having the same issue as canitzp. Are there any workarounds for this? Or does anyone know the latest build where the config menu works?

**Comment by endrift** [comment]
You can only access the config in-game. If you hit X when you're on the menu it exits (not crashing).

**Comment by ajs91** [comment]
Cool, feel dumb now. Thanks for the quick response!

**Comment by goldeneyeonline** [comment]
Haha, just had the same problem xD thanks for this thread :-)
