### ISSUE TITLE
mGBA Wii FPS going crazy!

### ISSUE THREAD

**Issue by fancymelonub** [mgba-emu/mgba#1135]
The FPS counter on mGBA Wii was going crazy. It's always shows: Under 1 FPS, Few Hundred, Thousands maybe even millions! And the time thing on the ROM selection screen is also crazy. I'm using the latest dev build. It's possible this happened because my mGBA is on a USB instead of SD.

**Comment by endrift** [comment]
I think this might be an issue with libogc/devkitPPC. I wasn't seeing this until I upgraded sometime recently. @WinterMute, any idea if time stuff may be broken in latest?

**Comment by endrift** [comment]
This should be fixed now. It was a libogc bug that I've fixed downstream and filed a PR for.

**Comment by fancymelonub** [comment]
Cool, thanks!
