### ISSUE TITLE
Savestate handling could be improved.

### ISSUE THREAD

**Issue by eToThePi-i** [mgba-emu/mgba#1136]
I can move them these into separate issues if that would be preferable.

- [x] Cancelling from `File > Load state` and `File > Save state` is impossible (aside from completely exiting the emulator). Preferably, this would respond to the `Esc` key at the very least, and at its best have an explicit cancel button.
- [x] Arbitrary state "Save state...", "Load state..." does not appear to be possible from within the emulator. This forces outside file management, which is annoying and slows things down if you want to have more than 9 saved states.

Also, I was wondering if the save state format the emulator uses is documented anywhere (aside from the actual code that implements it). Specifically, I was curious if the code included a ROM hash value checksum, and where that might be in the output file. As far as I can figure from my loose search, the code for saving states is stored in [`mCoreSaveStateNamed()`](https://github.com/mgba-emu/mgba/blob/master/src/core/serialize.c#L302), but I'm not well-versed enough to figure out if/where a hash value might be in the file.

**Comment by endrift** [comment]
The former should be possible. I think there's a bug if a state isn't in focus though.

**Comment by endrift** [comment]
The former was fixed a few days ago.
