### ISSUE TITLE
[Qt] Tile view usability enhancements

### ISSUE THREAD

**Issue by eToThePi-i** [mgba-emu/mgba#1139]
- [x] `paletteId` should use `QSpinBox` instead of  `QSlider`. `QSlider` functions sluggishly and is completely unlabelled, making it difficult to choose a specific palette Id.
  - [Code location](https://github.com/mgba-emu/mgba/blob/c04d627de8471939afd395c737181f52241df08d/src/platform/qt/TileView.ui#L24-L58) (I could probably write a patch myself, but I'm unfamiliar with Qt and don't have the necessary programs installed.)
- [x] Map view width should be an option somewhere. Specifically what I have in mind is the ability to match the tiles to 2D tile mapping mode, *even at different zoom levels*.
  - Perhaps more sophisticated would be to check bit 6 of `DISPCNT` for the mapping mode and then adjust the UI accordingly if 2D tile mapping is enabled.
  - And it doesn't even have to make the window default wider; one could just add a scrollbar.
- [ ] For a more advanced experimental feature, a "palette map" might be useful. This would be a way of mapping a specific range of tiles to a specific palette, and then saving it to a file. Then one could view all tiles in the preferred palette without. This is kind of niche, and of limited use though, but it is an interesting idea.

**Comment by endrift** [comment]
I'm not planning on doing the third one.
