### ISSUE TITLE
[Bug] Repeatedly pressing keyboard shortcuts causes unresponsiveness.

### ISSUE THREAD

**Issue by RetroEdit** [mgba-emu/mgba#1140]
For example, I was pressing `ctrl-n` to frame advance continually. After about 60-120 presses, the emulator stopped responding to the keyboard shortcuts. Neither `ctrl-p` or `ctrl-n` would work, and even using the interface file menu buttons (`Emulation > Pause`, `Emulation > Next frame`) didn't work.

I only know about this bug in the context of pausing and frame advances. I *was* able to successfully reset the emulator using the interface reset (`Emulation > Reset`). The emulator has been open for a few hours, so there might be some caching issues at work.

**Comment by endrift** [comment]
What OS is this on? I know this used to be a problem on macOS but I thought that got fixed.

**Comment by eToThePi-i** [comment]
@endrift Windows 8.1. Sorry for the late reply. I haven't tested on 0.7.0 yet, though, so it might have been fixed; hopefully I'll be able to get around to testing it soon.

**Comment by RetroEdit** [comment]
This issue has gotten close to a year old, and I completely forgot about it. Does it still require further testing to see if it's in new versions? (I assume so). I can probably get around to testing it fairly soon if so.

**Comment by endrift** [comment]
Please retest in latest master.

**Comment by RetroEdit** [comment]
Retested in 0.6.3 to verify my original bug report, and that worked.

Tested in 0.9.0 and b6e5b6e, but I didn't notice the same bug.
