### ISSUE TITLE
Sound issue in PCM channel

### ISSUE THREAD

**Issue by retro-wertz** [mgba-emu/mgba#1142]
Only tested with a GBC game, in particular Bio Hazard/Resident Evil Gaiden.

Problem is that the volume during the part where is says "Resident Evil" (of "Bio Hazard on the J version) is very loud compared to other channels. Using the Audio channels option to isolate which channel this comes from has no effect since even with all 4 channels off, this voice sample is still heard(doesn't seem to be hooked up to any channel on/off option).

the comparison of the volume is based on video samples on youtube etc.

manually compiled:
Commit: f888d9b
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

**Comment by endrift** [comment]
The GBC does not have a PCM channel, so I'm a bit confused.

**Comment by endrift** [comment]
Here's a comparison with it on hardware: https://www.youtube.com/watch?v=vRTll7JqV2U

**Comment by retro-wertz** [comment]
(those guys on the vid are so annoyinglu loud, so the voice sample during when it says "resident evil" is not heard.

not a gb /gbc expect here. so its probably wave channel or channel 3 (at least on some emu that can disable the 4 channels.)

here is a better sample (not sure if this is from an actual hardware) skip to 0:22 where it would say resident evil when showing the title screen.

https://www.youtube.com/watch?v=jIVwXBvMdNk&t=34s

**Comment by endrift** [comment]
Yeah sorry it was the only obviously-hardware video I could find.

The trick it's doing is a little weird because it doesn't involve ANY of the sound channels--it's messing with audio artifacting caused by changing the volume rapidly, even when nothing is playing.
