### ISSUE TITLE
Harry Potter and the Philosopher's Stone (GBC): Can't start flying minigames

### ISSUE THREAD

**Issue by Miss-Inputs** [mgba-emu/mgba#1144]
mGBA version: 0.7-5186-575adcaf
OS: Antergos Linux
CPU/GPU: Intel i7-3720QM @ 2.6GHz, integrated Ivy Bridge graphics
ROM CRC32: 4fd8b7c5 `Harry Potter and the Sorcerer's Stone (USA, Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da,Fi)`

From the title screen, selecting "Bonus Games" and then one of the following hangs with a white screen (the sound also seems to hang):
- Race Draco to get back Neville's Remembrall!
- Norbert has escaped! Race to retrieve him!
- See if you can catch the owl!

What's interesting is that these three are all the same kind of minigame where you fly on a broom with horizontal scrolling. What's perhaps also interesting is "Find the correct key to unlock the door!" does work fine, and that does involve a broom (although it's not the same kind of minigame as those three).

The main game does load fine. I haven't yet tried playing through the story up to the point where those minigames would happen, though I do have a save file that has those minigames unlocked.

I'm tired so feel free to tell me off if I missed any details.

**Comment by Zowayix** [comment]
Okay, so for whatever reason, the "Race Draco to get back Neville's Remembrall!" minigame _does_ work when you get to that point in the main game.

I've attached a savestate just before that minigame starts, and a save file with all the minigames unlocked from the main menu (if you select Load Game and pick slot 1, it'll also be just before the point where that minigame would start).

Savestate: ![harry potter and the philosopher s stone usa europe en fr de es it nl pt sv no da fi](https://user-images.githubusercontent.com/31366697/43366911-118b4f18-9388-11e8-8d06-8e5f8da0dd66.png)

Save file: ![harry potter and the philosopher s stone usa europe en fr de es it nl pt sv no da fi save](https://user-images.githubusercontent.com/31366697/43366929-47e86eb0-9388-11e8-99af-414d5bc28552.png)

**Comment by endrift** [comment]
Seems to work for me. I'm going to assume it got fixed at some point and I never checked, but if you can confirm otherwise I'll reopen.
