### ISSUE TITLE
No win 64bits build on front site

### ISSUE THREAD

**Issue by Catarax** [mgba-emu/mgba#1145]
I have to change dl url from 32 to 64 to get that kind of build, I wonder why it's not listed :

https://mgba.io/downloads.html
https://github.com/mgba-emu/mgba/releases/download/0.6.3/mGBA-0.6.3-win64.7z

**Comment by endrift** [comment]
It's not listed because there's no advantage to it. The only reason it exists in the first place is for medusa, where there is an advantage.
