### ISSUE TITLE
How to compile for 3ds

### ISSUE THREAD

**Issue by TheCoder3156** [mgba-emu/mgba#1146]
I would like to know how to compile for the 3ds. I tried using `cmake -D 3DS:BOOL=ON ..
` in the build directory and then `make` but I eventually got a build error. I do have devkitARM with all the  3ds libraries so it should be able to compile.

**Comment by endrift** [comment]
`cmake .. -DCMAKE_TOOLCHAIN_FILE=../src/platform/3ds/CMakeToolchain.txt`

this is not a support forum, it's a bug tracker.
