### ISSUE TITLE
Getting a Jumped to invalid address: 09FE209C error while playing rom.

### ISSUE THREAD

**Issue by Fuey42** [mgba-emu/mgba#1148]
I am trying to to play the Nameless Fire Red Rom. The game work on vba-(m) emulator but for some reason that emulator has massive frame drops and de sync problems on my mac. Usually after starting up the rom on mGBA the game crashes right before professor Oak is supposed to show up and set you on your journey, so I get the title screen and everything.

 I got the game working but loading a .sav file that I had from the other emulator but during the first battle the game crashes giving me the Jumped to invalid address: 09FE209C error. Any help would be appreciated.

**Comment by endrift** [comment]
Please upload the save file.

FWIW unless they've updated it recently the intro cutscene is broken on hardware too.

**Comment by JMC47** [comment]
Have you tested this on a real GBA via a flashcart or something?  Romhacks are prone to have issues and many are only tested on emulators.

**Comment by justinmedoka** [comment]
I have been suffering from the same issue. I'm trying to play Mega Man and Bass, but the game keeps crashing and saying "jumped to an invalid address: ********" (the address is different every time. What should I do? The ROM is the original dump.

**Comment by maluhia** [comment]
I had this issue with my ROM hack. traced the issue to a bug in NLZ-GBA. When inserting tilesets and tilemaps, it must corrupt the rom a bit somehow. I solved it by reinserting the tilesets and tilemaps in unLZ and it worked.

**Comment by endrift** [comment]
Closing due to lack of reply.

**Comment by subad31155** [comment]
> Please upload the save file.
> 
> FWIW unless they've updated it recently the intro cutscene is broken on hardware too.

And now i can see if it was saving works?
