### ISSUE TITLE
CPU usage spikes when sensors window open

### ISSUE THREAD

**Issue by Diegoisawesome** [mgba-emu/mgba#1149]
Build: 0.6.3
OS: Windows 10 April Update
Game: Pokemon Emerald

In testing out some RTC features on my laptop, I came to realize that whenever I had the sensor window open, the game audio would start to stutter a bit. Checking Task Manager, it seems that mGBA goes from ~7% when running normally to ~19% with the window open. Not quite sure what's going on here.

**Comment by JMC47** [comment]
I can't reproduce this behavior.

**Comment by endrift** [comment]
I believe this is fixed in ac2c1417ad3acd412d254095161f1c7451b77c53.

**Comment by Diegoisawesome** [comment]
It is indeed! Downloaded the development snapshot build and it seems to have resolved the problem.
