### ISSUE TITLE
Getting error 09FE209C while playing rom

### ISSUE THREAD

**Issue by ollie92** [mgba-emu/mgba#1151]
I'm getting the error 09FE209C while playing the rom Meta Fire Red Y and it's when i'm in my bag I go over the "insect plate" is there a way to remove the item from my save file? it's seems to be the only issue i'm having with the game and it'll holt my progress since everything i buy is put below the insect plate in my bag and I can't use them or sell any item i pick up.

**Comment by endrift** [comment]
Please upload a save file

**Comment by ollie92** [comment]
[Pokemon Meta Fire Red Y Completed - Copy.zip](https://github.com/mgba-emu/mgba/files/2271314/Pokemon.Meta.Fire.Red.Y.Completed.-.Copy.zip)

**Comment by ollie92** [comment]
Like that?

**Comment by endrift** [comment]
Yes, thank you.

**Comment by ollie92** [comment]
Any updates on this :D thank you for looking into it for me.

**Comment by endrift** [comment]
Haven't had a chance to look into it yet.

**Comment by endrift** [comment]
Unfortunately it appears that the game also crashes on hardware when you hover over the insect plate. You'll have to use another emulator to drop it. Sorry.
