### ISSUE TITLE
Select file goes way to fast after apllying a overclock to the Vita with LOLIcon

### ISSUE THREAD

**Issue by Yoshideking** [mgba-emu/mgba#1155]
Hi,

We got this new plugin on the Vita scene, it's called  LOLIcon, it allow us to overclock te Vita's CPU to 494 MHz on any app (even the LiveArea).
So now he select file menu on mGBA got really sensitive. I press "down" and it skips by five steps, and with the analog stick you need to have a tiny move to move one space at a time.
Could you test this, please.

It really improves the performance, now a got a steady 59,72 fps on Fire Emblem, or Advance Wars.

Thanks for your time.

**Comment by endrift** [comment]
Can you check if this is fixed in the latest build fixes any of this?

**Comment by Yoshideking** [comment]
Im sry, will test in two weeks (away from home and wifi).

Many thx to your attention.

**Comment by protectivedad** [comment]
The same problems happens with me when PSV VSH and clocking at 444. I'm using 0.7-5338-18fc2cb.

**Comment by protectivedad** [comment]
Works fine on the latest build. Thanks.
