### ISSUE TITLE
Mario vs Donkey Kong scene 1-1 intro black screen

### ISSUE THREAD

**Issue by askotx** [mgba-emu/mgba#116]
There 's an issue on this rom- I tested Eur version- so, on scene 1-1 when you are starting after "how to play ..." demo, donkey starts to go to door, everything it's on black but you get sound, finally after donkey go through door, video comes back.

Tested on Windows and Wii lastest nightlies

**Comment by endrift** [comment]
Fixed in f6e0239cd339da24e04b30e394f84cffd4197a79.

**Comment by askotx** [comment]
I tested wii version on commit 2083aa9 and this bug is back

**Comment by endrift** [comment]
Re-fixed in c1082ae67fe2f51f5161ac5f2fc630d65495aaf4.
