### ISSUE TITLE
Issues with threaded renderer on 3DS.

### ISSUE THREAD

**Issue by vaguerant** [mgba-emu/mgba#1162]
Some games seem to have intermittent flickering during gameplay:
* **bit generations: Dotstream**
* **Drome Racers**

Other games with issues that seem new as of current build:
* ~~**Asterix & Obelix: XXL** - top row of pixels of foreground don't render, which I've never noticed before, but maybe it's normal, I will check into this more~~ Tested on hardware, this is normal behavior.
* **bit Generations: Dialhex** - has staticky audio which seems to be more than just performance-related
* **bit Generations: Dotstream** - ditto

Lastly, there seem to be some issues upon successive ROM loads with this build. The BIOS starts to look very broken after three or more loads, and (lay user guesswork/idiocy) the system appears to stay broken until the game reinitializes things. Most games seem to boot up fine (presumably initializing everything on startup), but a few examples that stay broken into the game are:
* **CT Special Forces - Back to Hell** (aka **Back in the Trenches** depending on region) - menu text is all displayed with the incorrect palette. Once you start a game/allow the attract mode demo to play, the menu is back to normal when it returns.
* **F-Zero Maximum Velocity** - Nintendo logo splash screen appears on wrong-colored backdrop (e.g. pink, gray) instead of the normal black. Screens after this seem unaffected.

After about 10+ successive ROM loads, mGBA crashed my 3DS and I had to restart the entire system to continue testing. On a fresh boot, F-Zero ran fine, but checking bit Generations: Dotstream on a fresh boot it retained the flickering and scratchy audio, so not all of these issues appear to be related to re-entry.

**Comment by endrift** [comment]
Palette-on-load issues should be fixed in 4ecc4b5a0d432abb37e598178f584ce51d3a03ae. Let me know which issues persist.

**Comment by vaguerant** [comment]
I can confirm the palette-on-load issues are resolved. I didn't have any issues with successive loads so far in terms of stability, either, but that's only very infrequently an issue anyway so I may just not be encountering it.

The flickering in Dotstream and Drome Racers continues. It looks similar to a (resolved) issue I filed a while ago, #837, which was related to scanline caching. The appearance of the flickering seems to look like sections of the screen being rendered in the wrong location, possibly further down the screen than intended, but it's hard identify exactly due to the speed and relative infrequency of the flickering.

The audio still seems scratchy in bit Generations titles, but I imagine this is unrelated to the renderer anyway. I'm doubting myself over whether this actually *is* an issue beyond performance now. The bit Generations games' audio seems like it might be sampled (guessing based on the very bitcrushed sound of them), which would tend to sound worse when running below full speed. It might be worth revisiting if/when these games are able to run full speed on N3DS hardware, but otherwise I'd say probably disregard the issue entirely.

**Comment by endrift** [comment]
Can confirm Drome Racers issue is threaded renderer specific.

**Comment by endrift** [comment]
It appears to be a race condition but I'm having a lot of trouble tracking down where or why, especially since nothing should be being accessed across threads except the FIFO, which is threadsafe.

**Comment by endrift** [comment]
bottom-of-the-screen flicker is fixed in 6d5e53f2d8e21e5c120863ac55139a42d55a1f75. Let me know if more issues remain.

**Comment by vaguerant** [comment]
I just updated to ca9448c (two commits after 6d5e53f), and the flickering behavior is still identical in Drome Racers and Dotstream on 3DS.

**Comment by endrift** [comment]
Hm, that's different than what I was seeing on Linux. I'll take a closer look today.

**Comment by endrift** [comment]
Fixed some edge cases with the FIFO. Should be good now, please retest again.

**Comment by vaguerant** [comment]
Tested with 749038d and can confirm that the flickering issue in both Dotstream and Drome Racers is completely resolved.

Unfortunately, a side-effect seems to be horizontal screen-tearing on about the bottom sixth of the screen in any games where performance is an issue (very easy to see in Metroid: Zero Mission, Sonic Advance and Dotstream, less so but still visible in Rayman 3, not an issue at all in, e.g Super Mario Advance 4, which maintains full speed). I can't get a screenshot as the issue seems to resolve when the emulator is paused, but the bottom sixth appears to lag one frame behind the rest of the screen about every second frame during periods of particularly bad performance.

Dropping back to the build immediately before the FIFO update, ca9448c, seems to resolve the tearing across all games (but obviously brings back the flickering in Dotstream and Drome Racers). I'm much more used to vertical tearing on the 3DS given the screen orientation so it was mildly interesting to me that this is horizontal.

**Comment by endrift** [comment]
I split the FIFO changes in two, so it may be that one of those broke things and the other resolved the flickering. Can you try de9bff4a29db25554e5234ff788617ed46a9436c if I haven't gotten to it yet? The second was more a proactive fix than a "I know this is broken otherwise" fix.

**Comment by endrift** [comment]
It helps if the read and write pointers aren't both actually the read pointer. Fixed now. Everything seems good!
