### ISSUE TITLE
mGBA 0.63 Windows 7 [Menu/Tools] inaccessible after ???, close and reopen

### ISSUE THREAD

**Issue by Vortaka** [mgba-emu/mgba#1165]
Hi!  First, love the emulator!  It does everything good and works great!

I found a little glitch maybe, however...  I am unable to reproduce it at will BUT it happened at least twice (0.63), can't remember happening on 0.61 (I updated maybe a weeks ago, start of September...).

What happens:
The Tools drop down menu (ONLY tools) is inaccessible/unopenable.  However, shortcuts are still working (Alt-C for cheats) but the drop down menu is no where to be seen...  I can also speculate (haven't tested it but once) but the menu seems to still be there (even though invisible).  When I click below the Tools (that doesn't show a drop down) the log screen opens (at it should at that position).

Temp fix: Save state/close/reopen mGBA...

It's not a HUGE problem but can cause annoyance sometimes...

Continue the great work!

Vortaka

Windows 7, 64bit
I7 2600
16gb ram

P.S.  If need of any more info, please email me!

**Comment by endrift** [comment]
Is the window just too small? I haven't seen it happen otherwise, nor am I sure how else that could happen. I can see if I can try reproducing it?

**Comment by Vortaka** [comment]
I'm in full screen (1440x900), well, zoomed full screen, so no...  I'll try to reproduce it too, and give any more info if I can, but I only was able to do it once, this afternoon...  So, it only happened twice in all...

Like I said, the Tools drop down menu is the only one that doesn't show (it's weird).  Everything else works as it should...

Vortaka

**Comment by Vortaka** [comment]
Update:

It happened again (I don't know if I should be happy to report it or not!).

First, time frame...  It seems to happen on a long play (more then 30 minutes).  I wasn't able to get a cause though...  I "alt enter" to see the menu and the tool drop down just doesn't show...

I can tell you, after the tests I did, that the menu is still fully active.  I click on Tools and with the arrow keys I can activate the log, two arrow down is the game overrides, etc...

Vortaka

**Comment by Vortaka** [comment]
First, I'm sorry to write another reply but I found a way to repeat the process!  It works every time!!!

1- Load the game!
2a- If you don't have a quick save (I'm using quick save 2)
2b- Load Quick save!
-- Start of loop --
3- If not in full screen (alt enter) then go in full screen!
4- Press Alt Enter again (window mode) and go in Tools/Cheat
5- Close Cheat
6- Goto start of loop (loop 2 or 3 times at most)...  The menu doesn't show for me anymore after that!  It works every shot!

Hope this helps!

**Comment by Vortaka** [comment]
New update for version 0.7!
The bug is still there...  The "UI" (aka the menu" hides behind the main window...  Same steps as before...
I tried to change the display driver, uncheck billinear filtering but to no avail...
Loosing the menu is a little awkward sometimes...
Continue the good work!

**Comment by endrift** [comment]
Does this still happen on latest mGBA?

**Comment by Vortaka** [comment]
Hi!  I am unable to repeat it on version 0.9.2
I tried the step by step method I used before (5 times in a row) without success!  So, I do think the problem has been resolved!
Case closed, thanks for the fix!
