### ISSUE TITLE
Temporary saves causing mGBA crash after reset

### ISSUE THREAD

**Issue by Diegoisawesome** [mgba-emu/mgba#1166]
Build: 0.6.3
OS: Windows 10 April Update
Game: Pokémon Emerald, FireRed (probably all the Pokémon games but haven't tested)

When loading a temporary save, the game loads properly the first time, but after a reset the emulator silently crashes when the game tries to read from flash memory.

**Comment by endrift** [comment]
Does this also happen in 0.7 dev builds? I made some changes to this recently that might have fixed it but postdate the release of 0.6.3

**Comment by Diegoisawesome** [comment]
Yep, still happens.

**Comment by endrift** [comment]
I can reproduce.
