### ISSUE TITLE
Fire Emblem Sacred Stones (E) - Black Screen after start of Lagdou Ruins Third Floor

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#1167]
**Fire Emblem Sacred Stones (E) - Black Screen after start of Lagdou Ruins Third Floor.**

The Screen turns black when you check the map and after you start Third Floor.
The music keeps on playing.

This occurs in the latest mGBA nightly for PC and Wii. 

**PC nightly used:** 
mGBA-build-2018-09-10-win32-5226-b03412aa38b39190f475cb89d5c8a2a5e97bc32d

**Wii nightly used:**
mGBA-build-2018-09-10-wii-5226-b03412aa38b39190f475cb89d5c8a2a5e97bc32d

I attached a save state for the problem.
[Fire Emblem - The Sacred Stones (Europe) (En,Fr,De,Es,It).zip](https://github.com/mgba-emu/mgba/files/2366323/Fire.Emblem.-.The.Sacred.Stones.Europe.En.Fr.De.Es.It.zip)

**Comment by JMC47** [comment]
Instead of a savestate could you provide a savefile?  That way if the bug is embedded into the savestate and gets fixed, we can still test it.

**Comment by endrift** [comment]
Unfortunately they deleted their account. We'll need someone to play through and get there again, unless you feel like trying to contact Dodain47 on GBATemp.

**Comment by JMC47** [comment]
It looks pretty far into the game...

**Comment by Dodain47** [comment]
Sorry for the late reply. Here is a sav file for the Eirika campaign. 
You will need to play through the 2 floors of the ruins to get to the bug. 
My troops should be strong enough.

[Fire Emblem - The Sacred Stones (Europe) (En,Fr,De,Es,It).zip](https://github.com/mgba-emu/mgba/files/2408224/Fire.Emblem.-.The.Sacred.Stones.Europe.En.Fr.De.Es.It.zip)

**Comment by SuperrSonic** [comment]
[Fire Emblem - The Sacred Stones (E).zip](https://github.com/mgba-emu/mgba/files/2408374/Fire.Emblem.-.The.Sacred.Stones.E.zip)
Here's the save right before the boss fight, you can one shot him with Artur's Ivaldi.

From the state in the op I thought it was an HLE bios problem since it would not crash with a real one.
However after using the save file it didn't crash either way.

**Comment by benderscruffy** [comment]
just used the save state and it doesnt black screen anymore
this can be closed
![fire](https://user-images.githubusercontent.com/2696404/58742173-f4c23b80-8454-11e9-8972-a638fdf68844.PNG)
