### ISSUE TITLE
mGBA wouldn't compile on Elementary OS

### ISSUE THREAD

**Issue by Delta456** [mgba-emu/mgba#1168]
I am using Elementary OS Loki which is based on Ubuntu 16.04. I cloned the whole repository and followed the build instructions for my system. When I entered `cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..` into the terminal and this happened.

These are logs files which were produced by CMAKE:

- Error Log

`Determining if the function snprintf_l exists failed with the following output:
Change Dir: /home/delta/Downloads/mgba-master/build/CMakeFiles/CMakeTmp
Run Build Command:"/usr/bin/make" "cmTC_bb3e3/fast"
/usr/bin/make -f CMakeFiles/cmTC_bb3e3.dir/build.make CMakeFiles/cmTC_bb3e3.dir/build
make[1]: Entering directory '/home/delta/Downloads/mgba-master/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_bb3e3.dir/CheckFunctionExists.c.o
/usr/bin/cc    -Wall -Wextra -Wno-missing-field-initializers -std=gnu99 -pthread -DCHECK_FUNCTION_EXISTS=snprintf_l   -o CMakeFiles/cmTC_bb3e3.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_bb3e3
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_bb3e3.dir/link.txt --verbose=1
/usr/bin/cc   -Wall -Wextra -Wno-missing-field-initializers -std=gnu99 -pthread -DCHECK_FUNCTION_EXISTS=snprintf_l    CMakeFiles/cmTC_bb3e3.dir/CheckFunctionExists.c.o  -o cmTC_bb3e3 -rdynamic 
CMakeFiles/cmTC_bb3e3.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text+0x15): undefined reference to `snprintf_l'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_bb3e3.dir/build.make:97: recipe for target 'cmTC_bb3e3' failed
make[1]: *** [cmTC_bb3e3] Error 1
make[1]: Leaving directory '/home/delta/Downloads/mgba-master/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_bb3e3/fast' failed
make: *** [cmTC_bb3e3/fast] Error 2`

- [Output Log File](https://pastebin.com/V0ECzhLZ) (Log File was pretty big)

**Comment by endrift** [comment]
What does the actual command output? That error log doesn't actually contain any fatal errors in the configure process, it just shows one of the functions I check to see if it exists doesn't.

**Comment by Delta456** [comment]
Could help?

**Comment by Raijinili** [comment]
The only error I see is `SDL_INCLUDE_DIR` being `NOTFOUND`.

I don't know what I'm talking about, but: I notice your build uses SDL. Try building without SDL.

**Comment by Delta456** [comment]
How would I do that? I am kind of a newbie sorry.

**Comment by endrift** [comment]
Try running `sudo apt-get install --no-install-recommends libavcodec-dev libavformat-dev libavresample-dev libavutil-dev libedit-dev libelf-dev libmagickwand-dev libpng-dev libqt5opengl5-dev libsdl2-dev libsqlite3-dev libswscale-dev libzip-dev qtmultimedia5-dev qttools5-dev-tool`

That should install all the dependencies. It will use a fair bit of space though.

**Comment by Delta456** [comment]
> I was having the same issue and grabbing all the dependencies fixed the issue for me.

It worked. Thanks :smile:
