### ISSUE TITLE
Final Fantasy 6 Advance: Sound broken from the very beginning

### ISSUE THREAD

**Issue by tomtung** [mgba-emu/mgba#1171]
The sound is broken right after the starting chord played by organ.

**Comment by endrift** [comment]
Which platform and version are you using? I can't reproduce. I notice some slight audio distortion but that might just be my audio drivers. Can you be more specific about how it's broken?

**Comment by endrift** [comment]
Can you turn on the FPS display to make sure it's running at full speed? It's not always full speed on N3DS.

**Comment by tomtung** [comment]
It was 59.75 fps when the sound started cracking, right when the title screen showed up.

**Comment by tomtung** [comment]
btw I also tried virtual console injection, and the sound worked fine there.

**Comment by endrift** [comment]
Does this still happen for you?

**Comment by Testsr** [comment]
@tomtung, can you retest with the latest development version?

**Comment by endrift** [comment]
There hasn't been a reply in nearly 4 months, I'm just closing this unless it's confirmed it still is a problem.
