### ISSUE TITLE
Sonic Advance 3 sprites jumping on Switch

### ISSUE THREAD

**Issue by auyx** [mgba-emu/mgba#1175]
During play on level one sprites for both the hud an characters jump about the screen. This does not seem to affect gameplay or collisions. Did Not happen on the vita version of mgba or the retro NX core. Happens both with and without official BIOS.

**Comment by endrift** [comment]
Which build did you test on? I'm curious if it's 108b0fc867292c554a6ef9b643fc39209561e35a or newer. I have a hunch that that may fix it, though it seems rather unlikely.

**Comment by auyx** [comment]
Thanks, whatever you did seems to have fixed it for me on switch.

Mgba is the best.

On 21 Sep 2018 22:24, "endrift" <notifications@github.com> wrote:

This seems to be fixed. Please retest.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mgba-emu/mgba/issues/1175#issuecomment-423674800>, or mute
the thread
