### ISSUE TITLE
mGBA crash on WebM record start

### ISSUE THREAD

**Issue by Sewef** [mgba-emu/mgba#1176]
Hello,

Whenever I try to record a WebM file with mGBA, the soft crashes when I press "Start".
Tried with mGBA 0.6.3 and a nightly build.

Settings : 
![image](https://user-images.githubusercontent.com/27089398/45689450-4e4b3a00-bb54-11e8-93a0-19da47f9cd72.png)

Windows Reliability Monitor infos (sorry, french.) : 
```
Source
mGBA Game Boy Advance emulator

Résumé
Fonctionnement arrêté

Date
‎18/‎09/‎2018 14:58

Statut
Non signalé

Description
Chemin d’accès de l’application défaillante :	C:\Users\...\mGBA-build-2018-09-18-win32-5259-108b0fc867292c554a6ef9b643fc39209561e35a\mGBA.exe

Signature du problème
Nom d’événement du problème :	APPCRASH
Nom de l’application:	mGBA.exe
Version de l’application:	0.7.0.0
Horodatage de l’application:	00000000
Nom du module par défaut:	mGBA.exe
Version du module par défaut:	0.7.0.0
Horodateur du module par défaut:	00000000
Code de l’exception:	c0000005
Décalage de l’exception:	00bf7a77
Version du système:	6.1.7601.2.1.0.256.1
Identificateur de paramètres régionaux:	1036
Information supplémentaire n° 1:	0a9e
Information supplémentaire n° 2:	0a9e372d3b4ad19135b953a78882e789
Information supplémentaire n° 3:	0a9e
Information supplémentaire n° 4:	0a9e372d3b4ad19135b953a78882e789

```

OS : Windows 7 Ultimate Edition (64 bits)
CPU : AMD Ahtlon™ II X4 640
GPU : NVIDIA GeForce GTX 950
RAM : 8GB

**Comment by endrift** [comment]
Worked around by replacing the Vorbis encoder with Opus, which is recommended anyway.

**Comment by endrift** [comment]
I think this may actually be an FFmpeg bug that mGBA is hitting, but I'm not sure.

**Comment by endrift** [comment]
I don't believe this is relevant anymore given that the Windows build doesn't even support Vorbis anymore.
