### ISSUE TITLE
GBC game Bomberman Selection (Korea) chokes when selecting a game to play.

### ISSUE THREAD

**Issue by MapleStoryPSN** [mgba-emu/mgba#1177]
The game loads up the title screen and main menu just fine but when selecting a game to play, it either hangs on a blank screen or hits you with a message in Korean saying it can only be played on a Game Boy Color. I've tested it with and without the GBC bios file and GBA and GBC Game Boy models. Was looking forward to seeing the broken English as explained here: https://tcrf.net/Bomberman_Selection

Tested on a Raspberry Pi 3 running mGBA 0.7-WIP

**Comment by endrift** [comment]
Easy fix. Thanks for reporting!
