### ISSUE TITLE
Mario Golf - Advance Tour Map/Overworld Shaking

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#1179]
The "Top Down" parts of the golf course seem to shake a lot on mGBA.  This occasionally can happen on console but not as much.

Console
![console](https://user-images.githubusercontent.com/6598209/45920891-fb85c100-be78-11e8-8122-aa816fe9d9eb.gif)

mGBA (Latest Nightly as of Today)
![shaking](https://user-images.githubusercontent.com/6598209/45920894-07718300-be79-11e8-8e1f-5e023e4d1f0d.gif)

**Comment by endrift** [comment]
This is almost certainly the same "problem" as #221, though I didn't think the GB Player did interframe blending.

**Comment by endrift** [comment]
Confirmed that this happens on hardware too.

**Comment by vaguerant** [comment]
Incidentally, the Game Boy Player does optionally do interframe blending, I believe they called it "soft mode" as opposed to "sharp mode". The 3DS GBA backward compatibility also does this optionally, though not (conveniently) user-controllably, just via a setting in the header.
