### ISSUE TITLE
Sound effects in Final Fantasy VI Advance randomly dropping out.

### ISSUE THREAD

**Issue by fsvgm777** [mgba-emu/mgba#118]
(Late) Cross-posing this from the [TASVideos forums](http://tasvideos.org/forum/viewtopic.php?p=415525#415525):
_I've had this happen on the unpatched European release (that is, without the sound restoration patch)...though, upon closer listening, it seems like a specific sound channel doesn't play at all at random._

_[Here are two recordings showcasing the sound issue.](https://www.mediafire.com/?g7yuuv8m5i3l5tn) (yes, the game is in French (I chose for it to be in French), but that's beside the point)_

_After mucking around a bit, it seems the issue is with sound channel 4. Note that sound channel 4 was enabled at all times in these two recordings._

We've talked about it on TASVideos's IRC channel a bit (it also contains relevant timestamps in the two recordings): https://dl.dropboxusercontent.com/u/64600169/ff6a_tasvideosirclog.txt

This currently happens on 0.3.0 and the latest nightly (2015-09-12), for the record. At least the Windows version is affected, not sure about other versions.

**Comment by endrift** [comment]
I think this might be the same bug as the one for channel 3 I fixed a while ago where it's doing 8-bit writes, causing things to get into an inconsistent state.

**Comment by endrift** [comment]
This should be fixed by 98529063ba822b0e2524a2882f0ea3b13f537482. Please confirm that it works in tomorrow's nightly.

**Comment by fsvgm777** [comment]
Just tested on the most recent nightly build (2015-9-15), and it appears the issue has been fixed. Thank you very much.
