### ISSUE TITLE
Issue with pokemon emerald romhack Touhoumon World Link 

### ISSUE THREAD

**Issue by xeroxenox** [mgba-emu/mgba#1180]
Running mGBA 0.6.3, have also tried it with 0.7-5292-ca9448c, rom hack requires rtc and save flash type 128k, have tried using manual override in the config.ini to no luck.

**Comment by endrift** [comment]
This probably works fine now in 0.9.0, please retest.

**Comment by endrift** [comment]
Closing due to lack of reply; assuming fixed.
