### ISSUE TITLE
  Sharp bilinear, scanlines, sabr v3, xbrz, supereagle shader for Switch

### ISSUE THREAD

**Issue by tabnk** [mgba-emu/mgba#1181]
It will be nice to have above shader for Switch build. :) 👍

**Comment by Ninjistix** [comment]
*sad face* okay, just figured i'd toss my 2 cents 💃

**Comment by Arnochocobo** [comment]
Please don't forget crt caligari, anything else is just garbage who shouldn't even exist in the first place. Thanks and keep up the good work!

**Comment by Arnochocobo** [comment]
And who cares about playing stuff on 3ds now that we have switch? What about supporting Game Gear while you are at it?

**Comment by tabnk** [comment]
RetroArch just released (nightly build) with full shader support for mGBA. I’m close this issue now. :)

**Comment by seanbperiod** [comment]
I just wanted to stem off this - any chance the shaders can be added to the standalone version?
