### ISSUE TITLE
cant open yoshi island

### ISSUE THREAD

**Issue by Moodie92** [mgba-emu/mgba#1182]
when i open Yoshi's Island - Super Mario Advance 3 it give me that screen , even when i delete all saved files 
![0593 - yoshi s island - super mario advance 3 u mode7 -0](https://user-images.githubusercontent.com/40892036/46015184-de97fa80-c0d1-11e8-87aa-9c92829cb934.png)

**Comment by JMC47** [comment]
What version of the game are you using?  Everything is working for me.

**Comment by endrift** [comment]
You probably have a bad dump. I know there are several floating around.

**Comment by Moodie92** [comment]
i thought the same of a bad dump !!! so i transfer it to my android phone and it is working 
![42478946_159052605027005_4582277823300894720_n](https://user-images.githubusercontent.com/40892036/46022105-422a2400-c0e2-11e8-812f-e54e8b762e5e.png)

**Comment by Moodie92** [comment]
edit : i used another dump still the same !!!

**Comment by endrift** [comment]
Mode 7 is a piracy group. If you use a verified good dump it works.
