### ISSUE TITLE
mgba 0.7.0-b1 without sound on 3ds

### ISSUE THREAD

**Issue by Hinotori1127** [mgba-emu/mgba#1183]
without sound when play gba game , on 0.6.3 dont have the problem

**Comment by Ninjistix** [comment]
is this a specific game? because I've tried every gba pkmn game and the audio was fine, 

I tested mega-man BN1 and the audio was fine but on some maps/zones it started to get slow/staticy

**Comment by Ninjistix** [comment]
me personally n3DS cia as for OP no idea.

**Comment by Hinotori1127** [comment]
> Are you using a .cia or a .3dsx? Are you on o3DS or n3DS? What firmware version?

CIA . n3DS . 11.8.0-41J

**Comment by Hinotori1127** [comment]
> is this a specific game? because I've tried every gba pkmn game and the audio was fine,
> 
> I tested mega-man BN1 and the audio was fine but on some maps/zones it started to get slow/staticy

I tested all my games. But there is no sound in every game.

**Comment by endrift** [comment]
Make sure you've dumped dspfirm.cdc first.

**Comment by Hinotori1127** [comment]
> Make sure you've dumped dspfirm.cdc first.

I haven't do it .How to dump?

**Comment by endrift** [comment]
Either https://github.com/zoogie/DSP1/releases/tag/v1.0 or https://github.com/Cruel/DspDump/releases should do the trick.

**Comment by Hinotori1127** [comment]
> Either https://github.com/zoogie/DSP1/releases/tag/v1.0 or https://github.com/Cruel/DspDump/releases should do the trick.

ok ty ;-)

**Comment by Hinotori1127** [comment]
> Either https://github.com/zoogie/DSP1/releases/tag/v1.0 or https://github.com/Cruel/DspDump/releases should do the trick.

I tried DSP1 and it ran successfully on my 3ds.
Now all my gba game have sounds. thank you!
