### ISSUE TITLE
Bottom Screen doesn't show updated changes..

### ISSUE THREAD

**Issue by Ninjistix** [mgba-emu/mgba#1184]
When opening the menu with X or loading a game, or even changing the game from top screen to bottom screen with Y, the bottom screen doesn't update to track the changes.. 

[Bottom Screen still showing game img after switched back to top]
![img_20180926_114319](https://user-images.githubusercontent.com/12572974/46092018-efa04480-c181-11e8-8577-168f1db1ff7f.jpg)

[bottom screen showing X menu after game has been resumed]
![img_20180926_114337](https://user-images.githubusercontent.com/12572974/46092019-efa04480-c181-11e8-86af-fa0f834ad4e3.jpg)

[bottom screen showing loading img after game is already running
![img_20180926_114944](https://user-images.githubusercontent.com/12572974/46092187-5faeca80-c182-11e8-885c-82aeb3e73e13.jpg)

it seems to not be tracking any of the actual changes, just whatever was last on the screen

Edit: Sorry forgot to add any relative info, 
Ver . mGBA 0.7 beta 1 (cia)
Console: n3DS ver 11.8.0-41U

**Comment by endrift** [comment]
This used to work, but...I think some citro3d update broke it. Will fix before 0.7.0 final though, thanks for filing.

**Comment by Ninjistix** [comment]
no problem (only thing missing is the cheats ;) #903) added the console info to op
