### ISSUE TITLE
Wii port - Game Boy and Game Boy Color video interferences

### ISSUE THREAD

**Issue by SieKensou** [mgba-emu/mgba#1185]
I noticed some thin lines like some kind of interferences that appear on the screen during the emulation. I don't notice it when playing Game Boy Advance games, but with Game Boy and Game Boy Color they are very noticeable. They even appear during the BIOS screen.

**Comment by endrift** [comment]
Regressed in ea2159d159f2ddb5514b9137a116eb74a2ed872f
