### ISSUE TITLE
[GBA][VITA][PSP2] The mGBA is terminated when I play 0690-Metroid Fusion US.

### ISSUE THREAD

**Issue by hsuanpai** [mgba-emu/mgba#1187]
Hi

I play the game 0690-Metroid Fusion US about half hour. And got PSP2 core dump.
File attached is psp2 core dump file. 
BTW: I found the audio still will broken at sometimes.

OS: PSVita 2000, version: 3.68
mGBA version is 0.7 b1

[psp2core-1538154094-0x0000772a77-eboot.bin.psp2dmp.zip](https://github.com/mgba-emu/mgba/files/2429115/psp2core-1538154094-0x0000772a77-eboot.bin.psp2dmp.zip)

**Comment by endrift** [comment]
There have been more audio fixes since 0.7-b1. Do you have more than one instance of this happening? If you haven't played Fusion since it crashed and you have a .ss0 file for it, please upload it here.

**Comment by endrift** [comment]
Does this still happen for you?

**Comment by endrift** [comment]
Closing due to lack of reply.
