### ISSUE TITLE
Held rewind controller shortcut still works in multiplayer

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#119]
Based on recent commits, this looks like something you would want disabled.

**Comment by endrift** [comment]
Rewind definitely. Fast forward is effectively dead in multiplayer due to how lockstep works.

**Comment by tony971** [comment]
I'm still able to use fast forward in multiplayer.

**Comment by endrift** [comment]
Are you actually in the multiplayer portion of a game, with the games linked?

**Comment by tony971** [comment]
I'm in the part that triggers the "Player X of Y" messages but I haven't actually had the games interact. I'll try that later.

**Comment by endrift** [comment]
Yeah, the lockstep driver isn't active at that point and most of the stuff that's disabled would actually still work fine there. But I disabled them because if you have multiplayer windows open...you're probably not gonna want them anyway.

**Comment by endrift** [comment]
Rewind disabled in 822df23, but fast forward can still be triggered. Not sure how much it matters though.
