### ISSUE TITLE
"Left" button on controller also triggers an "A"

### ISSUE THREAD

**Issue by tronje** [mgba-emu/mgba#1190]
I've configured my controller in the controller menu in the settings. I've assigned each button in the diagram to one button on the controller. It all works very nicely, except that whenever I press left, it's as if I've also pressed A at the same time, which is a bit annoying.
Any ideas? Much appreciated!

P.S. running version 0.6.1

**Comment by endrift** [comment]
0.6.1 is very outdated. Please try 0.7-b1.

**Comment by JMC47** [comment]
Try clearing joysticks and reconfiguring the dpad.

**Comment by tronje** [comment]
I compiled 0.7-b1 and it works like a charm now, thanks very much! Sorry for the trouble.
