### ISSUE TITLE
Super Mario Advance 2 Right+Left glitch

### ISSUE THREAD

**Issue by themalu866** [mgba-emu/mgba#1191]
In Super Mario Advance 2 - Super Mario World if you're riding Yoshi with the right and left buttons pressed at the same time Yoshi will keep going to the right but with the sprites of when he turns around.

I checked in other emulators and when you press the two buttons Mario walks to the left, which doesn't happen on mgba. So maybe that's what's causing the glitch.

![yosh](https://user-images.githubusercontent.com/42208976/46249441-a65d2880-c3ff-11e8-929e-3dce996ce148.png)
![yogli](https://user-images.githubusercontent.com/42208976/46249689-c1ca3280-c403-11e8-996e-098259e35233.gif)
![yosss](https://user-images.githubusercontent.com/42208976/46249844-4fa71d00-c406-11e8-99c2-b47b1ff6c330.gif)

On 0.6.3 was alright.

![righyos0 6 3](https://user-images.githubusercontent.com/42208976/46249901-7580f180-c407-11e8-90a9-4267606bec20.gif)

**Comment by JMC47** [comment]
Do other emulators allow pressing both left/right at the same time.  If I remember correctly, this is the behavior you'd expect in this game.

**Comment by endrift** [comment]
Many emulators have special handling of what happens if you press opposing directions on the d-pad at the same time. If you allow both keypresses funny things can happen, including things like Metal Slug Advance crashing, and an assortment of other glitches. It may just be that the different emulators have different handling of this. There's a setting for how to handle it in mGBA too.

**Comment by endrift** [comment]
Do you have "Allow opposing input directions" checked in Settings > Interface?

**Comment by JMC47** [comment]
I have a broken dpad on one of my GBAs I wonder if I could do this in the game.

**Comment by themalu866** [comment]
"Allow opposing input directions" was disabled
I enabled and it's still the happens.

**Comment by endrift** [comment]
Oh. Looks like that feature broke then.

**Comment by themalu866** [comment]
I tested on 07-b1 and the glitch still happens but on 0.6.3 was fine.

![righyos0 6 3](https://user-images.githubusercontent.com/42208976/46249928-d7415b80-c407-11e8-953f-5c4541dfb131.gif)
