### ISSUE TITLE
mGba crashes on opening any Viewer expect Palette Viewer on Elementary OS

### ISSUE THREAD

**Issue by Delta456** [mgba-emu/mgba#1192]
mGba crashes on opening any gba rom and using the Sprite Viewer. I am using Elementary OS Loki which is based on Ubuntu 16.04.

**Comment by endrift** [comment]
having trouble reproducing this on Ubuntu 18.04 using latest master. What version are you using?

**Comment by Delta456** [comment]
> having trouble reproducing this on Ubuntu 18.04 using latest master. What version are you using?

I am using  version 0.70

**Comment by Delta456** [comment]
All tools crash on opening expect Palette Viewer.

**Comment by endrift** [comment]
Still can't reproduce. Can you upload your config? Should be in ~/.config/mgba/config.ini. It will contain paths that you may want to redact.

**Comment by Delta456** [comment]
Here it is
`[ports.qt]
width=480
lastDirectory=/home/delta/Downloads
height=320
fullscreen=0`

**Comment by endrift** [comment]
That can't be the whole thing...

**Comment by Delta456** [comment]
See for yourself

![image](https://user-images.githubusercontent.com/28479139/46356212-e4687f80-c67f-11e8-95d6-af8662df17af.png)

**Comment by endrift** [comment]
What about ~/.config/mgba/qt.ini?

**Comment by Delta456** [comment]
![image](https://user-images.githubusercontent.com/28479139/46356885-4a093b80-c681-11e8-844b-bdd5c59775ad.png)

**Comment by endrift** [comment]
I still can't reproduce. Can you build a debug version (`cmake . -DCMAKE_BUILD_TYPE=Debug && make`) and send me a backtrace of it crashing?

**Comment by Delta456** [comment]
I tried using VBA-m this time and it also crashes. I think its the problem with my Distro's version (16.04). I will try to update to 18.04 and see if the problem is still there.

**Comment by Delta456** [comment]
Seems like there some problem with previous version of Ubuntu 16.04

**Comment by endrift** [comment]
It's hard to fix if I can't reproduce it. That's why I asked for a backtrace.

**Comment by Delta456** [comment]
> It's hard to fix if I can't reproduce it. That's why I asked for a backtrace.

Could tell how to do a backtrace?

**Comment by endrift** [comment]
Run the debug build in gdb and when it crashes type `bt` in the prompt

**Comment by endrift** [comment]
Are you able to reproduce this with the current dev builds?

**Comment by Delta456** [comment]
I am able to reproduce this error with the newest build too. My OS reported that it crashed with SIGSEGV and the disassembly said that it cannot access memory at 0x7f75b68eb3ef.

**Comment by endrift** [comment]
Is this still a problem on latest dev builds? I'd still like a backtrace.

**Comment by endrift** [comment]
Please retest. I'd still like that backtrace if you can reproduce it. Just the address and "SIGSEGV" isn't enough. It prints out a lot of info that I need.

**Comment by Delta456** [comment]
I am no longer using Elementary OS. I will close this now.
