### ISSUE TITLE
Game pad issues with Game boy Games

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#1193]
The game pad works correct with Game Boy Color and Game Boy Advance but not with Game Boy it keeps going right without me touching it. Try game Double Dragon 1 and Super Mario Land.

mGBA-build-2018-09-30-win32-5326-2865c9ab2bf454041660d04508d82b1db436c26b

This is the kind of Game Pad I have. 

https://www.amazon.com/ZD-Gamepad-Controller-Joystick-Playstation/dp/B01GDKXMPA/ref=sr_1_3?ie=UTF8&qid=1538336529&sr=8-3&keywords=ZD+T+Gaming+Wired+Gamepad&dpID=411JjprhbiL&preST=_SX300_QL70_&dpSrc=srch

**Comment by endrift** [comment]
This was fixed in the very next commit, but the Windows build didn't get built for some reason.
