### ISSUE TITLE
"Separate fast forward volume control" Main Volume doesn't work

### ISSUE THREAD

**Issue by ImSpecial** [mgba-emu/mgba#1194]
Windows 10, using latest dev build, probably something to do with [this comment](https://github.com/mgba-emu/mgba/commit/5fa1638b1df3e16984bc356653fe405de6e944c7).

Problem is in the title pretty much, there are now two volume sliders, a "Main" and "Fast Forward"

Fast Forward works as expected, Main doesn't seem to do anything as volume sounds like it's at 200% no matter where the slider is at.

For the record I like something around 75% Main / 20% FF

**Comment by endrift** [comment]
Yeah I noticed something like this last night. Will inspect further.
