### ISSUE TITLE
Cheat codes auto loading

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#1195]
Game boy cheats will auto load could you please make it so Game boy advance cheats will auto load on game boot?

**Comment by endrift** [comment]
They already do.

**Comment by Cibomatto2002** [comment]
It will auto load cheats if I load a savestate but not if I just load a game. Maybe I am missing something.
 I made a video to show you how it works on my end.

https://www.youtube.com/watch?v=ZG4re_dFhlY&feature=youtu.be

**Comment by endrift** [comment]
The name of your ROM has a hyphen. The name of the cheats file doesn't. They need to have the same name for mGBA to know where to find them.

**Comment by Cibomatto2002** [comment]
Sorry about that.
