### ISSUE TITLE
i don't think the xbr shader is supposed to look like this

### ISSUE THREAD

**Issue by Ninjacat64** [mgba-emu/mgba#1199]
![screen shot 2018-10-02 at 9 23 57 am](https://user-images.githubusercontent.com/21105636/46351621-cb32e500-c625-11e8-8167-142818cee5c0.png)
![screen shot 2018-10-02 at 9 24 02 am](https://user-images.githubusercontent.com/21105636/46351623-cb32e500-c625-11e8-92bd-da47cbcf4529.png)
there is constantly this static film that covers the graphics while i try to use the xbr filter
it seems to react to the window state and whether or not i am using resampling
all the other shaders work fine 
using mbga 0.5.0 (heads branch)
updating isn't an option for me, don't ask why

running on macbook air with intel i5 and intel HD graphics 6000

macos version 10.12.6, kernel 16.7.0

**Comment by endrift** [comment]
That's an ancient branch that hasn't been updated in over a year.

Anyway it's a driver bug unfortunately. It works fine on some drivers but not others.
