### ISSUE TITLE
Make CPU prefetch discrete from instruction execution

### ISSUE THREAD

**Issue by grantgalitz** [mgba-emu/mgba#12]
I don't know any compatibility issues with doing or not doing this, but the overhead is actually minimal if the run loops are redone. The run loops would need to be highly modified, and as such would be more fit as a feature request for a far off version.

**Comment by grantgalitz** [comment]
What I'd do for this:

- Switch on bit fields stored in an integer
- Fold the cycles per run check *into* the bit fields*
- Make CPU execution the first checked case, and only include the exection and prefetch stuff in the main switch
- Check for DMA/Halt/Stop in the default clause
- When you predict the next "event" you can also determine clocks until emulator iteration end. This can be folded into the bit checks inside a secondary less called switch and you can cleanly return out of the while (true) loop.

You'd probably do this differently I'd assume, but I tried a bunch of methods and wound up with these:
https://github.com/grantgalitz/IodineGBA/blob/master/IodineGBA/IodineGBA/GameBoyAdvanceIOCore.js#L91
https://github.com/grantgalitz/IodineGBA/blob/master/IodineGBA/IodineGBA/GameBoyAdvanceIOCore.js#L111
https://github.com/grantgalitz/IodineGBA/blob/master/IodineGBA/IodineGBA/GameBoyAdvanceIOCore.js#L155

**Comment by endrift** [comment]
What would I *gain* from doing this? This seems like a whole lot of hassle that I have no real reason for doing, other than improved cycle accuracy and open bus behavior in exceedingly bizarre cases.

We talked about this in IRC a while ago and I expressed no interest in doing it myself. You can submit a PR if you want. This isn't worth the effort for me to try to do it myself.

**Comment by grantgalitz** [comment]
That is a good question... what would change from implementing this.
I wonder if some game has tight timing and gets fps dips or a dropped frame every now and then from the difference.

**Comment by grantgalitz** [comment]
I guess we'll wait and see if such a game exists.

**Comment by grantgalitz** [comment]
I know we discussed this on IRC, I just wanted to document it at least.
