### ISSUE TITLE
mac os 10.13 and 10.14: playing a gbc game doesnt show video until window resize

### ISSUE THREAD

**Issue by EzioisAwesome56** [mgba-emu/mgba#1200]
so whenever i try to play a gbc game on mbga 0.6.3, the window doesnt show game video until i resize the window. this happens on all video modes to gbc games, however gba games start displaying the video correctly right away.

heres a video if you want to see what i mean
[video on my twitter](https://twitter.com/ezioisntcool56/status/1047246119833669633)

**Comment by EzioisAwesome56** [comment]
oh, it is indeed fixed

my apologies, i was unable to find any information or the fact it was fixed through googling and thought it was still a bug

sorry for bothering you, ill just close this

**Comment by endrift** [comment]
It came back at some point so I wasn't sure if it had regressed again or if I hadn't fixed it again. No worries.
