### ISSUE TITLE
Wii port - Game Boy games missing some sound effects

### ISSUE THREAD

**Issue by SieKensou** [mgba-emu/mgba#1202]
I was testing some games like King of Fighters '95 and King of Fighters: Heat of the Battle and both doesn't play a lot of sound effects (like the sound when charging Power and some hits sound effects). I have the original games and I tested them in original hardware an that sound effects should play.

**Comment by endrift** [comment]
Which version are you using? There have been lots of audio fixes since 0.6.3.

**Comment by SieKensou** [comment]
I downloaded the last development version a few days ago (to test if the last bug I posted was fixed). Now I have downloaded the latest (from 2, october 2018) and it still have that problems. In fact, in KOF95 doesn't sound nothing more than the jump sound.

**Comment by endrift** [comment]
In SGB mode, KOF uses SNES Audio, which is not supported in mGBA. You need to either force it into GB mode or use higan. You'll notice it doesn't work in bgb either.

**Comment by SieKensou** [comment]
Ah, yeah, you are right, okay, sorry, when I was playing I thought it was a bug. How can I set the emulator to never use the SGB on the Wii? When I turn off the borders it still uses the SGB colors and all its stuff.
