### ISSUE TITLE
Wii Port - Super Game Boy Option

### ISSUE THREAD

**Issue by SieKensou** [mgba-emu/mgba#1205]
The missing sound effects issue with some games using Super Game Boy due to the fact that they uses SuperNES audio makes me don't want to use SGB. I like the Super Game Boy, but the game loses too much without sound effects.
Would be possible to add an option to "Use Super Game Boy" (ON/OFF) for the Wii? I only see the option to turn off the SGB borders but setting that option off it only removes the border, but the games still uses the SGB colors and all its stuff (including the SNES audio that will not sound). With this new option we could play all the Game Boy games using Super Game Boy if we wanted (and not only the ones with borders or special features for the SGB) or just play as a normal Game Boy. Of course, this option only would affect to the GB games, not GBC or GBA games would be affected by this option.

About the SNES sound effects problem, the best option I can think to make SGB experience better in this emulator, as this emulator will not support the SNES audio, would be to make the SGB mode always to use GB audio... but I don't know if this would be possible and maybe making it work this way would be very difficult...

**Comment by endrift** [comment]
You can edit the config file manually to set a per-game override, but that's...quite annoying to do by hand. It's a bit late in the 0.7 cycle to fix this though, so I'm going to do this in 0.8.
