### ISSUE TITLE
Failed to load GBA ROM in archive (*.zip *.7z) when the path or filename contains CJK characters.

### ISSUE THREAD

**Issue by lxrite** [mgba-emu/mgba#1206]
Failed to load GBA ROM in archive (*.zip *.7z) when the path or filename contains CJK characters. When I remove these CJK characters from the path it's works fine.

- mGBA version: 0.7 beta 1
- OS: Windows 10 x64 Chinese Simplified

**Comment by endrift** [comment]
Seems to work on Linux, so I'm assuming it's a Windows-specific issue.

**Comment by leoxxx** [comment]
It still exsists in 0.8.1.
So strange,  CJK characters named gbc & gba files are O.K.

**Comment by leoxxx** [comment]
Still error in 0.8.2.

**Comment by endrift** [comment]
Fixed in mgba-emu/dependencies@69d651ab3b806fbe454928cf8e4c7779ddee6b16. Turns out the third-party library I was using to open zip files didn't work with CJK characters on Windows. I updated the library and future builds should have this fixed, including mGBA 0.8.3.
