### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#1207]
What is a DSYM File? I see there is a installer now is this the only way to get the new Development builds? I don't really like to install Emulators this way I like the old unzip and drag and drop better.

**Comment by lotharsm** [comment]
As far as I know, a dSYM file contains debug information for iOS apps.

The installer is not the only way of getting new development builds, the 7z archived developments are still available at http://mgba.io/downloads.html#desktop-os-2.

**Comment by endrift** [comment]
dSYM is just DWARF-format symbols. You usually see the extension on macOS or iOS, and I picked it somewhat arbitrarily. You only need to download those if you want to try to debug something that's gone wrong, usually a crash.

Anyway this isn't a support forum.

**Comment by Cibomatto2002** [comment]
I was getting the DSYM Files when download the windows port that's why I ask what they was because I could not use them in Windows. Went back and redownloaded it on 10-8-2018 and everything is ok now no more DSYM files for Windows.
