### ISSUE TITLE
Robot Wars: Extreme Destruction won't advance past the title screen

### ISSUE THREAD

**Issue by Shima33** [mgba-emu/mgba#1208]
It displays the opening credits and language select just fine, as well as playing music, but once you get to the title screen, the copyright information and the "PRESS START" text never appear. Opening the TAS Studio in Bizhawk reveals that all frames after the opening animation are all lag frames, oddly.

Tested with Bizhawk 2.3, the latest dev build of Bizhawk, mGBA version 0.6.3 and mGBA version 0.7 beta 1 - none of these work.

**Comment by endrift** [comment]
This appears to be the same issue as #539. Seems there's a 7 cycle delay on IRQs. This is too dangerous to implement in mGBA 0.7, putting in 0.8.

**Comment by endrift** [comment]
Fixed by the same commit, f6a4a13b60ae30fa74ee33422e2d951b6c0a3348.
