### ISSUE TITLE
libretro improvement suggestions

### ISSUE THREAD

**Issue by lacastri** [mgba-emu/mgba#1209]
https://github.com/lacastri/mgba/tree/libretro
1. higher rate; most libretro ports use 48000 default
2. lower latency; 1024 samples can take 1-2 retro_run calls to update audio at 32768 default rate
3. libretro memory; cheat search, misc

**Comment by endrift** [comment]
Did you mean to file a PR?

**Comment by lacastri** [comment]
Just checking for some community feedback first. Not all my ideas turn out okay and enough get reverted down the line. So just making sure there's no obvious complaints before filing an official PR.
