### ISSUE TITLE
Minor issues in Sonic Advance

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#121]
The "save and quit" option in the Tiny Chao Garden saves but takes you to this screen:
![image](https://cloud.githubusercontent.com/assets/6880539/9917145/0532231a-5c8e-11e5-97b0-ba44b23a1a53.png)
This screen also comes up if you do the A+B+SEL+START reset. Both issues are present in Sonic Advance 2 as well. Using the libretro port this doesn't happen if bios is enabled.

In the options menu under Player Data, the black box is not displaying the player name:
![image](https://cloud.githubusercontent.com/assets/6880539/9917226/79c3abc2-5c8e-11e5-816f-360929739401.png)

Backing out of the character select screen makes some of the graphics black, this also happens when you finish an act. This doesn't happen on real hw.
![image](https://cloud.githubusercontent.com/assets/6880539/9917328/effb0a42-5c8e-11e5-9f49-ae23a12842d9.png)

**Comment by endrift** [comment]
The first issue is https://endrift.com/mgba/bugs/show_bug.cgi?id=141. I'll look at the others soon.

**Comment by endrift** [comment]
Fixed in b5a34c9fe772ad08dfb04dc0eac7e1b3ef3dc6d8 and ea1f87d745a4b686ecb0b74a2303a71a5a27dda2.
