### ISSUE TITLE
(Vita port) Screen tearing in Pokemon Prism

### ISSUE THREAD

**Issue by Pokemiah** [mgba-emu/mgba#1211]
While playing Pokemon Prism on mGBA the screen tears a bit on the top. If you can I would appreciate it if you could fix it at your earliest convenience. It also seems to have an audio issue when exiting the badge screen where it plays some brief noise that wasn't present on the other emulator I was using. That one is really minor compared to the screen tearing bug. Thanks in advance.

**Comment by endrift** [comment]
I can reproduce. I've seen this bug before, but I haven't been able to fix it before.

**Comment by Pokemiah** [comment]
I see. I don't know much about the inner workings of emulators so I can't give much advice on this other than to check the renderer to see how to improve the logic to increase performance but that would be stating the obvious. Anyway, I hope you'll be able to figure out how to fix this bug in the future.

**Comment by endrift** [comment]
I finally figured out the issue. It's fixed now, and latest builds (going up in a few minutes) should have this fixed.
