### ISSUE TITLE
Nectaris GB (Japan) hangs on a blank screen on every Game Boy model.

### ISSUE THREAD

**Issue by MapleStoryPSN** [mgba-emu/mgba#1214]
Tested both the base rom and the English fan-translation on RetroPie running lr-mGBA 0.7-WIP. Both work fine on lr-gambatte.

Also, would like to thank you guys for getting Bomberman Selection working!

**Comment by endrift** [comment]
Seems to work for me. What's the SHA1 of the base ROM you have?

**Comment by MapleStoryPSN** [comment]
I just updated from source and it works properly. I guess the core was just outdated, so false alarm.
