### ISSUE TITLE
Mario Golf - Advance Tour crashes when rewinding

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#1216]
Using mGBA-build-2018-10-13-win32-5380-4d383b129dd51083a917f5c82ec9f3314c577a65 I get this error.

![capture10-15-2018-2 51 22 pm](https://user-images.githubusercontent.com/21169038/46974993-19ff6680-d08b-11e8-896e-db4a45b5f1ed.jpg)
 
I only get this error when I press Rewind it's at random.

Here is my log maybe it will help.

[Logs.zip](https://github.com/mgba-emu/mgba/files/2480373/Logs.zip)

**Comment by endrift** [comment]
What game?

**Comment by Cibomatto2002** [comment]
Mario Golf - Advance Tour (USA)

**Comment by endrift** [comment]
Please retest in latest dev.

**Comment by Cibomatto2002** [comment]
I tried to make it cash for 30 minutes now so far it has not crashed so maybe it is fixed now. :)

**Comment by endrift** [comment]
Thanks for testing. I did fix a lot of savestate bugs recently.

**Comment by Cibomatto2002** [comment]
Thanks for all the work you do on this emulator i enjoy it on a daily basis.  I wonder why retroarch has not updated the mGBA core? I need the updated core for my rasberry pie 4.

**Comment by endrift** [comment]
Their version is aligned with 0.8.3, though their build infrastructure was recently hacked, so I'm not sure what the status of any of it is.
