### ISSUE TITLE
Add Simple filter like Scanlines or TV mode to 3DS version.

### ISSUE THREAD

**Issue by NCorp-Studios** [mgba-emu/mgba#122]
Can you add a simple filter like scanlines or tv mode to the 3DS version. It would be really convenient.

**Comment by endrift** [comment]
The 3DS does not have pixel shaders, making this impossible to do in hardware, and it would be slow to do it in software. I'd prefer to save those cycles for emulation.

**Comment by NCorp-Studios** [comment]
Okay. I didn't know that the 3DS didn't have pixel shaders. I like mGBA very much though. Keep up the good work.
