### ISSUE TITLE
[libretro] FLASH512 saves are broken

### ISSUE THREAD

**Issue by jdgleaver** [mgba-emu/mgba#1221]
As of commit 830cad3e7bc24281d8d9da31672c020693a17c5b, games with the FLASH512 save type no longer save correctly, nor can existing saves be loaded. For example, "Golden Sun (USA, Europe)" produces this error when attempting to save:

![golden sun usa europe -181024-111809](https://user-images.githubusercontent.com/38211560/47426536-64689d80-d785-11e8-9a10-9fc92f8901b2.png)

The issue only affects the libretro core, and I think I can see why:

Commit 830cad3e7bc24281d8d9da31672c020693a17c5b adds this check:

https://github.com/mgba-emu/mgba/blob/830cad3e7bc24281d8d9da31672c020693a17c5b/src/gba/savedata.c#L259-L265

...but since the save data is initialised like this in src/platform/libretro/libretro.c:

https://github.com/mgba-emu/mgba/blob/830cad3e7bc24281d8d9da31672c020693a17c5b/src/platform/libretro/libretro.c#L491-L492

...the ``} else if (end >= SIZE_CART_FLASH1M) { `` condition is always met, and FLASH512 games are incorrectly assigned a type of FLASH1M.

I only had a quick look at the code, so I may be wrong - but I hope this helps solve the issue.

**Comment by blackman91** [comment]
Yeah I can confirm this not saving bug on RetroArch using the mgba core, it even happens on RetroArch for Android.

**Comment by SilentHeII** [comment]
Yep. Sonic Advance 2 starts with everything unlocked on the latest Retroarch build which indicates a bad save.
