### ISSUE TITLE
0.7 beta does not load 0.6.3 savestates in GB and GBC

### ISSUE THREAD

**Issue by dart193** [mgba-emu/mgba#1222]
I have quite a lot games in progress that do not have battery save, so I have to use savestates, and it looks like the new beta is not able to load 0.6.3's savestates. This happens only in GB and GBC games: GBA still loads fine, and battery saves are working properly in GB, GBC and GBA. I tried to play with old save file to make it work in 0.7, but was not able to get correct result. 0.7's savestates seem to be bigger by 20 kilobytes.

**Comment by endrift** [comment]
There is no guarantee of compatibility between versions (in pretty much any emulator). I try but it's never perfect.
