### ISSUE TITLE
No build instructions for other platforms

### ISSUE THREAD

**Issue by pixel-stuck** [mgba-emu/mgba#1223]
As the title says, there's no clear instructions anywhere I could find to build for non-pc platforms. I figured it out after 20 minutes of screwing around, but it'd be nice to just have some instructions in the readme.

For example, for 3ds
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=../src/platform/3ds/CMakeToolchain.txt ..
make

of course you might also want to add something about the differing dependencies/toolchains
Thanks :)

**Comment by endrift** [comment]
Good idea. I'll look into doing this soon.

**Comment by pixel-stuck** [comment]
Looks like this was resloved; closing
