### ISSUE TITLE
[libretro] Rewinding when writing sram causes crash and file corruption 

### ISSUE THREAD

**Issue by fennectech** [mgba-emu/mgba#1225]
If you rewind to the point when you last saved your game the application will crash and potentially corrupt your sram file.     Simple solution is to dump rewind buffer when writing sram.

**Comment by endrift** [comment]
Is this still an issue? I think this got fixed a wihle ago but I'm not sure.

**Comment by fennectech** [comment]
with how old this is. I have no idea

**Comment by endrift** [comment]
Can you test it...?

**Comment by fennectech** [comment]
I. Honestly dont even remember what it was on. But i will give it a try in a couple weeks if you remind me Life is litteraly insane rn and the switch is packed away   (Also.  The original system it was on has long since died and been replaced with a chipped OLED if that changes things
