### ISSUE TITLE
Having trouble with search memory trying to make cheats codes.

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#1227]
Trying to make cheat codes with the search memory but can't make a one even tho I know how to make them game to try Metroid 2 I tried a few other games but with no luck.

mGBA-build-2018-11-03-win32-5390-ed0a7c68eab07e4dca5b2744b2a45ef7b00917b1

**Comment by endrift** [comment]
Closing in favor of...another issue you also filed #772
