### ISSUE TITLE
Wii loses video output when launching mGBA while connected through HDMI.

### ISSUE THREAD

**Issue by Maesejesus** [mgba-emu/mgba#1228]
Hi. I'd like to inform a problem with the Wii port of mGBA.

If you have your Wii connected through an HDMI adapter, whenever you enter mGBA, you lose signal with the console. This is because when launched, mGBA must change the resolution of the system, reset the video signal or something like that; causing this issue. This quirk started a few months ago (it didn't happen before, there was no video change at all), and back then the TV was able to recover the connection, but since 0.7.1 and its nightlies, it's impossible for my TV to get any video signal.

This doesn't happen when using other applications that may change the video format or resolution. For example, Nintendont may change it when launching a PAL GC game, but it just takes a couple seconds to get image back. With mGBA you just lose it.

Of course, I'm calling it a problem if mGBA still works at 480P/I. I know for a fact that HDMI adapters don't do 240P, although I kinda doubt if mGBA now boots itself on that resolution. I'll keep messing with it, though.

**Comment by endrift** [comment]
Can you track down when it started breaking? The old builds are still available at https://mgba.io/builds/0/

**Comment by Maesejesus** [comment]
At last, I found it!

The last nightly where it didn't make that video reset is from 23rd March: 5053-7a53c35
https://github.com/mgba-emu/mgba/commit/7a53c35123f9d3033e18afc05660b017c956181c

The next nightly, started to make the video reset thing: 5054-ea2159d
https://github.com/mgba-emu/mgba/commit/ea2159d159f2ddb5514b9137a116eb74a2ed872f

**Comment by endrift** [comment]
Not sure what changed but sounds good.
