### ISSUE TITLE
Add VisualBoyAdvance-style printf SWI support

### ISSUE THREAD

**Issue by HorstBaerbel** [mgba-emu/mgba#1230]
Running my binary with VBA I can print strings using a SWI 0xFF:
```
#if defined(__thumb__) || defined(_M_ARMT)
	void print(const char *s) // THUMB code
	{
		asm volatile("mov r0, %0;"
					"swi 0xff;"
					: // no ouput
					: "r" (s)
					: "r0");
	}
#else
	void print(const char *s) // ARM code
	{
		asm volatile("mov r0, %0;"
					"swi 0xff0000;"
					: // no ouput
					: "r" (s)
					: "r0");
	}
#endif
```
We all know mGBA is soo much better than VBA :wink:, but is there a similar facility in mGBA? This was very practical for printf-debugging and especially profiling without too much overhead... In mGBA I get a unsupported BIOS call error message (which is correct actually).

**Comment by endrift** [comment]
Yup, support files are included in this directory: https://github.com/mgba-emu/mgba/tree/master/opt/libgba
