### ISSUE TITLE
Mute bug when pressing Tab or Shift + Tab Keys

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#1234]
Mute bug when pressing Tab or Shift + Tab Keys it will unmute when pressing those keys.

 mGBA-build-2018-11-10-win32-5394-9262475cb47c1bbfd4422591394b789ce18f6b6b

**Comment by endrift** [comment]
Make sure it's set to mute when fast forwarding. This is split out now.
