### ISSUE TITLE
Legend of Zelda, The - The Minish Cap (USA) not loading saved game

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#1236]
Trying to save the game and it will not so i'm having to use quick save to save game and quick load to load game i'n my save folder you can see there is a saved games but it never loads. here is a video of me saving the game and trying to reload it.

https://www.youtube.com/watch?v=rXVuFiSLBwg&feature=youtu.be

Here is the save file it makes. 
[Legend of Zelda, The - The Minish Cap (USA).zip](https://github.com/mgba-emu/mgba/files/2592598/Legend.of.Zelda.The.-.The.Minish.Cap.USA.zip)

mGBA-build-2018-11-17-win32-5396-dd7e422bde762063efded268abc8f14b06821e03

**Comment by endrift** [comment]
How old is your quick save? Very old quick saves seem to improperly store the savetype, which breaks saving after loading the state. See what happens if you save without having loaded a quick save first.

**Comment by Cibomatto2002** [comment]
I think I found out what it was someone deleted my game then tried to save it again with a Quicksave and broke the normal game save. the quicksave was on the mGBA-build-2018-11-17-win32-5396-dd7e422bde762063efded268abc8f14b06821e03 build. here is the quick save if you want to try it out.

[Legend of Zelda, The - The Minish Cap (USA).zip](https://github.com/mgba-emu/mgba/files/2598049/Legend.of.Zelda.The.-.The.Minish.Cap.USA.zip)
