### ISSUE TITLE
Controller-mapped fast forward stops working after accessing menu items

### ISSUE THREAD

**Issue by Sagiri** [mgba-emu/mgba#1237]
I have fast forward mapped to RB on my controller, and if I have to use the menus (for example, to pause emulation or take a screenshot) occasionally mGBA will start ignoring that mapping and I can't toggle the fast forward state with my controller any more until I close and relaunch the emulator.

The controls for the game itself continue to work. I don't know if mapping e.g. pause emulator has the same problem since I've never tried it.

I've experienced this over several versions of mGBA.

**Comment by endrift** [comment]
Please try a dev build, I believe this was fixed recently

**Comment by Sagiri** [comment]
I tried it and I couldn't get the bug to happen. It was happening consistently enough to say that, indeed, this has been fixed.

Thank you.
