### ISSUE TITLE
Make register values more distinct in the debug console

### ISSUE THREAD

**Issue by Sagiri** [mgba-emu/mgba#1238]
The current way the console displays the state of the registers is:

```
00000001 00000004 030030F0 00000001
00000000 030030E4 030030E4 030030F0
00000000 00000000 00000000 00000000
00000040 03007E24 080004AB 080008B0
```

Would it possible to change that slightly to:

```
R00=00000001 R01=00000004 R02=030030F0 R03=00000001
R04=00000000 R05=030030E4 R06=030030E4 R07=030030F0
R08=00000000 R09=00000000 R10=00000000 R11=00000000
R12=00000040 R13=03007E24 R14=080004AB R15=080008B0
```

As a related suggestion/alternative, would it be possible to add a `r/r` command to easily read the value from a particular register as a counterpart to `w/r`?

**Comment by endrift** [comment]
The opposite of `w/r` is `p`

**Comment by Sagiri** [comment]
Oh, you have to do (e.g.) `p r3`. I didn't even think to try that because the description made it sound like it was just for displaying literal values.

I only suggested `r/r` because the other `w/?` commands all have `r/?` counterparts.

**Comment by endrift** [comment]
That's reasonable, but I'm not sure it's that useful all told.
