### ISSUE TITLE
3DS: GUI doesn't cleanup when closed

### ISSUE THREAD

**Issue by FayneAldan** [mgba-emu/mgba#124]
Unless FPS display is turned on, the GUI doesn't clear on the bottom screen, either when you close the the GUI or you load the ROM (as the GUI says "Loading...").

**Comment by endrift** [comment]
Known bug; I didn't have enough time last night to fix it and thought it was more useful to push it out and fix it tonight.

**Comment by FayneAldan** [comment]
Is this fixed yet...?

**Comment by endrift** [comment]
I'm literally working on it *right now*.
