### ISSUE TITLE
symbol lookup error FFmpegEncoderSetVideo

### ISSUE THREAD

**Issue by LaBatata101** [mgba-emu/mgba#1244]
- OS: Manjaro 18.0
Got this error after updating my manjaro
`mgba-qt: symbol lookup error: mgba-qt: undefined symbol: FFmpegEncoderSetVideo`

**Comment by LaBatata101** [comment]
The weird thing is that the mgba 0.7.0-beta1 works fine.
The version I was using was 0.6.3-1.0

**Comment by endrift** [comment]
Did you build 0.6.3 from the PKGBUILD? It's possible your libmgba is out of sync.

**Comment by LaBatata101** [comment]
It's from the oficial repositories

**Comment by endrift** [comment]
Is this still an issue?

**Comment by endrift** [comment]
Closing due to lack of reply.
