### ISSUE TITLE
Gameboy: Super Mario Land 1 Color Hack frequent skips to updating statusbar digits

### ISSUE THREAD

**Issue by Searinox** [mgba-emu/mgba#1253]
Tested on New Nintendo 3DS with latest commit as of posting this.

Patch location: https://www.romhacking.net/hacks/1187/

Videos of the hack can be found online. Some color application delay and shortlived tile color glitching and pixels below the statusbar flickering are normal.

What is not normal is that sometimes statusbar numbers will not update. One digit may update while others may not. This can happen with the score and coins also but the most frequent occurrence is the timer. If you simply wait for the timer to tick down, you will frequently see digit changes skipped; for example the timer will count down from 400, 399 down to 390 then it will proceed with 399 again, then 398, 397... until it reaches 390 then it will update to 379 suddenly or maybe it won't and it will do it on the next count. Single increments also often skip, for example 399, 398, 396, 394, 392.... This can also be observed in the bonus games when Mario wins extra lives, he jumps and the number sometimes doesn't increase, but it will be correctly displayed on next level. As the score increases level transitions can make entire digits disappear altogether and the updates to the number become infrequent.

This does not happen on other emulators. Also tried on a GB flashcart and confirmed not to be happening. Video playthroughs you can find around also update normally.

**Comment by retro-wertz** [comment]
nah, seems to happen even on hardware https://www.youtube.com/watch?v=kSsb5hemrQM

**Comment by Searinox** [comment]
Seems I messed up. I will investigate this further.
