### ISSUE TITLE
Library problem

### ISSUE THREAD

**Issue by roracle** [mgba-emu/mgba#1255]
When I go to load a ROM, it doesn't save the location I was last using (/home/roracle/Emulation/GBA/roms/).
So I set up the library directory, and nothing was shown on the screen.
I had to select "Show when no game open" option, so the list showed up finally.
However, when I double-click a title, it just sits there like a bump on a log.
Expected behavior: double-click a title in the list view and start the game.

**Comment by endrift** [comment]
What build are you using? I don't seem to be able to reproduce this anymore.

**Comment by endrift** [comment]
Are you still able to reproduce this?

**Comment by endrift** [comment]
Closing due to lack of reply.
