### ISSUE TITLE
Donkey Kong (World) (Rev A) (SGB Enhanced) bug

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#1256]
When playing Donkey Kong (World) (Rev A) (SGB Enhanced) you never here  Lady say help but in this video you can here her say it. 

https://youtu.be/t2iicAjF9xI?t=121

mGBA-build-2018-11-23-win32-5402-38bad71e119aa71f9c89d066fdfe589d3cdfd2e6

**Comment by bentley** [comment]
This is a SGB audio feature, like the applause in Kirby’s Dreamland 2. Unless something’s changed since #223, @endrift has no plans to implement it.

**Comment by Cibomatto2002** [comment]
Oh ok I thought it was a bug.
