### ISSUE TITLE
Super Mario Land gameboy sound distortion after dying

### ISSUE THREAD

**Issue by Invictaz** [mgba-emu/mgba#1257]
Each time after you die in world 2-1 the sound becomes worse. More cracks and distortion.
The only option to fix this is go into the menu or pause / unpause.

I'm not sure which one of the two fixed it. 

OS:  VITA

**Comment by endrift** [comment]
Can you upload a save game?

**Comment by Invictaz** [comment]
Super Mario Land 1 doesn't have savegames. Only states. Here is one.

**Comment by endrift** [comment]
This was probably just a general Vita sound quality issue. Closing unless you can get it to happen again.
