### ISSUE TITLE
Building 3DSX on Windows is faulted

### ISSUE THREAD

**Issue by FayneAldan** [mgba-emu/mgba#126]
Building the 3DSX file on Windows (using MINGW32) is a bit faulted...
```
$ cmake .. -D3DS=TRUE -G "MSYS Makefiles"
-- The C compiler identification is GNU 4.9.2
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    C:/devkitPro/devkitARM/bin/arm-none-eabi-gcc

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
```
At this point, I set `CMAKE_C_COMPILER` to the path given above, but with `.exe` added to the end.
```
$ cmake .. -D3DS=TRUE -DCMAKE_C_COMPILER=C:/devkitPro/devkitARM/bin/arm-none-eabi-gcc.exe -G "MSYS Makefiles"
-- The C compiler identification is GNU 4.9.2
-- Check for working C compiler: C:/devkitPro/devkitARM/bin/arm-none-eabi-gcc.exe
-- Check for working C compiler: C:/devkitPro/devkitARM/bin/arm-none-eabi-gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: C:/msys32/mingw32/bin/pkg-config.exe (found version "0.28")
-- The ASM compiler identification is GNU
-- Found assembler: C:/devkitPro/devkitARM/bin/arm-none-eabi-gcc
CMake Error at CMakeLists.txt:183 (enable_language):
  The CMAKE_ASM_COMPILER:

    C:/devkitPro/devkitARM/bin/arm-none-eabi-gcc

  is not a full path to an existing compiler tool.
```
Then I did the same thing with `CMAKE_ASM_COMPILER`.
```
$ cmake .. -D3DS=TRUE -DCMAKE_C_COMPILER=C:/devkitPro/devkitARM/bin/arm-none-eabi-gcc.exe -DCMAKE_ASM_COMPILER=C:/devkitPro/devkitARM/bin/arm-none-eabi-gcc.exe -G "MSYS Makefiles"
```
This worked. However, I highly doubt this was intended. The first command should have worked.

**Comment by endrift** [comment]
It IS broken, but the first command isn't correct either. You just gave it a compiler, not actually the toolchain telling it what to do.

But it is broken on windows so giving you the right directions for other platforms won't make it work either.

**Comment by FayneAldan** [comment]
The compiler it tries to use (if one isn't specified) DOES exist, but it claims it doesn't exist, simply because the compiler is an exe file.

**Comment by FayneAldan** [comment]
As a side note:
```
[ 82%] Built target mgba
[ 83%] picasso uishader.vsh
/bin/sh: /C/devkitPro/devkitARM/bin/picasso: No such file or directory
make[2]: *** [3ds/uishader.shbin] Error 127
make[1]: *** [3ds/CMakeFiles/mgba.elf.dir/all] Error 2
make: *** [all] Error 2
```
That `picasso` file doesn't seem to exist anywhere in my devkitPro directory...

**Comment by endrift** [comment]
picasso isn't included in devkitARM yet. It will be in next one, I think. https://github.com/fincs/picasso

**Comment by FayneAldan** [comment]
Okay... So, I just realized that the reason it WAS compiling to 3DS was because I also ran [the command here](https://forums.mgba.io/showthread.php?tid=27&pid=93#pid93) (changing wii to 3ds) before doing anything I said in the first post. I didn't realize the effect from that carried over into the following commands.

**Comment by endrift** [comment]
Please let me know if this is fixed in 9a538f872a78f7964d808d5a042474d563b4eb71. You'll need to delete the CMakeCache and CMakeFiles files first, then redo `cmake .. -DCMAKE_TOOLCHAIN_FILE=../src/platform/3ds/CMakeToolchain.txt`.

**Comment by FayneAldan** [comment]
```
$ cmake .. -DCMAKE_TOOLCHAIN_FILE=../src/platform/3ds/CMakeToolchain.txt
-- Building for: NMake Makefiles
CMake Warning at CMakeLists.txt:2 (project):
  To use the NMake generator, cmake must be run from a shell that can use the
  compiler cl from the command line.  This environment does not contain
  INCLUDE, LIB, or LIBPATH, and these must be set for the cl compiler to
  work.


-- The C compiler identification is GNU 4.9.2
-- Check for working C compiler: C:/devkitPro/devkitARM/bin/arm-none-eabi-gcc.exe
CMake Warning at CMakeLists.txt:2 (project):
  To use the NMake generator, cmake must be run from a shell that can use the
  compiler cl from the command line.  This environment does not contain
  INCLUDE, LIB, or LIBPATH, and these must be set for the cl compiler to
  work.


CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO" "cmTC_19d09\fast"
-- Check for working C compiler: C:/devkitPro/devkitARM/bin/arm-none-eabi-gcc.exe -- broken
CMake Error at C:/msys32/mingw32/share/cmake-3.3/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "C:/devkitPro/devkitARM/bin/arm-none-eabi-gcc.exe" is not
  able to compile a simple test program.

  It fails with the following output:

   Change Dir: C:/msys32/home/Deanna/mgba/build/CMakeFiles/CMakeTmp



  Run Build Command:"nmake" "/NOLOGO" "cmTC_19d09\fast"

  The system cannot find the file specified

  Generator: execution of make failed.  Make command was: "nmake" "/NOLOGO"
  "cmTC_19d09\fast"





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "C:/msys32/home/Deanna/mgba/build/CMakeFiles/CMakeOutput.log".
See also "C:/msys32/home/Deanna/mgba/build/CMakeFiles/CMakeError.log".
```

**Comment by endrift** [comment]
Oh sorry, delete those files again and do it with `-G "MSYS Makefiles"` this time, too. I build on Windows so infrequently that I forget CMake does this.

**Comment by FayneAldan** [comment]
`cmake` was successful. I'm testing `make` now. Last time I tried `make` though (when I manually provided the compiler paths), I was given an error because `bannertool` couldn't be found. I'm guessing that's also something in the next version of devkitARM?

**Comment by endrift** [comment]
I believe Picasso will be in r45, but I don't know about bannertool. Shouldn't be too hard to find them, although I'm not sure how easy to compile on windows they are. Regardless, the base bugs have been fixed now, it seems. Hopefully these tools will be in r45, whenever that lands.

**Comment by FayneAldan** [comment]
I just wanna say: The only reason I was trying to compile it was because the nightly build is from two days ago. (and it still is)

**Comment by endrift** [comment]
I didn't push last night. There should be a new nightly in 4 hours, but not much has changed.

**Comment by roytam1** [comment]
Leave a note here for reference on get pass for CMake on Windows:

````
cmake -D3DS=TRUE -G "MSYS Makefiles" -DCMAKE_C_COMPILER=$DEVKITARM/bin/arm-none-eabi-gcc.exe -DCMAKE_CXX_COMPILER=$DEVKITARM/bin/arm-none-eabi-gcc.exe -DCMAKE_ASM_COMPILER=$DEVKITARM/bin/arm-none-eabi-gcc.exe -DCMAKE_AR=$DEVKITARM/bin/arm-none-eabi-ar.exe -DCMAKE_SYSTEM_NAME=Generic
````
