### ISSUE TITLE
Automatically load matching No$GBA-style .sym files when loading a ROM

### ISSUE THREAD

**Issue by Zeturic** [mgba-emu/mgba#1260]
No$GBA uses `.sym` files to load information about the symbols in a ROM. For example, if you have the following:

```00000000 0
80000000 .dbl:0010
80000010 main
8000002C subroutine
80240000 newblock
```

In a file named `rom.sym` and then open `rom.gba` in No$GBA, it will load those symbols and then you can use them for setting breakpoints and jump to them in the disassembly view (etc).

Would it be possible to include this in mGBA?

**Comment by endrift** [comment]
Symbol files should already be loaded, but the symbols don't show up in disassembly yet.

**Comment by Sagiri** [comment]
I swear I tried and they weren't being recognized for breakpoints in the debug menu. I'm probably just on an outdated build, though.

**Comment by Zeturic** [comment]
PPSSPP and PCSX2 have a slight variation on the format which can include the lengths of functions. For example:

```
00000000 0
80000000 .dbl:0010
80000010 Main
8000002C Subroutine,0000001C
80240000 NewBlock,00000014
```

Would it be possible for mGBA to support this format as well? I can't think of anything mGBA could do with the function lengths (especially since they're not guaranteed for every label), so it'd basically just be throwing away everything after an including a comma.

**Comment by endrift** [comment]
Both parts of this issue should now be fixed.
