### ISSUE TITLE
Slowdown on nightlies since0.7 b1 in n2ds and vita

### ISSUE THREAD

**Issue by Turbito** [mgba-emu/mgba#1264]
Hi, I was testing the latest nightly downloaded from the mgba site. A few days ago I downloaded one, (can't remeber the build id, sorry) but today download the latest nightly, https://github.com/mgba-emu/mgba/commit/6a5ce56f73d4df6f841324eca08b79c0792f4cc2

These two seems to run super slower than the builds from 0.7b1 that run decently.
The builds was tested in  my n2ds (latest fw version, latest luma version fwiw) and psvita.

I don't know if it's my configuration (¿¿) or it's some type of regression.

Tested Pokémon Emerald (crash on save) and FF Tactics Advance.

**Comment by endrift** [comment]
How much has it slowed down? I don't notice any difference.

**Comment by Turbito** [comment]
It drops from about full speed to 48fps in average in my vita, and with choppy sound (it didn't happen in 0.7 beta 1).
In the n2ds is similar (running as cia, ofc)
I haven't tested it in other platforms, sorry. But if it is necessary I can provide logs although I don't know how to.

**Comment by Turbito** [comment]
ok, with latest commit emerald no longer crashes saving, but in FFTA there are significative framerate drops (with choppy audio) while in 0.7b1 just works fine.

**Comment by endrift** [comment]
Can confirm with FFTA on the Vita.

**Comment by endrift** [comment]
Fixed in 029d0e169b154dd60e02a0134da25328f8719de1.
