### ISSUE TITLE
Possible regression with noise channel volume level

### ISSUE THREAD

**Issue by kode54** [mgba-emu/mgba#1265]
As reported here:

https://hydrogenaud.io/index.php/topic,117161.0/topicseen.html

> I recently updated GSF Decoder from 3.0.7 to 3.0.8 and I've noticed that it sounded off. I've uploaded some files comparing how the Wild Pokémon theme from FR/LG sounds like in 3.0.7, 3.0.8, and from a 3DS. As you can hear, the noise channel is a lot quieter in the new version. Is there a way to revert back to the old version for now?

Attaching their files here for convenience.

[3.0.7.ogg.gz](https://github.com/mgba-emu/mgba/files/2757419/3.0.7.ogg.gz)
[3.0.8.ogg.gz](https://github.com/mgba-emu/mgba/files/2757421/3.0.8.ogg.gz)
[3DS.ogg.gz](https://github.com/mgba-emu/mgba/files/2757423/3DS.ogg.gz)

Another example, whether you have it now or not, the Space Pirate Mother Ship from Metroid - Zero Mission. The noise channel is quite obvious there.

[35 Space Pirate Mother Ship.gba.gz](https://github.com/mgba-emu/mgba/files/2757444/35.Space.Pirate.Mother.Ship.gba.gz)

**Comment by kode54** [comment]
Here is the commit which causes it:
555122e0a1bc1311040e6ff7a8b2d95090fa76ca

Here are some audio samples:
[Original audio before the change](https://github.com/mgba-emu/mgba/files/2777566/moo1.flac.gz)
[Audio after more precision added](https://github.com/mgba-emu/mgba/files/2777567/moo2.flac.gz)
[Audio after a blep buffer instance with timestamps added onto the process](https://github.com/mgba-emu/mgba/files/2777570/moo3.flac.gz)

This branch attempts to correct it, but I want some feedback first. It still seems way too quiet compared to just truncating to the nearest sample.

https://github.com/kode54/mgba/commit/ac40bb45dc024b7e34c39427a4bb5533ff508d24

**Comment by easyaspi314** [comment]
Yeah this is definitely a regression, and it still hasn't been fixed. :frowning:

Looking at both kode54@ac40bb4 commit and kode54@4c9fc990, the latter is definitely better, but there are still a few issues with the patch. Some noise samples can sound a little crackly.

This can be easily noticed in FRLG with the 'ksh-ksh-ksh-ksh' of exiting a room or in the beginning 'whoosh' in the Trainer battle theme.

Can't get audio recording to work properly on my MacBook, so here is a recording from mGBA with the kode54@4c9fc990 patch manually applied. It didn't sync properly but the audio is fine.  
[mgba noise.mp4.gz](https://github.com/mgba-emu/mgba/files/3364922/mgba.noise.mp4.gz)

**Comment by Kurausukun** [comment]
Another good way to compare using Pokemon is opening the start menu or running away from a battle. Both of those use the noise channel and sound noticeably off. I'd also really like to see this fixed, seeing as the updated core is now also being used in BizHawk, so the issue has migrated there as well.

**Comment by endrift** [comment]
I've looked into this and it's unfortunately not going to be easy to fix. Pokémon FR/LG does some nasty stuff with the noise channel that my sub-sampling approach introduced in 0.7 averages out. This decimates the range of the noise channel in the actual samples, making it very quiet. Without implementing something more robust I'm not sure how to properly fix this, and a robust fix will take a fair amount of time and effort. The old version just didn't sub-sample, so it had a problem with how some other games use the noise channel. kode54's fix is, at best, a hack to prevent the range decimation, but is at least somewhat effective.

**Comment by endrift** [comment]
Turns out channel 4 (and all of the GB channels) are aliased in such a way that I had been emulating but was supersampling to attempt to smooth out--this was incorrect for GBA audio, and has been disabled in GBA mode.
