### ISSUE TITLE
2DS Xl [SGB] - Kirby Dream Land 2 doesnt load/boot

### ISSUE THREAD

**Issue by mddifilippo89** [mgba-emu/mgba#1266]
Running the latest nightly 1/14/19.

The game is distorted and freezes on launch. You do see the SGB border if you specify BIOS files. Otherwise I was I getting a black screen.

**Comment by endrift** [comment]
Having trouble reproducing. Have you tried without BIOS?

**Comment by mddifilippo89** [comment]
I had to remove the autogenerated mGBA folder from the root of the SD card that contains the paths to my BIOS and remove any extra files created when saving the game. When I started back up again the game started. 

If I exit or reset, the game the system freezes. The system also crashes when quitting mGBA and reopening mGBA. (wasn't happening in the latest stable build)

I can create a separate bug for these.

**Comment by endrift** [comment]
.cia or .3dsx?

**Comment by mddifilippo89** [comment]
I use .3dsx. Acquired Homebrew through Jack Sorrell's steel diver method fyi.

**Comment by mddifilippo89** [comment]
How come SGB is integrated but GB games still show up in black and white?

**Comment by endrift** [comment]
SGB only applies to games with explicit SGB support, like Pokémon Red. It doesn't touch games that don't have explicit support unless you override it.

**Comment by mddifilippo89** [comment]
Okay so what I can try is simply adding back only the GBA Bios.

**Comment by mddifilippo89** [comment]
The latest patch fixed alot of the issues I was having. 

https://github.com/mgba-emu/mgba/issues/1371
