### ISSUE TITLE
[3DS] System crashes 

### ISSUE THREAD

**Issue by mddifilippo89** [mgba-emu/mgba#1267]
Crashes occur: .3dsx

1. resetting a game
2. quitting a game. 
3. backing out to homebrew and then back into mGBA. 
4. loading a save state (intermittent)
5. Cancelling in menu

**Comment by mddifilippo89** [comment]
Did you test the nightly?

**Comment by mddifilippo89** [comment]
Also, the GBA games I've tested (Mario Kart and Metroid Fusion) won't start. Stuck on loading.

**Comment by mddifilippo89** [comment]
If I go back 0.6.3 then everything starts working as it should.

**Comment by mddifilippo89** [comment]
FYI, I've been using unzipped games. I quickly tested a zipped file and I was able to quit and select a new game.

**Comment by endrift** [comment]
Forward duping to #1281.
