### ISSUE TITLE
Bug when adding a breakpoint using GDB

### ISSUE THREAD

**Issue by macabeus** [mgba-emu/mgba#1268]
To debug a game, I need to set some breakpoints at a specific memory address. But when I set a breakpoint using GDB by `break *0x0800696E` command, or by IDA Pro, the game restart and stop when I start the debug session.
This behaviour didn't happens if I start the debug session with none breakpoint. 

This bug also happens when I use some IDA's feature, such as "Execute instructions until the cursor is reached".

**Comment by macabeus** [comment]
@endrift
Thank you for the fast reply!

When I said "restart and stop", I meant that "the game restarted (shows the Namco's logo), but then keep in a black screen".
Let me show gifs to explain it better...

If I set none breakpoint, everything works:
![peek 2019-01-16 03-45](https://user-images.githubusercontent.com/9501115/51228860-50c27280-1941-11e9-9e5c-ac9f03aaf0b6.gif)

If I set one breakpoint, "restart and stop":
![peek 2019-01-16 03-54](https://user-images.githubusercontent.com/9501115/51229156-80be4580-1942-11e9-94e5-c1e84e674b76.gif)

**Comment by endrift** [comment]
This is a result of trying to set a breakpoint in Thumb code while running in ARM mode. The GDB protocol doesn't really have a good way to fix this, so what you need to do is step through until you hit Thumb code and then set the breakpoint.

**Comment by macabeus** [comment]
@endrift Thank you for replay. I tried following your idea but I still can't make the breakpoint work =/

Using IDA, I checked if the current instruction is a Thumb code ([the value is 01, then we are at a Thumb code](https://reverseengineering.stackexchange.com/a/12701)):
![image](https://user-images.githubusercontent.com/9501115/51233161-4e1b4980-1950-11e9-9230-212b1ca38e72.png)
Then I add my breakpoint at another Thumb code... but it still not working. The emulator restart and stop.

I also tried using only the GDB console, but I didn't can run a single command. I tried using the GDB's command `s` and ` si`, but both fails.
`s` fails and show the message `Cannot find bounds of current function`, and `si` only keep it on the same address:

```
(gdb) s
Cannot find bounds of current function
(gdb) si
0x03003589 in ?? ()
(gdb) si
0x03003589 in ?? ()
(gdb) si
0x03003589 in ?? ()
```


Do you have a idea about how to make the breakpoint work?

**Comment by endrift** [comment]
I don't know how to get IDA working. I don't think IDA's gdb support is that great.

As for gdb itself, I'm not sure how you even wound up at that address. It's not valid. Try again? `si` _is_ what you want to use.

**Comment by macabeus** [comment]
@endrift  Well... I also don't know how GDB arrived at this address. I only opened the rom, started the GDB server, and connected the GDB client using the command `target remote localhost:2345`.

I tried using others game roms, but I had the same error. But using the others roms, the address showed at GDB is `0x000000`. But the commands `s` and `si` still doesn't work.
I also checked using Linux, and I get the same problem.

Do you can use GDB debugger in your computer?
