### ISSUE TITLE
Very slow/high FPS when using Qt as the display driver

### ISSUE THREAD

**Issue by macabeus** [mgba-emu/mgba#1269]
When I start a ROM using Qt as the display driver, the emulator run very slowly (< 10 FPS). Then, a workaround that I did was enabling `Fast forward` option, but the game run with a very high FPS (> 300).

I need to use Qt because I'm running mGBA at a Windows VirtualBox, where I do not have OpenGL.

**Comment by endrift** [comment]
Make the window smaller.

This isn't a bug, it's just a limitation of software rendering.
