### ISSUE TITLE
[Android] [Libretro] Final Fantasy Tactics Advance can't save.

### ISSUE THREAD

**Issue by Chronosplit** [mgba-emu/mgba#1270]
Whenever I access the menu for saved games, I get an "error in backup memory" message and all save functions are greyed out.  This also happens when there is no savefile present, after deleting the .srm file.

This issue is not present in any other GBA core.

**Comment by Chronosplit** [comment]
Latest online update from this morning, which according to RA is 0.7b1 c32d831

**Comment by endrift** [comment]
Odd, wonder why their core isn't up to date. This was fixed in the very next commit.

**Comment by ulinvega** [comment]
I also have this issue with mGBA on android. Hope it gets resolved soon.

**Comment by shlomi-toren-sp** [comment]
I'm getting this issue with Tactics Ogre as well.

**Comment by endrift** [comment]
This has been fixed by now.
