### ISSUE TITLE
Redirect debug information to STDOUT

### ISSUE THREAD

**Issue by sweetpalma** [mgba-emu/mgba#1273]
<img width="595" alt="2019-01-19 14 28 04" src="https://user-images.githubusercontent.com/17027163/51426834-e76c8900-1bf8-11e9-91d8-d93b4dc7b416.png">

Is it possible to redirect the following debugger information right to the STDOUT of `mgba` running in terminal? I've tried different values for `--log-level` option, no luck so far.

**Comment by sweetpalma** [comment]
<img width="1050" alt="2019-01-19 14 44 57" src="https://user-images.githubusercontent.com/17027163/51438927-9376a880-1cbb-11e9-8433-bf37fd71656e.png">
Unfortunately, it does not seem to work 😢

**Comment by endrift** [comment]
Ah, right, you can't do it atm with the Qt frontend. The SDL frontend prints to stdout only. I intend to fix this with the logging revamp I'll do eventually.

**Comment by sweetpalma** [comment]
Is there any way to run SDL frontend on OSX? I see two packages `mgba-qt` and `mgba-sdk` for Ubuntu, but not alternative version for OSX, is any available?

**Comment by endrift** [comment]
Yeah, but I don't think I distribute it. You'd probably have to build it yourself.

That said, I just committed the long-overdue logging revamp (which I planned to do two+ versions ago) and it will be in the builds on the site soon. The UI needs some improvement (you'll need to go to the settings pane), but it should work now.
