### ISSUE TITLE
Support EWRAM wait state configuration through GBA register 4000800h

### ISSUE THREAD

**Issue by HorstBaerbel** [mgba-emu/mgba#1276]
The GBA (Regular + SP, NOT GBA Micro or DS) support EWRAM wait state control through "undocumented" register 4000800h ([see GBATek](http://problemkaputt.de/gbatek.htm#gbasystemcontrol)). Support would be nice. Atm mGBA reports:

> [GAME ERROR] GBA I/O:	Write to unused I/O register: 800
> [GAME ERROR] GBA I/O:	Write to unused I/O register: 802

Code:
```
#define REG_WAITEWRAM (*(volatile uint32_t *)(REG_BASE + 0x0800))
// set undocumented register for EWRAM waitstates
// sets EWRAM wait states to 2/2/4 vs. 3/3/6 (default 0x0D000020)
REG_WAITEWRAM = 0x0E000020;
```

**Comment by endrift** [comment]
I haven't added support for remapping/disabling EWRAM via the low bits yet, but this takes care of the easier stuff.
