### ISSUE TITLE
graphic glitch on Onimusha Tactics

### ISSUE THREAD

**Issue by codingbum** [mgba-emu/mgba#1278]
mgba version: 0.6.3 (about window says 0.6.1)
display driver: OpenGL
os: archlinux x64

There is a graphic glitch in the post-battle screen of Onimusha Tactics (Game Boy Advance, 2003, 70475d7f). 

Here a video showing the glitch: https://streamable.com/kyll7

savestate: 
(you just have to kill the mob for the fight to finish)
[Onimusha Tactics (U).ss1.zip](https://github.com/mgba-emu/mgba/files/2799091/Onimusha.Tactics.U.ss1.zip)

**Comment by endrift** [comment]
Seems to be fixed in master, but there are other graphical glitches now.
