### ISSUE TITLE
Gunstar Super Heroes / Gunstar Future Heroes - status bar has graphical glitches

### ISSUE THREAD

**Issue by YaketyJoe** [mgba-emu/mgba#1279]
OS and Version: Windows - mGBA version 0.7.0 - released Jan 26, 2019.

In the games "Gunstar Super Heroes / Gunstar Future Heroes", the top energy bar has layering issues, causing graphical glitches. Part of the game goes over the weapon icons, when it does not in real hardware. 

This issue clearly happens on first boss and on the second level. Please see images below:

![gunstar future heroes europe en ja fr de es it -3](https://user-images.githubusercontent.com/47089109/51806291-24ee9900-222d-11e9-90f0-b3019d7fe9a1.png)
![gunstar future heroes europe en ja fr de es it -0](https://user-images.githubusercontent.com/47089109/51806296-33d54b80-222d-11e9-8162-a95b77c0a479.png)
![gunstar future heroes europe en ja fr de es it -1](https://user-images.githubusercontent.com/47089109/51806297-33d54b80-222d-11e9-9d09-8248edf6348b.png)
![gunstar future heroes europe en ja fr de es it -2](https://user-images.githubusercontent.com/47089109/51806298-33d54b80-222d-11e9-87cc-0afc4d040585.png)

**Comment by endrift** [comment]
Please provide a savestate.

**Comment by YaketyJoe** [comment]
Sure, here is a Save State, from a No-Intro rom:
[Gunstar Future Heroes - bug01ss.zip](https://github.com/mgba-emu/mgba/files/2800507/Gunstar.Future.Heroes.-.bug01ss.zip)

**Comment by fleroviux** [comment]
fwiw this game is massively exceeding the scanline cycle limit for OBJs and excepts OBJs beyond that limit to get discarded. implementing this will fix the issue.
there still will be small cut-ins at the bottom of the status bar, but those appear to happen on HW as weel.

**Comment by endrift** [comment]
Strange, I already implement the cycle limit for OBJs.

**Comment by fleroviux** [comment]
![image](https://user-images.githubusercontent.com/13669774/84211651-1b7d6e00-aabc-11ea-9dfc-4fdb7514f3ea.png)
That's strange then. I've only checked the first stage until the first boss so far which has the same problem as NanoboyAdvance had until recently. Implementing the cycle limit fixed it for me.

**Comment by fleroviux** [comment]
Just a wild guess: are you maybe rendering OBJs in reverse order (127 first, 0 last)?
That's something I changed recently and reverting that change Gunstar Super Heroes breaks.

**Comment by endrift** [comment]
Looks like my sprite cycle implementation was buggy! Thanks for the help @fleroviux.
