### ISSUE TITLE
Graphical emulation bug on Mario Party Advance

### ISSUE THREAD

**Issue by FayneAldan** [mgba-emu/mgba#128]
The bug only appears on dialog boxes that suggest a quest for you to do next.

mGBA (3DS):
![mGBA](http://i.imgur.com/6VZI85f.png)

VisualBoyAdvance (PC):
![VisualBoyAdvance](http://i.imgur.com/2GSXdBn.png)

**Comment by endrift** [comment]
Can you please attach a savestate?

**Comment by FayneAldan** [comment]
GitHub doesn't allow attaching non image files.

**Comment by endrift** [comment]
Just rename it to .png, since the savestates are PNGs (with extra data embedded).

**Comment by FayneAldan** [comment]
![Save Data](https://cloud.githubusercontent.com/assets/1149870/10011638/a474db72-60ba-11e5-8fcd-97b325531737.png)
It's interesting you say that, since neither Windows nor GitHub consider it a valid PNG... I was still able to upload it regardless...

**Comment by endrift** [comment]
That's the ROM, not the savestate.

**Comment by FayneAldan** [comment]
That would explain the 8 MBs...
![Save State](https://cloud.githubusercontent.com/assets/1149870/10011761/a415187a-60bc-11e5-907a-0beb6b3b0608.png)

**Comment by endrift** [comment]
I'll try to take a look at this tomorrow.

**Comment by endrift** [comment]
This looks easy to fix. I'll try to get it in by tomorrow's nightly.

**Comment by endrift** [comment]
Fixed in 5ef980116a65c9eb31343859f87d6e3b74ffd52f. Thanks for noticing this, it turned out to be a pretty bad bug!

**Comment by FayneAldan** [comment]
I'm curious now. How was this a bad bug? What else was affected by this bug?

**Comment by endrift** [comment]
This bug would affect a good chunk of times when a sprite is marked as "semitransparent" but also the scene is marked as "darken". In these cases, the semitransparent is supposed to override the darken, but this bug made it so that the darkening would still occur, hence why the sprite was black.

**Comment by FayneAldan** [comment]
Interesting, but was anything else affected by this bug? (And since when does GBA have PNG sprites?! o_O)

**Comment by endrift** [comment]
As far as I know, nothing else, but I'd be surprised if it was actually nothing.

Also, the sprite is just the dark box in the corner. The savestate is a PNG because that's how I wrote mGBA :stuck_out_tongue:

**Comment by FayneAldan** [comment]
I meant because you said "semitransparent."

**Comment by endrift** [comment]
Oh, yeah, it's the effect they use in e.g. FFTA when the judge appears and is the only sprite that has the blend effect.
