### ISSUE TITLE
switch port unable to load roms with foreign character.

### ISSUE THREAD

**Issue by gqbigpaps** [mgba-emu/mgba#1287]
Hi, the switch port seems to be unable to load any archived (.zip) rom files with any non English characters, specifically korean. Unfortunately I have my roms organized in a way so that their naming takes after the language it was published in. Is there a way to work around this without having to rename all my roms?

**Comment by endrift** [comment]
Are the foreign characters in the .zip name or the names of the contents of the .zip? Also, does it work with unarchived ROMs?

**Comment by gqbigpaps** [comment]
The foreign characters are in in .zip name and names of the content of the said zip.
(ie pokemon korean version is named 포켓몬(k).zip and the inside the zip the rom is named 포켓몬(k).gba
The menu renders all korean characters to "_" when listing the files. Unzipped roms also fails.
I am on 6.2 reinx.

**Comment by gqbigpaps** [comment]
> Are the foreign characters in the .zip name or the names of the contents of the .zip? Also, does it work with unarchived ROMs?

I've just realized perhaps its not an issue with mgba but switch as a whole since it just got official korean support in 7.0.
Other homebrews seems to have the same problem with displaying korean characters.

**Comment by endrift** [comment]
The display issue is because the font mGBA uses doesn't have hangul. I'm not sure how I'm gonna handle that yet, though.

**Comment by gqbigpaps** [comment]
Does the app rely on system font or does it have its own font embedded?
If its the former I reckon once 7.0 is cracked it should be able to display fine and load.
If not perhaps try including a font that has hangul? I would like to help translate the homebrew in to Korean as well if you guys are interested.

**Comment by endrift** [comment]
It looks like there's a bug in the Switch OS regarding filenames that aren't ASCII: https://github.com/switchbrew/libnx/issues/90#issuecomment-390697783

It looks like this isn't fixable on my end, unfortunately.
