### ISSUE TITLE
Quick save states sometimes get corrupted

### ISSUE THREAD

**Issue by themalu866** [mgba-emu/mgba#1293]
Okay, so I noticed that sometimes when I quick save (with shift+F1 or F2 or F3...) GB or GBC games and then try to load them, the save file doesn't work.
Sometimes even with a early save that works, I save over it and doesn't load anymore, not even by pressing F10 and choosing the save file.
This doesn't seems to happen when I play GBA games but I'm not sure about that, probably have to check more.
Maybe this has been overlooked because it doesn't always happens and other people don't save as much but I pretty sure it's a glitch, I've never seen any other emulator where this happens.
I use on Windows 7 and no, I didn't mess with the roms names or saves and neither with the kind of archives they are, it's just something that happens randomly.

[Super Mario Land.zip](https://github.com/mgba-emu/mgba/files/2823666/Super.Mario.Land.zip)

[Goemon.zip](https://github.com/mgba-emu/mgba/files/2823677/Goemon.zip)

**Comment by endrift** [comment]
Please attach a corrupted save state.

**Comment by endrift** [comment]
Good news: the states aren't corrupted, there was a bug in loading them. That's fixed now so the dev builds will be able to load them again.
