### ISSUE TITLE
mGBA RTC is offset from system time

### ISSUE THREAD

**Issue by Zeturic** [mgba-emu/mgba#1295]
I added a RTC to a Pokemon Fire Red ROM using the DNS tool, with [your](https://www.pokecommunity.com/showpost.php?p=9837239&postcount=250) fix applied.

The way it's supposed to work is that it places the following at `0x0300553C`:

```
u16 year
u8 unknown
u8 month
u8 day
u8 unknown
u8 hour
u8 minute
u8 second
```

However, when I open it in mGBA, this is what I get:

![screenshot 292](https://user-images.githubusercontent.com/6500490/52160144-69d75d00-267d-11e9-9f0f-e00b5bfd3da8.png)

If you parse that by hand, you'll see that it says February 2nd 2019, 4:56:31, exactly five hours ahead of my system time (which you can see in the bottom right).

I did notice that if I switch from `System time` to `Fixed time`, the time is correct (well, until a second passes, I suppose).

I'm on 64-bit Windows 10 and mGBA 0.7.0, though I remember first noticing this behavior a few months back.

**Comment by endrift** [comment]
Does this happen with other RTC games? I wonder if this is Windows only.

**Comment by Zeturic** [comment]
I just retested this in 0.8.0 and it doesn't happen any more. I re-downloaded 0.7.0 and retested it there, and it doesn't happen there any more, either.

I'm still on the same Windows 10 PC as when I originally posted this, though obviously there have been Windows Updates since then. So I guess it was something in Windows itself?

**Comment by Testsr** [comment]
Weird. Anyway, should we close this?

**Comment by endrift** [comment]
Yeah, I guess so. I don't think anyone else reported it.
