### ISSUE TITLE
Mario Golf: Advance Tour Linking Barely works

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#13]
There's really no issue template, so I'll explain it as best as I can.

The game has specific instructions when linking.  Start up game one, go to link menu.  Then it tells you to start up game 2 and go to the linking menu.  99% of the time, absolutely nothing happens.  It just keeps telling you to do the same damn instructions over and over again.

But let's say the blue moon happens and the game actually connects!  It drops to a mere 5 FPS and crashes when you try to switch from one emulator to the other in order to select the second character.

I'd see if that crash is consistent, but I never have gotten it to detect the link cable a second time.  I don't know how I got it to connect the first time.

**Comment by endrift** [comment]
Seems to work for me. I have to do the same trick as with Four Swords where you have to back player 1 out of the Vs menu and then go back in while player 2 is in the menu. But I don't have any speed issues beyond the normal ~2% slowdown (that still needs to be fixed). I should investigate a bit more closely to see how well it works on Windows, though.

**Comment by JMC47** [comment]
It seems that the slowdown to 5 fps followed by crash is a global problem that just happens on all games.

**Comment by endrift** [comment]
I'll see what I can do about this, but I really cannot reproduce the slowdown in my configuration.

**Comment by endrift** [comment]
Reported as being fixed, at least in master.
