### ISSUE TITLE
Zatch Bell! - Electric Arena crashes during gameplay

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#130]
Enter a match using Zatch specifically, one of his fighting moves is done with B+A+Up, when triggered that's when the game crashes with a popping sound and some buzzing/bleeps ensue.

**Comment by endrift** [comment]
I don't seem to be able to reproduce this. Which build and platform are you on?

**Comment by SuperrSonic** [comment]
Wii and tested on the latest(oct 5) nightly, also tried libretro Wii port.

I tried the android libretro port now and it works fine, sorry, it seems Wii only, I didn't think to test that, thought testing one libretro port was enough.

**Comment by endrift** [comment]
Fixed in 4db61f400be9e49fb754c0473768143010cd2c20.

**Comment by SuperrSonic** [comment]
Thank you, by the way the NiGHTS mini game now works as well.
