### ISSUE TITLE
Gyrometer axis inverted on Switch

### ISSUE THREAD

**Issue by RSDuck** [mgba-emu/mgba#1300]
It took a short while for me to notice that I wasn't completely bad at playing Wario Ware Twisted, but that the Z-axis is inverted on Nintendo Switch 😄 

Probably the same issue as https://github.com/mgba-emu/mgba/issues/324

I only tested it on the Retroarch build, but it likely affects the standalone build too, since they use the same code for gyrometer input.

**Comment by endrift** [comment]
I swear I tested this...will try again soon. I always get this wrong.
