### ISSUE TITLE
Memory Test Regression in mGBA 0.7.0

### ISSUE THREAD

**Issue by Zenjir0** [mgba-emu/mgba#1301]
I'm sure this might already be known, but when I ran the gba-suite v0-r51 on mGBA 0.7.0 it only passes 1455 out of the 1552 tests.

mGBA 0.6.3 still gets a solid 1552/1552 when tested. 

gba-suite rom can be acquired here for those that are wondering what the test suite is: https://forums.mgba.io/showthread.php?tid=18

**Comment by endrift** [comment]
I fixed a handful, the rest seem to be DMA related.
