### ISSUE TITLE
GB and GBC games with GBA frame sizes

### ISSUE THREAD

**Issue by themalu866** [mgba-emu/mgba#1302]
Playing on Windows I noticed that when loading GB and GBC games the frame size keeps on GBA but with black bars on the sides (the aspect ratio is right)
I have to manually choose the same Frame size in order to get it right (in this case is x3) but I notice that the size is smaller

 The bigger ones are when I load the game (3x) and the smaller ones when I choose 3x manually
![tytyt](https://user-images.githubusercontent.com/42208976/52669581-8b4a0b80-2efd-11e9-8736-c7e7e86e7467.png)

![oo9it](https://user-images.githubusercontent.com/42208976/52669586-900ebf80-2efd-11e9-8a66-8c5bd73e04e0.png)

![ikli](https://user-images.githubusercontent.com/42208976/52669590-956c0a00-2efd-11e9-8ab0-48538f576bb2.png)

This is way more noticeable with the Super Gameboy borders
In this case still is 3x but the smaller ones are when I load the game and the bigger ones after I choose 3x manually.
![kluy](https://user-images.githubusercontent.com/42208976/52669964-98b3c580-2efe-11e9-8aed-4bc3512f8efb.png)

![yuttuy](https://user-images.githubusercontent.com/42208976/52669975-a1a49700-2efe-11e9-8a5e-a6199c229b37.png)

![rtr45](https://user-images.githubusercontent.com/42208976/52670570-090f1680-2f00-11e9-9aa8-47bf47f36b45.png)

I don't know which is right, but I think it's the one without the black bars.

**Comment by endrift** [comment]
Can you see if the screen size you wanted is checked in the menu before or after loading the game? There should be code in there right now to fix this.

**Comment by themalu866** [comment]
LIke I said, it doesn't matter if is checked before or after load a game, YOU have to to check MANUALLY before or after loading to work.
![1](https://user-images.githubusercontent.com/42208976/53923589-9ce38680-4057-11e9-92f8-05cc2a5a2665.png)
![2](https://user-images.githubusercontent.com/42208976/53923595-a10fa400-4057-11e9-848f-c341e1410fb9.png)
![3](https://user-images.githubusercontent.com/42208976/53923603-a8cf4880-4057-11e9-8dd4-fc8fb8a1cd98.png)

**Comment by endrift** [comment]
Closing as dupe.
