### ISSUE TITLE
Can the Debug console default to having all message levels on?

### ISSUE THREAD

**Issue by Lokathor** [mgba-emu/mgba#1303]
Right now when you activate the emulator three of the debug message levels aren't on by default, so messages at those levels during a game's startup don't get logged.

**Comment by endrift** [comment]
That would almost certainly be too slow, and hang users' consoles when even trying to look at it.

**Comment by Lokathor** [comment]
Can there be a command line option or config file setting to boot with all levels on perhaps?

**Comment by endrift** [comment]
Already have both: `-l -1` and `logLevel=-1`.

**Comment by Lokathor** [comment]
Ah ha! My mistake then. Consider it resolved.
