### ISSUE TITLE
FPS keep dropping over time

### ISSUE THREAD

**Issue by branchus** [mgba-emu/mgba#1308]
Hi I set the target FPS at 60, when it starts, the FPS is at 60, but over time, it keeps drop to 55...50...45...40. generally within two hours game play.

I'm on windows 10 64bit and tried mGBA both 64bit and 32bit. and playing Final Fantasy VI advance. I have nVidia Quadro P2000 graphic card, Xeon CPU and 32GB RAM. I have used the 0.63, 0.70 and latest daily build, but all have the same issue.

Thanks

**Comment by kurayami6** [comment]
The exact same thing happened to me when I played Spyro 2: Season of Flame.

Very latest version of mGBA, Windows 7, GTX 970, i5.

**Comment by endrift** [comment]
Have you confirmed it's not just the FPS counter, but that the FPS itself is actually dropping?

**Comment by branchus** [comment]
> Have you confirmed it's not just the FPS counter, but that the FPS itself is actually dropping?

Hi endrift

Yes, I confirm the FPS is actually drop together with the sound

**Comment by endrift** [comment]
I haven't been able to reproduce this yet; I've left Mother 3 on audio test for about 5 hours to no framerate reduction.

**Comment by branchus** [comment]
Hi Endrift

the issue persisting, anyway, I can always close and reopen. it may be the compatibility issue with graphic driver or audio driver.

I tried to switch the display driver to the software(Qt) driver, the FPS drop to 0.5FPS (unplayable). but the CPU usage is only 3%

**Comment by endrift** [comment]
The software driver slows down if the window is larger. Are you in full screen?

**Comment by branchus** [comment]
Yes, I'm using full screen and the screen resolution is 4k

Do you think the issue related to this full screen 4k resolution? I will try the smaller window and report it back
Thanks

**Comment by endrift** [comment]
That explains why the software driver is so slow. See if a smaller window (1x preferable) makes software work at a reasonable rate and still slow down over time.

If it does still slow down over time try fiddling with the audio driver settings.

**Comment by branchus** [comment]
> That explains why the software driver is so slow. See if a smaller window (1x preferable) makes software work at a reasonable rate and still slow down over time.
> If it does still slow down over time try fiddling with the audio driver settings.

Hi endrift

I tried to use x1 with software driver, the FPS locked at 0.5FPS with CPU load at 2% (unplayable)
I tried the x1 mode with OpenGL driver, it still slows down after a while.

the game I tested is final fantasy VI advance.

Thanks

**Comment by endrift** [comment]
What are your sync settings, i.e. Sync to audio (recommended), sync to video, or both (not recommended)?

**Comment by branchus** [comment]
I used to set sync to both
after I read your comment, I did below test
first, only turn off sync to video, game still slows down
then, turn off both sync, FPS goes to 600
finally, only turn off sync to audio, game no longer slows down

seems the issue is related to the audio driver

I'm using a usb audio interface (Focusrite Scarlett 2i4) ASIO audio driver with sample rate 48khz, buffer 256

**Comment by branchus** [comment]
I think I solved the issue

if I choose buffer size 512 in my audio interface control panel, then the game no longer slows down

Thanks

**Comment by endrift** [comment]
@kurayami6 can you confirm if this also fixes it for you?

**Comment by kurayami6** [comment]
Yeah it's fixed.
