### ISSUE TITLE
[Wii] Mario & Luigi - Super Star Saga

### ISSUE THREAD

**Issue by askotx** [mgba-emu/mgba#131]
This rom has some issues on wii version, when you return to save Queen and giver her a beverage, game freezes, tested on lastest nighlty version, I've attached a png file when game gets locked and a battery file to test, 

This issue doesn't happen on win32 version, it keeps going on: Queen gets back to herself, it's a transformation or something like that.
![mario luigi - superstar saga europe en fr de es it -0](https://cloud.githubusercontent.com/assets/2125887/10266047/be3e752a-69fe-11e5-98d2-d748da456482.png)

https://mega.nz/#!TA4lwAxB!7csJC8Bb_4SlmpFb_6PqKyRB3Z1j5y2OrQnPPJm4AAU

**Comment by endrift** [comment]
Fixed in 2ea44603a810320af7a90d0dd4bb96116aca239d. Thanks for finding this.
