### ISSUE TITLE
X / 0 = 0? Possible bug.

### ISSUE THREAD

**Issue by jmwielandt** [mgba-emu/mgba#1315]
Hi, editing some code of pokeemerald and testing it on mGBA 0.7 (0ddade326c241eeff0f2c5fcec49e0ea7219ce83), i've found that if i do:
```C
u32 a = /*whatever != 0*/;
u32 b = 0;
u32 c = a / b;
```
The final value of var `c` is `0` (zero).
Is how the real GBA processor works or is a bug?

Thx

**Comment by endrift** [comment]
The actual BIOS routine freezes if you try to divide by zero, IIRC. That's kind of hard to emulate though.

**Comment by endrift** [comment]
The associated code is here: https://github.com/mgba-emu/mgba/blob/master/src/gba/bios.c#L264-L269

It shouldn't be 0 though, you might have constant folding being done by the compiler.

**Comment by Berbe** [comment]
What would be the value of emulatin a state which leads nowhere?

If such a buggy and useless situation can be detected, logged (extremely important, and it is being done already) and avoided, that can only be a benefit.

You could consider the resulting state is not realistic and unpredictible, true, but that means the original game on the original hardware was not playable past this point anyway.
I do not see a realistic emulation which would be satisfying: making the emulator's host hang? The program unresposive? Making it crash or reset? Hell, hell & hell, isn't it? What would be the value in those?
