### ISSUE TITLE
Earthworm Jim 2 (USA) nothing but a white screen

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#1318]
using 0.7.0

**Comment by endrift** [comment]
Works for me. Do you have a bad dump?

**Comment by benderscruffy** [comment]
use GBA bios

**Comment by endrift** [comment]
Still works when I do that.

**Comment by benderscruffy** [comment]
it  works when i untick use gba bios 
weird

**Comment by benderscruffy** [comment]
last thing i can think off
untick skip bios intro

**Comment by endrift** [comment]
Yup I can reproduce now
