### ISSUE TITLE
Metal Max 2 Kai (Japan) flashing text

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#1319]
using 0.7.0
the text keeps flashing then disappears during the game

**Comment by endrift** [comment]
This is caused by IRQ timing on their hblank routine being extremely tight. Going to be very difficult to track down and fix.

**Comment by endrift** [comment]
Partially fixed in f9f105a8520813a5d6300bc082e5bf98d6c01d95, but the flashing is still horrible.
