### ISSUE TITLE
black screen with SDL

### ISSUE THREAD

**Issue by jbo-85** [mgba-emu/mgba#132]
SDL only shows a black screen after this commit, sound seems to work:
https://github.com/mgba-emu/mgba/commit/f128f844a67e4cf6ddbe5b90171a4f983c1b5459

This is on Fedora Linux.

**Comment by endrift** [comment]
Thanks for tracking this down. I've been aware of it for a while but hadn't gotten around to tracking down the commit yet.

**Comment by endrift** [comment]
Fixed in 9f5bfeeebb70f0ad05157df55009273726e39109.
