### ISSUE TITLE
Port to WASM platform?

### ISSUE THREAD

**Issue by HadesD** [mgba-emu/mgba#1322]
I 've compaire mGBA with some another emulator on windows, and mGBA is the best performance emulator.
I think if port to WASM then i can use this API to write my own emu site to playoffline on my phone :)

I'm making mGBA-wasm repo to contrib but do not know so much about mgba code. And if you all will be release a wasm build, then let me know.

Thanks you all.

**Comment by endrift** [comment]
Dupe of #1296.

**Comment by patrickcorrigan** [comment]
Any update on this? I'm up for trying to port it too.
