### ISSUE TITLE
Library displays in tree view instead of list view

### ISSUE THREAD

**Issue by flingrocks** [mgba-emu/mgba#1324]
Despite having the Library set to List view (libraryStyle=0 in config.ini), sometimes when the program opens, the Library displays in Tree view. In addition, unlike when you actually have Tree view set, the game items in this tree do not run when double-clicked. 
Settings in UI for library still says "List view" and the ini key remains unchanged.
Issue seems to occur more times in the 64-bit version but does happen in both. I experienced this behavior on version 0.7.1 under Windows 10.

**Comment by endrift** [comment]
@waddlesplash Would you have time to look into this? If not I can at some point.

**Comment by flingrocks** [comment]
Similar to this, oddly enough the "Open in archive..." dialog will also sometimes display in Tree view. Using Open button or double-clicking game title closes the dialog but does not load the game. This happened less frequently than that with the Library.

**Comment by endrift** [comment]
They both use the same backend for listing games, so that's not surprising.

**Comment by waddlesplash** [comment]
I may have some time in the next week.

**Comment by endrift** [comment]
I'm pretty sure this is fixed now; let me know if it's not and I'll reopen.
