### ISSUE TITLE
Recent files list will not start games within archives

### ISSUE THREAD

**Issue by flingrocks** [mgba-emu/mgba#1325]
Entries on Recent files list to games inside archives fail to work.
Entries to just the archive (like "E:\Games\Asteroids.7z") do work, but entries to specific games within an archive (such as "E:\Games\Strategy.7z\Shogi.gba") do not load anything. Found broken in 0.7.1 and 0.7.0, but it was working fine in 0.6.3.

**Comment by endrift** [comment]
Wait when did I fix this? I wasn't aware it ever worked. I'll try to take a look tonight or tomorrow.
