### ISSUE TITLE
Versatility by The New Image demo graphic glitches

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#1327]
all the graphics are messed up
http://www.pouet.net/prod.php?which=1795
![versatility](https://user-images.githubusercontent.com/2696404/53675604-264f2d80-3cd3-11e9-83fc-e8dfdcf41bfa.PNG)

**Comment by endrift** [comment]
Seems to be broken in SameBoy and BGB in exactly the same way--it might just not work on hardware.

**Comment by benderscruffy** [comment]
not a bug
