### ISSUE TITLE
Ken Griffey Jr.'s Slugfest (USA) glitchy background

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#1331]
just choose homerun derby and the background keeps on flashing
![ken](https://user-images.githubusercontent.com/2696404/53679852-734ff580-3d0d-11e9-8ef9-0067a85e8ba0.PNG)

**Comment by endrift** [comment]
Looks like it's doing tricks to have more colors in the background by swapping out the palettes, but it misses intervals.

**Comment by endrift** [comment]
STAT IRQ blocking is to blame.
