### ISSUE TITLE
Glitch on Boktai: lines keep appearing

### ISSUE THREAD

**Issue by themalu866** [mgba-emu/mgba#1335]
Playing on Windows, it doesn't matter what region (USA, Europe), there's a flickering line that keeps appearing all the time in the whole game.
![bok](https://user-images.githubusercontent.com/42208976/53694758-18141680-3d92-11e9-8f42-7d3381b96ac8.gif)
![tyf](https://user-images.githubusercontent.com/42208976/53694797-6d502800-3d92-11e9-830b-596253ec74ff.gif)
And I also noticed that the shadows don't seem to be working properly, it doesn't matter if Sync Video is on or off, and I know the game uses a blinking effect but they seem to be pretty erratic and irregular now, but you can't see on gifs.

**Comment by endrift** [comment]
This regressed fairly recently.

**Comment by endrift** [comment]
Note to self: pay better attention to the warnings the compiler emits.
