### ISSUE TITLE
Cross Country Racing (Europe) (En,Fr,De) (SGB Enhanced) (GB Compatible) road is glitchy

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#1338]
when you choose your stage choose tarmac and the road is glitchy
![cross](https://user-images.githubusercontent.com/2696404/53703895-c9c64c80-3e51-11e9-818d-e79cee500b1a.PNG)

**Comment by endrift** [comment]
Which level is this? I'm having trouble reproducing.

**Comment by benderscruffy** [comment]
just choose championship - clover - rally event then you can choose beginner,tarmac and gravel choose tarmac
just wondering if the fix for ken griffey baseball fixed it as i havent updated to the latest MGBA yet

**Comment by endrift** [comment]
It looks the same in SameBoy so I'm not sure what the bug is.

**Comment by benderscruffy** [comment]
think this will need HW testing

**Comment by benderscruffy** [comment]
not a bug
