### ISSUE TITLE
Super Snakey (Japan) (SGB Enhanced) missing  graphics

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#1339]
when run in SGB mode the part of the fence is missing which covers the playing area
![snakey](https://user-images.githubusercontent.com/2696404/53704049-69380f00-3e53-11e9-8a64-3f9d9d57c5f6.PNG)

here is what it is supposed to look like
![super-snaky](https://user-images.githubusercontent.com/2696404/53704052-76ed9480-3e53-11e9-95b6-0eaa97c1c2aa.gif)

**Comment by endrift** [comment]
This is an implementation limitation in the current SGB implementation.
