### ISSUE TITLE
Chiki Chiki Machine Mou Race (Japan) missing hud

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#1345]
in the bottom right hand corner is supposed to be the HUD map but it is only a thin black line
![chiki](https://user-images.githubusercontent.com/2696404/54064568-64f36380-4250-11e9-8ec5-54ac76fd57c3.PNG)

**Comment by endrift** [comment]
Issue also occurs in SameBoy (@liji32). Seems to have to do with decreasing the value of WY.
