### ISSUE TITLE
[Feature] Custom save type overrides

### ISSUE THREAD

**Issue by PikalaxALT** [mgba-emu/mgba#1353]
**Situation**: We want to modify the game code of a ROM compiled from the Pokémon Sapphire source (original: AXPE) to a custom code.  However, doing so causes the software to fail to run.  The BIOS loads correctly and all the header and logo checks succeed, but Sapphire's flash check fails because mGBA's autodetection misclassifies the save type as FLASH 512K rather than FLASH 1M.  Vanilla Pokémon titles do not suffer this problem because the FLASH 1M and RTC are hardcoded in mGBA source.

**Proposal**: Allow the user to supplement the `_overrides` table in [src/gba/overrides.c](src/gba/overrides.c#L13) with their own INI file.  Suggest the following structure:

    [GAME_CODE]
    savetype = SAVE_TYPE_ENUM
    hardware = HW_ENUM
    idleLoop = IDLE_LOOP
    mirroring = BOOLEAN

Example:

    [TPPS]
    savetype = SAVEDATA_FLASH1M
    hardware = HW_RTC
    idleLoop = IDLE_LOOP_NONE
    mirroring = false

Allow the user to omit one or more fields in these overrides, in which case the default values are used.  For INI sections with codes matching those already present in source, have the user settings take precedence, in which case missing fields in the INI will cause mGBA to use the hardcoded values.

**Comment by endrift** [comment]
This is already implemented.

**Comment by PikalaxALT** [comment]
Thank you for your ever-so-helpful comment.  While I now see where this functionality is implemented, I am concerned that the implementation does not work as desired.  Indeed, when launching the emulator with a modified config file, the original symptoms persist.  To run the ROM, I need to open the "Game Overrides" tool on emulator launch, select the Save type as "Flash 1Mb" and the hardware as "Realtime clock", and then load the ROM.  If the emulator is closed and reopened, the same procedure must be repeated, even if I hit "Save" in the "Game Overrides" tool window.  In order to clear overrides (i.e. to load a ROM that does not support Flash 1M or has Gyroscope), the emulator must be closed entirely.

These observations are based on version 0.7.1 from Mac OSX Homebrew.  If there is a more current build that resolves this issue, please point me to it; otherwise, I implore you to reopen this issue.
