### ISSUE TITLE
[BUG]: Save type overrides in config.ini are ignored (Mac OS Mojave, mGBA v0.7.1)

### ISSUE THREAD

**Issue by PikalaxALT** [mgba-emu/mgba#1354]
Steps taken:

- Launch mGBA
- Tools > Game Overrides...
- Set save type to "Flash 1Mb" and hardware to "RTC", deselecting "Autodetect"
- Load a modified copy of Pokemon Sapphire with a custom game code (PMSE)
- Once the game starts to run, click "Save" in the Game Overrides window
- Close mGBA
- Launch mGBA anew
- Load the same ROM without setting up the overrides (using cmd+0)

Expected outcome: Modified Sapphire runs normally, with no in-game error messages regarding the 1M subcircuit board or the internal battery.

Observed:

- Game fails to load.  Log indicates that it autodetected the save type as Flash 512kb, which is incorrect.
- If I recompile the ROM with the boot-time flash check commented out, it will run but present the "1M subcircuit board is not installed" and "Internal battery has run dry" errors when progressing beyond the title screen.
- The override.PMSE entry does exist in the file ~/.config/mgba/config.ini as expected, however it seems to be entirely unused by the emulator.

A similar issue was incorrectly filed as #1353.

**Comment by endrift** [comment]
Can you upload the patch? I can't seem to reproduce. Also, make sure the override says `savetype=FLASH1M` and `hardware=1`. I know the override dialog can be a bit finicky and I'd like to fix that in 0.8.

**Comment by PikalaxALT** [comment]
While I cannot give you a patch with all the changes I made, I can supply an xDelta patch on Pokemon Sapphire US-EN v1.0 (SHA1: 3ccbbd45f8553c36463f13b938e833f652b793e4) that makes a minimal set of changes to reproduce the issue in mGBA:
[romcode.xdelta.gz](https://github.com/mgba-emu/mgba/files/2968499/romcode.xdelta.gz)

**Comment by endrift** [comment]
Confirmed. I'll have a fix out tonight.
