### ISSUE TITLE
Pagemaster (SGB)

### ISSUE THREAD

**Issue by Sun-in-jang** [mgba-emu/mgba#1357]
Hello, there is issue with game "Pagemaster" for super game boy. There
no sound at all, only music (in options through music/sound test) . Also i checked with that video
https://www.youtube.com/watch?v=nFRpcINVFEE (guy is there have both
sound & music). I don't know guys is that normal thing or emulation feature, that is SGB sounds is problematic.

**Comment by themalu866** [comment]
SGB on mgba always sounded weird to like.
Like in Donkey Kong, Pauline scream "HELP! HELP!" is missing on SGB mode.

**Comment by endrift** [comment]
Forward duping to #1366.
