### ISSUE TITLE
Mac OS Mojave: cmake tries to incorrectly link libelf

### ISSUE THREAD

**Issue by PikalaxALT** [mgba-emu/mgba#1358]
Setup: cmake, qt5, gmake, and libelf are all installed via homebrew.  libedit is not found and its associated feature is disabled by cmake.  Environment includes all the Qt5 DIR variables.

To reproduce:

    mkdir -p build
    cd build
    cmake ..
    gmake

Error:

    [ 56%] Linking C shared library libmgba.dylib
    ld: library not found for -lelf
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Possible cause: Generated file CMakeFiles/mgba.dir/link.txt does not include the flag `-L/usr/local/Cellar/libelf/0.8.13_1/lib`.  It does, however, include the flag `-lelf`.  This could be a problem with cmake making bad assumptions about where libraries can be found, or an issue in homebrew with linking libelf to /usr/local.  Regardless, the fact that libelf was found in a directory other than /usr/local/lib/ yet that information is never passed to ld, indicates a problem with cmake configuration.

**Comment by endrift** [comment]
Can you paste the output of `grep libelf_ CMakeCache.txt` for me? This is an easy fix but I don't have a Mac with Homebrew handy at the moment. I can check tomorrow otherwise.
