### ISSUE TITLE
Games with accents don't start when clicking the rom files

### ISSUE THREAD

**Issue by themalu866** [mgba-emu/mgba#1359]
Playing on Windows 7, I always change the property of roms for their respective emulators and they load just fine.
Mgba also works with the exception of Pokemon games, I tested Yellow, Crystal, Ruby and Emerald and none of them loaded, it's like I clicked on the mgba itself and not the game file.
But the games still work if you go to "File", "Load ROM" and them choose it.
And this it's not a problem of just changing properties because other GBA and GBC games load normally.
I think this is a very recent change because they loaded before not long ago.

**Comment by endrift** [comment]
What are the filenames? Do they have accent marks in them?

**Comment by themalu866** [comment]
Yes, I downloaded them and they have accent marks.
I tried taking the accents and now they work.
That's weird.

**Comment by themalu866** [comment]
Yes, from where I downloaded them they have accent marks.
I tried taking the accents and now they work.
That's weird, but why this happens with accents?
I tried ½ and doesn't work either.

**Comment by endrift** [comment]
I'll see if I can reproduce on Windows 10. I don't have Win7 anymore.
