### ISSUE TITLE
[Wii] Video Filter: Unfiltered option.

### ISSUE THREAD

**Issue by ShadowOne333** [mgba-emu/mgba#136]
The default filter option used for mGBA is pretty harsh on people with sight problems like myopia or astigmatism.
I would like to ask (if possible) for the implementation of an unfiltered option for the emulator (no blur effect).
Either toggle Filter On/Off could do it from the Settings menu.

Thanks in advance!

**Comment by endrift** [comment]
Which port are you using? The default option on PC *is* unfiltered.

**Comment by ShadowOne333** [comment]
I'm using the Wii port of mGBA. 
I haven't tried the 3DS one yet so I'm unaware if that one has the default filter too.

**Comment by endrift** [comment]
The reason filtering isn't optional on the Wii port is due to not knowing exact pixel sizing of the screen, but I haven't actually tried to fix that yet. I'll look into that soon.

**Comment by ShadowOne333** [comment]
Thank you SO much for taking my request into consideration. :)

**Comment by ShadowOne333** [comment]
Thank you SO much for taking my request into consideration. :)

**Comment by GB-CG** [comment]
240p mode would be a cool feature too. 240p looks so much better then playing GBA games in 480p.

**Comment by endrift** [comment]
Added in 6a4af381511e20c6cd8a462f1070c3292689c238.

**Comment by nateify** [comment]
I would also appreciate a true 240p mode for mGBA Wii. Setting it to unfiltered and pixel-accurate is still 480i.

**Comment by endrift** [comment]
I would love to do this if I have a TV or capture card that supports 240p. I'm not sure if I do, though. My old TV and my Blackmagic do not, but I haven't tested my new TV, or my Empia or Hauppauge capture devices yet.

**Comment by GB-CG** [comment]
@nateify You sure it's not in 480i? I also use unfiltered and pixel-accurate, but in 480p, and it actually looks super nice.

**Comment by nateify** [comment]
I can't view 480p on my CRT. However, Extrems fork emGBA supports 240p when the meta.xml is passed the argument "--scan-mode=non-interlaced".

VBA GX fork also supports 240p for GB/GBA: https://github.com/libertyernie/vba-wii
