### ISSUE TITLE
Save states not working

### ISSUE THREAD

**Issue by themalu866** [mgba-emu/mgba#1360]
On windows 7, paths are all right but loading by pressing F1 don't load, Shift+F1 don't save and F10 doesn't show anything.
But Load alternate save, Load temporary save and Load state file are still working.

**Comment by Nairod001** [comment]
Occurring on Windows 10 as well, double checked previous builds and it appears to have been introduced in [build 5548](https://github.com/mgba-emu/mgba/commit/c364a6527a83d22bdd79e77286d0b53b0b624746), also stops in-game save states from being read/written.
