### ISSUE TITLE
Bomberman GB (2) missing super game boy sound effect

### ISSUE THREAD

**Issue by JimsAlliance** [mgba-emu/mgba#1363]
OS: Win7x64
mGBA: 0.7.1

The (enhanced) Super Game Boy bomb sound effect is missing in Bomberman GB (specifically the western version, as this is actually Bomberman GB 2. The Japanese Bomberman GB (1) was released in the West as Wario Blast).

When emulating the original game boy the (regular) bomb sound effect does work.

**Comment by themalu866** [comment]
This seems to happen with a lot of GBC games on Super Gameboy mode.
Like in Donkey Kong, Pauline's scream "help" is missing.

**Comment by JimsAlliance** [comment]
> 
> 
> This seems to happen with a lot of GBC games on Super Gameboy mode.
> Like in Donkey Kong, Pauline's scream "help" is missing.

That's good. The more games it affects, the larger the chance that it will get fixed. Both are regular GB games and not GBC games though. ;)

I tried multiple GB emulators and none of them played this sound. Only SNES emulators did. My guess is that none of the GB emulators play it because they simply lack the SNES audio support.

**Comment by endrift** [comment]
Forward duping to #1366.
