### ISSUE TITLE
Please make mGBA load cheat files with extensions (.cht) or (.clt)

### ISSUE THREAD

**Issue by vannessqn** [mgba-emu/mgba#1365]
Or anyone can show me how to convert their cheats to (.cheats)? Because I can't find a cheats collection with (.cheats) extension, it's frustating...

**Comment by endrift** [comment]
.cht appears to have several different formats. Can you be more specific (uploading a file in the format you mean should be enough)? .clt appears to be a binary format so I might not want to do that one yet.

**Comment by vannessqn** [comment]
Oh ty for the reply, I love mGBA but I just want to download a cheats collection, add in the program then done, using one by one code on the internet is frustating and I prefer standalone emulators than retroArch.
Hope you can improve the emulator more.
[0095 - Advance Wars (US).zip](https://github.com/mgba-emu/mgba/files/3317975/0095.-.Advance.Wars.US.zip)

**Comment by endrift** [comment]
This was implemented in 3f044a5791166da2f05f1e72c8d6d06b6cd2d846 and 6bd38d1565a4e19d86c840240e2f97dc2fdc4d58. CLT is still unsupported and will probably remain that way.

**Comment by vannessqn** [comment]
Ty very much
