### ISSUE TITLE
[ENHANCEMENT] [SGB] Emulate SNES sound in SGB mode.

### ISSUE THREAD

**Issue by billy-acuna** [mgba-emu/mgba#1366]
Some (most) of the SGB enhanced games uses SNES sound for some samples (i e. KoF95, Donkey Kong...). Even Animaniacs uses SNES sound for the music in SGB mode.
I know @endrift does not want to fully emulate the whole SNES, but I emulating only the sound side for those games would be cool.

This is just a useless gimmik but can be also the SGB startup snes rom be emulated too (assuming it is not a hard task)?

**Comment by endrift** [comment]
Unfortunately this would require writing an SPC emulator, which is out of scope for a single feature used by sparingly few games.

**Comment by RafaelOliveira71594** [comment]
Soo You Blocked Conversion l Will Switch To Same Boy Bye
