### ISSUE TITLE
[Request] Allow using ROM filename with Discord integration

### ISSUE THREAD

**Issue by Zowayix** [mgba-emu/mgba#1368]
So this is a very cool feature, although it seems what it shows as the currently playing game in Discord is taken from the inbuilt database (which seems to be an old version of No-Intro's GBA dat) or the ROM header, if that's not found; which the title bar does as well I guess. So you get things like this:
![image](https://user-images.githubusercontent.com/31366697/54936603-e4827180-4f76-11e9-9037-5d4eb8d5b419.png)

This doesn't really mean anything to the casual observer who might click on someone's name to see what they're playing.

Would it be possible to have an option to show instead the filename as the game's title (perhaps with the .gba extension chopped off)? This would allow for more accurate display of the game's name with things like homebrew and hacks which would probably never be in the database, or bad dumps that don't match, or good dumps that have a bad dump in the database, or other cases like that; and hence allow me to flex on people more effectively by showing off that I play better games than them.

**Comment by endrift** [comment]
Honestly this should probably be the default, if not the only option. I was pondering it when I added the feature and kinda waited to see if anyone requested it.
