### ISSUE TITLE
No Audio on n3DS

### ISSUE THREAD

**Issue by stoponerr** [mgba-emu/mgba#1370]
Latest firmware, Luma 9.1, I have tried a handful of games (fusion, crystal, crystal clear, zero mission & fire emblem) and none of them have any audio whatsoever. I have tried suggestions from around the internet for older versions without any change.

**Comment by endrift** [comment]
Did any of those suggestions include dumping the DSP blob?

**Comment by stoponerr** [comment]
@endrift I was pretty sure I did this when the guide told me to but I've done it so many times it's possible I just skipped it. Fixed now, thank you very much.
