### ISSUE TITLE
stuck at loading game MGBA

### ISSUE THREAD

**Issue by bfleck123** [mgba-emu/mgba#1371]
Tried to use MGBA on my new 3ds xl, when i touch to load the room, the screen freezes at "loading game...", tried other roms but doesnt work
SNES9x and GBC emulator works 100%

TY

**Comment by endrift** [comment]
Whic version are you using?

**Comment by bfleck123** [comment]
mgba version  0.7.1
3ds  11.9.02-42

**Comment by endrift** [comment]
3dsx or cia?

**Comment by bfleck123** [comment]
3dsx

**Comment by Kickiusz** [comment]
I hae exactly the same issue, same firmware, also new 3ds xl, also 3dsx. GB and GBC roms work with no problems.

**Comment by Kickiusz** [comment]
Also it happens wether or not I use bios.

**Comment by endrift** [comment]
I can reproduce. It looks like the games crash less than a frame after they're loaded, during games' initialization routines. Investigating.

**Comment by endrift** [comment]
Temporary workaround while I figure out how to fix this:

in /mGBA/config.ini, in the [ports.3ds] section add this line:
```
threadedVideo=0
```

and it should work, but it might be slow.

**Comment by mddifilippo89** [comment]
I've confirmed the latest nightly fixed a lot issues. I ran a few gba games and experienced no crashing between swaps as of yet. thank you.
