### ISSUE TITLE
Could mgba be possible on the PSP? If Wii can run it...

### ISSUE THREAD

**Issue by Nashismo** [mgba-emu/mgba#1373]
So yeah,

That is my question, because it is not a demand of course! See guys, I have this emulator running on my Wii, the "enhanced" MGBA version, and it runs absolutely flawlessly!

And I was thinking, this emu is so awesome it could even run on the PSP! But there are no ports currently in development, and it is such a shame, because as far as I know, this is the fastest GBA emulator that exists.

Could anyone port it to the PSP? Could someone like me even do it? I mean a simple guy with free time and not many skills? I once compiled a few Wii emulators and they came out well, but I guess that is much easier.

If you guys know anyone willing to port your emu to PSP, lead me to them :)

Cheers and thank you for this wonderful thing you have made!
Nashismo.

**Comment by endrift** [comment]
Seeing as it doesn't even run full speed on the Vita, this isn't happening any time soon. It would be cool, but it's not feasible without big changes.
