### ISSUE TITLE
[Request] Window pauses emulation when minimised

### ISSUE THREAD

**Issue by RunisDauphin** [mgba-emu/mgba#1379]
Hi, I am Runis Dauphin from Rebelles Unis:

Could you add the feature of having the emulation stopped in case of window minimisation, similar to what Kega Fusion does?

What I would like is having the emulation running while I am doing something else (for example, I am reading a PDF but the mGBA window behind the PDF Foxit Portable is running the emulation and the music) but, when I minimise it, the emulation stops (and time in game does not run and music does not sound) until I deminimise it.

The most similar thing I can do is press the Pause key in the keyboard (who is assigned to "Pause emulation").

**Comment by waddlesplash** [comment]
There is already a "Pause when inactive" setting. Isn't this sufficient?

**Comment by endrift** [comment]
I think they were asking for it to only pause while minimized, but not when in the background.

**Comment by RunisDauphin** [comment]
M. Pfau just nailed it. That is what I want. It is more or less the behaviour that Kega Fusion has in this regard.
