### ISSUE TITLE
Ubuntu x86 Builds 

### ISSUE THREAD

**Issue by Zetchzie** [mgba-emu/mgba#138]
Is there any plans to make this for x86 Ubuntu? very sorry if this is spam but Ive looked everywhere.

**Comment by endrift** [comment]
Are you unable to build it yourself?

**Comment by Zetchzie** [comment]
I cant find anything on how to do that and it only gives me 64bit version

**Comment by Zetchzie** [comment]
Im really sorry if this is spam im new to linux so building it would be new to me i was hoping there was one like on your download page.

**Comment by endrift** [comment]
I'm curious why you installed a 32-bit build, then. Almost all hardware in the last 9 years supports 64-bit.

**Comment by Zetchzie** [comment]
My machine doesn't support 64bit my machine was made back in 2002. I should upgrade but im not rich and getting a new computer is not in the cards. You have a 32bit build for windows why not Ubuntu?

**Comment by endrift** [comment]
I'm surprised that thing still runs at all o.o windows is 32-bit because 32-bit installations of windows are a lot more prevalent still than 32-bit Linux. It'll work on 32-bit Linux but I don't have an environment for compiling it at the moment.

**Comment by Zetchzie** [comment]
Lol yeah i'm surprised it runs as well Its disc drive is gone so it's smashed up My windows XP got corrupted last year so i'm a linux user. Anyways thanks for your quick response. I guess I'll use the windows build under wine for know. Again sorry if this was spam.

**Comment by endrift** [comment]
It'll be a bit slow. You should see about compiling the 32-bit version yourself. You'll need to install the build-essential, cmake, libsdl2-dev, libpng-dev, libzip-dev and qtbase5-dev packages first though.

**Comment by Zetchzie** [comment]
I'm not so sure how to do that If I build anything its usually with a walkthrough. Is there a set of commands I need to run in terminal? I can get those packages in Synaptic Package Manager Right?

**Comment by endrift** [comment]
I can do a write up tonight.

**Comment by Zetchzie** [comment]
Thank you ^^ much appreciated
