### ISSUE TITLE
[Request] Video layer toggle option

### ISSUE THREAD

**Issue by RunisDauphin** [mgba-emu/mgba#1383]
Hi, I am Runis Dauphin from Rebelles Unis:

Could you implement the same system for video layer toggle (for every layer) and sound channel toggle (for every channel) that several VBA branches have? It is useful for some games to know what is hidden behind layers (for example, in Megaman Battle Network games, there are characters and pick-ups hidden behind objects, and they are not always that easy to spot).

**Comment by RunisDauphin** [comment]
And, if possible, could you add a possibility to set shortcuts to set speeds, video layer toggle (for every layer) and sound channel toggle (for every channel)?

**Comment by endrift** [comment]
Already present.
