### ISSUE TITLE
[Request] Keep weird bug with mGBA window

### ISSUE THREAD

**Issue by RunisDauphin** [mgba-emu/mgba#1384]
Hello, I am Runis Dauphin from Rebelles Unis:

I ignore if anyone has perceived it, but if you hold a button while you change window (from mGBA to anywhere), this button will be pressed until you re-enter the window AND press that button again. That affects at least the action buttons and the autofire buttons.

My suggestion is keep it (at least, until autofire buttons become toggle buttons instead of hold ones AND autohold keys, as adressed previously in #1381), because is really useful for monotonous tasks that need to be done in RPGs (although there may be some others that get benefit out of that).

Thanks, and if you change the work model of the autofire buttons, that would be better for spamming in games.

**Comment by endrift** [comment]
This isn't really that easy to fix anyway, given how key input works.
