### ISSUE TITLE
Audio/Video freezes briefly upon saving game.

### ISSUE THREAD

**Issue by Brimcon** [mgba-emu/mgba#1385]
The emulator hangs for a few frames upon syncing savedata on Windows.

This occurs more frequently playing Fire Emblem, as the game saves with every action taken. 

mGBA is the only emulator that does this. Please advise.

**Comment by Brimcon** [comment]
Seems to be related to using mGBA and loading from a different Hard Drive. (EG: mGBA and ROM on E drive. Moving both to C Drive fixes the issue)

**Comment by endrift** [comment]
Yeah, your hard drive was probably just slow. I didn't want to say "get better hardware" though :P

**Comment by Brimcon** [comment]
Fair. mGBA really works wonders on SSDs, not so much on HDDs.
