### ISSUE TITLE
building issue for Turkish language fails

### ISSUE THREAD

**Issue by fpscan** [mgba-emu/mgba#1386]
Hi,

Recently I started to translate mGBA into Turkish and finally I made some progress. I tried to build to see how its looks but my mGBA.exe gives some .dll errors. Such as avutil, avcodec etc. So MSYS log here : https://gist.github.com/fpscan/4c9b7875b7cf5859da17325d88081abe

`-- Checking for one of the modules 'libavresample'
CMake Warning at CMakeLists.txt:151 (message):
  Requested module libavresample missing for feature USE_LIBAVRESAMPLE.
  Feature disabled.
Call Stack (most recent call first):
  CMakeLists.txt:484 (find_feature)`

Even liavresample missing and its disabled .dll errors such as avcodec related to libavre? If anyone can build it for me, I can give Turkish .ts file

**Comment by endrift** [comment]
The problem has to do with how the built file is looking for DLLs. An easy way to solve this is to run mGBA from within the command like, after building it:

`./qt/mGBA.exe`

That *should* work. Don't `cd` into another directory.

**Comment by fpscan** [comment]
> The problem has to do with how the built file is looking for DLLs. An easy way to solve this is to run mGBA from within the command like, after building it:
> 
> `./qt/mGBA.exe`
> 
> That _should_ work. Don't `cd` into another directory.

Thank you so much, It works, and translations looks great. I will change few things then how can I send this for main software.

![image](https://user-images.githubusercontent.com/4651944/56201352-5cf5c300-6049-11e9-89d3-8d1295b15ff0.png)

I assume that I will write nice description and **commit to master**?

**Comment by endrift** [comment]
This would only affect the Qt desktop version.

You'll need to push to a fork and file a PR for me to merge your changes. I can't see them just from the commit ID.
