### ISSUE TITLE
Issue with 3DS nightly build 10/21

### ISSUE THREAD

**Issue by Committee** [mgba-emu/mgba#139]
Using N3DS on 10.1 firmware mgba does not load any rom, getting white screen only.

Tried it through ironhax, themehax, and oot3dhax all with the same results.

Tried loading a clean gba bios and getting a white screen also.

reverted to 10/20 build and works just fine.

**Comment by endrift** [comment]
This is due to some changes I made last night per @smealum's request. Might be a bug in his ctrulib on older *hax payloads.

**Comment by endrift** [comment]
I was wrong about that last comment. Should be fixed in c27dde73e7051ea1da0c604c0ba98d7c347de8fe.
