### ISSUE TITLE
[Request] Shortcut to set up different speeds

### ISSUE THREAD

**Issue by RunisDauphin** [mgba-emu/mgba#1390]
Hi, I am Runis Dauphin from Rebelles Unis:

In some versions of VBA, you can set up hotkeys for different speeds (for example, O key sets 50% speed and I key re-sets 100% speed). This is useful for some zones that are very difficult in some games and require input precision, speed and synchronisation.

**Comment by endrift** [comment]
This will be done by the time the input revamp is merged--it's already done but the code isn't stable enough to merge yet.

**Comment by endrift** [comment]
Action revamp (part of the input revamp) has been merged.
