### ISSUE TITLE
Save Corruption in Minish Cap

### ISSUE THREAD

**Issue by MrDrumline** [mgba-emu/mgba#1392]
EDIT: SRAM patching the game file seems to have fixed the issue? 

This is on RetroArch Android, on a OnePlus 6T on Android 9 Pie. I'm running latest version of the mGBA core the updater will download. This applies both in Play Store stable and recent nightly version of RetroArch.

EDIT: Same issue happens on Windows with RetroArch stable 1.7.6 and latest mGBA nightly.

When I start up Minish Cap the game gives me a message that all of my save files are corrupted. This happens even when no saves for the game exist. When trying to create a save the game warns me it was unable to create a save. 

Of the GBA games I have Minish Cap seems to be the only one where this happens. Playing with/without a GBA BIOS does not fix the issue.

**Comment by lotharsm** [comment]
I just tried with the latest mGBA nightly and I can't reproduce the issue you describe. Which version of the ROM file are you using and is it a "clean" dump?

**Comment by endrift** [comment]
This is a libretro bug I've tracked down to their specific fork--it doesn't occur in upstream.
