### ISSUE TITLE
Telefang Power in-battle menu is missing the right half

### ISSUE THREAD

**Issue by Searinox** [mgba-emu/mgba#1394]
This doesn't occur in the latest release but it does occur in the latest nightlies. Once combat begins, the right side of the battle menu is whited out.

**Comment by endrift** [comment]
Probably an issue with the window feature. Thanks for finding this, I made some risky changes but couldn't find anything it broke.

**Comment by endrift** [comment]
Fix was easy. I regret not looking into it sooner.
