### ISSUE TITLE
Need administrator permission to make new folder and then add to it?

### ISSUE THREAD

**Issue by voorXIII** [mgba-emu/mgba#1395]
Why do I need administrator permission to make a new folder (trying to keep all the games in the same place as the emu) and then need admin perms to add to that folder? I don’t think it was like that for the last version

**Comment by Dimensional** [comment]
Where are you trying to run the emulator from? If you're running it from Windows in either of the "Program Files" Folders, then it definitely requires administrator permissions because that's a secured location that only an administrator can write to.

**Comment by voorXIII** [comment]
Ah, that makes sense then. I put it in the default location it asks which was one of the program files. Thanks for the help!
