### ISSUE TITLE
AGBPrint doesn't print to the console

### ISSUE THREAD

**Issue by paeolo** [mgba-emu/mgba#1397]
I just managed to get AGBPrint to work. It would be very nice to output the strings to the linux console. Is it possible? (I mean it's a feature request..).
Thank you

**Comment by felixjones** [comment]
I'm going to +1 this because I use the debug features a lot, but having to open the logging window every time is rather annoying, I'd be very happy if there was the option to put them to stdout (and OutputDebugString for Win32).

Include mGBA's debug print API with this, not just AGBPrint.

**Comment by endrift** [comment]
This is already possible in the dev builds--check out the new logging config page in settings.
