### ISSUE TITLE
Power Pro Kun Pocket 3 (Japan): BGM timing issues

### ISSUE THREAD

**Issue by Nukotan** [mgba-emu/mgba#1399]
mGBA v0.7.1

The problem that the FIFO ch sound disappears temporarily.
Changing the value of info->when changes the situation.
But I don't know the correct value.
https://github.com/mgba-emu/mgba/blob/1deff07aa1b0d3d4b6b15e875fbeb0cc8eff0926/src/gba/dma.c#L297-L302

**Comment by endrift** [comment]
Does this still reproduce on latest mGBA?

**Comment by endrift** [comment]
Closing due to lack of reply.
