### ISSUE TITLE
Mega Man Battle Network 4 - Jump To Invalid Address randomly after Link Battles

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#14]
If you play multiple Link battles, about 1/6 will cause the emulator to show up with this nifty little popup followed by the game disappearing.
![endrifthalp](https://cloud.githubusercontent.com/assets/6598209/7305397/8d2c8d0e-e9cb-11e4-9980-f786ae7ce594.jpg)

I've reproduced it twice now.  Linking seems to work okay in this game sometimes, but it's pretty garbage framerate wise, and is subject to drop to 5 fps and crash whenever it feels like.

**Comment by endrift** [comment]
This was due to save corruption, since both games were using the same save file. Some sort of safeguard should be added, but that's an enhancement, not a bug.
