### ISSUE TITLE
[Wii] Game won't start (v0.4)

### ISSUE THREAD

**Issue by GB-CG** [mgba-emu/mgba#140]
All I get is a white screen. I'm using the 0.4-2907-5922beb build.
I have a GBA bin file unless it's a incorrect one, or am I overlooking something?

Issue in motion: https://www.youtube.com/watch?v=6agRjlrSiKo

**Comment by endrift** [comment]
Fixed in c27dde73e7051ea1da0c604c0ba98d7c347de8fe.

**Comment by GB-CG** [comment]
Works now! Thanks for checking it out.
