### ISSUE TITLE
RTC example ROM non-functional (vs EZO & VBA-m)

### ISSUE THREAD

**Issue by felixjones** [mgba-emu/mgba#1400]
Attached is an old RTC test of mine written for the EZ Flash Omega cartridge, the C code behind the RTC operation of this ROM is based on the work of the PRET Emerald project (which is guaranteed to produce a working RTC ROM for their toolset).

[rtc_test.zip](https://github.com/mgba-emu/mgba/files/3137667/rtc_test.zip)

This test works on Omega, at the time that was good enough for my needs, however I have never been able to get this working on mGBA. Out of curiosity, I tried this on VBA-m and was surprised to find it worked, so I am left a little puzzled as to where the issue lies.

I have tried writing and re-writing my RTC code a few times over the past week and have been unable to get any kind of response working on mGBA. The correct overrides for RTC have been applied, I have also tried using game IDs from known RTC games to use the automatic HW detection of mGBA and still no luck.

**Comment by endrift** [comment]
Can I see your source? I've modified how the RTC works significantly and it seems to be outputting correctly now but I'm still getting errors from your program.
