### ISSUE TITLE
Recording >2 NVENC streams on Geforce cards

### ISSUE THREAD

**Issue by t0r3n0** [mgba-emu/mgba#1401]
On consumer grade Geforce graphics cards, the max amount of simultaneous streams using NVENC is 2. When clicking Start in the Record video window, a check should be made to ensure that 2 videos arent currently being encoded already, if h.264(NVENC) is selected. Just lost over 2 hours of footage recording 4 games simultaneously (dont ask lol)

**Comment by endrift** [comment]
Turns out it was already checking, but it didn't really let you know adequately that it had failed. It's fixed now.
