### ISSUE TITLE
MultiBoot ROMs fails to load durring GBA BIOS intro

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#1409]
**Version used:**
mgba-qt 0.7.1 64bit Arch Linux.

**Settings:**
in the BIOS section:
- "GBA BIOS file:" is set to a file with a crc32 of 0x81977335
- "Use BIOS file if found" is checked
- "Skip BIOS intro" **un**checked.

**Steps to reproduce:**
Compile or find a ROM such that the multiboot header is extended from the main GBA header, is able to boot normally as a ordinary GBA rom, and is also able to be transferred as is, via the GBA MultiBoot protocol, to run from WRAM.

DevkitARM builds such ROMs when the output filename ends with "_mb.gba", attached is such a build from it's example template.
[template_mb.gba.zip](https://github.com/mgba-emu/mgba/files/3169696/template_mb.gba.zip)

**Expected results:**
BIOS plays it's intro with the text "Nintendo®" intact, fades to white, and loads the multiboot ROM as a ROM (which will then most likely proceed to copy itself to WRAM to run there instead).

**Actual results:**
BIOS plays it's intro but with blank text, as if no cartage was inserted. Indeed a quick look in Tools->View Memory shows that all Game Pak ranges shows the open bus pattern.

**Comment by endrift** [comment]
Multiboot ROMs are mapped into EWRAM and usually fail if you try to load them in the ROM address range. The BIOS clears EWRAM at boot time. I'm not sure what else there is to say here?

**Comment by jroatch** [comment]
I guess I ultimately wanted a option to *not* automatically load up MultiBoot roms in EWRAM because I needed to see if a particular ROM would function the same when started by either ROM or RAM Entry Points.

If loading to EWRAM with BIOS always fails because of the EWRAM clearing, why not try loading it as a ROM? It may "usually fail" but not always.

**Comment by endrift** [comment]
That's also confusing and unexpected. I'd need to figure out a better UI for this.

**Comment by endrift** [comment]
This was addressed by making the BIOS automatically be skipped if it's a multiboot ROM.
