### ISSUE TITLE
[Feature Request] 3DS Port Button Remapping and Fast Forward Option

### ISSUE THREAD

**Issue by Committee** [mgba-emu/mgba#141]
Request in title, possible with the 3DS port or already in the roadmap?

**Comment by endrift** [comment]
Already in the roadmap, just haven't gotten to it yet.

**Comment by Committee** [comment]
Thank you, good to close this then.

**Comment by endrift** [comment]
I'm going to leave it open until I implement it, actually.

**Comment by endrift** [comment]
Oh wow I totally missed the "fast forward option" part of this. Not going to be possible--the 3DS isn't fast enough for that to do anything useful in almost any game.

**Comment by Committee** [comment]
Harvest Moon FOMT :)

It'a alright it was just a thought.

**Comment by endrift** [comment]
I ended up implementing fast forward anyway, even though it doesn't work very well (read: at all in most games)
