### ISSUE TITLE
mgba-qt crash missing glTexEnvf

### ISSUE THREAD

**Issue by mrcmunir** [mgba-emu/mgba#1411]
I have tried compiling for OpenGL desktop, Opengl es2 and Opengl es3 for nvidia jetson nano and in all modes returns

```
No provider of glTexEnvf found.  Requires one of:
    Desktop OpenGL 1.0
    OpenGL ES 1.0
```

It's weird because it supports Opengl 4.6 core and Opengl es 3.2

This only happen in mgba-qt but working fine in non-qt build.

**Comment by endrift** [comment]
Can you try this again on latest master? I made a lot of changes in that region.

**Comment by mrcmunir** [comment]
@endrift Thanks it's working and fixed 
![Captura de 2019-05-20 02-33-20](https://user-images.githubusercontent.com/1274014/57990593-6dfe7d80-7aa8-11e9-9f2b-44da1b649e49.png)
