### ISSUE TITLE
Black screen on OpenGL

### ISSUE THREAD

**Issue by themalu866** [mgba-emu/mgba#1414]
Playing on Windows 7, win-32.
This problem is recent, none of the games are loading and if I go to Settings and then press Ok or Apply the emulator just crashes and none of the changes I made are saved.
I also noticed that in Shortcuts that the letters only change if move the mouse out of them.
In this image the "P" only changed to "R" when I moved the mouse, this didn't happen in older versions.
![rerewr](https://user-images.githubusercontent.com/42208976/58107049-7b5a5b80-7bbf-11e9-9f9d-3221bd331fa4.png)
And for some reason a copy of mgba keeps appearing on AppData\Local\Temp.

**Comment by endrift** [comment]
The settings crashing bug is fixed, can you see if any of the other stuff is resolved?

**Comment by themalu866** [comment]
Driver Display: on OpenGL is screen is black but the music still plays.
But on Software (Qt) and OpenGL (force version 1.x) is okay.
![errer](https://user-images.githubusercontent.com/42208976/58202005-e2097300-7cac-11e9-907e-bd1c2a408f8c.png)

And if I try to put a Shader the emulator crashes.
So yeah, is still not fixed.

**Comment by endrift** [comment]
What GPU do you have?

**Comment by themalu866** [comment]
Ati Radeon 3000 Graphics
I checked 0.7.1 and everything worked fine.

**Comment by endrift** [comment]
That's a pretty ancient card. I'm assuming your drivers are as up to date as they can be?

**Comment by themalu866** [comment]
Yes, like I said the 0.7.1 released on Feb 24, 2019 is working fine, the newest ones are the problem.
0.8-5613-bb7f41e8 was also working fine

![rtr4](https://user-images.githubusercontent.com/42208976/58226156-d002f100-7cfb-11e9-9e77-4b3132e0e869.png)

**Comment by Cibomatto2002** [comment]
Maybe if you delete the config file that may help.

**Comment by themalu866** [comment]
I already tried this and it doesn't work.
I even delete the entire mgba folder on AppData\Roaming and it didn't work.
And it keeps crashing when I try to use a shader.
![yuyu](https://user-images.githubusercontent.com/42208976/58321386-661a4280-7df4-11e9-96f0-a543872c1cdd.png)

**Comment by endrift** [comment]
Ok, should be more fixed now. Let me know.

It may still crash if you select the OpenGL renderer (as opposed to the OpenGL display driver), but that's harder to fix.

**Comment by fanboy01** [comment]
I also have a issue when using shaders.

For starters, mGBA starts up just fine and there were no crashes when navigating the menus.  

I loaded the gba-color shader just fine and my game had no problems

Though, when I closed mGBA and tried to restart it, mGBA wouldn't restart.

I deleted my entire config,ini and mGBA could open again.

Another way I solved the issue was by just deleting the line referencing shader use in config.ini

**Comment by themalu866** [comment]
So on Display driver OpenGL: still black but with the sound and OpenGL force version 1.x is working fine.
For the shaders: on both OpenGL and force version 1.x if I try to load a shader with NO game loaded it still crashes but if load the shader with a game loaded it doesn't crash (but still black on OpenGL)
![erer](https://user-images.githubusercontent.com/42208976/58368548-0fc90480-7ec5-11e9-820e-db54e3aa2dc6.png)
But the same thing that happened with fanboy01: then if if close mGBA with a shader loaded and try to open again it doesn't restart and this appears and I can only delet the emulator if I end WerFault.exe
![7887](https://user-images.githubusercontent.com/42208976/58368577-72ba9b80-7ec5-11e9-896b-efc0b4fb66ff.png)

**Comment by endrift** [comment]
The shader crashes should be fixed now. Let me know about the black screen issue.

**Comment by themalu866** [comment]
Yes, the shaders are working now but the screen still black on OpenGL.
Software and force version 1.x are working fine.
![reer](https://user-images.githubusercontent.com/42208976/58466668-7aba4b80-8110-11e9-8100-3bfa60e54b6c.png)

**Comment by benderscruffy** [comment]
have an AMD Radeon HD 7450
any game using opengl is black screen with music playing with or without Interframe blending ticked
i can only use software (Qt) now

**Comment by endrift** [comment]
I ordered an AMD Radeon HD 7450 on eBay for testing. Hopefully it shows up soon, because it seems to work fine on an R7 240.

**Comment by Suissant** [comment]
I have a radeon hd 5770 with the last driver released by amd (they stopped supporting the radeon 5xxx hd series) and have the exact same problems already reported in here.

**Comment by QcSamuel** [comment]
on the latest Development build the opengl renderer is a black screen too on my 1050ti with updated drivers

**Comment by themalu866** [comment]
The black screen still in the 0.8-5931-81fd7e3c1 on both 32 and 64.
![err](https://user-images.githubusercontent.com/42208976/65522782-a92f1400-dec1-11e9-9ee8-52bc2342a0e1.png)
But on 0.7.3 is fine.
![qwewqe](https://user-images.githubusercontent.com/42208976/65522813-b815c680-dec1-11e9-943d-f8e0a33f64cd.png)
And question: why this message appears as default in 0.7.3?
I thought it was removed a long time ago in the Windows version.
Is there any way to disable this?

**Comment by themalu866** [comment]
Now OpenGL and Software (Qt) are working but OpenGL (force version 1.x) isn't.
![trrt](https://user-images.githubusercontent.com/42208976/66266576-457be380-e7fd-11e9-966c-1f55c3097c8b.png)
![ytrty](https://user-images.githubusercontent.com/42208976/66266594-7d832680-e7fd-11e9-9e50-525c7f055ed9.png)

**Comment by endrift** [comment]
Is this with the very latest dev build? I made an important change in the most recent commit.

**Comment by endrift** [comment]
Can you confirm if this works again now?

**Comment by themalu866** [comment]
OpenGL and Software (Qt) are fine but OpenGL (force version 1.x) isn't working.
![ytyt](https://user-images.githubusercontent.com/42208976/89570496-abaa0c00-d7fc-11ea-88f0-60a9932518b8.png)

**Comment by endrift** [comment]
This is almost certainly fixed by now. If not, tell me and I'll reopen.

**Comment by ZeptoBST** [comment]
When starting a game from command line in Windows, the issue occurs. Does not happen when launching a game manually from the interface.

**Comment by endrift** [comment]
> When starting a game from command line in Windows, the issue occurs. Does not happen when launching a game manually from the interface.

Same symptoms, different bug. You want #2781
