### ISSUE TITLE
Wii - Loading GBA roms in 7z/zip crashes

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#1417]
4e2052f9341e05a47a20e4060d5dd56d741e0088 is the first build that fails.

In Dolphin it hangs on the "Loading..." screen, on console it's just a black screen. For some reason, if I load a gb/gbc zipped rom and then load a zipped gba rom it will work but then on the next load it will still crash.

**Comment by endrift** [comment]
Does 52ac4d686 help at all?

**Comment by SuperrSonic** [comment]
Yes, it works now!
