### ISSUE TITLE
F-Zero Climax menus not being displayed properly

### ISSUE THREAD

**Issue by fanboy01** [mgba-emu/mgba#1419]
When using mGBA 0.8-5734-89983901, some of the menus in F-Zero Climax are not displaying correctly.

Here's what the grand prix menu looks like in mGBA 0.8-5734-89983901 

Notice how the menu label looks fuzzy and blurry looking

![wrong menu](https://user-images.githubusercontent.com/30210016/58361900-6551d280-7e2d-11e9-8f42-52223135b74a.PNG)

And here's what this menu is supposed to look like (mGBA 0.7.1)

![correct menu](https://user-images.githubusercontent.com/30210016/58361907-76024880-7e2d-11e9-8677-550a72b99e32.PNG)

More egregious is the time attack menu which has missing labels!

![Time attack menu](https://user-images.githubusercontent.com/30210016/58361928-9f22d900-7e2d-11e9-83ae-e55b6fdcfb5f.PNG)

**Comment by endrift** [comment]
Is this with the Software renderer or OpenGL renderer?

**Comment by fanboy01** [comment]
It was with the software renderer.  I just tried the OpenGL one and still no luck. 

And for what it's worth, using Windows 10 64-bit 1803.  Graphics card is NVIDIA GeForce MX130

**Comment by endrift** [comment]
I have a fix for that crash, but I'm still investigating the ordering issue.

**Comment by endrift** [comment]
Regressed in 459eaefcfcf75a177ddecab65e7896279109f7c5.
