### ISSUE TITLE
Konjiki no Gash Bell - Unare Yuujou no Zakeru 2 - minor graphical garbage

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#142]
Save file: http://www.mediafire.com/download/4mic7jqd88cznsq/Konjiki_no_Gashbell%21%21_-_Unare%21_Yuujou_no_Zakeru_2_%28Japan%29.sav
Once it gets to the main menu, select VS Mode and Free Battle or similar to select the specified char team. Those parts are in English.
![char](https://cloud.githubusercontent.com/assets/6880539/10704985/9e51dc2a-79a8-11e5-8552-71980c628432.png)
The selected character team's intro animation before the match begins consistently shows a small 8x8 pink/blue garbage above the characters and goes away before the animation ends.

![mgba](https://cloud.githubusercontent.com/assets/6880539/10705118/9818ab80-79a9-11e5-84c9-e9854f976646.PNG)

**Comment by endrift** [comment]
I don't seem to be able to reproduce this in any build that I try.

**Comment by SuperrSonic** [comment]
I used the Wii version, Oct 25 nightly and the libretro android version both with and without bios. I checked with other emus and it did not occur so I don't think it's a bad rom.

I also tried the libretro Wii version, and it was slightly different, the color was green instead.
Is there anything else I could try? Unfortunately I can't confirm this issue on other platforms.

**Comment by endrift** [comment]
Oh oops, I was using the wrong character. I've been able to reproduce now.

**Comment by endrift** [comment]
Fixed in b8b7ec0b12cdfa3aab1da32e06e8868e76ed9dbb.

**Comment by SuperrSonic** [comment]
Thank you!!

**Comment by SuperrSonic** [comment]
This issue seems to be back in the latest nightly, although it's slightly different and sometimes smaller. It doesn't really bother me but either way decided to confirm this here in case it might interest you.

**Comment by endrift** [comment]
Hmm, I double checked to see if it was back when I made the change last night and I thought it was gone still. Strange.

**Comment by SuperrSonic** [comment]
![konjiki-0](https://cloud.githubusercontent.com/assets/6880539/10992209/51ad3602-843a-11e5-8e4c-fc7dbc13e59b.png)
I noticed something that might help reproduce this, load into a free battle and then exit for 4 times it will look like the above screen, the fifth time however will look like the screen below. Did this various times, it always resulted the same way. Could you confirm this behavior?
![konjiki no gashbell - unare yuujou no zakeru 2 japan -0](https://cloud.githubusercontent.com/assets/6880539/10992356/73e51e1e-843b-11e5-8b8f-2e4bb67211e0.png)

**Comment by endrift** [comment]
I think this might have been fixed again in the meantime.

**Comment by SuperrSonic** [comment]
No change from what I tried.
