### ISSUE TITLE
Memory Test anomaly in mGBA 0.7.2

### ISSUE THREAD

**Issue by Zenjir0** [mgba-emu/mgba#1420]
Odd behavior occurs when trying to run the Memory Test suite in gba-suite v0-r51.

In mgba 0.7.1 test finished successfully.

In mgba 0.7.2 test runs, but fails to show results and returns to the main menu. All other tests work as intended.

**Comment by themalu866** [comment]
On 0.7.2 I noticed that f I try to change the FPS Target on the Settings window it doesn't work and it always goes back to 59.7275.
I can only change it on the mgba window but if I go to the Settings window it goes to 59.7275 again, and I don't even need to change the FPS, it goes to Native automatically.
![sdsds](https://user-images.githubusercontent.com/42208976/58389000-70a72880-7ffc-11e9-86ea-f10812a3713f.png)
And the option to give GB games GBC colors is missing.
![rtrt](https://user-images.githubusercontent.com/42208976/58389032-d09dcf00-7ffc-11e9-9258-f232bcd98334.png)

**Comment by endrift** [comment]
Please stay on topic.

**Comment by endrift** [comment]
Fixed by fc2b0432077fc6d497be13ea1344bc2b197168e8
