### ISSUE TITLE
FPS automatically changing to Native

### ISSUE THREAD

**Issue by themalu866** [mgba-emu/mgba#1421]
On 0.7.2 I noticed that f I try to change the FPS Target on the Settings window it doesn't work and it always goes back to 59.7275.
I can only change it on the mgba window but if I go to the Settings window it goes to 59.7275 again, and I don't even need to change the FPS, it goes to Native automatically.
![58389000-70a72880-7ffc-11e9-86ea-f10812a3713f](https://user-images.githubusercontent.com/42208976/58389158-1909bc80-7ffe-11e9-8f04-b01f7ffaf8db.png)

**Comment by endrift** [comment]
This is fixed in master. Please check a development build. I'll merge it for an 0.7.3 if there is one though.
