### ISSUE TITLE
HEVC nvidia showing in red (not available)

### ISSUE THREAD

**Issue by branchus** [mgba-emu/mgba#1422]
Hi
I try to record the game using HEVC nvidia encoder. but it show in red and I cannot use it.

h264 nvidia works fine.

My current graphic card is nvidia Quadro P2000 (nvidia workstation card), the below link points to the official nvenc support on nvidia website
https://developer.nvidia.com/video-encode-decode-gpu-support-matrix

Quadro P2000 supports HEVC nvenc encoder and it support unrestricted co-current sessions compare to the normal Geforce card.

Can you look into this please?
Thanks

**Comment by endrift** [comment]
I actually noticed the same thing recently. I'll look into it when I get a chance.

**Comment by endrift** [comment]
Turns out the ffmpeg build wasn't configured to have HEVC nvenc enabled. Future builds should have this fixed.
