### ISSUE TITLE
Unexpected behaviour related to mute toggle when fast forwarding + miscellaneous improvements

### ISSUE THREAD

**Issue by iuzwpr2p39rh7w** [mgba-emu/mgba#1424]
Muting the audio by clicking on "Audio/Video" -> "Mute" then unlocking the FPS target with "Fast forward (held)" or "Fast forward" (Tab and Shift+Tab, respectively) will unmute the audio.
I had just muted the game audio because I was only testing something which did not require game audio for a while so I opted to listen to something else and turned the system audio back up leading to me being mildly startled by the loud high-pitched game intro.
After some research, I learned that this issue had been [brought up before](https://mgba.io/i/1234) and that there is a seperate setting for muting fast forward volume. Toggling it requires three mouse clicks ("Tools" -> "Settings..." -> [Audio/Video ->] "Mute") and does not seem to be assignable to a shortcut. Having the option to mute the audio output when fast forwarding independently of the normal audio is useful, but I do not find it intuitive as I would expect the game audio to be quiet after clicking on "Mute", as did Cibomatto2002 in the aforementioned issue.
My proposed solution is to mute all audio when "Mute" is enabled, as I do not know of a scenario where one would want to disable the normal but not the sped up audio, add an entry for muting audio only when fast forwarding under "Mute" and make it also assignable to a shortcut.

Unrelated to this issue, I suggest assigning "Ctrl+M" as default key combination to toggle muting the audio as it currently is unbound and should be intuitive to other users. Personally, I would like to be able to see the audio levels also as percentages instead of just as unlabeled sliders. Even better would be to add the ability to manually input specific values.
Additionally, I want to point out that the No-Intro .dat should be updated. It may not be necessary to do this for each release, but the three .dat files, that [nointro.dat](https://github.com/mgba-emu/mgba/blob/d8dc368f36e37a9c318600eb06068302687b1823/res/nointro.dat) is based on, are more than three years out of date.
Finally, the copyright information scattered over many different souce files and visible on the Windows binary under "Properties" -> "Details" is out of date and does not match [your website's footer](https://github.com/mgba-emu/www/blob/0050fb1d2c14edf690b4024a05cd262850ad9111/_config.yml#L4).

**Comment by endrift** [comment]
I've updated the dat.

I'll look into the mute thing tomorrow. That sounds like a bit of an oversight that the menu setting doesn't affect both.

You're right that the copyrights are generally out of date. However, that's not hugely important. I don't generally set all of them to the current year on projects anymore, only when I make big changes to files, and I've been forgetting.

**Comment by endrift** [comment]
I thought about default assigning Ctrl+M, but it would have required a bit of restructuring that didn't seem worthwhile, especially since manually binding it is easy.
