### ISSUE TITLE
REQ: DSi port

### ISSUE THREAD

**Issue by Ntemis** [mgba-emu/mgba#1426]
Hi, since there is a port for 3DS how feasible is to request a mgba for DSi consoles.
At least for gba core emulation i think would be enough for a lot of people.
Regards
P.s i have HiyaCFW on my DSi and i am willing to test everything if you need a tester.

**Comment by profi200** [comment]
GBA emulation on DSi is impossible. The closest you will get is this: https://github.com/Gericom/GBARunner2

GB(C) is doable but i don't think it's worth it especially since there are already good ones.
