### ISSUE TITLE
Super Mario World messed up graphics

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#1432]
![Super Mario Advance 2 - Super Mario World-0](https://user-images.githubusercontent.com/6880539/58619373-cd237580-8292-11e9-90f7-46963978bd18.png)

Appears to have regressed here https://github.com/mgba-emu/mgba/commit/3056655060b3be0eabd35742ea2b8e1cb18ccb09

**Comment by endrift** [comment]
Thanks for tracking this down, I had noticed it earlier but didn't look into it at the time.
