### ISSUE TITLE
Setting the audio buffer absurdly high crashes all games

### ISSUE THREAD

**Issue by ROMaster2** [mgba-emu/mgba#1433]
Happened with the latest build, `0.8-5800-a1cdd65e`. 

This happened by mistake. I set my audio buffer to 400256 when I meant to set it to 400 instantly crashed mGBA. Any attempt to load a new ROM (without fixing the number) crashes too.

Probably a minor issue since no sane person would want that setting, but it's easily reproducible.

**Comment by endrift** [comment]
More or less fixed in d048917b72d008f0c0776cfc9f3defd9f6c72ef7.
