### ISSUE TITLE
Windows - Bilinear Filtering doesn't work with OpenGL

### ISSUE THREAD

**Issue by teconmoon** [mgba-emu/mgba#1435]
Edit: Bilinear Filtering doesn’t work in conjunction with the GBA Color Shader.

Original Post: When my display driver is set to **OpenGL**, the **Bilinear filtering** option does nothing. With **Software (Qt)** or **OpenGL (force version 1.x)** selected, **Bilinear filtering** works as expected.

I was originally going to just leave **OpenGL (force version 1.x)** selected as a workaround, but shaders are only selectable while the **OpenGL** display driver is in use.

Running Intel(R) HD Graphics 615. Thanks for reading!

**Comment by endrift** [comment]
Which shader are you using that's causing this issue? It seems to work for several of them, but not all of them.

**Comment by teconmoon** [comment]
Hi there, thanks for the reply. Currently using the GBA Color Shader included with mGBA. Not sure how I missed this during troubleshooting, but like you stated, I don’t have this issue if I’m not using that shader.

**Comment by endrift** [comment]
Yeah, that's the only one I've been able to reproduce this issue in. I have a fix forthcoming.

**Comment by teconmoon** [comment]
Nice, I look forward to it! Let me know if you need a tester
