### ISSUE TITLE
Sprites do not load correctly on 0.7.2

### ISSUE THREAD

**Issue by RunisDauphin** [mgba-emu/mgba#1436]
Hi, I am Runis Dauphin from Rebelles Unis:

I was playing Klonoa Empire of Dreams (USA) on mGBA 0.7.2 (Windows). The sprites do not load correctly when they are partially covered on the top end of the window.

Hope you can solve it.

Runis Dauphin

**Comment by RunisDauphin** [comment]
This is an example of the problem. The glitched graphic on the top is a blackhole (or maybe a Flying Moo). Sometimes, in some computers, when replicating the error and conditions are met, the sprite, instead of appearing glitched, does not appear at all. The second image is how it should look (and how it does look in the same game file with version 0.7.1 with the exact same configuration).
![GBA Klonoa 1 - Empire of Dreams (Estados Unidos)](https://user-images.githubusercontent.com/49384468/59416247-4bb90080-8dc5-11e9-9454-2f97a04205d0.png)
![GBA Klonoa 1 - Empire of Dreams (Estados Unidos)](https://user-images.githubusercontent.com/49384468/59416262-51aee180-8dc5-11e9-8c22-14f67f525530.png)

If helpful, this corresponds to Ghazzaland, vision 1-1, end of the second screen, but can be appreciated and perceived in any level.

I do not know what is going on with this 0.7.2 version, but it seems to have errors that had been solved in previous versions.

**Comment by endrift** [comment]
This was fixed in 0cace151e1148cfd12d4175f816a044871d8e113, so it'll be fixed in the next release--if there's an 0.7.3, it'll be there, otherwise 0.8.0.
