### ISSUE TITLE
Pokemon Pinball and Zelda: Minish Cap Audio crackling, slow [3ds]

### ISSUE THREAD

**Issue by saphiroko** [mgba-emu/mgba#1440]
Both of these roms work fine when I run them on VBA on PC, but it's super crackly and slower than normal on mGBA. The games themselves also run at a much slower rate than they should be. My framerate goes between 24 and 35 but it's probably half as fast as it should be. Could this be something wrong with how I installed my CFW? Or maybe a setting I just missed? I tried all of the different frameskips too, and nothing changes. I used the guide for Seedminer + Fredtool from 3ds.hacks.guide. Thanks!

**Comment by endrift** [comment]
Are you on o3DS? o3DS is too slow to run mGBA at full speed.

**Comment by saphiroko** [comment]
I'm on the 3dsXL, would that make a difference?

**Comment by endrift** [comment]
Original 3DS XL or New 3DS XL?

**Comment by saphiroko** [comment]
Original, sorry!

**Comment by endrift** [comment]
Yeah, unfortunately there's not much to be done there. Sorry about that. There may be a port of gpSP that works faster.

**Comment by saphiroko** [comment]
Aww darn. Thank you for the quick response though!
