### ISSUE TITLE
[psvita] Latest build have issues with saves in Pokemon fire red

### ISSUE THREAD

**Issue by Turbito** [mgba-emu/mgba#1441]
at time of writing this the latest nightly is at commit https://github.com/mgba-emu/mgba/commit/5321ffd2277a277a3aafda23a5956c8c06b4d94f

Loading Pokémon fire red (haven't tested any other game) got the game telling the save is damaged and won't save. And start a new game. 
I have rolledback to stable 0.7.2 and it works again in psvita as expected

I don't have any log but feel free to write me how I got them if needed

**Comment by endrift** [comment]
Can you send me a 'damaged' save? I've been getting scattered reports of flash-type saves being broken but I haven't been able to reproduce.

**Comment by Turbito** [comment]
Sure. This work under Linux and psvita with 0.7.2 but not in psvita with the nightly
[pkmn_firered.sav.zip](https://github.com/mgba-emu/mgba/files/3268246/pkmn_firered.sav.zip)

**Comment by endrift** [comment]
Strange, it seems to work for me. Can you send your config.ini too?

**Comment by Turbito** [comment]
Weird. Updated again from 0.7.2 to that nightly and it's working now.
I tested it when happened and could reproduce it twice. The last update was from a nightly to another nightly but I don't think that is relevant.
Clossed issue I guess :/
