### ISSUE TITLE
Mario Kart - Super Circuit graphical corruption with OpenGL renderer on Windows

### ISSUE THREAD

**Issue by angrylion7** [mgba-emu/mgba#1443]
Since revision `5817-ff8f03a` I always have corrupted graphics in the game's scrolling intro (evident by just letting the intro run) and in several other places in the game, such as the "Luigi Circuit" track of the "Lightning Cup". Most tracks/levels of the game are not affected by this though. Only happens with the OpenGL renderer, regardless of the "high-resolution scale" setting. I'm on Windows 7 x64, with a GeForce GT630 1 GB VRAM (GK208 chip) and latest nVidia driver v430.86.

![5817](https://user-images.githubusercontent.com/16341594/59180950-d522c580-8b6e-11e9-9637-d4c8323e3dfd.png)

![5817-2](https://user-images.githubusercontent.com/16341594/59181433-06e85c00-8b70-11e9-9114-4c7a234fa312.png)

**Comment by angrylion7** [comment]
Cannot test the 32-bit build of 09ccf54 uploaded to mgba.io on Windows 7 x64: Procedure starting point “_free_locale” not found in DLL “msvcrt.dll”. This cannot be fixed by installing CRT redistributables. The culprit might be a Qt update or a compiler update.

**Comment by endrift** [comment]
Culprit appears to have been ImageMagick, which I'm downgrading to a slightly older version (it's only used for outputting GIFs so this should be safe), and you can check again after a new build is published using it sometime tomorrow.

**Comment by endrift** [comment]
Was this resolved?

**Comment by angrylion7** [comment]
Yes, it was fixed, sorry for not specifying that.

**Comment by endrift** [comment]
I'm not sure what fixed it, but I'm glad to hear it's fixed.
