### ISSUE TITLE
Golden Sun - Depth issues

### ISSUE THREAD

**Issue by Krusher97** [mgba-emu/mgba#1444]
![temp](https://user-images.githubusercontent.com/25664221/59182121-8f71f700-8b86-11e9-83e2-dd461186543a.png)

The carpet is rendered over character sprites. There are some other areas too where similar layering issues occur.

Battery Save near the area : [Golden Sun (U).zip](https://github.com/mgba-emu/mgba/files/3271196/Golden.Sun.U.zip)

**Comment by endrift** [comment]
Works fine in 0.7.x, but fails on master.

**Comment by SuperrSonic** [comment]
Seems to start here 459eaefcfcf75a177ddecab65e7896279109f7c5

**Comment by Dimensional** [comment]
I've noticed issues like this even playing on other GBA emulators, and it usually only happens when some cheats are enabled, like No Clipping.

**Comment by Krusher97** [comment]
![temp](https://user-images.githubusercontent.com/25664221/59331572-e7893480-8d11-11e9-8f9d-2e43942ac789.png)
Working in the latest nightly.
