### ISSUE TITLE
Pokemon Cloud White crashing

### ISSUE THREAD

**Issue by kris657** [mgba-emu/mgba#1449]
Been trying to solve this issue for a couple of hours, but to no avail. 

When playing the Pokemon Fire Red romhack Pokemon Cloud White, the game crashes/freezes when you do anything related to opening the pokemon menu where you view your party and/or checking the summary. It seems to work properly on VBA-M, however i much prefer using mGBA instead

Hopefully this is fixable. I could try and deploy a manual fix if anyone has any suggestions to solving this. Thank you.
[Pokemon Cloud White v.523d.ups.zip](https://github.com/mgba-emu/mgba/files/3293358/Pokemon.Cloud.White.v.523d.ups.zip)

**Comment by endrift** [comment]
Finally got around to testing this on hardware; it crashes there too. The bug is with the ROM hack.
