### ISSUE TITLE
Audio corruption

### ISSUE THREAD

**Issue by Yalefeuv** [mgba-emu/mgba#145]
Version: mGBA 0.3.1
System: Win7 64 bits Pro SP1
Game: Bengt - 2004Mbit Compo Game (homebrew available here http://gbadev.org/index.php?showinfo=1272)
Steps to reproduce: Launch Bengt (first game in the list) then wait for the demo to start or press A or Down.
Bug: Audio corruption  (audio is fine on real hardware)

Log sample (looping):
STUB:	Keypad interrupts not implemented
STUB:	Stub I/O register write: 130
STUB:	Stub I/O register read: 002
STUB:	Stub video register write: 0x002
STUB:	Keypad interrupts not implemented
STUB:	Stub I/O register read: 084
STUB:	Stub I/O register read: 084
STUB:	Keypad interrupts not implemented

**Comment by endrift** [comment]
The audio corruption is almost certainly unrelated to the keypad interrupts.

**Comment by endrift** [comment]
Confirmed, this bug is unrelated to keypad interrupts, although it's true that keypad interrupts are not implemented. I should have a proper fix for this tonight.

**Comment by Yalefeuv** [comment]
Thanks for this quick answer. I will change the title.

**Comment by endrift** [comment]
This was fixed in a93b21e88640848a0dac4a1319ffb4e3506040b6, btw.
