### ISSUE TITLE
No sound for both gb, gbc and gba for version 0.7.2-3ds

### ISSUE THREAD

**Issue by chen4393c** [mgba-emu/mgba#1461]
Is any version's sound available for 3ds? Could you please fix it?

**Comment by endrift** [comment]
Make sure you've dumped the DSP blob. https://github.com/Cruel/DspDump/releases

**Comment by dvlprCabret** [comment]
Not works, I have this message, Im using last version of mGBA-0.7.2 and luma 

Fetching DSP component...

Failed: Need to run using *hax 2.0+

Press START to exit.

**Comment by endrift** [comment]
This is not the place to ask for troubleshooting with other projects.

Anyway, if you google 3DS dsp dump I'm sure you'll find instructions.
