### ISSUE TITLE
mgba-util/dllexports.h stuck behind SKIP_LIBRARY=OFF but still required when ON

### ISSUE THREAD

**Issue by mackal** [mgba-emu/mgba#1464]
If I do `cmake -DBUILD_LIBRETRO=ON -DSKIP_LIBRARY=ON -DUSE_EDITLINE=OFF ..` dllexports.h is not created but still required to build

```
mgba/include/mgba/core/log.h:10:10: fatal error: mgba-util/dllexports.h: No such file or directory
   10 | #include <mgba-util/dllexports.h>
      |   
```

If I do `ccmake ..` to manually toggle stuff on/off causes the file to be generated though (probably one of the times I have to hit c to get it to show me things)

(As with my last issue, same reason for USE_EDITLINE being OFF)

**Comment by lotharsm** [comment]
I can confirm this on MSYS2/Mingw64.

**Comment by mackal** [comment]
Getting a new error now (same set up)

```
CMake Error at /usr/share/cmake/Modules/GenerateExportHeader.cmake:399 (get_property):
  get_property could not find TARGET mgba.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  CMakeLists.txt:1002 (generate_export_header)
```

**Comment by endrift** [comment]
I guess I misunderstood how generate_export_header works. Will look into it closer in a bit.

**Comment by mackal** [comment]
I know the last issue I had with `-DBUILD_LIBRETRO=ON -DSKIP_LIBRARY=ON` also gave a TARGET issue.

**Comment by softtwo** [comment]
Quick fix looks like this:

https://github.com/mgba-emu/mgba/blob/master/CMakeLists.txt#L1002
```
if(BUILD_LIBRETRO)
	generate_export_header(${BINARY_NAME}_libretro BASE_NAME ${BINARY_NAME} STATIC_DEFINE BUILD_STATIC EXPORT_FILE_NAME ${CMAKE_CURRENT_BINARY_DIR}/include/mgba-util/dllexports.h)
elseif(BUILD_OPENEMU)
	generate_export_header(${BINARY_NAME}-openemu BASE_NAME ${BINARY_NAME} STATIC_DEFINE BUILD_STATIC EXPORT_FILE_NAME ${CMAKE_CURRENT_BINARY_DIR}/include/mgba-util/dllexports.h)
else()
	generate_export_header(${BINARY_NAME} BASE_NAME ${BINARY_NAME} STATIC_DEFINE BUILD_STATIC EXPORT_FILE_NAME ${CMAKE_CURRENT_BINARY_DIR}/include/mgba-util/dllexports.h)
endif()
```

TARGET changes between ```mgba_libretro```, ```mgba-openemu``` and ```mgba```.

Maybe you can set a TARGET_NAME variable in the script to squash the multiple branches together.

I compile with this for minimal features:
```-DLIBMGBA_ONLY=ON -DBUILD_LIBRETRO=ON -DSKIP_LIBRARY=ON```

**Comment by mackal** [comment]
I did test out @softtwo 's suggestion, which did work, but maybe there is a better way to do it.

**Comment by softtwo** [comment]
It's not elegant so I didn't PR it. :wink:

Something more reasonable would be:
https://github.com/toufy/mgba/blob/master/CMakeLists.txt#L11
```
set(BINARY_NAME mgba CACHE INTERNAL "Name of output binaries")
set(TARGET_NAME mgba)
```

https://github.com/toufy/mgba/blob/master/CMakeLists.txt#L906
```
	set(TARGET_NAME ${BINARY_NAME}_libretro)
	file(GLOB RETRO_SRC ${CMAKE_CURRENT_SOURCE_DIR}/src/platform/libretro/*.c)
```

https://github.com/toufy/mgba/blob/master/CMakeLists.txt#L919
```
	set(TARGET_NAME ${BINARY_NAME}-openemu)
	find_library(FOUNDATION Foundation)
```

https://github.com/toufy/mgba/blob/master/CMakeLists.txt#L1002
```
generate_export_header(${TARGET_NAME} BASE_NAME ${BINARY_NAME} STATIC_DEFINE BUILD_STATIC EXPORT_FILE_NAME ${CMAKE_CURRENT_BINARY_DIR}/include/mgba-util/dllexports.h)
```

We can then replace lines like ```${BINARY_NAME}_libretro``` with ```${TARGET_NAME}``` all over script. But I leave it to @endrift 's creativity for any better solution.

**Comment by endrift** [comment]
I think what I'm going to do actually is bypass that header file if it's libretro or openemu and predefine the things in common.h if it is
