### ISSUE TITLE
MGBA Vita constantly crashing after update

### ISSUE THREAD

**Issue by NintendoGamer83** [mgba-emu/mgba#1466]
I updated MGBA on Vita to latest version.
I then got the C2-12828 error.
Assumed it was due to the new version.
Uninstalled it, then installed an older version. I still got the error message.
Any hints please?

**Comment by endrift** [comment]
Latest stable (0.7.2) or latest dev (0.8-[...])? Can you upload your config.ini?

**Comment by NintendoGamer83** [comment]
The 0.7.2 one.
How do I upload that?

**Comment by endrift** [comment]
Use vitashell and ftp to grab it from ux0:/data/mGBA/config.ini. It should be small enough that you can paste it in here.

**Comment by NintendoGamer83** [comment]
It says 'we dont support that file type'

**Comment by NintendoGamer83** [comment]
This is what i got from opening it though:

*[gui.input.PSP2]
keyTake screenshot=-1
keyIncrease solar brightness=-1
keyDown=6
keyLeft=7
keyUp=4
keyDecrease solar brightness=-1
keyBack=13
keyCancel=12
keyRight=5
keyFast forward (held)=-1
keyScreen mode=13
keySelect=14
keyFast forward (toggle)=-1

[ports.psvita]
autoload=1
useBios=1
screenMode=2
autosave=1
sgb.borders=1
lastDirectory=ux0:/ROM/GBA/
frameskip=1
camera=1
gba.bios=ux0:/ROM/GBA/gba_bios.bin
fpsCounter=0

[gba.input.PSP2]
keyR=9
keyL=8
axisUpAxis=-0
keyStart=3
keyLeft=7
keyDown=6
axisLeftAxis=-1
keyB=15
keyUp=4
axisUpValue=64
axisDownAxis=+0
axisRightValue=192
axisRightAxis=+1
axisDownValue=192
keyA=14
keyRight=5
axisLeftValue=64
keySelect=0

*

**Comment by endrift** [comment]
Thanks.

Are you getting the crash when loading a game or the emulator itself?

**Comment by NintendoGamer83** [comment]
Loading the emulator itself.
It loads up.
Shows no games. Then the error message.

**Comment by endrift** [comment]
Are you running in safe mode or unsafe mode? (Vitashell should tell you which mode is active if you're not sure)

**Comment by NintendoGamer83** [comment]
Unsafe mode.
I didn't have this problem until after I updated MGBA.
I also tried that Kai GBA emulator in Adrenaline after this, and got a GPU crash.
Playing GBA games in Retroarch is still ok though.

**Comment by endrift** [comment]
Ok, one last question: does the folder ux0:/ROM/GBA/ exist?

**Comment by NintendoGamer83** [comment]
No. 
I have roms in a folder called "AAAROM" so that its quicker to find.

**Comment by endrift** [comment]
Perfect. That should be enough information for me to diagnose and fix this. In the meantime, delete the lastDirectory and gba.bios lines (you can do this directly in vitashell so you don't have to reupload it) and that should hopefully work around the crash.

**Comment by NintendoGamer83** [comment]
Are those in the config in Tai?

**Comment by endrift** [comment]
No, they're in the ux0:/mGBA/config.ini file.

**Comment by NintendoGamer83** [comment]
Thanks.
Ill try that

**Comment by NintendoGamer83** [comment]
It actually worked.

**Comment by endrift** [comment]
Should be fixed in the dev builds now, for real. Will also be fixed in 0.7.3, when that comes out.
