### ISSUE TITLE
Frames skipping even on 0 frames to skip.

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#1470]
The last few Development build updates I have had trouble with frames skipping. Even if I put it on 0 frames to skip it still does it The last mGBA that work correct for me was mGBA-build-2019-05-21-win64-5709-2781a2a9f951b39ff89e47d0d13106918e1316c3

Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Pentium G3240 @ 3.10GHz	43 °C
	Haswell 22nm Technology
RAM
	8.00GB Dual-Channel DDR3 @ 698MHz (10-10-10-25)
Motherboard
	Gigabyte Technology Co. Ltd. H81-D3 (SOCKET 0)
Graphics
	ELEFW328 (1360x768@60Hz)
	Intel HD Graphics (Gigabyte)
	1023MB NVIDIA GeForce GT 720 (EVGA)
	ForceWare version: 417.35
	SLI Disabled
Storage
	931GB TOSHIBA DT01ACA100 (SATA )
Optical Drives
	HL-DT-ST DVDRAM GH24NSC0
Audio

**Comment by endrift** [comment]
There were a lot of commits between 5709 and now. All of them are buggy?

**Comment by Cibomatto2002** [comment]
Sorry but I don't know what else to say about my problem. Here is a video I made to show you what i'm talking about.

https://www.youtube.com/watch?v=y-v6LpCRieI&feature=youtu.be

**Comment by endrift** [comment]
Is that the only game that does this? It's basically impossible to tell it's frameskipping in that game. And please test other builds between 5709 and latest, as there are a lot.

**Comment by Cibomatto2002** [comment]
No all games do it I tested other builds right after 5709 that's when it starts Game Boy advance does it to maybe when Qt: Improve GL syncing got improved that is causing my problem.

**Comment by Cibomatto2002** [comment]
Just got mGBA 0.7.3 and it looks like it may be fixed now.

**Comment by endrift** [comment]
0.7.3 does not include the buggy branch, which is still present in nightlies.

**Comment by endrift** [comment]
Should be fixed in 3920c6191f2caa155b1e5ef67f4b5ce26e8a7093, let me know.

**Comment by Cibomatto2002** [comment]
Fixed on my end
