### ISSUE TITLE
Debugging with GDB broken between 0.6.3 and 0.7.2

### ISSUE THREAD

**Issue by johnbentcope** [mgba-emu/mgba#1471]
My environment is Win10 64, using VSCode and compiling with DevKitARM. As the title states, the same template project (https://github.com/JamieDStewart/GBA_VSCode_Basic) succeeds in a debugging effort while using 0.6.2 and 0.6.3 but not with 0.7.2. 

When calling mGBA 0.7.2 from the application, the code runs on the system, ignoring breakpoints, and an error message appears in VSCode stating

> Unable to start debugging. Unexpectedly GDB output from command "-target-select remote localhost:2345". Remote replied unexpectedly to 'vMustReplyEmpty': timeout

Happy to provide more input on this issue if needed.

**Comment by endrift** [comment]
Can you check if this is still broken? I made some fixes last night.

**Comment by JamieDStewart** [comment]
Just ran through this with mGBA 0.7.3 Win64 and can confirm that GDB debugging is working again in the current stable release version of mGBA on windows.
