### ISSUE TITLE
mGBA for 3ds soft gets crashed often

### ISSUE THREAD

**Issue by Noctehuan** [mgba-emu/mgba#1474]
I've download the mGBA V0.72 and used FBI installed it on my new 3dsxl, but after I used this emulator a few days, I found that  V0.72 easily crashed: detail was that open the emulator and then just press UP DOWN LEFT RIGHT or any other keys random for a while(about 1min) then the emulator crashed. Remember that don't open any a game, just on the menu and press any keys for some times. Hope next version can fixs it.and now I'll still use the v0.6, personally I think V0.72 still not so stable.

**Comment by endrift** [comment]
If one of those buttons is X that cleanly exits the emulator from the menu—not crashing.

**Comment by Noctehuan** [comment]
> If one of those buttons is X that cleanly exits the emulator from the menu—not crashing.

Thanks for you remind, tried again, hold X (Or B) in the menu for about 3 seconds will directlt exit, is this a default setting of the emulator?

**Comment by endrift** [comment]
Yes.

**Comment by Noctehuan** [comment]
> Yes.

Okay that's  fine.
