### ISSUE TITLE
"Libretro core OFF" in cmake when attempting to compile using vitasdk

### ISSUE THREAD

**Issue by webodan** [mgba-emu/mgba#1477]
I'm attempting to build the libretro core of mgba for psvita (as i can't find it anymore inside of vpk packages of libretro's buildbot site for some reason), and I'm not having luck because it just disables this option for me in the compiler. I've used the commands listed in the readme of this page after installing vitasdk and vdpm, and this is what I got:

```
-- Build type: Release
-- Platforms:
-- 	Game Boy Advance: ON
-- 	Game Boy: ON
-- Features:
-- 	Debuggers: ON
-- 	CLI debugger: ON
-- 	GDB stub: ON
-- 	Video recording: ON
-- 	GIF recording: OFF
-- 	Screenshot/advanced savestate support: ON
-- 	ZIP support: libzip
-- 	7-Zip support: ON
-- 	SQLite3 game database: ON
-- 	ELF loading support: ON
-- 	Discord Rich Presence support: ON
-- 	OpenGL support: libepoxy
-- Frontends:
-- 	Qt: ON
-- 	SDL (2): ON
-- 	Profiling: OFF
-- 	Test harness: OFF
-- 	Test suite: OFF
-- 	Python bindings: OFF
-- 	Examples: OFF
-- Cores:
-- 	Libretro core: OFF
-- Libraries:
-- 	Static: OFF
-- 	Shared: ON
-- Configuring done
-- Generating done
-- Build files have been written to: /w/x/y/z
```

How can I make it compile the libretro core?

**Comment by endrift** [comment]
I guess I forgot to reply to this, but you can't build the libretro core for vita (or 3DS, Wii, or Switch) via the upstream repo. You need to use the makefile in the downstream repo.
