### ISSUE TITLE
Dragon Ball Z - Gokuu Gekitouden (Japan) (SGB Enhanced) (GB) crashes

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#1478]
at the start of the game just keep going right and it will crash 
![dragon](https://user-images.githubusercontent.com/2696404/60394383-15fe7080-9b56-11e9-8e5e-7692d1261852.PNG)

**Comment by endrift** [comment]
Happens in BGB and SameBoy too. Wonder if it's a bad dump.

**Comment by benderscruffy** [comment]
before you fixed it the intro was missing now it is shown
