### ISSUE TITLE
Freeze/Hang in Super Street Fighter II Turbo - Revival

### ISSUE THREAD

**Issue by ctbfourone** [mgba-emu/mgba#1480]
OS: macOS 10.14.5
Versions: mGBA 0.7-0.7.2-5488-c2b6692ce and OpenEmu 2.0.9.1

After you select a character in Arcade mode the game (audibly too) grinds to a halt. In-game it should be showing a speed selector (normal/turbo 1/turbo 2/etc). Tested in Boycott Advance and couldn't reproduce it. Haven't tried it on Linux or Windows.

**Comment by endrift** [comment]
Can reproduce in 0.7.2, but it seems to have been fixed in the meantime. I recommend using a dev build at least for now.

**Comment by ctbfourone** [comment]
Also got this error message.

<img src="https://fourone.org/~ctb/misc/mgba-ssf2tr-freeze.jpg">

**Comment by ctbfourone** [comment]
Thanks!
