### ISSUE TITLE
Sound crackling & frame rate issues in Fire Emblem GBA game on PS VITA

### ISSUE THREAD

**Issue by mohasi** [mgba-emu/mgba#1483]
First congrats on the great work!

I unfortunately came across issues on the first game I tried. I am using the latest 0.7.2 release for the VITA. The first game I am trying, and the only game I really want to play is Fire Emblem, on the intro scene there are many frame rate drops and lag, frame rate drops to around 45, and sound is delayed.

After the intro the frame rate goes back to around 59.

A worse problem is the constant oddities in sound. There are "crackles" frequently and the sound is not smooth.

I am also using a GBA bios but that has made no difference. I also later tried the build for the latest commit "OpenGL: Fix 1.x interframe blending" which has the same issues.

Please if you could take a look. Thanks.

PS. What is the render resolution with the border? The PS VITA's 960*544 would look perfect at 3X original GBA resolution. If it is not at 3X, would be great to have that for the VITA as default.

**Comment by endrift** [comment]
Unfortunately both issues stem from the fact that mGBA isn't able to run at full speed on the Vita's low powered CPU. Without it being faster there's not much that can be done here.

Also the GBA screen should be at 720x480, i.e. 3x.

**Comment by mohasi** [comment]
Hi endrift, thanks for your reply. Please could you explain why would this https://www.reddit.com/r/VitaPiracy/comments/8yzmg4/near_perfect_gba_emulation_gpsp_kai/ be able to run at full speed with sound on the PSP and mGBA is finding the VITA under powered?

**Comment by endrift** [comment]
gpSP is a significantly less accurate emulator; it takes a lot of shortcuts that mGBA doesn't, and as a result is able to run games closer to actual hardware.
