### ISSUE TITLE
The Yeti3D GBA Engine Demo stuck on Gameboy screen bug

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#1487]
using the latest dev version
stuck on the gameboy screen
https://www.gbadev.org/download.php?section=demos&ID=568

**Comment by endrift** [comment]
ROM doesn't have the logo bytes. This would happen on real hardware too.

**Comment by benderscruffy** [comment]
this works on my GBA sp with EZflash omega
