### ISSUE TITLE
Crazy Racer 3D (GBA) stuck on Gameboy screen bug

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#1488]
using the latest dev version
stuck on the gameboy screen
https://gbadev.org/download.php?section=games&ID=696

**Comment by endrift** [comment]
ROM has an invalid header checksum. This would happen on hardware too.

**Comment by benderscruffy** [comment]
this loads on my GBA sp with EZflash omega

**Comment by endrift** [comment]
Doesn't that bypass the BIOS screen though? I'm pretty sure loading a ROM in EZF Omega goes straight into the game.
