### ISSUE TITLE
Ending emulation crashes emulator

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#149]
Whether by using the "shutdown" option from the menu or exiting the emulator entirely, shutting down emulation ends in Windows giving a "mGBA Game Boy Advance emulator has stopped working" popup.

**Comment by endrift** [comment]
What build are you using? I thought I fixed this.

**Comment by tony971** [comment]
Latest nightly

**Comment by endrift** [comment]
This was an issue with libepoxy, which I had just started using last night. I updated to a different version of libepoxy and the bug went away. Should be fixed in the next nightly as a result.
