### ISSUE TITLE
Video output choppy after 787c99b949b93e7263c53f483ff556dbd9684869

### ISSUE THREAD

**Issue by CounterPillow** [mgba-emu/mgba#1496]
* CPU: Intel(R) Core(TM) i7-7500U CPU (2c/4t)
* GPU: whatever iGPU that uses
* OS: Arch Linux x64, X11 with KWin

I've noticed git master having noticeably choppy video output compared to 0.7.2. So I went on my merry way bisecting this and landed on 787c99b949b93e7263c53f483ff556dbd9684869.

To bisect this, I booted the GBA bios in mgba-qt while full-screened, resetting the console a couple of times with Ctrl+r to get a good feel for the video output. "good" commits had a noticeably smooth entry of the letter G, whereas bad commits didn't. The builtin video recording doesn't capture any framedrops, so my guess is that it's purely an issue with presentation.

 May be related to #1470.

**Comment by CounterPillow** [comment]
Looks like I can make it less choppy if I make the timer fire more often with the following change:

```patch
diff --git a/src/platform/qt/DisplayGL.cpp b/src/platform/qt/DisplayGL.cpp
index 06ff72f1..411e111e 100644
--- a/src/platform/qt/DisplayGL.cpp
+++ b/src/platform/qt/DisplayGL.cpp
@@ -294,7 +294,7 @@ PainterGL::PainterGL(QWindow* surface, QOpenGLContext* parent, int forceVersion)
                m_free.append(new uint32_t[1024 * 2048]);
        }
 
-       m_swapTimer.setInterval(16);
+       m_swapTimer.setInterval(1);
        m_swapTimer.setSingleShot(true);
        connect(&m_swapTimer, &QTimer::timeout, this, &PainterGL::swap);
 }
```

But that's clearly not the proper solution. Why is the swapTimer interval hardcoded to 16 anyway?

**Comment by rzumer** [comment]
Is this a millisecond count rounded down from 60fps? No wonder it misses some frames if so, error will accumulate.

**Comment by CounterPillow** [comment]
If that's the case then this presentation loop design also breaks things like G-Sync/FreeSync, since it swaps 60 times a second instead of swapping whenever there is a new frame to display.

I guess this was done for things like frame blending?

**Comment by Cibomatto2002** [comment]
I'm glad I"M not the only one with the choppy Video output.

**Comment by kurayami6** [comment]
I know how you feel. I thought I must have been imagining it or something. But it's definitely fucked.

**Comment by LimitCrown** [comment]
I have been experiencing this issue as well, and it feels like the video becomes much choppier as the audio buffer setting is increased. I have tried to set the FPS target to either 60 fps or the native frame rate of 59,7275 fps as well, but nothing manages to alleviate the problem.

**Comment by FateForWindows** [comment]
I'd also like to add that any build made after this commit seems to be stuck at 30 FPS with Sync on Video enabled, and changing the display driver and/or renderer doesn't make a difference. I have a feeling this is what the video output actually is with Sync on Video on.

Just for comparison, with that setting off in the latest build Mega Man and Bass averages around 550 FPS on my laptop with sync off. Frameskip is not enabled. So obviously, whatever sync fix was put in place seems to have messed it up more. Also, just to note, my laptop's display is 1080p, 60Hz.

**Comment by Dotty** [comment]
I found that it appears locked at a visual 30 FPS (Though full speed) with Sync to Video off, but Sync to Audio on. And not even a consistent 30FPS, as whether odd or even frames would be displayed swaps about every second (Harvest Moon dialogue boxes). That also completely locks up for a few seconds every 20-30 seconds.
Sync to Video on, with or without Sync to Audio, displays all the frames, but runs at about 56-58FPS. With absolutely awful audio obviously.

Thankfully the RetroArch core still works fine; with butter smooth audiovisuals. So if you're okay with using that (No Link or high resolution support) it's a fair option for now at the very least.

**Comment by FateForWindows** [comment]
Sync issues still persist as of commit 1dc405d

**Comment by Cibomatto2002** [comment]
Just got mGBA 0.7.3 and it looks like it may be fixed now.

**Comment by endrift** [comment]
It's not. I've been working on it but 0.7.3 is from a branch that doesn't include the buggy code.

**Comment by endrift** [comment]
Should be fixed in 3920c6191f2caa155b1e5ef67f4b5ce26e8a7093, let me know.

**Comment by Cibomatto2002** [comment]
Fixed on my end.

**Comment by LimitCrown** [comment]
The framerate issue appears to be fixed for me now as well. However, it now appears that trying to load a shader when a game isn't active will cause the emulator to crash and if a shader was loaded before opening the emulator, the emulator won't start. I'm not sure whether this is due to this change, but it wasn't present in 0.7.3.

**Comment by CounterPillow** [comment]
Buttery smooth now, thanks for fixing this!

**Comment by FateForWindows** [comment]
Fixed for sure! Thank you!
