### ISSUE TITLE
Minish Cap Crashes during big octo fight

### ISSUE THREAD

**Issue by nephitejnf** [mgba-emu/mgba#1497]
This version if the PAL/Euro version. It has happened once on stream.
My install in the mgba from the Arch repos.
https://www.twitch.tv/videos/458137547

**Comment by RetroEdit** [comment]
This may seem like a bad question, but is this actually an emulation bug? I've had similar crashes happen on an actual GBA, and it's possibly just a bug in the Minish Cap game itself. The Minish Cap speedrunning community would probably know more details, though.

**Comment by RetroEdit** [comment]
So I asked around The Minish Cap's speedrunning Discord, and they linked to at least one case of a crash happening on console (no weird sound though): https://www.twitch.tv/videos/96331519

There's also some save states related to this bug (BizHawk format though, unfortunately): if you hold 'A' to bounce the rock back at the Octo boss, then the game will freeze. This works in both older (2.3) and the most recent stable release of BizHawk, both with and without the Bios enabled. Rename the file extension to '.State' to use it.

[Zelda_no_Densetsu_-_Fushigi_no_Boushi_Japan.mGBA.QuickSave1.zip](https://github.com/mgba-emu/mgba/files/4182540/Zelda_no_Densetsu_-_Fushigi_no_Boushi_Japan.mGBA.QuickSave1.zip)


Mikesky also said: 
> i'm pretty sure it's due to some sprite limit on gba... most happen when there's an excess of sprites on screen, roll dust, flame particles, rock exploding... we keep encountering a similar bug with lantern in rando... If leo happens to track down and patch it for rando, perhaps we can make a patch for tmc proper.

Also, this a bit more of hearsay, but I have a friend who was playing it recently on console and complaining about crashes, and I can ask them about it.

Honestly, I think it's probably safe to say this isn't an emulator bug at this point, but this can definitely wait for further confirmation and testing if that's preferable.

**Comment by RetroEdit** [comment]
Just as an additional, I asked my friend about the sound, and they said it was the exact same sound.

**Comment by PPLToast** [comment]
Hello. Just for some clarification, the screeching audio is the result of not playing with real bios. The music is supposed to keep playing like normal. As for the issue at hand, it's for sure not an emulator bug. I think it has something to do with the camera as Octo gets hit but that's about it. I'd close.

**Comment by RetroEdit** [comment]
On real console, I'm pretty sure I've experienced screeching audio too, and this is also what my friend said (who's played it much more recently than me). So maybe there are multiple ways the audio can be affected by the crash.

Also, somewhat related, but I think some people in the Minish Cap Speedrunning Discord Server were wondering if it might be possible to patch a fix, since it affects the original game, and I think it would be cool if that could happen.

**Comment by endrift** [comment]
> Hello. Just for some clarification, the screeching audio is the result of not playing with real bios.
This is fixed now. Thanks for pointing out that discrepancy.

**Comment by endrift** [comment]
Closing because this is very likely a game bug and not an emulation bug.
