### ISSUE TITLE
Wrong emulation of thumb BL instruction for large values

### ISSUE THREAD

**Issue by SiD3W4y** [mgba-emu/mgba#1500]
The arm reference defines the thumb bl instruction as such (T1 encoding)

```
Notes:
ARMv4T, ARMv5T, ARMv6, ARMv7 if J1 == J2 == 1
ARMv6T2, ARMv7 otherwise

Encoding:
BL1: | 11110 | S | imm10 |
BL2: | 11 | J1 | 1 | J2 | imm11 |

The immediate is encoded as such: SignExtend(S:I1:I2:imm10:imm11:0)

With:
- I1 = not(J1 ^ S) 
- I2 = not(J2 ^ S)
```

The documentation is confusing as it may let the user think that J1 and J2 must be equal to 1 at all times, which is not the case.

The problem is that mgba doesn't use the J1 and J2 value in the computation of the final address. The current implementation works for calls in a 4Mb range but not beyond (and as per the reference the supported range for this branch is 16Mb). For such jumps mgba will just jump over the call.

We can see this in action in this gist with the current implementation and the fixed one where only the large branch fails:  https://gist.github.com/SiD3W4y/7f13922073a7c4470e3ab5704455d83d
(even though BL1/BL2 are handled in isa-thumb.c, the computations are the same). 

I tried to fix it myself but failed to find a way to cleanly do it as there are now collisions in the instruction lookup table (BL2 has 4 different encodings instead of one).

**Comment by endrift** [comment]
The documentation clearly states that the non-1 cases (the ones in question here) only apply to ARMv6T2 and ARMv7. ARMv4T, which is what the GBA uses, and ARMv5T, which is what the DS uses, both disallow this.

If you can demonstrate that the ARMv7 version works on GBA I'll fix this, otherwise you've misread the docs.
