### ISSUE TITLE
Codebreaker Slide codes - increment not working?

### ISSUE THREAD

**Issue by oleg-py** [mgba-emu/mgba#1501]
Hi there, I have a problem with using a cheat for Final Fantasy IV Advance 1.1 (European version) on 0.7.2 Win64 (c2b6692ce2a5abcfc47dc4ddad020059eb82767e)

All items (Use Fat Chocobo to withdraw items)
```
72022B94 6624
82022B94 F800
72022B94 F800
82022B96 0203
72022B94 F800
82022B92 0144
72022B94 F800
4203F800 0001
00010144 0004
72022B94 F800
4203F802 0063
00000144 0004
```

The problem lies in this bit:
```
4203F800 0001
00010144 0004
```

It is supposed to do 324 (0x0144) writes offset by 0x0004 bytes starting from 0x203F800, incrementing each consecutive value by 0x0001. It seems mGBA ignores the increment part, however, which I can see in memory editor. In game that portion is an item ID, so result is same item repeated 324 times.

**Comment by endrift** [comment]
Seems like I was working off of flawed/incomplete documentation. Should be an easy fix.

**Comment by oleg-py** [comment]
@endrift I've just checked the cheat with latest dev. build and it works as intended. Thanks a lot!
