### ISSUE TITLE
Pokemon Cloud White 1 Consistent Crashing

### ISSUE THREAD

**Issue by Noviian** [mgba-emu/mgba#1502]
Hey, I don't know if it's within rules to make another post about an issue already listed, but the other dude doesn't list very much info or any info at all, so I'm going to fill in that here.
(original issue the other guy posted is #1449)

The version of the emulator I'm running is 0.7.2 (according to the window title). I'm playing the first release of the fanmade pokemon game Pokemon Cloud White and I didn't download any of the extra patches listed on the site, although they may have been included in the original download. I'm not sure.

In the pokemon screen, selecting to see the summary of any kind of pokemon results in the emulator giving me a black screen. Rewinding, fast forwarding, changing the display driver, syncing to either video or audio, nothing changes the result.

[Here](https://pastebin.com/cw4sY3vH) is the last few seconds of the logs.

The logs were speeding by so fast, I was getting probably dozens of errors and warns per second until the game blackscreened and all of it stopped, ending with
"[GAME ERROR] GBA Memory:	Bad BIOS Load32: 0x00000038
[WARN] GBA:	Illegal opcode: 0000efff"
at the end.

Hope this gets fixed soon, I'm a huge fan of pokemon cloud white and now, your new emulator I've found. But for now, I'll be using a different emulator to play Pokemon Cloud White.

**Comment by Ryuhouji** [comment]
This is not a problem with mGBA. mGBA is a highly accurate GBA emulator, and probably the best of its kind. You need to get a hold of the romhacker that is working on cloud white and have them fix their invalid address jump. Which is what causes this error. I am also working on a romhack, and I target mGBA. Pokemon cloud white should too.

**Comment by endrift** [comment]
I tested this on hardware and @Ryuhouji is correct, it crashes there too. Although I was not willing to jump to that conclusion without testing it.
