### ISSUE TITLE
mGBA-build-2019-08-03-win32 load game bug

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#1504]
Using mGBA-build-2019-08-03-win32-5887-aba3ef017cbed199f901b885a8cacbd7f3c776b9 build will not load any game. This is a far as I can get. 

![Capture2-26-2019-1 00 36 AM4-13-2019-1 36 54 PM8-12-2019-1 32 50 AM](https://user-images.githubusercontent.com/21169038/62848416-30715100-bca1-11e9-9ee1-c58679565be3.jpg)

**Comment by Testsr** [comment]
mGBA-build-2019-08-14-win32-5889-cee01c738569f00a9b0674f5daeaa55fa58ac9b7 works.
![Test](https://user-images.githubusercontent.com/31809837/63097137-f959b300-bfb2-11e9-80f1-456bb8066a8d.png)

**Comment by Testsr** [comment]
Close commit.

**Comment by Cibomatto2002** [comment]
Thanks
