### ISSUE TITLE
Missing backgrounds in KOF 95

### ISSUE THREAD

**Issue by neogeo-user** [mgba-emu/mgba#1508]
mGBA "0.8.0" compiled from RetroPie source, commit [8cf7b43](https://github.com/libretro/mgba/tree/8cf7b434fefb52be8bb3effe61e8fb16e9297733)—I hope you don't mind me reporting this issue here. Running on Raspberry Pi 2.

Playing King of Fighters 95, there seem to be missing backgrounds; it appears in the intro screen and also during battle. These appear fine with Gambatte

Happens in both SGB (what I'm glad that mGBA supports) and regular GB modes.

mGBA SGB:
![King of Fighters '95, The (USA) (SGB Enhanced)-190821-091834](https://user-images.githubusercontent.com/54290622/63415905-5b247d80-c3f6-11e9-901e-7917e7ed2ee3.png)
![King of Fighters '95, The (USA) (SGB Enhanced)-190821-091848](https://user-images.githubusercontent.com/54290622/63415912-5d86d780-c3f6-11e9-959f-f16e1bdb8809.png)

mGBA GB:
![King of Fighters '95, The (USA) (SGB Enhanced)-190821-093455](https://user-images.githubusercontent.com/54290622/63416262-07fefa80-c3f7-11e9-9d96-1ca1c68c6adb.png)
![King of Fighters '95, The (USA) (SGB Enhanced)-190821-093507](https://user-images.githubusercontent.com/54290622/63416273-0a615480-c3f7-11e9-9b02-e9c9e2ae044d.png)

Gambatte:
![King of Fighters '95, The (USA) (SGB Enhanced)-190821-092028](https://user-images.githubusercontent.com/54290622/63415935-69729980-c3f6-11e9-8ce9-84d8bc078cd2.png)
![King of Fighters '95, The (USA) (SGB Enhanced)-190821-092038](https://user-images.githubusercontent.com/54290622/63415939-6b3c5d00-c3f6-11e9-828b-9cb53d3df532.png)

Thank you for your effort.

**Comment by endrift** [comment]
Seems to work on my end. Might be something wrong with the libretro branch.

**Comment by neogeo-user** [comment]
Thanks for looking into it @endrift.

**Comment by neogeo-user** [comment]
I copied the current `mgba` into libretro's `mgba` fork; after modifying their `Makefile.libretro` makefile I managed to get it compiled as a libretro core (I couldn't see how to create one from regular mgba).

And the backgrounds were there in all their glory!

I've filed the issue with libretro so I hope they can fix it. Thank you for your time.
