### ISSUE TITLE
Search for an unknown value

### ISSUE THREAD

**Issue by Cleverking2003** [mgba-emu/mgba#1510]
Cheat Engine has an option for searching for an unknown value. This feature would be very useful in MGBA for reverse engineering and romhacking. Could this feature be added?

**Comment by endrift** [comment]
Can you describe what it actually does in more detail?

**Comment by Cleverking2003** [comment]
Here's an example: https://www.youtube.com/watch?v=hgrIKUR5Hww. The feature is called 'Unknown initial value'.
