### ISSUE TITLE
ARMIPS symbols are supposed to be case insensitive

### ISSUE THREAD

**Issue by Zeturic** [mgba-emu/mgba#1512]
ARMIPS treats all its symbols case insensitively (it actually does so by lowercasing everything). I don't know why, just that it does so.

When mGBA automatically reads in a matching `.sym` file when loading a ROM for use in the debugger, it doesn't take this into account. This is somewhat inconvenient when the lowercase version isn't the "canonical" version of the name - e.g. in C-land it's called `Foo` but ARMIPS (and consequently mGBA) call it `foo`.

Since case sensitivity is fairly ubiquitous, I can understand if you'd rather not have case insensitivity by default, but an option would be nice.

**Comment by endrift** [comment]
That sounds more like an issue with ARMIPS than mGBA. I'm unlikely to change this, but I'll leave it open while I think about if adding an option is worthwhile.

**Comment by Zeturic** [comment]
I just opened a PR for ARMIPS to make it case preserving when outputting `.sym` files. If it gets merged, it should make this a nonissue.
