### ISSUE TITLE
Mute keyboard shortcut not muting fast forward volume

### ISSUE THREAD

**Issue by LuckyLapras** [mgba-emu/mgba#1517]
not sure if this really counts as an issue, but when i press ctrl+m to mute, it doesn't mute the fast forward volume, and i have to go into the settings anyway to do that. running 0.7.2 on windows 10
![image](https://user-images.githubusercontent.com/40395281/64251153-b040b300-cf0f-11e9-89f9-50c72b41addb.png)
![image](https://user-images.githubusercontent.com/40395281/64251168-bcc50b80-cf0f-11e9-96e9-f4f7f1ea1341.png)

**Comment by endrift** [comment]
Dupe of #1424. Will be fixed in 0.7.3 when I release that.
