### ISSUE TITLE
Zen - Intergalactic Ninja (USA)graphics glitch

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#1519]
when running it through the super gameboy the alien head is out of place
![zen2](https://user-images.githubusercontent.com/2696404/64468626-867acc80-d159-11e9-9810-d7ae5555b5a5.PNG)

**Comment by endrift** [comment]
Confirmed, happens in non-SGB mode too.

**Comment by endrift** [comment]
This appears to be a window bug.
