### ISSUE TITLE
Games play at half-speed unless settings menu opened first

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#152]
Booting directly to a ROM or opening mGBA and then launching a ROM will make the game play at 30.3-30.5 fps. Opening and closing the settings menu before playing the game fixes this for some unknown reason. Ending emulation and starting it again also fixes the issue but resetting does not.

**Comment by endrift** [comment]
Guh. Windows again?

**Comment by tony971** [comment]
Yea, it's safe to assume that all of my issues are tested on Windows 10

**Comment by tony971** [comment]
Ending emulation and starting it again also fixes the issue but resetting does not.

**Comment by tony971** [comment]
This is dependent on the audio buffer sample rate setting. Does not occur between 1024-2048 samples.

**Comment by endrift** [comment]
Please confirm if this is fixed in the next nightly.

**Comment by tony971** [comment]
Still not fixed. To reproduce, set audio buffer to 4096 samples and then close mGBA. When you open mGBA again, load a recent ROM before touching anything else.

**Comment by endrift** [comment]
I can reproduce on 4096.

**Comment by endrift** [comment]
Fixed in 21d51964e8be28f2b5e294510c55bee4eb267862.
