### ISSUE TITLE
Mgba 0.7.3 Crash on ps vita

### ISSUE THREAD

**Issue by AnimeRar** [mgba-emu/mgba#1527]
When I play Pokemon hack, MGBA always crashes
Error code in PS Vita (C2-12828-1)
Sorry if my English is bad
![15686187058018892894037781405689](https://user-images.githubusercontent.com/42729263/64940295-ce9e9b00-d88d-11e9-9c3a-78202b59f6dc.jpg)

**Comment by endrift** [comment]
Does it only crash for the Pokémon hack, or does it crash with all games? And which hack?

**Comment by AnimeRar** [comment]
Only pokemon hack, I play pokemon adventure red chapter, pokemon Mega power, pokemon flora sky rebirth, pokemon light platinum Mega, and pokemon Mega power
