### ISSUE TITLE
Audio issues in 0.7.3

### ISSUE THREAD

**Issue by Lighti85** [mgba-emu/mgba#1529]
Sound effects that should sound like explosions, deep dark hits or thunder are just barely hearable and extremly high pitched in 0.7.3
It's quite extreme in some games and sometimes the sound effects are just a little bit distorted. But they are "wrong" now in almost every game.
This didn't occur in 0.7.0

Extreme examples:
"The Legend of Zelda - Link's Awakening": Thunderstorm in the intro of the game
"Tetris": When a block hits the ground

Less extreme examples:
"Super Mario Land": Dying enemies (e.g. the explosion after jumping on turtles)
"Turtles - Fall of the Foot Clan": Weapons sounds and exploding enemies (after you hit them)

Setup Details:
mGBA Version: 0.7.3 64bit (Standalone Version)
Windows: 10 Pro 64bit
CPU: i7-2600k
GPU: Nvidia GTX 970
Audio: External Audio Interface (fiiO e10k Olympus 2)

**Comment by endrift** [comment]
Does this occur in 0.7.2 or is it a regression in 0.7.3? I was playing SML last night so I'm pretty sure it happens in master too.
