### ISSUE TITLE
Cannot set FPS target faster than 60

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#153]
You can physically select the option and audio will become high-pitched and choppy, but the framerate will remain at 60. Possibly related to #117

**Comment by endrift** [comment]
Probably the same bug, but I've been unable to reproduce it. Does it still reproduce on all of the old nightlies?

**Comment by tony971** [comment]
Thee last working nightly was October 11.

**Comment by endrift** [comment]
The October 12 bug should be fixed in the October 25 nightly. Is it not?

**Comment by tony971** [comment]
It was working from 10/25-10/30. Broken again by 11/2.

**Comment by endrift** [comment]
So somehow shaders broke this...weird.

**Comment by endrift** [comment]
Please confirm if this is fixed in the upcoming nightly.

**Comment by tony971** [comment]
Closing because it's the same bug as #117
