### ISSUE TITLE
Sound issues with all gb/gbc games on Atmosphere Switch with 0.73 and newer nightlies

### ISSUE THREAD

**Issue by Instandhaltung** [mgba-emu/mgba#1532]
The sound on gb/gbc games is buzzing and scratchy, often directly at the beginning of the emulation. When going to the menu of mgba, the sound works again until shortly later. It seems that the sound gets worse especially after a full screen redrawing (like changing from a game menu to gameplay), but it could be my imagination.

System: Switch with Atmosphere (FW8.1.0)
mGBA 0.7.3 and newer, older versions (if availabe) not tested
Overclock does not improve or worsen the problem

**Comment by Instandhaltung** [comment]
I'd really like to try the new buildt, and although the change is visible in the "changes" file, it remains the same. The nro has the same size to the bit, so maybe it doesn't get updated properly. Is it possible to check that option? :)

**Comment by endrift** [comment]
Looks like I somehow lost track of the source changes. I'll double check when I get home, but it was a relatively simple fix so I can redo it if I need to.

**Comment by Instandhaltung** [comment]
> Looks like I somehow lost track of the source changes. I'll double check when I get home, but it was a relatively simple fix so I can redo it if I need to.

Thanks for your hard work!

**Comment by Instandhaltung** [comment]
Thanks! It worked! :)
