### ISSUE TITLE
Pokemon Emerald Speedchoice Crashes

### ISSUE THREAD

**Issue by OreoCupcakes** [mgba-emu/mgba#1538]
The Pokemon Emerald Speedchoice ROM, [compiled from this Github repo](https://github.com/ProjectRevoTPP/pokeemerald-speedchoice), crashes at boot up. mGBA just doesn't load the ROM at all as it stays stuck on a white screen.

**Comment by endrift** [comment]
Try setting an override for the flash size. Emerald (and hacks) tend to be unhappy without an override.

**Comment by OreoCupcakes** [comment]
Alright, I did that. I set a Game Override of Save Type Flash 1Mb and Real Time Clock and the game loads with no problems now. Thanks.
