### ISSUE TITLE
Autofire B button makes me turn right.

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#1539]
mGBA-build-2019-09-30-win32-5936-6bbf5755c63f49d974b31951c5609b42c7ae0492

it's been doing this for a long time and not sure when it started it may have done this the whole time.  Here is the config/qt files maybe that will help.

[General]
audioDriver=1
displayDriver=1
cameraDriver=0
windowPos=@Point(449 160)

[mru]
0=E:/Roms/Game Boy ROMS/Castlevania - The Adventure (USA).zip
1=E:/Roms/Game Boy ROMS/Metroid II - Return of Samus (World).zip
2=E:/Roms/Game Boy ROMS/Metal Masters (USA).zip
3="E:/Roms/Game Boy ROMS/Castlevania II - Belmont's Revenge (USA, Europe).zip"
4="E:/Roms/Game Boy Color ROMS/Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev B) (SGB Enhanced).zip"
5="E:/Roms/Game Boy ROMS/Double Dragon II (USA, Europe).zip"
6="E:/Roms/Game Boy ROMS/Double Dragon 3 - The Arcade Game (USA, Europe).zip"
7="E:/Roms/Game Boy Advance ROMS/Ace Combat Advance (USA, Europe).zip"
8=E:/Roms/Game Boy Advance ROMS/Star Wars - Episode II - Attack of the Clones (USA).zip
9=E:/Roms/Game Boy ROMS/Super Mario Land (World) (Rev A).zip

[shader.default.0]
gamma=1
scale%5B0%5D=1
scale%5B1%5D=1
scale%5B2%5D=1
bias%5B0%5D=0
bias%5B1%5D=0
bias%5B2%5D=0
desaturation%5B0%5D=0
desaturation%5B1%5D=0
desaturation%5B2%5D=0

[shortcutAxis]
autofireA=@String(\0-1)
autofireB=@String(\0-1)
holdRewind=+2
holdFastForward=+5
cheatsWindow=@String(\0-1)

[shortcutProfileAxis.XInput%20Controller%20%231]
autofireA=@String(\0-1)
autofireB=@String(\0-1)
holdRewind=+2
holdFastForward=+5
cheatsWindow=@String(\0-1)

[shortcutButton]
autofireA=3
autofireB=2
holdRewind=-1
holdFastForward=-1
cheatsWindow=-1

[shortcutProfileButton.XInput%20Controller%20%231]
autofireA=3
autofireB=2
holdRewind=-1
holdFastForward=-1
cheatsWindow=-1

[shortcutKey]
holdFastForward=
holdRewind=

[ports.qt]
gbc.bios=
sgb.bios=
preload=0
width=480
useBios=1
audioBuffers=1536
lockAspectRatio=0
volume=256
autoload=1
shader=
gb.pal[4]=16777215
sgb.borders=1
savestatePath=E:/Emulators and Codes/Game Boy Advance/Saves
screenshotPath=C:/Users/Jason/Desktop
libraryStyle=0
autosave=0
logToStdout=0
useDiscordPresence=0
fastForwardRatio=2.5
logLevel=7
sampleRate=44100
mute=0
rewindBufferCapacity=300
allowOpposingDirections=0
suspendScreensaver=1
savegamePath=E:/Emulators and Codes/Game Boy Advance/Saves
patchPath=
showFps=1
cheatAutosave=1
idleOptimization=ignore
pauseOnMinimize=0
lastDirectory=E:/Roms/Game Boy ROMS
gba.bios=
audioSync=1
frameskip=0
fpsTarget=60
fastForwardVolume=256
cheatsPath=E:/Emulators and Codes/Game Boy Advance/Cheat
scaleMultiplier=3
gb.pal[0]=16777215
gb.pal[8]=16777215
skipBios=0
autofireThreshold=5
rewindEnable=0
cheatAutoload=1
loadStateExtdata=9
gb.bios=
useCgbColors=1
videoSync=0
fastForwardMute=0
pauseOnFocusLost=0
showLibrary=0
logToFile=0
interframeBlending=0
fastForwardHeldRatio=2.5
height=505
fullscreen=0
lockIntegerScaling=0
resampleVideo=1
logFile=
gba.audioHle=0
saveStateExtdata=31
videoScale=1
hwaccelVideo=0

[gba.input.SDLB]
keyR=5
keyL=4
axisUpAxis=-1
hat0Right=4
gyroSensitivity=2e+009
keyStart=7
keyLeft=2
keyDown=1
hat0Left=5
axisLeftAxis=-0
keyB=0
keyUp=0
hat0Down=7
axisRightValue=12288
axisRightAxis=+0
axisUpValue=-12288
axisDownAxis=+1
gyroAxisX=0
tiltAxisX=2
axisDownValue=12288
keyA=1
keyRight=3
device0=XInput Controller #1
hat0Up=6
gyroAxisY=1
axisLeftValue=-12288
keySelect=6
tiltAxisY=3

[gba.input.QT_K]
keyR=83
keyL=65
keyStart=16777220
keyLeft=16777234
keyDown=16777237
keyB=90
keyUp=16777235
keyA=88
keyRight=16777236
keySelect=16777219

[gba.input-profile.XInput Controller #1]
keyR=5
keyL=4
axisUpAxis=-1
hat0Right=4
gyroSensitivity=2e+009
keyStart=7
keyLeft=2
keyDown=1
hat0Left=5
axisLeftAxis=-0
keyB=0
keyUp=0
hat0Down=7
axisRightValue=12288
axisRightAxis=+0
axisUpValue=-12288
axisDownAxis=+1
gyroAxisX=0
tiltAxisX=2
axisDownValue=12288
keyA=1
keyRight=3
hat0Up=6
gyroAxisY=1
axisLeftValue=-12288
keySelect=6
tiltAxisY=3

[config qt.zip](https://github.com/mgba-emu/mgba/files/3673559/config.qt.zip)

**Comment by endrift** [comment]
You have autofire B and right mapped to the same key. This isn't a bug.

**Comment by Cibomatto2002** [comment]
I think it is a bug for me I deleted everything in the folder and still got it I did get it working tho all I did was press clear button and deleted the up down left right and remapped them and now is all good 
![old](https://user-images.githubusercontent.com/21169038/65931657-44e3e700-e3d0-11e9-9462-9308b27fce61.jpg)

![new](https://user-images.githubusercontent.com/21169038/65931661-47ded780-e3d0-11e9-8478-eb617130cba0.jpg)

**Comment by Cibomatto2002** [comment]
This is the kind of gamepad I have.

https://www.amazon.com/gp/product/B01GDKXMPA/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1
