### ISSUE TITLE
Noise channel sounds tinny

### ISSUE THREAD

**Issue by nephitejnf** [mgba-emu/mgba#1546]
I started playing pokemon bluestar on 0.7.3 and noticed the noises seemed kinda tinny. It checked with Blue version and still the same thing. Compared that with gambatte and gambatte played the sounds normally. This wasn't a problem in 0.7.2. I'm not sure if you can hear it in the clip.

my audio buffer was set at 1536 at the moment

https://www.twitch.tv/videos/492872226

**Comment by endrift** [comment]
This has already been fixed and will be fine in 0.8, once that's released.
