### ISSUE TITLE
When saving GameShark Cheats, cheat codes don't load

### ISSUE THREAD

**Issue by Affishal** [mgba-emu/mgba#1549]
So when I save a .clt file, and I load it back the next time, I don't see the codes it's just the name that I gave it.

**Comment by endrift** [comment]
Can you attach the cheat file?

**Comment by Affishal** [comment]
[Pokemon Red.zip](https://github.com/mgba-emu/mgba/files/3748484/Pokemon.Red.zip)

**Comment by Affishal** [comment]
the cheat file is compressed and it should be there

**Comment by endrift** [comment]
This is a VBA format cheat file. They aren't supported in mGBA.
