### ISSUE TITLE
Sonic Advance 2 - crash

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#155]
During the Final Zone it seems to always crash at the last boss fight.
The save state to skip to the actual boss:
![sonic advance 2 ss1](https://cloud.githubusercontent.com/assets/6880539/11018348/dd7628d0-859b-11e5-9a6f-af98287cf4ab.png)
Either staying in a corner for a while or playing will crash it here.
Tested the Wii nightly Nov 7

I wasn't sure if I should just open another issue if I can include it here. The first Sonic Advance has random sprites glitching out at times, the conveyor belt in the save state below for example is constantly flashing from normal to corrupt. Other sprites like springs are sometimes distorted until used.
![sonic advance ss1](https://cloud.githubusercontent.com/assets/6880539/11018385/945c4556-859d-11e5-9aff-a93cf674072b.png)
I also saw something similar in other games, in Ace Attorney the L and R button sprites during cross-examinations are glitched.

None of these issues were encountered in a build from Oct 25

**Comment by endrift** [comment]
The graphical glitches should be fixed in the next nightly. Let me know if the crash is, too.

**Comment by SuperrSonic** [comment]
Yes, everything's working now.
