### ISSUE TITLE
GBA Audio: PSG sound channels lower quality than on actual hardware

### ISSUE THREAD

**Issue by bleakassassin** [mgba-emu/mgba#1552]
mGBA plays back GB sound channels in GBA games at a lower quality than real hardware. It's been this way with the emulator ever since I can remember. Many basic sound effects in the Pokémon games, for example, use 8-bit sounds, and it's easy to tell that they don't sound as crisp as they should. My best guess would be that these PSG channels are set to play back at a lower sampling rate than they should be.

I've tested with the beta build and the XQ GBA audio option enabled, but it doesn't seem to do anything with these channels. I assume it only touches sample-based channels?

**Comment by Nashismo** [comment]
This emulator has ALWAYS had bad sound. I use this emulator on the Wii and the only version that I have found to have sound somewhat bearable is version 20190730. It is a shame because this emulator is very fast and good otherwise!

**Comment by Yave-Yu** [comment]
I hope mGBA will fix PSG sound issues in future (most better on next release), thus any GBA-audio plugin based on mGBA such as foo_input_gsf, Droidsound-E will fix too!

**Comment by Yave-Yu** [comment]
Now latest mGBA version is 0.9 (beta), but PSG sound still have same issue. Fine example on any GBA Pokemon games' cursor SFX, it's unlike VC GBA and VBA-M, it sounds broken, is first GBA model's PSG sound like this? I don't know, but it makes me unpleasure.
mGBA plays GB/GBC games' sound is more like **Fast** setting in Gambatte or BGB's resampler instead of **High quality (Polyphase FIR)**, so some music will cause a little mess, fine example on _Super Mario Land_'s 2-3 or 4-3's BGM.
I'm really hope mGBA's develops solve the PSG sound problems.

**Comment by bleakassassin** [comment]
@endrift It seems the issue remains the same in v0.9.0. PSG audio still plays back at a lower quality, with noticeably more crackling and distortion than there is on real hardware. I decided to look into this a bit myself with actual hardware. I used a hacked 3DS with a GBA Virtual Console title to do this in order to run the title in AGB mode. I don't think there's any difference between this mode and an actual GBA in terms of audio playback, but someone can correct me if need be.

Disclaimer: I'm a ROM hacker. My ROM hack utilizes PSG audio as the sole form of playback for an alternate soundtrack to the hack.

I attached two FLAC files showcasing the disparity in audio quality between these two ways of playing my hack. The audio goes from the company logo sound to the intro music, then title screen, and then the music for one of the levels in the game. I edited out some silent moments between the last two for a little extra brevity. Unfortunately it has to be a bit apples-to-oranges, since I can obviously only capture an analog recording of the audio from real hardware. You can hear me messing with the 3.5mm cable at some points. Sorry about that. The volume is a bit lower than mGBA as a result, too, but increasing it won't showcase as much of clipping and distortion present in the mGBA version.

I also uploaded an image of the waveform of part of the mGBA audio. Amplitude stays above 0.0 at all times except for when the FIFO channels are used (a couple of samples are played back throughout the duration of the audio, not part of the music itself). 

![waveform](https://user-images.githubusercontent.com/10283728/112921578-a291e600-90d0-11eb-8299-925331b155f9.png)


[Analog recording from AGB-compatible hardware](https://drive.google.com/file/d/1xb8Me9NkMeswp7w9MKMaevYZ1VdnSQk6/view?usp=sharing) 
[Lossless recording from mGBA](https://drive.google.com/file/d/1ex2j6LESKH9UiRas8kclivh_GLrXUIBe/view?usp=sharing)

P.S.: Would it be possible to add an option for increasing the playback rate of the PSG channels? Is that part of the plans for XQ GBA audio?

**Comment by My1** [comment]
oh wow in this sample it kinda hurts how bad mGBA is in comparison tbh

**Comment by Gamulation** [comment]
It's defenetly a problem. I hate this myself, I can't see my screen when gaming, so auido is all I go by, I am blind. I wanted to play my childhood, Pokémon firered, but listening to that sound, hell no. IDK how good the video quality in this emulator looks, it sounds shitty.

**Comment by endrift** [comment]
![image](https://user-images.githubusercontent.com/605502/114460053-23071b00-9b96-11eb-9af4-d4b7c727d764.png)
Spectrogram definitely shows something off (notice the conspicuous subharmonics at 1/2f of each tone). Not entirely sure the root cause. Wonder if it has to do with the DC offset?

**Comment by profi200** [comment]
Keep in mind the 3DS outputs unfiltered GBA audio so it's not a 100% fair comparison (at least against a real GBA). If mGBA doesn't do any special filtering the comparison should be fine though.

**Comment by endrift** [comment]
As best as I can tell what's going on here is that the game is configuring the GBA to output at 64kiHz/8-bit (2x the normal frequency but 1 bit less depth) which mGBA does not yet support for performance reasons. I have to either figure out how to implement it quickly (possible, but tricky), deal with the performance loss (which is significant on slower platforms like the 3DS), or figure out some half-way solution like relegating it to an option.

**Comment by My1** [comment]
> Keep in mind the 3DS outputs unfiltered GBA audio so it's not a 100% fair comparison (at least against a real GBA).

so a real GBA filters stuff?



> As best as I can tell what's going on here is that the game is configuring the GBA to output at 64kiHz/8-bit (2x the normal frequency but 1 bit less depth) which mGBA does not yet support for performance reasons

then the interesting question on how VBA etc. do it?

**Comment by endrift** [comment]
A real GBA does filter stuff yes.

The way VBA does it is that PSG audio is effectively sampled at 16 MiHz, using blip_buf. This is analogous to continuous sampling here, I suppose. While this is sort of how it works on a GB (but at 4 MiHz instead) it's not how it works on a GBA, so it's not how mGBA emulates it. Real GBAs have a selectable sample rate of 32 kiHz, 64 kiHz, 128 kiHz or 256 kiHz. The downside to increasing the sample _rate_ is that it decreases the sample _depth_, so individual samples become lower quality.

**Comment by My1** [comment]
> The downside to increasing the sample _rate_ is that it decreases the sample _depth_, so individual samples become lower quality

reminds me a bit of the pikachu voice in pokemon yellow which upped the sample rate a bunch but chose to go with 1 bit depth, however the sound in total would be worse if you ax the rate of such an audio that runs with that option. (for whatever reason it does run at such an option)



> While this is sort of how it works on a GB (but at 4 MiHz instead) it's not how it works on a GBA, so it's not how mGBA emulates it

so basically they chose an approach that might be cheating while you try to be more faithful to the original. but running 16 MiHz sounds like even more taxing than going up to the 64.

**Comment by endrift** [comment]
The way they do it only requires updating the audio sampling stuff (blip_buf) when the PSG samples _change_, which happens way less often, instead of sampling on an interval like the actual GBA does.

**Comment by endrift** [comment]
Excluding the inverted channel issue, this should be as of 3c0d9f719718a3f547cbac5d181ec46b9365dbb9 (possibly earlier)
