### ISSUE TITLE
Vita Analog Input

### ISSUE THREAD

**Issue by AlC4pwn** [mgba-emu/mgba#1554]
Is there anyway to add Analog Input for the Vita? I could have sworn it used to work but if that's not true, could the feature please be added?

**Comment by kode54** [comment]
What would it map to, other than digital controls with a healthy dead zone? The GBA has no analog inputs, other than that one game with a light sensor.

**Comment by kode54** [comment]
Sorry for criticizing this, I didn't realize mapping them was outright broken. My bad.

**Comment by AlC4pwn** [comment]
Thank you for the fix
