### ISSUE TITLE
mGBA multiplayer window not working

### ISSUE THREAD

**Issue by worldofworlds** [mgba-emu/mgba#1555]
I am running the latest version of mGBA on my mac.
When I try trading pokemon with a multiplayer window, everything works until after the trade. After the trade, it says "Communication error... Please check all connections, then turn the power OFF and ON." Thanks for the help.

**Comment by endrift** [comment]
Does latest mean 0.7.3 or 0.8 beta 1?

**Comment by worldofworlds** [comment]
0.7.3. Should I try 0.8 beta 1?

**Comment by endrift** [comment]
Yes please, there are some fixes to multiplayer in it.

**Comment by worldofworlds** [comment]
It worked! Thank you so much, finally have an Alakazam in Fire Red!
