### ISSUE TITLE
I thought there was a way to choose a default ROM for startup

### ISSUE THREAD

**Issue by TheN64man** [mgba-emu/mgba#1559]
I could be thinking of a completely different emulator entirely, but it'd be pretty swell to be able to select a default game on emulator startup in Wii builds, so I could create forwarders to them. I thought there was a way, but I might have been using some unofficial build or something else that I don't have anymore. Does this really count as an issue? I don't know, depends on how you look at it.

(To clarify, I'm not talking about any BIOS. A default game to run when the emulator is started.)

**Comment by endrift** [comment]
You can do it by passing arguments when starting the process, but that's a little different. I don't know how forwarders work behind the scenes, but it may be possible to make.

**Comment by TheN64man** [comment]
ah, I was just looking into that a while ago. I think I can add arguments to meta.xml or running them through something else, like WiiFlow (but formatted differently than below) but I don't know what to write that works. I figured `-rom` would work, because the word "ROM" was in it.
`<arg>-rom</arg>`
`<arg>sd:/roms/game.gbc</arg>`
Would this work for any reason, or should it be more specific?

**Comment by endrift** [comment]
There's only one arg passed, so you should do it without the `-rom` argument.
