### ISSUE TITLE
Alien Hominid : cheats codes that activate by default

### ISSUE THREAD

**Issue by Dk64** [mgba-emu/mgba#1561]
Hello,

Thank you very much for your work.

When I play Alien Homicid on Mgba, there are cheats codes that activate by default from the beginning of the game. Can not disable them. It's really very weird. Thinking it came from the rom, I tried others, but the cheats remain activated.

I use Mgba 0.7.3. on windows 7. 

An idea ?

**Comment by endrift** [comment]
What do you mean by cheat code? I don't see anything out of the ordinary on my end.

**Comment by kode54** [comment]
Maybe user is running trainer’d rom dumps instead of unmangled ones.

**Comment by endrift** [comment]
It's also possible that they entered codes in at one point which are being autoloaded by default when running again later

**Comment by endrift** [comment]
Please provide the info I asked for or else I can't do anything.

**Comment by endrift** [comment]
Closing due to lack of reply.
