### ISSUE TITLE
Segfault in "View sprites/tiles/map" 

### ISSUE THREAD

**Issue by Cleverking2003** [mgba-emu/mgba#1567]
I'm often getting segfaults when I press "View sprites/tiles/map". I'm on Lubuntu 18.10

**Comment by endrift** [comment]
What version of mGBA are you using?

**Comment by endrift** [comment]
Is this in GB or GBA games? I'm having trouble reproducing. And did you build it yourself or are you using prebuilt?

**Comment by endrift** [comment]
Can you build with `cmake . -DCMAKE_BUILD_TYPE=Debug` and then run it in gdb to get me a backtrace?

**Comment by Cleverking2003** [comment]
[crash.txt](https://github.com/mgba-emu/mgba/files/3843124/crash.txt)

**Comment by endrift** [comment]
That's...a weird place to crash. Are you on a 32 bit OS? Can you try this diff to see if it fixes it?

```diff
diff --git a/src/core/map-cache.c b/src/core/map-cache.c
index 495978672..166eba633 100644
--- a/src/core/map-cache.c
+++ b/src/core/map-cache.c
@@ -16,10 +16,14 @@ void mMapCacheInit(struct mMapCache* cache) {
 
 static void _freeCache(struct mMapCache* cache) {
 	size_t tiles = (1 << mMapCacheSystemInfoGetTilesWide(cache->sysConfig)) * (1 << mMapCacheSystemInfoGetTilesHigh(cache->sysConfig));
-	mappedMemoryFree(cache->cache, 8 * 8 * sizeof(color_t) * tiles);
-	mappedMemoryFree(cache->status, tiles * sizeof(*cache->status));
-	cache->cache = NULL;
-	cache->status = NULL;
+	if (cache->cache) {
+		mappedMemoryFree(cache->cache, 8 * 8 * sizeof(color_t) * tiles);
+		cache->cache = NULL;
+	}
+	if (cache->status) {
+		mappedMemoryFree(cache->status, tiles * sizeof(*cache->status));
+		cache->status = NULL;
+	}
 }
 
 static void _redoCacheSize(struct mMapCache* cache) {
```

**Comment by Cleverking2003** [comment]
Yes, I'm using a 32-bit OS. The diff gets me a different segfault
[crash.txt](https://github.com/mgba-emu/mgba/files/3846471/crash.txt)

**Comment by endrift** [comment]
Let me know if the latest batch of changes fixes this.

**Comment by Cleverking2003** [comment]
Now it's fixed. Thank you
