### ISSUE TITLE
Stuck while playing GBA games

### ISSUE THREAD

**Issue by sumfun4WF** [mgba-emu/mgba#1570]
I am trying to play a pokemon fan game (sadly, it is in Chinese), but the game will stuck at the very early stage of the game, music plays VERY VERY slowly, and graphic gets stuck completely, how can I provide useful logs for debugging?

**Comment by endrift** [comment]
Can you provide a link to the ROM hack and information about which version (e.g. 0.7.3 or 0.8 beta 1, and Windows or some other platform) you're running?

**Comment by endrift** [comment]
Closing due to lack of reply.
