### ISSUE TITLE
GBA: Bounded fast-forward distorts sound

### ISSUE THREAD

**Issue by MadaraUchiha** [mgba-emu/mgba#1571]
When setting the Fast Forward Speed under Settings > Emulation to anything except for checking the Unbounded box, the sound gets distorted to a very high pitch whenever fast forward is invoked.

mGBA version 0.7.3 (downloaded from the website)
OS: Windows 10 version 1903
CPU: i7-6700HQ
Graphics: nVidia GTX 1060

**Comment by endrift** [comment]
This is caused by how bounded fast-forward is implemented, and would require a completely different implementation to fix. I have no plans at this time to change how it's implemented. You can meanwhile disable audio while fast-forwarding, though it is suboptimal.
