### ISSUE TITLE
Opening files - Diacritics in filename don't work

### ISSUE THREAD

**Issue by MegaSigma22** [mgba-emu/mgba#1573]
I've just noticed that diacritics like accent marks(in the case of "pokémon" for me) impede ROMs from loading. I know it's a fairly minor issue but it bothers me a little. Hope you can fix this soon.

**Comment by endrift** [comment]
Which operating system?

**Comment by endrift** [comment]
Closing due to lack of reply. (This was fixed recently on Windows with zip files, if that's what you were hitting.)
