### ISSUE TITLE
[Linux] Qt menu weird behavior

### ISSUE THREAD

**Issue by sergiobenrocha2** [mgba-emu/mgba#158]
I don't remember if I reported this, maybe on IRC, but there's some weird behavior in the Qt menu.

Click on File for example, the menu will drop down, click again to have it vanish, then click in any other menu, the menu will not respond, click again and you will get the menu work.

Ubuntu 14.04, Qt 5.2.1.

**Comment by CanadianJeff** [comment]
I have the same issue (+1)

**Comment by endrift** [comment]
Is this still an issue?

**Comment by sergiobenrocha2** [comment]
Yup.

**Comment by sergiobenrocha2** [comment]
I'm testing 0.4.0 release on debian sid, Qt 5.5.1, there's no issue. Is it due Qt version maybe?

**Comment by spaceporn** [comment]
I don't have this issue on Arch on mGBA 0.4.1, Qt 5.7.0. On another note, is there a way to hide the menu so it only shows when Alt is pressed or something? I'm googling it but haven't found anything yet, since most applications have this option on a view menu.

**Comment by endrift** [comment]
This was probably a Qt bug.
