### ISSUE TITLE
[Feature Request] MSU-1 file support

### ISSUE THREAD

**Issue by bajolzas** [mgba-emu/mgba#1581]
Id like to know if there is any chance for mGBA to support MSU-1 files for CD quality audio, like it happens in some SNES emulators.

It would also be nice if files made for snes games that have a gba port could be used for it, if such patch is made.

**Comment by endrift** [comment]
MSU-1 is SNES-specific. If there were a GBA equivalent I'd be ok supporting it but there isn't one at this time.

**Comment by bajolzas** [comment]
I based my request on this forum's 3rd post, where byuu says that MSU-1 could be done for any system:
http://helmet.kafuka.org/byuubackup/viewtopic.php@f=26&t=4788.html

Now, you my not know how to implement it, but I guess it could be something to have in mind for the future.

**Comment by endrift** [comment]
I'm pretty sure byuu meant analogues to MSU-1, not MSU-1 itself. But now I've gotten to thinking about what would need to be done to add an MSU-1-like for GBA.

**Comment by bajolzas** [comment]
Well, nice to hear :)

**Comment by avegee24** [comment]
> I'm pretty sure byuu meant analogues to MSU-1, not MSU-1 itself. But now I've gotten to thinking about what would need to be done to add an MSU-1-like for GBA.

well if we got sappy panning and said sound driver is really documented one could assemble (as in ASM) an msu-like hack
