### ISSUE TITLE
pokemon emerald rom doesn't seem to load

### ISSUE THREAD

**Issue by halouthere233** [mgba-emu/mgba#1586]
whenever i try to load the rom it doesn't want to and this keeps popping up in the logs:

[GAME ERROR] GBA I/O:	Read from write-only I/O register: 0C4
[GAME ERROR] GBA I/O:	Read from write-only I/O register: 0D0

emulating on windows 10 home, mGBA version 0.7.3
anything else, just ask me

**Comment by endrift** [comment]
What do you mean by "doesn't want to load"? Just a white screen? You might have a hacked ROM that mGBA doesn't recognize as Emerald, which can cause this issue. (Emerald needs to have the 1 Mbit Flash override set or it won't work, and mGBA detects Emerald and sets it automatically.)

**Comment by halouthere233** [comment]
sorry, yeah, just a white screen.
okay, with the override it's working now, thanks a lot.
