### ISSUE TITLE
Autodetect model doesn't use SGB mode for SGB enhanced GBC games (and Pokemon Yellow)

### ISSUE THREAD

**Issue by jklphe00** [mgba-emu/mgba#1587]
The following was experienced in mGBA v0.7.3 and 0.8 beta 1.

It seems that Game Boy Color games with Super Game Boy enhancements do not run in Super Game Boy mode automatically with Autodetect on in the settings. 
![mGBA 0 7 3 - Autodetect](https://user-images.githubusercontent.com/8462513/69896420-288ef880-12f4-11ea-8c38-1820d60d58f6.png)
Rather, they remain in GBC mode. The way I checked was anytime after loading a ROM, I went to Game overrides to see what Game Boy model Autodetect had chosen for that particular game.

This also happens with the special case of Pokemon Yellow, which is a regular Game Boy game but with GBC AND SGB enhancements. Pokemon Yellow is run in GBC mode instead of SGB mode with Autodetect.

GB games with SGB enhancements run in SGB mode using Autodetect, so everything is fine for that category of games.

I did also try changing the model from Autodetect to Super Game Boy and it loads all games in Super Game Boy mode fine.

The issue is with the current behavior of Autodetect. I would think that if SGB enhancements exist for any game, then it would run in SGB mode over GBC mode. Otherwise if the current behavior is intended, we would have to manually change the Game Boy model in the settings if we desire SGB enhancements every time we load a GBC game that supports the feature.

**Comment by endrift** [comment]
SGB mode is just GB with some minor enhancements, GBC is a lot more. This is the intended behavior (though a better UI for it like BGB has might be nice).

**Comment by jklphe00** [comment]
Thanks for the clarification that it is intended.

I guess it would be nice to have an option if the Autodetect can prefer SGB mode for those of us that like having the SGB borders or maybe even keep the games in GBC mode but force a display of the SGB borders around it. Do you think this can be considered?

**Comment by ISSOtm** [comment]
BGB has "autodetect, prefer X" settings.
