### ISSUE TITLE
Bounded fast forward is broken

### ISSUE THREAD

**Issue by mathturtle** [mgba-emu/mgba#1590]
The fast-forward/turbo button works fine when in unbounded mode, but when set to 5x or some other bounded amount the sound fast forwards and the graphics do not.  Found when testing the 0.8 beta 1 preview.  I was testing out GB/GBC games, but I just checked with a GBA game and it behaved the same.  (Pokemon Yellow/Silver and Fire Emblem Sacred Stones if you need this info).  I'm on Windows 10.

**Comment by endrift** [comment]
Which display driver are you using? (E.g. OpenGL)

**Comment by mathturtle** [comment]
OpenGL

**Comment by endrift** [comment]
I forgot to ask, do you have sync to video enabled?

**Comment by mathturtle** [comment]
![image](https://user-images.githubusercontent.com/553788/73185105-7dc86a00-40eb-11ea-80e9-61c19e68b2b3.png)

No. I had sync to audio enabled because it (at least used to) help with gb/gbc link cable connections according to comments on another issue.  Turning on sync to video doesn't help with this issue and turning off both makes the game run in unbounded speed up mode all the time.

**Comment by endrift** [comment]
I can reproduce this on Windows but not on Linux.

**Comment by endrift** [comment]
Regressed in 3920c6191f2caa155b1e5ef67f4b5ce26e8a7093.

**Comment by DandeMC** [comment]
Is the problem fixed or still open?

**Comment by endrift** [comment]
It's fixed but the fix hasn't made it to a released version yet.

**Comment by DandeMC** [comment]
Can I fix the problem myself? When does the release come in which the problem is fixed?

**Comment by endrift** [comment]
You can download a development build from the website which has the fix present: https://mgba.io/downloads.html#development-downloads

**Comment by domesticated** [comment]
Problem still persists for Mac OSX in the latest development build.
