### ISSUE TITLE
Loud scratchy noise on a certain save

### ISSUE THREAD

**Issue by sapphireish** [mgba-emu/mgba#1598]
I have a certain save on Pokemon Emerald where a loud scratchy noise started up mid-way through the game. I have other saves on the same game and none of them have the same scratchy audio as this particular one. The sound goes away whenever I turn off FIFO channel A and FIFO channel B, though the game music becomes a bit warped.

If needed, here are my audio settings:
![image](https://user-images.githubusercontent.com/58956982/70943661-5e83ea80-201f-11ea-9dae-3a3e54b215e8.png)

And a short clip of what it sounds like:
https://www.youtube.com/watch?v=qTNVblkwLkE

I use Window 10 if that helps at all?

Edit: I've found a fix for the issue, but thank you anyhow!

**Comment by endrift** [comment]
That video seems to be inaudible for me. Can you upload the save? You may need to zip it first for GitHub to allow it.

**Comment by sapphireish** [comment]
[save3 pokemon emerald.zip](https://github.com/mgba-emu/mgba/files/3980699/save3.pokemon.emerald.zip)
Is that okay?

**Comment by endrift** [comment]
Haven't taken a look at the save yet, but this does look like what I wanted. Thanks.

**Comment by sapphireish** [comment]
Sweet - thank you in advance!

**Comment by xnaas** [comment]
@sapphireish was this resolved for you somehow?
