### ISSUE TITLE
Input does not work on Ubuntu 15.04

### ISSUE THREAD

**Issue by guineawheek** [mgba-emu/mgba#16]
Booted up regularly, but did not respond to keyboard input.

**Comment by endrift** [comment]
Are you building yourself? What revision are you using?

**Comment by endrift** [comment]
I can't reproduce this. Are you using the Qt version or the SDL version? I need *way* more info than you gave.

**Comment by guineawheek** [comment]
Sorry for the late response.
Yes, it was built with the SDL library.
```git rev-parse head``` gives me 924efefc3839a3745bf9e4e6da419bacdda9b4ef as the revision.

**Comment by endrift** [comment]
Hmm, the latest builds seem to work fine for me. Can you try installing the nightlies that I've recently posted? https://s3.amazonaws.com/mgba/mGBA-nightly-2015-05-10-ubuntu64-vivid-73d2c8fda8b7d324ab2b338b17bd10d36651f0f4.tar.xz

**Comment by guineawheek** [comment]
Fixed in latest branch, thanks!
Tried to build the latest commit from source before trying the deb packages, but it complained that pixman.h was missing despite libpixman-1-dev being installed....
