### ISSUE TITLE
Crash when trying to open "View sprites..." following user-modified memory

### ISSUE THREAD

**Issue by RetroEdit** [mgba-emu/mgba#1600]
I was looking through the memory of the game Game & Watch Gallery 4, and I was experimentally modifying the memory to better understand how the game works. While playing the game "Fire - Modern Mode", I changed the address `0x0203c3ce` to 0, and many of the sprites became a rainbow mish-mash of corrupted-looking sprite. I then opened up `Tools > View sprites...`.

At this point, the behavior changes depending on the version of mGBA. On 0.7.3, the immediate cause of the crash was trying to scroll up too many address numbers, which caused the emulator to pause for a moment and then terminate execution. When I tried it on 0.8 beta 1, mGBA did not successfully open the sprite viewer and crashed soon after attempting to open it.

I know modifying the memory in an arbitrary manner like this is not something that is likely to happen during normal execution of a game, but perhaps the game itself or other games could cause the sprites to end up in similar states, and it seems inideal (and potentially a security vulnerability) for the emulator to crash as a result.

Additionally, another interesting feature of G&WG4 is that the current minigame state is automatically saved when the game is paused. To make it more straightforward to reproduce, this save file can be loaded: [G&WG4 mGBA sprite crash 1600.zip](https://github.com/mgba-emu/mgba/files/3980843/G.WG4.mGBA.sprite.crash.1600.zip)

**Comment by endrift** [comment]
Seems to be a division by zero error, looking into it now.

**Comment by endrift** [comment]
This was two separate bugs, fixed in 1002dfd0dbd86950145493c82ff1af7744e60c81 and 2cb5a08f4f02468e351cab80a92f5803ec3356cf.
