### ISSUE TITLE
"Some changes will not take effect until the emulator is restarted."

### ISSUE THREAD

**Issue by RetroEdit** [mgba-emu/mgba#1601]
This is somewhat minor, but an annoying thing that's been happening recently: the first time I use "set all" controls after downloading the emulator, the dialog box pops up with "Restart needed: Some changes will not take effect until the emulator is restarted." This only happens the first time I do this after download; subsequent changes to controller inputs will not trigger this message. The annoying part is that it isn't even true in the case of controller setup, as the controller will work immediately following setup.

(I doubt I'm imagining this, but didn't the controller settings used to be saved globally so that new installs would preserve previous controller settings?)

**Comment by endrift** [comment]
The zip files now include a `portable.ini` file which causes settings to only be saved locally; delete that file if you want to go back to global settings.

I'll see if I can track down this issue this weekend.
