### ISSUE TITLE
[0.8] Emulator display sometimes reverts to bilinear filtering

### ISSUE THREAD

**Issue by RetroEdit** [mgba-emu/mgba#1602]
*Edits can be seen in history. I've revised my understanding of the issue, and have removed my original mistaken understanding so it's easier to read.*

This sometimes occurs when going out of focus or back into focus. Sometimes it just flickers into bilinear filtering and doesn't completely revert; other times it will completely convert and not be corrected until refocusing.

This appears in both [build 5988-2cb5a08](https://github.com/mgba-emu/mgba/commit/2cb5a08f4f02468e351cab80a92f5803ec3356cf) (the latest build as of this writing), and 0.8 beta 1. This does not appear to occur in 0.7.3. A bisect may be a good idea.

**Comment by endrift** [comment]
This issue is I believe because it swaps out a static background image when you pause the game, but I'm not sure why it's being scaled improperly.
