### ISSUE TITLE
Sprite viewer: magnified tile displayed from BG tiles instead of OBJ tiles

### ISSUE THREAD

**Issue by rtandy** [mgba-emu/mgba#1603]
0.8-beta1, Qt, on Debian 10.2 (buster).

In the sprite viewer, the magnified tile shown when I click on the sprite preview is taken from BG tiles instead of OBJ tiles.

Before taking the screenshots below, I clicked on the top-left part of the 2x2 sprite. The tile id (4) and palette id (0) are correct, however the tile and address displayed are for BG tile 4 (0x06000080) when it should be OBJ tile 4 (0x06010080).

![image](https://user-images.githubusercontent.com/795000/71302113-6c59a880-235c-11ea-90bf-89ba8378aba5.png)
![image](https://user-images.githubusercontent.com/795000/71302116-6ebc0280-235c-11ea-9bcc-a459be5628a0.png)
![image](https://user-images.githubusercontent.com/795000/71302277-5816ab00-235e-11ea-8622-32fd602820c5.png)

**Comment by endrift** [comment]
Fixed by 158e2ef, which I accidentally typo'd the bug number in.
