### ISSUE TITLE
PS vita Mgba doesn't work with the control sticks (L2)

### ISSUE THREAD

**Issue by Fenjor** [mgba-emu/mgba#1604]
It is what is says in the title, the controll sticks don't work.... Also after reproggaming the controlls to L2.

**Comment by Fenjor** [comment]
Its just the new version i tried the 0.61 version and it works

**Comment by endrift** [comment]
The control sticks are broken in 0.8 beta 1. The development builds have fixes for that: https://s3.amazonaws.com/mgba/mGBA-build-latest-vita.7z

I don't know what you're talking about with reference to L2 though.

**Comment by endrift** [comment]
Closing due to lack of reply.
