### ISSUE TITLE
Is one Game Pak multiplayer possible?

### ISSUE THREAD

**Issue by RetroEdit** [mgba-emu/mgba#1608]
In *Game & Watch Gallery 4*, a game I'm playing there's multiplayer support for it. However, the instruction manual specifies only one cartridge should be used in the primary GBA:

> **Linking Instructions**
> 1. Make sure the POWER Switches on all of the game systems are turned OFF, then insert the Game Pak into Player 1's Game Pak slot.
> 2. Insert the Game Link cable into the External Extension Connectors (EXT), making sure to insert the small, purple connector into Player 1's game system and the large, grey connector into the other game system.
> 3. Turn each system's POWER switch to ON.

However, I'm not sure if mGBA currently supports this. I've gotten multiple-cartridge multiplayer working before, but since the interface doesn't allow one instance of the emulator to be active without having a cartridge to be receiving GBA-link information. Is this an interface issue, or an implementation issue?

**Comment by endrift** [comment]
It is currently broken, see #425.

**Comment by RetroEdit** [comment]
Whoops sorry. I did check previous issues, but I only searched for "multiplayer". I guess I should have searched for "link".
