### ISSUE TITLE
[Qt] Glitchy graphics after rewinding

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#161]
After releasing rewind, the background layers become distorted and black areas appear on screen

![one](http://i.imgur.com/LVV1R4V.png)

![two](http://i.imgur.com/cmQACpY.png)

![three](http://i.imgur.com/wVlkEcW.png)

**Comment by tony971** [comment]
Changing locations seems to fix the location (going into a building or battle)

**Comment by endrift** [comment]
Whoa, looks like the mosaic and window registers got screwed up somehow.

**Comment by endrift** [comment]
Fixed in ff4950c50d9289765d9e8852d115a03862c7862e.
