### ISSUE TITLE
Camelot Sports games on GBC (Mario Golf, Mario Tennis, Mobile Golf) stutter when transitioning from one screen to another on Switch

### ISSUE THREAD

**Issue by Instandhaltung** [mgba-emu/mgba#1610]
The games Mario Golf, Mario Tennis, Mobile Golf do all stutter while loading(?). The sound is interrupted for a short period of time while transitioning from menu to gameplay and vice versa, and while moving to different areas in RPG mode.

**Comment by RetroEdit** [comment]
This must be exclusive to switch; I can't reproduce on WIndows, though I haven't gotten deep into the games.

**Comment by Instandhaltung** [comment]
Yeah, other games do have slight stutters while transitioning as well

**Comment by Instandhaltung** [comment]
Has been fixed a while ago.
