### ISSUE TITLE
[Qt] Muting immediately after pausing causes the screen to go black.

### ISSUE THREAD

**Issue by RetroEdit** [mgba-emu/mgba#1612]
This is really just a minor inconvenience, so it needn't be fixed for 0.8, but it's annoying and it shouldn't happen.

**Comment by endrift** [comment]
I can't reproduce. Can you give me some more info about your setup?

**Comment by RetroEdit** [comment]
Windows 8.1, Intel Pentium N3540 processor. Happens straight from extraction with the latest nightly as of this writing, `6008-ccdbcf6`, but also occurs in prior versions going back to at least 0.7.3 (probably before; I can check if you want).

If there's anything else that would be useful, please let me know.

**Comment by RetroEdit** [comment]
Here's a timeline of how this bug appears to have progressed:

- The bug did not appear in 0.6.3
- A similar bug appears in 0.7 beta 1, but instead the screen becomes vertically flipped, and solely when unmuting.
- In 0.7.0, muting toggles between the screen being vertically flipped and not, though occasionally if one is spam-pressing mute while paused, it skips a cycle.
- The current incarnation begins in 0.7.1

So then I tried to trace down when this stuff was introduced in the hourlies. Unfortunately, the hourlies appear to derive from `master`, whereas the releases derive from `0.7`, so they aren't quite comparable; I wasn't able to find the vertical screen flipping version in the hourlies. But I was able to find the black screen version appears to have been introduced in [`5202-7cc09c7`](https://github.com/mgba-emu/mgba/commit/7cc09c713b3219023c0fdc8fa709739cdaacdbff)

**Comment by endrift** [comment]
What GPU?

Also that's weird, muting it shouldn't affect how things are drawn. Are you using the menu to mute it or a hotkey?

**Comment by RetroEdit** [comment]
My GPU is Intel HD Graphics and I'm using the menu to mute it.

Also, just to be clear, the screen does not continue to be black once unpaused again, sorry I didn't mention that early, but that's why I said it wasn't high-priority.

**Comment by endrift** [comment]
Should be fixed now, let me know

**Comment by RetroEdit** [comment]
Worked like a charm!
