### ISSUE TITLE
pokemon Saiph rom hack hangs on 3ds but not on wii port

### ISSUE THREAD

**Issue by TriforceOfPwnage** [mgba-emu/mgba#1615]
Hello sorry ahead of time if i shouldnt be posting this here. Buti recently decided try the rom hack pokemon saiph on mgba's 3ds port. It hangs when you open the pokemon summary screen 100% if the time on a black screen. this happrns on hardware too. But wierdly enough it runs fine on the wii port without this issue according to gbatemp reports. Any thoughts on what can be causing this issue. also Opting.to use bios actually gets farther by actually getting to the summary screen but leaving it results in the hang anyway. 

heres a link to.the patch https://drive.mobisystems.com/sharelink/dGVzcGluZXRAZ21haWwuY29t.3E1oScdnGxS29mA0fAAikj

**Comment by TriforceOfPwnage** [comment]
forgot to mention this hack uses fire red as base

**Comment by endrift** [comment]
Can you verify that the latest Wii version and latest 3DS version differ in behavior? I don't really trust random GBATemp users to test things properly if not stated.

**Comment by TriforceOfPwnage** [comment]
Ill get my friend to test it on his wii. and btw that was not a link to a rom lol. it was just a ups file

**Comment by TriforceOfPwnage** [comment]
alright tested it myself at.a friends house and no it does not run on either wii or 3ds.

**Comment by endrift** [comment]
So does that match behavior on hardware? If so, this bug can be closed.

**Comment by TriforceOfPwnage** [comment]
yes on hardware it hangs as well
