### ISSUE TITLE
Bad sound on latest Wii version of MGBA, pinpointing solution.

### ISSUE THREAD

**Issue by Nashismo** [mgba-emu/mgba#1617]
Hi, first let me thank you, because this is the greatest GBA emualtion there is for the Wii!

It is really amazing and is super fast, but there is this one issue with it. Sound. Sound is really bad and tends to crackle a lot, it is really terrible, and I am aware that the original GBA had lackluster sound to begin with, but not at these levels.

See I am not someone to lie, and I tried for weeks and weeks to get better sound on your emu, and yes, I did! Using version 0.6.0-2017-07-16 (edit)! In that version of your emu for the Wii, crackling sound is fixed and it is the best version in terms of sound.

But the problem of bad sound quality remains! As it is still very very poor. VBA GX has MUCH better sound, but the emulator is very slow and not as accurate as yours!!

So, I hope you believe me, I have very good ears and I tested many many of your Wii versions, and that one was the best 0.6.0-2017-07-16 (edit).

But still the sound itself is VERY low quality, please let me know, I can test whenever you want me to.

Thank you,
Nashismo.

**Comment by endrift** [comment]
Can you give me a commit ID? It should be that long string of numbers and letters in the filename.

**Comment by Nashismo** [comment]
> 
> 
> Can you give me a commit ID? It should be that long string of numbers and letters in the filename.

Ok, I will 100% honest with you. I am using Enhanced MGBA, which features the Gameboy Player interface which is version 07/30/2017, I got the date wrong but now I saw the exact date on the XML file.

I could not find any recent version of your emu that has good sound on Wii. So I looked for a version of MGBa that the developer of EMGB could've used. And I found it, is mGBA version 0.6.0-2017-07-16 (the version that enhanced MGBA was probably using in July 30th 2017).

Commit: f4c4be7b121556f47438dbac940186da4d4199d6

In this version your emu sounds very good and has no skipping, lag or any crackling sound whatsoever. Still sounds low quality, but it sounds much better than any of your recent versions!

Thank you and forgive me, I did  not see your post before,

My best regards and happy new year,
Nashismo.

**Comment by endrift** [comment]
Have you tried the 0.8 beta 1? Things have changed a LOT since then. https://github.com/mgba-emu/mgba/releases/download/0.8-b1/mGBA-0.8-b1-wii.7z

**Comment by Nashismo** [comment]
> 
> 
> Have you tried the 0.8 beta 1? Things have changed a LOT since then. https://github.com/mgba-emu/mgba/releases/download/0.8-b1/mGBA-0.8-b1-wii.7z

Yes. I have tried most versions and the last one (0.8 beta 1) too. Audio seems better in the sense that you hear better lows, but the crackling and stutter/lag is there as usual. Like I said, the ONLY version, at least on Wii, without crackling sound issues is version 0.6.0

At first I thought it was because of using the "enhanced" MGBA but after investigating, I discovered that it was the fact that the author of "enhanced MGBA" was using version 0.6.0 of your emu (as a base), and that is why it had better audio.

Cheers and thank you for yor time endrift,
Nashismo.

**Comment by Nashismo** [comment]
OK!! Now I have tested almost all versions left, that I had not tested before!

And I found exactly when the crackling sound started! It started on MGBA Version 0.7 beta 1 commit: 776d8a7f7126aa6fe215a22c507a00e2aba9911a

Because, the last version of MGBA working well on sound was version 0.6.3, this being tha last and best version with the better sound, no skipping, no crackling.

I hope this helps, I had some free time today so I checked today as best as I could, always making sure to delete the config.ini file before installing each and every version.

**Comment by endrift** [comment]
Can you use the dev builds to try to narrow it down? That gives me a lot more info. https://mgba.io/builds/36/ and later pages should contain the builds you can look through.

**Comment by Nashismo** [comment]
> 
> 
> Can you use the dev builds to try to narrow it down? That gives me a lot more info. https://mgba.io/builds/36/ and later pages should contain the builds you can look through.

Ok, I will look through these and try to find when the problem started. I will be doing that. Cheers.

**Comment by Nashismo** [comment]
It was no easy task!!

But I found it! Last version working correctly, with no skipping audio, no crackling audio was version MGBA revision: 5189-20c99d2 (2018/08/03)

The first revision that started having the sound problems was of course the one that came right after this, revision: 5190-825c70b (2018/08/03)

I am so happy I found it, I hope it can be of use!

Nashismo.

**Comment by endrift** [comment]
Does this build fix or otherwise improve things for you? I can commit it to master if it does. [audio.zip](https://github.com/mgba-emu/mgba/files/4050118/audio.zip)

**Comment by Nashismo** [comment]
> 
> 
> Does this build fix or otherwise improve things for you? I can commit it to master if it does. [audio.zip](https://github.com/mgba-emu/mgba/files/4050118/audio.zip)

I am sorry I was watching history channel, the ancient astrounats or something, time flew. But yes, I have just test it this new dol, and it is terrible, garble sound, worse than ever before, something definetely changed.

Thank you for your time endrift, whatever you need me to do, just let me now.

Nashismo.

**Comment by endrift** [comment]
Ok, try this one. I don't have my Wii connected right now so I've been testing in Dolphin, but if this one is also broken I can hook up my Wii tomorrow.
[audio.zip](https://github.com/mgba-emu/mgba/files/4050270/audio.zip)

**Comment by Nashismo** [comment]
> 
> 
> Ok, try this one. I don't have my Wii connected right now so I've been testing in Dolphin, but if this one is also broken I can hook up my Wii tomorrow.
> [audio.zip](https://github.com/mgba-emu/mgba/files/4050270/audio.zip)

I tested it already. Is hard to explain sound is better than the file you gave me before, but now we go back to the crackling that we had before. The difference is that now is more like a noise, the typical crackling that I saw in all other versions was more like a skipping, similar to when en emulator is missing frames.

In summary, this last version still has audio problems, they are a just different, so still not good, sadly.

Thank you for your time endrift, I will be here tomorrow, I have my Wii always ready to test ;)

Nashismo.

**Comment by endrift** [comment]
I haven't hooked up my Wii yet, but I'm curious: is the TV you're plugging into PAL? I've only really tested this on NTSC platforms.

**Comment by Nashismo** [comment]
> 
> 
> I haven't hooked up my Wii yet, but I'm curious: is the TV you're plugging into PAL? I've only really tested this on NTSC platforms.

My TV is NTSC, Sony trinitron made in 2007, on NTSC Wii plugged in using component.

**Comment by Nashismo** [comment]
The best game I have found to find audio flaws is simple to let Metroid Zero Mission play, then when the demo starts (Samus traversing the stages) you can find many instances of sound crackling. Actually right before that just when a star is falling before the intro, you can hear a crackling in the sound.

This is my primary game to use, because it has many lows and high pitched sounds, and if not emulated perfectly, the audio will be terrible.

**Comment by endrift** [comment]
Thanks, that was helpful! Try this new dol.
[audio.zip](https://github.com/mgba-emu/mgba/files/4056961/audio.zip)

**Comment by Nashismo** [comment]
> 
> 
> Thanks, that was helpful! Try this new dol.
> [audio.zip](https://github.com/mgba-emu/mgba/files/4056961/audio.zip)

YES!! Is fixed, you did it! This is wonderful, it truly is fixed! No more crackling sound, no more weird garble audio!

Yes, the audio could be better, but that's because GBA hardware itself is not that good, the emu is not to blame!

This is really amazing endrift, I am glad, really glad! It would be nice if what you did could help all MGBA versions, hopefully. But Wii is working good now :)

My best regards and thank you for your time and your effort endrift.
Nashismo.

**Comment by Nashismo** [comment]
I am truly happy and glad for everything but taking this chance I will ask you one last thing. Do you now how to make the user interface image more "narrow"? I cannot read anything close to the borders of the screen (left or right), it is probably because I am using a CRT TV. But I could in older versions of MGBA.

Thank you, and well is not that important, but definetely usefull for anyone playing on a standard TV, I cannot see what I change in the config screen and that's a bit of a problem :)

Cheers, but that's for any other time, I have bother you too much now! My best regards!

Nashismo
