### ISSUE TITLE
Graphic glitch in Kingdom Hearts Chain of Memories with OpenGL HD graphics

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#1620]
In a GBA and in GBA's software mode, when a counterattack is executed the screen gets pixelated for an instant.

![1989 - Kingdom Hearts - Chain of Memories (E)(Eternity)-2](https://user-images.githubusercontent.com/16591467/72535494-ea846e80-3878-11ea-90b5-4816a27c412e.png)

But with the OpenGL HD mode, that screen effect gets corrupted.

![1989 - Kingdom Hearts - Chain of Memories (E)(Eternity)-1](https://user-images.githubusercontent.com/16591467/72535556-0a1b9700-3879-11ea-8ccb-89f2ce98aab2.png)

**Comment by endrift** [comment]
Can you upload a save as close as possible to when you can first do one of these, ideally a tutorial? I'm not familiar with how to play this game.

**Comment by RafaelTrepaUnCarballo** [comment]
I can.

[KH Chain of memories Europe.zip](https://github.com/mgba-emu/mgba/files/4087603/KH.Chain.of.memories.Europe.zip)

In the zip there's a **save** from the beginning of the first level (you have to climb the stairs to enter) and a **savestate** performing a cardbreak/counterattack (for mgba 0.8-6016-bd87038c9 and my European ROM).

I know the savestate probably won't work, the instructions to do a cardbreak with the save.

0. Activate OpenGL at any resolution, even x1
1. After loading the save, climb the white stairs and cross the door
2. Touch one of the enemies that appear suddenly to start a battle.
3. Wait for any enemy to activate a card and then press A to use one of yours. The glitch will happen.

(actually a cardbreak is performed you have to use a card with a higher number than the enemy's or a 0 card. The enemy can also do cardbreaks against you, causing the same glitchy transition)
