### ISSUE TITLE
Need mgba-en.ts

### ISSUE THREAD

**Issue by teorex3** [mgba-emu/mgba#1623]
I use english version, but I need to translate some text into my native language for convenience. There are files in other languages, but I would like to translate from English. 
If it’s not difficult for you to add a file with English lines, thanks.

**Comment by endrift** [comment]
@lotharsm can you suggest how to start with something like this?

Also, what language?

**Comment by teorex3** [comment]
now -
`<message>
        <location filename="../LoadSaveState.ui" line="261"/>
        <source>Cancel</source>
        <translation>Abbrechen</translation>
    </message>`

need - 
`<message>
        <location filename="../LoadSaveState.ui" line="261"/>
        <source>Cancel</source>
        <translation>Cancel</translation>
    </message>`
as a result, quickly replace with Russian, where necessary - 
`<message>
        <location filename="../LoadSaveState.ui" line="261"/>
        <source>Cancel</source>
        <translation>Отмена</translation>
    </message>`

**Comment by lotharsm** [comment]
@teorex3 so, basically you need a new translation file for Russian, is that correct?

**Comment by teorex3** [comment]
@lotharsm , yes, need an empty template or english with english lines.
<source>English</source>
<translation>Empty or English</translation>
an empty file is useful for translation into any language, thanks.

**Comment by lotharsm** [comment]
I added a template for the Russian translation file with a6e92b6df779f0eb7fe76109f0b419a2a4bbd960, so you can start translating it now.

For the translation, you need to open the new mgba-ru.ts file with Qt Linguist. After modifying and saving the file, you simply re-compile mGBA with the UPDATE_TRANSLATION flag enabled. Another way is to use Linguist's "lrelease" tool, but I never worked with this tool.

**Comment by lotharsm** [comment]
> an empty file is useful for translation into any language, thanks.
Providing an empty file for "general use" is most likely not possible due to the way Qt handles translation, since we need to include the proper language tags. 

But...
> also did not find information for translators in README.md and on the mgba website.
... I'll see what I can do about this.

**Comment by fitojb** [comment]
Have you considered using an online service like Weblate to handle the addition of new translations?

**Comment by Mte90** [comment]
To update the ts files I got it with `lupdate *.cpp *.ui -ts ./ts/*.ts  -locations absolute -no-obsolete` inside the `/src/platform/qt` folder.

**Comment by teorex3** [comment]
Translated using Weblate (Russian)

Currently translated at 0.0% (0 of 939 strings)

Translation: mGBA/mGBA Qt
Translate-URL: https://hosted.weblate.org/projects/mgba/mgba-qt/ru/

**Comment by endrift** [comment]
I forgot this issue was still open. I've resolved the root issue since.
