### ISSUE TITLE
The record video feature sometimes records GBC games as 256x224 video

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#1626]
1. Open a GB/GBC game (the recorder window shows the right resolution)
2. Open the Record Video window. It shows the right resolution
3. Reopen the same GB/GBC game with Ctrl+0. Now the recorder shows **(256x224)** as **native**.

This bug only happens if you have opened that window at least one time. It doesn't get fixed until you close the emulator.

**Comment by endrift** [comment]
256x224 is SGB resolution, not GBA.
