### ISSUE TITLE
Golden Sun 2 (OpenGL HD) A glitchy line appears in the background of the battles

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#1631]
It appears when the battle starts and with the furthest camera angle. This only happens in the OpenGL render, the software render is fine.

![GOLDEN_SUN_B-1](https://user-images.githubusercontent.com/16591467/72925822-9e8f6900-3d53-11ea-9253-7149024c154b.png)

**Comment by endrift** [comment]
This is a known issue that is unfortunately probably not fixable due to how the game handles the large backgrounds. I'll keep looking into if it's possible, as I know it's very distracting.
