### ISSUE TITLE
Stable release for mGBA 0.8.0 x64-bit?

### ISSUE THREAD

**Issue by devalter1001** [mgba-emu/mgba#1634]
First, thank you on the wonderful release! I notice there is not a stable build of the 64-bit version, 32-bit has one, but the 64-but one is a dev build.

Will there be stable 64 build of mGBA 0.8.0?

**Comment by endrift** [comment]
I respun the build. See if it works now.

**Comment by BartSimpsunn** [comment]
fixed for me, reports 0.8.0, no weird dev numbers now

**Comment by fancythedeveloper** [comment]
You mean Commit ID? whatever it's fixed
