### ISSUE TITLE
Famicom Mini series: corrupted graphics with OpenGL renderer on Windows in certain games

### ISSUE THREAD

**Issue by angrylion7** [mgba-emu/mgba#1635]
I'm on Windows 7 x64, using a GeForce GT630 1 GB VRAM GPU (GK208 chip) and the latest nVidia driver v441.87. Super Mario Bros. 2 and Metroid from Famicom Mini Series show black space instead of lower row(s) of emulated background tiles as shown on the screenshot, and only do this with the OpenGL renderer. Many other entries in the Famicom Mini Series don't suffer from this, and neither does Metroid from the Classic NES series, curiously. This happens as far back as 20ea552. I also tested 921f3f8, and it's the same, only the background in SMB2 is not rendered properly at all. I assumed that's because the OpenGL renderer was not mature enough by the time of 921f3f8, and I don't need to go further back, am I wrong?
![smb2](https://user-images.githubusercontent.com/16341594/72945790-f8148980-3d8d-11ea-8d1e-ce93913c2f4d.png)

**Comment by endrift** [comment]
This appears to be because sprite cycle counting isn't implemented yet.

**Comment by endrift** [comment]
Helps if I actually do this per scanline, which I wasn't.
