### ISSUE TITLE
Compiling mGBA Python bindings on Windows

### ISSUE THREAD

**Issue by KaneTW** [mgba-emu/mgba#1637]
Is there a guide to compiling Python bindings? I got them to compile by messing with the preprocessor a bunch but it's now failing at the linking step with a bunch of

   `undefined reference to '__imp__strncat_s_l' ...`

**Comment by RetroEdit** [comment]
I'm going to close this in a similar manner to other Python API issues like #2773 given that the Python API is deprecated now with the implementation of the Lua scripting subsystem. Python *is* planned as a future extension to that scripting subsystem.

I'm sorry you weren't able to get help, but I don't see a specific issue like this being resolved now. The issue tracker isn't well suited to handle support issues like this unfortunately (the Discord server can work better). Fortunately, other options for scripting exist like the newer Lua implementation or using mGBA in BizHawk.
