### ISSUE TITLE
Stuck @ ~50hz + Sound crackling while using 8bitdo SN30 Pro+ via Bluetooth

### ISSUE THREAD

**Issue by Ludhelm** [mgba-emu/mgba#1638]
In every game i tested the sound is crackling like hell.
No problems with other gba cores.
Retroarch 1.8.2
mGBA core 0.8 c4951dd

Windows 10 64bit
Ryzen 3900x
32gb RAM 3200mhz
RTX 2080

Standalone mGBA 0.8.0 works perfectly and the Interframeblending is just great.

**Comment by Ludhelm** [comment]
So i tested it on a different system with the exact same settings.

Windows 10 64bit
Ryzen 3600
16gb RAM 3200mhz

Same Retroarch and mgba build.

NO crackling wtf ? 

The only thing i noticed is that on the second system it runs with ~60hz but on my main system it runs @ ~50hz . Any suggestions ?

**Comment by endrift** [comment]
This is almost certainly a RetroArch issue, not an mGBA issue.

**Comment by Ludhelm** [comment]
EVERY other core is working flawlessly. Even if the problem is Retroarch pls give me any suggestion.

**Comment by endrift** [comment]
I'm not an expert on RetroArch so I don't know. Ask on their support channels, they'd know better

**Comment by Jules-A** [comment]
You could try using a newer RetroArch version? They are at v1.8.4 now.

**Comment by Ludhelm** [comment]
Updated to 1.8.4. Nothing.

BUT i found the culprit ! When my 8bitdo SN30 Pro Plus is connected via Wifi the core/retroarch goes down to 50 hz. After turning it off the fps go up to 60 and the sound is perfect. WTF ?! So is it a bug in Retroarch or mgba core ? I use this controller in Xinput mode.

**Comment by Ludhelm** [comment]
*via Bluetooth not wifi

**Comment by endrift** [comment]
I've seen that happen with other games (like Bloodstained and Assassin's Creed) when a Bluetooth controller is either low on battery or almost out of range. It seems to be an issue with Windows' Bluetooth implementation.

**Comment by Ludhelm** [comment]
Hmm. The batterie is not low and the antenna is only 1m - 2m away.

**Comment by Ludhelm** [comment]
Using a ps4 controller via bluetooth and DS4 Windows no problem at all BUT if i change the device from that virtual Xinput Controller to 8bitdo SN30 Pro+ (listed as xbox one controller) the fps go down and the crackling starts.

**Comment by Ludhelm** [comment]
So i did some more testing.

I tested the following controllers (all are listed as Xbox One Controller in Retroarch)

8bitdo - SN30 Pro+     -stuttering
8bitdo - SF30 Pro        -stuttering
8bitdo - Lite                -No stuttering
8bitdo - Zero 2           - Stuttering

**Comment by endrift** [comment]
This is a dupe libretro/mgba#163, in that case.
