### ISSUE TITLE
Monopoly sound problems

### ISSUE THREAD

**Issue by jmc92** [mgba-emu/mgba#1639]
On build - mGBA-build-2020-01-23-win64-6040-541715008bea659104a1705caa69a7bfd3f36637
I get constant sound crackling noise from Monopoly no matter if I use SDL or QT. The sound is to speed, nothing is lagging and the game plays right otherwise. I've tried using software and opengl rendering but that doesn't change anything.
Just checked and the problem existed in 0.7.3, and 0.7-b1-win32 as well.
I'm on windows 7 with a realtek sound card.

**Comment by endrift** [comment]
This is another Full Fat game, so it's the same bug as #356 and #875.

**Comment by jmc92** [comment]
Ah, sorry about the clone then.
