### ISSUE TITLE
"Cannot make QOpenGLContext current in a different thread"

### ISSUE THREAD

**Issue by jiangzhengwenjz** [mgba-emu/mgba#1642]
The build you are using: `0.8-0.8.0-6037-2368391f`
The operating system you're using: `ubuntu 18.04`
Your CPU and graphics card: `i5-4210U`/`Intel Haswell Mobile`

So, I downloaded the debian packages from mgba.io. In mgba-qt, I can load ROMs and play without any problem, but when I exit the program, the following appear in the terminal: 
```
Cannot make QOpenGLContext current in a different thread
Aborted (core dumped)
```

**Comment by endrift** [comment]
Are you exiting via the menu or via the X in the corner? Are you using the Shutdown option in the Emulation menu?

It shouldn't matter, but I just want to narrow down if there are any potential places things could be going wrong. Also, are you using the OpenGL enhancement renderer? If so, I fixed a bug the other day that might be related.

**Comment by jiangzhengwenjz** [comment]
@endrift 
> Are you exiting via the menu or via the X in the corner? Are you using the Shutdown option in the Emulation menu?
I tried both and they produced the same problem. 

> Also, are you using the OpenGL enhancement renderer? 
No, I'm using  software renderer. However, switching to OpenGL in `tools -> settings -> enhancements` (and restarting the program) produced the same problem.

**Comment by jiangzhengwenjz** [comment]
Also I found switching ROM halfway can also cause the problem.

**Comment by endrift** [comment]
Do you have gdb installed? If so, can you get a backtrace of where it's aborting?

**Comment by jiangzhengwenjz** [comment]
```
[Thread 0x7fffb53d5700 (LWP 8698) exited]
[Thread 0x7fffb4b73700 (LWP 8700) exited]
[Thread 0x7fffb4bb4700 (LWP 8699) exited]
Cannot make QOpenGLContext current in a different thread

Thread 10 "Painter Thread" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffb5bd6700 (LWP 8697)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff781be97 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff781d801 in __GI_abort () at abort.c:79
#2  0x00007ffff4badfb7 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff539ec73 in QOpenGLContext::makeCurrent(QSurface*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#4  0x00007ffff56b2234 in QOpenGLVertexArrayObject::destroy() ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#5  0x00007ffff56a52f8 in  () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#6  0x00007ffff56a5519 in  () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#7  0x00007ffff56a06d9 in QOpenGL2PaintEngineEx::~QOpenGL2PaintEngineEx() ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#8  0x00007ffff4bc19cd in QThreadStorageData::finish(void**) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff4bc2293 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff4bc3185 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff62196db in start_thread (arg=0x7fffb5bd6700)
    at pthread_create.c:463
#12 0x00007ffff78fe88f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by endrift** [comment]
This should be fixed now; let me know if it's still broken for whatever reason.

**Comment by endrift** [comment]
Caused #1686.
