### ISSUE TITLE
Exiting the temporary save dialogue brings FPS to 0

### ISSUE THREAD

**Issue by PhoenixBound** [mgba-emu/mgba#1643]
Tested on 0.8.0 (win64 build). My OS is Windows 10 64-bit, CPU is an Intel i5-6500, GPU is an AMD R9 390.

Steps to reproduce:

* Open a ROM with File --> Load ROM...
* Go to File --> Load temporary save... or File --> Load alternate save... once the game or GBA BIOS begins to boot
* Cause the dialogue box that pops up to close in some way -- e.g. choose a save file and hit OK, click the Cancel button, or close the window with the X in the corner.

At this point, the emulation remains paused at 0 FPS, and the only menu option that seems to do anything is Emulation --> Shutdown

**Comment by endrift** [comment]
I don't seem to be able to reproduce this. What do your A/V settings look like?

**Comment by PhoenixBound** [comment]
![image](https://user-images.githubusercontent.com/13182187/74575637-6099f500-4f4d-11ea-894c-16dff1a99ccc.png)

**Comment by endrift** [comment]
Does this happen if you use the SDL audio driver too?

**Comment by PhoenixBound** [comment]
Switching to SDL seemed to fix it.

**Comment by endrift** [comment]
Ok, I'll take a look at if I can reproduce with Qt Multimedia.
