### ISSUE TITLE
Exit emulator from ROM

### ISSUE THREAD

**Issue by crawfxrd** [mgba-emu/mgba#1645]
**Feature request**:
I am looking for functionality similar to QEMU's `isa-debug-exit` device. Writing to this device's port from the guest will cause QEMU to exit.

**Background**:
I am using mGBA for development of a Rust program targeting the GBA. I am looking to run tests from within the guest. This nice-to-have would allow the ROM to exit mGBA without user intervention.
In combination with `REG_DEBUG_*` for logging to mGBA, this would allow for running and reporting results of test ROMs (in my case, `cargo xtest`) in an automated fashion.

Ref: https://os.phil-opp.com/testing/#exiting-qemu
Ref: [qemu/hw/misc/debugexit.c](https://github.com/qemu/qemu/blob/ba2ed84fe6a78f64b2da441750fc6e925d94106a/hw/misc/debugexit.c)

**Comment by endrift** [comment]
The easiest target for this would be disabling IRQs and calling the Stop SWI, which would effectively turn off the GBA (more accurately, put it in a low-power, unrecoverable state). Making that close the emulated game (which in the SDL version exits the emulator) would probably be doable.

**Comment by endrift** [comment]
Added in a8999958dafb0486c4d5474ed13d21e36e17cc3c, used as per the description in the previous comment.
