### ISSUE TITLE
Glitch on Yoshi's Island

### ISSUE THREAD

**Issue by themalu866** [mgba-emu/mgba#1647]
Playing on Windows 7, I think is a transparency glitch.
![fdfdff](https://user-images.githubusercontent.com/42208976/73136605-15678300-402e-11ea-844b-6429b85d5ee6.png)

This is happening in all versions, here are the save states.
[Yoshi's Island.zip](https://github.com/mgba-emu/mgba/files/4113562/Yoshi.s.Island.zip)

**Comment by endrift** [comment]
Seems to be an issue with the window parameters.
