### ISSUE TITLE
Fast Forward and Mute Only Work While Being Held Down

### ISSUE THREAD

**Issue by Zeturic** [mgba-emu/mgba#1650]
I just downloaded 0.8.0 from 0.7.2. I use a wired Xbox One controller.

In 0.7.2 (and earlier) versions, I mapped `Mute` to left bumper and `Fast Forward` to right bumper. I could toggle them by hitting the relevant bumper.

I attempted to set up 0.8.0 identically, but it doesn't work. Both only activate while the bumper is being held down.

I do not have a shortcut set for `Fast Forward (Held)`.

**Comment by endrift** [comment]
Windows?

**Comment by Zeturic** [comment]
Yes, sorry. Windows 10.

**Comment by endrift** [comment]
I'll see about fixing this tonight.
