### ISSUE TITLE
error mgba-qt

### ISSUE THREAD

**Issue by ludo77** [mgba-emu/mgba#1651]
Hello,
when I use the command: mgba-qt
I have an error:
`Qt: Session management error: None of the authentication protocols specified are supported
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
mgba-qt: Couldn't find current GLX or EGL context.
`
please help me

**Comment by endrift** [comment]
What hardware are you running this on?

**Comment by ludo77** [comment]
My hardware is ubuntu 18.04:
2 graphics cards: i915 and GeForce GTX 850M
version 0.7.3 of mgba worked very well before the 0.8 update.

**Comment by ludo77** [comment]
the emulator mgba is ok (it's working)

**Comment by endrift** [comment]
Is this still an issue? It likely a problem with lutris itself.

**Comment by Testsr** [comment]
@ludo77, any updates?

**Comment by endrift** [comment]
Closing due to lack of reply
