### ISSUE TITLE
Enhancement: Expose instruction-by-instruction debugging to an API

### ISSUE THREAD

**Issue by RetroEdit** [mgba-emu/mgba#1652]
Related to [this](https://github.com/TASVideos/BizHawk/issues/1777), one useful feature in Bizhawk that the VBA-Next core has but the mGBA core doesn't is instruction-by-instruction debugging. In Bizhawk, this is present in at least two forms: the Trace Logger and the Debugger (I will try to add screenshots later).

As far as I know, mGBA doesn't really expose this, but it would be required for feature parity with the VBA-Next core. Moreover, it would just be generally useful to access when (if?) Lua support is added to mGBA.

Also sort of related: #1629, though if instruction-by-instruction debugging were exposed to Lua in sufficient capacity, this could be implemented by the end-user (which is probably less than ideal; it would be more ideal if mGBA did implemented it, but personally I see instruction-by-instruction debugging as more generally applicable and I would prefer if that were prioritized).

**Comment by endrift** [comment]
This already exists, and I've talked to @vadosnaprimer about it some.

**Comment by RetroEdit** [comment]
Thanks, just wanted that brought up in case it wasn't, but it's good that's on the BizHawk team's radar. I guess I'll have to look forward to BizHawk 2.5 (or later) in the meantime.
