### ISSUE TITLE
007 - NightFire 

### ISSUE THREAD

**Issue by scraggles80** [mgba-emu/mgba#166]
during the gameplay the bottom of the screen just flickers with garbage
![007 - nightfire usa europe en fr de -0](https://cloud.githubusercontent.com/assets/4402150/11164013/6cfef47c-8b1f-11e5-8628-314593de5f44.png)

**Comment by endrift** [comment]
Fixed in 2b2a037de53880aacfff17d8dadbcf54ccf226e9
