### ISSUE TITLE
Glitch on Chikyuu Kaihou Gun ZAS

### ISSUE THREAD

**Issue by themalu866** [mgba-emu/mgba#1666]
Playing on Windows 7, the background just keeps blinking.
![eee](https://user-images.githubusercontent.com/42208976/74590749-0140f100-4ff0-11ea-935a-a12e3d4a7bd8.gif)
![3443](https://user-images.githubusercontent.com/42208976/74590765-36e5da00-4ff0-11ea-8e21-757e7e0782c6.png)

**Comment by Panderner** [comment]
You have to turn on interframe Blending it has options: Simple, Smart and LCD Ghosting. Fast or Accurate option. This game uses fake transparency effect using flickering for backgrounds just like F-Zero's Mipmap And Wave Race

**Comment by RetroEdit** [comment]
I've tried interframe blending and I don't see the options "Simple, Smart and LCD Ghosting" or the "Fast or Accurate" options. For the sake of the OP and myself, can someone provide more details on how to change these options?

**Comment by endrift** [comment]
The inter frame blending options mentioned are in the libretro core, not upstream. As for the slight flickering, this is effectively a bug in the inter frame blending approach.

**Comment by Panderner** [comment]
Interframe blending is not available in standalone version?

**Comment by RetroEdit** [comment]
Interframe blending itself is available as a single checkbox, but the specific options you mentioned are not.
