### ISSUE TITLE
ELF loading regression from 0.8.0 to 0.8.1

### ISSUE THREAD

**Issue by Diegoisawesome** [mgba-emu/mgba#1669]
On 0.8.0 I used to be able to load the pokeemerald ELF file, and run it normally. In 0.8.1, however, it crashes on a white screen on boot presumably because it can't find the header (the name in the status bar is blank) so the save type is wrong.

**Comment by endrift** [comment]
Are you sure? #1450 was never closed...

**Comment by Diegoisawesome** [comment]
Yeah, here's the ELF loaded in 0.8.0 and 0.8.1, side by side:
![image](https://user-images.githubusercontent.com/6080951/74617274-2a8d7a00-50e1-11ea-86f2-f1399028f71e.png)
