### ISSUE TITLE
0.8.1 bugged and not stable?

### ISSUE THREAD

**Issue by BartSamptson44** [mgba-emu/mgba#1670]
hi!, new release is awesome but found bug! https://i.imgur.com/2VGYr6f.png

says a bunch of random numbers instead of stable 0.8.1, will a stable be out soon?

**Comment by endrift** [comment]
Ugh, the builders went rogue again. Is this the 32 or 64 bit? And also this isn't a bug.

**Comment by BartSamptson44** [comment]
picture is 64. i, checked both 32 and 64 from zip portable ver. and they both look like that.

**Comment by endrift** [comment]
Ok, it should be fixed now, just redownload the files.
