### ISSUE TITLE
Unable to load ROMs from mounted NTFS partition

### ISSUE THREAD

**Issue by aggserp4** [mgba-emu/mgba#1671]
I'm running version 0.8-8-4fdbf82 on Ubuntu 18.04.

I am unable to navigate to my mounted NTFS partition where my ROMs are located using the "Load ROM..." function. Attempting to open the ROM via the file manager gives a "Could not load game. Are you sure it's in the correct format?" error. Is there any workaround for this other than copying the files to my current partition?

**Comment by endrift** [comment]
If you use a dev build does it give a different error?

**Comment by aggserp4** [comment]
I initially couldn't find how to get the dev build to work so installed the snap from the "edge" channel (which, according to the title bar, was the same version as the one I had installed before from the "stable" channel). That one still didn't work, but it didn't give any error message at all (it just booted up and nothing happened).

Then I figured out that the dev build works from the command line, and that one worked perfectly.

**Comment by endrift** [comment]
Strange. Any unusual characters in the filenames?

**Comment by aggserp4** [comment]
No, unless you count parentheses in the file name. But I don't think they matter since it plays fine if it's in my current partition.

I tried launching the game from the command line using the "stable" snap version and got the error "Could not run game. Are you sure the file exists and is a compatible game?". So I assume there's a change in the relevant code between the stable and development versions.

**Comment by endrift** [comment]
I slightly changed the error messages for failing to load a game but I thought that was it. I was looking for which one came up (it used to just be "failed to load", now it's either "can't find file" or "file not compatible"-style ones), so now I'm even more confused. I may have to make an NTFS image just to test this.

**Comment by aggserp4** [comment]
Alright, I've just randomly found the reason for this. Turns out snap packages can't access removable drives or other partitions (it's possible to set up permissions to let them do so, but there isn't an option for that for mgba). I installed the deb version from your website and it works as expected.
