### ISSUE TITLE
ELF no longer works 0.8.1 (sample attached)

### ISSUE THREAD

**Issue by felixjones** [mgba-emu/mgba#1677]
Works in 0.8.0, but not in 0.8.1 (white display). This also means GDB debugging ELF is not available.

Download ELF: [gba-debug.zip](https://github.com/mgba-emu/mgba/files/4242401/gba-debug.zip)

I don't believe this ELF is doing anything special, it simply writes to VRAM.

**Comment by endrift** [comment]
Dupe of #1669
