### ISSUE TITLE
Black screen on OpenGL

### ISSUE THREAD

**Issue by johnny-mac** [mgba-emu/mgba#1678]
Hi, sorry I'm not the most savvy user but I'll try to explain the problem as best I can.

When not using OpenGL 1.x, the screen remains black but you can hear sound. Using OpenGL 1.x makes the screen work again. Any idea the culprit behind this? I'm running Void Linux MUSL, a minimalist independent distro. Please let me know if there's anything else I can tell you. 

I should also add that this is the only emulator I have giving me issues, all the others work fine.

**Comment by RafaelTrepaUnCarballo** [comment]
I think the cause it's in your linux distribution.

https://wiki.voidlinux.org/Musl#Possible_problems

> Some programs (mostly graphical applications) will work incorrectly, or segfault when run under musl. This may be due to programs expecting some glibc-specific behavior.

**Comment by endrift** [comment]
Can you post the output of `glxinfo`?

**Comment by johnny-mac** [comment]
Sorry for the late reply:
https://pastebin.com/Rwz33Z6x

**Comment by johnny-mac** [comment]
Awesome Endrift, glad to see this got fixed :)
