### ISSUE TITLE
Advance Guardian Heroes (USA) popping sound

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#1679]
When music is playing you can here a popping sound. Here is a video. 

mGBA-build-2020-02-24-win32-6141-12ae8ba9491b8428711cbbde50f8cc5719007cfa
 
https://www.youtube.com/watch?v=3LFQtUYa-Ic&feature=youtu.be

**Comment by endrift** [comment]
Link doesn't work; video is private

**Comment by Cibomatto2002** [comment]
sorry about that. 

https://www.youtube.com/watch?v=H1CuVw9Av88&feature=youtu.be

**Comment by endrift** [comment]
I'm pretty sure your audio or sync settings are off; it doesn't happen on my end.

**Comment by Cibomatto2002** [comment]
Deleted everything now it's working correct.
