### ISSUE TITLE
Super Monkey Ball Jr. (USA)

### ISSUE THREAD

**Issue by scraggles80** [mgba-emu/mgba#168]
fails to save 
![super monkey ball jr usa -0](https://cloud.githubusercontent.com/assets/4402150/11177309/9d6f9330-8c7f-11e5-8514-4669b210dba0.png)

**Comment by endrift** [comment]
Autodetection doesn't seem to work in this game. Fixed by adding an override in a27209737b25c84d949ac0e698a5e6e3b814caa6.
