### ISSUE TITLE
mGBA cant load or save Pokémon Emerald save

### ISSUE THREAD

**Issue by FellFromTheSky** [mgba-emu/mgba#1680]
I try to load the save of the Pokémon Emerald game that I dumped from my GBA SP, but mGBA don't recognize it. I also dumped the game from it. I dumped other saves from other games and it works perfectly, for example Donkey Kong Country. All Pokémon games are not loading nor saving the game. Then it's the same thing for every GBA emulators, but mGBA is formely the best one.
Please fix this ugly bug.
Thanks.

FellFromTheSky
Glory to the holy shovel ! :)

**Comment by endrift** [comment]
Please upload the save

**Comment by FellFromTheSky** [comment]
Ok, as I said it's directly from my GBA SP (dumped trough my DSL).
And it's supposed to work. It's a 128 Kb save file (big for a GBA).
download is on Google Drive :
https://drive.google.com/open?id=1Zfo3YIVmV1LHfxdP780ntDAmjCrVAelB

**Comment by endrift** [comment]
That file just looks like random junk data, not like a Pokémon save file...I wonder if it didn't dump properly. Also, is there any chance your Pokémon cartridges are bootlegs?

**Comment by FellFromTheSky** [comment]
bootlegs?

**Comment by FellFromTheSky** [comment]
Then, maybe mGBA or another emulator overwritten the file not correctly.

**Comment by endrift** [comment]
It's possible. Try dumping the save again and uploading a fresh version of that file.

**Comment by endrift** [comment]
Also take a look at some of these photos and compare your cartridge to them: https://www.google.com/search?tbm=isch&q=bootleg%20pokemon%20emerald

**Comment by FellFromTheSky** [comment]
Mine looks real. Then, it's one of the two cartridge that I bought in a pawnshop.
Those two are Pokémon Emerald and Tetris for GBC.
The other ones, I got them when I was a child, so I can't say if they're true or not.
SInce they are able to save and load, they're surely true.

**Comment by FellFromTheSky** [comment]
To be sure, how I can say a ROM file is from a real or fake cartridge without looking at the cartridge?

**Comment by endrift** [comment]
If you dump the cartridge ROM, you can compare the checksums (MD5, SHA1, SHA256) against known-good ROMs.

**Comment by FellFromTheSky** [comment]
Ok.
Then the game just freeze when I save my Pokémon Emerald game on mGBA

**Comment by endrift** [comment]
I meant the checksum of the ROM, not the save.

**Comment by FellFromTheSky** [comment]
yeah I know.
I was just saying that the game freeze in the mGBA emulator when I try to save it from the game menu (not mGBA menu).

**Comment by FellFromTheSky** [comment]
Ok thanks.
I'll check if my other ROMs are true ones.

**Comment by FellFromTheSky** [comment]
Uh, I can't find validated checksums for GBA games.
Could you help me to find some?
Thanks

**Comment by FellFromTheSky** [comment]
Do mGBA have a Discord server so we can talk on it?

**Comment by endrift** [comment]
Pokémon Emerald is:
SHA256: a9dec84dfe7f62ab2220bafaef7479da0929d066ece16a6885f6226db19085af
SHA1: f3ae088181bf583e55daf962a92bb46f4f1d07b7
MD5: 605b89b67018abcea91e693a4dd25be3

There's the No-Intro dats but those seem to be a bit hard to browse.

As for discord: check mgba.io for an invite link.

**Comment by FellFromTheSky** [comment]
So yah, I don't have the same hash, but it's maybe because the cartridge are not form the same country (mine was bought from Canada and it's in english).

**Comment by endrift** [comment]
Your save file had BPEE in its name, which is the game code for the version I have. It should be the same.

**Comment by FellFromTheSky** [comment]
So yah it's strange.

**Comment by FellFromTheSky** [comment]
Let's continue to talk on Discord

**Comment by endrift** [comment]
Determined over Discord that the copy is a bootleg, so there's not much I can do here. See also #247
