### ISSUE TITLE
Background horizontal mosaic isn't shown as expected when horizontal position is changed midframe

### ISSUE THREAD

**Issue by GValiente** [mgba-emu/mgba#1684]
Test rom:
[mosaic-test.zip](https://github.com/mgba-emu/mgba/files/4286171/mosaic-test.zip)

mGBA tested versions:
0.8.1 and 6156-8d194fa.

If the horizontal position of the background is not changed midframe, horizontal mosaic is shown as expected.
Of all tested emulators, VBA is the only one which seems to get it right:

![mGBA -  (60 fps) - 0 8 1 3_4_2020 9_30_26 AM](https://user-images.githubusercontent.com/13147012/75860026-6cb1fd80-5dfb-11ea-873f-59c2ad6b036b.png)

![No$gba Emulator  3_4_2020 9_29_57 AM](https://user-images.githubusercontent.com/13147012/75860028-6d4a9400-5dfb-11ea-81c4-7c491059c6ee.png)

![VisualBoyAdvance- 91% 3_4_2020 9_30_40 AM](https://user-images.githubusercontent.com/13147012/75860029-6d4a9400-5dfb-11ea-82e7-49ef4ca1aea9.png)

**Comment by GValiente** [comment]
Byuu seems to get it right too:
![mosaic-test 3_4_2020 9_45_51 AM](https://user-images.githubusercontent.com/13147012/75861064-1f369000-5dfd-11ea-97cd-fbf809ff84d2.png)

**Comment by endrift** [comment]
Do you have a non-animated version of this? It's kinda hard to compare against hardware when it's animating.

**Comment by GValiente** [comment]
[mgba_1684.zip](https://github.com/mgba-emu/mgba/files/5076711/mgba_1684.zip)

VBA seems to show the correct output:

![vba](https://user-images.githubusercontent.com/13147012/90284963-3630e200-de73-11ea-9be7-1dd95a126cfe.png)

mGBA output:

![Uploading mgba.png…]()

**Comment by GValiente** [comment]
If it helps, here's the source code of the latest test rom:
https://github.com/GValiente/butano/tree/master/issues/mgba_1684
