### ISSUE TITLE
GBASIOLockstepNodeLoad does not always update the SIO control flags.

### ISSUE THREAD

**Issue by Testsr** [mgba-emu/mgba#1685]
GBASIOLockstepNodeLoad does not always update the node->d.p->siocnt.

**Comment by endrift** [comment]
Can you describe what the expected behavior here is?

**Comment by Testsr** [comment]
The SIO_MULTI case writes a new value to node->d.p->siocnt in the code. The SIO_NORMAL_32 and SIO_NORMAL_8 case do not write to the node->d.p->siocnt. This might

**Comment by Testsr** [comment]
I noticed this with the [DEBUG] GBA Serial I/O:	Lockstep 0: SIOCNT <- 2083 after the game was supposed to write at high speed.

**Comment by Testsr** [comment]
The 0x2083 indicated the SIO_CNT is still in MultiPlayer Mode.

**Comment by Testsr** [comment]
GBASIOLockstepNodeLoad should reset everything. 

I am a bit of a bad tech nerd, sorry for that. I want to learn more about the GBA.

**Comment by endrift** [comment]
That's not at all how this code works. That memory is initialized by the core, elsewhere.
