### ISSUE TITLE
Adding a Multiplayer window while a rom is being played crashes mgba.

### ISSUE THREAD

**Issue by Testsr** [mgba-emu/mgba#1686]
Reproduction:
1) Load mGBA master branch with a rom.
2) Add a new multiplayer window.
3) mgba crashs.

Using Windows 10 1909.

**Comment by endrift** [comment]
Fixed in 74edd964daeebe53f6b1d9f86e91aecced1149a8 on Windows and GLX. Still need to test on macOS and EGL.
