### ISSUE TITLE
mgba crashing every time I attempt to load a ROM on Windows 7

### ISSUE THREAD

**Issue by breg-alad** [mgba-emu/mgba#1687]
I wanted to try mGBA 0.8.1 but I couldn't. Everytime I load a ROM it crashes immediately.

The emulator itself, not the game, crashes. I'm using Windows 7 32-bit. I tried installing the emulators both by un-zipping a 7z archive and by using the installer, and both in French and English languages, and both the latest (0.8.1) and an older version from 2017, the result is always the same.

It doesn't matter whether I attempt to load a GB, GBC or GBA ROM, anything crashes immediately and systematically

I tried the following "fixes", none of them have any effect :

- Removing save file created by another emulator
- Enable "Pause" before loading the ROM
- Removing video and sound sync
- Disabling audio completely ("mute")
- Alternating video render between "software" and "OpenGL"
- Add a BIOS file
- Tick the "preload entiere ROM into memory" option

None of this worked. Any attempt to load any ROM still result in crashes.

There seems to be nothing related to the crashes in the log file even when enabling all logs.

**Comment by endrift** [comment]
Have you tried setting the display driver to software?

**Comment by breg-alad** [comment]
Yes, and this is already mentionned in my OP by the way.

**Comment by breg-alad** [comment]
Wow I was absolutely 100% sutre I tried, but now that I try again it works. Sorry for the trouble !

**Comment by endrift** [comment]
Note that the software display driver is pretty slow. OpenGL (force 1.x) may work too, but if the non-force 1.x version doesn't work then you either have a very old GPU or you need to update your graphics drivers.

**Comment by breg-alad** [comment]
Still, if there's a driver problem or anything, the program should display some error, not crash !

**Comment by endrift** [comment]
Does this still reproduce? I fixed some issues with Intel GMAs that might have been this issue.
