### ISSUE TITLE
 Problem blinking white on PSVita

### ISSUE THREAD

**Issue by pinpon-1592** [mgba-emu/mgba#1689]
When you try to load and play a game, you experience the following issues:

![vita-min](https://user-images.githubusercontent.com/62130172/76598233-ca55f080-6545-11ea-9d21-56ec87eeb4a5.png)

Video link: https://youtu.be/h-tQyTjHsyI

1. The screen flashes white like a video.
2.If you reset it as shown in the picture, the game screen before reset will remain.

The game I play with videos and photos is Wario Ware Twisted, but this happens with other games as well.

The version is 0.81.

What should I do?

(Google Translate use)

**Comment by 371784711** [comment]
me too

**Comment by gotoAndDie** [comment]
I can confirm that this occurs on releases 0.8.1 and 0.8.2. However, version 0.8 beta 1 is fine, and the issue does not occur.

**Comment by gotoAndDie** [comment]
The issue appears to be caused by commit 97e2cf0 (Vita: Avoid uncached memcpy).

**Comment by endrift** [comment]
I was afraid that might be the case. It made it a lot faster, but...well, this happened.

**Comment by gotoAndDie** [comment]
It looks like the bug is related to frameskip; when frameskip is 0, the screen doesn't flash white anymore. When I turn frameskip up to 1 again, the screen seems to be displaying the last frame it was displaying before frameskip every other frame.

**Comment by endrift** [comment]
That would explain why I wasn't able to reproduce it earlier.

**Comment by endrift** [comment]
I plan to either merge #1822 or come up with an alternate solution tomorrow.
