### ISSUE TITLE
Graphical error in Golden Sun on mGBA 0.8.1

### ISSUE THREAD

**Issue by NotFx** [mgba-emu/mgba#1695]
I've recently noticed that mGBA loads Tret's sprite (just the sprite, no other data) in an out of bounds position where it's not supposed to be loaded (verified on original hardware). I'm on win10 x64.
![Ougon no Taiyou - Hirakareshi Fuuin (Japan) mGBA QuickSave3](https://user-images.githubusercontent.com/61700903/77208019-2ba83180-6afb-11ea-9267-54c12b190b79.png)

Original hardware:
![image](https://user-images.githubusercontent.com/61700903/77207205-13cfae00-6af9-11ea-9eee-209502835740.png)

mGBA:
![image](https://user-images.githubusercontent.com/61700903/77207132-dff48880-6af8-11ea-8892-6fb3bfe5c988.png)

This seems to always happen, regardless of RAM state. I first assumed it might be some specific corrupt RAM, but it happens off a hard reset as well, in both the JPN and ENG versions.

**Comment by endrift** [comment]
Please give me reproduction steps.

**Comment by NotFx** [comment]
Enter Tret Tree dungeon, go up the vine top left of room 1, exit through left door, move about half a ''unit'' left, retreat glitch (drain pp to 5 or lower, then use shoulder button to attempt retreat, then save and reset (either soft or hard), you'll be out of bounds when you load in)

While out of bounds, hold up+right, you'll appear on the bottom of the screen. Walk around the room shown on screen counter-clockwise, Tret sprite is there.

**Comment by NotFx** [comment]
We've managed to find an edge case of this happening on original hardware; it has to do with specific djinn being skipped/obtained. Suggests it might not be an inaccuracy, rather the combination of djinn I had in the test files is one of the edge cases.

Sorry if this wasted your time.
