### ISSUE TITLE
Pokken Controller not recognized

### ISSUE THREAD

**Issue by Bangaio65** [mgba-emu/mgba#1696]
mGBA 0.8.1 64-bit on Windows 7
Hori Pokken Controler for Switch. Works without issue in other emulators I tried (including no$GBA)

On https://html5gamepad.com/ it shows up as `0f0d-0092-POKKEN CONTROLLER`. It's not recognized as xinput on Windows, so it must be dinput? No clue.

Let me know if you need more info. Thanks.

**Comment by fancythedeveloper** [comment]
Try DInput then

**Comment by endrift** [comment]
It's just a generic USB-HID device. Neither xinput nor dinput. However, if SDL doesn't recognize it there's nothing I can do (at least until someone implements Windows-specific controller API stuff in mGBA, which is probably not a thing I'm gonna do any time soon).
