### ISSUE TITLE
Can't compile on Ubuntu, Cmake error

### ISSUE THREAD

**Issue by ikeboy** [mgba-emu/mgba#17]
>           $cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
-- Feature summary:
-- 	CLI debugger: ON
-- 	GDB stub: ON
-- 	Video recording: ON
-- 	GIF recording: ON
-- 	Screenshot/advanced savestate support: ON
-- 	ZIP support: ON
-- 	7-Zip support: ON
-- 	Better audio resampling: ON
-- Frontend summary:
-- 	Qt: ON
-- 	SDL (2): ON
-- 	Libretro core: OFF
-- 	Profiling: OFF
-- Library summary:
-- 	Static: OFF
-- 	Shared: ON
>CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SDLMAIN_LIBRARY
    linked by target "mgba-sdl" in directory /home/myusername/gba/mgba/src/platform/sdl
    linked by target "mgba-qt" in directory /home/myusername/gba/mgba/src/platform/qt
-- Configuring incomplete, errors occurred!

This is on Ubuntu 15.04.

**Comment by endrift** [comment]
Hmm, this looks like a CMake or SDL distribution problem. I'll need to spin up an Ubuntu VM to diagnose this, though.

**Comment by ikeboy** [comment]
The fix didn't work, same error. SDL packages are

>dpkg --get-selections | grep -v deinstall|grep sdl
libsdl-image1.2:amd64				install
libsdl-mixer1.2:amd64				install
libsdl-net1.2:amd64				install
libsdl-sound1.2:amd64				install
libsdl-ttf2.0-0:amd64				install
libsdl1.2-dbg:amd64				install
libsdl1.2-dev					install
libsdl1.2debian:amd64				install
libsdl2-2.0-0:amd64				install
libsdl2-dev					install

**Comment by endrift** [comment]
Very strange. The build randomly broke on OS X yesterday, but it looks entirely unrelated to any changes I made. I'll look into that; maybe it's the same.
