### ISSUE TITLE
Emulator sometimes crashes when using alt+tab

### ISSUE THREAD

**Issue by fighuass** [mgba-emu/mgba#1700]
Sometimes when I alt+tab to other programs (like for when I need a walkthrough), the emulator just crashes and quits.

**Comment by lotharsm** [comment]
Could you give us a few more information? Which operating system are you using and which version of mGBA? Does this only happens when a game is running or also when the mGBA is "idling" around?

**Comment by fighuass** [comment]
Whoops, sorry.

OS: Windows 10 Home x64 
mGBA version: 0.8-0.8.0-6037-2368391f3

Only seems to happen while a game is running (like when it's either running, or ingame but paused by the emu), if mGBA doesn't have anything opened it doesn't happen.

**Comment by lotharsm** [comment]
Have you already tried running the latest 0.8.1 version?

**Comment by fighuass** [comment]
Ah, wasn't aware that there was a new version. Yes, that does seem to fix it.

**Comment by lotharsm** [comment]
Thanks for the feedback - closing then.
