### ISSUE TITLE
Palette errors on game "Sheep"

### ISSUE THREAD

**Issue by Maesejesus** [mgba-emu/mgba#1702]
Hello, I'd like to submit an issue.

The game titled "Sheep" (really, just that, it was released on Europe but not the US it seems) has some palette problems. On certain stages, the game shows incorrect colors for things like sand.

I've tried different dumps, it happens in all of them. It doesn't happen in other emulators such as VBA. I tested it on two **Wii** releases, 0.8.1 stable and the last nightly (mGBA-build-2020-03-01-wii-6156-8d194fa95b703fbfbee0ef2eb41ce453dfcfe962) downloaded today.

I attach an screenshot and a SRAM save file too just in case. To see the error in one of its instances, you'd only need to load the save file in "Arrangement Mode". and choose the stage I was going to play next.
![Sheep-5](https://user-images.githubusercontent.com/21066817/77568025-4813e780-6ec8-11ea-8cb1-9c92a6546610.png)

https://www.dropbox.com/s/cmjb1n3byt8zwg0/Sheep.sav?dl=0

I'm sure it's a minor problem compared to others but I wanted to inform in any case.

**Comment by endrift** [comment]
How consistent is this for you? It's not happening on PC, but I haven't tried on Wii yet.
