### ISSUE TITLE
How to use the memory viewer

### ISSUE THREAD

**Issue by Mte90** [mgba-emu/mgba#1705]
I am trying to understand how to change values in memory with mgba but the memory viewer is not easy to understand (also there is not doc about the debug stuff integrated in this software).

As example I pick a value, found with the search (also if writing something in the search field and press Return doesn't do anything), select in the table view the address, press the button to open the memory viewer, found the value but is not possible to change that.

![Screenshot_20200328_222932](https://user-images.githubusercontent.com/403283/77834270-cb8d3d00-7143-11ea-8547-23ccb594c894.png)

So before start digging with the source code I don't know if mgba support that feature.

**Comment by RetroEdit** [comment]
It should allow you to edit the value in the hex editor (maybe not?) It might be that you have not found the correct value for what you want, i.e. that the value does not do what you think it does. You may have better luck with BizHawk's memory tools.

As for mGBA's debug tools, they are a work-in-progress, and better, more intuitive tools are planned for future versions of mGBA.

**Comment by Mte90** [comment]
The `140` value as the screen in the right bottom is not possible to edit, is like in readonly mode (I know a bit Qt).

**Comment by RetroEdit** [comment]
I meant typing in hex directly into the hex editor definitely does work, because I remember specifically doing it in mGBA before.

**Comment by endrift** [comment]
You just type the number in. But if the game isn't paused it might just overwrite it's immediately.

Anyway this isn't a bug and this also isn't a support forum.

**Comment by Mte90** [comment]
Thanks for the answers!
Yes in the hex editor is possible to change it, I was thinking that the fields in bottom of the memory viewer like integer etc. as text field it was possible to change the values from there and automatically inserted that value in the memory.

Instead I have to do it manually the conversion.

**Comment by Mte90** [comment]
Before opening a new ticket do you think it is possible to implement in those fields an auto conversion of the value in the hex viewer? in this way is more simple to hack the games.

**Comment by endrift** [comment]
Yeah, I didn't realize that's what you were talking about. We can use this bug for that.

**Comment by Mte90** [comment]
No problem :-D

**Comment by endrift** [comment]
I (finally) got around to adding integer editing. String editing is probably not going to come in this release though.

**Comment by Apihplays** [comment]
it is possible to add edited memory to cheat list ? for example address 03000651=80 for medaforce leader to keep constantly available for each robattle.
