### ISSUE TITLE
Trouballs [CGB] fail to start if CGB BIOS isn't in use

### ISSUE THREAD

**Issue by GerbilSoft** [mgba-emu/mgba#1715]
Trouballs: Shows "This game can only be played on Game Boy Color".
- MD5: 1b5e155ac68d2c7b89e49c5e1024b45c

**Comment by endrift** [comment]
One bug per issue please.

**Comment by GerbilSoft** [comment]
Split it into two issues. It might be the same root cause, though.

**Comment by endrift** [comment]
While true, if it's not then it would be difficult to "half-close" the issue. Dupes are preferable.
