### ISSUE TITLE
Deadsoul_ogre Demo

### ISSUE THREAD

**Issue by scraggles80** [mgba-emu/mgba#172]
the graphics are all messed up
http://www.gbadev.org/demos.php?showinfo=512

**Comment by endrift** [comment]
It's broken on hardware too, but broken in a different way. Might just be the flashcart though.

**Comment by endrift** [comment]
Given all of the out-of-bounds access that the ROM does, and the fact that this is the same in every emulator I've thrown it at, this is probably not actually an mGBA bug.
