### ISSUE TITLE
New feature request: save screenshots of the same rom in the same folder

### ISSUE THREAD

**Issue by angelxd84130** [mgba-emu/mgba#1725]
when I load a rom as zip file, all screenshots are in the path where I downloaded the rom, so I wish can save them as a folder. 
<img width="518" alt="截圖 2020-04-12 上午11 38 58" src="https://user-images.githubusercontent.com/19487525/79076971-b3c0c780-7cb2-11ea-957b-ff63316b37ba.png">

**Comment by endrift** [comment]
This is already possible in Settings > Paths.
