### ISSUE TITLE
Chaos89 Demo

### ISSUE THREAD

**Issue by scraggles80** [mgba-emu/mgba#174]
top and bottom of screen keep flashing
http://www.gbadev.org/demos.php?showinfo=457

**Comment by endrift** [comment]
Reproduces on hardware.

**Comment by scraggles80** [comment]
this runs on VisualBoy Advanced with no problems

**Comment by profi200** [comment]
If it runs the same way on real hardware i don't know why the game should be fixed in emulators.
The author of that game likely only tested it with an inaccurate emulator.

**Comment by endrift** [comment]
The version as distributed can't even ben run on hardware anyway; it's missing a header that the GBA BIOS checks for that I had to stick on manually. I'm quite certain this was never tested on hardware, and this actually represents a bug in VBA if it "works fine" in VBA.
