### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#1740]
Hi whenever I open a rom file it just closes mGBA, I'm using windows 10 64bit, just like my PC. I then realized it was a dev build, so I downloaded 0.8.1 and same problem. The games I tried were Kirby Amazing Mirror, Kirby Nighmare in Dreamland, and Castlevania Double Pack. Kirby games are .gba, and Castlevania is .zip. I tried on some older builds but the same thing happened.

**Comment by Testsr** [comment]
@ghost, is this not working now?

**Comment by endrift** [comment]
"Ghost" means they deleted their account.
