### ISSUE TITLE
Linux version takes too long to load

### ISSUE THREAD

**Issue by citrus3301** [mgba-emu/mgba#1744]
I installed from snap store on ubuntu 20.04. When I press the start menu icon (which opens the specific program mgba-qt) it takes about 1 and a half minutes to load, but if i try and open it twice, two windows load. If I try to open it from a terminal here is what i get : 

> lemon@lemontron:~$ mgba-qt
ln: failed to create symbolic link '/home/lemon/snap/mgba/492/.config/gtk-2.0/gtkfilechooser.ini': File exists
Gtk-Message: 00:29:20.397: Failed to load module "canberra-gtk-module"

(mgba-qt:19475): dbind-WARNING **: 00:29:20.399: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-xwisYHH9Kn: Permission denied
Qt: Session management error: None of the authentication protocols specified are supported
lemon is my username and lemontron is my pc, if this is just something with packages please let me know

**Comment by endrift** [comment]
Sounds like a problem with snap. The non-containerized version doesn't have this problem. It's too bad the Debian maintainer has gone MIA or else there'd be a recent version in Ubuntu.

**Comment by citrus3301** [comment]
how can i install without snap, is there a way to just build a deb file?

**Comment by endrift** [comment]
I provide those on the site, but I have yet to set up builders for 20.04. I was going to do that in March but I ended up taking a break from mGBA so it never got done.

**Comment by endrift** [comment]
I've updated the builders to start building for 20.04 whenever the next commit rolls around.

**Comment by lotharsm** [comment]
Yes, snap packages take a few seconds to load. However, more than 1 minute sounds like a flaw on your system. After a fresh reboot I get loading times of not more than 5 seconds for the mGBA snap. 

The warnings you see are harmless, they don't explain why it takes so long to launch.

**Comment by endrift** [comment]
I've started distributing (unstable) builds of mGBA for focal: https://mgba.io/builds/1/
