### ISSUE TITLE
Slowdowns and audio crackling issues on latest stable version for the Vita

### ISSUE THREAD

**Issue by Deadfalt999** [mgba-emu/mgba#1750]
No matter wich game I pick, I experience slowdowns and audio crackling issues, some games like Super Mario Advance 4 are really affected by them but games like Pokemon Ruby have them but barely noticeable. Been having those issues for a while with each new stable version.

**Comment by endrift** [comment]
That's not a bug, it's just the Vita being slow. I've tried to make mGBA faster but there are diminishing returns at this point. See also #1483.
