### ISSUE TITLE
[3DS ISSUE] Framerate is choppy.

### ISSUE THREAD

**Issue by theblackndsage** [mgba-emu/mgba#1751]
I have an old 3DS and I just downloaded and ran the most recently updated mGBA emulator and I tried running all the games and every single one's framerate is choppy as well as the audio. The only thing I've messed around with is the frameskip option, the interframe blending option, the screen mode option, and the filtering option and no luck. 

Is it just because I'm running it on an old system or do I need to install one of the older versions?

Any suggestions?

**Comment by endrift** [comment]
The old 3DS is extremely underpowered and  not sufficient for emulating the GBA.

**Comment by theblackndsage** [comment]
Just wanted to add that I was able to find a work around with Twilight if anyone was curious.
