### ISSUE TITLE
Game freeze in Golden Sun Lost Age

### ISSUE THREAD

**Issue by Digifiend84** [mgba-emu/mgba#1753]
Trying to play the GBA game **_Golden Sun: The Lost Age_** in Medusa's 2017-04-26-win64 build. Works fine most of the time, but then occasionally, you get a freeze, where any text on screen looks fine but the rest of the graphics and sound are corrupted. I've attached a brief video of this, which happened during a battle, and a savestate from another instance of this crash in a town. It happens on the world map as well, so it looks like it can happen anywhere.
**Save state:** [gslacrash.zip](https://github.com/mgba-emu/mgba/files/4628748/gslacrash.zip)
**Video:** [gslacrash.zip](https://github.com/mgba-emu/mgba/files/4628706/gslacrash.zip)

I did try the 2018-01-31-win64 build (Medusa's newest version to my knowledge), but that build is even worse, as the emulator crashes when the Camelot logo is supposed to appear on boot, so all you see is the Nintendo logo.

**Comment by endrift** [comment]
medusa is not currently maintained. Please use mGBA for GBA games instead.
