### ISSUE TITLE
Not able to build standalone for 3ds and wii

### ISSUE THREAD

**Issue by Ntemis** [mgba-emu/mgba#1755]
demetris@demetris-TA770E3:~/mgba/build$ cmake -DCMAKE_TOOLCHAIN_FILE=/home/demetris/mgba/src/platform/3ds/CMakeToolchain.txt ..
-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/bin/arm-none-eabi-gcc
-- Check for working C compiler: /usr/bin/arm-none-eabi-gcc -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/usr/bin/arm-none-eabi-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/demetris/mgba/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_7fbe7/fast"
    /usr/bin/make -f CMakeFiles/cmTC_7fbe7.dir/build.make CMakeFiles/cmTC_7fbe7.dir/build
    make[1]: Entering directory '/home/demetris/mgba/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_7fbe7.dir/testCCompiler.c.obj
    /usr/bin/arm-none-eabi-gcc -DARM11 -D_3DS  -I/opt/devkitpro/libctru/include -march=armv6k -mtune=mpcore -mfloat-abi=hard -ffunction-sections -mword-relocations    -o CMakeFiles/cmTC_7fbe7.dir/testCCompiler.c.obj   -c /home/demetris/mgba/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_7fbe7
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_7fbe7.dir/link.txt --verbose=1
    /usr/bin/arm-none-eabi-gcc -I/opt/devkitpro/libctru/include -march=armv6k -mtune=mpcore -mfloat-abi=hard -ffunction-sections -mword-relocations   -L/opt/devkitpro/libctru/lib -lctru -specs=3dsx.specs -march=armv6k -mtune=mpcore -mfloat-abi=hard -ffunction-sections -Wl,--gc-sections  CMakeFiles/cmTC_7fbe7.dir/testCCompiler.c.obj  -o cmTC_7fbe7 
    arm-none-eabi-gcc: error: 3dsx.specs: No such file or directory
    CMakeFiles/cmTC_7fbe7.dir/build.make:97: recipe for target 'cmTC_7fbe7' failed
    make[1]: *** [cmTC_7fbe7] Error 1
    make[1]: Leaving directory '/home/demetris/mgba/build/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_7fbe7/fast' failed
    make: *** [cmTC_7fbe7/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:10 (project)

-- Configuring incomplete, errors occurred!
See also "/home/demetris/mgba/build/CMakeFiles/CMakeOutput.log".
See also "/home/demetris/mgba/build/CMakeFiles/CMakeError.log".

**Comment by endrift** [comment]
Did you forget to install libctru?

**Comment by Ntemis** [comment]
I have latest development tools installed with dkp-pacman

**Comment by endrift** [comment]
It's definitely not using the right gcc, that's the system version. What's the output of `which arm-none-eabi-gcc`? And if it's `/usr/bin/arm-none-eabi-gcc`, what's the value of `$PATH`?

**Comment by Ntemis** [comment]
demetris@demetris-TA770E3:~$ sudo dkp-pacman -S 3ds-dev
:: There are 13 members in group 3ds-dev:
:: Repository dkp-libs
   1) 3ds-examples  2) citro2d  3) citro3d  4) devkitarm-crtls  5) devkitarm-rules  6) libctru
:: Repository dkp-linux
   7) 3dslink  8) 3dstools  9) devkit-env  10) devkitARM  11) general-tools  12) picasso  13) tex3ds

Enter a selection (default=all): 
warning: 3ds-examples-20200417-2 is up to date -- reinstalling
warning: citro2d-1.3.0-1 is up to date -- reinstalling
warning: citro3d-1.6.0-1 is up to date -- reinstalling
warning: devkitarm-crtls-1.0.3-1 is up to date -- reinstalling
warning: devkitarm-rules-1.0.0-1 is up to date -- reinstalling
warning: libctru-1.8.0-1 is up to date -- reinstalling
warning: 3dslink-0.5.2-2 is up to date -- reinstalling
warning: 3dstools-1.1.4-2 is up to date -- reinstalling
warning: devkit-env-1.0.1-2 is up to date -- reinstalling
warning: devkitARM-r54-3 is up to date -- reinstalling
warning: general-tools-1.0.3-1 is up to date -- reinstalling
warning: picasso-2.7.0-1 is up to date -- reinstalling
warning: tex3ds-2.0.1-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (13) 3ds-examples-20200417-2  3dslink-0.5.2-2  3dstools-1.1.4-2  citro2d-1.3.0-1  citro3d-1.6.0-1  devkit-env-1.0.1-2  devkitARM-r54-3  devkitarm-crtls-1.0.3-1
              devkitarm-rules-1.0.0-1  general-tools-1.0.3-1  libctru-1.8.0-1  picasso-2.7.0-1  tex3ds-2.0.1-2

Total Installed Size:  298,88 MiB
Net Upgrade Size:        0,00 MiB

:: Proceed with installation? [Y/n]

**Comment by Ntemis** [comment]
demetris@demetris-TA770E3:~$ which arm-none-eabi-gcc
/usr/bin/arm-none-eabi-gcc

**Comment by endrift** [comment]
And the value of `$PATH`?

**Comment by Ntemis** [comment]
demetris@demetris-TA770E3:~$ printf "%s\n" $PATH
/home/demetris/.local/bin:/opt/devkitpro/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by endrift** [comment]
I'm assuming the answer is yes, but does `/opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc` exist? This may be an issue with how I have CMake searching for paths. CMake can be really opaque sometimes.

**Comment by Ntemis** [comment]
demetris@demetris-TA770E3:~$ ls /opt/devkitpro/devkitARM/bin/
arm-none-eabi-addr2line  arm-none-eabi-cpp         arm-none-eabi-gcc-ar      arm-none-eabi-gcov-tool      arm-none-eabi-ld.bfd    arm-none-eabi-ranlib   arm-none-eabi-strip
arm-none-eabi-ar         arm-none-eabi-elfedit     arm-none-eabi-gcc-nm      arm-none-eabi-gdb            arm-none-eabi-lto-dump  arm-none-eabi-readelf
arm-none-eabi-as         arm-none-eabi-g++         arm-none-eabi-gcc-ranlib  arm-none-eabi-gdb-add-index  arm-none-eabi-nm        arm-none-eabi-run
arm-none-eabi-c++        arm-none-eabi-gcc         arm-none-eabi-gcov        arm-none-eabi-gprof          arm-none-eabi-objcopy   arm-none-eabi-size
arm-none-eabi-c++filt    arm-none-eabi-gcc-10.1.0  arm-none-eabi-gcov-dump   arm-none-eabi-ld             arm-none-eabi-objdump   arm-none-eabi-strings

**Comment by Ntemis** [comment]
http://dpaste.com/1M95HKR

**Comment by endrift** [comment]
You can use triple-backticks around lines to make them code blocks.

Anyway, I've managed to reproduce the issue on my end and will look into it further.

**Comment by Ntemis** [comment]
good news, thanks

**Comment by endrift** [comment]
You will need to delete your CMakeCache.txt before you can try again

**Comment by Ntemis** [comment]
now it complains about this
/bin/sh: 1: BANNERTOOL-NOTFOUND: not found
3ds/CMakeFiles/mgba.3dsx.dir/build.make:66: recipe for target '3ds/mgba.smdh' failed
make[2]: *** [3ds/mgba.smdh] Error 127
CMakeFiles/Makefile2:718: recipe for target '3ds/CMakeFiles/mgba.3dsx.dir/all' failed
make[1]: *** [3ds/CMakeFiles/mgba.3dsx.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by autofire372** [comment]
You need to install [bannertool](https://github.com/Steveice10/bannertool). You should also install makerom from [Project_CTR](https://github.com/3DSGuy/Project_CTR) so the cia builds.
