### ISSUE TITLE
Broken savegame screen on Mario & Luigi: Superstar Saga

### ISSUE THREAD

**Issue by renecatharsis** [mgba-emu/mgba#1756]
The savegame screen on Mario & Luigi: Superstar Saga (tested the EU version) looks broken sometimes. Weirdly enough it doesn't happen all the time, but I can get it to look broken when resetting a few times.

Build used: mGBA-0.8.1-win64 with OpenGL renderer
OS: Win10 Pro, 64-bit
System specs: Core i7-8750H, GeForce GTX 1060

Broken screen:
![mlss-saves-broken](https://user-images.githubusercontent.com/1114906/82158537-ded9a080-9888-11ea-80fc-e7b8e1e64a75.png)

Correct screen:
![mlss-saves-correct](https://user-images.githubusercontent.com/1114906/82158539-e305be00-9888-11ea-944f-e833b9619c4e.png)

**Comment by endrift** [comment]
I think I've seen this in the US version too. Not sure why it's inconsistent though; every time I've tried to debug it it doesn't happen.

**Comment by renecatharsis** [comment]
Which OS are you trying to get it to break on?
I could set up a quick VM with that and see if I can reproduce it there to maybe rule out OpenGL on Windows as the issue (unless it's *BSD which will leave me begging for mercy :) ).

**Comment by RetroEdit** [comment]
Also, if you can reproduce it, a savestate of when it's in the broken state might be somewhat helpful? At least it would confirm whether the issue is PC-specific or an actual emulation problem.

**Comment by renecatharsis** [comment]
While trying to reproduce I have noticed something curious. I had continued playing on my save since opening the issue and couldn't reproduce the error anymore. 
I could however reproduce again on a fresh savefile, while only having Mario as part of my team, Luigi is only still hanging around, not part of the actual battling team. As soon as Luigi joins, I cannot reproduce any more.

While messing around I even found another bug occuring on the save screen only.
When I enter the "Mario Bros." mode on the start screen, exit out and then enter "Mario & Luigi" mode, it looks like the save game's behind prison bars. This bug I can reproduce consistently at any game state.
![mlss-saves-broken-mariobros](https://user-images.githubusercontent.com/1114906/82250332-8cad8380-994b-11ea-838d-9d80a73d22df.png)

You can find savestates of all that attached.
* ss1 for a state working just fine
* ss2 for a state with the broken graphics of the original bug description
* ss3 for a state of prison cell mode

[mlss-states.zip](https://github.com/mgba-emu/mgba/files/4646108/mlss-states.zip)

**Comment by endrift** [comment]
is that "mode" only in the OpenGL renderer too?

**Comment by renecatharsis** [comment]
Seems like it, couldn't force it to happen on Software Renderer at all.

**Comment by endrift** [comment]
Ok, I'll try to look into this tonight. Thanks for the savestates.
