### ISSUE TITLE
OAM windowing broken

### ISSUE THREAD

**Issue by Sierraffinity** [mgba-emu/mgba#1759]
The shine on the Pokémon Emerald title screen, when hitting A to skip the shine animation at the beginning, leaves it on the screen for far too long. This seems to be a recent regression in recent development builds:

![pokeemerald_modern-0](https://user-images.githubusercontent.com/6080951/82726586-0f12ac00-9c9a-11ea-96e5-9c895bbff976.png)

**Comment by endrift** [comment]
I've seen this happen with the OpenGL renderer, but never the software renderer. You are using the OpenGL renderer right?

**Comment by Sierraffinity** [comment]
Yeah, but this has only started to occur recently.

**Comment by endrift** [comment]
The most recent change that could have done this was 4036136fe54e1b66ded88869d2eade20fc3a3cd5, four months ago.

**Comment by Sierraffinity** [comment]
Yeah entirely possible that could have been the cause, considering I've always sped past the title when playing recently. Before late February I was using release 0.8.1 and didn't have this issue, but got on the development version because of a different fixed bug.

**Comment by endrift** [comment]
I can reproduce in 0.8.1.
