### ISSUE TITLE
mGBA v. 0.8.1 Black Screens at Pokemon Fire Red Title Screen

### ISSUE THREAD

**Issue by OrisX** [mgba-emu/mgba#1765]
I load up the game and try to play it, and it will play the intro scene just fine, but as soon as it is supposed to switch to the title screen or I try to press A into it, it just gives a black screen. This is on Windows 10 64 bit. Do I have my settings wrong or something?

**Comment by endrift** [comment]
What does the ROM Info dialog (under the file menu) say?

**Comment by OrisX** [comment]
It says:

Game Name: (unknown)
Internal name: POKEMON FIRE
Game ID: AGB-BPRE
File size: 22554432 bytes
CRC32: 574de5bb

I actually had it renamed because I'm dumb, but this is a ROM hack, if that makes a difference. Using FireRed as a base.

**Comment by endrift** [comment]
Oh, it might be a problem with the ROM hack then. Which ROM hack is it?

**Comment by OrisX** [comment]
Metal Red. I heard the game is poorly programmed, but it works okay on VBA. It's just that VBA doesn't work as well as mGBA. No offense to the devs of VBA.

**Comment by endrift** [comment]
So far it looks like the game is hitting an undefined instruction, which would be a fatal error on hardware. It crashes the same way in NO$GBA as it does in mGBA. I'm not sure why it's not crashing in VBA-M though.

**Comment by Dimensional** [comment]
Both mGBA and No$GBA aim to be as accurate as possible to the real hardware. VBA-M however doesn't try to do that and instead employs things like speed hacks to get around any issues that games may have. As a result, the rom hack may utilize these exact same hacks in it's own code, which VBA-M wouldn't have problems with but the other emulators would.

**Comment by endrift** [comment]
I have confirmed that this crashes the same way on hardware.
