### ISSUE TITLE
Debug tracer traces only one instruction and stops

### ISSUE THREAD

**Issue by animaone** [mgba-emu/mgba#1767]
Debug tracer trace only one instruction and stop.
How to reproduce the bug:
compile sdl platform and start mgba with -d flag
trace more than one instruction, and sometimes it will trace only one instruction, sometimes it will trace the requested number of instructions
mgba -d rom
trace 1000

if I get input from pipe, 
echo "trace 100000" > input ; mgba -d rom < input
it will trace a big quantity of instructions and will close, or will just trace one instruction and close

When I start in debug mode, than type continue and press F11 in the emulator, the tracing in the debugger will work correctly.

**Comment by endrift** [comment]
I'm having trouble reproducing this. What git commit are you using, and on which OS?

**Comment by animaone** [comment]
00aa647
https://github.com/mgba-emu/mgba/commit/00aa6476c885fa66e9621960fc9555533ed19bcd

I am compiling the code in Ubuntu 18.04.1

**Comment by animaone** [comment]
This bug seems to be present since version 0.8.1

**Comment by animaone** [comment]
I've tested other versions, the bug is present in version mgba-0.8.0 (https://github.com/mgba-emu/mgba/commit/2368391f33da9da072524c59646c8d0e2c885525), but not in mgba-0.8-b1(https://github.com/mgba-emu/mgba/commit/13893803c3f528327a7aa96056e7c51564c5f86c), tracing in 0.8.0 is slightly slower also

**Comment by endrift** [comment]
I believe I fixed this a few weeks-to-months ago; it was broken for GB games specifically.
