### ISSUE TITLE
(3DS/latest) ARM11 Exception on launch (3dsx and cia)

### ISSUE THREAD

**Issue by autofire372** [mgba-emu/mgba#1768]
On the latest stable as well as the latest commit of Luma3DS, bot the 3dsx and cia builds of mgba crash on launch as depicted below:
![20200529_222223 1](https://user-images.githubusercontent.com/8486750/83317549-8b0d7680-a1fb-11ea-8a97-6760a88c93ed.jpg)

**Comment by endrift** [comment]
Hm, I wonder if Luma updates broke something.

**Comment by autofire372** [comment]
I should probably note that an old build of mgba from August 2019 worked fine on the same build of Luma.

**Comment by endrift** [comment]
That commit didn't change anything that affects anything shipped. I did, however, update libctru at the same time though.

**Comment by JL2210** [comment]
I don't have the issue on mine. I'll run Luma3DS Updater just to make sure.
