### ISSUE TITLE
0.8.1 in 3DS some GB issues

### ISSUE THREAD

**Issue by adrianmi1** [mgba-emu/mgba#1772]
I play in the New 3DS XL and i used to had the 0.7.2 version but I decided to update because some GBA games ran a little slow sometimes, with the 0.8.1 the fps in the GBA game (FF Tactics Advance) is much better but i noticed some GB issues. Since version 0.8.0 games like "Magic Knight Rayearth (Japan) (SGB Enhanced)" (and it´s translated patch version, both, the problem is not for the patch because I tried another patched games and all work well) or "Smurfs, The (Europe) (En,Fr,De,Es)" crashes at the start of the game, Magic Knight in the introduction text and Smurfs stays in the GB bios logo (if i dont use bios it crash with a white screen).
I tried with 0.8.0 and same, but in 0.7.3 its all ok with GB games.
I tried just a few, tested like 6 randomized games and found this errors in this two (I imagine it happens with more).
Thanks for all the work you are doing with the emulator, hope this issue report help you.

**Comment by endrift** [comment]
Magic Knight Rayearth works for me in 0.8, but Smurfs works in neither for me. Strange. What's in your /mGBA/config.ini?

**Comment by adrianmi1** [comment]
[gba.input.3DSK]
keyR=8
keyL=9
keyStart=3
keyLeft=5
keyDown=7
keyB=1
keyUp=6
keyA=0
keyRight=4
keySelect=2

[ports.3ds]
gbc.bios=/Bios/GBC/gbc_bios.bin
sgb.bios=/Bios/SGB/sgb_bios.bin
autoload=0
useBios=1
screenMode=4
filterMode=1
autosave=1
sgb.borders=1
darkenMode=0
sgb.model=SGB
lastDirectory=/Roms/GBC/Pokemon/Pokemon 2ª Generación/Pokemon Oro/
frameskip=0
camera=1
gba.bios=/Bios/GBA/gba_bios.bin
sgb.borderCrop=0
lastGame=/Roms/GBC/Pokemon/Pokemon 2ª Generación/Pokemon Oro/Pokemon - Edicion Oro (Spain) (SGB Enhanced).gbc
fpsCounter=1
gb.bios=/Bios/GB/gb_bios.bin
interframeBlending=0

[gui.input.3DSK]
keyTake screenshot=-1
keyIncrease solar brightness=26
keyDown=7
keyLeft=5
keyUp=6
keyDecrease solar brightness=27
keyBack=1
keyCancel=10
keyRight=4
keyFast forward (held)=-1
keyScreen mode=11
keySelect=0
keyFast forward (toggle)=-1

**Comment by adrianmi1** [comment]
in yours?

**Comment by endrift** [comment]
I don't see anything suspect in here. I'll take a look at why Smurfs is failing for me, though.

**Comment by endrift** [comment]
Smurfs is fixed in 90e932e12c0e093d9ff35989bf12778d7ff079eb, but this won't be cherry-picked into 0.8.2 for compatibility reasons.

**Comment by endrift** [comment]
Can you please link to the translation for Rayearth?
