### ISSUE TITLE
Docker building not working from Windows or Linux

### ISSUE THREAD

**Issue by autofire372** [mgba-emu/mgba#1773]
In light of [my issues building mgba locally](https://github.com/mgba-emu/mgba/issues/1769), I installed the Windows 10 May 2020 Update, installed Docker Desktop (set to use the wsl2 backend), and tried the docker build instructions.

First off, the command given fails on Windows unless "PWD" is bracketed, like so:

`docker run --rm -t -v ${PWD}:/home/mgba/src mgba/windows:w64`

Even after fixing that, the docker image fails at the cmake configuration stage:

```
PS C:\Emulation\mGBA\source> docker run --rm -t -v ${PWD}:/home/mgba/src mgba/windows:w64
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/lib/ccache/x86_64-w64-mingw32-gcc
-- Check for working C compiler: /usr/lib/ccache/x86_64-w64-mingw32-gcc -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/usr/lib/ccache/x86_64-w64-mingw32-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/mgba/src/build-win64/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_1bb3c/fast"
    /usr/bin/make -f CMakeFiles/cmTC_1bb3c.dir/build.make CMakeFiles/cmTC_1bb3c.dir/build
    make[1]: Entering directory '/home/mgba/src/build-win64/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_1bb3c.dir/testCCompiler.c.obj
    /usr/lib/ccache/x86_64-w64-mingw32-gcc -DEPOXY_STATIC_LIB -DZIP_STATIC   -o CMakeFiles/cmTC_1bb3c.dir/testCCompiler.c.obj   -c /home/mgba/src/build-win64/CMakeFiles/CMakeTmp/testCCompiler.c
    ccache: error: Failed to create directory /home/mgba/.ccache/tmp: Permission denied
    CMakeFiles/cmTC_1bb3c.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_1bb3c.dir/testCCompiler.c.obj' failed
    make[1]: *** [CMakeFiles/cmTC_1bb3c.dir/testCCompiler.c.obj] Error 1
    make[1]: Leaving directory '/home/mgba/src/build-win64/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_1bb3c/fast' failed
    make: *** [cmTC_1bb3c/fast] Error 2




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:10 (project)


-- Configuring incomplete, errors occurred!
See also "/home/mgba/src/build-win64/CMakeFiles/CMakeOutput.log".
See also "/home/mgba/src/build-win64/CMakeFiles/CMakeError.log".
```

I tried from Windows PowerShell and via WSL2 (Ubuntu 20.04), and got the same error.

**Comment by Dimensional** [comment]
What is the full directory path to where you save the source code? First thing I noticed is it appears you're getting a permission issue for the folder, where ever you're running it from. I don't entirely know how Docker works, but I think it seamlessly mounts your current directory over the directory you specified in the command. Maybe double check the permissions, including making sure that docker can edit it, either as you or as Hyper-V/WSL2, I believe.

Again, I don't know how it works, but it appears to be related to permissions for editing the folder where your files are saved, so check those permissions to see if they are still tied to you.

`ccache: error: Failed to create directory /home/mgba/.ccache/tmp: Permission denied`

**Comment by autofire372** [comment]
The error happens no matter where I try to clone the source to, the permissions all check out. and that shouldn't affect the Ubuntu VM anyway, as WSL2 uses separate .vhdx hard disk images.

**Comment by endrift** [comment]
I know what the problem is and will fix it today.

**Comment by autofire372** [comment]
Is it a WSL2 compatibility issue? I know I've been able to run the docker command with success on a native Manjaro install...

**Comment by endrift** [comment]
No, it's a bug introduced in https://github.com/mgba-emu/dependencies/commit/d3a754253bff02a2f2f0dd9b9c1bd685bc8fe06d a few days ago. For future reference, issues with the Docker containers should go in that repository.

**Comment by autofire372** [comment]
Got it.
