### ISSUE TITLE
ARM instruction decoder: umulls is decoded as umull

### ISSUE THREAD

**Issue by jeffayle** [mgba-emu/mgba#1778]
version: mgba-qt 0.9-11-8187174 on Linux x86-64

The ARM decoder incorrectly decodes `umulls` instructions as `umull`. This output is from the debugger:

```
08000304:  E0976994	umull r6, r7, r4, r9
08000308:  E0B76994	umlal r6, r7, r4, r9
0800030C:  E0D76994	smull r6, r7, r4, r9
08000310:  E0F76994	smlal r6, r7, r4, r9
08000314:  E0910392	umull r0, r1, r2, r3
08000318:  E0B10392	umlal r0, r1, r2, r3
0800031C:  E0D10392	smull r0, r1, r2, r3
08000320:  E0F10392	smlal r0, r1, r2, r3
```

These instructions were all assembled (using gnu toolchain) from the variants with `s`. This can be verified by [plugging those opcodes into another disassembler](http://shell-storm.org/online/Online-Assembler-and-Disassembler/?opcodes=E0976994E0B76994E0D76994E0F76994&arch=arm&endianness=big&dis_with_addr=True&dis_with_raw=True&dis_with_ins=True#disassembly). I also checked [this arm7tdmi reference](http://www.ecs.csun.edu/~smirzaei/docs/ece425/arm7tdmi_instruction_set_reference.pdf) (page 37) to make sure that these instructions exist on this processor. I've come across no documentation that these instructions might be broken on some processors, but I'm not setup to test this on real hardware.

**Comment by endrift** [comment]
This ended up being a disassembler bug, not a decoder bug, so it was only the textual output that was wrong.

**Comment by jeffayle** [comment]
fantastic, thank you for fixing that so fast!
