### ISSUE TITLE
fedora build doesn't link libGL

### ISSUE THREAD

**Issue by jiangzhengwenjz** [mgba-emu/mgba#1779]
OS: fedora 32
build: https://github.com/mgba-emu/mgba/commit/f11cb1c16bcd036227c970ee1ee3f2794a63509e

In order to link `mgba` and `mgba-qt`, we need `libGL` so `-lGL` should be passed in link.txt (generated by cmake). But it's not.

**Comment by endrift** [comment]
There is code in the CMakeLists for doing this. What is the output of CMake?

**Comment by jiangzhengwenjz** [comment]
It turns out to be my bad. Sorry for wasting your time.
