### ISSUE TITLE
Video doesn't update when reloading a save state

### ISSUE THREAD

**Issue by Liger0** [mgba-emu/mgba#1782]
Hi, when loading a save state on mgba 0.8.1, the video is not updated immediately. Instead, it needs you to advance of 3 frames, and between the 3 advancements the old and new images are overlapped with a different percentage.
It is a bit of a trouble when using save state to try to do a determinate action depending on the frame (although a frame counter isn't implemented, so manually thought) and video output.

**Comment by endrift** [comment]
What does the Shaders section of Settings say?

**Comment by Liger0** [comment]
"No shader loaded"

**Comment by endrift** [comment]
Is this still a problem in latest dev build?
