### ISSUE TITLE
[0.8.2] screen flickers when hold turbo key is pushed and a few seconds after releasing it

### ISSUE THREAD

**Issue by Liger0** [mgba-emu/mgba#1790]
When pressing the hold-for-turbo hotkey, the screen wobbles. It keeps doing so a few seconds after releasing it. 
This doesn't happen with fixed turbo
https://youtu.be/XmQsXFDzSeI

It never happened on older mgba versions.

**Comment by kode54** [comment]
Probably has to do with the multi-buffering and switching the buffering so that it can do unregulated frame output. I blame GPU drivers, if anything.

**Comment by endrift** [comment]
Do you have a high refresh rate monitor? What Hz is it running at?

**Comment by Liger0** [comment]
75 hz

**Comment by endrift** [comment]
Yes, I know things changed. But this is useful information for me to debug this. My high framerate monitor moved when I broke, so this is good to know. I guess I have to buy a new one.

**Comment by Liger0** [comment]
WIndows 10 build 2204 prompted out on my system, and I updated. Then I updated the  drivers since the new ones contained support for the 2204 build.
The result?
Now I haven't still faced this flickering issue in the 0.8.2, and I have faced it on 0.8.1 only once while not using turbo at all.
The other thing is, before updating, I had mgba 0.8.2 being twice as fast compared to 0.8.1, with 1650fps on the latest release and 800 fps in the old one in Pokemon emerald with turbo mode.
After updating windows 10 with the relative drivers, both releases lock at 800 fps now like it did on 0.8.1 only before, and the crashes mentioned in #1791 have also gone.
Not sure how all of those things are related, but this is all I can say.

**Comment by Liger0** [comment]
Updated to windows 10 build 2204, new drivers with 2204 support, and it still is happening with 75hz and amd drivers set to "use vsync unless the app uses a different setting"

**Comment by endrift** [comment]
Please let me know if the latest build (https://s3.amazonaws.com/mgba/mGBA-build-latest-win32.7z for 32 bit,  https://s3.amazonaws.com/mgba/mGBA-build-latest-win64.7z for 64 bit) fixes either this or #1791 (or both).

**Comment by kode54** [comment]
Here is a video of that 64 bit build, running Metroid Zero Mission intro loop, with me madly toggling the fast forward key. I can't even tell what I'm supposed to be looking for:

https://f.losno.co/v/metroid_ffwd.mp4

**Comment by endrift** [comment]
I _believe_ this is fixed (according to some users I queried online) in 4807d684825af75f16b19cd03a4dbbd6520f4a60. Closing, but will reopen if you find it's not.
