### ISSUE TITLE
[0.8.2] Keeps crashing

### ISSUE THREAD

**Issue by Liger0** [mgba-emu/mgba#1791]
0.8.2 keeps crashing. It happens while playing , but also a lot more when I click the cross to close the emulator.
It never crashed on older versions.

**Comment by endrift** [comment]
You really need to start putting information about your system in these bugs if you want them to be fixed.

**Comment by Liger0** [comment]
Win 10pro x64 v1909
Ryzen 5 1600
RX Vega 56

Ask if anything else is needed.

**Comment by Dimensional** [comment]
1. What were you doing when it crashed? Playing the game, loading the game, looking at settings?
2. What game were you attempting to play, if not already playing, when the emulator crashed?
3. Was it an official game or a rom hack?
4. What was it's checksum? You can find this by clicking on File and then selecting "ROM info.."
5. Were you doing anything else on your PC, like downloading games, watching videos, recording or streaming?

**Comment by Liger0** [comment]
The game is emerald jap, and the checksum is verified to be correct.
I was playing it, sometimes with another game in full screen (when it crashed during gameplay), the other in multiplayer instance with another game (when it crashed closing either game from the X).
It also crashed in single instance when closing with the X.

I have had like 10 crashes, but never crashed on mgba 0.8.1.

**Comment by PentiumMMX166** [comment]
mGBA Crashes randomly when i use the speedup (Mapped as R2 on my gamepad).

Problem Event Name:	APPCRASH
  Application Name:	mGBA.exe
  Application Version:	0.8.2.0
  Application Timestamp:	00000000
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.24384
  Fault Module Timestamp:	5c6e245d
  Exception Code:	c0000005
  Exception Offset:	000000000003fffd
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033

Specs:
CPU: AMD Athlon(TM) 64 X2 640 @ 3.00 GHz
RAM: 4.00 GB DDR2-800 RAM
GPU: PNY nVidia Geforce GTS 450 (Fermi) 1 GB GDDR5
HDD: Seagate Barracuda 500GB 7200RPM HDD, Seagate Barracuda 2TB 7200RPM HDD
OS: Windows 7 Ultimate x64

mGBA Version: 0.8.2

**Comment by endrift** [comment]
What are your settings? Both for Audio/Video and for Enhancements?

**Comment by PentiumMMX166** [comment]
all default, from when i downloaded it. 

Audio Driver - SDL
Audio Buffer - 1536 Samples
Sample Rate - 44100 Hz
Volume - Max
Fast Forward Volume - Max
Display Driver - OpenGL
Frameskip - 0
FPS target - 60 FPS

**Comment by Liger0** [comment]
Not sure if the fact that, in turbo mode, mgba 0.8.2 has double the speed of mgba 0.8.1 (with no frame limit) could be a cause of the instability when using turbo in the latest version.

**Comment by endrift** [comment]
As with #1790, I believe this is fixed in 4807d68. Closing, but will reopen if you find it's not.
