### ISSUE TITLE
Watchpoint labels are nonsense in 0.8.2

### ISSUE THREAD

**Issue by RetroEdit** [mgba-emu/mgba#1794]
Game shouldn't matter, but I'll mention it anyway. Here's what I did, in the game Super Mario Advance 4 - Super Mario Bros. 3 (CRC-32: `a44ba79f`).

```
> watch/w 0x03002AE0
 r0: 00000000   r1: 00000000   r2: 03002A40   r3: 00000001
 r4: 03002A40   r5: 03002240   r6: 0300761C   r7: 0000FFFE
 r8: 08120794   r9: 03003773  r10: 03002DBC  r11: 00000000
r12: 00000001  r13: 03007DDC  r14: 080AB9A7  r15: 0800072E
cpsr: 6000003F [-ZC---T]
0800072C:  1C18     	add r0, r3, #0
Added watchpoint #%I64i
```

It says it added watchpoint `#%I64i`, clearly not a standard number, perhaps the formatting for output wasn't escaped.

**Comment by endrift** [comment]
Did you build this yourself? What compiler? `%I64` is only used on Windows.

**Comment by RetroEdit** [comment]
Nah, I still can't build Qt.
