### ISSUE TITLE
Save issue with Dragon Ball Z: Legacy of Goku II

### ISSUE THREAD

**Issue by semecan** [mgba-emu/mgba#1797]
I have a weird save issue with Dragon Ball Z: Legacy of Goku II and tested two scenarios:

Scenario 1 - no existing save:
When I start playing the game normally and save, a save file is created.
When I restart the game, the save file seems not to be loaded, as there are only empty file in the save selection. Using "Load alternative save" does not work either.

Scenario 2 - existing save from a different emulator:
When putting a save from a different emulator into the folder, the save file does not seem to be loaded just like in scenario 1. But if I use "Load alternative save" to load the savegame, it loads and saves just fine. After saving and restarting mgba, I still need to use "Load alternative save" to use the save.

The save file created by mgba is 32kb in size, while the save file from the other emulator is 64kb in size. If needed, I can upload that save file.
Legacy of Goku I  and Buu's Fury work just fine.

My PC Specs: 
Windows 7 x64
AMD Phenom II X4 965
AMD Radeon HD 5850

**Comment by semecan** [comment]
Okay I just found the save type option in the "Game overrides" menu, when selecting "SRAM" instead of "autodetect" saving works properly. So I guess "autodetect" does not properly detect the save type for that rom.

**Comment by endrift** [comment]
I think you may have a hacked ROM. I'm pretty sure that game does not use SRAM.

**Comment by ketsuban** [comment]
Let's try to confirm that. @semecan Can you provide the SHA256 hash of your ROM? Does it match one of these?

```
a51382a23fbfba425074fc75821ac653b56134648c31ef80a26181e256a54925 *Dragon Ball Z - The Legacy of Goku II (Europe) (En,Fr,De,Es,It).gba
6e6c370c339ec9171cb1956adf837a0d342a197f78964882ef46c3086656ff75 *Dragon Ball Z - The Legacy of Goku II (USA).gba
b82ca939b0d574897d54feb840c87d161e097bfbdc69342af9d7af6734925165 *Dragon Ball Z - The Legacy of Goku II International (Japan).gba
```

**Comment by semecan** [comment]
No, the SHA256 hash of my rom is: `3a69df1d9e1ddac41ef9552e7c16590391cb36466423b8912783fc041436f83f`
I guess the roms I tested were SRAM patched roms, which seem to be quite common with that game.

**Comment by endrift** [comment]
Thanks for confirming. I might want to add a way to detect these SRAM patched games and switch to SRAM. Hm.
