### ISSUE TITLE
Real time clock setting on italian localization is broken

### ISSUE THREAD

**Issue by EddyHg80** [mgba-emu/mgba#1798]
![Annotazione 2020-06-19 133630](https://user-images.githubusercontent.com/9092453/85128603-e8607a80-b231-11ea-9255-3f831fea93cc.png)

Hey there's this problem with real time clock, only in the italian localization (I checked english, german and french and they are fine).
Also in game it doesn't work, even if I use one of the working languages above, it's always night.
It's strange because on VBA-M it actually works, so I think it's not the rom's fault.

**Comment by endrift** [comment]
We need an Italian translator to fix this, and the Italian translation as-is was a one-off.

**Comment by EddyHg80** [comment]
I can actually help out! I'm not a programmer but if you show me the files to edit I think I can try to contribute.

**Comment by RetroEdit** [comment]
Fixing the localization will only fix the text displayed.

In regards to RTC, it can be tricky for ROM hacks. Some ROM hacks were created using VBA as a reference, so they have bugs on more accurate emulators like mGBA and real-console.

As for what file contains the translated text, I think it's [src/platform/qt/ts/mgba-it.ts](https://github.com/mgba-emu/mgba/blob/master/src/platform/qt/ts/mgba-it.ts).
