### ISSUE TITLE
SMA4 e-Reader communication failure

### ISSUE THREAD

**Issue by RandomNumbersGuy** [mgba-emu/mgba#1800]
Hi. 

For the life of me, I cannot link together a USA e-Reader ROM with a USA Super Mario Advance 4 ROM (V 1.1) in two multiplayer windows without getting a "communication failure" every time. I understand the e-Reader functionality is still experimental, and it's very possible (likely, even) I'm doing something wrong, so I'm not too eaten up about it, but just thought I should let it be known, just in case.

Build is 0.9-6213-3f818f07.
![ed5dcfd21114d5cdc28acd63e34ffd58](https://user-images.githubusercontent.com/44385110/85190442-78c8aa80-b286-11ea-9be7-6f623e1865a0.png)

**Comment by endrift** [comment]
You're fine; this is definitely an mGBA bug. The linking code is pretty fragile right now.
