### ISSUE TITLE
Fast forward mute not turned off when unmuting through the Audio/Video dropdown.

### ISSUE THREAD

**Issue by mdx97** [mgba-emu/mgba#1801]
It seems commit 7246055 made an update to toggle fast forward mute along with regular muting. But, it was later changed in commit 77ab0ef to only ever turn fast forward muting _on_, but never off through that option (fixing a bug that caused fast forward muting to always be set off at startup).

Does this mean this function that handles the mute option is somehow being called on startup?

I discovered this in the official 0.8.2 release, but it looks like this code has not changed on master.

**Comment by mdx97** [comment]
So, I reverted the change made in 77ab0ef - and I'm not seeing the issue of it resetting the mute value whenever I start the program (that was reported in #1574).

I also checked out the 0.7.3 release, and built that locally (the version that the issue was originally reported in). I'm not seeing the issue happen there either. I'm using Windows 10 64-bit like the reporter was.

I have the reversion ready for PR on my fork if this is acceptable.

**Comment by SneakyLeif** [comment]
I'm using 0.8.3, and encountering this issue after binding Mute to a controller button in the Shortcuts sub-menu in Settings. After muting and unmuting once, the fast-forward mute option stays enabled. Any way to set the Mute Shortcut to unmute fast-foward mute as well as normal mute when toggling off?

**Comment by endrift** [comment]
@mdx97 I left a comment on your commit. I'll be OK merging it after that comment is addressed.

**Comment by endrift** [comment]
Looks like I accidentally included that version in the commit bbdbfaf34e48a9c3ff03c27abafe7aca6dbfd19c.
