### ISSUE TITLE
Spidersoft Pinball games do break the Emulator (mGBA standalone, Switch)

### ISSUE THREAD

**Issue by Instandhaltung** [mgba-emu/mgba#1803]
The Pinball games for the original GameBoy break the Emulator after a couple of moments ingame (seconds to a couple of minutes). This happens on all games afaik. The screen becomes scrambled and the game completely stops.
![2020062223464500-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/20743229/85339799-29cc8080-b4e5-11ea-81e2-9188f3c4f2d3.jpg)

Affected games:
- Pinball Dreams
- Pinball Fantasies
- Pinball Mania
- Pinball Deluxe

mGBA standalone 0.82 Switch

**Comment by endrift** [comment]
Duplicate of #271.
