### ISSUE TITLE
mGBA 0.8.2 takes a long time to start

### ISSUE THREAD

**Issue by thesuperdoge** [mgba-emu/mgba#1804]
Whenever i try to start the application, nothing happens.
There's only a background process running, but no window appearing.

**Comment by thesuperdoge** [comment]
apparently, it does start after a long time waiting. But it takes like actually 5 minutes before i see a window pop up

**Comment by endrift** [comment]
What OS are you on?

**Comment by thesuperdoge** [comment]
W10

**Comment by Testsr** [comment]
Tried mgba 0.8.2 on my Windows 10, and it starts up in the normal time you expect it to. Using Windows (64-bit archive).

**Comment by endrift** [comment]
I've had more than one person reporting this happening but I've never been able to reproduce it myself. And when I asked for help gathering information from people who could reproduce it I've only ever gotten the cold shoulder.

**Comment by lotharsm** [comment]
I'm also on Windows 10, never experienced such a delayed start. Maybe some antivirus snakeoil kicking in?

**Comment by endrift** [comment]
Following up on this, are you using the library feature? I've found it can slow down if you have a large library and have been planning to fix that.

**Comment by endrift** [comment]
I addressed the slowdown with the library feature in 405f12d1bdfd2d2ce239c2cf6e2fd6107f41066f, please retest.
