### ISSUE TITLE
Nintendo Switch mGBA remapping

### ISSUE THREAD

**Issue by SudoUser-Sam** [mgba-emu/mgba#1806]
is it possible to remap the x button which is the mgba menu to something else? 

i checked the config and even the github for any clues to what i could define the menu button to in the config but came up short.

I'd like to change it from x to the start button for the menu (basically flipping the map)

**Comment by endrift** [comment]
It should be possible to do this in the remapping section under interface keys.

**Comment by TyMiles2012** [comment]
I had this issue on Wii but maybe it'll work for you.  You want to change the Cancel key under interface keys.  I noticed Cancel was mapped to Home on WiiRemote which also opened the menu, so I tried that and that solved my issue.

**Comment by endrift** [comment]
Closing because this was never actually missing.
