### ISSUE TITLE
[Wii] Mr. Driller games show corrupted graphics.

### ISSUE THREAD

**Issue by Maesejesus** [mgba-emu/mgba#1808]
These games (Mr. Driller 2 and Mr. Driller Ace) worked phenomenally before 0.8.2, the latest one I have is a 0.8.1 nightly from March.

![Mr  Driller 2-1](https://user-images.githubusercontent.com/21066817/85562618-f268eb80-b62c-11ea-986f-6ceb25633382.png)
![Mr  Driller 2-0](https://user-images.githubusercontent.com/21066817/85562623-f39a1880-b62c-11ea-8ea6-3b8d9ce58f14.png)

I don't know if they also have issues in other platforms or if there are more games that now have this issue (I have not gone through all my games), though.

PS: Thanks for fixing that other glitch about palettes some time ago. I didn't thank you back then... I kinda forgot with how the world is going right now.

**Comment by endrift** [comment]
Definitely broken on PC too.

**Comment by endrift** [comment]
Regressed in 8ab757e1b37049e7e4ae295aabec7bd3061975ed, somehow. A workaround in the meantime is to use the official BIOS.
