### ISSUE TITLE
Play fullscreen, without the Arcade Console graphics

### ISSUE THREAD

**Issue by paoloalby** [mgba-emu/mgba#1811]
Is there any way to play fullscreen, removing the arcade console all around the game?

I'm playing mgba on Nintendo Switch

**Comment by endrift** [comment]
I have no idea what arcade console you're talking about. What game?

**Comment by paoloalby** [comment]
Donkey Kong rom for example, as you can see, it's "inside" an Arcade Console and not full screen. 

![donkey kong](https://user-images.githubusercontent.com/15869726/86438398-c1607900-bd06-11ea-9ab4-dc34c7d66f98.jpg)

**Comment by endrift** [comment]
Oh, that's the SGB border. You can turn off SGB borders in settings.

**Comment by paoloalby** [comment]
Oh good!
How can I access to Settings in Nintendo Switch mgba.nro ?

**Comment by endrift** [comment]
By default it's the X key, and there should be a section labeled something like settings or configuration.
