### ISSUE TITLE
[Request] Making sav Files compatible with flashcarts

### ISSUE THREAD

**Issue by RunisDauphin** [mgba-emu/mgba#1812]
Hi, I am Runis Dauphin from Rebelles Unis:

I bought back in January 2020 a flashcart for Game Boy Advance games (more exactly, it was the EZ-Flash Omega). I supposed that, more or less like my R4iSDHC, it would allow me to play in some way my Game Boy Advance files from the cart in the PC and back to the cart. And I was right: VBA-RR and the flashcart can open each other's sav File without importing/exporting; just by dragging and dropping.

The problem is that mGBA is not able to read DIRECTLY from the flashcart (neither drag from the cart and drop on the sav Files directory or importing/exporting them through the emulator; the other way around does not work either). The way I must follow right now is drag the sav File from the cart, open the game on VBA-RR with the sav File dropped, save the sav File again on VBA-RR and then open the game on mGBA with this new sav File. If I want to play again on my GBA SP or Nintendo DS Lite, I simply have to follow the same procedure in the reversed order (save on mGBA, open on VBA-RR, save on VBA-RR and drop onto the cart).

I have not tried Game Boy or Game Boy Color yet, and they do not run natively in this kind of carts (for example, both EZ-Flash Omega and Everdrive GBA X5 use Goomba as Game Boy and Game Boy Color emulator), and I ignore how compatible are already those sav Files with mGBA, VBA-RR or any other emulator, for that matter.

Thanks for your attention.

Runis Dauphin, chef et administrateur de Rebelles Unis.

P.D.: I know I have mentioned it already in other issues, but mGBA and VBA-RR can open each other sav Files without importing/exporting: just save on one emulator, copy that sav File to the other emulator's sav Files directory and open said game.

**Comment by endrift** [comment]
Please provide an example save file and tell me which game it's for.

And also you really don't need to introduce yourself every single bug. Or at all. They're bug reports, not personal letters.

**Comment by RunisDauphin** [comment]
I send you a file I am using for Sonic Battle (USA). I have the habitude of renaming them "Console abreviation" Name of game (Region in Spanish).format.

So this file is called GBA Sonic Battle (Estados Unidos).gba (original file Sonic Battle (USA).gba).

[Demo file.zip](https://github.com/mgba-emu/mgba/files/4837461/Demo.file.zip)

Refering to your point about the letters, I do it this way trying to be nice and keep a bit of courtoisie, but, if you do not like it, I can stop doing it.

Hope this can be implemented. When I play in some computers (that do not let me enter as an administrator) I can not use VBA-RR because someone forgot/did not want to install DirectX9 (and as such VBA-RR won't start), and I can not play the files from the console on the PC (where I make exchanges/cloning with the savefiles).

Thanks for your work, and keep it up.

**Comment by endrift** [comment]
The save appears to work fine for me, assuming I give it the correct name.

**Comment by RunisDauphin** [comment]
OK, I am going check it soon. Last time I tried I think it was on v0.8.0.
Sorry for the delay on the answer, heat is definitely not good for health.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by RunisDauphin** [comment]
Recently checked on mGBA 0.8.2.

Veredict?: Works flawlessly, savefile loaded no probleme whatsoever.
