### ISSUE TITLE
[0.8.2] Debugger watchpoint hitting/setting output contains junk format string

### ISSUE THREAD

**Issue by karmic64** [mgba-emu/mgba#1816]
Noticed recently that watchpoints have been given incremental identifier numbers instead of being directly tied to the address that triggers them. Great feature, but the output of the debugger is now wrong:

For example, entering `watch/w $2000000` now prints:

`Added watchpoint #%I64i`

And when it hits, it prints:

`Hit watchpoint %I64i at 0x00000001: (new value = 0x02000000, old value = 0xFFFFFFC0)`

The format string that is meant to contain the watchpoint number is not interpreted as such, so as a result all of the displayed numbers are "shifted" to the right, and the actual old value of the address is not displayed at all.

Using 64-bit Windows 10.

**Comment by RetroEdit** [comment]
Duplicate of #1794.

**Comment by karmic64** [comment]
OK, missed this. Thanks.
