### ISSUE TITLE
Cycle-count display is a junk format string (Windows)

### ISSUE THREAD

**Issue by RetroEdit** [mgba-emu/mgba#1817]
I happened to open up a recent mGBA (specifically, `0.9-6257-cdf9105f56182a207662c93da1e7a3a7f6bb2040`) for some testing. I noticed cycle count had been added to the debugger. However, it just displays as `%I64u` on Windows.

This looks like a similar type of issue as #1794.

**Comment by endrift** [comment]
That shouldn't be possible...I don't use that format string anymore. I wonder what's going on.
