### ISSUE TITLE
Error in THUMB mode SBC carry flag setting

### ISSUE THREAD

**Issue by DenSinH** [mgba-emu/mgba#1818]
I wrote a [test ROM generator (fuzzer) ](https://github.com/DenSinH/Random) for the GBA, and generated some ROMs with it. Running them on mGBA shows that the way you determine your carry flag in THUMB SBC instructions does not always work. Below is the error my generated test ROM gives:

![image](https://user-images.githubusercontent.com/25347040/87256555-06697580-c494-11ea-82f7-fb3a72ed75a7.png)

The test shifts `r1` by `r2`, stores it in `r3` (clearing the carry flag), then the SBC instruction is called (`SBC r4, r3`), which should have the carry flag cleared as output. [YetAnotherEmuDev](https://github.com/YetAnotherEmuDev) confirmed it, in your [THUMB mode SBC carry flag checking](https://github.com/mgba-emu/mgba/blob/f6522ea08468cea5c18784a948db145c8bb7f316/src/arm/isa-thumb.c#L206), `n` overflows, and is then used for calculating the flag.

By the way, the ROM was tested on hardware, and it passed, just to be clear. I hope this helps!

By the way, if you want to check this for yourself, the ROM that showed this particular issue is still in the repo, but really any ROM you generate with it with enough test cases will show this issue.

Also, the way you set it for ARM ADC/SBC/RSC instructions seems to be correct, so it should be an easy fix!

**Comment by endrift** [comment]
It was indeed an easy fix. I actually have tests for it, but only in ARM mode!
