### ISSUE TITLE
mGBA stutters with OBS

### ISSUE THREAD

**Issue by ROMaster2** [mgba-emu/mgba#182]
https://www.dropbox.com/s/sqknmgdw6bu3hz5/stream.mp4?dl=1

I was trying to make a video for testing input delay, but each time I start to record it began to stutter. Not sure why.

**Comment by Krak-n** [comment]
If this is occurring with a Qt build, it may be related to: #181?

**Comment by endrift** [comment]
Could be, although @guineawheek is on Ubuntu, not Windows.

**Comment by Krak-n** [comment]
Would it be possible to test a SDL build of mGBA on Windows to see if the issues persist?

I'm busy at the moment and can't test it myself. However if I don't see an update I'll run tests for both Windows and Linux when I get home.

**Comment by Krak-n** [comment]
Finished testing on Arch. Apologies for the delay:
* https://u.teknik.io/iymwPr.mp4

No noticeable lag when built from master. @ROMaster2 If you test the latest nightly, are you still experiencing any lag when running OBS?

Going to test them on windows, but needed to dump my first tests here.

**Comment by ROMaster2** [comment]
I'm currently using 0.3.1 release.

I don't know; Maybe there's something up with my settings. I'll have to do some more testing.

**Comment by ROMaster2** [comment]
This seems to have fixed itself, at least mostly. OBS Studio very rarely stutters now with mGBA running.

**Comment by endrift** [comment]
Wonder what the issue was. Glad to hear it's not an issue anymore.
