### ISSUE TITLE
Pokémon Emerald Audio Issue

### ISSUE THREAD

**Issue by xnaas** [mgba-emu/mgba#1820]
Here's a [YouTube video](https://www.youtube.com/watch?v=zhP2IydlBXY) illustrating the audio issue.

The issue is only present on the `FIFO Channel A` and `FIFO Channel B` audio channels. The four `PSG` audio channels are fine.

This mostly only seems to be an issue in the opening scene with the professor. Doesn't really happen outside of that that I've noticed.

-----

Additional info:

mGBA version: 0.8.2
PC specs: https://pcpartpicker.com/user/xnaas/saved/CTBWGX

FWIW, this same audio issue appears in ares and VBA-M as well.

**Comment by endrift** [comment]
Can you please explain the issue? I'm not sure I'm understanding exactly what the issue is.

**Comment by xnaas** [comment]
Do you not hear the clicking in the background in the video?

**Comment by endrift** [comment]
My laptop is kind of quiet and it wasn't obvious. Have you confirmed that it doesn't happen on hardware?

**Comment by xnaas** [comment]
Here's a second example with the PSG audio channels filtered out and only the FIFO audio channels present: [youtube link](https://www.youtube.com/watch?v=sakudbgyY44)

**Comment by xnaas** [comment]
I don't hear the noise on my Game Boy Micro either through the speakers or with wired headphones plugged in.

**Comment by xnaas** [comment]
I don't know if an MVL is useful or not for audio, but...

[emerald-video-debug-log.mvl.zip](https://github.com/mgba-emu/mgba/files/4945174/emerald-video-debug-log.mvl.zip)

**Comment by endrift** [comment]
No, mVLs are video only. I'll take a look sometime later. Not right now though.

**Comment by xnaas** [comment]
Fair enough. I'm sure there's plenty of actually important things to look into lol

**Comment by vaguerant** [comment]
I was asked in IRC if I could record this on hardware to see whether it occurs there. Here's the resulting file as recorded from a DS Lite. I personally cannot hear the audio artifacts demonstrated in @xnaas's videos.

https://cdn.discordapp.com/attachments/424654243199320066/735020115598508072/PokemonEmerilBam.m4a

**Comment by endrift** [comment]
Either I'm deaf or I can't hear this on latest master. Can you retest this?

**Comment by xnaas** [comment]
Even on 0.8.4 this sounds worlds better: [Streamable video](https://streamable.com/igw5qf)

Whatever changes happened between 0.8.2 and 0.8.4 must've been adequate. 😃
