### ISSUE TITLE
The New Addams Family Series (E) [CGB] crashes in the intro cutscene

### ISSUE THREAD

**Issue by GerbilSoft** [mgba-emu/mgba#1821]
After selecting one of the two languages (either language), the first cutscene plays, which locks up after the first lines of dialog are displayed.

- mGBA build: git master (5b319cfd91fff2fcd3df0e1fce3e498454796da0)
- ROM: The New Addams Family Series (E) [CGB]
- ROM MD5:  2d2a8314f789d490bf83ed3c44538fe3

**Comment by endrift** [comment]
Seems to happen in every emulator I've tried, including SameBoy (cc @LIJI32) and bgb.

**Comment by endrift** [comment]
Turns out you have to press down to advance the dialog. Very unintuitive. That works everywhere though.
