### ISSUE TITLE
[Flickering and graphical glitches] Advance wars 1 and 2

### ISSUE THREAD

**Issue by cjlaborde** [mgba-emu/mgba#1823]
![flickering5](https://user-images.githubusercontent.com/40572114/88260897-46e6a180-cc93-11ea-9d14-0cfefb7e56f0.gif)
Here is another problem 

> > ![mgbaAW2](https://user-images.githubusercontent.com/15524479/84745800-1704f980-af83-11ea-860f-64e1f94c4c5d.gif)
> > Not sure if this is the exact same issue, but I ran into this with Advance Wars 2 dialogue. The issue persists whether or not I have interframe blending or sync to video enabled (in the gif both are enabled).
> 
> I have same issue with advanced wars
> ![flickering3](https://user-images.githubusercontent.com/40572114/88259933-56fd8180-cc91-11ea-9c3a-bf7b2cb96945.gif)

I am using Retoarch with MGBA on linux.
Issue seems to be happening more often when there is Dialog text at the top of the screen.

@tnelling Seems to have same issue.

**Comment by endrift** [comment]
Retroarch huh. I believe they're currently basing off of mGBA 0.8.2.

**Comment by cjlaborde** [comment]
Here are my specs
![image](https://user-images.githubusercontent.com/40572114/88261698-c88aff00-cc94-11ea-8b65-e26ebfc2d8b0.png)

**Comment by tnelling** [comment]
When I encountered the issue, I was running mGBA 0.8.1 on Windows

**Comment by cjlaborde** [comment]
I am using VGA-M now and doesn't have this issue.
Seems VGA had issues with Advance Wars 2 in the Past but they fixed it as in mentioned in the screenshot below.
https://emulation.gametechwiki.com/index.php/Game_Boy_Advance_emulators
![image](https://user-images.githubusercontent.com/40572114/88263412-00477600-cc98-11ea-9fbe-8eef9d9ad152.png)

**Comment by endrift** [comment]
It doesn't actually mention what issues it had though. (Also it's VBA, not VGA.)

**Comment by endrift** [comment]
Regressed in 223be49e7845327997a5258338cf6eb6190b475f. That should mean you can use a real BIOS to temporarily work around the issue.

**Comment by endrift** [comment]
It doesn't look like I'll be able to fix this in 0.8.3 (or 0.8.x at all), so I'm retargeting it for 0.9.0 (as a blocker)
