### ISSUE TITLE
[New 3DS] Zelda ALTTP - Sound glitches and low framerate when alternating between dark and light worlds

### ISSUE THREAD

**Issue by andrebrait** [mgba-emu/mgba#1826]
Hi there.

First of all, thanks for this port for the 3DS. It's the best emulator in terms of graphics so far. My only issue with it so far has been sound emulation, particularly in Zelda ALTTP/Four Swords, when playing ALTTP and alternating between light and dark worlds.

I am using a patched ROM (voice removal patch), but it runs well in other emulators _and_ on the real hardware (I have a NDS Lite and an EzFlash 3in1 in which I used to play the game), so it might be interesting to see what's happening there.

I'm attaching a save file so you can easily reproduce it. Just press `select` and choose the magic mirror. Then press `A` to alternate to the light world. When in the light world, a shiny thing on the ground (which will appear where you switched to it) will allow you to go back to the dark world.

The file below is the save game only.
[Legend of Zelda, The - A Link to the Past & Four Swords (USA) (Voice Removal 0.1).zip](https://github.com/mgba-emu/mgba/files/4973576/Legend.of.Zelda.The.-.A.Link.to.the.Past.Four.Swords.USA.Voice.Removal.0.1.zip)

**Comment by endrift** [comment]
What other emulators? This is almost certainly just mGBA slowing down due to the 3DS being too weak.

**Comment by andrebrait** [comment]
Well, on the N3DS, specifically, the gpsp core on RetroArch handles this part just fine. But yeah, maybe it's just because it's less accurate/demanding.

**Comment by endrift** [comment]
Yes, gpSP is both less accurate and less demanding. I'd recommend turning on the FPS counter to see what it says during the sound issues.

**Comment by andrebrait** [comment]
Yes, FPS does go down while the animation is playing. Too bad. Otherwise this is the best emulator I could find.

I'll try it on my Vita and see how it fares there. I try to play Nintendo games on Nintendo consoles but maybe the Vita will just become "the one" for everything I have.

**Comment by endrift** [comment]
Generally mGBA is slower on Vita than on N3DS. I'll keep trying to make it faster, but the hardware will only let me get away with so much.
