### ISSUE TITLE
Final Fantasy VI Graphics Issues Caused by 6261-007baef

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#1827]
As of this build, various things are broken.  Vertical Scrolling Layers appear to be offset by some amount resulting in graphical glitches.

007baef

![image](https://user-images.githubusercontent.com/6598209/88474843-7f3ae980-cef8-11ea-974f-10e0cd28912d.png)

![image](https://user-images.githubusercontent.com/6598209/88474846-8bbf4200-cef8-11ea-99c3-9f8343419919.png)

9295c3c89

![image](https://user-images.githubusercontent.com/6598209/88474812-1e131600-cef8-11ea-8f1e-3a826dce47f1.png)

![image](https://user-images.githubusercontent.com/6598209/88474807-12bfea80-cef8-11ea-8559-a0990f5090e1.png)

**Comment by endrift** [comment]
CC @DenSinH, who reported the bug that commit fixed.

**Comment by DenSinH** [comment]
I just noticed I got tagged, but I see it's fixed already

**Comment by endrift** [comment]
Yeah, I thought the bug might be some unexpected fallout from the change or error in your test somehow. Turns out it was just a small bug in the change. Apologies for the noise.
