### ISSUE TITLE
Cheats wont work when playing Metroid Zero Mission

### ISSUE THREAD

**Issue by CommicKick69ing** [mgba-emu/mgba#1828]
I trying to use an invisibility cheat, but not matter wht website I go to no matter how may codes I use none work for some reason I s this some type of bug with the emualor?

**Comment by endrift** [comment]
This is a support request, not  bug, given how fucking terrible code sites are. Please tell me the codes in question.

**Comment by CommicKick69ing** [comment]
Infinite Health | 83001536 0513
https://megalixir.cc/gba/metroid-zero-mission/

**Comment by Cibomatto2002** [comment]
Here is some codes I use in the game.
![Capture](https://user-images.githubusercontent.com/21169038/88759834-38840400-d131-11ea-9bae-7eba2b64f8fc.jpg)

**Comment by endrift** [comment]
Why do you have the infinite health cheat in there twice?

**Comment by Cibomatto2002** [comment]
i'm not sure. LOL i need to delete one.

**Comment by endrift** [comment]
The code works for me with a USA ROM. It's probably not compatible with whatever version of the game you're using.

**Comment by Cibomatto2002** [comment]
You maybe right. Thanks for your time.
