### ISSUE TITLE
A frame of graphical garbage appears after skipping the first cutscene in Broken Circle (Europe) (En,It) (Unl)

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#1829]
Skip the opening cutscene and a frame of garbage will appear. Tested with all settings default. Also tested in VisualBoyAdvance-1.7.2 and it doesn't happen. I recorded a webp of it.

[broke.zip](https://github.com/mgba-emu/mgba/files/4982724/broke.zip)

**Comment by endrift** [comment]
I am able to reproduce this on hardware, so it doesn't appear to be a bug in mGBA.
