### ISSUE TITLE
Mute option

### ISSUE THREAD

**Issue by Q3CPMA** [mgba-emu/mgba#183]
I think there should be a bindable (and visible in the Qt menu) option to mute audio.

**Comment by Q3CPMA** [comment]
Well, I made a little something:
[code]
From 249fe44205b4045f8ded075871e9ab5bc8c6e6dc Mon Sep 17 00:00:00 2001
From: john Carmack <johncarmack@cock.li>
Date: Tue, 1 Dec 2015 23:35:23 +0100
Subject: [PATCH] Add mute/unmute

---
 src/platform/qt/Window.cpp | 16 +++++++++++++++-
 1 file changed, 15 insertions(+), 1 deletion(-)

diff --git a/src/platform/qt/Window.cpp b/src/platform/qt/Window.cpp
index ece84cb..5691550 100644
--- a/src/platform/qt/Window.cpp
+++ b/src/platform/qt/Window.cpp
@@ -1140,7 +1140,21 @@ void Window::setupMenu(QMenuBar* menubar) {
 	enableChB->setChecked(true);
 	connect(enableChB, &QAction::triggered, [this, i](bool enable) { m_controller->setAudioChannelEnabled(5, enable); });
 	addControlledAction(audioChannels, enableChB, QString("enableChB"));
-
+	
+	audioChannels->addSeparator();
+	
+	QAction* enableAllCh = new QAction(tr("Mute/Unmute all"), audioChannels);
+	enableAllCh->setShortcut(tr("Ctrl+m"));
+	enableAllCh->setCheckable(true);
+	enableAllCh->setChecked(true);
+	connect(enableAllCh, &QAction::triggered, [this, i](bool enable) {m_controller->setAudioChannelEnabled(0, enable);
+																	  m_controller->setAudioChannelEnabled(1, enable);
+																	  m_controller->setAudioChannelEnabled(2, enable);
+																	  m_controller->setAudioChannelEnabled(3, enable);
+																	  m_controller->setAudioChannelEnabled(4, enable);
+																	  m_controller->setAudioChannelEnabled(5, enable); });
+	addControlledAction(audioChannels, enableAllCh, QString("enableAllCh"));
+	
 	QMenu* toolsMenu = menubar->addMenu(tr("&Tools"));
 	m_shortcutController->addMenu(toolsMenu);
 	QAction* viewLogs = new QAction(tr("View &logs..."), toolsMenu);
-- 
2.6.2
[/code]

I have no idea how to do a pull request.

**Comment by endrift** [comment]
This won't do a proper mute, it just turns on or off the channels. There's a setting for muting that does a "master" mute that you might want to use instead, and is stored on exit or start.

**Comment by Q3CPMA** [comment]
Sorry, never did anything Qt (or anything on this project ever). Just did "monkey see, monkey do".

**Comment by endrift** [comment]
I can try to take a poke at this soon, it was getting frustrating doing this in the settings dialog.

**Comment by Q3CPMA** [comment]
Heh, didn't even see it in the settings window.

**Comment by endrift** [comment]
Fixed in e0863dc708d4d16d4047adb000c4ee65ab4130ed.
