### ISSUE TITLE
[Wii] Interframe blending forces texture filtering

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#1830]
When using frame blending with the pixel-accurate screen mode and the filtering is set to pixelated, there is noticeable blurring on the screen, normally this isn't a problem when using 480i/p modes where non-integer scaling is usually preferred but in 240p mode it becomes more of a problem.

I don't understand why it's happening but it's like it's prescaling to an incorrect size so in integer scales it still blurs.

Because of this it might be better to disable texture filtering when using this setting.

**Comment by endrift** [comment]
Does this happen with GB/C and GBA? Or just one?
