### ISSUE TITLE
Emulator fails to render picture with OpenGL on Wayland compositor

### ISSUE THREAD

**Issue by kode54** [mgba-emu/mgba#1837]
And it runs impossibly slowly at the same time if the OpenGL enhancements are turned on. @endrift indicated that this is an issue with the OpenGL context handling in the Qt frontend, and that a rework or rewrite of this code is a blocker for 0.9, after some other more pressing issues.

Running this with the enhancements turned on can make games take so long to actually start producing sound, the emulator may seem to be locked up, but it's not. It probably will segfault if you load another game or quit it, though.

As a workaround, anyone experiencing this issue and wishing to use the OpenGL renderers, can run `mgba-qt` with the correct environment variable set:

```
env QT_QPA_PLATFORM=xcb mgba-qt
```

**Comment by endrift** [comment]
Please retest in 74edd96 or newer.

**Comment by Testsr** [comment]
@kode54 Are you going to test this?

**Comment by endrift** [comment]
He relayed on Discord that it wasn't fixed. I guess the bug didn't get updated.

**Comment by endrift** [comment]
I've been trying to debug this for the past few hours and have no clue what's going on. It seems like it might be a Qt bug, but I'm not really sure what to do about it. I asked in #dri-devel on FreeNode, but no one really replied. I might try again later.

**Comment by kode54** [comment]
It doesn't appear to be a wlroots bug, at least, as you were also testing KDE, right? I saw that conversation, didn't know what to add to it.

**Comment by endrift** [comment]
Yes, I was testing in KDE Plasma. I didn't realize you were in that channel.

**Comment by kode54** [comment]
This bug is different now. Maybe. I know it affects Wayfire, but not Sway. So there's that.

**Comment by kode54** [comment]
Closing this as it only affects one wlroots compositor, and I only know of one wlroots compositor that lets you use overlapped and freely resizable windows. As I have given up on using this compositor in favor of using the Linux/freedesktop singularity, Gnome, this is no longer relevant to me.
