### ISSUE TITLE
Inaccuracy in Golden Sun

### ISSUE THREAD

**Issue by Q3CPMA** [mgba-emu/mgba#184]
![Golden Sun screenshot] (https://madokami.com/te6k3b.png)

The little ripples on the water are the background 1 video channel, but they're drawn on top of the sprite one. Maybe it's an ingame bug, but it looks pretty strange.

**Comment by Q3CPMA** [comment]
Another one that looks like a bug to me:
![Golden sun video](https://madokami.com/18y56o.mp4)

Look at the contact pixels between the block and the adjacent wall.

**Comment by endrift** [comment]
Can you upload a savestate or savegame in this dungeon?

**Comment by Q3CPMA** [comment]
Ok.

**Comment by endrift** [comment]
I have confirmed that both of these bugs occur on real hardware as well.
