### ISSUE TITLE
Some windows can't be clicked the X button to close in WIN 7

### ISSUE THREAD

**Issue by leoxxx** [mgba-emu/mgba#1843]
Such as "Settings...", "Game Pak sensors...".
They can be used Alt+F4 & Esc to close.

**Comment by endrift** [comment]
I can reproduce. Seems like a Qt bug. I'll look into it.

**Comment by endrift** [comment]
Fixed in mgba-emu/dependencies@84ca410a5f442f34aede398ada5bfdb479236b5a (it was indeed a Qt bug, so I upgraded Qt)
