### ISSUE TITLE
[Feature Request] Support D3D in Windows & Vulkan, please

### ISSUE THREAD

**Issue by leoxxx** [mgba-emu/mgba#1844]
As shown in the title.

**Comment by endrift** [comment]
Find me some devs willing to do this and maybe I'll consider it.

**Comment by leoxxx** [comment]
@unknownbrackets
Excuse me, can you help this project?

**Comment by wabberz** [comment]
Not sure why you pinged me, I thought you were joking with the request. I trust that endrift knows what they're doing, if D3D or Vulkan would improve anything, I'm sure it would be there alread, so I doubt it's the bottleneck in any scenario.

**Comment by leoxxx** [comment]
> 
> 
> Not sure why you pinged me, I thought you were joking with the request. I trust that endrift knows what they're doing, if D3D or Vulkan would improve anything, I'm sure it would be there alread, so I doubt it's the bottleneck in any scenario.

I think you are interested in it. D3D is supported in VBA.(No Vulkan at that time)  I think D3D & Vulkan is better than OpenGL.
Now you said you think it's a joking. So ignore it.

**Comment by wabberz** [comment]
Define "better". I don't think it makes much if any difference here. And no, I actually thought you were joking, since Vulkan for GBA sounds like overkill.
