### ISSUE TITLE
A Chinese translation error

### ISSUE THREAD

**Issue by leoxxx** [mgba-emu/mgba#1845]
Frame size="画面大小" or "窗口大小"
So, "帧率" is a translation error. It's not "frame rate".

**Comment by endrift** [comment]
cc @EmpyreusX, who did most of the work on that translation.

**Comment by tommai78101** [comment]
Note: The file to change is located here:

https://github.com/mgba-emu/mgba/blob/386b788956da824036574fd445e2efd59d9afba6/src/platform/qt/ts/mgba-zh_CN.ts#L4105

**Comment by endrift** [comment]
If @EmpyreusX doesn't reply soon I'll probably do the fix myself. It sounds like 窗口大小 would be closer since it's adjusting the size of the window, not the whole screen (at least, according to what I'm getting out of Google translate)

**Comment by leoxxx** [comment]
You are rigth. It's not whole screen.The "画面" that means the screen area in the emulator, not whole screen. So "画面"="窗口" here.
Either of them can be uderstood by Chinese. Maybe "窗口大小" is more understandable.

**Comment by leoxxx** [comment]
You are right. It's not whole screen.The "画面" that means the screen area in the emulator, not whole screen. So "画面"="窗口" here.
Either of them can be uderstood by Chinese. Maybe "窗口大小" is more understandable.

**Comment by leoxxx** [comment]
You are right. It's not whole screen.The "画面" that means the screen area in the emulator, not whole screen. So "画面"="窗口" here.
Either of them can be uderstood by Chinese. Maybe "窗口大小" is more understandable.

**Comment by leoxxx** [comment]
You are right. It's not whole screen.The "画面" that means the screen area in the emulator, not whole screen. So "画面"="窗口" here.
Either of them can be uderstood by Chinese. Maybe "窗口大小" is more understandable.

**Comment by leoxxx** [comment]
You are right. It's not whole screen.The "画面" that means the screen area in the emulator, not whole screen. So "画面"="窗口" here.
Either of them can be uderstood by Chinese. Maybe "窗口大小" is more understandable.

**Comment by leoxxx** [comment]
You are right. It's not whole screen.The "画面" that means the screen area in the emulator, not whole screen. So "画面"="窗口" here.
Either of them can be uderstood by Chinese. Maybe "窗口大小" is more understandable.

**Comment by leoxxx** [comment]
You are right. It's not whole screen.The "画面" that means the screen area in the emulator, not whole screen. So "画面"="窗口" here.
Either of them can be uderstood by Chinese. Maybe "窗口大小" is more understandable.

**Comment by leoxxx** [comment]
You are right. It's not whole screen.The "画面" that means the screen area in the emulator, not whole screen. So "画面"="窗口" here.
Either of them can be uderstood by Chinese. Maybe "窗口大小" is more understandable.

**Comment by leoxxx** [comment]
You are right. It's not whole screen.The "画面" that means the screen area in the emulator, not whole screen. So "画面"="窗口" here.
Either of them can be uderstood by Chinese. Maybe "窗口大小" is more understandable.

**Comment by leoxxx** [comment]
You are right. It's not whole screen.The "画面" that means the screen area in the emulator, not whole screen. So "画面"="窗口" here.
Either of them can be uderstood by Chinese. Maybe "窗口大小" is more understandable.

**Comment by leoxxx** [comment]
You are right. It's not whole screen.The "画面" that means the screen area in the emulator, not whole screen. So "画面"="窗口" here.
Either of them can be uderstood by Chinese. Maybe "窗口大小" is more understandable.

**Comment by leoxxx** [comment]
You are right. It's not whole screen.The "画面" that means the screen area in the emulator, not whole screen. So "画面"="窗口" here.
Either of them can be uderstood by Chinese. Maybe "窗口大小" is more understandable.

**Comment by EmpyreusX** [comment]
Well, it's just a typo here. "Frame size" indeed means "帧大小" or "画面大小" in Chinese, but "帧大小" is relatively more accurate and common. "窗口" are apparently unsuitable in this case. I will fix that ASAP.

**Comment by leoxxx** [comment]
> Well, it's just a typo here. "Frame size" indeed means "帧大小" or "画面大小" in Chinese, but "帧大小" is relatively more accurate and common. "窗口" is apparently unsuitable in this case. I will fix that ASAP.


> frame
美 [freɪm]
英 [freɪm]
n.帧；支架；骨架；画面
v.给…做框；给…镶边；作伪证陷害；制订
adj.〈美〉木造的
网络框架；车架；边框

@EmpyreusX   @endrift 

This is bing's translation. Althoug "帧"="画面", If it's "帧"，Chinese will think it's a screen unit. Actually it's adjusting the size of the emulator's window. So endrift's translation is right and EmpyreusX's translation is wrong.
I'm a Chinese.

**Comment by endrift** [comment]
Wouldn't you know it, EmpyreusX is also Chinese. Being condescending isn't going to help anything here.

**Comment by leoxxx** [comment]
@
No, I don't know. Not condescending. Just tell you what's the right. 
If you think it's the condescending, please delete my issue. And I'll never comment.

**Comment by EmpyreusX** [comment]
I think I'm kind of stubborn in this argument.
"帧大小" is generally a professional terminology used in filmmaking or video production, but it will easily lead to misunderstanding of what it actually stands for in mGBA.
After further investigations to `Window.cpp` and `mgba-ja.ts` (Japanese localized Qt Linguist file, where "Frame size" is translated to "画面サイズ"), "画面大小" might seem like a eclectic choice.

**Comment by leoxxx** [comment]
@EmpyreusX
endrift 说你是中国人，那我就用中文说一下。我无意冒犯开发组的各位，上述言论不是来显摆我是中国人，只对这个词现行翻译会造成中国人的误解。上面我也表理了帧和画面可以表达为一个意思。我个人认为画面大小或者窗口大小比较贴近实际。你上述评论中也说了帧是个专业名词容易造成误解，日语直接翻译成画面大小。（我英语不是很好，不知道你上述的发言是否理解正确，如有误望指正）。
另外询问一下设置中的“允许逆向输入”是什么？实际功能我没试出来，可以的话麻烦你用中文和英语都描一下这个功能的作用，先谢为敬。

**Comment by endrift** [comment]
Just to confirm, are you both agreed now that 画面大小 is a suitable translation?

**Comment by EmpyreusX** [comment]
@endrift Yes.

**Comment by EmpyreusX** [comment]
@leoxxx ”允许逆向输入“是一个特殊功能。在同时按下相反方向的方向键（例如向左和向右键）时，mGBA会对这一行为进行特殊处理，例如触发《合金弹头A》的崩溃BUG（具体可以参考 #1191 中的解释）。由于在实际的 GBA 主机上进行这项操作不会有任何反应，所以这项功能使用较少。
同时多谢指出另一个翻译错误，这是之前的贡献者翻译的，这里应该翻译成”允许反方向输入“。

**Comment by leoxxx** [comment]
I see.

**Comment by EmpyreusX** [comment]
> I see.I think "相对的方向" is more understandable or add (相对的方向).

Bingo.

**Comment by endrift** [comment]
Note that he updated the wording between you making the change on your end and you replying.

**Comment by EmpyreusX** [comment]
> I see.I think "相对的方向同时输入" or add (相对的方向同时输入) is more understandable.

也对，不过逐字翻译“允许相对的输入方向”感觉更好。

> Note that he updated the wording between you making the change on your end and you replying.

We are discussing other translation issues in Chinese. Is it appropriate to re-open #1845 issue, or just open an another issue and leave that as it is?

**Comment by endrift** [comment]
Sure, I'll reopen it.

**Comment by leoxxx** [comment]
> > I see.I think "相对的方向同时输入" or add (相对的方向同时输入) is more understandable.
> 
> 也对，不过逐字翻译“允许相对的输入方向”感觉更好。
> 
> > Note that he updated the wording between you making the change on your end and you replying.
> 
> We are discussing other translation issues in Chinese. Is it appropriate to re-open #1845 issue, or just open an another issue and leave that as it is?

Agree. 我偷懒少打两个字。

**Comment by EmpyreusX** [comment]
> > > I see.I think "相对的方向同时输入" or add (相对的方向同时输入) is more understandable.
> > 
> > 
> > 也对，不过逐字翻译“允许相对的输入方向”感觉更好。
> > > Note that he updated the wording between you making the change on your end and you replying.
> > 
> > 
> > We are discussing other translation issues in Chinese. Is it appropriate to re-open #1845 issue, or just open an another issue and leave that as it is?
> 
> 允许相对的方向输入 如何？ 我觉得直接根据英语把输入放在前面有点怪怪的。我之前的偷懒少打了允许两个字。

也行。

**Comment by leoxxx** [comment]
刚看了一眼你的changed.
发现有些专业名词翻译有点问题。比如：tile layers， 我觉得翻译成块图层（有点怪）或图块图层比较好一点，或者干脆不翻tile.
当初我也找过这些词的资料，比如Sprite这个词，有翻译成精灵的，我觉得不翻也可以。

**Comment by leoxxx** [comment]
@EmpyreusX
刚看了一眼你的changed.
发现有些专业名词翻译有点问题。比如：tile layers， 我觉得翻译成块图层（有点怪）或图块图层比较好一点，或者干脆不翻tile.
当初我也找过这些词的资料，比如Sprite这个词，有翻译成精灵的，我觉得不翻也可以。

**Comment by leoxxx** [comment]
@EmpyreusX
刚看了一眼你的changed.
发现有些专业名词翻译有点问题。比如：tile layers， 我觉得翻译成块图层（有点怪）或图块图层比较好一点，或者干脆不翻tile.
当初我也找过这些词的资料，比如Sprite这个词，有翻译成精灵的，我觉得不翻也可以。

**Comment by EmpyreusX** [comment]
> @EmpyreusX
> 刚看了一眼你的changed.
> 发现有些专业名词翻译有点问题。比如：tile layers， 我觉得翻译成块图层（有点怪）或图块图层比较好一点，或者干脆不翻tile.
> 当初我也找过这些词的资料，比如Sprite这个词，有翻译成精灵的，我觉得不翻也可以。

感谢提示。经过权衡利弊，给出以下意见：
①. “Sprite”的中文翻译“精灵图”已经在程序员和CSS前端设计领域被广泛使用，维基百科上的[条目](https://zh.wikipedia.org/wiki/%E7%B2%BE%E7%81%B5%E5%9B%BE)也将精灵图作为标题。“精灵图”还被收纳于中国台湾[国家教育研究院](http://terms.naer.edu.tw/detail/3268800)的网络学术名词词典中。因此，在考虑华人地区的词汇使用频度的前提下，翻译成“精灵图”并无不妥。
②. 对于“Tile”，主要在以前的翻译工作中考虑到其译义“瓷贴”常用于微软Windows 8的中文白皮书中，故潜移默化引用这一翻译。经过进一步考证，“Tile”翻译成“图块”确实更为合理。
我会进行进一步更改，欢迎提出更多合理意见。

**Comment by leoxxx** [comment]
@endrift
Not update in 0.8.4.
