### ISSUE TITLE
Confuser in Final Fantasy VI Advance causes glitchy line on hud!

### ISSUE THREAD

**Issue by Legion502onGitHub** [mgba-emu/mgba#1846]
![Final Fantasy VI Advance (Europe) (En,Fr,De,Es,It)-200806-171237](https://user-images.githubusercontent.com/69094410/89588263-eb76f080-d808-11ea-97e2-d8b200a9467a.png)
Whenever any character that knows Confuser (such as Magitek-riding Terra) uses said ability, a glitchy line spans across the top of the hud window for the duration of the move. This was discovered in mGBA 0.8, and it occurs with and without the official GBA BIOS. Furthermore, this occurs in all versions (Japanese, North American, and European) of the game when played on mGBA 0.8.

**Comment by angrylion7** [comment]
Savestate for a North American ROM:

[confuser.zip](https://github.com/mgba-emu/mgba/files/5042456/confuser.zip)

**Comment by Legion502onGitHub** [comment]
An explanation of what you are trying to imply regarding the save state would most certainly be nice.

**Comment by endrift** [comment]
Regressed in 4e296c3efc2fb1b753ef1a1085642d691d4b1567.
