### ISSUE TITLE
Gameshark Saves don't import

### ISSUE THREAD

**Issue by ccfman2004** [mgba-emu/mgba#1851]
I can't seem to get Gameshark game saves to work.  I load the ROM then import the Gameshark save then reset the game but it doesn't load the Gameshark save.  Not sure what to do.

**Comment by endrift** [comment]
What game? Please provide the Gameshark save.

**Comment by ccfman2004** [comment]
Pokemon Sapphire
[pokemon-sapphire-version.2532.sps.zip](https://github.com/mgba-emu/mgba/files/5061178/pokemon-sapphire-version.2532.sps.zip)

**Comment by endrift** [comment]
This save is for a US version of Pokémon Sapphire. Did you try it with a European version?

**Comment by ccfman2004** [comment]
My ROM is the USA/Europe version.

**Comment by endrift** [comment]
There is no "USA/Europe" version of Pokémon Sapphire. The ROM site you downloaded it from mislabeled it.

**Comment by ccfman2004** [comment]
That's what mGBA says it is.

**Comment by endrift** [comment]
Gonna have to yell at some No-Intro datters then. Anyway, it loads fine for me.
![axpe-0](https://user-images.githubusercontent.com/605502/89986787-e7483a00-dc31-11ea-8357-1b78f4b3cdc8.png)

**Comment by ccfman2004** [comment]
The MD5 of my rom is 9bc2b765ca6997175fac51e6cdc29089

**Comment by endrift** [comment]
GameShark saves do checksum matching. Since the checksum is different, it thinks it's the wrong game and rejects. It's arguably a bug in VBA that it doesn't reject it. This information is not presented to the user though, and there's no option to override it.

**Comment by ccfman2004** [comment]
As far as I'm aware the only difference in the rev 2 is the berry glitch is fixed.

**Comment by endrift** [comment]
The file is different. That's enough for the checksum matching to fail. That's the whole point of checksum matching.

**Comment by ccfman2004** [comment]
There should be an option to override it since it's the right game just a different revision.

**Comment by endrift** [comment]
I don't disagree. And it turns out I already had a flag for disabling checksum matching, but it wasn't zealous enough with the checks it skipped.
