### ISSUE TITLE
Feature Suggestion/Question: 3DS Link Cable implementation

### ISSUE THREAD

**Issue by Nomagno** [mgba-emu/mgba#1855]
I was wondering if it would be possible to add an option to send the Link data trough the headphone jack (It supports stereo output and microphone input) instead of regular audio.

**Comment by endrift** [comment]
What is this useful for?

**Comment by alvarosaez316** [comment]
Well I have two new 3ds, and am currently replaying the whole Pokemon series in chronological order with my sister. So, this is useful for exactly the same stuff the original GBA cable was: local multiplayer

**Comment by endrift** [comment]
For a wide number of technical reasons this is infeasible. Sorry.
