### ISSUE TITLE
Pokemon Emerald slowdowns

### ISSUE THREAD

**Issue by ccfman2004** [mgba-emu/mgba#1856]
There is a lot of frame rate and audio issue with Pokemon Emerald.

**Comment by endrift** [comment]
You really need to start giving me ACTUAL information (system, version, specs, etc) or else I can't do shit.

**Comment by ccfman2004** [comment]
New 2DS 11.13.0 Luma 10.2
mGBA CIA 8/13/2020 Nightly
Pokemon Emerald U MD5: 605b89b67018abcea91e693a4dd25be3

**Comment by kode54** [comment]
I know there was something I was once told about Pokemon Emerald versus the Ruby and Sapphire games, that it was stupid and did busy looping reading the vblank register to regulate the game speed, but that shouldn't adversely affect game performance. Much.

**Comment by endrift** [comment]
On a system as weak as the 3DS it can.

**Comment by ccfman2004** [comment]
The funny thing is that I have no issues when playing the game as a custom VC GBA game so the system is clearly capable of playing it perfectly.

**Comment by endrift** [comment]
VC GBA games aren't emulation; they're run directly on an ARM7. The comparison isn't applicable.

**Comment by ccfman2004** [comment]
I always thought they were emulated.

**Comment by endrift** [comment]
You were always mistaken then. Anyway, I can't really get any major slowdowns on my end. Without any more info there's nothing I can do, and it's probably just the 3DS being slow shit.

**Comment by ccfman2004** [comment]
What information would you like?

**Comment by endrift** [comment]
I dunno, maybe a situation in which it noticeably slows down? And a save so I can just get there? You know, stuff that's more than "something is wrong".

**Comment by ccfman2004** [comment]
It mostly happens when I enter/exit building the audio stutters a lot.
[0004000000088000.gbavc.sav.zip](https://github.com/mgba-emu/mgba/files/5072128/0004000000088000.gbavc.sav.zip)

**Comment by endrift** [comment]
The 3DS is too slow run mGBA 100% of the time. That specific sequence is known to push mGBA pretty hard, and barring some major revelation I'm not expecting, I don't think it's gonna get much faster.

**Comment by ccfman2004** [comment]
I tried a different emulator, GBARunner2, that runs in DS Mode and it doesn't have the same issues.

**Comment by endrift** [comment]
GBARunner2 is a hypervisor. It doesn't emulate the instructions in the same way, it runs them (again) directly and tries to do fancy tricks to get the hardware stuff working. It's _again_ not comparable.

**Comment by ccfman2004** [comment]
Learning new stuff all the time.

**Comment by profi200** [comment]
mGBA still has its uses on New 3/2DS but if you want fullspeed either GBARunner2 or for 100% compatibility [this](https://github.com/profi200/open_agb_firm). The later uses the GBA hardware just like GBA VCs do (keep in mind save type detection is not reliable yet in open_agb_firm).
