### ISSUE TITLE
MSYS2/mingw-w64: Seemingly missing dependencies

### ISSUE THREAD

**Issue by lotharsm** [mgba-emu/mgba#1857]
Hi there,

I just tried to compile the latest mgba-master with my trusty MSYS2/mingw-w64 toolchain. However, I ran into the following issue at the cmake stage:
```
CMake Error at CMakeLists.txt:863 (add_library):
  Target "mgba" links to target "BZip2::BZip2" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:863 (add_library):
  Target "mgba" links to target "LibLZMA::LibLZMA" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at src/platform/sdl/CMakeLists.txt:112 (add_executable):
  Target "mgba-sdl" links to target "BZip2::BZip2" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at src/platform/sdl/CMakeLists.txt:112 (add_executable):
  Target "mgba-sdl" links to target "LibLZMA::LibLZMA" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at src/platform/qt/CMakeLists.txt:286 (add_executable):
  Target "mgba-qt" links to target "BZip2::BZip2" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at src/platform/qt/CMakeLists.txt:286 (add_executable):
  Target "mgba-qt" links to target "LibLZMA::LibLZMA" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

I haven't done any bisecting this, but with the same toolchain (no updates inbetween), I was able to successfully build it about two weeks ago.

**Comment by Dimensional** [comment]
I get this issue all the time when compiling for Windows. I've had to switch and use the Docker instructions to build the Windows x64/32 version.

**Comment by endrift** [comment]
I believe this is actually a bug in MSYS2's libzip package. They fairly frequently forget to declare dependencies.

**Comment by endrift** [comment]
Looked into it some and...it may be a CMake bug or a libzip bug. I'm really having a hard time telling which.

**Comment by endrift** [comment]
As a temporary workaround until I figure out whose bug this is just add `-DUSE_LIBZIP=OFF` to the CMake command

**Comment by lotharsm** [comment]
Thanks a lot for this workaround! Just a quick side note, I had to use ` -DUSE_MINIZIP=OFF -DUSE_LIBZIP=OFF -DUSE_LZMA=OFF` to solve all missing dependencies. With MINIZIP or LZMA enabled, I passed the CMake stage, but ran into linking issues afterwards - maybe this helps :)

**Comment by endrift** [comment]
Uh, you definitely want those two still on. What linking issues did you encounter?

Anyway, I filed a bug on the libzip tracker: https://github.com/nih-at/libzip/issues/205

**Comment by lotharsm** [comment]
Well. It seems that my toolchain is trolling me right now - I checked again with a clean build in order to reproduce the linking issues, and now `-DUSE_LIBZIP=OFF` is sufficient to build without any issues.

**Comment by lotharsm** [comment]
I really don't get it, now I have to use `-DUSE_MINIZIP=OFF -DUSE_LIBZIP=OFF -DUSE_LZMA=OFF` again for linking it successfully... :(

**Comment by Testsr** [comment]
Is 'undefined reference to `unztell64'' the issue you are getting?

**Comment by endrift** [comment]
Yes, I have a fix for that that I'm about to push. The libzip-specific part of issue is the one mentioned in a previous comment.

**Comment by endrift** [comment]
minizip issue worked around in d2af8b83e06019ed28b68ec311fcffc3c863433d. I'm going to leave this open until a solution for libzip itself is found, but I'm not really sure what to do there.
