### ISSUE TITLE
Debugger is slow in elf files

### ISSUE THREAD

**Issue by Cleverking2003** [mgba-emu/mgba#1859]
When I load an elf file and enter a command in the debugger, it is executed slowly. All commands after that work as fast as they usually do. Latest mGBA (master) on Linux

**Comment by endrift** [comment]
Is this the Qt frontend? And does it matter what the first command is?

**Comment by Cleverking2003** [comment]
> Is this the Qt frontend? And does it matter what the first command is?

Yes, it's qt and the first command is always slow, no matter what it is

**Comment by endrift** [comment]
Ah, I see what you mean now. I think that's the symbol loading. Will investigate further. I may need to optimize the hash table that symbols get loaded into; since it's never used during usual runtime I never got around to fixing some of the faults with it.
