### ISSUE TITLE
Sonic Advance - minor inconsistent bug

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#186]
Sometimes when starting a stage the camera will be several screens below the starting point but quickly reaches the character's position, this happens rarely but I managed to capture a state with the issue, any zone will show this issue except the last two. I'm not using the bios, and I've only tried this on Wii.
Another issue that only happens at times is that the reset combo will crash the game, I've seen this in other games as well and never encountered with real bios.

![sonic advance_issue ss1](https://cloud.githubusercontent.com/assets/6880539/11768307/991fb856-a17d-11e5-9682-5d7b045cc878.png)

**Comment by taisel** [comment]
I believe some of the sonic advance games rely on specific values the bios leaves in RAM after the BIOS intro ends.

**Comment by endrift** [comment]
Loading this savestate on non-Wii causes the same bug to occur on the non-Wii version, so clearly whatever is causing it to get into this weird state has already happened at this point. I'll try to investigate what's going on soon.

**Comment by endrift** [comment]
Does this still happen without the savestate?

**Comment by SuperrSonic** [comment]
Tested for some 20 minutes of resetting, in-game reset and rom reloading, doesn't seem to happen anymore.
