### ISSUE TITLE
Rayman 10th Anniversary loops on startup screen

### ISSUE THREAD

**Issue by TheLastProject** [mgba-emu/mgba#1860]
I bought a copy of Rayman 10th Anniversary for GBA and dumped it with the Retrode 2. My copy has barcode AGB-BX5P-EUR, which seems to be this exact version: https://vgcollect.com/item/64533.

When starting the game, the game shows a copyright screen, the Ubisoft logo, then a black screen for several seconds followed by a white flash very shortly. It then repeats the screen->logo->black screen->white flash indefinitely.

The SHA256SUM of my cartridge is b1296ca8e2448c975b11e47f082b84304975690a466b00711b3d9c245d0ae269.

I'm running this on the Odroid Go Advance running EmuELEC 3.8-test. It runs RetroArch 1.9.0 with mGBA 0.8.3 (555df03a01). This is an AARCH64 device.

I'll try to find some time tomorrow to test this on an x86_64 device to see if it works fine there.

Please tell me if there is any more info I can provide to make this easier to debug.

**Comment by endrift** [comment]
That SHA256 doesn't match a known-good dump. What size is your file? It's an EEPROM save, so that can confuse some dumpers.

**Comment by TheLastProject** [comment]
The file is 8MB, Thanks for the pointers. I guess it's using the EEPROM stuff to save extra data to fit both games on one cartridge?

Anyway, guess that's not an mGBA issue then. I tried to find a shasum on no-intro but found none for this game, so thank you for finding a correct SHA256SUM.

I'll see how far I can get with your pointers, thank you again. If I figure something out I'll post it here for the next person who may run into this.

Will close the issue now as it doesn't seem mGBA related then. Sorry for the invalid issue and thank you for the pointers and explanation!

**Comment by endrift** [comment]
The EEPROM is being used for saves specifically. I haven't tried dumping GBA games with a Retrode 2, but I do have one I can use to see how it handles EEPROM cartridges. Make sure the switch is flipped to 3.3V.

**Comment by TheLastProject** [comment]
Seems to have been a bug with the Retrode 2's autodetection. Opening `RETRODE.CFG` and setting the following:
```
[forceSystem] gba
[forceSize] 16
```

Creates a 16MB dump which does run fine. The sha256sum is indeed 7adbd9a0fcac09460afb6aeae75367515865fd7b4e13d0473c2d5dc42367bd29 as you said.

Thanks for the pointers and the awesome emulator!
