### ISSUE TITLE
[mgba-3DS] Puyo Puyo Fever (Japan) has no audio

### ISSUE THREAD

**Issue by RunisDauphin** [mgba-emu/mgba#1868]
mGBA version: mGBA-3DS Dev-version 6470
Launching method: through CIA forwarder
System: New Nintendo 2DS XL (Black and Blue) European
System Firmware: 11.13.0-45 E
Banned: Not yet (as far as I know, because I do not use for anything but emulators and my Nintendo DS games).

When I try to play Puyo Puyo Fever (Japan) on my console, no matter if audio is muted or not, or how loud console is in that moment, no sound comes out of the speakers at any moment. When I try to get out of the emulator, I check that the speakers do still work. I tried this same copy on mGBA-Wii (but not this Dev-version), mGBA-Win32 (but not this Dev-version), Ez-Flash Omega (got on 15/01/2020) and Visual Boy Advance - ReRecording, and none of them have this issue.

I have not tried other games yet, but I suspect this is a general issue.

Runis Dauphin, chef et administrateur de Rebelles Unis

**Comment by endrift** [comment]
Did you dump the DSP blob?

**Comment by RunisDauphin** [comment]
What is DSP blob, and how do I dump it?

**Comment by Syko7956** [comment]
> What is DSP blob, and how do I dump it?

I think endrift is talking about this https://gbatemp.net/threads/dsp1-a-new-dsp-dumper-cia-for-better-stability.469461/
You most likely have done this if you looked at modern guides for hacking your 3DS. It's something easy to forget. It's a CIA you boot up and it grabs an important file for audio. Then it auto deletes itself.

**Comment by RunisDauphin** [comment]
I have definitely NOT done this. I followed a guide made by Colombian channel Mundo Yakara Colombia (previously El Mundo Gamer de Yakara), and said tutorial was based on a guide on https://3ds.hacks.guide/ (https://3ds.hacks.guide/seedminer). I do not know if you can understand Spanish, but I could and found that easy-to-perform method.

I still do not know what should I do: do I dump it or not? and if answer is yes, how?

**Comment by Syko7956** [comment]
> I still do not know what should I do: do I dump it or not? and if answer is yes, how?

Download the DSP1.zip, Install the cia. It'll do the rest of the work for you automatically and uninstall itself since it's a one-time need. After that you're good to go. It should work just like that. It's important since homebrew apps rely on it. You also need it for the Commadore 64 emulator, vice3ds
