### ISSUE TITLE
Super Mario Advance 2 issue (doesn't happen on a real GBA)

### ISSUE THREAD

**Issue by rhythm-g** [mgba-emu/mgba#1876]
Selecting Super Mario World from the game select menu and then backing out makes this happen.
![SUPER_MARIOB_AA2E00-0](https://user-images.githubusercontent.com/63170033/92328190-eb972580-f02c-11ea-90b7-ec3e924bc321.png)
When I do this in VBA it looks like this:
![SUPER_MARIOB_AA2E00](https://user-images.githubusercontent.com/63170033/92328396-73c9fa80-f02e-11ea-8917-4f11fe40856b.png)
On a real GBA it looks the same as the VBA screenshot.

Edit: I also noticed some flickering pixels where the transparency effect is supposed to be.

**Comment by RetroEdit** [comment]
Oh, so the bottom of the Yoshi is out of sync with the top of the Yoshi in mGBA? Huh.

**Comment by rhythm-g** [comment]
@RetroEdit There's a transparency effect being done by where it says Choose a game.

**Comment by endrift** [comment]
Regressed in ed2353ff76da104221a0dfcdfe26a724a536a517.
