### ISSUE TITLE
Weird New Buffering/Freezing

### ISSUE THREAD

**Issue by BelthMan** [mgba-emu/mgba#1877]
So I've been playing emulated Pokemon games for a while now on mGBA 0.8.2 and only recently when I started playing Pokemon Sapphire and am near the 8th gym the emulator has started lagging really badly for no particular reason at all. I've been trying to find a fix but there is none I have found so far, turning on sync to video makes the performance very sharp and high FPS except in doing so it stops lagging but then freezes terribly every other 4 seconds and it's just very jarring. Not only does the game completely freeze up every 4 seconds with sync to video on but the audio completely stops to and it just isn't good lol. The alternative isn't much better either with sync to video off it's so terribly laggy and I was wondering if I may need to install a newer version of mGBA or an older one that worked better or what I can do to optimize my emulator? (Also I'm using Windows 10 64-bit and if you need specifications of my specs and what not I can give them if that would help resolve the issue) I'm new to this site and just tech stuff in general so sorry for any confusion.

**Comment by endrift** [comment]
Can you show me your settings? Audio/Video, Emulation and Enhancements pages, specifically.

**Comment by endrift** [comment]
Closing due to lack of reply. If you post the info requested I can reopen.
