### ISSUE TITLE
Oddly specific rom hacks don’t work.

### ISSUE THREAD

**Issue by BignThicc** [mgba-emu/mgba#1880]
Pokémon sweets 1 & 2 do not work and crash on title screen on psvita (0.8.3). I've tried over three dozen Pokémon roms with success. I know it's not their size as several 32MB rooms have ran just fine. The aforementioned are both 20MB or less. I know it's not hardware capability as they run perfectly on the retroarch core for vita.

**Comment by endrift** [comment]
These ROM hacks crash on actual GBA hardware too.

**Comment by fancythedeveloper** [comment]
Wouldn't be surprised if those were old ROM hacks back when most were made for VBA in mind.

**Comment by endrift** [comment]
Yeah, a lot still are. For example RTC hacks pretty much all use code that's buggy on real hardware so they basically only work in VBA, or emulators that have the same bug that the hacks inadvertently use. That's not what's going on here, but a lot of hacks are just like that.
