### ISSUE TITLE
Unknown speed regression on 3DS after 0.8.1

### ISSUE THREAD

**Issue by chipzoller** [mgba-emu/mgba#1882]
I don't have any empirical data to share on this so hopefully a description will help me to help you gather it.

Sometime after 0.8.1 an odd speed-related regression was introduced in the 3DS version (running on a 2DS) which causes frame drops and lag where none existed in 0.8.1. This is with the default settings and no other changes, environmental or otherwise. Unknown if this was introduced with 0.8.2 or 0.8.3, but uninstalling 0.8.3 and reinstalling 0.8.1 "fixes" the issue.

I'm sorry this isn't more helpful. Please let me know what I can do/get to clarify the issue.

**Comment by endrift** [comment]
This is most likely the bug that was introduced by 3ef59bd2c401d49654b0d003ed83e86e55e245a3, which was fixed in a87fe56ec691df7a865b858cde4033a382178c77 (after 0.8.3). Try using a development build to see if it's fixed there, and if it is, it should be fixed when 0.8.4 comes out.

**Comment by chipzoller** [comment]
Yes, confirmed, it is fixed in the [latest commit](https://github.com/mgba-emu/mgba/commit/f636b88f275aeb76a44a204c2e95c8d948eac799). Thank you for that. Also, *thank you* for providing Docker images to quickly and easily build from source. What a super nice thing you've done there.
