### ISSUE TITLE
Dolphin joy support build of mgba

### ISSUE THREAD

**Issue by alfredmanner** [mgba-emu/mgba#1887]
Hi everyone, where can I download a build of the mgba with support for dolphin, I have come across many post that link to source code of that mod however no prebuilt download.

Please can someone please link me to it, I'm stuck with vgba playing Zelda FS and it keeps closing down. :(

**Comment by endrift** [comment]
You cannot download a build at this time. It never got merged because it was very flaky and barely worked.
