### ISSUE TITLE
[XQ GBA Audio] Strident audio glitches in Zelda Minish Cap

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#1888]
After playing the ocarina, a loud beep may sound. If you dodge the transporting beep, the volume of other sounds increases for a second.

[Captures Zelda Minish Cap bug.zip](https://github.com/mgba-emu/mgba/files/5214019/Captures.Zelda.Minish.Cap.bug.zip)

Windows 10 x64, mgba latest build, Realtek High Definition Audio as a sound card.

**Comment by endrift** [comment]
Closing as the old XQ audio driver has been removed.
