### ISSUE TITLE
Advance Wars 2 NTSC refuses to run?

### ISSUE THREAD

**Issue by GB-CG** [mgba-emu/mgba#189]
<img width="592" alt="screen shot 2015-12-16 at 21 30 07" src="https://cloud.githubusercontent.com/assets/11931125/11854522/5464a50c-a43c-11e5-9c77-ccdbc0601e39.png">
and 'FATAL:	Jumped to invalid address: 03007DDC' in the log list.
The PAL version works, but the 'Mode7' NTSC rom crashes after pressing Start on the Mode7 screen.

**Comment by endrift** [comment]
Seems to work for me. You might have a non-clean dump. What's the md5 sum of the ROM itself? Should be `46599031EF71117C587BD3666C326C07`.

**Comment by GB-CG** [comment]
Yeah I thought it might be a non-clean dump. Pardon my ignorance, how do I find the md5 sum?
I've tried another NTSC rom and it's working now.

**Comment by GB-CG** [comment]
Never mind I've found the 'Mode7' sum: 29366BC79094492456210AA7013E14EC

The md5 sum you mentioned is correct.

**Comment by GB-CG** [comment]
I thought I'll try removing the mode 7 intro with GBATA, but that didn't work either:
<img width="493" alt="screen shot 2016-01-24 at 01 51 04" src="https://cloud.githubusercontent.com/assets/11931125/12534227/9f80f446-c246-11e5-8313-d7bca7269b14.png">

**Comment by endrift** [comment]
How big is the output ROM? That looks like a legitimate address...

**Comment by GB-CG** [comment]
The mode7 rom with intro and without is 8,388,608 bytes (8.4 MB).

**Comment by endrift** [comment]
Yep, that's beyond the end of the ROM then. I think you just have a bunk ROM.

**Comment by GB-CG** [comment]
Ahh ok, the rom you mentioned (46599031EF71117C587BD3666C326C07) has 8,403,263 bytes.

**Comment by endrift** [comment]
Fixed by 3a134fcda68c4fbe702088640fd8c023567e8679 and /6fe43d1d4cfc7c15046e8a7df3354df272e97f4d
