### ISSUE TITLE
Holding the lantern partially breaks Link's body in certain areas in Minish Cap with OpenGL.

### ISSUE THREAD

**Issue by Tiberius1437** [mgba-emu/mgba#1890]
![Capture](https://user-images.githubusercontent.com/68873449/93118955-608cee00-f704-11ea-9100-4a8fb55b8518.PNG)

![Capture2](https://user-images.githubusercontent.com/68873449/93118969-65ea3880-f704-11ea-9b02-468140d9b581.PNG)

This doesn't happen with software thought I found that switching from OpenGL to software during gameplay crashes the emulator. 

![Capture3](https://user-images.githubusercontent.com/68873449/93119271-db560900-f704-11ea-9b09-fdb8f17d6cbd.PNG)

**Comment by fancythedeveloper** [comment]
Maybe try setting it to OpenGL before starting?

**Comment by endrift** [comment]
If it crashes it's a bug. Regardless, it's not _this_ bug.

**Comment by RafaelTrepaUnCarballo** [comment]
It also happens in the European edition.

For testing purposes I attach a save and savestate in a dungeon with torches (if you can't load the savestate, just teleport in the blue wrap and go down.

[Legend of Zelda, The - The Minish Cap (Europe) (En,Fr,De,Es,It) European Backport Edition.zip](https://github.com/mgba-emu/mgba/files/5238882/Legend.of.Zelda.The.-.The.Minish.Cap.Europe.En.Fr.De.Es.It.European.Backport.Edition.zip)

**Comment by endrift** [comment]
This appears to be an OBJWIN priority conflict.
