### ISSUE TITLE
When uploading .gba files in WinSCP they are 0kb and won't load (PS VITA)

### ISSUE THREAD

**Issue by belody42** [mgba-emu/mgba#1891]
Until today any rom I have used has worked fine and the file size remains unchanged when uploading files into my GBA ROMS folder, however multiple .gba files I put onto my ps vita today failed to load which has never happened before and when I looked in WinSCP they were all 0kb. This is strange because they are not 0kb files, they all have regular .gba file sizes it's just that when I upload them to GBA ROMS they change to 0kb and I'm not sure why. I tried deleting an existing from and re-uploading it to my GBA ROM folder and it remained the correct size and is playable in mgba. Is there a known way to fix this? I also tried getting roms from multiple sources in case the website/s used were the cause.

Examples of gba games this has occurred for: Wario Land 4, Pokemon Mystery Dungeon Red Rescure Team, Kirby Nightmare in Dreamland, Super Mario Advance 3 Yoshi's Island

**Comment by endrift** [comment]
That doesn't sound like an mGBA bug. Something else is probably truncating them.

**Comment by belody42** [comment]
Ah you're correct, I deleted some games and the new ones are the correct size and will load now, I guess I needed space for the new games
