### ISSUE TITLE
[Wii Port] Original Game Boy screen color option

### ISSUE THREAD

**Issue by SieKensou** [mgba-emu/mgba#1893]
Hi,
I'm using this emulator on the Wii console. I would like to ask if it would be possible to add a new option to simulate the original first Game Boy screen color insteaf of seeing the games in black and white. Something like this:
https://youtu.be/tQrixG3nvAk
It would be awesome and the experience with the Game Boy games would be much better.
Thanks and congratulations for the great job with this emulator.

**Comment by endrift** [comment]
This can currently be done by manually editing the config file, but having an actual option for it in the UI would be nice too.

**Comment by SieKensou** [comment]
Yeah, it would be nice having the option, thanks.
What I need to do to activate it manually?

**Comment by endrift** [comment]
This was added a few months ago to the dev version and I forgot to close this.
