### ISSUE TITLE
[Wii port] Game Boy advance controls

### ISSUE THREAD

**Issue by SieKensou** [mgba-emu/mgba#1895]
For some Game Boy Advance games is more confortable to use the "y" and "x" buttons instead the triggers but for some others is better to use the triggers, so I want to suggest to map the "y" button and the "x" button of the GameCube controller and the Classic Controller/Pro Controller as the Game Boy Advance "L" trigger and "R" trigger too, so you can use what you want, the L/R triggers or the y/x buttons.
This is what I mean:
GBA L trigger: Classic Controller/Game Cube Controller "L" trigger and "y" button.
GBA R trigger: Classic Controller/Game Cube Controller "R" trigge" and "x" button.

Thank you very much for the great job you are doing with this great emulator.

**Comment by endrift** [comment]
Manually remapping controllers is an existing feature.

**Comment by SieKensou** [comment]
Thanks for the reply. I know, but I mean to use the 2 buttons always indistinctly to not have to map always the buttons. Or is it possible to map 2 different buttons for the same button?

**Comment by endrift** [comment]
Yes, it is. There's a special "GameCube controller 2" input map so you can do this. It doesn't map to player 2, it maps to a second set of inputs for controller 1.

**Comment by SieKensou** [comment]
I tried but I can't do what I wanted and it doesn't affect to the Classic Controller.... What I was asking is to set the "L" trigger and the "y" button as the "L" trigger button from the GBA, so I can use on or the other depending on the game and not having to change the controller configuration. Maybe instead of that can you add to the button maps options "L and y" and "R and x", meaning that these 2 buttons will work for that specific button....

**Comment by endrift** [comment]
Oh, I see, what you're looking for is currently being tracked by #87, as the input mapping code involved is shared between all platforms.
