### ISSUE TITLE
Audio problems in intro for Panel de Pon GB restoration

### ISSUE THREAD

**Issue by eisnerguy1** [mgba-emu/mgba#1896]
So, I've been trying out the[ Panel de Pon GB restoration project](https://www.reddit.com/r/PanelDePon/wiki/pdpgbrestoration), from the [Panel de Pon Discord](https://discord.gg/RQ6FSy8), in mGBA (0.9-6513-e232e5ce4) on macOS 10.14.6.  I've noticed an audio glitch and missing audio.

There's a strange issue in part of the intro.  Before the title screen, Lip is supposed to say "Nintendo".  Here's how it's supposed to sound:
https://www.youtube.com/watch?v=1NNAdhuVbLY

And here's how it sounds in mGBA:
https://www.youtube.com/watch?v=1im6awIYCmI

Also, after this screen, a small jingle is supposed to play before the title screen. That's shown in the first video and it's missing in the mGBA video.

I've tried the standalone version of mGBA (0.9-6513-e232e5ce4), version 0.8.3 in Retroarch and I got the same results as well.  I'm not sure what's causing the issues.  I've gone through all of mGBA's settings and I can't find anything that would cause the audio glitch.  When I kept on playing, I didn't notice any other odd audio glitches.

**Comment by endrift** [comment]
I won't be able to test this without some way of patching the Pokemon Puzzle Challenge ROM.

**Comment by eisnerguy1** [comment]
Gotcha. Ok, here's are 2 ips patch files that I generated off of the PDPGB_Restoration_8_28_20 version.  It's the latest version that was posted on the discord.  There's one where I used the English rom as the source file and another where I used the Japanese rom as the source file.  The patched rom are probably the same but, I wanted to be sure.
[PDPGB_Restoration_8_28_20_ips_files.zip](https://github.com/mgba-emu/mgba/files/5282144/PDPGB_Restoration_8_28_20_ips_files.zip)

**Comment by endrift** [comment]
This is an issue with channel 3.

**Comment by eisnerguy1** [comment]
Oh dang, I completely forgot about this. Thanks for adding it to the 0.10.0 milestone :D I really appreciate it!
