### ISSUE TITLE
Disabling super game boy border makes window show garbage pixels.

### ISSUE THREAD

**Issue by Lokathor** [mgba-emu/mgba#1898]
* Version: 0.9-6424-4a28264d
* Git Hash: master 4a28264d0cf2608a401f352687e63b238c47bc9f

With a game boy game running and the Super Game Boy border displayed, if you turn off the super game boy border in the settings then the window displays garbage pixels.

* It happens reliably, and with more than just one game (tried Pokemon Red and also Donkey Kong)
* It doesn't happen with games that don't have a super game boy border (tried Dragon Warrior 1+2)
* If you take a screenshot using mGBA itself the screenshot produced shows the proper output.

**Comment by Lokathor** [comment]
![PXL_20200927_002211550](https://user-images.githubusercontent.com/5456384/94352726-166e0b80-0026-11eb-9ec9-d131960d5492.jpg)

**Comment by endrift** [comment]
This appears to be because the GL backend gets confused about the stride when the resolution changes. GL thinks the stride is equal to the width, whereas the core has no such illusions.
