### ISSUE TITLE
Qt/macOS: unpausing won't update display

### ISSUE THREAD

**Issue by lunasorcery** [mgba-emu/mgba#1899]
Pausing the emulation will correctly pause the display, unpausing will resume emulation but the display will be stuck on the paused frame. Further pauses will update the display to new paused frames but will never resume live visuals. This occurs with both Cmd+P and pausing via the menu.

Observed on a3d5e3481 (latest master at time of posting).
Appears to have been introduced at ca8559549c2b77b5adb958557c3a6c9d6ebc5d47 (checked via git bisect).
Only occurs on the Qt build - SDL version is unaffected.
This affects both GB and GBA emulation.
Observed on macOS 10.14.6, on a 2016 MBP (2.9 GHz Intel Core i5, Intel Iris Graphics 550 1536 MB)

**Comment by endrift** [comment]
I assume this also happens with the OpenGL 1.x display driver, but not with the Software display driver?

**Comment by lunasorcery** [comment]
Yes - this only seems to occur on the GL and GL 1.x drivers, Software appears unaffected.

I've got a change at https://github.com/lunasorcery/mgba/commit/2d3c13cebc1f835ad7ca92b9ffa8f45818d61a46 that appears to resolve it but I'm not confident it's the 'correct' fix.

**Comment by RetroEdit** [comment]
There was only a README change in the linked commit, and the latest build still seems to have the issue, so it seems like this might have been closed in error.
