### ISSUE TITLE
Win64 installer insists on a start menu entry

### ISSUE THREAD

**Issue by Maffsie** [mgba-emu/mgba#1904]
The latest released installer for mGBA on Windows x64 has an option to "Do not create a start menu entry", however during installation, the start menu entries are created irrespective of if this option is ticked.

**Comment by lotharsm** [comment]
Thanks for reporting this! Fixed via https://github.com/mgba-emu/mgba/commit/78343663c443cb936296e4b705832d46bc6d4387
