### ISSUE TITLE
GBA/OpenGL: Sprites behind a Mode 4 background are hidden entirely

### ISSUE THREAD

**Issue by lunasorcery** [mgba-emu/mgba#1907]
Any sprites with their priority set to draw behind a Mode 4 background will be hidden entirely - when populating the relevant background layer, the OpenGL renderer treats palette index 0 as a solid color rather than a transparent passthrough.
This might affect other background modes too; I'm not sure.

Observed on 7b3900f
Only occurs on the OpenGL Video Renderer. The Software Video Renderer is unaffected.

**Comment by endrift** [comment]
Do you have an example game this is used in? It's an easy fix but I want to make sure I do it properly.

**Comment by lunasorcery** [comment]
Observed on _Asterix & Obelix XXL_:
<img width="721" alt="Screen Shot 2020-10-11 at 22 36 47" src="https://user-images.githubusercontent.com/2166769/95692603-fe4ddd00-0c1e-11eb-8214-c3e75376fbe8.png">
<img width="721" alt="Screen Shot 2020-10-11 at 22 36 36" src="https://user-images.githubusercontent.com/2166769/95692605-0017a080-0c1f-11eb-8ab7-1866eb710226.png">

and _Drome Racers_:
<img width="721" alt="Screen Shot 2020-10-11 at 22 32 04" src="https://user-images.githubusercontent.com/2166769/95692610-01e16400-0c1f-11eb-93aa-8d34ec002237.png">
<img width="721" alt="Screen Shot 2020-10-11 at 22 32 23" src="https://user-images.githubusercontent.com/2166769/95692608-0148cd80-0c1f-11eb-8bb8-e1788ab79e7b.png">
