### ISSUE TITLE
[Debugger] Flawed display of PC-relative store operations

### ISSUE THREAD

**Issue by lunasorcery** [mgba-emu/mgba#1908]
Observed on 7b3900f

Disassembling PC-relative store operations will display the value at the destination address rather than the address itself.

Repro case: disassemble ARM code from _Asterix & Obelix XXL_ at 0x030000C4:
```
> dis/a 0x030000C4
030000C4:  E5CF1104	strb r1, =0x00000000
```

Ideally this should show that it's storing the value at address 0x030001D0, rather than displaying the current value at that address.

Additionally, I think that PC-relative _load_ operations should also display the address rather than the value, though I can see that being a matter of personal preference.

**Comment by endrift** [comment]
Good catch. I will probably add a `; [#0x030001D0]` at the end of the instruction like some other emulators do for PC-rel loads; however, having the actual value there I think is more informative by default than having to chase the address.

**Comment by lunasorcery** [comment]
I agree that having the value displayed is more practical than asking the user to go pointer-chasing, and so displaying both is a sensible compromise. That said, I'd propose flipping your suggestion, such that the _value_ is the commented extra part on the right, and the _address_ is shown on the left as part of the instruction.
This is what VBA does:
<img width="426" alt="Screen Shot 2020-10-12 at 22 49 25" src="https://user-images.githubusercontent.com/2166769/95793354-4d5a4780-0cdd-11eb-8db6-95edcce3d87e.png">

**Comment by endrift** [comment]
I disagree with that proposal simply because when you're writing assembly you don't write "where do I want to load this literal from in the pool?", you wrote "what literal do I want to load?" and the assembler chooses where in the pool it goes.

**Comment by lunasorcery** [comment]
I must shamefully confess I was not familiar with the concept of literal pools being inserted by the assembler, and had naively assumed such things were written by the programmer manually. So I've only ever known the `ldr rX, someAddress` syntax and not the `ldr rX, =someValue` syntax. Now that I'm aware of that I can appreciate your stance.

That being said, would you agree that for _store_ operations, the destination address is the important information and the current value at that address is comparatively useless?

**Comment by endrift** [comment]
Oh yes 100%, that's a bug and I intend to fix it tonight.
