### ISSUE TITLE
Sonyc (homebrew/bootleg) - Grass/wall rendering issue

### ISSUE THREAD

**Issue by SorachiJirachi** [mgba-emu/mgba#1909]
There is an old homebrew/bootleg Game Boy Advance demo known as Sonyc, which is based on a bootleg MSX2 game. The demo has a problem when run in VisualBoyAdvance in that the grass and walls in the first level are not rendered. It seems mGBA has the same issue on the latest stable version under 64-bit Windows 7:

![image](https://user-images.githubusercontent.com/72827255/95917959-ef903300-0da2-11eb-99d8-c508d1a4d5ea.png)

For comparison's sake, it should also be noted that the issue does not apply in the older BoycottAdvance emulator:

![image](https://user-images.githubusercontent.com/72827255/95918010-fe76e580-0da2-11eb-9880-f04bdd6b844c.png)

It's probably not an important issue considering the demo's unlicensed/homebrew status, but would it possible that this can be rectified in a later version of mGBA?

**Comment by endrift** [comment]
The bootleg appears to be using invalid tiles. I'd need to check on hardware, since I expect it won't work there either.

**Comment by endrift** [comment]
Confirmed identical to the output on a DS, and very similar to a GBA (modulo some not well-understood/unimplemented behavior described here: https://mgba-emu.github.io/gbatek/#using-invalid-tile-numbers)
