### ISSUE TITLE
[Enhancement Request: Wii] Support read from USB Drive

### ISSUE THREAD

**Issue by OTFree** [mgba-emu/mgba#191]
Thank you for all of your hard work! I'm currently using mgba for my Wii U (running virtual Wii) and I know that vbagx supports the use of a external usb hard drive as opposed to an SD card. Do you think USB support could be implemented in the future?

**Comment by endrift** [comment]
I've been thinking about how to do this for a while without totally redoing a good chunk of the file browser. I think it can be done, but I need some time to mull over the right way to do it.

**Comment by OTFree** [comment]
Okay, take as much time as you need. Thank you for the quick reply and for all of your efforts! I hope to see this potentially utilized in a future release :)

**Comment by askotx** [comment]
But actually you can do it, you just need to run mgba from usb when you launch it.

**Comment by OTFree** [comment]
Ahhh, I hadn't considered that. Thank you for the suggestion!

**Comment by endrift** [comment]
Fixed in 2495b650a4dbf12c4955e187f8b3551b67f76297. Doesn't seem to work with my SD Gecko for whatever reason, but I imagine that's not really a problem for anyone.
