### ISSUE TITLE
Final Fantasy VI Lag on ''Mode 7'' sections.

### ISSUE THREAD

**Issue by BrazilianDood** [mgba-emu/mgba#1911]
I'm running the latest 0.8.3 Wii version.
The game has a lag spike whanever a Mode 7 section starts (so basically while flying with the airship or riding a Chocobo) the sound also stutters because of said lag.
The rest of the game runs pretty smoothly though, I think it's also relevant to mention that I'm using the ''Sound Restoration'' mod, this improves some of the lag that naturally  exists in the original game, I tested these exact sections with the same mod in other emulators and they ran much better than the Wii version of mgba, maybe this is an issue that can be fixed?
![Final Fantasy VI Advance-0](https://user-images.githubusercontent.com/58200737/96256215-9a187980-0f8e-11eb-8caf-513bd2e33325.png)
![20201016_085012](https://user-images.githubusercontent.com/58200737/96256243-aac8ef80-0f8e-11eb-81e7-a56a7c45ec7e.jpg)

**Comment by endrift** [comment]
This may just be the Wii not being fast enough to keep up. mGBA hasn't always been fast enough to run full speed on the Wii and this may be a segment where it still isn't.

**Comment by BrazilianDood** [comment]
> This may just be the Wii not being fast enough to keep up. mGBA hasn't always been fast enough to run full speed on the Wii and this may be a segment where it still isn't.

I see, well I just think it's interesting how the entire game runs with no lag on wii, with the only exception being the Mode 7 sections (it makes me think how square managed to emulate this effect on the GBA in the first place).

**Comment by endrift** [comment]
The GBA has some display modes that are similar to mode 7 that it's using. Unfortunately they're very slow to emulate, which is probably part of the bottleneck here.

**Comment by BrazilianDood** [comment]
> The GBA has some display modes that are similar to mode 7 that it's using. Unfortunately they're very slow to emulate, which is probably part of the bottleneck here.

Most likelly yes, since the original game already features lag in these sections, in fact, the game with the restoration mod is actually running faster than the vanilla version of the game, even with the added lag on Wii. This port of FF6 is indeed rough.
