### ISSUE TITLE
Background palette isn't updated in H-Blank

### ISSUE THREAD

**Issue by GValiente** [mgba-emu/mgba#1913]
[Test ROM](https://github.com/mgba-emu/mgba/files/5395265/test.zip)

The palette of a background isn't updated in a H-Blank interrupt (mGBA 0.8.3, Windows 10, software renderer):

![mgba_0_8_3](https://user-images.githubusercontent.com/13147012/96333406-103dde80-106a-11eb-9dde-dcd3b7036e9e.png)

However, it is working with the latest development version posted on mgba.io (6542-bf2cdba):

![mgba_0_9_dev](https://user-images.githubusercontent.com/13147012/96333427-2e0b4380-106a-11eb-973c-f8c6f96a55fb.png)

**Comment by endrift** [comment]
This was fixed in c2893d641e6c18496d1637f8d729ee5f1d3b1b4d, which means it was the same bug as #1846, which was fixed two months ago (and said fix is already on the 0.8 branch, only a few commits after 0.8.3 came out).

**Comment by GValiente** [comment]
Thanks a lot for looking at it.
