### ISSUE TITLE
[Debugger] Load/Store instructions don't indicate writeback flag

### ISSUE THREAD

**Issue by lunasorcery** [mgba-emu/mgba#1915]
Observed at 4aed125b3.

The disassembler appears not to note the writeback flag when disassembling ldr/str instructions.

For example:
```
ldrh r8, [r7, r2]!  ; opcode e1b780b2
ldrh r8, [r7, r2]   ; opcode e19780b2
```
mGBA will display both instructions as `ldrh r8, [r7, r2]`, missing the trailing `!`, but will correctly perform the writeback when executing.

This appears to affect all forms - all of `ldr`, `ldrh`, `ldrb`, `str`, `strh`, `strb`, with both register offsets and immediate offsets.

**Comment by endrift** [comment]
I'm pretty sure this used to work. It may be a recent regression. Checking now.

**Comment by endrift** [comment]
This was indeed a regression, but not a recent one. It broke in _0.2.0_.
