### ISSUE TITLE
Final Fantasy VI Advance - Graphic glitch in Figaro castle

### ISSUE THREAD

**Issue by ossi-c** [mgba-emu/mgba#1916]
In Figaro Castle, when talking to one of the two guards in the first court, from the tile below them, there are glitch tiles flickering on the top border of the text box. The glitch is not present when talking to the guards from the side.

I also tried using a dumped BIOS file, with the same result. Also, the glitch couldn't be recreated in Higan.

Game: Final Fantasy VI Advance (EU)
mGBA version: 0.8.3 (Release)
OS: Windows 10 (64bit) 

![Final Fantasy VI Advance (Europe) (En,Fr,De,Es,It)-0](https://user-images.githubusercontent.com/10448766/97106267-cb94f180-16c0-11eb-99a4-d540928e0685.png)
![Final Fantasy VI Advance (Europe) (En,Fr,De,Es,It)-1](https://user-images.githubusercontent.com/10448766/97106269-cd5eb500-16c0-11eb-893b-897d723bc63c.png)

**Comment by endrift** [comment]
It's very likely that this is a dupe of #1846, which was fixed some time ago and should be fixed in 0.8.4 when I release that soon.

**Comment by ossi-c** [comment]
Just tested it with latest development build (0.9-6554-a2cd8f6), can confirm that the issue has been fixed indeed.
