### ISSUE TITLE
GBC like Color pallete in GB games 

### ISSUE THREAD

**Issue by kprkpr** [mgba-emu/mgba#1921]
Hi guys!
I'm using mgba in a new 3ds for gb/gbc/gba emulation and seems great so far!
The unique thing I miss is that GB games are not colorized like in a normal GBC or GBA (Or some emulators like gameyob, but some gb games not work in it)
I have gbc_bios selected in the UI, and I don't know if it's an options than I can turn on in config ini file...
Screenshot attached
![IMG_20201029_205230](https://user-images.githubusercontent.com/5132053/97626465-25334e00-1a2a-11eb-8b2d-106485e6888c.jpg)
Tried in master and mgba 0.8.3
Thanks!

**Comment by skmpowdjy** [comment]
I filed #1697 for this
You can manually edit the ini and it will work, but it will get overridden sometimes as I mentioned in that ticket

**Comment by kprkpr** [comment]
Oh...
But I don't know what is the option in the ini file... What is it??

**Comment by skmpowdjy** [comment]
`gb.model=DMG
cgb.model=CGB
sgb.model=SGB`

Those are which hardwares are used to run GameBoy, GameBoy Color, and Super GameBoy titles.  If you want to run GB games on a GBC, you would set `gb.model=CGB`
`AGB` is also available to run these on a GameBoy Advance, for titles with GBA extras like Zelda OoA/OoS

**Comment by endrift** [comment]
This has been supported in dev builds for several months now.
