### ISSUE TITLE
Emulator freezes with quick save mapped on xInput gamepad

### ISSUE THREAD

**Issue by Yankshuru** [mgba-emu/mgba#1922]
As title says, mGBA (win64 version) 0.8.4.

I tried regular save state and quick save state, same issue for both.

The mapped button was L3/R3

Thanks for the support.

**Comment by endrift** [comment]
This was likely caused by #1889.

**Comment by endrift** [comment]
I was half right--that PR exposed the actual issue, but the fix was elsewhere.
