### ISSUE TITLE
Version.cmake patch version 3 (should now be 4)

### ISSUE THREAD

**Issue by Digital-Chaos** [mgba-emu/mgba#1923]
https://github.com/mgba-emu/mgba/blob/545a76f876af47671c8089b1ee09bf1d4a55f47e/version.cmake#L6

**Comment by endrift** [comment]
Well that's what I get for not expecting to release a 0.8.4 in the first place. Good catch, but it's a little late now. I guess I'll bump it to 0.8.5 in case I release that too.

**Comment by endrift** [comment]
"Fixed" in 17f0edd7862b2f02dac4f323e3afee6853dbd891.
