### ISSUE TITLE
Is the Chinese translation updated?

### ISSUE THREAD

**Issue by leoxxx** [mgba-emu/mgba#1924]
https://github.com/mgba-emu/mgba/issues/1845

**Comment by endrift** [comment]
Translation changes between major releases don't get backported to point releases. The strings shift between the branches, making porting the changes that apply and the changes that don't somewhat difficult. I'm not sure how best to handle this though.

**Comment by leoxxx** [comment]
Maybe need a  language file.
Reference to VBA-M.
https://github.com/visualboyadvance-m/visualboyadvance-m

**Comment by endrift** [comment]
I have no idea what that has to do with anything. I just mean that if you work off of one branch the changes may not be applicable to the other. Fixing both branches is difficult.

**Comment by leoxxx** [comment]
So, is it updated in next release? I don't understand the github merge function.

**Comment by endrift** [comment]
It will be updated in 0.9.0, when that comes out.
