### ISSUE TITLE
Data processing instructions with a shift by register where rs == 15 seem to be broken

### ISSUE THREAD

**Issue by wheremyfoodat** [mgba-emu/mgba#1926]
If rs == r15, the pc should still be (addr of instruction + 8), not +12.
In the .zip below, I've included a test ROM + source code for this edge case.

If the shift is by (addr of instruction + 8), the ROM displays green.
If it's +12, the ROM displays blue.
Else, it displays red.

The version of mgba I've installed displays blue, while the 3DS displays green

[shift_test.zip](https://github.com/mgba-emu/mgba/files/5469930/shift_test.zip)

**Comment by endrift** [comment]
Good catch. Looks like I misread GBATEK a [_long_ time ago](https://github.com/endrift/gbajs/commit/a15b43d4d93070e085176bc06818aaba17093f44) and never caught that it was a bug.
