### ISSUE TITLE
Mega Man Zero (USA) garbled visuals

### ISSUE THREAD

**Issue by MODFireball** [mgba-emu/mgba#1927]
Trying to play Mega Man Zero (USA) on the latest versions of mGBA (only tested v0.8.3 and v0.8.4), the game gets garbled visuals straight from the intro into game play of the first level. Tried using both with and without GBA Bios. Other than this one, all other Mega Man Zero games (2-4) work fine from what I can tell!  : ) 

Please see the following examples: https://imgur.com/a/1dnTEx6

**Comment by yuriks** [comment]
Seems to work fine here on v0.8.4. I played through the end of the intro stage boss and didn't see any corruption. My rom sha1 is `193b14120119162518a73c70876f0b8bffdbd96e`.

**Comment by MODFireball** [comment]
Yep, that was the problem - bad rom. Sorry for the mixup, it is all good! Closing issue.
