### ISSUE TITLE
QT frontend segfaults on fedora 21

### ISSUE THREAD

**Issue by GUIpsp** [mgba-emu/mgba#193]
SDL frontend works fine.

GDB says this:

        Program received signal SIGSEGV, Segmentation fault.
        0x00000000004a08c0 in QGBA::ShaderSelector::makePage(GBAGLES2Shader*, QString const&, int) ()

Not a C developer, so not sure how I can help, please tell me if there is anything I can do to help debug this :)

**Comment by endrift** [comment]
Hopefully fixed now, let me know.

**Comment by GUIpsp** [comment]
Seems that fixed it, thanks! :)
