### ISSUE TITLE
Building on Debian

### ISSUE THREAD

**Issue by apaz-cli** [mgba-emu/mgba#1937]
I figured out that I needed to install libsdl2-dev, and it now compiles. But it doesn't link. It appears that cmake doesn't know where to find opengl. The error looks like so:

```
.
.
.
/usr/bin/ld: ../libmgba.so.0.9.0: undefined reference to `glUniformMatrix2fv'
/usr/bin/ld: ../libmgba.so.0.9.0: undefined reference to `glDeleteBuffers'
/usr/bin/ld: ../libmgba.so.0.9.0: undefined reference to `glUniform1iv'
/usr/bin/ld: ../libmgba.so.0.9.0: undefined reference to `glClearStencil'
/usr/bin/ld: ../libmgba.so.0.9.0: undefined reference to `glUniform2f'
/usr/bin/ld: ../libmgba.so.0.9.0: undefined reference to `glLinkProgram'
/usr/bin/ld: ../libmgba.so.0.9.0: undefined reference to `glShaderSource'
/usr/bin/ld: ../libmgba.so.0.9.0: undefined reference to `glDrawBuffers'
/usr/bin/ld: ../libmgba.so.0.9.0: undefined reference to `glFinish'
/usr/bin/ld: ../libmgba.so.0.9.0: undefined reference to `glGenFramebuffers'
collect2: error: ld returned 1 exit status
make[2]: *** [sdl/CMakeFiles/mgba-sdl.dir/build.make:149: sdl/mgba] Error 1
make[1]: *** [CMakeFiles/Makefile2:451: sdl/CMakeFiles/mgba-sdl.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by endrift** [comment]
Probably related to the issues causing #1872.

**Comment by apaz-cli** [comment]
@endrift It's worth noting that I actually already have libopengl0 installed. I'm very unfamiliar with cmake wizardry however.

**Comment by endrift** [comment]
To be clear, that issue involves CMake changing how detecting OpenGL is done, and mGBA assuming the old way while not handling the new way, so that misdetection may be relevant here too.

**Comment by endrift** [comment]
This may be fixed now, please try again.

**Comment by apaz-cli** [comment]
Yep, it works now. Notably though, Debian users do need to install libsdl2-dev. Not sure if that sort of thing should be in the build instructions or not, or if people can just infer that by looking at the error.

**Comment by apaz-cli** [comment]
I'm a fool, it's listed as a dependency. Thanks for the help.
