### ISSUE TITLE
Does anyone know how to disable speedup?

### ISSUE THREAD

**Issue by MarcellusIsHere** [mgba-emu/mgba#1940]
The emulator is absolutely amazing. I've had tons of fun playing some classics, such as the Pokémon RSE, Wario Land 4, ect. But when I was playing a Pokémon rom when I used speedup. Eventually, though, I used speedup (More specifically, I turned in on by accident pressing some buttons on my keyboard) and I can't disable it for the life of me! I've tried deleting it, then redownloading, using older versions, everything! It continues to be sped up. When I activate speedup in the menu nothing happens. When I turn it off nothing happens. What do I do?

**Comment by endrift** [comment]
You need to enable one of the sync options. I recommend sync to audio.

This isn't a support forum, by the way. Support is offered on Discord.

**Comment by MarcellusIsHere** [comment]
I apologize. Thank you for the help.
