### ISSUE TITLE
Ability to boot mGBA with both a multiboot image and a game pak

### ISSUE THREAD

**Issue by obskyr** [mgba-emu/mgba#1941]
For development of multiboot software, it'd be absolutely lovely to be able to start the PC version of mGBA with both a ROM in the game pak slot and a multiboot image running. It's possible to do this through the “Replace ROM…” option after booting a multiboot image, but as it requires some manual interaction, it's not entirely suited to rapid prototyping.

My suggestion would be to either add a positional argument (e.g. `mgba actually_running.mb plugged_in.gba`) or a “plug in but don't run” option (e.g. `mgba --inserted plugged_in.gba actually_running.mb`), but the specific implementation isn't particularly important.

**Comment by endrift** [comment]
I used `--mb` instead of `--inserted` but the semantics are the same.
