### ISSUE TITLE
bug cutscene mario vs donkey kong jp dident check us ver.

### ISSUE THREAD

**Issue by ro66in** [mgba-emu/mgba#1942]
I think I found a bug in japanese version of mario vs donkeykong, one of the cut scenes is missing sprites, the world 2 mm stage cutscene, thats the stage after 2-6, the cutscene looks total mess, just a couple of sprites show up.. I have bios enabled

**Comment by endrift** [comment]
Thanks for the report. It seems to work fine for me though? Were you using any non-default settings?
![2mm](https://user-images.githubusercontent.com/605502/99473507-89e21a00-28ff-11eb-9656-e5e6e884cc75.png)

**Comment by ro66in** [comment]
I checked again, press start during that cutscene, and the image will be total mess, I just checked it again, i am using default settings bios enabled

**Comment by ro66in** [comment]
![Uploading 20201118_091840.jpg…]()

**Comment by endrift** [comment]
I don't think the image finished uploading before you hit comment.

The only thing I'm seeing on my end that looks odd is the chest popping to another side of the screen, and some Toads disappearing spontaneously, which admittedly may be a bug. But I'd need to verify what it's supposed to look like.

**Comment by ro66in** [comment]
Yup thats the bug, its not an issue gameplay wise realy
![Uploading 20201118_091840.jpg…]()

**Comment by endrift** [comment]
You need to wait for the image to finish uploading before you hit comment.

**Comment by ro66in** [comment]
Firefox ia broaken on android, cant downl or upload thats why it doesent upload, i have to try with chrome.. my excuse

**Comment by ro66in** [comment]
![20201118_091840](https://user-images.githubusercontent.com/74624166/99505465-27c9f900-2981-11eb-953e-5f9eee0a9365.jpg)

**Comment by endrift** [comment]
Oh, THAT I'm not seeing on my end. Interesting.

**Comment by ro66in** [comment]
I use bios, I even changed 60 fps to native fps etc but nothing changes it

**Comment by endrift** [comment]
I wonder if there's something wrong with the BIOS dump you're using. Does the boot logo show up? If you have the log viewer open (under tools), with INFO checked, when you load the ROM does it say "Official GBA BIOS detected"?

**Comment by ro66in** [comment]
Yup it says official gba bios, and the bios logo shows up normal.. dumps come from latest no intro packs

**Comment by endrift** [comment]
Very strange. Can you upload your save file? You'll need to zip it before it lets you attach it.

**Comment by ro66in** [comment]
I have to connect phone to pc first, but during the bug, i get alot of error message in log game error gba memory bad bios load8 32 etc

**Comment by ro66in** [comment]
But when i start log says offi bios detected, but the error messages when the bug accurs in the log suggest bad bios? So i may try a different bios then

**Comment by endrift** [comment]
Do you not have a web browser on your PC?

And yeah, those error messages are just an indication that the game isn't particularly well programmed. That's why it's marked as "game error"; it's a problem with the game itself, not the emulation of the game.

**Comment by ro66in** [comment]
Yea I have a webbrowser on my pc, i am just not fond of turning on pc internet and microsoft trying to download all kinds of updates and edge bs

**Comment by ro66in** [comment]
[mariovsdonkeysave.zip](https://github.com/mgba-emu/mgba/files/5558886/mariovsdonkeysave.zip)

**Comment by endrift** [comment]
Same thing. I'm very, very confused now.
![2mm2](https://user-images.githubusercontent.com/605502/99508416-689e1f80-2939-11eb-9ef0-08b1e2a8a6a0.png)

(if you see them, ignore the weird white trails; that's a bug in the browser's (Firefox in my case) APNG decoder)

**Comment by ro66in** [comment]
Thats the cutscene I dont see, yea strange

**Comment by endrift** [comment]
I'm assuming that if you go to the ROM info dialog (under the File menu) it says the CRC32 is 7C2B5269?

**Comment by ro66in** [comment]
I just used a build and the cutscene works alright, maybe becaus I copied latest version of mgba over older version?

**Comment by ro66in** [comment]
yup thats the right checksum

**Comment by ro66in** [comment]
Yea works in a dev build I downloaded

**Comment by ro66in** [comment]
Just not the stable release I use

**Comment by ro66in** [comment]
I will just use the dev build to play it then.. thanks for your time, still.. v strange huh

**Comment by ro66in** [comment]
I am sorry I found what caused it , in enhancements I had the vid on opengl, I changed to software and it works fine..

**Comment by endrift** [comment]
This was apparently fixed by 9902e2eeeed324eecf813b4dd93ceafc03fc6ae7 but I didn't retest afterwards.
