### ISSUE TITLE
implement correct window 1 & 0 behavior

### ISSUE THREAD

**Issue by destoer** [mgba-emu/mgba#1945]
hi wrote a test to see how the gba actually checks for window start and end

https://github.com/destoer/gba_tests/tree/master/window_midframe

**Comment by endrift** [comment]
This appears to affect the game Combat Choro Q, which is very definitely displayed wrong in mGBA at the moment.

**Comment by endrift** [comment]
I'm not going to be able to implement the mid-vblank changes in mGBA 0.11, but I can improve the statefulness.
