### ISSUE TITLE
Item in Pokemon causing game crash

### ISSUE THREAD

**Issue by Drake356** [mgba-emu/mgba#1948]
In the game Pokemon Altered Emerald two specific items cause my game to crash each time I scroll down through my bag over them. They are the Electirizer and the Safety Specs as shown in first image. The crash message I get after each time is shown in the 2nd image. I don't exactly know how to extract the saves from the game but I have the full game, but don't know if I can upload it or not without getting in trouble.

I should also note that I opened the game in VBA-m and it was able to scroll over the items just fine. When I dropped both of those items and saved I was able to continue playing on mGBA.

![image](https://user-images.githubusercontent.com/11483055/100002337-0ce4f380-2d8a-11eb-919f-d26b9a0ad817.png)

![image](https://user-images.githubusercontent.com/11483055/100002389-1bcba600-2d8a-11eb-8076-332c174e9576.png)

**Comment by endrift** [comment]
Save files are by default put in the same directory as the ROM, and I'll need that to diagnose the issue.

As for VBA-M, most of these ROM hacks are only tested on VBA, so that's not surprising; often they break on hardware an emulators that are more accurate than VBA.

**Comment by Drake356** [comment]
Here is the save file. Do you need the ROM as well?
 Also it seems it was only the Safety Specs causing it.
[altered-emerald-v3.07c.zip](https://github.com/mgba-emu/mgba/files/5602733/altered-emerald-v3.07c.zip)

**Comment by Drake356** [comment]
I might have lost the save like an idiot...Give me a bit to get it back.

**Comment by Drake356** [comment]
Alright I got it. Will you need the ROM as well?
[altered-emerald-v3.07c.zip](https://github.com/mgba-emu/mgba/files/5613415/altered-emerald-v3.07c.zip)

**Comment by endrift** [comment]
I will try to find the patch for the hack myself.

**Comment by Ammako** [comment]
This crashes on real hardware as well
