### ISSUE TITLE
Emulation starts before debugger has settled

### ISSUE THREAD

**Issue by felixjones** [mgba-emu/mgba#1950]
8:10 in my video shows this: https://youtu.be/ZFRWBSMC5eI?t=490

At the moment this means I have to add an artificial delay at the start of the program to wait for everything to settle before my breakpoints work. This also means I can't place a reliable breakpoint at the very start of the program, at the entry point.

This happens with CLion, VSCode and Visual Studio.

**Comment by endrift** [comment]
Yeah, this is a problem with the core starting on a second thread, and program flow on the main thread doesn't get to the debugger on the main thread until the CPU thread has had a little time to spin. I'll see if I can add a way to block startup when needed.

**Comment by endrift** [comment]
This ended up being easier than I thought. Whoops.
