### ISSUE TITLE
[3DS CIA] No sound at all after update to 0.8.4 

### ISSUE THREAD

**Issue by Shazoo** [mgba-emu/mgba#1955]
Under 0.8.3, sound was good . 

My operation flow : 
1. remove 0.8.3 via the system built-in data manager . 
2. install 0.8.4 via dev menu . 
3. all the gba game lost their sound . 
4. remove 0.8.4 via the system built-in data manager .
5. install the nighty version 
6. no sound 
7. remove nighty version via the system built-in data manager . 
8. reinstall 0.8.3 
9. ** no sound ** 

Any suggestion ? Thanks .

**Comment by endrift** [comment]
Are you sure you were using 0.8.3 before? I removed CSND support a while ago, so now it needs the DSP blob (see the FAQ on the website), but if it was working on 0.8.3 I presume you've already dumped that.

**Comment by Shazoo** [comment]
Thanks . I re-dump the dsp with dsp1.cia and 0.8.4 works well again . 

I think it caused by my homebrew code which destroyed a lot of another packages month ago ...
