### ISSUE TITLE
UMLAL with rd_hi = rd_lo yields wrong result

### ISSUE THREAD

**Issue by ladystarbreeze** [mgba-emu/mgba#1956]
In mGBA 0.8.4, the `UMLAL` instruction yields incorrect results when `rd_hi` and `rd_lo` are the same register.
On hardware (3DS + open-agb-firm), `UMLAL r4, r4, r4, r4` with `r4 = 20001h` sets `r4` to `20005h`. mGBA sets `r4` to `60006h`. Presumably, this is the correct order of operations:

```
a = do_unsigned_long_multiplication(rm, rs)
a += concat(rd_hi, rd_lo)
rd_lo = a_lo
rd_hi = a_hi
```

![3ds_gba_umlal](https://user-images.githubusercontent.com/51570316/100525138-613f0780-31be-11eb-96ac-cbcb1311756c.png)

![mgba_umlal](https://user-images.githubusercontent.com/51570316/100525159-a400df80-31be-11eb-9765-8b976f2f86aa.png)

**Comment by endrift** [comment]
Can you please actually upload the test ROM so I don't have to make one myself?

**Comment by ladystarbreeze** [comment]
Sorry, here's the test ROM.

[umlal.zip](https://github.com/mgba-emu/mgba/files/5611264/umlal.zip)
