### ISSUE TITLE
[3DS][Query] Slow ROM open since the addition of a "Loading" screen when opening a ROM, version ~0.7

### ISSUE THREAD

**Issue by Searinox** [mgba-emu/mgba#1957]
A "Loading" screen was added to the emulator around the time of version 0.7 or such. Before then, ROMs used to load very quickly. Since then, a selected ROM takes quite a long time to load and start. The "Loading" screen displays a percentage of completion, and the progress is slow. Is the slowdown that was introduced unavoidable and necessary for the better emulation or is this unintended and potentially improvable?

**Comment by profi200** [comment]
Can confirm this. Updated recently and noticed the slow loading times. First thought this has something to do with save states but had them disabled.

**Comment by endrift** [comment]
There has always been a loading screen, but the percentage was added in 0.8 IIRC. I tried to make it only update after every large chunk, but I suppose it's possible that the chunk size is still too small.

**Comment by Searinox** [comment]
I can't comment on the back-end of how things work since I can only take note of the cosmetics of the "Loading" screen. However, when it was added, it coincided with a very marked slowdown in ROM loading as well. Again I cannot comment on whether the screen itself is linked to the degradation, I would just like to note that when that was done, it was accompanied by a very big degradation in ROM loading performance.

**Comment by endrift** [comment]
Yeah, I'll look into it later today.
