### ISSUE TITLE
Loading The Final Fantasy Legend (USA) without a BIOS causes a few seconds of broken graphics. 

### ISSUE THREAD

**Issue by Tiberius1437** [mgba-emu/mgba#1958]
![Capture](https://user-images.githubusercontent.com/68873449/100734194-618c0c80-3423-11eb-91db-816d0a9a117a.PNG)

**Comment by Testsr** [comment]
Can you check the stable verision 0.8.4 and see if that version has the same bug.

**Comment by Tiberius1437** [comment]
It doesn't.

**Comment by Testsr** [comment]
@endrift, I have bisected the regression to commit 4baa8b3d9b5ecf411d65d5f53d5ec705b926d6dc.

**Comment by endrift** [comment]
Good catch. Thanks for bisecting.
