### ISSUE TITLE
RetroArch version doesn't track RTC correctly in GBC games

### ISSUE THREAD

**Issue by Megabobster** [mgba-emu/mgba#1959]
I have found this issue to be present in RetroArch 1.9.0 with mGBA 0.8.3 (latest core currently available) on Windows 10 x64. It is not present in the standard desktop build of 0.8.3 or 0.8.4 (Windows x64). It is not present in other RetroArch GBC cores (I tested Gambatte specifically), though the RTC time is offset compared to mGBA (#1295?).

Whenever I load Pokemon Silver or Crystal (or the romhack Crystal Clear), instead of telling me the current time, it says "TIME NOT SET" and prompts me to set the time before loading my saved game. Saving and exiting after resetting the clock does not seem to resolve this. I tested on Pokemon Ruby and Sapphire (GBA games, though the RTC is used less significantly) and those seem to track properly, or at least I am not prompted about it and the in-game clock is functional. Oddly, after I set the clock and save and exit the first time, it will (usually) still start with the correct time when asking me to reset the clock.

[Here is what happens when I set the clock.](https://www.youtube.com/watch?v=j-yHI1MUm6k)

[Here is what happened immediately after that when I closed and re-opened the game.](https://www.youtube.com/watch?v=tbfbF5LRwUo)

[Here is what happened after I then set the core to Gambatte.](https://www.youtube.com/watch?v=xReORWj0sUY)

May be related to #1134 but as I said it seems to work properly for GBA games.

**Comment by endrift** [comment]
Fixed, but it's probably gonna cause massive merge conflicts with downstream.

Ah well, I warned them.

**Comment by Megabobster** [comment]
Awesome, thanks!
