### ISSUE TITLE
Game name and framerate aren't shown when the display driver is set to software QT

### ISSUE THREAD

**Issue by Tiberius1437** [mgba-emu/mgba#1965]
![Capture](https://user-images.githubusercontent.com/68873449/101013734-d8a6d980-35b8-11eb-821d-b2d31da7b173.PNG)

![Capture2](https://user-images.githubusercontent.com/68873449/101013752-de042400-35b8-11eb-8487-aacebec0da08.PNG)

**Comment by Testsr** [comment]
This issue is because the Dynamic Title Flag is not auto set when opening the settings menu.

**Comment by endrift** [comment]
I think the first time you save the settings, if you didn't touch this flag it gets disabled. I keep forgetting to fix that.
