### ISSUE TITLE
OpenEmu Can't Communicate With Core

### ISSUE THREAD

**Issue by joshvickerson** [mgba-emu/mgba#197]
Following c2340bb, OpenEmu is able to run with the mgba core installed. I am, however, unable to run a game using the core. I get a "couldn't communicate with helper application" error. Is there anything else I can provide you to help debug the issue?

![screen shot 2016-01-03 at 4 11 39 pm](https://cloud.githubusercontent.com/assets/2325487/12081108/d7b59162-b235-11e5-9a88-9c6bbaa12bc4.png)

**Comment by endrift** [comment]
The output of Console searching for "OpenEmu" would be helpful, including crashlogs if applicable.

**Comment by joshvickerson** [comment]
Here's the Console output. Looks like the problem is it can't find the mgba executable.

1/3/16 4:11:37.866 PM OpenEmu[7699]: Cannot find executable for CFBundle 0x7fab3d01cf00 </Users/josh/Library/Application Support/OpenEmu/Cores/mGBA.oecoreplugin> (not loaded)
1/3/16 4:11:38.018 PM OpenEmuHelperApp[7702]: parent application is: OpenEmu
1/3/16 4:11:38.021 PM OpenEmuHelperApp[7702]: Apple Internal Keyboard / Trackpad
1/3/16 4:11:38.048 PM OpenEmuHelperApp[7702]: Cannot find executable for CFBundle 0x7f8990c4f180 </Users/josh/Library/Application Support/OpenEmu/Cores/mGBA.oecoreplugin> (not loaded)
1/3/16 4:11:38.063 PM OpenEmuHelperApp[7702]: ROM did not load.
1/3/16 4:11:38.064 PM OpenEmuHelperApp[7702]: <NSXPCConnection: 0x7f8990d0c710> connection from pid 7699: Warning: Exception caught during invocation of received message, dropping incoming message and invalidating the connection.
Exception: *** -[NSProxy methodSignatureForSelector:] called!
1/3/16 4:11:38.064 PM OpenEmu[7699]: Helper Connection (0x7fab3f135260) failed with error: Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 0" UserInfo={NSDebugDescription=connection from pid 0}
1/3/16 4:11:41.860 PM OpenEmu[7699]: Deallocating proxy: <OEThreadProxy 0x7fab3af7bda0, target: <OEGameDocument 0x7fab3af664c0, ROM: 'Pokemon Ruby', System: 'openemu.system.gba', Core: 'com.endrift.mgba'>>

Is it possible I missed something while building?

**Comment by endrift** [comment]
Seems to work for me. Did you copy the core over properly? Can you `ls -R` the directory and paste that?

**Comment by joshvickerson** [comment]
I must have built it wrong. The executable is missing, and I just noticed the built core is only 1kb in size.

ls -R output:

mGBA.oecoreplugin josh$ ls -R
Contents

./Contents:
Info.plist	MacOS

./Contents/MacOS:

**Comment by endrift** [comment]
Yeah, that's cmake preparing the bundle, but the bundle hasn't been actually fully created yet.
