### ISSUE TITLE
Wii emulation on gba pokemon games

### ISSUE THREAD

**Issue by HoneyCatto** [mgba-emu/mgba#1972]
When I use the latest version for the wii homebrew I try playing a pokemon game but when I enter a battle on this build it freezes a few times and makes horrible sounds and it tends to happen a lot more when I load a save state and enter battle, hoping this gets fixed in next build 👍

**Comment by endrift** [comment]
Which games? Were they ROM hacks? By latest do you mean 0.8.4, or a development build?

**Comment by endrift** [comment]
Closing due to lack of reply.
