### ISSUE TITLE
The win64 installer exe still says 0.8.3

### ISSUE THREAD

**Issue by TheGinGear** [mgba-emu/mgba#1973]
![image](https://user-images.githubusercontent.com/39550332/101538024-1eb9bf80-3962-11eb-9a5b-73ec9bc8ca77.png)
It still installs 0.8.4 normally, It's literally just a typo

**Comment by endrift** [comment]
It's not a typo (technically speaking), and it can't be fixed without rolling a new release. See discussion in #1923.
