### ISSUE TITLE
mGBA on Windows 10 does not open on the latest development version.

### ISSUE THREAD

**Issue by Testsr** [mgba-emu/mgba#1974]
Version 67f8197493dd3f978b96f69ad1eabfc1d674de69 is the last version that opens.

**Comment by Testsr** [comment]
Version 67f8197493dd3f978b96f69ad1eabfc1d674de69 is the last version that opens.

**Comment by Testsr** [comment]
Backtrace of issue.
0x00000000663bb2a4 in sqlite3_finalize ()
   from C:\msys64\mingw64\bin\libsqlite3-0.dll
(gdb) backtrace
#0  0x00000000663bb2a4 in sqlite3_finalize ()
   from C:\msys64\mingw64\bin\libsqlite3-0.dll
#1  0x00000000702c6aff in NoIntroDBLoad ()
   from C:\msys64\home\User\mgba\build\libmgba.dll
#2  0x0000000000436fb5 in QGBA::GBAApp::reloadGameDB() ()
#3  0x0000000000437de0 in QGBA::GBAApp::GBAApp(int&, char**, QGBA::ConfigController*) ()
#4  0x000000000055e550 in main ()
(gdb)

**Comment by endrift** [comment]
I already know what the issue is and will have a fix in less than an hour, most likely. In the meantime you can work around it with portable mode.
