### ISSUE TITLE
The Smurfs (SGB) - Game won't start

### ISSUE THREAD

**Issue by tuzepoito** [mgba-emu/mgba#1982]
When launching Super Game Boy version"The Smurfs", the game will simply not start, and only a blank screen is displayed. When disabling Super Game Boy emulation, the result is the same. Other SGB games will work fine.

Software : mGBA 0.8.4, Windows 64-bit, portable version.
Platform : Windows 8.1 (64-bit)
Title name : "Smurfs, The (USA, Europe) (En,Fr,De) (Rev 1) (SGB Enhanced)"
SHA-256 sum : 5d9c9ce079923b92034c7c2d172b5abfad9ec37332102cb247ea849393db9a99

**Comment by endrift** [comment]
This was fixed quite some time ago, but the fix wasn't able to be merged into the point releases; it works in dev builds and will work in 0.9. More info here: https://github.com/mgba-emu/mgba/issues/1772#issuecomment-640136908
