### ISSUE TITLE
Building with Docker

### ISSUE THREAD

**Issue by hgdagon** [mgba-emu/mgba#1985]
OK, I'm not familiar with Docker at all (don't kill me). In fact, before reading up on it today, I thought it was like flatpak/snap.

That said, it seems there's not a lot that can go wrong. So, I installed docker desktop, tested it on `docker/getting-started`. Now, when I'm running this:
```
docker run --rm -t -v D:\msys64\home\George\mgba\src mgba/windows:w64
```
I get:
```
mkdir: cannot create directory 'build-win64': Permission denied
```

Same for `w32`.  I tried substituting `\` for `/`, but that didn't do anything.
Starting an issue here, since I'm not sure if it's an issue with Docker or the images (or me).

**Comment by endrift** [comment]
Docker for Windows is very unhappy when you use a volume outside of the home directory. Further, you've got the syntax for the volume flag wrong. It's supposed to be the host location on the left of the colon and the container location on the right. Further, the container location _must_ be the same as what's in the REAME for it to work.

**Comment by endrift** [comment]
![image](https://user-images.githubusercontent.com/605502/102028869-016d6280-3d61-11eb-8912-a2a21615b0ba.png)

You can see in this image of the Docker Desktop GUI that I have `D:\msys32\home\Vi\mgba` mounted to `/home/mgba/src`. You'll need to do something similar with your container.

**Comment by hgdagon** [comment]
> Further, you've got the syntax for the volume flag wrong. It's supposed to be the host location on the left of the colon and the container location on the right.

So it *is* an issue with my eyes. I was a bit confused with that volume. It's running now. Reeeally slowly, but running.

**Comment by endrift** [comment]
You can run it with `-e MAKEFLAGS=-j4` to build with four cores instead of one, etc, though you have to put those arguments _before_ the name of the image (in this case `mgba/windows:w64`)
