### ISSUE TITLE
Broken text with memory viewer on macOS

### ISSUE THREAD

**Issue by felixjones** [mgba-emu/mgba#1987]
This is on `0.9-6703-beba0cb2c`
![Screenshot 2020-12-15 at 20 57 09](https://user-images.githubusercontent.com/1824671/102272194-4982b580-3f18-11eb-8d87-22fca5fa7acf.png)

**Comment by endrift** [comment]
Looks like it's having trouble with using the right font.

**Comment by endrift** [comment]
Do you have the ability to compile mGBA yourself right now? If so, can you see if changing `QFont::Monospace` to `QFont::TypeWriter` near the top of MemoryModel.cpp?

**Comment by endrift** [comment]
Forgot to mention; this should be (indirectly) fixed by 71379aac66f002e8bc87bc3bc936fbfc4b688b27, but if it's not there's a bigger problem (though an easier to solve one this time).
