### ISSUE TITLE
_neon2x may be incorrect

### ISSUE THREAD

**Issue by easyaspi314** [mgba-emu/mgba#1989]
I am concerned about the `_neon2x` function.

Specifically, if we go in with `r1` being `(uint16_t[]){ 0,1,2,3,4,5,6,7 }`, running this neon code:

https://github.com/mgba-emu/mgba/blob/2770b654f5f1fe70ac5ddcf1d0742ef004345781/src/util/arm-algo.S#L19-L25

Would result in `r0` and `r5` both being `(uint16_t[]){ 0,0,1,1,2,2,3,3 }`.

I believe that this is a typo, and if it isn't, it is very inefficient.

**Comment by easyaspi314** [comment]
If the goal was to get `r0` to `{0,0,1,1,2,2,3,3}` and `r5` to `{4,4,5,5,6,6,7,7}`, perhaps this is intended:
```asm
 vld1.16 {d0, d1}, [r1]! 
 vmov q1, q0
 vst2.16 {d0, d2}, [r0]! 
 vst2.16 {d1, d3}, [r5]!
```
(Or this depending on how fast `vst2` is)
```asm
 vld1.16 {d0, d1}, [r1]! 
 vmov q1, q0
 vzip.16 q0, q1 
 vst1.16 {q0}, [r0]! 
 vst1.16 {q1}, [r5]!
```

**Comment by easyaspi314** [comment]
Actually, looking at its only usage in `sw-sdl1.c`, it wouldn't even compile. It should just be removed.

**Comment by endrift** [comment]
You're right, it should be removed. It's not included in the build anymore and I didn't realize it was still in the source tree.

**Comment by easyaspi314** [comment]
Making a pr now.
