### ISSUE TITLE
[Wii] Gamecube controller input error

### ISSUE THREAD

**Issue by GB-CG** [mgba-emu/mgba#199]
Since the 3128 Build onward, The Gamecube pad (DOL-003)'s D-Pad Left acts like the left button and the A button simultaneously. The official Wiimote works fine. Here's my config:

[input.GCN1]
keyB=9
axisUpAxis=+1
keyStart=12
axisUpValue=64
keyRight=1
keyA=8
keyUp=3
keyLeft=0
keyL=6
keyR=5
keySelect=10
axisRightAxis=+0
axisDownAxis=-1
axisLeftValue=-64
axisRightValue=64
axisDownValue=-64
keyDown=2
axisLeftAxis=-0

**Comment by GB-CG** [comment]
Ok, I seemed to have fixed it by deleting the config.ini in the mGBA folder.

**Comment by endrift** [comment]
There was one commit where it would write a bad value for the GCN2 (second set of buttons on the controller) values to the config file. I fixed it quickly, but it would require removing the config file to fix it. I guess you got hit by that :/

**Comment by GB-CG** [comment]
I've tried 3145, it's ok now. I didn't notice the GCN2 config actually.
