### ISSUE TITLE
Crash when saving in Pokémon RomHack "Pokémon Fuligin"

### ISSUE THREAD

**Issue by renecatharsis** [mgba-emu/mgba#1991]
The game crashes whenever I'm trying to heal up in a Pokémon Center in the FireRed RomHack "Pokémon Fuligin".
Since it's a hack it may technically not be an emulation issue and crash on hardware, too, I thought I'd report it anyway.

Edit, forgot to add:
Healing in another Pokémon Center doesn't cause a crash, could only force it in this one specifically.

Builds used: mGBA-0.8.4-win64 and dev build 6713-4ecf64a-win64
OS: Win10 Pro, 64-bit
System specs: Core i7-8750H, GeForce GTX 1060
ROM CRC: n/a

Log output with all log levels enabled says on crash:
```
[FATAL] GBA Memory:	Jumped to invalid address: E7E6D5D8
[WARN] GBA:	Illegal opcode: 0000b710
```

Attached a video of the crash and a savefile right in front of the healing NPC.
[fuligin-crash.zip](https://github.com/mgba-emu/mgba/files/5720201/fuligin-crash.zip)

**Comment by endrift** [comment]
I have confirmed that this crash also occurs on hardware, so it's unfortunately a bug with the ROM hack.
