### ISSUE TITLE
(GBC) Games with cartridge type 0xFE fail to create a save and RTC file

### ISSUE THREAD

**Issue by ds22x** [mgba-emu/mgba#1993]
Specifically Robopon - Sun Version and its Japanese sister games suffer from this problem, producing an in-game save error message.
The games will successfully create a save and RTC file when using Sameboy.

I know mGBA is primarily a GBA emulator, but I wanted to at least post this for the future.

**Comment by endrift** [comment]
HuC-3 support is pretty tricky. Latest dev builds should save but so far my attempts to actually reverse engineer the cartridge interface for RTC have met with limited success. While doing it I found that a bunch of SameBoy's assumptions are wrong, so I didn't want to just go and do it the same way SameBoy does.

**Comment by ds22x** [comment]
I see.
At least now I know why the games only seem to work with some emulators (even if the implementation isn't proper).

BTW, the most recent dev build (17253f5760f1dbdfc75b5fb4a2e91e124370c8de) still fails to save.
![mgba 17253f5760f1dbdfc75b5fb4a2e91e124370c8de](https://user-images.githubusercontent.com/45218067/103160250-b9bfef80-47d2-11eb-8732-8272aa2453da.jpg)

In any case, I hope it can be made working in the future, but I perfectly understand if it doesn't get done any time soon, seeing it's not exactly a widely used mapper anyway.

**Comment by endrift** [comment]
Yeah, getting it working was on the list for 0.9 but getting it to work properly turned out to be [way more complicated than I expected](https://gbdev.gg8.se/forums/viewtopic.php?id=744) so it got bumped to 0.10.

**Comment by endrift** [comment]
This should be fixed in c829cd2e70eec9f37ecf6e83c674a193afeed035. Please retest.

**Comment by ds22x** [comment]
Robopon - Sun Version saves and loads fine now.
