### ISSUE TITLE
Multiplayer window not working and persistent window glitch

### ISSUE THREAD

**Issue by jordonia** [mgba-emu/mgba#1994]
I was using the cheats tool and now whenever I start mGBA it opens in full screen, and opens a white window I cannot close. The multiplayer window option also no longer works. I've tried deleting the app and removing associated files, but the issue persists. I'm on OS X 10.15.4 using mGBA 0.8.4
<img width="562" alt="Screen Shot 2020-12-27 at 11 45 57 AM" src="https://user-images.githubusercontent.com/76641167/103175693-d4797f00-4839-11eb-82df-b362d7f01c09.png">
<img width="1462" alt="Screen Shot 2020-12-27 at 11 46 50 AM" src="https://user-images.githubusercontent.com/76641167/103175696-df341400-4839-11eb-985d-6ff52f5567cb.png">
<img width="1530" alt="Screen Shot 2020-12-27 at 11 50 43 AM" src="https://user-images.githubusercontent.com/76641167/103175697-e22f0480-4839-11eb-81c3-dde901eb2699.png">

**Comment by jordonia** [comment]
I tried the 0.9.0 build and get a crash, older versions all crash as well
https://pastebin.com/K5vyq6qt

**Comment by endrift** [comment]
The white window is a known issue (#1212) that I have been unable to track down. That said, you'll need to delete ~/.config/mgba for a clean install.

**Comment by jordonia** [comment]
The fresh install resolved all my issues, thank you. Thanks for the thread!
