### ISSUE TITLE
insta-crash

### ISSUE THREAD

**Issue by PhazonOverlord115** [mgba-emu/mgba#1995]
whenever i run any game on this software, it imminently crashes or shuts down

https://user-images.githubusercontent.com/71577297/103188831-e0d3fb00-487e-11eb-82e9-2d2917137073.mp4

**Comment by endrift** [comment]
Without knowing what's in your recent list I can't really do anything here. You'll need to find your qt.ini file, which should be in %AppData%/mGBA

**Comment by PhazonOverlord115** [comment]
ok I see it, now what do i do with the "qt.ini" file?

**Comment by endrift** [comment]
I need the contents of the `[mru]` section in that file.

**Comment by PhazonOverlord115** [comment]
ok i copied and pasted this from what you needed

[mru]
0=C:/Users/Phazon Overlord115/Desktop/games documents/game zips/metroid games/Metroid Fusion (USA).gba
1=C:\\Users\\Phazon Overlord115\\Desktop\\games documents\\game zips\\metroid games\\Metroid Fusion (USA).gba
2="C:\\Users\\Phazon Overlord115\\Desktop\\games documents\\game zips\\metroid games\\Classic NES Series - Metroid (USA, Europe).gba"
3="C:/Users/Phazon Overlord115/Desktop/games documents/game zips/metroid games/Classic NES Series - Metroid (USA, Europe).gba"

**Comment by endrift** [comment]
Though that MRU section looks a bit weird, there's nothing there that is obviously broken. It also looks like it was modified by two different sources though, so that's kind of strange. If you remove the section entirely does it stop crashing?

**Comment by PhazonOverlord115** [comment]
oh shoot im sorry about the wait, i recently wiped my drive because it was almost full, and now i need to do some more test later, im sorry.

**Comment by PhazonOverlord115** [comment]
nope it still crashes. and i only have metroid fusion installed to

**Comment by endrift** [comment]
Does it crash when you hover over the Recent section or just in general? Are there specific things that make it crash or just having it open long enough?

**Comment by PhazonOverlord115** [comment]
It only crashes when i launch a fame and no settings change the outcome ether

**Comment by PhazonOverlord115** [comment]
ok i have found a mod for a game that can do the same actions as your creation, and sorry for the inconvenience for leaving your product
