### ISSUE TITLE
mgba's UI makes me feel physically ill 

### ISSUE THREAD

**Issue by shoeshinerniggy666** [mgba-emu/mgba#1997]
I can't comment on the quality of the emulation itself but my god is it a bad look for people to boot up the emu and be greeted with that poorly laid out, confusing, butt ugly car wreck of a UI. It's less functional than Nesticle which came out over 20 years ago. I know programming and UI design are two different jobs and skill sets but there really is no excuse for the state of it. Overhaul the entire thing. Burn it down and start from scratch.

**Comment by endrift** [comment]
If you feel like writing a bug report that's not intentionally inflammatory, let me know, but given your username I suspect you don't.

**Comment by Tiberius1437** [comment]
Do you agree that it needs to be overhauled?

**Comment by Tiberius1437** [comment]
Besides if I was polite you'd have just ignored me like the other 435 issues.
