### ISSUE TITLE
Loading ROM in mgba-qt crashes the program on Ubuntu 15.04

### ISSUE THREAD

**Issue by guineawheek** [mgba-emu/mgba#20]
Opening a ROM in the qt dialog exits leaving a terminal message reading:
```mgba-qt: symbol lookup error: mgba-qt: undefined symbol: VDirOpenZip```

**Comment by endrift** [comment]
Muhhh...that symbol totally exists in libmgba.so. Is it not being loaded properly at runtime, I wonder? Try running with `LD_DEBUG=libs` (this will produce a lot of output, so pipe stderr to a file) and pastebin that.

**Comment by guineawheek** [comment]
http://pastebin.com/NeSWfw6m

**Comment by endrift** [comment]
Hmm, that looks okay. Which build are you using? Self-compiled or a nightly? Which nightly, if a nightly? I've tested one of them in a VM and it seems to work, but I don't have time at the moment to test the other.

**Comment by guineawheek** [comment]
It's the adee44f6e998ebf01c0e539bc5a5fca5d8e37168 nightly. The previous nightly (73d2c8fda8b7d324ab2b338b17bd10d36651f0f4) used also ran into the same issue.

**Comment by endrift** [comment]
Found the problem. It's trying to dynamically link against /usr/local/lib/libmgba.so.0.3, which is more than likely a version you built yourself (since the .deb puts it in /usr/lib); please remove it and see if you still have this problem.

**Comment by guineawheek** [comment]
DERP! It worked! Should've been the first thing I checked. Sorry.
Out of all the alternatives on Linux, this is the only emulator that manages to save and load Pokemon Emerald properly, so very nice work!
