### ISSUE TITLE
I accidentally reset a setting and now I can't see my screen but audio is there

### ISSUE THREAD

**Issue by guramon** [mgba-emu/mgba#2002]
I accidentally changed something and I can't see video anymore. All I need really is a pic of the Wii versions in game settings menu, that way I can fix the setting without needing to see. Thanks

**Comment by endrift** [comment]
It'll take me a bit to get this to you but in the meantime you can try running it in Dolphin

**Comment by guramon** [comment]
My situation is kinda weird, I don't have a pc, and the only way I can download things is a shitty laptop the school gave me that blocks every website, and If I really want something, I have to go to some shady sites. Is there something I can use that's in homebrew browser?

**Comment by Maesejesus** [comment]
Why not erase the configuration file? or not even that, rename it to something else. Then launch again the emulator and it will launch with default settings. You can erase or rename it with WiiXplorer from the Wii itself, if you can access that.

**Comment by endrift** [comment]
@guramon sorry for the delay. If you can use a text editor to edit mGBA/config.ini, change the videoMode setting to 0. I can also get you screenshots of the menus if that's easier.

**Comment by endrift** [comment]
This isn't really a valid bug report anyway, but I can still try and help, especially on Discord.
