### ISSUE TITLE
When you open a ROM with mGBA directly on Windows, config.ini doesn't seem to be read

### ISSUE THREAD

**Issue by LOuroboros** [mgba-emu/mgba#2009]
I have a portable installation of mGBA with my desired configuration for things like keys and other stuff.
The thing is that if I set my .gba ROMs to "Open with" mGBA on Windows' Properties. my configuration for mGBA is not present.
What I mean, is that mGBA seems to be booting up with its default configuration. None of the keys I have in my installation work. Z is B when it should be A, for example.
When I go, open mGBA and then my ROM on it, the configuration from config.ini is being read normally though.

It's something that doesn't really happen with other emulators I use or used like VBA, NO$GBA, Desmume, BSnes, et cetera, so I thought I should open an issue for it.

**EDIT**: Additionally, it seems that mGBA creates files of its own in the folder where the ROM is located after opening it like this.
Namely: `config.ini`, `library.sqlite3`, `nointro.sqlite3` and `qt.ini`.

**Comment by endrift** [comment]
Hm, so it properly detects that it's in portable mode but doesn't properly detect where that portable mode is supposed to be. I changed a bunch of this codepath in dev builds. Can you see if it behaves differently with the dev builds instead of stable (assuming you're not already using a dev build)?

**Comment by LOuroboros** [comment]
> 
> 
> Hm, so it properly detects that it's in portable mode but doesn't properly detect where that portable mode is supposed to be. I changed a bunch of this codepath in dev builds. Can you see if it behaves differently with the dev builds instead of stable (assuming you're not already using a dev build)?

I was already using a dev build, yes. I just downloaded the latest one, and it doesn't seem to behave any differently.

https://user-images.githubusercontent.com/4485172/104464502-c2b20e80-5591-11eb-857c-05137f8eeed0.mp4

**Comment by endrift** [comment]
Yeah, this looks to confirm what I was saying. I'll take a closer look shortly. I want to fix this for 0.9.
