### ISSUE TITLE
mGBA controller setup is extremely buggy, and makes mGBA crash

### ISSUE THREAD

**Issue by vgturtle127** [mgba-emu/mgba#201]
I have tried to setup an Xbox One controller, a PS4 controller through DS4Windows, a PS3 controller through BetterDS3, a Logitech F310, and a few USB SNES controllers, and it won't recognize any of them. Not only that, but when I close the dialog it sometimes crashes. Sometimes it crashes after I try to launch a game with a controller plugged in, and sometimes it crashes the first time I press a button in a game.

I'm not sure if it is just the fact I'm using a development build (0.4-3145-b6f1ddc), or if it was always like that and it just hasn't been fixed yet, or nobody knew it was like this...I don't know.

Is anybody else having these problems?

I am on 64-bit Windows 10 Pro. I can give you any information you want or need, I just don't want to post a huge wall of text if you guys don't like that in your email.

Anyway, any help would be appreciated.

**Comment by endrift** [comment]
Try using an older build (0.4-3141 or before, should just be the previous day) and seeing if that changes anything.

**Comment by vgturtle127** [comment]
@endrift That build just disconnects my controllers and then tries to reconnect them. I really don't know what would cause this. :confounded:

**Comment by autofire372** [comment]
I'm on Windows 8.1, and I've got a Razer Sabertooth Elite that mgba isn't seeing.

**Comment by vgturtle127** [comment]
@autofire372 What build are you using?

**Comment by autofire372** [comment]
The latest nightly at time of writing.

**Comment by vgturtle127** [comment]
@autofire372 OK, just checking to see if you were on a newer or later build...

**Comment by endrift** [comment]
@autofire372 that's almost certainly function of which controllers SDL can detect, and not an mGBA bug unfortunately.

**Comment by vgturtle127** [comment]
If SDL can detect Xbox 360 controllers, it should be able to detect the Sabertooth. It's just an Xbox 360 controller with some modifications that make it better (better directional pad, better, more responsive buttons, etc.).

Is there a list of controllers SDL can detect? I have more than a few controllers, so I want to add all fo them if I can.

**Comment by endrift** [comment]
Lemme know if it's more stable in the next nightly. I think I've worked out most of the bugs.

**Comment by vgturtle127** [comment]
@endrift OK, will test and get back to you.

**Comment by autofire372** [comment]
Well... it's an improvement. I can map and use my Razer Sabertooth's inputs, but the emulator froze when I applied new hotkeys (using the Sabertooth's triggers for fast forward and rewind, if that matters). Strangely, the new settings took anyway.

Also, mgba froze when I tried to make a savestate.

**Comment by endrift** [comment]
Okay, next nightly should fix a lot more of the issues.

**Comment by autofire372** [comment]
Settings/"apply" still freezes mgba, and it still crashes when I try to save a state.

**Comment by vgturtle127** [comment]
@endrift mGBA doesn't recognize directional pad changes in the settings, but recognizes the changes in-game. mGBA also now recognizes my controller as 2 controllers, an XInput controller and a Wireless Controller. I am using it wired.

The controller input is also still going through when I am in the settings menu with a game loaded, which makes it hard to change settings when in-game.

Tested using latest nightly.

**Comment by endrift** [comment]
Apply button fixed in d6bccd80f724670c4c17ebf1615f440158ea12db.

**Comment by vgturtle127** [comment]
@endrift Controller support is still kind of janky. I can't get it to recognize my PS4 controller. Let me try my Xbox One controller and my Logitech F310.

Did you know shaders are broken as well?

I would take a screenshot with mGBA's screenshot function, but it now crashes mGBA and generates a corrupt image. :cry: 

![screenshot 4](https://cloud.githubusercontent.com/assets/3183676/12566857/7e67d374-c381-11e5-99d2-2cb76ad07f9e.png)

![screenshot 5](https://cloud.githubusercontent.com/assets/3183676/12566856/7e64ad02-c381-11e5-90b3-290b27519a09.png)

Unless that's intentional, but based on the description I would assume it isn't accurate to what you had in mind. :wink:

**Comment by endrift** [comment]
You know there's this thing called "filing a separate bug," right? Also, shaders aren't supposed to show up in screenshots.

**Comment by vgturtle127** [comment]
@endrift Sorry, I just didn't want to open another bug if it was just a small issue on my end. I will open a separate issue.

**Comment by endrift** [comment]
Final call, is mapping still broken/buggy for anyone?

**Comment by vgturtle127** [comment]
@endrift Everything seems to work OK in the latest build. Thanks, endrift.
