### ISSUE TITLE
How to use the e-reader?

### ISSUE THREAD

**Issue by anonymous7002** [mgba-emu/mgba#2014]
I haven't found any guide on mgba.

**Comment by Testsr** [comment]
@anonymous7002, Ask on the discord, not here.
@endrift Could you close this?

**Comment by endrift** [comment]
You need to have a dev build. It can't be done yet on 0.8.4, but there's a "scan card" menu option in the dev builds (and in 0.9 when that releases).

@Testsr Stop @ mentioning me passively aggressively (to the OP) telling me to close things. It helps no one. I I know this can be closed, I just hadn't gotten around to doing it yet. This is a warning.

**Comment by Testsr** [comment]
Understood the warning. I won't be mentioning you about closures.
