### ISSUE TITLE
Pokemon Rom Hack crashing for unknown reason

### ISSUE THREAD

**Issue by StarmanLord** [mgba-emu/mgba#2015]
I am currently playing Pokemon Fusion Origins, a FireRed rom hack, on mgba 0.8.4. Occasionally, and seemingly at random, the emulator crashes to the screen shown in the attached screenshot. Why is this happening? What can I do to prevent it? Let me know if you need any more information, thank you!
![Screenshot 2021-01-16 014516](https://user-images.githubusercontent.com/77527400/104806455-4db32480-579d-11eb-93a9-ab309a5c31fa.png)

**Comment by endrift** [comment]
Mm, ROM hacks are quite often buggy and will actually crash on hardware. They tend to be only tested on VBA, which has a lot of known issues. mGBA 0.9 (still in progress, though dev builds are available on the website) has a "compatibility" mode that is on by default for FireRed hacks that may help here.

**Comment by StarmanLord** [comment]
Thank you, I'll give the 0.9 dev build a try!

**Comment by endrift** [comment]
Does it work in the dev build?

**Comment by sodomon2** [comment]
Hello :)

I have a similar error (I would say the same) when playing the hackrom of Pokemon Liquid Crystal,the game crashes from time to time when loading a savestate.

the strangest thing is that it only crashes on version 0.9.0.

I tried it in version 0.8.3 and it doesn't crash so it seems that the error is in version 0.9.0.

Here is a screenshot

![mgba-error](https://user-images.githubusercontent.com/49420637/114502798-54b1cd80-9bfa-11eb-9c43-e2518a14ff74.png)

**Comment by endrift** [comment]
@sodomon2 that bug was likely fixed a week or two ago in the dev builds and will be fine in 0.9.1 when I release it in a week or so
