### ISSUE TITLE
Sound is off in Rock 'Em Sock 'Em Robots

### ISSUE THREAD

**Issue by vgturtle127** [mgba-emu/mgba#202]
The sound is kind of off in Rock 'Em Sock 'Em Robots (I played the US version).

It kind of crackles and pops when any audio is playing. I can make a video, if you want.

I am running 64-bit Windows 10 Pro, using mGBA 0.3.2.

If you need more info, let me know.

**Comment by endrift** [comment]
I can reproduce, but again, might just be the game being shovelware and not actually a bug.

**Comment by vgturtle127** [comment]
@endrift Would a log file help?

**Comment by endrift** [comment]
No. What would you be logging?

**Comment by vgturtle127** [comment]
@endrift Well, I didn't know if mGBA logged the emulated hardware or if the log just logs the emulator itself. I figured if it logged the emulated hardware, we could check for inconsistencies or bugs or whatever. I don't know, just trying to be helpful. :smile:
