### ISSUE TITLE
Save error

### ISSUE THREAD

**Issue by olimar5050** [mgba-emu/mgba#2022]
I just downloaded mgba last night, but I found that my game always starts up with a error that says "failed to open save file. is the save directory writable?" how do i fix this?

**Comment by endrift** [comment]
You can start by telling me which game

**Comment by olimar5050** [comment]
I only played the gen 1 pokemon games so far, yellow, red, and blue.

**Comment by endrift** [comment]
And to confirm, are you using the Windows version 0.8.4?

**Comment by olimar5050** [comment]
Yeah you got it

**Comment by Dimensional** [comment]
Is the emulator loading from a User directory or elsewhere, and if so, where is it running from? Also where is the rom stored? With the emulator or elsewhere, again if the latter where?

**Comment by endrift** [comment]
Oh, wait. Did you install it into program files and then drop the ROMs into that directory? That won't work. You need to put the ROMs somewhere else.

**Comment by endrift** [comment]
Closing due to lack of reply (and the large likelihood of the issue being the ROMs being located in Program Files, which mGBA itself cannot write to)
