### ISSUE TITLE
(Interface) Shortcuts like Ctrl+0 don't work in mgba when it's not running games

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2024]
1. Open mGBA.exe
2. Try to use ctrl+0 to open the last game (doesn't work).

In order to work, you have to click the menu bar (File, Emulator, Tools... or even the white space in the bar) first, or do it while running a ROM.

**Comment by endrift** [comment]
I use this shortcut routinely. I'm not sure what's going on for you?

**Comment by RafaelTrepaUnCarballo** [comment]
It doesn't happen anymore. Maybe it's Windows 10, which sometimes behaves strangely with newly opened windows.
Sorry for the inconvenience.
