### ISSUE TITLE
LSDJ compatibility

### ISSUE THREAD

**Issue by Appalachgrove** [mgba-emu/mgba#2029]
Build: 0.8.4
OS: Mac Mojave 10.14.6
Core i5 1536MB

Hi! I use LSDj on Gameboy emulators (a GB music maker/tracker), and am experiencing some basic functionality that isn't existing. I've attached a video (slight volume warning) in which the notes are programmed to have a volume fade-out but are instead staying static, they should also be stopping completely when the marker hits the K00 on the right of the screen.

https://user-images.githubusercontent.com/78027144/105848347-f3cf1c00-6032-11eb-982f-986811fa9290.mp4

Is this a known issue? I'm happy to explain further if not. I would love have LSDJ supported as this is the only emulator I've found for mac that opens 2 instances for link-cabling. Thanks!

**Comment by endrift** [comment]
Hmm, weird. That feature should work but it has some strange edge cases. Can you provide me the save file? I believe I bought a copy of LSDj at some point so I should have the ROM somewhere.

**Comment by Appalachgrove** [comment]
OK, I've made some progress and perhaps gotten closer to the root of the problem:

The above video comes from an earlier build of LSDJ not considered "Stable" (v9.1.1). Attached in a zip with the .sav below:

[lsdj9_1_1 2.zip](https://github.com/mgba-emu/mgba/files/5877769/lsdj9_1_1.2.zip)

It does work as intended in other emulators, though. Earlier I did just download a fresh download of the most recent Stable build (8.5.1) and it actually works as intended, so I'll just use that one for my needs instead. Attached that in a zip with a little demo of it below:

[lsdj8_5_1-stable 2.zip](https://github.com/mgba-emu/mgba/files/5877781/lsdj8_5_1-stable.2.zip)

LSDJ has recently moved to a "free to download" model on their own website, so I'm going under the assumption that including the specific build's ROM in the zip file is alright for these purposes. Thanks!

**Comment by INFU-AV** [comment]
LSDj versions above 8.7.7 utilise "Zombie" mode envelopes in order to expand possible volume envelope range.
More about the mode can be found here:
https://gbdev.gg8.se/wiki/articles/Gameboy_sound_hardware#Obscure_Behavior

Even though site warns that trick doesn't work on some consoles, LSDj sucessfully performs this trick on all available official Gameboy hardware, and accurate emulators like BGB, Sameboy, Gambatte

Implementing this feature would mean step closer to accuracy of mgba

**Comment by endrift** [comment]
I do implement zombie mode (to some extent) but I believe it's disabled on GBC based on what that page said, which I guess is wrong.

**Comment by djmaximum17** [comment]
or Maybe NEZplug++ could be used for gameboy sound emulation. http://offgao.net/program/nezplug++.html
