### ISSUE TITLE
Glitches in Afro Thunders hair in Ready To Rumble Boxing Round 2

### ISSUE THREAD

**Issue by vgturtle127** [mgba-emu/mgba#203]
His hair gets a yellow square around it sometimes:

![0030 - ready 2 rumble boxing - round 2 u eurasia -1](https://cloud.githubusercontent.com/assets/3183676/12257725/8235804a-b8ce-11e5-8910-ef89409f930a.png)

There are other glitches too, mainly with the intros they have before the match.

Running 64-bit Windows 10 Pro with mGBA 0.3.2.

Any more info you need, let me know.

**Comment by endrift** [comment]
His hair is being given the wrong palette for that box. Also happens in VBA and no$gba, so I'd imagine it's just shovelware being buggy.

**Comment by vgturtle127** [comment]
@endrift If it happened on real hardware, I never noticed it. Maybe some weird hardware limitation/bug the devs had to hack around?

**Comment by endrift** [comment]
Limitation, maybe, but unlikely. Bug? Bad palette management. It might just be too dark on the original GBA to notice.

**Comment by vgturtle127** [comment]
It doesn't happen on other boxers as far as I know, would you like a log file? Also, let me go through all the other boxers and see if I notice anything weird.

**Comment by endrift** [comment]
There's nothing to log. It's not useful to give me a log file.

**Comment by vgturtle127** [comment]
@endrift OK. Let me check the other boxers. I'm pretty sure its just Afro Thunder.

**Comment by vgturtle127** [comment]
@endrift Actually, its Afro Thunder, Mama Tua, Rumble Man, and Michael Jackson. Shaquille 'O Neal, Lulu Valentine, Raging Rivera, Jet Iron Chin, Johnny Blood, Robox Rese4, and Joey T are all unaffected by this glitch.

The worst glitches are from Rumble Man, Afro Thunder, and Mama Tua. But sometimes Mama Tua doesn't get affected as much by it, especially in lighter arenas.

Michael Jackson only has some minor pixel glitches, which is probably more the limitations of the GBA then anything.

This game does have 3D arenas, by the way. Well, simulated with sprites, but still fairly resource intensive.

**Comment by LuciaBunny** [comment]
I just tested it on my DS Lite in GBA mode. Happens there too, so it's probably the game's fault.

**Comment by endrift** [comment]
Thanks @LuciaBunny. The DS Lite has no errata compared to the GBA, so that shows it's a game bug, not an emulation bug.
