### ISSUE TITLE
MGBA vita everytime I 30 seconds on inactivity causes the emulator to darkken my screen

### ISSUE THREAD

**Issue by CommicKick69ing** [mgba-emu/mgba#2030]
Its not the vita its self becuase the standby settings have been set to 15 min and mgba is the only app darkening my screen after 30 seconds. How do I turn this off the screen darking feature in mgba becuase do far I can find anything.

**Comment by endrift** [comment]
This is not a feature mGBA has, the Vita dims the screen on its own.
