### ISSUE TITLE
SEGFAULT while saving/loading state

### ISSUE THREAD

**Issue by Farlander-001** [mgba-emu/mgba#2031]
This issue happens on both 0.8.3 and latest 0.9-6763-6154ed91c. Saving state is successful, but mgba crashes anyway. BIOS is not used

OS: Linux Mint 20.1 (with all latest updates)
CPU: Intel Atom N570 (4) 1.667GHz
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Pineview M
OpenGL version string: 2.1 Mesa 20.2.6
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 20.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
**Software renderer**

Log attached

While loading state: [mgba_short.log](https://github.com/mgba-emu/mgba/files/5878631/mgba_short.log)

**Comment by endrift** [comment]
Please use the bug report tool in the dev build to generate a report.

**Comment by endrift** [comment]
Still waiting on that info.

**Comment by endrift** [comment]
Closing due to lack of reply.
