### ISSUE TITLE
cameloft games run poorly.

### ISSUE THREAD

**Issue by hairyballZ** [mgba-emu/mgba#2033]
ive noticed the cameloft games run very badly. mario golf, mario power tennis, goldensun. have similar slowdown issues with mario golf gbc.

**Comment by endrift** [comment]
On what hardware?

**Comment by Maesejesus** [comment]
I tried and at the very least all of the Camelot games I have play fantastic on the Wii version, both GBC and GBA.

**Comment by endrift** [comment]
Closing due to lack of info.
