### ISSUE TITLE
Some different Soundproblems at N.Switch

### ISSUE THREAD

**Issue by Klauserus** [mgba-emu/mgba#2034]
Hello

I tryed Nightly Version 0.9-6560.791818

I havent a youtube account. I documented this on some vidoes and uploaded this on a free hoster

[Castlevania:Aria of Sorrow](https://www.file-upload.net/download-14460182/MAH05362.MP4.html)

[The Legend of Zelda: Minish Cap](https://www.file-upload.net/download-14460195/MAH05361.MP4.html)
(When you passed the Door)

[F-Zero GPLegend](https://www.file-upload.net/download-14460200/MAH05359.MP4.html)
(At Titelscreen select, i see some Graphic glitches.
Sound crackeling at 0:41 and above)

thx

**Comment by endrift** [comment]
As you noticed, these are from the framerate dropping. They're not sound issues, they're just the game running slowly and therefore being unable to generate audio at the correct speed. I recommend turning down the GPU scaling, since it's slow at the moment, and that's what's causing the issue.
