### ISSUE TITLE
TV not reading signal when running mGBA on Wii over AV cables.

### ISSUE THREAD

**Issue by Kairi5431** [mgba-emu/mgba#2038]
On both a Roku TV and an Insignia anytime I run mGBA with my AV cables the TV stops reading the signal (tried with both 0.8.3 and 0.8.4), however when I use my component cables on the Insignia it reads the signal just fine (the Roku only has AV ports and the Insignia is a TV that I am trying not to use so that it can be available for someone else when they need it so AV is my only option).

**Comment by endrift** [comment]
You need to make sure your output signal is correct. mGBA cannot output 480p over composite, no matter how hard it tries.

**Comment by Kairi5431** [comment]
I'm not really sure how I would check the output signal, most I could think of was checking the Wii settings. I'll try and figure it out later and worst case scenario if I can't get it to work I'll just use my computer.

**Comment by endrift** [comment]
You can manually override the settings in mGBA's configuration menu. I don't generally recommend setting it manually, so if it's not set to autodetect you should change it back.

**Comment by Kairi5431** [comment]
Okay so it seems when I first put it on my Wii I must have changed the setting thinking it was gonna look better if I messed with it and now that I've changed it back it's working, thank you so much and from now on I'll probably think twice before I mess with a setting I don't necessarily need to. User error on my part and if anything hopefully it'll show up in searches for anyone who may have the same problem in the future.
