### ISSUE TITLE
[Wii] Arguments to load rom?

### ISSUE THREAD

**Issue by earithramir** [mgba-emu/mgba#2039]
Hi there, 

Im currently using an old version (0.4-2701) through WiiFlow
This uses the following arguments: 
```
arguments=-rom|{device}:/{path}/{name}|-video_mode|1|-r|4
```
I've tried to update this version to a couple of finals and the latstest development build
but when trying to run a rom with above mentioned arguments it displays a black screen with: "Load Failed"

Please tell me what arguments i need/can use to use this emulator in my frontend, thanks in advance!

**Comment by earithramir** [comment]
Nevermind..
Just found the solution, by removing the -rom and add the rom directly as first argument!!

```
arguments={device}:/{path}/{name}|-video_mode|1|-r|4
```

**Comment by endrift** [comment]
This is not a support forum.

Anyway, -video_mode, -r, or whatever, have never been arguments to this program.
