### ISSUE TITLE
Windows: button configuration clipping

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#204]
My monitor resolution is 3000x2000. This is my settings page.

![settings](http://i.imgur.com/GumBowv.jpg)

**Comment by endrift** [comment]
I was told that it's just the sidebar is too narrow on Windows in general, not specifically a scaling problem. I didn't test the sizing on Windows yet so I'll fix this when I next have access to a windows computer.

**Comment by tony971** [comment]
I just wanted to draw attention to the directional mappings, as well.

**Comment by endrift** [comment]
Yeah, I should probably change them to be proportional to the font size, something Qt doesn't really have by default. For some reason.

**Comment by tony971** [comment]
The sidebar now fits all of the text. The only time things get clipped now is when mapping multiple axes to the directional buttons.

**Comment by endrift** [comment]
Shoooould be fixed by 78ef8523ac3c49ccce9108427895dfd49cd829ce, let me know.

**Comment by tony971** [comment]
Yep. Fixed.
