### ISSUE TITLE
Not handling the timer cascade bit properly

### ISSUE THREAD

**Issue by mattrberry** [mgba-emu/mgba#2043]
When a timer is enabled, if its cascade bit is set then it should stop counting immediately. Unsetting it should resume the timer immediately from where it left off without reloading the counter. This is best demonstrated in the tonc tmr_demo, which is documented with source code [here](https://www.coranac.com/tonc/text/timers.htm#sec-demo). Not sure of any actual impact in games.

Tonc downloads in case you somehow don't have them: https://www.coranac.com/projects/#tonc

**Comment by endrift** [comment]
I have a tentative fix for this, but I did some refactoring/(questionable) cleanup at the same time so I need to test it more before I push it.
