### ISSUE TITLE
Sonic Advance 2  does not work when playing a single pak link game. 

### ISSUE THREAD

**Issue by Testsr** [mgba-emu/mgba#2044]
Sonic Advance 2 seems to download the program properly, but fails with a comunication error. 
Report is in the zip.
[Sonic Advance 2.zip](https://github.com/mgba-emu/mgba/files/5980785/Sonic.Advance.2.zip)

**Comment by Testsr** [comment]
Anyone listening?

**Comment by endrift** [comment]
I don't always reply to new bugs since I don't always have something to say

In this case since other games work, which they didn't before, this is a bit lower priority for me to look into this release, which is already way overdue.

**Comment by Testsr** [comment]
Tested with 0.10-7003-c0b0b6b00. New Problem arose, Sonic Advance never stops transferring any data.

**Comment by Testsr** [comment]
Checked what purports to be commit d9627e.  Restored original behaviour of seeming to download the program, but failing. Is it working on your end?
Attached another report.
[Report2.zip](https://github.com/mgba-emu/mgba/files/6729876/Report2.zip)

**Comment by endrift** [comment]
It definitely is working on my end, I checked multiple times.

**Comment by Testsr** [comment]
I also have the US version, and have verified it fails.

**Comment by Testsr** [comment]
Doing a deletion of all settings to see if that helps.

**Comment by Testsr** [comment]
Reset of setting made the game worked once, and never again.I don't know what this is, but this is certainly not fixed.

**Comment by endrift** [comment]
You appear to be correct, it's still broken for me sometimes.

**Comment by endrift** [comment]
Upon inspection, as best as I can tell all the right data is being exchanged, but then there's a race condition between the two GBAs because they change comm types a few times. This is a known issue in mGBA and isn't going to be addressed for a bit.
