### ISSUE TITLE
Controller Mapping

### ISSUE THREAD

**Issue by Anslean** [mgba-emu/mgba#2045]
I am currently using an unaltered version of `mGBA` (0.8.4), in conjunction with a Nintendo Switch controller (`Afterglow Deluxe+ Audio Wired Controller`).

The `Up` button on the `D-Pad` appears to map correctly in `Tools > Settings > Controllers`. However, upon closing the settings window, the `Up` button (and _no other button_) does not work as expected. Instead, it acts as an `A` button press. After reopening settings, there is no button mapped to the gameboy's `Up` button (if I had previously mapped a _different_ button to `Up` (emulator), then it resets to _that button_, rather than being fully unmapped). I have made sure to click `Apply` and `OK`, and I have tried making use of `Refresh`, as well as clicking `Clear Button` and `Clear Analog` prior to setting the input.

Visually, there doesn't _appear_ to be any issue until settings window is closed and reopened. Other buttons work as expected. Mapping a button _other_ than `Up` (controller) to `Up` (emulator) works as expected. Mapping all buttons on `VBA-M` (as well as `FCEUX`, `bSNES`, and all the other emulators I use) also works as intended. Mapping the `Up` (controller) button to any other button _fails_ in the same way described above.

**Comment by endrift** [comment]
Can you please post a screenshot of what it looks like before closing the window and after reopening it?

**Comment by Anslean** [comment]
Before:
![image](https://user-images.githubusercontent.com/79288692/108436499-283c8f00-7211-11eb-9b57-048fab78abf8.png)

After:
![image](https://user-images.githubusercontent.com/79288692/108436559-3ab6c880-7211-11eb-8609-ce28a32bc6f2.png)

**Comment by endrift** [comment]
Click clear button on the B button and then rebind both. The up button is for some reason mapped to the B button too.

**Comment by Anslean** [comment]
Oh, that worked. I feel kind of silly now, but I know I wouldn't have figured that out on my own for a long time. Thanks so much!
