### ISSUE TITLE
Mario & Luigi: Superstar Saga, Mario Bros. Multiplayer not loading

### ISSUE THREAD

**Issue by MrTailson** [mgba-emu/mgba#2046]
I have another window open with the "Open Multiplayer Window" option, and both instances are controlled by different controllers from each other at the same time, but when selecting the multiplayer option on player 1, then selecting multiplayer on player 2, they are stuck on the "Checking..." and "Please Wait..." screens indefinitely, and won't connect to each other.

**Comment by Testsr** [comment]
What version are you using?

**Comment by MrTailson** [comment]
> What version are you using?

Using 0.8.1 mGBA.

**Comment by endrift** [comment]
Please try a newer version; there have been fixes since then.

**Comment by MrTailson** [comment]
> Please try a newer version; there have been fixes since then.

Thank you. I will try this. It did not occur to me that my emulator would have been outdated. I will do that.

**Comment by Testsr** [comment]
@MrTailson Is it working now? If so, you can close this issue.

**Comment by MrTailson** [comment]
> @MrTailson Is it working now? If so, you can close this issue.

Yes, it is working now. Thank you so much.
