### ISSUE TITLE
[OpenGL][Dev builds] Constant black screen when running gbacraft

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2047]
gbacraft is a 3D homebrew inspired in minecraft.
https://www.gbadev.org/demos.php?showinfo=1527

In the latest dev build it runs perfectly on software mode, but the OpenGL renderer only shows darkness. 0.8.4 works fine.

Gameplay with VBA-M:
https://www.youtube.com/watch?v=UJLk7uiTBdk

Specs are: Windows 10 x64, Ryzen 7 4800H, Nvidia GTX2060, 16GB RAM

**Comment by endrift** [comment]
Is this with 0.8.4? Dev build?

**Comment by RafaelTrepaUnCarballo** [comment]
I tested the latest x64 build 

mGBA-build-2021-02-15-win64-6783-232aab5a088543d11712fc9e18bfe56f616e1f73

**Comment by RafaelTrepaUnCarballo** [comment]
I found another gba homebrew with a very similar issue: [Another World GBA](https://www.gbadev.org/demos.php?showinfo=1279).

In software mode, it plays fine, with OpenGL it only shows a plain black or dark blue screens.

I think both homebrew bugs are related, but if you don't think so I can open a new issue

**Comment by endrift** [comment]
That sounds plausibly related yeah. I probably broke one of the bitmap modes. I'll check it out before the release.

**Comment by endrift** [comment]
They both seem to work for me on Intel drivers on Linux, and they use different graphical modes (5 for the former, 4 for the latter). May be an Nvidia-specific issue.
