### ISSUE TITLE
Errors with Python bindings build

### ISSUE THREAD

**Issue by alexwennerberg** [mgba-emu/mgba#2049]
Building the python bindings on Debian Linux, for some cffi doesn't like a couple lines of source code.
This is cffi==1.14.5

```
cffi.FFIError: :[line number]: unsupported expression: expected a simple numeric constant
```

This error is triggered by these lines:
https://github.com/mgba-emu/mgba/blob/b3d97a4389840e539751b5b494ad0edb1dd7b793/include/mgba/internal/debugger/stack-trace.h#L24
https://github.com/mgba-emu/mgba/blob/master/include/mgba/internal/gb/video.h#L70

I came up with a naive solution of replacing these calculated constants with integers, but is there maybe something that cffi was doing wrong/could do differently?

Thanks for this library!

**Comment by endrift** [comment]
Your pycparser appears to be out of date. I actually did change some constants to be the naive solution mentioned here a while ago but pycparser fixed it I believe.

**Comment by alexwennerberg** [comment]
Thanks for the quick response! You're right -- I was using the debian package for pycparser (2.19) and cffi instead of pip. Using the latest version with pip fixed the issue. Thanks!
