### ISSUE TITLE
Flickering in Sonic Advance 3

### ISSUE THREAD

**Issue by sergiobenrocha2** [mgba-emu/mgba#205]
There's some flickering in the life counter picture (in the second character, tails in this case), using the libretro core on android, using the bios.

![screenshot_2016-01-13-03-03-06](https://cloud.githubusercontent.com/assets/5431285/12285664/95c80f9e-b9a3-11e5-909d-5c3a02db9135.png)

![screenshot_2016-01-13-03-03-05](https://cloud.githubusercontent.com/assets/5431285/12285680/b73ad936-b9a3-11e5-9017-3dd1f88edf7e.png)

The savestate:

![sonic advance 3 usa en ja fr de es it state](https://cloud.githubusercontent.com/assets/5431285/12285761/ac8406d8-b9a4-11e5-8ada-274fccfd2cf9.jpg)

**Comment by endrift** [comment]
Are you reliably able to get it into a state where this happens?

**Comment by sergiobenrocha2** [comment]
"Sonic Advance 3 (USA) (En,Ja,Fr,De,Es,It).state"  --> from c313f09 commit

CRC32:  49DDA5E6

![sonic advance 3 usa en ja fr de es it state](https://cloud.githubusercontent.com/assets/5431285/15765111/41a9aff2-2907-11e6-9a11-cabfb026969a.png)

**Comment by endrift** [comment]
No I mean, can you get it into that state without loading a savestate? Like, if you just play normally will it happen, or did it happen once and you took a savestate?

**Comment by sergiobenrocha2** [comment]
I can get that without savestates. It's somewhat hard to find a place where it happens. Try Sunset Hill zones

**Comment by sergiobenrocha2** [comment]
The battery save "Sonic Advance 3 (USA) (En,Ja,Fr,De,Es,It).srm"

![sonic advance 3 usa en ja fr de es it _ srm](https://cloud.githubusercontent.com/assets/5431285/15765239/a67fb0b0-2908-11e6-95da-838d38b759d4.png)

**Comment by sergiobenrocha2** [comment]
Try Sunset Hill Act 1, it'll happen in the very begin, without doing anything.

**Comment by SuperrSonic** [comment]
Might be a different issue altogether but I just noticed that the special stages have a constant glitched horizontal line at the top of the screen. It sometimes flickers and pausing makes it go away.
![sonic advance 3-1](https://cloud.githubusercontent.com/assets/6880539/18471616/9fd8cf30-7967-11e6-9781-e6bf06b1b760.png)

**Comment by sergiobenrocha2** [comment]
Try Sunset Hill Act 1, it'll happen in the very begin, without doing anything.

Was it related to #361 ? Seems it's fixed too

**Comment by endrift** [comment]
Please comment if it's not fixed, and I will reopen.
