### ISSUE TITLE
ROM OOB

### ISSUE THREAD

**Issue by mattrberry** [mgba-emu/mgba#2050]
In November, jsmolka added [gba-suite/unsafe](https://github.com/jsmolka/gba-tests/blob/master/unsafe/unsafe.asm) which tests ROM OOB reads. According to the tests, the bytes following the ROM up to the next power of 2 should read 0. I'm making the assumption that this has been tested on hardware, but I haven't spoken to jsmokla. This "unsafe" test fails on test 3 on mGBA, test 2 on NanoBoyAdvance, and test 1 on my EZ-Flash Omega.

**Comment by endrift** [comment]
ROM chips are always powers of two. It's impossible to test that on original hardware. Flash carts do not count as they're emulating the ROM interface.

**Comment by endrift** [comment]
It looks like, per https://github.com/mgba-emu/mgba/blob/0.8.4/src/gba/gba.c#L417, mGBA _explicitly_ aligns to the whole ROM space if the cartridge has a NPo2 size. The Po2 alignment is necessary for some incomplete dumps, like the Diddy Kong Pilot prototype. It's also what some flash carts do, so some homebrew accidentally ends up requiring it.
