### ISSUE TITLE
Game freeze: Robopon 2

### ISSUE THREAD

**Issue by Meerkov** [mgba-emu/mgba#2052]
See full report here:
https://github.com/TASVideos/BizHawk/issues/2635

TL;DR: Creating a Robopon in the tutorial area results in various glitches/game freezes. (This means you can't leave the tutorial area).

Reproduces in 0.8.4

**Comment by endrift** [comment]
Seems to work fine for me. Is your dump bad? That looks like a bad ROM load causing memory corruption to me. How big is your ROM?

**Comment by CasualPokePlayer** [comment]
> Seems to work fine for me. Is your dump bad? That looks like a bad ROM load causing memory corruption to me. How big is your ROM?
https://github.com/TASVideos/BizHawk/issues/2635#issuecomment-784542618

**Comment by endrift** [comment]
ok, well, I'm curious _how_ it's bad I suppose.

**Comment by Meerkov** [comment]
I've had it repro on 3 different roms.

- Robopon 2 - Ring Version (U) [!] - 4MB
- Robopon 2 - Cross Version (U) - 4MB
- Robot Ponkotto 2 - Ring Version (J) - 8MB

The japanese version didn't crash in the same way, and instead had problems after I played with the menus for a certain time.

Both different US roms, including one that's supposed to be a good dump, triggered this issue consistently.

Note that Bizhawk triggers this issue much faster, and you'll need to follow the slightly modified instructions here to see the differences for mGBA.
https://github.com/TASVideos/BizHawk/issues/2635#issuecomment-784490071

1. Play Robopon 2
2. Get Sun and Ion batteries (though any combination might work)
3. Get a folder
4. Combine your Robopon (Notice that the menu icon is glitched)
5. Enter the Robopon menu
6. Select the robopon you just made
7. Close the menu once you see your cursor is corrupted.

**Comment by Meerkov** [comment]
Actually, it looks like the (J) rom I used was 4MB as well, after checking my notes.

**Comment by Meerkov** [comment]
I think I'm satisfied that these roms are mislabeled, and that my [!] is actually not a good dump.
