### ISSUE TITLE
Metroid Zero Mission Fusion Link doesn't work

### ISSUE THREAD

**Issue by tom0113** [mgba-emu/mgba#2054]
Build 0.8.4
Windows 10 64 bit
On original GBA Hardware, linking Metroid Zero Mission and Metroid Fusion can unlock a Fusion Gallery in the options section of Metroid Zero Mission, this is done by connecting the 2 systems, holding start and select while Fusion launches and then selecting Fusion Link in options of Metroid Zero Mission.

I tried to do this in emulator by loading Metroid Zero Mission and Fusion in a multiplayer window, holding down start and select while fusion launched, and following the same steps as on console, only to get error messages (images attached) on both consoles.
![Metroid Fusion (Europe) (En,Fr,De,Es,It)-0](https://user-images.githubusercontent.com/30247048/108961704-d772dd80-76cb-11eb-8b62-5c67810c65c2.png)
![Metroid - Zero Mission (Europe) (En,Fr,De,Es,It)-0](https://user-images.githubusercontent.com/30247048/108961707-d8a40a80-76cb-11eb-9875-9159ef061407.png)

**Comment by endrift** [comment]
Did you try in a dev build? This looks like a duplicate of #425, which was only fixed recently.

**Comment by tom0113** [comment]
I had tried a couple times in build 0.9-6791.817e4d950 and the emulator crashed upon booting up a second window but I tried it again and it worked, problem solved.

**Comment by tribals** [comment]
@tom0113 Could you please explain how did you get it working?
