### ISSUE TITLE
Legend of Zelda Freezes at Chu Chu battle

### ISSUE THREAD

**Issue by jmc92** [mgba-emu/mgba#2056]
So, my younger sister did a run through of this game on mgba, since the other emulator she uses would always freeze here as well. I thought maybe mgba would get her over this hill.
Doesn't seem to work here either as of yet. I played this game a long time ago and I believe that this is where the ChuChu battle is supposed to be, where a big green blob comes out of the chest in the middle of the room. I have in this zip > https://drive.google.com/file/d/1VtW-M6bMlL2urXfXBhiLZ8QKmkl4K-zr/view?usp=sharing
The savestates and game saves she's sent me for this area. Save state 1, is before the lockup, where you go into the room. Save state 2 is after the lock up has occured. The music just plays and all the controls are frozen.

Here's a screenshot of the frame it locks in > https://i.ibb.co/TBvSRWk/minishfreezeup.jpg

This is the mgba version > mGBA-build-2021-02-13-win32-6782-7a3f2b12b5045fa67354c657d9c11b46a55fe173
And I've tried to troubleshoot it by switching to software rendering, syncing the frames to video or nothing at all, but to no avail.

**Comment by endrift** [comment]
Please attach the zip file generated by the bug report generator in the file menu.

**Comment by jmc92** [comment]
Here you go. This is made using save state 1, in the original zip I linked, and then going straight up through the doorway and upon freezing, I saved the bug report. https://drive.google.com/file/d/1WwkxmY87a3HjaxAhufPttrRr-I9ez7cf/view?usp=sharing
Hopefully that helps.

**Comment by endrift** [comment]
You appear to have a bad dump--the checksum is wrong. This is probably why the game is freezing regardless of emulator.

**Comment by jmc92** [comment]
You are absolutely right. And the problem is now resolved. You can mark this one as closed :D
Thank you for all the work you've done for mgba. It's a very cool emu.
