### ISSUE TITLE
GDB Breakpoints don't work properly

### ISSUE THREAD

**Issue by osum4est** [mgba-emu/mgba#2058]
Hello! I'm trying to debug this program but GDB breakpoints don't seem to be working correctly, and prevent proper execution of the rom.

Putting a breakpoint on a line < 26 seems to work OK, GDB stops on it, and resuming execution allows the rom to run properly. Putting a breakpoint inside the while loop however, causes issues (lines 27/29/30). 

GDB stops at the breakpoint, and resuming execution will run the loop and stop on the breakpoint again. I would expect each time the loop runs, for the counter to increment on screen, but it doesn't. No matter how many times you continue and hit the breakpoint again the screen does not update.

Secondly, if you remove the breakpoint after stopping on it and continue, the rom continues to run at < 20fps and still, the screen doesn't update.

Any ideas on why this would happen? I have a attached a very simple .c file that this issue happens in, as well as my build of the simple c file.

OS: macOS Big Sur
mGBA Version: 0.8.4
GDB Version: arm-none-eabi-gdb provided by devkitPro, 9.2

[GDB Breakpoints.zip](https://github.com/mgba-emu/mgba/files/6065816/GDB.Breakpoints.zip)

**Comment by osum4est** [comment]
Just tried building mgba from source and it fixes this issue! This only happens on the latest release version.

**Comment by endrift** [comment]
well I had just started debugging it but I'm glad to hear it's already fixed. The new release should be coming out soon.
