### ISSUE TITLE
(dev builds) mGBA can't load savestates from any original Game Boy game

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2061]
**UPDATE:** The savestates of **all original Game Boy games are broken** in the latest x64 dev build, or at least all the .GB roms I have:
Avenging Spirit, Donkey Kong Land, Final Fantasy Adventure, Kaeru no Tame ni Kane wa Naru, Kid Icarus - Of Myths and Monsters, Kirby's Dream Land 2, Mario Land (unless I autoapply the GBC color patch).

GBC and GBA games still works fines, though.

================
**OLD**: The latest dev build is unable to load savestates in Popeye 2. The savestates were made seconds ago with the same build.

I tested **mGBA-build-2021-03-05-win64-6807-cc739bb369b981ba1a053417bd5a1e4c981e7bfb** and another build from weeks ago (I forgot which version), both suffer the same bug.
The stable 0.8.4 has no problems with that.

I noticed the log of the dev builds gets filled with this game error:
```[GAME ERROR] GB MBC:	Attempting to switch to an invalid RAM bank: 0```

When I try to load a save state this appears in the logs:
```
[WARN] GB Savestate:	Incompatible savestate, please restart with correct BIOS in DMG mode
[INFO] Status:	State 1 failed to load
```

I'm using Windows 10 x64 with the x64 build.

**Comment by endrift** [comment]
Are you using a GBC BIOS for GB games, e.g. to get colorization?

**Comment by RafaelTrepaUnCarballo** [comment]
No, I don't use BIOS files.

I did more testing:
-The bug only happens when emulating the DMG and SGB models, but if you use GBC or GBA it works fine. (no bios needed)
-The GB Bios also fixes the bug
-In DMG model, without the BIOS, you can load a savestate made with BIOS and from that point you can create new savestates and load them without a problem.

**Comment by endrift** [comment]
Thanks for the report. Unfortunately the old savestates recorded an erroneous value which is why they're refusing to load. These savestates will not load unless they are manually repaired.
