### ISSUE TITLE
Pokemon Prism audio issue

### ISSUE THREAD

**Issue by Searinox** [mgba-emu/mgba#2062]
Pokemon Prism and Pokemon Crystal use the same ROM base and have always sounded the same on all systems including mGBA builds. As of the current build, Prism's audio is lacking a lot of the trailing and echoey features of sound and music. Playing just a bit of it and listening to the sounds and music and comparing it to that in Crystal should make it immediately clear, the audio is just more muffled.

**Comment by endrift** [comment]
Likely fixed by 601ece2e2aed5abc572a71a645af8adc84713970, please retest.

**Comment by Searinox** [comment]
Confirmed fixed.
