### ISSUE TITLE
Missing animations in Pokémon FRLG

### ISSUE THREAD

**Issue by Thirteen1355** [mgba-emu/mgba#2063]
Stat lowering animations and the 'blinking' animation prior to executing Metal Claw aren't displayed by mGBA.

**Comment by Thirteen1355** [comment]
The missing animations (along with some annoying lag) were caused by the setting "hwaccelvideo" being on =1. Setting it to =0 fixed the issues.

**Comment by endrift** [comment]
This was a duplicate of #1975 anyway, which has been fixed in dev for a while.
