### ISSUE TITLE
[mgba-emu upstream Libretro build] Flash1M games refusing to load properly

### ISSUE THREAD

**Issue by ds22x** [mgba-emu/mgba#2067]
This might be a bit of an odd and low-priority issue, but whenever I try to use a Libretro core build from upstream (not from the Libretro fork, I like to stress), the resulting build will have issues with GBA games that use the Flash1M save type (I.E. the Pokemon RPG games), which will refuse to load past the BIOS screen unless there's no savefile present, in which case it will complain that the Flash1M board is not initialized past the title screen.

**Comment by endrift** [comment]
This turned out to be a significant bug, so thanks for reporting it!
