### ISSUE TITLE
Audio issues with GB to GBC conversion mods

### ISSUE THREAD

**Issue by ds22x** [mgba-emu/mgba#2071]
Happens only with builds made from the latest source after the 0.8.4 release, but when you use GB to GBC conversion mods, the audio seems to be noticeably missing quite a lot of effects.
I can confirm it at least happens with the following mods:
http://www.romhacking.net/hacks/4477/
https://www.pokecommunity.com/showthread.php?t=361713
https://www.romhacking.net/hacks/5213/
https://www.romhacking.net/hacks/3784/

**Comment by endrift** [comment]
Can you attempt to narrow down when this broke? Old builds are available on the website: https://mgba.io/builds/1/ -- just grabbing one from every page or two and testing that should give a head start on narrowing it down

**Comment by ds22x** [comment]
https://github.com/mgba-emu/mgba/commit/bda43168394b3edf785ef916186d131f871e4029 is what broke it.

**Comment by endrift** [comment]
Possibly a duplicate of #2062, but I have a fix for this one coming shortly.

**Comment by autofire372** [comment]
I would just like to note that this affects actual GBC games as well. Tested with Super Mario Bros. Deluxe (USA, Europe) (Rev 2).
