### ISSUE TITLE
mgba-qt / linux: 'Boot BIOS' doesn't seem to do anything, even when specifying BIOS file via -b (+ --version doesn't work)

### ISSUE THREAD

**Issue by LunarLambda** [mgba-emu/mgba#2074]
I dumped my AGB-101's BIOS and while loading ROMs *does* boot the BIOS, the dedicated 'Boot BIOS' menu option doesn't seem to do anything at all.

I was hoping it would boot the BIOS without any cartridge inserted which would be nice for demonstration purposes, is it supposed to be like this?

As I was writing this I also just noticed that running `mgba-qt --version` doesn't actually print the version, it just opens the emulator.

The version is 0.8.4-1 according to my package manager.

**Comment by endrift** [comment]
It works on my end. What's your BIOS config section look like?

**Comment by LunarLambda** [comment]
Don't know, I never touched the config file, I only used the settings in the gui. I unfortunately just shut down my machine but I'll check.

**Comment by LunarLambda** [comment]
I found when going into Tools->Settings->BIOS and picking the GBA BIOS there, Boot BIOS works as expected.

Still leaves specifying a file with `-b` not totally working and `--version` also not working.

**Comment by endrift** [comment]
`--version` should work now (I believe I fixed it in 0.9.1) but `-b` isn't saved between loaded games so having it not work with boot BIOS is...somewhat expected. Not sure that's a _good_ behavior though. I'll have to think about how best to handle this.

**Comment by endrift** [comment]
Everything seems to work on my end now. Can you confirm on your end?
