### ISSUE TITLE
Crash when inspecting background 2 in "View map..."

### ISSUE THREAD

**Issue by justburner** [mgba-emu/mgba#2075]
mGBA silently crash when inspecting background 2 while in Mode 5

**Reproduction steps**
1. [Load entaktogen 3D test ROM](https://www.dropbox.com/s/cgwmeafnludi6uy/test.gba?dl=0)
2. Tools > View map...
3. Click "Background 2" radiobox
4. mGBA instantly closes

**Comment by endrift** [comment]
Weirdly it's not crashing for me, but it's definitely very glitchy.

**Comment by justburner** [comment]
Thanks, that patch fixed it, it no longer crashes here.

Forgot to mention that i'm using Windows 7
