### ISSUE TITLE
Uncheck "Use BIOS file" by default

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#208]
The emulator should be able to run on default settings without configuration. If users want to use a real BIOS, they'd still have to direct mGBA to the location of it. So as it stands, mGBA needs user configuration for both using a BIOS and not using a BIOS. Changing the default setting would make it so that only users who plan on using their own BIOS files have to configure anything.

**Comment by taisel** [comment]
Being allowed to not use a BIOS is a hack in of itself. It should always be recommended to use it, due to timing and untested games issues.

**Comment by taisel** [comment]
There's a homebrew ROM out there that dumps the BIOS ROM to your flash cart if you need, to complement the game ROMs you also dumped for backup purposes only. You should look at the BIOS file as if it's part 2 of the game ROM, because that's what it is.

**Comment by tony971** [comment]
Even the members of Dolphin concerned with legal correctness don't try to say that ROMs are dumped for backup purposes only.  That being said, why does it bother you if the non-copywrited BIOS is selected by default? All it does is remove a configuration step, should users decide to use it. Since using the real BIOS requires configuration, anyway, it doesn't make anything easier to keep this option selected by default.

**Comment by tony971** [comment]
And I find it funny that you say "game ROMs you also dumped for backup purposes only" while making an argument about how to play them.

**Comment by tony971** [comment]
The legality is a non-issue. Because assuming everything was done correctly, it's the same whether you use the dumped BIOS or not. The only issue is whether you should need to configure for both settings or just one.

**Comment by taisel** [comment]
Once you know all the timing issues related to eliding running the individual instructions step-wise and just HLE'ing the syscalls, it becomes more like running nouveau vs. the binary blob nvidia gives, at least from my perspective. It's extremely ugly once you peek into how emulators are able to run without the BIOS, and should not be tier-1 support.

**Comment by tony971** [comment]
I'll take that argument when you convince Dolphin to do the same.

**Comment by tony971** [comment]
Things that wouldn't change with this adjustment:

* Those who use the emulated BIOS won't start using their real BIOSes.
* Those who do use their real BIOSes will still have to configure mGBA to do so.

Things that would change:

* Users could download mGBA and play their ROMs with zero configuration.

**Comment by endrift** [comment]
Except...that third thing is already what happens? It's checked so that if that value is filled in, it automatically takes. If it's not filled in, it's functionally equivalent to no/HLE BIOS.

**Comment by tony971** [comment]
Ahh well then this ticket is just me misunderstanding the UI. Feel free to close.

**Comment by endrift** [comment]
The fact that the UI can be misunderstood this way shows that this is something worth considering. But ultimately it provides no functional difference.

**Comment by tony971** [comment]
Saw your "if found" comment. Works for me.
