### ISSUE TITLE
3DS: Switching from GBC to GBA games garbles the graphics

### ISSUE THREAD

**Issue by Searinox** [mgba-emu/mgba#2080]
Right so I'm not sure if this is 3DS-only or what other more general steps can repro it, but here's what I've got:

-load Pokemon Crystal
-close and load Pokemon Emerald

Graphics will be garbled until the ROM is unloaded and re-loaded.

I'm using the Bilinear Pixellated filter. Not sure if it's got anything to do with it.

**Comment by endrift** [comment]
The bilinear pixelated filter is probably relevant, yes.
