### ISSUE TITLE
Corrupted MGBA file

### ISSUE THREAD

**Issue by FluffySquirelz** [mgba-emu/mgba#2081]
Whenever I save my state in MGBA sometimes the emulator crashes and my save state is corrupted. I am unsure of why this happens or if I can fix that corrupted save state that I spent hours on.

**Comment by endrift** [comment]
I will need more information about your configuration, such as what OS you're on, what version of mGBA you're using, and more. Just give me any information you might think is applicable.

**Comment by endrift** [comment]
Closing due to lack of info. Not much to go on here if I don't get a reply.
