### ISSUE TITLE
[Switch][Latest nightly build][DOCK MODE] Abnormal speed oscilations during a capped turbo

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2082]
When playing in dock mode, while using the turbo the emulation speed may return to 100% for a few seconds, although still skips frames.

This phenomenon seems random, but it might be linked to sounds or effects (not sure). Portable mode is completely unaffected.

**Comment by endrift** [comment]
Are you using the hardware accelerated renderer?

**Comment by RafaelTrepaUnCarballo** [comment]
I can't reproduce it anymore. Maybe it was fixed
