### ISSUE TITLE
[Switch][Latest nightly build] Wrong image scaling after disabling GPU acceleration during a gameplay and reseting

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2083]
1. Start a game with GPU accelerated render set on ON and hi-res scaling set on 2 or higher
2. In the middle of the gameplay disable GPU accelerated render 
3. Reset from the mgba menu

mgba wrongly shows a x1 in a corner of a frozen hi-res frame, the last one before scaling.

Doing the opposite causes the image to stay low-res, although filling the screen correctly.

![imagen](https://user-images.githubusercontent.com/16591467/112514775-efef1a00-8d95-11eb-8ee0-5acc226e3d7c.png)

**Comment by endrift** [comment]
mGBA on Switch currently cannot switch between GPU and CPU rendering without unloading and reloading the game. However, 1x scale thing mentioned here is a bug indeed.

**Comment by endrift** [comment]
Turns out it was easier to just fix switching between GPU and CPU now (after I'd done a lot of heavy lifting on the PC side a few months ago) instead of fixing that bug :shrug: 

Fixed in 853c64b32691671507622e5131714e493f71375e.
