### ISSUE TITLE
The RTC in Pokémon Giratina's Legend (ROM Hack) doesn't work on the latest Nightly

### ISSUE THREAD

**Issue by LOuroboros** [mgba-emu/mgba#2086]
Title.

The download to the hack's .ups patch can be found here _(click on the picture linked in the post)_:
https://www.pokecommunity.com/showpost.php?p=10324252&postcount=476

![Untitled4024](https://user-images.githubusercontent.com/4485172/112651189-123f7100-8e44-11eb-95dd-eb8ed287bccb.png)

**Comment by endrift** [comment]
Please try enabling VBA bug compat in overrides (under the tools menu) before loading the ROM to see if it fixes it.

**Comment by LOuroboros** [comment]
> 
> 
> Please try enabling VBA bug compat in overrides (under the tools menu) before loading the ROM to see if it fixes it.

Nope, it doesn't.

Furthermore, even though I enabled it before booting up a ROM, the option appears to be disabled after checking it again while the game is running.

![Untitled4030](https://user-images.githubusercontent.com/4485172/112673501-b1706280-8e5c-11eb-98f1-8959ffccd2ed.png)

Inspecting the .ini files for a way to force enable it, I stumbled across a settings override for BPRE *(Pokémon FireRed USA)* in the config.ini file.
For whatever it's worth, Giratina's Legend is based on Pokémon Ruby, whose serial ID is AXVE.

**Comment by endrift** [comment]
Enabling VBA bug compat _does_ fix this, however enabling it is currently buggy. I'll have a fix for that tonight.

**Comment by endrift** [comment]
VBA bug compat enabling fixed in 3ce0472963ea747edb1e7233e2fdfe9b1d8db4b8, the hack now works if you enable it.

**Comment by LOuroboros** [comment]
> 
> 
> VBA bug compat enabling fixed in [3ce0472](https://github.com/mgba-emu/mgba/commit/3ce0472963ea747edb1e7233e2fdfe9b1d8db4b8), the hack now works if you enable it.

The state of the feature doesn't remain saved if I close mGBA though. As soon as I close mGBA, I check and it's disabled again.

Is that intended?
