### ISSUE TITLE
Sonic Advance/Advance 2/Pinball Party Tiny Chao Garden save corrupts randomly and game crashes when saving

### ISSUE THREAD

**Issue by Sonicjan** [mgba-emu/mgba#2087]
When first entering the Tiny Chao Garden in Advance 1, 2 and Pinball Party, everything works fine. But after some playtime the save completely corrupts, deleting or changing the Chao, giving max rings or setting them to 0, removing all Toys in the Garden and crashes when saving and exiting. When you reset the game and reenter the Garden, everything is deleted and a normal Chao Egg is sitting there (just like when you just started the game). Since Sonic Advance 1, 2 and Pinball Party have there own save next to the Tiny Chao Garden, the Emulator have problems with that save system. Playing the main game doesn't seem to be affected, but playing the Tiny Chao Garden is sadly impossible due to this.
(occured on PS Vita and PC)

**Comment by endrift** [comment]
Which version of mGBA are you using?

**Comment by endrift** [comment]
Does this occur on latest dev builds?

**Comment by Sonicjan** [comment]
Sorry never answering, didn't got notified about the Comments. It was on the latest public Builds as far as I remember. Nowadays I play those games on different systems, since those problems never went away. Don't know if they currently fixed and have no means on testing. Just didn't wanna leave you hanging with no reply...

**Comment by endrift** [comment]
I appreciate the reply, even if late. I'm not sure there's anything I can really do on this otherwise though, so I'm going to leave this closed.
