### ISSUE TITLE
DMA3 source address control flag

### ISSUE THREAD

**Issue by vivi168** [mgba-emu/mgba#2088]
Hello,

I'm toying with rust and gba dev.
I've noticed that when enabling DMA with a fixed source address, it doesn't work and still increment.

When testing the exact same rom on nocash emulator, it seems to work.

Here's a screenshot attached.
I'm transfering a palette to the palette ram, with DMA_SRC_FIX, but it still copies the entire palette instead of the first word only. (when changing to DMA_SRC_INC, it correctly increments on both emulators)

Maybe I'm doing something wrong, as I don't think such a bug would go unnoticed.

I'm using mgba latest release (heads/0.8.4)

![bugdma](https://user-images.githubusercontent.com/1566422/112698930-12169400-8e8b-11eb-924a-37aa904b4e40.png)

**Comment by endrift** [comment]
What's your source address? ROM does not support non-incremental reads.

**Comment by vivi168** [comment]
Well, I should have read the documentation more carefully 😅 , source address is indeed in ROM, @ 0x8000190
