### ISSUE TITLE
Logging crashes

### ISSUE THREAD

**Issue by vgturtle127** [mgba-emu/mgba#209]
Logging "SW Interrupts" or "Game Errors" often crashes the emulator within a few of either.

I was playing with Zelda Four Swords playing A Link To The Past, and turning on SW Interrupts crashes the log, but not the main emulator window. Turning on Game Errors flooded the log with (presumably game errors) and crashes both.

Not sure if this is not fully implemented, not fully tested, or just has some bugs still. Just wanted to let you know.

Running latest nightly on 64-bit Windows 10 Pro.

Using an Intel Pentium G2030 and Nvidia GTX 750 Ti.

**Comment by endrift** [comment]
It's just logging too much at once. It's hanging and you're letting it log more.

**Comment by vgturtle127** [comment]
@endrift Wouldn't that still be a bug, though? Or is it just the game?

**Comment by endrift** [comment]
I've tried to improve the logging performance a bit, but when you stuff several thousand lines per frame into a log, turns out it gets slow.

**Comment by vgturtle127** [comment]
@endrift Slow would be fine, that I would understand. But it crashes usually (at least for me). Even if I just select one option on the left. Maybe the "Max Lines" should be set lower by default? Maybe like 10? :laughing:

**Comment by endrift** [comment]
You're using Windows. Windows doesn't differentiate between hangs of longer than a few seconds and crashes, because ~user experience~.

Also 10 is *absurdly low* for anything.

**Comment by vgturtle127** [comment]
@endrift Absurdly low, but it works somewhat better at least? Actually, I put it on 10 and Game Error crashes it still. So I guess that isn't the solution there, at least. SW Interrupts works fine, though. So maybe just tweak the max lines a bit, I guess?

**Comment by endrift** [comment]
You have no idea what you're talking about. Your suggestions are not even tangential to real fixes. I have an idea for how to improve this, but I'm also busy so I can't do it now.

**Comment by vgturtle127** [comment]
@endrift Just trying to help. I know they aren't real fixes, but it would prevent a crash at least.

I'm also not sure what you mean by "I don't know what I'm talking about"...

**Comment by endrift** [comment]
Let me know if 6e7851f6142a9657213de4714c3de453b229e8d7 improves things at all.

**Comment by vgturtle127** [comment]
@endrift That fixed all the crashes.

Thanks endrift. Sorry if I was frustrating you. I really am just trying to help.

Much appreciated.
