### ISSUE TITLE
Pokemon adventure red chapter stopped working on 0.9.0

### ISSUE THREAD

**Issue by carnage702** [mgba-emu/mgba#2093]
So i updated both in 3ds and wii to 0.9.0 and now this amazing romhack stopped working, on 3ds it straight up fails to load and on wii it does dsi exception

on the last version the wii version runned preety well while the 3ds runned abit slow but still well, anything i need to do to make it work again?

**Comment by endrift** [comment]
I have a fix for the crash that I'll push soon. However, the failure to load is because the ROM is simply too big. They're supposed to cap out at 32 MB, but this hack is 33 MB. The GBA just cannot access that last part anyway, and in 0.9 it started rejecting ROMs that are too big. This is an issue with the ROM hack.

**Comment by carnage702** [comment]
thnaks i cant wait to add that to the wii and 3ds build when updated since mgba runs that game flawlessly on wii.

**Comment by endrift** [comment]
I'm not sure you understood my message. This is a fix for the crash on the Wii. It does not fix the game not loading, since the game not loading is due to mGBA recognizing that the ROM is invalid instead of silently truncating it.

**Comment by carnage702** [comment]
> 
> 
> I'm not sure you understood my message. This is a fix for the crash on the Wii. It does not fix the game not loading, since the game not loading is due to mGBA recognizing that the ROM is invalid instead of silently truncating it.

as long as i can play it on the wii/wiiu with wiiugamepad im good.

**Comment by Testsr** [comment]
> I have a fix for the crash that I'll push soon. However, the failure to load is because the ROM is simply too big. They're supposed to cap out at 32 MB, but this hack is 33 MB. The GBA just cannot access that last part anyway, and in 0.9 it started rejecting ROMs that are too big. This is an issue with the ROM hack.

Let me fix that for you. 
> They're supposed to cap out at 32 MiB ,but this hack is 32 MiB. 

I can load the rom hack just fine on my copy of MGBA 0.9.0, no warning ensues.

**Comment by Testsr** [comment]
@carnage702 

> as long as i can play it on the wii/wiiu with wiiugamepad im good. lucky that the retoarch version of wiiu still has an mgba that plays this romhack full speed no issue.
> 
> So you are saying you wont fix the romhack being invalid even tough it would run fine if there was no 32mb lock? couldnt there just be an exception on pokemon fire red based hacks to let them be bigger than 32mb?
I think your particular romhack 'Pokemon adventure red chapter' should work fine. I tested on my computer running mGBA 0.9.0 and it loaded.

**Comment by endrift** [comment]
You know if you actually did the math instead of assuming I'm wrong and posting a passive aggressive correction you'd realize that 33555563 bytes is more than 33554432, you're posting incorrect information, and the user is using a non-PC version.

You've helped: no one
You've insulted: everyone else here
You've made a fool of: yourself

**Comment by endrift** [comment]
> > I'm not sure you understood my message. This is a fix for the crash on the Wii. It does not fix the game not loading, since the game not loading is due to mGBA recognizing that the ROM is invalid instead of silently truncating it.
> 
> as long as i can play it on the wii/wiiu with wiiugamepad im good. lucky that the retoarch version of wiiu still has an mgba that plays this romhack full speed no issue.
> 
> So you are saying you wont fix the romhack being invalid even tough it would run fine if there was no 32mb lock? couldnt there just be an exception on pokemon fire red based hacks to let them be bigger than 32mb?

The issue is that before I was silently truncating them, which broke the 64 MiB GBA Video ROMs. This approach fixes the GBA Video ROMs but breaks this specific ROM hack (and almost no other ones). It's a bit of a conundrum to find a middle ground. Perhaps anything between 32 MiB and 64 MiB could return to being silently truncated.

**Comment by Testsr** [comment]
> You know if you actually did the math instead of assuming I'm wrong and posting a passive aggressive correction you'd realize that 33555563 bytes is more than 33554432, you're posting incorrect information, and the user is using a non-PC version.
> 
> You've helped: no one
> You've insulted: everyone else here
> You've made a fool of: yourself
> 
> This is your final warning.

Sorry for that, I did make a fool of myself. But why is this cap not in the Windows 10 version.

**Comment by endrift** [comment]
The cap is not in the PC version because the PC version has access more RAM than the Wii and 3DS do. Those versions hard cap the ROM buffer at 32 MiB because that's the size of the largest (actual game) ROM, whereas the PC version just maps in whatever it can.

**Comment by Testsr** [comment]
Ok

> You know if you actually did the math instead of assuming I'm wrong and posting a passive aggressive correction you'd realize that 33555563 bytes is more than 33554432, you're posting incorrect information, and the user is using a non-PC version.
> 
> You've helped: no one
> You've insulted: everyone else here
> You've made a fool of: yourself
> 
> This is your final warning.

Sorry, I admit that I made a fool of myself and insulted everyone else here . I will be better  next time.
