### ISSUE TITLE
Fast forward desync on 0.9

### ISSUE THREAD

**Issue by SAIYAN48** [mgba-emu/mgba#2094]
When using the both the toggle and held fast forwards, a slight video/audio desync occurs. Video and Audio are set to be in sync. This didn't occur in 0.8.4.

System:
Windows 10 x64
i7-8700K
16GB DDR4 3200
GTX 1660

**Comment by endrift** [comment]
This is a known issue with the OpenGL renderer--the draw buffer gets a bit backlogged as the GPU processes all of them and I've had bad luck fixing it so far.
