### ISSUE TITLE
[0.9.0] Inputs interrupted when active window changes. 

### ISSUE THREAD

**Issue by KapitalRoser** [mgba-emu/mgba#2096]
[Video demonstration with input displays](https://streamable.com/ghtzm3)
3 specific issues here:

- Controller inputs are dropped when a different window is made active. 
- Keyboard inputs are not updated when the emulator window is made inactive (ex. Player runs into a wall)
     - If the emu window is made active again, pressing direction again clears the input.
- Keyboard inputs are not read at all when emulator window is inactive, unlike controller inputs.  

This is important for anyone who is attempting to reference notes, or tab to something else while running in a straight line, or mashing dialogue. If the user were to make the window inactive at the wrong moment, they might alert an enemy or end up in the wrong position and die.

If you need them, here are the .sav and the report:
[Bug1.zip](https://github.com/mgba-emu/mgba/files/6225965/Bug1.zip)
[Pokemon - Leaf Green Version (U) (V1.1).sav.zip](https://github.com/mgba-emu/mgba/files/6225969/Pokemon.-.Leaf.Green.Version.U.V1.1.sav.zip)

**Comment by endrift** [comment]
One issue per ticket please.

1. By different window do you mean non-mGBA window? I'm pretty sure it works with other mGBA windows. Also it seems to contradict what you say at the end of the description of 3.
2. This is the exact opposite of #1384 which asks to keep this behavior.
3. I don't believe this is fixable without replacing the keyboard processing code entirely.

**Comment by KapitalRoser** [comment]
Thank you for your response. Apologies for the structure of my ticket, I'm fairly new to this.

Issue #1384 makes a valid point. I admit that I was not aware this keyboard behaviour was present in earlier versions. I retract my 2nd/3rd bullets.

Other windows I mean non-mgba windows, but it occurs on seperate instances of mgba as well. This interruption is the same as what is demonstrated in the video. Yes, you're right that windows within an instance of mgba like a settings dialogue. After further testing, it appears the interruption occurs with some controllers, but not others. My dpad movements are interrupted on Xbox One and Xbox Series X controllers, but not on my Switch-Gamecube Controller.

Given that I am no longer certain this an issue with mGBA (maybe I have weird drivers idk), I'm ready to close this issue.
