### ISSUE TITLE
[Development builds][Hackrom Crystal Clear 2.3.0] Crash when loading a savestate from the Pokedex

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2097]
1. Create a savestate
2. Open the pokedex menu
3. Load that savestate

The game will freeze with a light color screen.

This bug appeared at some point between the 0.8.4 and 0.9.0 releases.

Latest Win64 development build: CRASH
Latest Switch development build: CRASH
0.9.0 Win64 stable build: CRASH
0.8.4 Win64 stable build: WORKS FINE

Log details:
The game log spams two GAME ERROR on loop when opening the Pokedex
**[GAME ERROR] GB I/O:	Writing to unknown register FF15:00
[GAME ERROR] GB I/O:	Writing to unknown register FF1F:00**
...

And when you load the savestate, it shows many **[GAME ERROR] GB I/O:	Writing to unknown register FF56:00**
Those messages are stub in 0.8.4.

Hardware and software report:
[bug report.zip](https://github.com/mgba-emu/mgba/files/6230071/bug.report.zip)

**Comment by endrift** [comment]
Please retry in latest dev, I fixed a savestate bug pretty much immediately.

**Comment by RafaelTrepaUnCarballo** [comment]
I just downloaded **0.10-6896-30ed94e80** from your website.
Still has the bug

**Comment by endrift** [comment]
Where are you creating the savestate that you're loading while in the Pokedex? I'm not able to reproduce.

**Comment by endrift** [comment]
I've figured out the issue. I'll have a fix tonight.
