### ISSUE TITLE
Feature request: Selectable GB model preset palettes, like Gambattes.

### ISSUE THREAD

**Issue by Darkwolf1515** [mgba-emu/mgba#2098]
(sorry if this has been asked before, I did look around in both opened and closed issues.) While by no means essential, the option to choose to display how real GB screens looked is a neat feature, and helps with preservation, 

For those who don't know what I'm talking about, here's a link. https://docs.libretro.com/library/gambatte/#core-options

**Comment by endrift** [comment]
I intend to do something like this for non-color models at least.

**Comment by Darkwolf1515** [comment]
Well that was fast, glad to see you wanted it as well!

**Comment by endrift** [comment]
Added in a713d51e05e183e13acb7f537f1965ed977cf23a, though having some more presets would probably be a good idea.

**Comment by Darkwolf1515** [comment]
Do you have a list of which ones you created?

**Comment by endrift** [comment]
Right now it's just grayscale (the default), DMG green, and the GBC directional ones.

**Comment by Darkwolf1515** [comment]
gotcha, the gb light pallet is my personal favorite. Hope to see it one day.
