### ISSUE TITLE
[3DS] Not waking up (crash?) after reopening lid

### ISSUE THREAD

**Issue by tranaconda** [mgba-emu/mgba#210]
If you close your 3DS and open it again, the screen stays black. Seems to be a common problem in 3DS homebrew though...

**Comment by endrift** [comment]
Known issue, haven't gotten around to fixing it yet.

**Comment by tranaconda** [comment]
smea seems to have fixed in hus Homebrew Loader, but I cant find the right commit on Github - maybe it was a fix in ctrulib? I'll browse a little, maybe I can find it. Thanks for your great work by the way, I really enjoy mGBA :)

**Comment by endrift** [comment]
Nah, the HBL never had the bug, but *hax did, so that payload wouldn't let you suspend at all. mGBA has some issues that are preventing it from working even with the proper *hax payload that I'll get around to fixing.

**Comment by tranaconda** [comment]
Wow, you are quick. Wish I was half as good as you :)
