### ISSUE TITLE
Non-English FireRed detected as ROM hack

### ISSUE THREAD

**Issue by cruiseliu** [mgba-emu/mgba#2100]
The commit "GBA: Fix FireRed revision misdetecting as a ROM hack" only checks CRC of English versions.
mGBA sometimes creates invalid save file for Japanese FireRed. I can't always reproduce it, but I comment out relative lines in `overrides.c` and it never happens again.

**Comment by endrift** [comment]
Yes, I was made aware of this last night and I'm working on a fix.
