### ISSUE TITLE
Error 01EC2ED0

### ISSUE THREAD

**Issue by MisterLotospol** [mgba-emu/mgba#2101]
So I love to play pokemon rom hacks and for some have this certain attack which is called Flash Canon normally I don't think it would be in the gba games but it is, every time I use it or the enemy uses mgba crashes and gives the error 01EC2ED0. I tried to find on the internet solution but I don't see anyone with the same problem, can someone help me ?

**Comment by endrift** [comment]
Telling me what ROM hacks and what version you're using is a good start.

That's also not an error code, it's saying the game crashed by jumping to an invalid memory address. Said address is apparently 0x01EC2ED0.

**Comment by MisterLotospol** [comment]
> Telling me what ROM hacks and what version you're using is a good start.
> 
> That's also not an error code, it's saying the game crashed by jumping to an invalid memory address. Said address is apparently 0x01EC2ED0.

Okey the version of mGBA is the 0.8.4 and the roms I tried were pokemon rocket edition (original rom Pokemon Fire red) and pokemon Dark Violet (Original Rom was Fire Red)

**Comment by endrift** [comment]
Can you retest on 0.9.0? I can try later tonight myself.

**Comment by MisterLotospol** [comment]
> Can you retest on 0.9.0? I can try later tonight myself.

Can try I will see if I find a trainer with a pokemon with that move will report if I found

**Comment by MisterLotospol** [comment]
> Can you retest on 0.9.0? I can try later tonight myself.

Okey perfect it's working flawlessly now they used the attack and nothing happen !
