### ISSUE TITLE
Mgba not working on Mac OS 11.3 beta 6

### ISSUE THREAD

**Issue by Flemming7** [mgba-emu/mgba#2109]
When I try to open the app (version 0.9) on my Mac it says that the developer is not verified, is there a fix for this problem?

I found that this could be the problem: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution but I am not that technical...

**Comment by endrift** [comment]
This is a result of mGBA not being signed (like a lot of free software). Please look up ways to run unsigned programs even with Gatekeeper. I cannot sign software without paying Apple.
