### ISSUE TITLE
mGBA fails hblank_ly_scx_timing-GS

### ISSUE THREAD

**Issue by Kurayami7** [mgba-emu/mgba#2110]
![Capture](https://user-images.githubusercontent.com/77198254/113481657-75856f00-94e6-11eb-8d29-aa9e50a482ed.PNG)

[hblank_ly_scx_timing-GS.zip](https://github.com/mgba-emu/mgba/files/6252733/hblank_ly_scx_timing-GS.zip)

**Comment by endrift** [comment]
Please don't file issues for individual failing mooneye-gb tests; they're already in CInema so I know they're failing.

A blanket issue for all the ones that are failing may be fine though.
