### ISSUE TITLE
Jumped to invalid address: FFFFFB5A

### ISSUE THREAD

**Issue by leoxxx** [mgba-emu/mgba#2112]
Rom:Sonic Battle (translate by Bear Team)
mgba version:0.9.0
As shown in the gif.
![1](https://user-images.githubusercontent.com/5364709/113482279-83c89080-94d0-11eb-9f4e-b989e6ceaef9.gif)
If no save file, it will be triggered. So I create a save file by VisualBoyAdvance ,then play  the rom by mbga and it has no crash.

**Comment by endrift** [comment]
Do you have a link to the patch?

**Comment by leoxxx** [comment]
NO. Just have a rom. I have sent a email with it to you.

**Comment by leoxxx** [comment]
@endrift
Do you receive the email?

**Comment by endrift** [comment]
Yes I did. I haven't had time to look into it yet.

**Comment by endrift** [comment]
Unfortunately it also appears to crash on hardware on first run. It's an issue with the hack itself.

**Comment by leoxxx** [comment]
But why it has no error in VisualBoyAdvance?

**Comment by RetroEdit** [comment]
VisualBoyAdvance (VBA) is a less accurate emulator, so the ROM hack relies on inaccurate behavior compared to how a real GBA behaves.

mGBA is a high-accuracy project, so it's intended to replicate original hardware. If the ROM hack wouldn't work on original hardware, it's really considered a responsibility of the ROM hack developers to have done those tests, not mGBA to support every possible VBA bug.

**Comment by leoxxx** [comment]
I see.
