### ISSUE TITLE
mGBA fails intr_2_mode0_timing_sprites

### ISSUE THREAD

**Issue by Kurayami7** [mgba-emu/mgba#2113]
Let me know if you want me to stop reporting these. Otherwise I'm gonna go through the rest of the tests in this set. 

![Capture](https://user-images.githubusercontent.com/77198254/113482151-065d4a00-94e9-11eb-808f-1436af36f794.PNG)

[intr_2_mode0_timing_sprites.zip](https://github.com/mgba-emu/mgba/files/6252784/intr_2_mode0_timing_sprites.zip)

**Comment by endrift** [comment]
Closed for the same reason as #2110.
