### ISSUE TITLE
[UI][Windows] mgba forgets the frame size if you close it after maximizing

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2114]
Set a frame size, maximize, close it and open it again.
The next time will open a window that almost covers all the screen like a maximized window, but it isn't a maximized window.

Happens in the latest build (0.10-6908-be8b95f80) , 0.9.0 and 0.8.4.

**Comment by endrift** [comment]
Duplicate of #487, which I've tried to fix before.
