### ISSUE TITLE
Crashing when loading a savestate in Final Fantasy I+II Dawn of Souls

### ISSUE THREAD

**Issue by abiel0530** [mgba-emu/mgba#2115]
![image](https://user-images.githubusercontent.com/38668028/113488147-c731f780-94ee-11eb-8599-3e3a1fbdf8b7.png)
[error report.zip](https://github.com/mgba-emu/mgba/files/6253227/error.report.zip)

**Comment by endrift** [comment]
This may have been fixed in latest dev; please retest on a development build.

**Comment by abiel0530** [comment]
Tested it with 6916-af21292, savestates are loading okay now. Thank you!
