### ISSUE TITLE
Pokemon fire red/Leaf Green: Sound Quality of the menu selection sound

### ISSUE THREAD

**Issue by My1** [mgba-emu/mgba#2117]
it's not an overly big thing but compared to other emulators like vba the sound when scrolling through menus on channel one seems kinda less clear and not really nice in my opinion. (one might need headphones to hear the difference tho)

Version data:
Branch: heads/0.9.0
Revision: 42067aa322c46f648cd9f16e800641dce50c72b8
downloaded from website today
windows 10 2004 x64
CPU: i3-7020U
GPU: Intel HD 620 and Radeon 520.

**Comment by bleakassassin** [comment]
I noticed this long ago and even made an issue on it (#1552). It's an issue with all audio that utilizes the PSG chip for audio (square waves, triangle wave, noise channels). I can provide audio recordings from actual hardware for comparison. Here is the sound effect for scrolling through menus in Pokemon FireRed/LeafGreen, first off of a launch GBA (AGB-001) using a 3.5mm cable, then in mGBA through it's native a/v recording option:

[GBA](https://drive.google.com/file/d/1j_mdauYBGPDYH0pfjndMe3WNh_6CNftP/view?usp=sharing)
[mGBA](https://drive.google.com/file/d/1fGaLEe1I8-Hb0L_xRUZhAu3ilhB1cWz3/view?usp=sharing)

You might have to download the files and play them in an external program.

Also, here's something I noticed: the sound effect for using an item or Flying is actually wrong in mGBA. Along with being lower quality than actual hardware, it's pitched too low. Again, comparison is actual hardware and analog recording vs mGBA's internal recording:

[GBA](https://drive.google.com/file/d/19Q_pzwy1VPbzUAiMtyyWvkZlRVBCFYRE/view?usp=sharing)
[mGBA](https://drive.google.com/file/d/168fEX_WN0Rt3Nrzjv9VEE1WEYeKbe9xk/view?usp=sharing)

Any input would be greatly appreciated. I know audio isn't endrift's forte, but I feel like this is one area (of very few) where other emulators and solutions arguably still has an upper hand over mGBA.

**Comment by Gamulation** [comment]
It's the only problem I have with this emulator. It just sounds enoying listening to the text scroling sound. Music seems fine though, but the audio is not acurate, I also tested this on a few other emulators, VBA-M and VBA and they didn't have this problem.

**Comment by endrift** [comment]
VBA and VBA-M are basically the same, and they're known to "cheat" with PSG audio and make it higher quality (less aliased) than actual hardware.

**Comment by endrift** [comment]
Duping this to #1552 since it's probably the same root cause.
