### ISSUE TITLE
Restarting mGBA changes behavior of held fast forward

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#212]
I mapped the held fast forward button to the W key. It applied fine and worked successfully. When I closed mGBA and loaded it up again, the mapping was still shown correctly in the settings. However, it's function changed. It now behaved as a held A button. Re-mapping to the same key fixed the issue, but this occurs every time I restart mGBA.

**Comment by endrift** [comment]
Can you please upload your config file.

**Comment by tony971** [comment]
http://pastebin.com/rJGG2CN4

**Comment by endrift** [comment]
Can you upload the qt.ini file, too?

**Comment by tony971** [comment]
http://pastebin.com/Gad8qkYY

**Comment by endrift** [comment]
W is defaultly bound to autofire A, so it looks like the problem is that it's not actually getting loaded properly.
