### ISSUE TITLE
mGBA 0.9.0 slows down after prolonged fast forward speed (and freeze)

### ISSUE THREAD

**Issue by piperun** [mgba-emu/mgba#2120]
If you use Fast forward for quite some time, the game will struggle to keep 60fps going, even sometimes going so low as 4-8fps and if you try and use the emulator functions (save/load state, restart/shutdown, etc.) the emulator will freeze (and take some time to close unless you force kill it in task manager).

Tried on:
Pokémon Emerald (U)
Pokémon Emerald Kaizo
Pokémon Fire Red Omega
Pokémon Fire Red 1.1 (U)

Bellow is the bug report:
[bug.zip](https://github.com/mgba-emu/mgba/files/6296142/bug.zip)

**Comment by endrift** [comment]
Does this still happen with the OpenGL enhancement renderer disabled? And does it also happen with the latest dev build? This may be related to #2094, which I fixed last night.

**Comment by piperun** [comment]
This seems to be correct from my testing, if I disable OpenGL I haven't had this issue occur.

**Comment by endrift** [comment]
Please test that configuration. I can't tell if it's that bug or not otherwise.

**Comment by endrift** [comment]
Closing due to lack of reply.
