### ISSUE TITLE
Frame advance flickers forward and back

### ISSUE THREAD

**Issue by RetroEdit** [mgba-emu/mgba#2122]
## Versions tested

- 0.6.3: Not present
- 0.7.x and 0.8.x: Untested
- 0.9.0: Present
- b6e5b6e (latest master): Present

## Description

Something seems really off here: it seems like rendering during frame advance might be a frame off.

Here's what sometimes occurs: I press frame advance, it renders a frame that appears to be the next frame for a split-second, then reverts back to the previous frame (probably a clone frame, if the game updates graphics at 30 FPS).

Tested using Donkey Kong Country GBA.

**Comment by endrift** [comment]
I'm not sure why but I'm not able to reproduce anymore, even though I could before. Can you post a bug report zip when you have it reproducing?

**Comment by RetroEdit** [comment]
It occurred instantly for me, but sure.

**Comment by RetroEdit** [comment]
Here's a bug report zip. This particular log is midway through the intro. It also reproduces basically anywhere I tested; at the very start of the Rareware logo, the bug occurred.

[dkc-frame-advance-stutter.zip](https://github.com/mgba-emu/mgba/files/6317805/dkc-frame-advance-stutter.zip)

**Comment by endrift** [comment]
Wow, there's like...nothing in this config. I was trying to figure out stuff about your config but you either deleted all of it or this is an exceedingly fresh installation.

**Comment by RetroEdit** [comment]
@endrift Note `Portable: Yes` inside of `System info`.

I don't copy over config when I download a fresh mGBA; I generally re-configure it from scratch if necessary.

Generally, I try to treat testing like a controlled experiment, where I remove as many confounding variables as I can. This also reduces the chance that it's a user error on my part, but I do occasionally make them nonetheless.

**Comment by endrift** [comment]
I wasn't sure. The info I was specifically looking for wasn't present in the config so I couldn't tell if it was stripped down or just the default.

**Comment by RetroEdit** [comment]
Yep, just letting you know for the future. I think I am unlikely to get lazier with testing over time.
