### ISSUE TITLE
Loading save state fails on mgba-qt but works on mgba (linux)

### ISSUE THREAD

**Issue by glefundes** [mgba-emu/mgba#2123]
I'm running mGBA 0.9.0 on pop!_OS 20.10 and have encountered an issue with loading save states on Pokemon Radical Red.

After playing for some time on mgba-qt I had two saved sates: ss1, and a slightly outdated ss2.

When trying to load, ss1 appears to be successful but the game immediately resets to the opening screen and I'm unable to resume playing. ss2 on the other hand loads normally.

I then tried loading ss1 direcly via the CLI with

`mgba -t pkmn-radical-red/radical-red-v2.2b.ss1 -3 pkmn-radical-red/radical-red-v2.2b.gba`

and much to my surprise, the save state loaded normally like this. I'm glad I didn't lose my progress, but I'd really prefer playing on the QT version for the practicality and flexibility. Is there a fix for this? The bug report zip is attached below.
[bug-report.zip](https://github.com/mgba-emu/mgba/files/6306963/bug-report.zip)

**Comment by endrift** [comment]
This is most likely the same issue as #2097, which is fixed in latest dev builds already.

**Comment by endrift** [comment]
Please retest on a dev build.

**Comment by glefundes** [comment]
> Please retest on a dev build.
Sorry for the delay, couldn't test before as I wasn't able to reliable reproduce the issue until now. Just tested on 0.10-6950-a7c451708 and indeed it seems to be fixed. Thank you!
