### ISSUE TITLE
Webcam Access??

### ISSUE THREAD

**Issue by ChickenNugget25** [mgba-emu/mgba#2125]
I closed mGBA earlier today and it tried to open my webcam... Why?

**Comment by endrift** [comment]
It shouldn't attempt to access your webcam unless you were using a GB Camera ROM. I've gotten a few reports of something like this happening but haven't been able to reproduce.

**Comment by ChickenNugget25** [comment]
I'll just record closing it next time.  I was playing pokemon yellow.

**Comment by endrift** [comment]
I've figured out this can happen the first time you save settings. I'm looking into a fix now.

**Comment by endrift** [comment]
This should be fixed now. Thanks for poking me to look into it again.
