### ISSUE TITLE
LDMS with empty rlist does not reload CPSR when it should

### ISSUE THREAD

**Issue by ladystarbreeze** [mgba-emu/mgba#2127]
In mGBA 0.9.0, the `LDM rbase, {}^` instruction does not reload CPSR. Hardware interprets an empty rlist as "transfer r15" (which is correctly implemented in mGBA); however, this also applies to `LDMS`, so hardware ends up reloading CPSR.

```
; switch to Abort mode, set up SPSR
mov     r0, 0x17
msr     cpsr_csxf, r0
orr     r0, 0xF0000000
msr     spsr, r0

adr     r1, .Pool_Main
dw      0xE8D10000 ; ldmia r1, {}^

.Main_PrintResult:
    ; save new CPSR value, switch back to System mode
    mrs     r0, cpsr ; F0000017h on hardware, 00000017h in mGBA
    msr     cpsr_csxf, 0x1F
    mov     r1, 8
    bl      .PrintHex

.Loop_Endless:
    b       .Loop_Endless
    
.Pool_Main:
    dw      MEM_ROM0 + .Main_PrintResult
```

![ldmia_empty_cpsr](https://user-images.githubusercontent.com/51570316/114934221-ece9c580-9e39-11eb-9b73-c8ff104992ee.png)

![ldmia_empty_cpsr_mGBA](https://user-images.githubusercontent.com/51570316/114934226-eeb38900-9e39-11eb-8a0c-5fdc4f37c3de.png)

[ldmia_empty_cpsr.zip](https://github.com/mgba-emu/mgba/files/6320953/ldmia_empty_cpsr.zip)

**Comment by endrift** [comment]
Talk about an edge case of an edge case. Doesn't look hard to fix though.
