### ISSUE TITLE
mGBA crashes ("mGBA has stopped working") when attempting to make a save state

### ISSUE THREAD

**Issue by autofire372** [mgba-emu/mgba#213]
I'm on Windows 8.1. I was testing Castlevania: Harmony of Dissonance, and after making an in-game save, I attempted to make a quick save state, only for mGBA to crash upon hitting Shift+F1.

After restarting the emulator, I tried saving a state through the menu, and that crashed mGBA too.

**Comment by endrift** [comment]
Can you upload your config.ini file? I can't reproduce this locally.

**Comment by autofire372** [comment]
[Here](http://pastebin.com/dFqHH9JJ).

**Comment by autofire372** [comment]
Whoops, github fail on my part.

**Comment by tony971** [comment]
Also happens to me on Windows 10.

**Comment by endrift** [comment]
This is caused by a bad build of libpng in the Windows nightly. I've swapped out the build with the old one and it should be working now.

**Comment by autofire372** [comment]
Yep, it's working again. Thanks!
