### ISSUE TITLE
Regression: Hamtaro Ham-Ham Heartbreak crashing after new game name entry

### ISSUE THREAD

**Issue by n1ghttrap** [mgba-emu/mgba#2131]
This was previously reported in #840 and was closed after the following commit:
https://github.com/mgba-emu/mgba/commit/e71e4c69ed17c1f2ca208d71821fa337bf088b10

Seems like this prefetch behavior causes the issue, and has perhaps been reintroduced in later builds.  The crash occurs in both 0.9.0 and the dev build 6951-e6fb9f4.

Thanks in advance for your time.

**Comment by endrift** [comment]
Yeah, it's been broken again for a while. I'm pretty sure it's a timing issue.

**Comment by Dawnblairr** [comment]
noticed this as well today, from the current version pulled through the retroarch online updater.

**Comment by yontekh** [comment]
My gf is also experiencing this issue.
I tried both the USA and Europe ROM. Both softlock after entering name and starting the game.

It works fine in VBA 1.8.0.

**Comment by endrift** [comment]
I have a fix in the works for this, however it won't be able to be merged into 0.9.3, so it's being delayed until 0.10.0

**Comment by Meerkov** [comment]
Crazy. I went here to report this issue so I wouldn't annoy Yoshi, and yet here they are, one day before me with the same issue.
