### ISSUE TITLE
Holding down a key keeps raising interrupts

### ISSUE THREAD

**Issue by jtsiomb** [mgba-emu/mgba#2132]
I have a key interrupt handler which sets a global keypress variable, which is read and then cleared in the main loop. Testing on an actual GBA SP, pressing and holding down the button results in a single interrupt. The action in the main loop happens once until I release it again. mgba keeps raising interrupts for as long as the key is held down, and the action in the main loop happens continuously until I release it again.

I also tried the same thing on visualboy advance, which behaves exactly like mgba, and on no$gba which behaves like the actual hardware.

Tested on GNU/Linux with the SDL version of the latest mgba revision from git (e6fb9f44a74cf35fe03251520a49a3f52e6ee6be), and also tested the Qt version from the 0.8.3 release.

I can carve a minimal example from my GBA code to reproduce the problem if necessary.

**Comment by endrift** [comment]
This was fixed in e224b455761b32263deeb36821f8091fadc63399.
