### ISSUE TITLE
Metroid: Zero Mission - Some GSF files play burst of noise at boot

### ISSUE THREAD

**Issue by kode54** [mgba-emu/mgba#2134]
From the GSF set, which produce a self-booting ROM that does nothing but play music or audio, some of them produce a burst of static noise on boot, just before the intended sound output.

From the following, 98 - Save Complete.gsf, as converted to a stripped .GBA file:

[metroid_zero_mission_gsf.zip](https://github.com/mgba-emu/mgba/files/6346465/metroid_zero_mission_gsf.zip)

If I already posted this, I have no idea how to find it, other than somehow searching for my own issues.

**Comment by endrift** [comment]
Regressed in 5c58186f03fb053038ee804b44051f21623ec62c (cc @Gericom) -- seems the audio fifo fix broke this specifically, though I'm not sure why.

**Comment by endrift** [comment]
This reproduces on hardware. Not an mGBA bug, sorry.
