### ISSUE TITLE
mGBA crashes when loading roms using OpenGL

### ISSUE THREAD

**Issue by SilverKnight-Z** [mgba-emu/mgba#2136]
Hello, I have a problem with the latest version:
 
mGBA crashes and closes showing the Windows notification "mGBA has stopped working" when loading any rom, whether be Game Boy Advance, Color or Original. This happened to me also in version 0.9.0.

I found it strange since the previous version I use, 0.7.3, works perfectly out of the box (without changing anything but the controls and some hotkeys). I thought about changing options starting with the video system, and then, the roms loaded using "Sotware Qt", but the audio sounds noisy; when using "OpenGL" and "Open GL (force version 1.x)" the emulator tries to load the rom but crashes and closes. In contrast, version 0.7.3 loads any rom perfectly with smooth video and clear audio using "Open GL" as the video system.

I attach the report file generated by mGBA without loading any rom, because if it did, the emulator would simply close as I mentioned.

![crash with opengl](https://user-images.githubusercontent.com/82909608/115478342-f09f9280-a213-11eb-9425-373a0c98f296.png)
[crash with opengl.zip](https://github.com/mgba-emu/mgba/files/6347222/crash.with.opengl.zip)

**Comment by endrift** [comment]
Strange. What's your GPU? Are your drivers updated? Does this happen on 0.8.x?

**Comment by SilverKnight-Z** [comment]
- It' s the integrated video. Intel Graphics Media Accelerator 3150. I'm using a Samsung N150 Plus netbook
- The video driver is not up to date, but I prefer to leave it that way, because when I updated it the brightness on my netbook was stuck at maximum and I couldn't adjust it in any way. Luckily I managed to revert to the previous driver.
- I didn't try version 0.8.x, I went straight to 0.9.

**Comment by endrift** [comment]
Ah, the most garbage GPU ever. Still, having it be broken is a regression. Please try on 0.8.x to see if it work on any of them so I can narrow down when it broke.

**Comment by SilverKnight-Z** [comment]
I finished testing, but first a small clarification: I retested version 0.9.1 and the audio sounds fine, probably the environmental noise didn't let me hear it better or it was just my imagination.

That said, now the tests with versions 0.8.x:

- 0.8.0: mGBA behaved just as I previously reported.
- 0.8.1: Same as above
- 0.8.2: Same as above
- 0.8.3: Same as above, and also some lag at times. (of course this only happens with software Qt)
- 0.8.4: Same as above, lag is fixed (i.e., it behaves like in versions 0.8.0 through 0.8.2)

**Comment by endrift** [comment]
by "just as you previously reported" do you mean like 0.7.3 or like 0.9.x?

**Comment by SilverKnight-Z** [comment]
Hello, sorry for the late reply.

I mean 0.9.x

Also, today I did another test that I don't know if it has anything to do with my problem, but I hope it helps you in some way: 
I compared the time it takes for the library of each mGBA version to detect my roms in a folder. I have 120 roms in total; 33 Original Game Boy, 33 Game Boy Color, 51 Game Boy Advance and 3 more zipped Game Boy Color roms in a subfolder.

These were the results:
0.7.3 - 42.88 seconds.
0.8.0 - 21.64 seconds
0.8.1 - 27.37 seconds
0.8.2 - 28.83 seconds
0.8.3 - 29.02 seconds
0.8.4 - 26.43 seconds
0.9.0 - 47.62 seconds, and it detected the 3 compressed roms I had inside a sub-folder and the previous versions did not detect.
0.9.1 - 50.62 seconds, and just like 0.9.0, it detected the 3 compressed roms inside a sub-folder.

I did this test because I remembered that last night in 0.9.0 and 0.9.1 the library took longer than usual to fill up and I thought it was something that could not go unnoticed.

**Comment by endrift** [comment]
I am able to reproduce this bug on my ancient netbook, however I'm not really able to debug it without upgrading the Windows 7 license away from Starter. May take a bit.

**Comment by SilverKnight-Z** [comment]
No problem, I will wait patiently. Thank you for your hard work

**Comment by endrift** [comment]
I've just pushed a change that _may_ fix this _if_ you turn off the OSD. Download the latest dev build (7107 or newer), go to settings and under Interface, turn **off** Show OSD Messages, and then turn the Display driver in A/V back to OpenGL. See if that resolves the crashing for you, and makes the speed better.

**Comment by SilverKnight-Z** [comment]
Sorry for the late reply. Github doesn't notify me anything.
I tested several games, using opengl and opengl 1.x as video driver with dev build 0.10-7112-45e81d0ec from 11/09/2021 and I can conclude that:
- mGBA didn't crash.
- Game Boy original and Color games run perfect (between 59 and 60 fps).
- Gamera (#2202) runs at 60 fps, but it takes a couple of seconds to change screen and the audio is muted at that instant, like if there is lag, but there is not. However, this only happens when running it in SGB mode. I don't know if this is the actual behavior of the game in that scenario. In GB and GBC mode the audio is not muted at any time and the screen switching seems faster.
- Game Boy Advance games run equally well (between 59 and 60.4 fps), however sometimes there is a minimum of lag (between 53 and 58 fps) and a ocasional minimum of audio distortion. And when opening the file, emulation, etc, menus while the game is running, there is constant lag which reaches 45 fps. This does not happen with GB or GBC games
