### ISSUE TITLE
Crash in Pokemon Emerald after a certain amount of time in 0.9.1, but not in 0.9.0

### ISSUE THREAD

**Issue by mobileGBpokemon** [mgba-emu/mgba#2137]
I decided to update to the portable version of 0.9.1, and started playing Pokemon Emerald. However, I quickly learned that if I alt-tabbed away from the game, or if I tried to make the full screen game go to windowed using alt-enter, the game would be stuck on a previous frame and eventually crash. It's weird because in 0.9.0 portable it would not crash, even if I'm using the same config.ini file. In the end I just reverted back to 0.9.0.

I assume this glitch would also occur on other games, but I have only tested Pokemon Emerald on it.

**Comment by endrift** [comment]
Please upload the bug report zip generated by the bug report tool in the file menu.

**Comment by mobileGBpokemon** [comment]
[gba.zip](https://github.com/mgba-emu/mgba/files/6358599/gba.zip)
Oh, my bad, I totally forgot to do that before. One other thing I noticed is that it happens most often when you register someone in the PokeNav.

**Comment by endrift** [comment]
Can you see if this also reproduces if you use the Software display driver instead of OpenGL?

**Comment by mobileGBpokemon** [comment]
I was always using the Software driver instead of OpenGL because I figured it had better stability, so yes, I can confirm that this occurs using the Software driver.

**Comment by endrift** [comment]
The config file shows you're using the OpenGL driver though.

**Comment by mobileGBpokemon** [comment]
I apologize, I was looking in the complete wrong place for the video driver settings. I was checking under "Enhancements" instead of "Audio/Video".

Anyways, when I used the Software driver, the bug did not occur in my ~1 hour of playtime, but there was a seeming... delay in the responsiveness that was not there in OpenGL, so I will continue using OpenGL on 0.9.0.

I am now wondering what in OpenGL could have caused that weird bug in 0.9.1 when it didn't do it in 0.9.0 and in all versions prior.

**Comment by endrift** [comment]
There were changes to that code path in 0.9.1. I should take a closer look.

**Comment by endrift** [comment]
Is it a crash (the program just disappears) or a hang (the program becomes unresponsive)? They're different and tell me a bunch of information just in the presence of that difference.

**Comment by mobileGBpokemon** [comment]
It's definitely a hang, sorry for not making that clear earlier.

**Comment by endrift** [comment]
Ok, I found some potential deadlocks. I fixed them, so please tell me if that fixes it for you using latest dev build.

**Comment by mobileGBpokemon** [comment]
It seems to have fixed it in the latest dev build. Thanks!
