### ISSUE TITLE
Messy graphic when enabling xbr filter

### ISSUE THREAD

**Issue by CarterLi** [mgba-emu/mgba#214]
Audio/Video => Shader Options... => Load New Shader => `Select xbr.shader`
![screenshot 2016-01-26_22-08-06](https://cloud.githubusercontent.com/assets/6134068/12582702/ac2db6fe-c479-11e5-8e92-d8e6d5ebb099.png)
Version: 0.4-3182-b2850af
OS: OSX 10.11.3

**Comment by endrift** [comment]
This is a GPU bug on OS X with the Intel drivers. Wish I could fix it, but this specific xBR impl just won't work with your configuration. Sorry.
