### ISSUE TITLE
Drill Dozer, no rumble

### ISSUE THREAD

**Issue by Hexaae** [mgba-emu/mgba#2146]
Rumble not working with Drill Dozer (same game on VBA-M emulator does rumble). I've enabled Settings > Emulation > Enable GBP features by default and Game overrides > Rumble + GBP features but still can't feel rumble on my XBox One Bluetooth controller with mGBA 0.9.1.

**Comment by endrift** [comment]
I was investigating this issue earlier and I believe it's related to the upgraded version of SDL I used in 0.9. Rolling it back to 2.0.12 seems to bring rumble back (which I did in https://github.com/mgba-emu/dependencies/commit/4779e01c50854abdd23dcb1355f05e46c19c7a7e), so I'm going to try respinning the builds of 0.9.1 on Windows soon with the different version of SDL applied.

**Comment by Hexaae** [comment]
Can't SDL.dll be loaded from the exe dir? This would make it easier to change it and experiment different versions...

**Comment by endrift** [comment]
No, it's statically linked into the .exe to make it easier to distribute.

**Comment by Hexaae** [comment]
> No, it's statically linked into the .exe to make it easier to distribute.

I suggest the std dynamic loading method for the future. Not excluded some users may have issues with weird controllers from time to time, and swapping SDL could be an easier solution than waiting for a new mGBA build.  Just my 2 cents.

**Comment by autofire372** [comment]
> 
> 
> > No, it's statically linked into the .exe to make it easier to distribute.
> 
> I suggest the std dynamic loading method for the future. Not excluded some users may have issues with weird controllers from time to time, and swapping SDL could be an easier solution than waiting for a new mGBA build. Just my 2 cents.

Speaking from experience, dynamically-linked builds of mGBA (on Windows, at least) refuse to launch unless started from mingw.

**Comment by Hexaae** [comment]
> so I'm going to try respinning the builds of 0.9.1 on Windows soon with the different version of SDL applied.

If you need beta-testing for rumble here I am

**Comment by endrift** [comment]
New builds are available at the same download links as before, and they have working rumble for me now.
