### ISSUE TITLE
Downloads lack version for Ubuntu 21.04

### ISSUE THREAD

**Issue by v1993** [mgba-emu/mgba#2148]
When trying to run 0.9.1 build for Ubuntu 20.10 on 21.04 I get an error

```
mgba-qt: error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory
```

It seems that libzip have been updated in new distro version, so it's required to build on it.

**Comment by endrift** [comment]
![image](https://user-images.githubusercontent.com/605502/116496587-41d60480-a85a-11eb-83f6-562d18079687.png)

This has been here the whole time.

**Comment by endrift** [comment]
It seems there was an issue with this build that could lead to the error you see above. This has been addressed and the linked file is updated with what should be a working version now.
