### ISSUE TITLE
Feature request: Fast forward mute on other platforms

### ISSUE THREAD

**Issue by rik-smeets** [mgba-emu/mgba#2150]
I use mGBA as an emulator on the Wii. The function to mute audio whilst fast forwarding like in the Windows desktop app isn't available there (unless I missed it somehow). So when activating fast forward, I manually mute and unmute the audio.

Even though I'm unexperienced with coding in C, I did manage to build a working version which includes this feature. It's probably not optimal, but if you like I could open a pull request? It'd be open for review/changes of course.

**Comment by RetroEdit** [comment]
endrift is happy to get pull requests, so feel free to send one. Worst that happens, it won't get accepted. Most likely, there will be a feedback and review process.
