### ISSUE TITLE
[HLE BIOS] Temporal glitched screen after restarting some GBC games

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2152]
Without an official BIOS, some GBC games may show a garbage screen after doing a hard reset (ctrl+R)  in the middle of certain scenes. It usually only lasts one second, but some can lasts longer.

A few examples:

- **Donkey Kong Land** (reset in the title screen, also gameplay)
![Donkey Kong Land (USA, Europe)-3](https://user-images.githubusercontent.com/16591467/116534872-61653f80-a8e3-11eb-8742-7dc860993deb.png)

- **Pokemon Yellow** (reset in the title screen)
![Pokemon Amarillo-0](https://user-images.githubusercontent.com/16591467/116534904-675b2080-a8e3-11eb-8f8f-93d270e5dfae.png)

- **Infinity** (pretty much any moment)
![infinity-1](https://user-images.githubusercontent.com/16591467/116534925-6f1ac500-a8e3-11eb-9918-69983e9ac7d5.png)

- **Meitantei Conan - Kigantou Hihou Densetsu (Japan) (SGB Enhanced)** with english patch
![Meitantei Conan - Kigantou Hihou Densetsu (Japan) (SGB Enhanced) ENG-0](https://user-images.githubusercontent.com/16591467/116535077-a25d5400-a8e3-11eb-8bf3-87dd281ab3eb.png)

-Alone in the Dark: New Nightmare

THe issue is present in the most recent build (0.10-6970-91874af0c) but also in old stable ones (0.8.4)

**Comment by endrift** [comment]
Yeah I've seen stuff like this too. It's been kinda low priority for perhaps obvious reasons.
