### ISSUE TITLE
Regression Issue - Object layer now rendering one row of pixels too low over background

### ISSUE THREAD

**Issue by CliveArdern** [mgba-emu/mgba#2153]
**Build:** 0.9.1
**OS:** Windows 10 x64
**CPU:** Ryzen 7 3800X
**GPU:** RTX 2070 SUPER
**Frequency:** 100%
**Games tested:** Golden Sun, Golden Sun: The Lost Age

**Steps to Reproduce**
1. In Golden Sun or Golden Sun: The Lost Age, begin any random battle.
2. Select Fight and observe the bottom UI.

**Description:**
Several layers appear to be incorrectly rendering one pixel too high or too low. This is most noticeable in the Golden Sun games where the character sprites in the Object layer can be seen overlapping the top row of pixels on the Background 1 layer. 
In addition, the top row of pixels appears to be duplicated, rendering to two rows instead of one.

**Additional Info:**
This issue occurs **regardless** of renderer or enhancement selections.
This issue is **not** present in 0.8.4. Other intermediary builds have not been tested.
This may be the same issue as #2149 

**Image A: Character sprites overlapping the buttons in 0.9.1**
![image](https://user-images.githubusercontent.com/52113871/116550986-51535d00-a8ef-11eb-83d2-679953b6b602.png)

**Image B: No issues present in 0.8.4**
![image](https://user-images.githubusercontent.com/52113871/116551071-6e882b80-a8ef-11eb-9621-8e3415a38fac.png)

**Comment by endrift** [comment]
This is possibly fallout from https://github.com/mgba-emu/mgba/commit/c73ad72d4106801ffd716b97e25cdc42e8720f44.

**Comment by endrift** [comment]
I can confirm that reverting that change _does_ fix this, as well as #2149, without regressing the bug it was designed to fix. Reverting it seems like a good plan until I can change the GBA renderer to range-based.
