### ISSUE TITLE
The Legend of Zelda: Oracle of Seasons (Europe) - Problems loading a save point

### ISSUE THREAD

**Issue by Chocolateunu** [mgba-emu/mgba#2158]
Hi

I have a problem that, after starting the game, I try to load a save point and it fails, causing a black screen and sound glitches.

Attached a video of the problem and the bug report when it is with the problem.

https://user-images.githubusercontent.com/69604481/116883185-4ea87e80-abf3-11eb-8b6c-db6f54cc9876.mp4
[Oracle of Seasons problem.zip](https://github.com/mgba-emu/mgba/files/6415139/Oracle.of.Seasons.problem.zip)

**Comment by endrift** [comment]
Can you please upload the .ss1 file associated with your ROM?

**Comment by Chocolateunu** [comment]
[LOZ - OFS ss1.zip](https://github.com/mgba-emu/mgba/files/6442749/LOZ.-.OFS.ss1.zip)
No problem. Here you go

**Comment by Chocolateunu** [comment]
Hello, @endrift. Sorry for mentioning you, but I wanted to know if the problem I had with the savestate was something mine or indeed there was a saving problem

**Comment by endrift** [comment]
I have not yet looked into it, sorry.

**Comment by Chocolateunu** [comment]
> I have not yet looked into it, sorry.

No problem !!!

**Comment by Chocolateunu** [comment]
For curiosity, I rechecked what was going on and when I saved again, overwriting the corrupted save, it worked. I'm sorry for the bad timing that could have caused this.

**Comment by endrift** [comment]
Yeah this savestate is very clearly broken. I'm not really sure how it got created so broken, but that's the bigger issue here.
