### ISSUE TITLE
[3DS] Sound starts glitching when the menu is accessed

### ISSUE THREAD

**Issue by FayneAldan** [mgba-emu/mgba#216]
Every time the menu is accessed, the sound starts glitching, with it getting more messed up every time you access the menu.

**Comment by endrift** [comment]
This is related to the use of CSND. Adding NDSP support will fix this, but I haven't been able to get that working yet.

**Comment by endrift** [comment]
Landed DSP, which fixes this.

**Comment by FayneAldan** [comment]
:smile:
