### ISSUE TITLE
mGBA - POKEMON FIRE - 0.9.1 Fast Forward Causing Crashes (Windows X)

### ISSUE THREAD

**Issue by Weberton01** [mgba-emu/mgba#2160]
When I use fast forward on the emulator, it causes a crash an unpredictable amount of time after or whenever I turn fast forward off. It might go for five minutes or one minute. All my settings are set to default. Help is appreciated.

**Comment by endrift** [comment]
If you have sync to video turned on turn it off. That setting is buggy in 0.9.1.

**Comment by endrift** [comment]
Have you tried seeing if it's on and if turning it off to see if it fixes it?

**Comment by endrift** [comment]
Closing due to lack of reply, assuming it's a duplicate of #2138.
