### ISSUE TITLE
[Game Boy] "Use GBC colors in GB games" displays SGB colors when checked

### ISSUE THREAD

**Issue by tuzepoito** [mgba-emu/mgba#2161]
### Environment
- **Platform**: Windows 8.1 64-bit
- **mGBA version**: 0.10-6981-380987617
- **mGBA interface**: mGBA Qt 64-bit

### Description of bug

**Pre-steps**:
- Open mGBA Qt.
- Go to "Tools > Settings > Game Boy".
- Use the following settings:
![mgba-settings](https://user-images.githubusercontent.com/47950394/117308447-d6a3b800-ae81-11eb-835a-6665d0cd7c74.png)
- Load a GB game that has a builtin color palette in the Game Boy Color system (examples: Donkey Kong (World) (Rev 1), Donkey Kong Land (USA, Europe), Pac-In-Time (Europe) )

**Expected behavior**:
The screen displays colors as seen on a Game Boy Color.
![dkl-title-expected](https://user-images.githubusercontent.com/47950394/117307310-bf17ff80-ae80-11eb-8296-3374c84ae002.png)

**Observed behavior**:
The screen displays a different color palette, apparently the one seen on the Super Game Boy.
![dkl-title-mgba](https://user-images.githubusercontent.com/47950394/117308977-4ca81f00-ae82-11eb-9d13-eacc263cd4e4.png)

**Additional information**:

In the settings I set all systems to "Game Boy Color (CGB)" on purpose, just to make sure it is Game Boy Color that is emulated; to no avail, the Super Game Boy color palette is still displayed.

It seems the "Use GBC colors in GB games" checkbox forces use of SGB palettes instead of GBC palettes, contrary to what is displayed on the checkbox description. For many SGB games, this is not a problem because it seems the builtin GBC palettes were modeled after the Super Game Boy palettes. However, there are a few select games where the GBC palette is different from the SGB palette; and apparently, if the box is checked the system behaves as a Super Game Boy.

I have other examples:

Donkey Kong Land (USA, Europe):
Expected:
![dkl-expected](https://user-images.githubusercontent.com/47950394/117311261-56cb1d00-ae84-11eb-9f9f-6eff4d74cb96.png)

Observed:
![dkl-mgba](https://user-images.githubusercontent.com/47950394/117311245-516dd280-ae84-11eb-8a3f-4cb18b909546.png)

Donkey Kong (World) (Rev 1):
Expected:
![dk-expected](https://user-images.githubusercontent.com/47950394/117311406-73675500-ae84-11eb-8050-39751b5ecaeb.png)

Observed:
![dk-mgba](https://user-images.githubusercontent.com/47950394/117311428-77937280-ae84-11eb-9e6e-4930c0b5441d.png)

Pac-In-Time (Europe):
Expected:
![pacintime-begin-expected](https://user-images.githubusercontent.com/47950394/117311474-80844400-ae84-11eb-9c63-c5d6cc4becbd.png)
![pacintime-title-expected](https://user-images.githubusercontent.com/47950394/117311486-82e69e00-ae84-11eb-89e9-50cceabeb163.png)
![pacintime-expected](https://user-images.githubusercontent.com/47950394/117311495-84b06180-ae84-11eb-8a56-4de14b6d8fd7.png)

Observed:
![pacintime-begin-mgba](https://user-images.githubusercontent.com/47950394/117311512-8843e880-ae84-11eb-9c0d-58a7f03909bc.png)
![pacintime-title-mgba](https://user-images.githubusercontent.com/47950394/117311522-8b3ed900-ae84-11eb-8099-a1ef2c23ddc3.png)
![pacintime-mgba](https://user-images.githubusercontent.com/47950394/117311530-8d089c80-ae84-11eb-932a-bd9d12f48e34.png)

**Comment by endrift** [comment]
Well, you've completely mischaracterized what's going on here (they're loading as SGB games, not GB games with SGB borders, and it almost certainly has nothing to do with that checkbox), but given you've set all the models to CGB that shouldn't be happening (and might have other undesired side effects).

**Comment by tuzepoito** [comment]
> given you've set all the models to CGB that shouldn't be happening (and might have other undesired side effects).

That's the point: I expected that setting all systems to CGB, and checking "Use GBC colors in GB games" would force loading the CGB palettes. But it doesn't happen. So I began wondering what that checkbox is supposed to do.

**Comment by endrift** [comment]
It turns out the specific bug here is that the GBC colors setting breaks the GB model overrides settings above, and they end up detecting as SGB games. That is a bug, not an intended behavior. I have a fix ready.

**Comment by tuzepoito** [comment]
Thanks, the colors are displayed accurately for those games.

**Comment by xHuGoatx** [comment]
Is this possible on ps vita ?
