### ISSUE TITLE
mGBA hangs and then crashes when clearing cache / Suggestion to improve grouping in library tree view

### ISSUE THREAD

**Issue by SilverKnight-Z** [mgba-emu/mgba#2171]
Hello again, this time I' m reporting some issues that happened while testing with the roms library.

First of all, mGBA hangs and then crashes after pressing the "clear cache" button in the "interface" section of the "settings" window (See screenshots 1, 2 and 3). Curiously, the rom library appears completely clean when the emulator is reopened. This means that it still does its job despite the crash. This happens from version 0.8.2 to 0.9.1.

![hang and crash in 082 a 084 when clearing cache](https://user-images.githubusercontent.com/82909608/118015493-53bbab00-b322-11eb-9bae-197d70684f39.jpg)
Screenshot 1: mGBA 0.8.2 hanging and crashing when clearing cache

![hang and crash in 090,091 when clearing cache 1](https://user-images.githubusercontent.com/82909608/118015990-de9ca580-b322-11eb-9ac5-66af16498cb9.jpg)
Screenshot 2: mGBA 0.9.1 hanging when clearing cache

![hang and crash in 090,091 when clearing cache 2](https://user-images.githubusercontent.com/82909608/118016167-13a8f800-b323-11eb-9675-4397b9f1ae92.jpg)
Screenshot 3: mGBA 0.9.0 crashing

It' s worth noting that in versions 0.7.3, 0.8.0 and 0.8.1 I can clear the cache quickly and perfectly, without hangs or crashes.

Moving on and before I bring up the next topic, I should point out that I have my roms unzipped in a main folder, which itself has a subfolder with more compressed roms plus a single unzipped one.

That said, the grouping in the library tree view is odd (for lack of a better word) and needs improvement (which I'll explain later). I'll explain what happens since version 0.7.3, so you get my point:

- In 0.7.3 mGBA detects the main folder where my unzipped roms are and the subfolder I mentioned before, as can be seen in screenshot 4. However, it does not detect the roms inside the subfolder; neither the compressed ones nor the single unzipped rom that is there.

![árbol mgba 073](https://user-images.githubusercontent.com/82909608/118017130-3b4c9000-b324-11eb-8e42-44fdecd1be1c.jpg)
Screenshot 4: mGBA 0.7.3 Detecting roms only in the main folder

- From 0.8.0 to 0.8.4 mGBA only detects the main folder with the unzipped roms and does not detect the subfolder anymore (see Screenshot 5).

![árbol mgba 080 a 084](https://user-images.githubusercontent.com/82909608/118017332-7a7ae100-b324-11eb-8fd1-215b72e4645e.jpg)
Screenshot 5: mGBA 0.8.0 detecting only the main folder with its roms

- In 0.9.0 and 0.9.1 is where the grouping in the tree view gets odd, because while it detects ALL roms (both in the main folder and the subfolder, zipped and unzipped), only the unzipped ones in the main folder are grouped correctly where they should be; while the zipped roms in the subfolder appear at the same tree level as the main folder, and the only thing that appears inside the subfolder is the single unzipped rom it has inside (see Screenshots 6 and 7).

![árbol mgba 090 y 091-1 EDITADO](https://user-images.githubusercontent.com/82909608/118017657-e2312c00-b324-11eb-9dba-ccb43818cc7a.jpg)
Screenshot 6: Tree with all roms detected by mGBA 0.9.0 part 1

![árbol mgba 090 y 091-2 EDITADO](https://user-images.githubusercontent.com/82909608/118017745-f70dbf80-b324-11eb-93b9-cb505401636a.jpg)
Screenshot 7: Tree with all roms detected by mGBA 0.9.0 part 2

Ideally, all roms should appear together at the same tree level that belongs to the folder or subfolder they are in, I mean something like this:

![árbol mgba orden propuesto EDITADO](https://user-images.githubusercontent.com/82909608/118018100-5a97ed00-b325-11eb-9ffd-d554206b2638.jpg)
Screenshot 8: Suggested grouping for tree view

I hope that my ideas were understandable and also attached the report file that I generated with mGBA 0.9.1. 
[Crash when clearing cache.zip](https://github.com/mgba-emu/mgba/files/6468014/Crash.when.clearing.cache.zip)

Thank you very much for your time.

**Comment by endrift** [comment]
The cache clearing issue may be fixed by 405f12d1bdfd2d2ce239c2cf6e2fd6107f41066f, please check in the latest build.

Also, since you can put multiple ROMs in a single zip breaking them out into folders makes sense, though special casing zips with only one ROM in them may make sense to collapse.

**Comment by endrift** [comment]
Also this report is for two separate things, which you should not do on a bug tracker, especially since one is a bug and one is an enhancement request. It makes it harder to track what's done or not. Please file a separate ticket for the feature request if the cache issue is not already fixed in the aforementioned commit.

**Comment by SilverKnight-Z** [comment]
> The cache clearing issue may be fixed by 405f12d, please check in the latest build.

I tested the mGBA dev build 0.10-6995-96988133b and indeed, it''s solved. Thank you. 

> Also this report is for two separate things, which you should not do on a bug tracker, especially since one is a bug and one is an enhancement request. It makes it harder to track what's done or not. Please file a separate ticket for the feature request if the cache issue is not already fixed in the aforementioned commit.

I'm very sorry, I figured it would be more comfortable for you and I was afraid it would look like spam if I made too many requests. From now on, I'll do it as you indicated. In fact I'll open a few right now.
