### ISSUE TITLE
[Feature Request] Support for more save files and savestates formats in the converter

### ISSUE THREAD

**Issue by SilverKnight-Z** [mgba-emu/mgba#2177]
As stated in the title, it would be great to be able to convert to and from more save files and savestates formats, as it would make it easier to fully migrate to mGBA from other emulators such as Visual Boy Advance Link, Visual Boy Advance-M, Gambatte, Gearboy, TGBDual, among others; or even exchange save files between them.

Formats such as:

**Save files**

- ".sa1" - VBA Link
- ".srm" - Retroarch cores for GB, GBC and GBA (Gambatte, Gearboy, TGBDual)
- and others

**Status files**

- ".sg1"- VBA Link 
- ".sgm" -VBA-M
- and others

**Comment by endrift** [comment]
"Battery" save files just need to have the extension changed, there's no actual conversion to do there.

Save state files cannot be converted effectively due to having way too much application-specific information in them and generally being less stable between versions.

**Comment by SilverKnight-Z** [comment]
> Save state files cannot be converted effectively due to having way too much application-specific information in them and generally being less stable between versions.

Oh, I see

> "Battery" save files just need to have the extension changed, there's no actual conversion to do there.

Ah, still, I'll do some tests and comment later

**Comment by endrift** [comment]
I do intend to add support for (at least) importing NO$GBA saves, but I've yet to determine the format they're in (there's no documentation of course) so that might take time.

**Comment by SilverKnight-Z** [comment]
> I do intend to add support for (at least) importing NO$GBA saves, but I've yet to determine the format they're in (there's no documentation of course) so that might take time.

Oh great! That's good to hear. Good luck with that

> "Battery" save files just need to have the extension changed, there's no actual conversion to do there.

Indeed, the save files work perfectly by changing their extension. I tested the ones I had from Visualboy Advance Link 1.8 and InfoGB for Playstation 2. 

Thanks for your advice
