### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by FieryMewtwo** [mgba-emu/mgba#2179]
I'm using Homebrew on my O3DS (not CFW) and was wondering if I needed the xml and smdh files, or just the 3dsx file.

**Comment by fancythedeveloper** [comment]
Pretty sure you only really need the 3dsx file, but preferably just get all.

**Comment by FieryMewtwo** [comment]
Okay, thank you!

**Comment by endrift** [comment]
You should use the xml file too, especially on o3DS without cfw.

**Comment by FieryMewtwo** [comment]
Okay.

**Comment by endrift** [comment]
Why did you reopen this and didn't post anything?

**Comment by FieryMewtwo** [comment]
mGBA still doesn't work at all. I'll just use another emulator.
