### ISSUE TITLE
Compiling fails on Raspberry Pi 2 (Ubuntu Mate)

### ISSUE THREAD

**Issue by fredericmeyer** [mgba-emu/mgba#218]
Compiling on my Raspberry Pi 2 with Ubuntu Mate failed with the following error message:
```
[ 75%] Building CXX object qt/CMakeFiles/mgba-qt.dir/DisplayGL.cpp.o
In file included from /usr/include/GL/gl.h:2055:0,
                 from /home/frederic/Schreibtisch/mgba/src/platform/opengl/gl.h:14,
                 from /home/frederic/Schreibtisch/mgba/src/platform/qt/DisplayGL.cpp:15:
/usr/include/GL/glext.h:468:19: error: conflicting declaration ‘typedef ptrdiff_t GLsizeiptr’
 typedef ptrdiff_t GLsizeiptr;
                   ^
In file included from /usr/include/arm-linux-gnueabihf/qt5/QtGui/qopengl.h:97:0,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL/qgl.h:39,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL/QGLWidget:1,
                 from /home/frederic/Schreibtisch/mgba/src/platform/qt/DisplayGL.h:18,
                 from /home/frederic/Schreibtisch/mgba/src/platform/qt/DisplayGL.cpp:6:
/usr/include/GLES3/gl3.h:69:25: note: previous declaration as ‘typedef khronos_ssize_t GLsizeiptr’
 typedef khronos_ssize_t GLsizeiptr;
                         ^
In file included from /usr/include/GL/gl.h:2055:0,
                 from /home/frederic/Schreibtisch/mgba/src/platform/opengl/gl.h:14,
                 from /home/frederic/Schreibtisch/mgba/src/platform/qt/DisplayGL.cpp:15:
/usr/include/GL/glext.h:469:19: error: conflicting declaration ‘typedef ptrdiff_t GLintptr’
 typedef ptrdiff_t GLintptr;
                   ^
In file included from /usr/include/arm-linux-gnueabihf/qt5/QtGui/qopengl.h:97:0,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL/qgl.h:39,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL/QGLWidget:1,
                 from /home/frederic/Schreibtisch/mgba/src/platform/qt/DisplayGL.h:18,
                 from /home/frederic/Schreibtisch/mgba/src/platform/qt/DisplayGL.cpp:6:
/usr/include/GLES3/gl3.h:70:26: note: previous declaration as ‘typedef khronos_intptr_t GLintptr’
 typedef khronos_intptr_t GLintptr;
                          ^
qt/CMakeFiles/mgba-qt.dir/build.make:298: recipe for target 'qt/CMakeFiles/mgba-qt.dir/DisplayGL.cpp.o' failed
make[2]: *** [qt/CMakeFiles/mgba-qt.dir/DisplayGL.cpp.o] Error 1
CMakeFiles/Makefile2:197: recipe for target 'qt/CMakeFiles/mgba-qt.dir/all' failed
make[1]: *** [qt/CMakeFiles/mgba-qt.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by endrift** [comment]
Can you delete the build directory and paste the output of running CMake fresh?

**Comment by fredericmeyer** [comment]
This is the result of downloadingt the newest source in a fresh CMake environment:
[ 77%] Building CXX object qt/CMakeFiles/mgba-qt.dir/DisplayGL.cpp.o
In file included from /home/pi/mgba-0.5.0/src/platform/opengl/gl.h:17:0,
                 from /home/pi/mgba-0.5.0/src/platform/qt/DisplayGL.cpp:15:
/usr/include/GL/gl.h:134:17: error: conflicting declaration ‘typedef double GLdouble’
 typedef double  GLdouble; /* double precision float */
                 ^
In file included from /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL/qgl.h:47:0,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL/QGLWidget:1,
                 from /home/pi/mgba-0.5.0/src/platform/qt/DisplayGL.h:18,
                 from /home/pi/mgba-0.5.0/src/platform/qt/DisplayGL.cpp:6:
/usr/include/arm-linux-gnueabihf/qt5/QtGui/qopengl.h:98:17: note: previous declaration as ‘typedef GLfloat GLdouble’
 typedef GLfloat GLdouble;
                 ^
In file included from /usr/include/GL/gl.h:2055:0,
                 from /home/pi/mgba-0.5.0/src/platform/opengl/gl.h:17,
                 from /home/pi/mgba-0.5.0/src/platform/qt/DisplayGL.cpp:15:
/usr/include/GL/glext.h:468:19: error: conflicting declaration ‘typedef ptrdiff_t GLsizeiptr’
 typedef ptrdiff_t GLsizeiptr;
                   ^
In file included from /usr/include/arm-linux-gnueabihf/qt5/QtGui/qopengl.h:82:0,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL/qgl.h:47,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL/QGLWidget:1,
                 from /home/pi/mgba-0.5.0/src/platform/qt/DisplayGL.h:18,
                 from /home/pi/mgba-0.5.0/src/platform/qt/DisplayGL.cpp:6:
/usr/include/GLES2/gl2.h:69:25: note: previous declaration as ‘typedef khronos_ssize_t GLsizeiptr’
 typedef khronos_ssize_t GLsizeiptr;
                         ^
In file included from /usr/include/GL/gl.h:2055:0,
                 from /home/pi/mgba-0.5.0/src/platform/opengl/gl.h:17,
                 from /home/pi/mgba-0.5.0/src/platform/qt/DisplayGL.cpp:15:
/usr/include/GL/glext.h:469:19: error: conflicting declaration ‘typedef ptrdiff_t GLintptr’
 typedef ptrdiff_t GLintptr;
                   ^
In file included from /usr/include/arm-linux-gnueabihf/qt5/QtGui/qopengl.h:82:0,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL/qgl.h:47,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL/QGLWidget:1,
                 from /home/pi/mgba-0.5.0/src/platform/qt/DisplayGL.h:18,
                 from /home/pi/mgba-0.5.0/src/platform/qt/DisplayGL.cpp:6:
/usr/include/GLES2/gl2.h:70:26: note: previous declaration as ‘typedef khronos_intptr_t GLintptr’
 typedef khronos_intptr_t GLintptr;
                          ^
In file included from /usr/include/GL/gl.h:2055:0,
                 from /home/pi/mgba-0.5.0/src/platform/opengl/gl.h:17,
                 from /home/pi/mgba-0.5.0/src/platform/qt/DisplayGL.cpp:15:
/usr/include/GL/glext.h:2205:149: error: conflicting declaration ‘typedef void (* GLDEBUGPROC)(GLenum, GLenum, GLuint, GLenum, GLsizei, const GLchar*, const void*)’
 typedef void (APIENTRY  *GLDEBUGPROC)(GLenum source,GLenum type,GLuint id,GLenum severity,GLsizei length,const GLchar *message,const void *userParam);
                                                                                                                                                     ^
In file included from /usr/include/arm-linux-gnueabihf/qt5/QtGui/qopengl.h:92:0,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL/qgl.h:47,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL/QGLWidget:1,
                 from /home/pi/mgba-0.5.0/src/platform/qt/DisplayGL.h:18,
                 from /home/pi/mgba-0.5.0/src/platform/qt/DisplayGL.cpp:6:
/usr/include/arm-linux-gnueabihf/qt5/QtGui/qopengles2ext.h:192:28: note: previous declaration as ‘typedef void (* GLDEBUGPROC)(GLenum, GLenum, GLuint, GLenum, GLsizei, const GLchar*, GLvoid*)’
 typedef void (GL_APIENTRYP GLDEBUGPROC)(GLenum source,GLenum type,GLuint id,GLenum severity,GLsizei length,const GLchar *message,GLvoid *userParam);
                            ^
qt/CMakeFiles/mgba-qt.dir/build.make:331: recipe for target 'qt/CMakeFiles/mgba-qt.dir/DisplayGL.cpp.o' failed
make[2]: *** [qt/CMakeFiles/mgba-qt.dir/DisplayGL.cpp.o] Error 1
CMakeFiles/Makefile2:197: recipe for target 'qt/CMakeFiles/mgba-qt.dir/all' failed
make[1]: *** [qt/CMakeFiles/mgba-qt.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
pi@raspberrypi:~/buildmgba $ 

Also according to glxinfo I have OpenGL  3.0:
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.7, 128 bits)
OpenGL version string: 3.0 Mesa 11.1.0
OpenGL shading language version string: 1.30

Wondering why it says VMWare, Inc. though.

**Comment by endrift** [comment]
No...I said the output from CMake, not from make ;_;

Also it says VMware because VMware owns mesa. You don't have real OpenGL, you have a software renderer.

**Comment by fredericmeyer** [comment]
My bad, I'm stupid ;_; I should've know better, since I actually use cmake in my own projects XD
Anywhere, here you go:
```
-- The C compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Looking for strdup
-- Looking for strdup - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for localtime_r
-- Looking for localtime_r - found
-- Looking for snprintf_l
-- Looking for snprintf_l - not found
-- Looking for newlocale
-- Looking for newlocale - found
-- Looking for freelocale
-- Looking for freelocale - found
-- Looking for uselocale
-- Looking for uselocale - found
-- Looking for setlocale
-- Looking for setlocale - found
-- Looking for chmod
-- Looking for chmod - found
-- Looking for umask
-- Looking for umask - found
-- checking for one of the modules 'libedit'
-- Looking for XOpenDisplay in /usr/lib/arm-linux-gnueabihf/libX11.so;/usr/lib/arm-linux-gnueabihf/libXext.so
-- Looking for XOpenDisplay in /usr/lib/arm-linux-gnueabihf/libX11.so;/usr/lib/arm-linux-gnueabihf/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/arm-linux-gnueabihf/libX11.so
-- checking for one of the modules 'libavcodec'
-- checking for one of the modules 'minizip'
-- checking for one of the modules 'libzip'
-- checking for one of the modules 'MagickWand'
-- checking for one of the modules 'epoxy'
-- checking for one of the modules 'sdl2'
-- The CXX compiler identification is GNU 4.9.2
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Platforms:
-- 	Game Boy Advance: ON
-- 	Game Boy: ON
-- Features:
-- 	CLI debugger: OFF
-- 	GDB stub: ON
-- 	Video recording: OFF
-- 	GIF recording: OFF
-- 	Screenshot/advanced savestate support: ON
-- 	ZIP support: minizip (included)
-- 	7-Zip support: ON
-- 	OpenGL support: OpenGL
-- Frontends:
-- 	Qt: ON
-- 	SDL (2): ON
-- 	Profiling: OFF
-- 	Test harness: OFF
-- 	Examples: OFF
-- Cores:
-- 	Libretro core: OFF
-- Libraries:
-- 	Static: OFF
-- 	Shared: ON
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/buildmgba
```

Interesting though that the Pi2 runs with a software renderer? Maybe I missed to install some extra driver.

**Comment by profi200** [comment]
That's normal. The RPi GPU is designed for phones and the properitary driver only supports OpenGL ES. There is a WIP GPU driver though (last i heard from it it was still very unstable and "crashy").

**Comment by endrift** [comment]
Try installing libepoxy-dev and seeing if that affects anything.

**Comment by fredericmeyer** [comment]
Installing libepoxy-dev fixed this problem. It works perfectly fine now!
