### ISSUE TITLE
Pokémon Prism crashes on mGBA

### ISSUE THREAD

**Issue by VS-R** [mgba-emu/mgba#2186]
[PokemonPrismStopsWorking.zip](https://github.com/mgba-emu/mgba/files/6488199/PokemonPrismStopsWorking.zip)
Both a friend of mine and I are having this issue that after a while the game freezes then mGBA crashes. Tried on bgb and worked just fine. 
 If this info is useful in some way I used the bug report tool right after the game froze.

**Comment by endrift** [comment]
Turn off sync to video. This is known buggy in mGBA 0.9.1. It's since been fixed (see #2138), but there hasn't been a release since.
