### ISSUE TITLE
[Windows] A small stutter when entering a pokemon center in pokemon leafgreen

### ISSUE THREAD

**Issue by brunoxberti** [mgba-emu/mgba#2187]
Dear mgba team. I've found a bug in pokemon leafgreen whenn using your emulator. Whenever i enter the main floor of a pokemon center either from the outside or the top floor of the center, the game frezes for a while and the sprites on the foreground are seem to be shaded with black. This all only last for about half a second, until it fades out, it doesn't instantly disapear it fades out. This only happens in pokemon centers and the Elite 4 entrence. It doesn't occur in the trainer tower, gyms, poke-marts or other buildings.
I've had this problem with version 0.9.0 and 0.9.1 of the emulator; I can't remember if it happened in version 0.8.4, but it defnetly didn't happened with visual boy advanced.
[Bug1pokemonleaf.zip](https://github.com/mgba-emu/mgba/files/6491038/Bug1pokemonleaf.zip)

**Comment by endrift** [comment]
I know this happens on hardware in Emerald, but I'm not sure about FRLG. I'll check.

**Comment by CasualPokePlayer** [comment]
FRLG is affected by the same thing, it's due to wireless adapter code going haywire. Only way to correctly remove the lag is to actually emulate the wireless adapter.

**Comment by endrift** [comment]
Yeah, I was able to confirm this happens on hardware, though it's hard to tell since the GBA screen has such terrible gamma.
