### ISSUE TITLE
GTA Advance won't go past BIOS

### ISSUE THREAD

**Issue by vgturtle127** [mgba-emu/mgba#219]
My computer's specifications are:

64-bit Windows 10 Pro
Intel Pentium G2030
Nvidia GTX 750 Ti
16GB of RAM

I am using mGBA version 0.4 and the latest development build.

I tried with OpenGL (force 1.x), OpenGL, and the Qt software renderer as well.

With emulated BIOS or with a BIOS file, GTA Advance will not load past the BIOS. Or if there is no BIOS, it just loads to a white screen.

The ROM works in VBA-M, Higan, and No$GBA.

Here is a savestate at the white screen:

[GTA savestate.zip](https://github.com/mgba-emu/mgba/files/121013/GTA.savestate.zip)

EDIT: Fixed broken upload

**Comment by GB-CG** [comment]
What's the checksum? Mine is `76FD030AAFCD170F04202160306F4ED7`. (It's the zip file at least)
Mine works on Wii & OSX, but I haven't tried it on Windows yet.

**Comment by vgturtle127** [comment]
@GB-CG Mine is 4FC0D236B28191036A694913AB3841C127E8B59E (Zip file as well).

I also tried decompressing the ROM, still all of the same results...

**Comment by endrift** [comment]
Zip file checksums are useless. Take the checksum of the ROM in the zip file.

**Comment by GB-CG** [comment]
My .gba rom is `2C8EF9CCE9F46B55247468EA449AEADE`, and it's working for me.

**Comment by vgturtle127** [comment]
@endrift @GB-CG Alright, I guess it must be on my end.
