### ISSUE TITLE
Audio issues

### ISSUE THREAD

**Issue by biolizardshadow** [mgba-emu/mgba#2191]
I just updated from version 0.7.3 and I noticed that Square 1 and Square 2 don't mesh together like they are supposed to. On the title screen of a rom hack I am creating square 1 and square 2 fade in from volume 0. In version 0.7.3 they fade in with no problems, but now with version 0.9.1 when both square waves fade in they make this grading sound which doesn't happen in mgba 0.7.3 or on real hardware. The beginning of the song sounds pretty rough because of this. 

The other thing I have run across is that when I change the output sample rate in the MP2K sound engine to 31536 Hz, direct sound B makes a clicking sound when I open the game , and then every time the game saves. It's not super loud but it's not super quiet either and it is very noticeable when it happens. 

It seems that I can't upload audio files here so I unfortunately can't demonstrate what I am talking about here.

**Comment by endrift** [comment]
This is almost certainly fixed in 0.10, but I don't really have any reproduction steps here to work from to tell if not.
