### ISSUE TITLE
Raw Game Fails to Load, but ELF Works

### ISSUE THREAD

**Issue by ammrat13** [mgba-emu/mgba#2192]
Running mGBA version 0.9.1 on Arch Linux from the repositories (package `mgba-qt`). CPU is AMD Ryzen 5 2600X. GPU is Nvidia GeForce GTX 1650 Super.

I'm trying to test my homebrew game on mGBA. Source, object file, ELF file, and GBA file are in [test_game.zip](https://github.com/mgba-emu/mgba/files/6511299/test_game.zip). Loading the ELF file into mGBA works fine, but loading the GBA file gives
> The game has crashed with the following error:
> Jumped to invalid address: 00000000

**Comment by endrift** [comment]
I haven't looked at the file yet but my first guess is that it's misdetecting whether or not it's multiboot. Will look in depth in a bit.

**Comment by ammrat13** [comment]
Probably. It's being loaded at `0x0200_0000` instead of `0x0800_0000`.

**Comment by ammrat13** [comment]
Resolved by making the ROM file `32MiB`. Probably works because of the check [here](https://github.com/mgba-emu/mgba/blob/e932068baa77bf944af91d6a7a31d9d3b73758ae/src/gba/gba.c#L640).

**Comment by endrift** [comment]
Yes, that check will resolve this, but I'm concerned that it's misdetecting regardless.
