### ISSUE TITLE
[Libretro] Ability to adjust Solar Sensor levels

### ISSUE THREAD

**Issue by Awakened0** [mgba-emu/mgba#22]
Currently the Libretro port lacks any way to change the solor sensor level. I think it'd be best to map the increase and decrease functions to unused RetroPad buttons. L2 and R2 or L3 and R3 would work well. That way you could change the level easily during gameplay.

**Comment by endrift** [comment]
I'm not sure about that approach, but I do want to add some way of adjusting them.

**Comment by Awakened0** [comment]
That'd be the only way to have a dedicated button and/or key for adjusting it. Some of the other cores map system functions to unused RetroPad buttons. For example, Desmume maps "blow in the mic" to L3 and the Nestopia core maps "flip disk" to L for Famicom Disk System games. Users can remap those functions using core remap or override files.

You could instead add a core option to adjust the solar level. It'd just be slightly more cumbersome, since a user would have to bring up the menu and navigate to Options, Core Options. That can all be done with a gamepad too, so it's not too bad.

You could probably implement both methods if you wanted.

**Comment by endrift** [comment]
I talked to some libretro devs about this a few hours ago and they said pretty much exactly the same thing. I'll probably do it that way, after all.

**Comment by endrift** [comment]
3a31577cab0794a929e738f02687c9fc4e40c46a adds support for the solar sensor, but there are no keybindings yet.

**Comment by endrift** [comment]
5a932631bee45043aabc0eda64858164b91c171e binds them to L3 and R3.

**Comment by Awakened0** [comment]
Got a nightly build today to try this out. It works perfectly. Thanks!
