### ISSUE TITLE
its getting annoying 

### ISSUE THREAD

**Issue by Wyrmlad** [mgba-emu/mgba#2201]
Every time I speed up the gameplay, it freezes and it will crash. It began 1-2 weeks ago and I don't know why.

**Comment by endrift** [comment]
Turn off sync to video if you have it on. This is a known bug in 0.9.1 (see #2138) which has been fixed in dev and will work in 0.9.2.

**Comment by Wyrmlad** [comment]
@endrift it was off and it still does it

**Comment by endrift** [comment]
It still does what? Still crashes in the dev builds?

**Comment by Wyrmlad** [comment]
i dont know

**Comment by Wyrmlad** [comment]
I dont recall about the dev builds tho

**Comment by endrift** [comment]
Can you give me the file generated by the bug report dialog? I don't have enough to go off of with the barest minimum of what you've given me.
