### ISSUE TITLE
[Bug] Control doesn't work in Gamera - Daikaijuu Kuuchuu Kessen 

### ISSUE THREAD

**Issue by SilverKnight-Z** [mgba-emu/mgba#2202]
There is a bug in the control of the Original Game Boy game Gamera - Daikaijuu Kuuchuu Kessen (Japan) (SGB Enhanced) that I first discovered in version 0.7.3 and it varies depending on the version. It happens with both the translated ROM and the original from No-Intro set.

- In 0.7.3 stable: Select doesn't work and I can't continue the game because in a later screen I'm asked to press it obligatory.
 
- From 0.8.0 to 0.9.1 stable: None of the keys work, or Start doesn't work (I don't know how to tell). The game starts but as it asks to press Start I can't continue. This also happens in the latest dev build 0.10-7010-a507276e2 from 05-30-2021.

I attach the generated report files for the original and the translated ROM.
[Original ROM bug report.zip](https://github.com/mgba-emu/mgba/files/6587670/Original.ROM.bug.report.zip)
[Translated ROM bug report.zip](https://github.com/mgba-emu/mgba/files/6587671/Translated.ROM.bug.report.zip)

EDIT 17/06/2021: Link for the translation patch: https://www.romhacking.net/translations/5995/

Thanks for your attention.

**Comment by CasualPokePlayer** [comment]
I did some research into this game. A simple tracelog can pull up this game's joypad routine: https://pastebin.com/raw/Pqm1md4s

An interesting thing is this game does not write $30 to joyp between the player reads! It only does it once after both players are read out. This seems to imply that the docs saying that writing $30 to joyp to increment the player count is wrong. This might be the source of the bug.

**Comment by endrift** [comment]
I'm pretty sure I tested that...

**Comment by CasualPokePlayer** [comment]
> 
> 
> I'm pretty sure I tested that...

I wrote a few testroms to test my theory (you probably saw them talked about in #research on gbdev), and my theory seems to be right. Writing $30 is unneeded to increment the joypad number. In fact, the tests seem to indicate that a simple P15 low to high will increment the joypad number.

**Comment by endrift** [comment]
I haven't checked Discord yet today, but I'm pretty sure my tests covered that. I will need to double check.

**Comment by endrift** [comment]
I see what I did wrong. I only incremented on P15 low to high if P14 was already high. It needs to work with P14 low as well.
