### ISSUE TITLE
mGBA freezes at random

### ISSUE THREAD

**Issue by crissequeira89** [mgba-emu/mgba#2203]
I’ve been trying to find out if there is any consistency to this bug, but I can’t see one. So far, I’ve experimented with the US releases of Pokémon Silver and Emerald. I have the latest release of mGBA and the latest Windows 10. The program just literally freezes and I have to force shut it down. This is the first time I have EVER had any issue with mGBA.

**Comment by endrift** [comment]
If disabling vsync fixes this, this is a duplicate of #2138.

**Comment by crissequeira89** [comment]
I’ve tried to disable vsync, but then it just runs really fast and I don’t know how to fix that. Anyway, I forgot to mention something important, which is that, if I just wait long enough (and this can be a few or a lot of minutes), the game will randomly continue to run, but then also randomly freeze at some point again.

**Comment by crissequeira89** [comment]
I’ve enabled audio sync and that keeps the game running stable without video sync turned on, so I guess that fixes the issue.
