### ISSUE TITLE
Game freeze and FPS rise to 1200

### ISSUE THREAD

**Issue by Dragerage** [mgba-emu/mgba#2206]
Hi guys, I am trying to play Pokemon Radical Red and I am getting game freezes and not responding often when either switching between normal and fast forward and when saving a game state. I have closed all other applications and have tried deleting and reinstalling the application however I keep getting the issue. Is there a setting i can try to solve it on my end? 

[Bug report mGBA.zip](https://github.com/mgba-emu/mgba/files/6602507/Bug.report.mGBA.zip)

**Comment by endrift** [comment]
Please retest on 0.9.2, which just came out.

**Comment by endrift** [comment]
Closing due to lack of reply.
