### ISSUE TITLE
Newest update broken!

### ISSUE THREAD

**Issue by 03bgood** [mgba-emu/mgba#2207]
Platform: Android (GPD XD+)
Issue: Multiple (See below)
Version:  eb3ddbe

Issue #1; In Wario Land 4, when exiting and then resuming (with "Load State Automatically" enabled under "Saving"), the sound effect that plays when collecting rubies/sapphires, is almost muted, same goes with some other sound effects as well. Loading a save state sometimes fixes this. Older versions never had this issue before. I can even prove it, by restoring a backup of an earlier version of mGBA. This issue also doesn't occur when running WL4, with the VBA-M core.

Issue #2: The rewind feature is broken when using it while running any GB/GBC game, when the game is rewinding, it pauses quite a bit and often crashes RetroArch, a lot. Basically the rewind feature doesn't function well with GB/GBC where in previous versions, it worked fine. Again, I can verify this by using a backup of an earlier version of mGBA. I use the both this feature and the fast forward feature for a lot of Pokemon games (both official and fanmade hacks) and this is where I'm encountering this problem the most.

**Comment by endrift** [comment]
Libretro downsteam issues should be filed at https://github.com/libretro/mgba/issues/, not here. Further, one issue per filed issue please.
