### ISSUE TITLE
Every time I go to a route on my ROM, it keeps crashing. I don't know why, but any help is appreciated.

### ISSUE THREAD

**Issue by Wyrmlad** [mgba-emu/mgba#2209]
I don't know why my emulator keeps crashing.
![2021-06-09 (38)](https://user-images.githubusercontent.com/85089093/121333642-d5750900-c8cd-11eb-9e5b-0dfac6fe5807.png)

**Comment by endrift** [comment]
Please attach the zip file generated from the report bug dialog.

**Comment by endrift** [comment]
Reminder that I cannot help you if you don't give me enough information. That zip file collects a bunch of information at once so I can help.

**Comment by endrift** [comment]
Closing due to lack of reply, again.
