### ISSUE TITLE
Golden Sun overworld map vibrates

### ISSUE THREAD

**Issue by CharlesCorrin** [mgba-emu/mgba#221]
Golden Sun's overworld map vibrates. I don't have the original cartridge, but it didn't do that on the Wii U Virtual Console version from what I recall. Some Youtube videos agree. I'm using OpenGL and real GBA BIOS on the latest nightly build (2a80ddf). I'm using Windows 10.

The Golden Sun is the North American/European version. CRC is e1fb68e8.

**Comment by endrift** [comment]
This is intended behavior. It vibrates every other frame, which isn't visible on e.g. the GBA display due to ghosting and 60Hz.
