### ISSUE TITLE
[3DS] Can't open menu

### ISSUE THREAD

**Issue by MallickCheese** [mgba-emu/mgba#2213]
I accidentally unbinded the open menu button and now I can't open the menu, would it be possible to create a button combination to open the menu?

**Comment by endrift** [comment]
You unbound the button, and now there's no button. You'll need to edit your config file to fix this. Asking for a button combination is, well, asking for the thing you had and then broke.

**Comment by MallickCheese** [comment]
Well I was thinking more of a three button combination that can't be unbound.

**Comment by endrift** [comment]
I think a better option would be to make it so you can't unbind it, personally.
