### ISSUE TITLE
game stuck, key stuck (movement key)

### ISSUE THREAD

**Issue by PR3D4TOR91** [mgba-emu/mgba#2217]
Hello,
I am playing Radical Red (Pokemon Firered 1.0 U version) and the character just keeps moving up, it is like the key is stuck. 
Randomly occurs, when i reloaded the rom it worked for a few moments, then its back. Now it is not working anymore at all. Stuck all the time. 
Any ideas?

**Comment by RetroEdit** [comment]
#2351 is a similar issue that may offer solutions. This sounds more likely to be a controller issue than an mGBA issue. This would be difficult to address without more info.

**Comment by endrift** [comment]
Closing due to no response. If you give me the information requested I can reopen this.
