### ISSUE TITLE
100% disk usage when opening the emulator on a fresh instalation

### ISSUE THREAD

**Issue by vini1264** [mgba-emu/mgba#2219]
I'm experiencing a weird bug when i do a new fresh installation of MGBA emulator, where when i open it for the first time it's using 100% of my hard drive. Also when i load a game for the first time and close the emulator it's still open on the task manager and i have to close it manually. The problem is gone when i close the emulator and it creates the configuration files on the folder, so i can open it again without it using 100% of the disk. This bug only happens when i delete the configuration files and do a fresh installation.

I'm using MGBA 0.9.1

**Comment by endrift** [comment]
How slow is your drive? It tries to build a database from the nointro.dat file when you first load it, but it sounds like this has confused you. You can delete the nointro.dat file if you don't want this database, but I don't think you've discovered a bug.

**Comment by vini1264** [comment]
> How slow is your drive? It tries to build a database from the nointro.dat file when you first load it, but it sounds like this has confused you. You can delete the nointro.dat file if you don't want this database, but I don't think you've discovered a bug.

Yeah i got it now, i've deleted the nointro.dat and my Hard Disk is not goint crazy anymore on the first load. For some reason this file makes my HD go to 100% of usage.
