### ISSUE TITLE
mgba hangs after a pause.

### ISSUE THREAD

**Issue by CharlesCorrin** [mgba-emu/mgba#222]
I tried to use the mgba emulator's pause function with a Golden Sun ROM loaded. After unpausing, the emulator hangs. If I disable "Sync to audio" afterward it un-hangs, but has no sound. However, going into the settings and selecting "OK" will un-hang the emulator and resume normal function.

I'm using OpenGL and real GBA BIOS on the latest nightly build (2a80ddf). I'm using Windows 10.

**Comment by endrift** [comment]
oops, I fixed this on a branch last night and didn't realize that it applied to master as well. I'll merge the change tonight.

**Comment by endrift** [comment]
Fixed in 811d654893a68882f15b04f6f3f9bfe47dea20da
