### ISSUE TITLE
[Bug] Castlevania - The Adventure for GB doesn't show GBC colors by default

### ISSUE THREAD

**Issue by SilverKnight-Z** [mgba-emu/mgba#2220]
As the title says, Castlevania - The Adventure (USA) doesn't show GBC colors by default when "use GBC colors in GB games" is checked in mGBA 0.9.1. The only way to make it show them, is changing the model from Original Game Boy to Game Boy Color in the "Game Boy" section from "Settings" menu and using the GBC boot BIOS. This behavior also happens in the ROM version: Castlevania - The Adventure (USA) (Castlevania Anniversary Collection). Both ROMs are from the No-Intro set.

My System information:
OS: Windows 7 Starter SP1 32-bit
GPU: Intel Graphics Media Accelerator 3150
RAM: 1 GB

Thanks for your attention.

**Comment by endrift** [comment]
The Game Boy Color does not have a preset for colors for that game specifically, which is what that setting is for. What you're looking for is a feature that does not exist in 0.9 (but does in dev) where you can specify GBC palettes for GB mode.
