### ISSUE TITLE
The settings' GUI is too small to display translated words

### ISSUE THREAD

**Issue by Felipefpl** [mgba-emu/mgba#2221]
the image below shows an example in "Loops inativos", there are other places in the GUI where this happens:

![Sem título](https://user-images.githubusercontent.com/5569804/122581786-cad51500-d02d-11eb-9143-c92cbcfa5aec.gif)

**Comment by endrift** [comment]
Can you see if this still happens with the latest dev build? This might have been fixed by updating the version of Qt I was using.

**Comment by Felipefpl** [comment]
Hi, i did as you suggested and the problem was solved, gonna close this now, thanks for the reply.
