### ISSUE TITLE
My gba emulator is not fast forwarding

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#2229]
Whenever I try to fast forward the audio just starts to glitch out, neither the video nor audio actually fast forward though. I haven't been able to find many sources about this so all I've really tried is messing around with the syncing to audio and syncing to video but that hasn't done anything.

**Comment by endrift** [comment]
Please upload the report file from the report bug dialog (under the file menu)

**Comment by endrift** [comment]
Closing since the user deleted their account and thus cannot actually reply...
