### ISSUE TITLE
Using Wii port on Wii U, save states often crash the game or take away audio. Mac build opens up with Korean UI.

### ISSUE THREAD

**Issue by HomeStarRunnerTron** [mgba-emu/mgba#2231]
Hi-hi!

I just learned about mGBA's Wii U gamepad compatibility and absolutely _leaped_ on getting it all set-up on my vWii. Currently, everything seems to be doing just fine. I've found that, for some reason, I can't switch the Input from "GameCube Input (1)", but, I mean, Wiimotes and Classic Controllers and Wii U Gamepads are all responding, anyway, so... guess it auto-detects, even though it just stays on "GameCube Input (1)".

The big problem right now is the save states. On the games I tried to play (Mario & Luigi: Superstar Saga, Super Mario Land 2, Space Channel 5 GBA Port), when attempting to put in a save state, then load it, it will often completely freeze the game or cause the audio to disappear completely. This happens when I boot both through the vWii Homebrew Channel or through Wii U VC inject-- and this problem arises in both the dev build and the current release. If I use mGBA on my _computer_ instead, then try to load one of my save states that I made on the _Wii_, the save state does the same thing-- it crashes the game or makes the audio disappear. HOWEVER, if I create and load a save state on my computer, none of these issues arise.

... and as another note, when I'm trying to use mGBA on my MacBook Pro 10.14.6, the UI is all in Korean. ... and I'm not sure where to change that. Interesting Times.

At any rate-- the big problem is properly creating save states on the vWii. Maybe this is only an issue that arises on the Wii U instead of a normal Wii-- unsure, since I only have a Wii U. Thank you so much for your Time, and look forward to hearing back! :  )

**Comment by endrift** [comment]
You don't switch which input you're using, you switch which input you're remapping when you do that.

The macOS issue is #1469, which I thought I'd fixed. I'll reopen the ticket.

I'll look into savestates.

**Comment by HomeStarRunnerTron** [comment]
Thank you super-much for your response! :  D

> You don't switch which input you're using, you switch which input you're remapping when you do that.

Oh! Uh... ... what button do you press after selecting the input to change the mapping? [Here's a video of me trying every possible way to activate remapping after selecting what I wanted to remap.](https://www.youtube.com/watch?v=d9CDmHHdcTE)

**Comment by endrift** [comment]
Uhh, it's supposed to be A, but I guess I broke that at some point.

**Comment by HomeStarRunnerTron** [comment]
Just as a bit of an update, I tried every stable release of the Wii port on my Wii U, and all of them can't seem to consistently create a save state and load it properly. I could never get it to load a save state at the menu screen of Mario & Luigi: Superstar Saga without the music just disappearing. I don't have a normal Wii to test if it works fine on there, but perhaps that might contribute? All the very best, thank you for all your hard work and your considerate responses to everybody here!

**Comment by Maesejesus** [comment]
Hi, I have tried on my original Wii, and I can confirm that the, at least last nightly version, does have issues with the save states. I haven't got them crash the emulator, but you lose sound when loading a save state (even if it's made a few seconds before, not loading a save state created on an older version). 

I've been trying on some of my older versions of mGBA for the Wii, and the most recent one I have (and the one I've been using until right now) is a boot.dol made the 19th of April of 2021, in that one save states works well and there's no audio loss, and obviously no crashing (although that might be a Wii U problem? Who knows), so it might have happened after that. 

Just wanted to help a bit, I hope it does.  Thank you for your work as always, Endrift.

**Comment by endrift** [comment]
That's definitely useful info, I'll take a look at that today since I want to get that fixed before 0.9.2

**Comment by HomeStarRunnerTron** [comment]
> I've been trying on some of my older versions of mGBA for the Wii, and the most recent one I have (and the one I've been using until right now) is a boot.dol made the 19th of April of 2021, in that one save states works well and there's no audio loss, and obviously no crashing (although that might be a Wii U problem? Who knows), so it might have happened after that.

Hehe, is there any chance you could help me find this April 19th build? I've looking around the buildbot and can't seem to figure out how to get a specific older DOL. Then I could see if it fixes my problem in the games specified. :  )

**Comment by endrift** [comment]
This page may be useful: https://mgba.io/builds/6/

**Comment by endrift** [comment]
The savestate audio and input remapping bugs are fixed now (thanks for finding them!), but I haven't tried vWii savestates yet. Are you running from the HBC or via an injected channel?

**Comment by HomeStarRunnerTron** [comment]
> The savestate audio and input remapping bugs are fixed now (thanks for finding them!), but I haven't tried vWii savestates yet. Are you running from the HBC or via an injected channel?

HOORAY! I JUST tried out revision 6952-3a8975d, 6953-84d8c37 and 6954-2973211, and they all worked perfectly, with both bugs dropped! It was through an injected channel, but to test, I just used my injected HBC, and I can say it works perfectly using the Wii U Gamepad. Lemme test the newest daily build and see what's up...

**Comment by HomeStarRunnerTron** [comment]
SUCCESS! The brand-new daily build works poi'fectly with the Wii U Gamepad, input modification and save states and all! So excited to finally play Mario & Luigi with the proper timing on the hits, hahaha.

**Comment by endrift** [comment]
So no more crashing either? If not, please close this. The Mac build issue is tracked by another issue, as I linked earlier.

**Comment by HomeStarRunnerTron** [comment]
Abso-tootly, apologies for not closing it the first time, I was just really excited to let you know! ^_^

**Comment by Maesejesus** [comment]
Fantastic, thanks for fixing it so quickly! 
I'm glad that I keep some older builds just in case whenever I update.
