### ISSUE TITLE
Unable to edit saves in Fire Red

### ISSUE THREAD

**Issue by SirPigeon** [mgba-emu/mgba#2233]
Was trying to do a trade evolution via editing my saves but when I replace the save in the roms folder and boot the game it still uses the save from before I edited the save. I'm on switch if it helps

**Comment by endrift** [comment]
Are you sure you overwrote the right file? This sounds like a tech support question, not a bug, and this isn't a tech support forum.

**Comment by endrift** [comment]
Closing due to lack of reply.
