### ISSUE TITLE
Crashing while want to save state

### ISSUE THREAD

**Issue by eldrzej1** [mgba-emu/mgba#2239]
When i want to save pokemon leaf green its crashing out. version 0.9.1

**Comment by Sabelohaha** [comment]
I'm having the same issue and its really annoying, I have to save every five minutes unless i want to lose a lot of progress. Same version

**Comment by endrift** [comment]
Please retest in 0.9.2.

**Comment by endrift** [comment]
Closing due to lack of reply.
