### ISSUE TITLE
[Wii] 'Exception (DSI) occurred!'

### ISSUE THREAD

**Issue by GB-CG** [mgba-emu/mgba#224]
<img width="655" alt="screen shot 2016-02-14 at 22 58 54" src="https://cloud.githubusercontent.com/assets/11931125/13037036/01ddb69a-d36f-11e5-9d85-0646ba2a336b.png"> Happens every time when I launch it. This is on 0.5-3326.

**Comment by endrift** [comment]
This was fixed in the meantime.
