### ISSUE TITLE
Mgba 0.9.1 OpenGL fast forward not working

### ISSUE THREAD

**Issue by tomdog86** [mgba-emu/mgba#2241]
I'm playing Mega Man Battle Network 3 when I switch to OpenGL. Now fast-forwarding doesn't work and rewinding leaves behind glitch after effects.
[error report.zip](https://github.com/mgba-emu/mgba/files/6796103/error.report.zip)

**Comment by endrift** [comment]
This is a duplicate of a bunch of other bug reports that can easily be found by searching.

**Comment by tomdog86** [comment]
what's the issue no. that can fix the problem?

**Comment by endrift** [comment]
Use a development build until 0.9.2 comes out (hopefully soon)
