### ISSUE TITLE
Huge framedrop on GBA emulation when its BIOS is loaded

### ISSUE THREAD

**Issue by hikagura99** [mgba-emu/mgba#2243]
As the title states, whenever the BIOS is loaded mgba's emulation slows down, and by a lot(5 FPS circa). Another glitch is in the BIOS screen: visually goes in a smooth 60fps but the audio starts screeching and trembling. 
[Here's a video](https://drive.google.com/file/d/1hd87qS6bIqmO5zHqbb93ePEBrrOUldcY/view?usp=sharing)

In the video there's another issue. The settings page occupies all the screen height, which can give some problems on DE's such as KDE or xfce, so a resizing option would be much appreciated.

My specs are:
OS: Artix Linux
Kernel: Linux 5.12.14-artix1-1
DE: Plasma 5.22.3
CPU: Intel i5 7200u
GPU: Intel HD Graphics 620 and AMD Radeon R5 M330
mgba version: https://github.com/mgba-emu/mgba/releases/tag/0.9.2, compiled from github

**Comment by endrift** [comment]
Are you still having this issue? I need a bug report zip to do anything at all with this, but I suspect you have something weird in your settings.
