### ISSUE TITLE
Graphical glitches in Famicom Mini 01 - Super Mario Bros. (Japan) (En) (Rev 1)

### ISSUE THREAD

**Issue by Hector-Eli-Wood** [mgba-emu/mgba#2244]
Tested with the latest development version of mGBA. Happens with both software and OpenGL. Looks like everything except Mario is flickering and distorting.

[mario glitch.zip](https://github.com/mgba-emu/mgba/files/6798294/mario.glitch.zip)

**Comment by endrift** [comment]
Not a bug. The NES has 224 scanlines but the GBA only has 160, so it's flickering to make it look more detailed. Turn on interframe blending.
