### ISSUE TITLE
1,400+ fps for Mother 3

### ISSUE THREAD

**Issue by Shepardmint** [mgba-emu/mgba#2246]
Hello, I'm playing the Mother 3 Fan Translation and every time I load it up, it would go at 1,400 fps. What do I do to slow it down? I'm using v.9.2 of mgba too. Thanks.

**Comment by endrift** [comment]
Turn on sync to audio.

**Comment by Shepardmint** [comment]
Thank you so much.

**Comment by Testsr** [comment]
@Shepardmint, since your question has been answered, could you close the issue?

**Comment by endrift** [comment]
I thought I closed this already.
