### ISSUE TITLE
Character and menu movement in Pokemon Red Fire stuck

### ISSUE THREAD

**Issue by dannEEsc** [mgba-emu/mgba#2247]
Hello.

Playing Pokemon Red Fire (spanish versión), trying to level up a pokemon on Pokémon Day Care of Cerulean City, keeping the character movement and fast forward against a wall. After about an hour, the image froze, and scared to lose the advance, i made a quick save. 

I restart mGBA, start the game and and the character just keeps moving down, it is like the key is stuck.

Please help.

Annexed archive bug game report: 
[Reporte- problemas con los controles direccionales.zip](https://github.com/mgba-emu/mgba/files/6834970/Reporte-.problemas.con.los.controles.direccionales.zip)

**Comment by dannEEsc** [comment]
I can solve the problem uninstalling and reinstalling mGBA. (I take chance for update to v 0.9.2, i don't know if this may be relevant.

**Comment by endrift** [comment]
This was probably fixed in 0.9.2, as there were several freezing bugs in it that have since been fixed.
