### ISSUE TITLE
hamtaro ham ham heartbreak game locksup.

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#2248]
When playing hamtaro ham ham heartbreak the game will lock up but the music still plays. Start a new game click on ok you will see a circle but it never closes to advance other emulators the game works fine. Windows 10 RetroArch 1.9.6 mGBA( ca21f86)

**Comment by endrift** [comment]
Duplicate of #2131. Please search next time.

**Comment by Cibomatto2002** [comment]
sorry about that
