### ISSUE TITLE
Application freezes on save state after long playtime; Lost save data 

### ISSUE THREAD

**Issue by dislikers** [mgba-emu/mgba#2252]
Hello,

I am playing Pokemon Red on mGBA version 0.9.2 on Windows 10 64-bit. My CPU is AMD FX-4300. My GPU is Geforce GTX 960. I have 16 GB of RAM. Before I continue, please let me know if I am missing details or if I am doing something wrong as it is my first time using Github. I'll try to explain this in a simple way in a Q&A format.

**What happened?**
Same as title. I would play a few hours of this game without issue. However, toward the end of my gameplay, I would try to save to a save state. mGBA would freeze, and it would show as not responding. I lost an hour of gameplay the first time, no save data was lost the second time (I will explain later), and around 3 hours of gameplay the third.

**How can we reproduce this issue?**
1. Open mGBA and load Pokemon Red.
2. Start a new game. You don't have to press anything after you press "New Game."
3. Wait 1-3 hours. 
4. Attempt to save using a save state.
5. The screen should turn white, mGBA will show as not responding, and the save state will not be saved.

I tested this just now and it froze as expected.

**How did you attempt to resolve it?**
The first time I resolved it by simply playing through again. The second time, I waited a good 30 minutes for the game to start responding again. It did not. I opened another instance of mGBA. I closed out of the frozen mGBA instance. I loaded up Pokemon Red into the new instance. Surprisingly, the data was not lost and I was able to go back from where I started. The third time, I attempted to do the same but it did not work. My save data was lost and so I came onto Github to report it.

**Anything else?**
I'm not sure what causes this issue. I believe it may be due to a memory issue. However, according to Task Manager, my memory is not being clogged up. I will attach my bug report but I don't believe it will have much useful information.

[b.zip](https://github.com/mgba-emu/mgba/files/6859115/b.zip)

I will also attach my save state files and the ROM itself if that is necessary.

[Saves.zip](https://github.com/mgba-emu/mgba/files/6859123/Saves.zip)

**Comment by endrift** [comment]
Please try using a development build. There was an issue with this that I discovered that should be fixed in development builds already.

**Comment by dislikers** [comment]
Sorry for the late reply, but this seemed to be fixed in the development build as you said. I just tested it myself and it works. Thanks.

On a side note, is it possible to recover that lost save state? I lost a lot of progress and I don't feel like trying to play through those sections again.

**Comment by endrift** [comment]
If you saved in-game you may be able to use the save converter to extract it. Otherwise it's unlikely.
