### ISSUE TITLE
Game stuck on x10 speed 

### ISSUE THREAD

**Issue by Dcbafge** [mgba-emu/mgba#2254]
when im playing i put the fast forward speed to x10 but then when i tried to change the fast forward speed back to 2x it won't change and even when i turn off the fast forward or uninstall and reinstall the emulator it's still stuck on x10 speed

**Comment by endrift** [comment]
Make sure you have sync to audio enabled, otherwise it has nothing to tell it to run slower than "as fast as possible".

**Comment by endrift** [comment]
Please confirm if that fixed it.
