### ISSUE TITLE
Controller mapping is a mess with Dualshock 4

### ISSUE THREAD

**Issue by lorywindrunner** [mgba-emu/mgba#226]
Using a regular Dualshock 4 mapping buttons only works for some buttons.

Cannot map Dpad at all (but still works in game?) The analog stick only works with some buttons.

**Comment by lorywindrunner** [comment]
Got it to work but it is was very messy

**Comment by lorywindrunner** [comment]
Well it was working but when i restart the program buttons are being remapped automatically.

**Comment by endrift** [comment]
I added a preset for the DualShock 4, it should help with some things. However, the controller mapping is just outright confusing and this has been a known issue for as long as it's been present, and needs to be revamped.

**Comment by endrift** [comment]
A lot of this was fixed today. The D-pad not remapping is due to how they show up to mGBA; it's basically hard-mapped at the moment and it hasn't been customizable in any version of mGBA. That bug is being tracked by https://endrift.com/mgba/bugs/show_bug.cgi?id=144

**Comment by endrift** [comment]
This should all be fixed now, although the revamp hasn't really been done yet. Hats specifically are now remappable.
