### ISSUE TITLE
OpenGL Enhancement Renderer fails if all layers are off.

### ISSUE THREAD

**Issue by Lokathor** [mgba-emu/mgba#2260]
Test Rom: [demo.zip](https://github.com/mgba-emu/mgba/files/6889582/demo.zip)

This starts up, turns off the Forced Blank bit, and then write pink to the backdrop color palette slot.

This should make pink appear on the whole screen.

However, if the OpenGL display driver is used and the OpenGL enhancement renderer is selected, then the screen ends up all white instead, as if the forced blank bit was still on.

**Comment by endrift** [comment]
This seems to work fine...if the BIOS intro plays. Otherwise I'm able to reproduce as described.
