### ISSUE TITLE
Trying to trade pokemon Gen 3 and wont work

### ISSUE THREAD

**Issue by Rancor20** [mgba-emu/mgba#2263]
I have tried many ways to try and trade pokemon in gen 3 but to no eval. People say just unselect "pause while inactive", but i cant find it anywhere

**Comment by endrift** [comment]
Pause while inactive is in settings, under interface.

I can't help you unless you give me a better description of what's failing. But also this is for reporting bugs, not general tech support.

**Comment by Rancor20** [comment]
My apologize, I've looked in settings. Is there a specific section of
settings that it's at?

**Comment by endrift** [comment]
...yes, interface, which I said already.

**Comment by Rancor20** [comment]
Got it, guess I'll have to figure out a different was because the two games
still won't connect in multiplayer
