### ISSUE TITLE
Create loader for custom Vita bubbles

### ISSUE THREAD

**Issue by DRok17** [mgba-emu/mgba#2267]
Can you create a loader for adding custom bubbles to the live area? RetroArch, DaedalusX64, FAKE-08 and ScummVM all have this. It would be great for people who want to use mGBA natively rather than using the RetroArch core.

**Comment by endrift** [comment]
Related to #713, though likely easier to implement.

**Comment by endrift** [comment]
I have something almost working for this. Mostly just need to implement the UI for creating the bubbles, and afterwards I can do #713 too.
