### ISSUE TITLE
Crash issue on Vita

### ISSUE THREAD

**Issue by zenuno-on-vita** [mgba-emu/mgba#2268]
After a few seconds of booting up most roms, the whole app would crash. One way I found around the issue was to disable auto save. I believe that enabling it again after that did not make the glitch happen again. Weird, this went on for months with every version I tried until I found someone online with the same issue that recommended I disable autosave

**Comment by endrift** [comment]
Does it depend on where the ROMs are located? Also are you in safe mode in henkaku?

**Comment by zenuno-on-vita** [comment]
It doesn’t matter where the rom is since they’re all in the same location. Also yes, every single other homebrew works and I also just checked

**Comment by zenuno-on-vita** [comment]
ALSO now it won’t save at all, like I save and try to load and it just doesn’t… I just lost hours of gameplay without knowing xd

**Comment by endrift** [comment]
You....didn't actually answer either question. If you put the ROMs somewhere else, like ux0:/data, does it work? And are you in safe mode in henkaku?

**Comment by endrift** [comment]
I am unable to reproduce this on my Vita, and I still haven't gotten the info I requested. Please also upload your config.ini (in ux0:/data/mGBA)
