### ISSUE TITLE
Paths support broken

### ISSUE THREAD

**Issue by CharlesCorrin** [mgba-emu/mgba#227]
Paths support is broken in the latest Windows build (5c2dbc5). It acts as if you've told it "Same directory as the ROM" when you have a path loaded. This is on Windows 10.

EDIT: Tried it in new latest Windows build 58c09c9. It is broken there as well.

**Comment by endrift** [comment]
Regression in 0.5-pre. Will have a fix tonight.

**Comment by endrift** [comment]
Fixed in d232a538cc74fac4846ef3aa790eced33b61c919.

**Comment by DarkD** [comment]
Broken in mGBA 0.6-4020. Same behaviour as stated by CharlesCorrin. Win7 x64.

**Comment by endrift** [comment]
I'm not having any problems with paths support on my end. Can you post your config.ini? It should be in %APPDATA%\mGBA\

**Comment by DarkD** [comment]
`[input.QT_K]
keyL=83
keyR=67
keyStart=16777220
keyDown=16777237
keyLeft=16777234
keyB=65
keyUp=16777235
keyA=90
keyRight=16777236
keySelect=81

[ports.qt]
width=960
audioBuffers=2048
lockAspectRatio=1
useBios=1
volume=256
rewindBufferInterval=0
fastForwardRatio=-1
savestatePath=d:\Games\GBA\mGBA\States\
screenshotPath=d:\Games\GBA\mGBA\Screenshots\
mru.0=D:/Games/GBA/ROMs/1141 - Final Fantasy Tactics Advance (UA).gba
sampleRate=48000
mute=0
rewindBufferCapacity=0
allowOpposingDirections=0
suspendScreensaver=1
idleOptimization=remove
savegamePath=d:\Games\GBA\mGBA\Saves\
patchPath=d:\Games\GBA\mGBA\Patches\
fpsTarget=60
audioSync=1
bios=
frameskip=0
skipBios=0
rewindEnable=0
loadStateExtdata=1
videoSync=0
pauseOnFocusLost=0
height=640
resampleVideo=0
mru.1=D:/Games/GBA/ROMs/Iridion II (USA).gba
fullscreen=0
saveStateExtdata=7

[input-profile.]
keyL=10
keyR=11
axisUpAxis=-1
keyStart=3
keyDown=6
keyLeft=7
axisLeftAxis=-0
keyB=14
keyUp=4
axisRightValue=16384
axisRightAxis=+0
axisUpValue=-16384
axisDownAxis=+1
axisDownValue=16384
keyA=13
keyRight=5
axisLeftValue=-16384
keySelect=0

[gba.input-profile.]
keyR=-1
keyL=-1
axisUpAxis=-1
keyStart=-1
keyLeft=-1
keyDown=-1
axisLeftAxis=-0
keyB=-1
keyUp=-1
axisRightValue=12288
axisRightAxis=+0
axisUpValue=-12288
axisDownAxis=+1
axisDownValue=12288
keyA=-1
keyRight=-1
axisLeftValue=-12288
keySelect=-1

[gba.input.SDLB]
keyR=-1
keyL=-1
axisUpAxis=-1
keyStart=-1
keyLeft=-1
keyDown=-1
axisLeftAxis=-0
keyB=-1
keyUp=-1
axisRightValue=12288
axisRightAxis=+0
axisUpValue=-12288
axisDownAxis=+1
axisDownValue=12288
keyA=-1
keyRight=-1
device0=
axisLeftValue=-12288
keySelect=-1

[gba.input.QT_K]
keyR=67
keyL=83
keyStart=16777220
keyLeft=16777234
keyDown=16777237
keyB=65
keyUp=16777235
keyA=90
keyRight=16777236
keySelect=81

[input.SDLB]
keyL=10
keyR=11
axisUpAxis=-1
keyStart=3
keyDown=6
keyLeft=7
axisLeftAxis=-0
keyB=14
keyUp=4
axisRightValue=16384
axisRightAxis=+0
axisUpValue=-16384
axisDownAxis=+1
axisDownValue=16384
keyA=13
keyRight=5
axisLeftValue=-16384
keySelect=0
 `

**Comment by DarkD** [comment]
So yeah, don't reopen this issue. If possible please add autocreation of needed folders if they doesn't exist. (and I wish settings was in same folder as emulator for portable use...)

**Comment by endrift** [comment]
There's an option in the file menu to make the emulator portable: it makes a file called portable.ini and copies the config file to the local directory.

**Comment by DarkD** [comment]
Oh, I see, thanks! I'm getting used to mGBA right now, want to completely replace VBA with it as it's good, but showing it's age and not maintained anymore. VBA-M would be natural choice, but no, it's actually worse then old VBA, was checking it for some time, bad audio, memory leaks, general drop of performance, nu-uh, not a good replacement. On the other hand mGBA is great, like a healing balm to sore wound - great performance, compatibility, customization to tune everything to my taste and not readapt after VBA to different scheme of controls/shortcuts. Also ability to say "I have an issue, help me there!" and receive help or fix means a lot!
Thanks for making THE definitive GBA emulator, you're great!
