### ISSUE TITLE
Can't play ROM games on windows 10

### ISSUE THREAD

**Issue by Dogshitluck23** [mgba-emu/mgba#2271]
![Screenshot (9)](https://user-images.githubusercontent.com/88615255/128629165-a7a79a96-bf0d-47a0-a887-fe70a120f224.png)
I downloaded the emulator using the site but when I tried to play pokemon emerald it keeps crashing and doesn't start

**Comment by Dogshitluck23** [comment]
[Pokemon - Emerald Version (U) (1).zip](https://github.com/mgba-emu/mgba/files/6950562/Pokemon.-.Emerald.Version.U.1.zip)

**Comment by endrift** [comment]
Don't post ROMs. Please include the zip file generated by the Report Bug dialog under the file menu. And by crash do you mean hang or freeze?

**Comment by Dogshitluck23** [comment]
Like when i try to play, it instantly closes the window

**Comment by Dogshitluck23** [comment]
like it causes it force quit or smth
[bugreport.zip](https://github.com/mgba-emu/mgba/files/6950737/bugreport.zip)

**Comment by Dogshitluck23** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/88615255/128633346-00a768f5-3a24-4969-9285-c102b257cf49.png)

**Comment by endrift** [comment]
You do not appear to have GPU drivers installed. Please install them: https://www.intel.com/content/www/us/en/download/19344/30579/intel-graphics-windows-dch-drivers.html

**Comment by Dogshitluck23** [comment]
Ohh ok Thanks
