### ISSUE TITLE
Pokemon radical red 2.3a freezing druing evolving 

### ISSUE THREAD

**Issue by JITQ0N17** [mgba-emu/mgba#2272]
I have tried three different pokemons from three different locations to see if it would not freeze but at the end of evolving it would freeze. If I do not let them evolve the game would coninue as normal. I am using vba 2.1.4.
At the start of playing Pokemon radical red the game was running fine but after 3 days the game started to be going from 500 to 1000 percent in few seconds and changing speedup and turbo settings did not fix the problem but that is not the real problem since the game is playable. 
![Uploading Screenshot (18).png…]()

**Comment by endrift** [comment]
Are you saying it's freezing in VBA? Or that it works in VBA but not mGBA? Also your picture failed to upload.

**Comment by JITQ0N17** [comment]
Yes, it would freeze un VBA and sorry my internet is slow so I would try to upload it again
![Screenshot (18)](https://user-images.githubusercontent.com/88632944/128645835-b39d8399-92fb-4e34-8336-fd7773fa1b9b.png)

**Comment by endrift** [comment]
This is not the VBA bug tracker, nor the Pokémon Radical Red bug tracker. This is the mGBA bug tracker.

**Comment by JITQ0N17** [comment]
So is there anyway that it could be fixed? I can play the game but if I try to evolve a pokemon it would freeze during the process.

**Comment by endrift** [comment]
You are asking the wrong people. I don't know since I'm not involved with either project.

**Comment by epman100** [comment]
> 
> 
> So is there anyway that it could be fixed? I can play the game but if I try to evolve a pokemon it would freeze during the process.

you need to post the problem either [here](https://www.pokecommunity.com/showthread.php?t=437688) or [here](https://github.com/visualboyadvance-m/visualboyadvance-m/issues)
