### ISSUE TITLE
[Wii] Unable to open rom from "front-end"

### ISSUE THREAD

**Issue by askotx** [mgba-emu/mgba#2273]
I like to use Wiiflow to launch roms , but I get a half-flashing screen after launching a rom:
![20210808_165839](https://user-images.githubusercontent.com/2125887/128649709-0f38fa72-140d-42ed-b66b-72f3314f0087.jpg)

This is my plugin ini file:

```
[PLUGIN]
magic=56425894
covercolor=01a300
coverfolder=gba
filetypes=.gba
romdir=roms/handheld/gba
dolfile=emulators/mgba.dol
bannersound=sounds/GBA.ogg
displayname=Nintendo Game Boy Advance
consolecoverid=nintendo
arguments={device}:/{path}/{name}
``` 

mGBA version: 0.9.2 (2,155 KB)

Am I missing something? I don't know if mgba emu is loading properly config file like Switch is. Maybe I'm wrong.

**Comment by endrift** [comment]
I have never used Wiiflow so I have no idea what this even does. It may be an mGBA bug but it's hard to tell without knowledge of Wiiflow.

**Comment by askotx** [comment]
Does mGBA accept arguments like rompath, filename or both?

**Comment by endrift** [comment]
Just pass it a filename yeah. No --flags or anything.

**Comment by askotx** [comment]
I can launch mGBA from Homebrew Channel correctly and if I use another launcher WiiXplorer it works well too. And I even launch thourgh arguments from meta.xml.
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<app version="1">
	<name>mGBA</name>
	<coder>Jeffrey Pfau (endrift)</coder>
	<version>0.9.2</version>
	<short_description>mGBA Game Boy Advance emulator</short_description>
        <arguments>
          <arg>usb:/roms/handheld/gba/AdvanceW.gba</arg>
       </arguments>
</app>
```   
I'm starting to think it's on my end,  because it worked too, I'm going to close it. Anyways thanks for looking at it, I think it's wiiflow related and ... on my lack of searching well. 
Again, thanks!

**Comment by askotx** [comment]
I found something, Wiiflow sends `usb1:/` and mGBA expects: `usb:/`

Even if I set on plugin file from this: `arguments={device}:/{path}/{name}` to this: `arguments=usb:/{path}/{name}` I don't know why it's not working and crashing, maybe it's something related to wiiflow sending params.

But also I tested this and worked: `<arg>usb:/roms/handheld/gba/AdvanceW.gba</arg>` but if I use this: `<arg>usb1:/roms/handheld/gba/Advance Wars.gba</arg>` it throws a message saying "Load Failed!" and it goes back to HB channel.

**Comment by endrift** [comment]
I don't think that's an mGBA bug. `usb1:` afaik doesn't correlate with anything according to almost all Wii software, so I'm unsure why wiiflow is even sending it.
