### ISSUE TITLE
RTC issues with Pokémon Emerald on mGBA v0.10-7085 (Pop!_OS 21.04)

### ISSUE THREAD

**Issue by LOuroboros** [mgba-emu/mgba#2276]
Title.
I downloaded mGBA's packages for "Ubuntu (64-bit, 21.04)" from the Development Downloads section of its website, installed libmgba.deb and mgba-qt.deb, and when I opened a clean ROM of Pokémon Emerald *(sha1: `f3ae088181bf583e55daf962a92bb46f4f1d07b7`)* on mGBA, I got the usual "*The internal battery has run dry.*" error that signals an issue with the Real-Time Clock functionality.

![Screenshot from 2021-08-12 03-53-55](https://user-images.githubusercontent.com/4485172/129151411-ca32914a-017f-498e-a5d9-fdd6602bfbb3.png)

I didn't touch the Game Overrides at all, the only things that I changed were the key shortcuts, set mGBA to detect and remove idle loops, preload the ROM in memory, and set mGBA to pause whenever the window is in the background.

I'm not sure if the problem stems from the OS or mGBA, which is why I'm opening this issue post.
Funnily enough, if I boot up a ROM Hacking project of mine with a clock added to the start menu on a Windows version of mGBA through Wine, the RTC works normally.
![Screenshot from 2021-08-12 03-59-26](https://user-images.githubusercontent.com/4485172/129152094-f6406ba4-e5e1-4912-8492-97ac9780d371.png)

**Comment by LOuroboros** [comment]
> I've been unable to reproduce this issue on Windows 10.

I didn't have this problem on Windows 10 either, to clarify. I'm only experiencing it right now that I'm using Pop_OS! specifically.

> Check if the ROM is on a non-restricted directory

It is.

> also check on wine with the clean ROM to check if the bug still happens.

It does.

> If the .sav file is corrupted, it's gonna generate this message anyway. So I recommend deleting it and trying a new one.

It's a clean savefile.

**Comment by endrift** [comment]
I've never seen anything like this on Linux before, but I haven't used Ubuntu 21.04 or Pop!_OS at all. I can try setting up a VM or something maybe.

**Comment by Jaffacakelover** [comment]
I was testing `Music Recorder MP3 (Japan)` and had a similar issue. MGBA 0.9.2, Windows 10.
Upon startup, after the developer logo it gives a message in Japanese, which translates roughly to "Cartridge battery, please exchange".
![Music Recorder MP3 (Japan)-0](https://user-images.githubusercontent.com/3490850/134732416-0c8bf5f1-d4b2-48bc-a157-627e11c3fe6e.png)
Forcing realtime clock on in Game Overrides didn't work.

**Comment by endrift** [comment]
That's probably un-emulated cartridge hardware, not the RTC.
