### ISSUE TITLE
use Game_Music_Emu for GB audio

### ISSUE THREAD

**Issue by djmaximum17** [mgba-emu/mgba#2277]
personally I prefer Game_Music_Emu over mGBA's own emulation core, which I don't know how I can explain how terrible the current emulation sounds, so it should be changed in next release just so I don't have to rely on VBA-M anymore. https://github.com/kode54/Game_Music_Emu/tree/master/gme

**Comment by endrift** [comment]
There are many, many reasons this isn't going to happen.
