### ISSUE TITLE
[GAME ERROR] GBA Memory:	Bad memory Store32: 0x00005F90

### ISSUE THREAD

**Issue by GRINCH0212** [mgba-emu/mgba#2278]
i have no idea what this means but even after deleting and reinstaling it still wont let me play fan rom hacks or official so please help me understand it

**Comment by endrift** [comment]
That looks unrelated to the actual problem at hand. You need to tell me what games and hacks you're trying to play and what happens from your perspective, not the logs.

**Comment by endrift** [comment]
Closing due to lack of info
