### ISSUE TITLE
Gameboy color cheat codes crash Retroarch

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#2281]
Gameboy Advance game cheats work but not Gameboy color I don't have cheats to try on Gameboy to see if they will work. When trying to use a cheat Retroarch will exit. this is on all Gameboy color games. Core is updated.

Windows 10

**Comment by endrift** [comment]
This is the same as https://github.com/libretro/mgba/issues/235, which I keep forgetting to look into.

**Comment by Cibomatto2002** [comment]
Thank you so much for fixing it.

**Comment by Cibomatto2002** [comment]
it's been 4 days and I just updated mgba on the 19 bug is still there.
