### ISSUE TITLE
[Feature Request -3DS] Option of custom frames/borders in pixel perfect mode

### ISSUE THREAD

**Issue by IvandersonBordin** [mgba-emu/mgba#2282]
In mGBA for 3DS, it would be very nice and beautiful if you had the option to put an image/frame around the edges, or as a background when using the screen in reduced mode/pixel perfect in GBA games, just like I've seen in GBA games. GB and GBC.

**Comment by IvandersonBordin** [comment]
In mGBA for 3DS, it would be very nice and beautiful if you had the option to put an image/frame around the edges, or as a background when using the screen in reduced mode/pixel perfect in GBA games, just like I've seen in GBA games. GB and GBC.

**Comment by endrift** [comment]
I'm planning to do this as part of #1124. Closing as a duplicate.
