### ISSUE TITLE
The bug is back :(

### ISSUE THREAD

**Issue by TigreRoxo** [mgba-emu/mgba#2285]
[openGL + sinc to video.zip](https://github.com/mgba-emu/mgba/files/7025594/openGL.%2B.sinc.to.video.zip)
Hi, a few months ago I reported this bug in version 0.9.1, and it was solved in a beta release (#2138), but it came back in the new stable version. I know I can just turn off sinc to video, but I though in reporting here just in case.

**Comment by endrift** [comment]
It's not back so much as one of the fixes didn't get merged into 0.9.2 by mistake. It should still be fixed in the dev builds, and it's been merged into the forthcoming 0.9.3. Please try on a dev build to confirm though.

**Comment by TigreRoxo** [comment]
You are absolutely right the dev version is working fine. Thanks!
