### ISSUE TITLE
Bug while trading Pokémon 

### ISSUE THREAD

**Issue by Vookie93** [mgba-emu/mgba#2290]
I experience a bug where I can’t trade Pokémon between Pokémon red and blue. I get to the screen where I can choose between colloseum and trade and then the controls freezes and I can’t do anything. 
anyone got a fix for this? 
I have randomized the Roms to allow evolution without trading, don’t know if that does it?

**Comment by RunisDauphin** [comment]
As far as I know, only BGB (and maybe SameBoy) can do that for now. And maybe VBA-Link. I have only tried GBA connectivity.

**Comment by RunisDauphin** [comment]
And maybe the memory directions of your randomised cartridges are conflicting with the colosseum.
