### ISSUE TITLE
A gameshark code that works on VBA-M (SVN r878) doesn't work on mGBA

### ISSUE THREAD

**Issue by LOuroboros** [mgba-emu/mgba#2297]
Title.
I need to use a gameshark code to generate shiny Pokémon in a ROM Hack of Pokémon Emerald to check out something, and while the code works normally on my preferred version of VBA-M, it doesn't work on mGBA.
It's worth to note that this is also happening with a clean ROM of Pokémon Emerald, the same ROM that can be generated by building [Pokeemerald](https://github.com/pret/pokeemerald/).
![explorer_768](https://user-images.githubusercontent.com/4485172/131762083-a384ba44-98cc-4aa4-aa21-8afa6fe8a8d1.png)
![explorer_769](https://user-images.githubusercontent.com/4485172/131762091-bfef3950-dafa-4d02-8bcc-7e3dbd6f8edd.png)
![explorer_770](https://user-images.githubusercontent.com/4485172/131762587-4eca99b8-a8fd-40b4-82f5-ccf602117a1a.png)
![explorer_771](https://user-images.githubusercontent.com/4485172/131762590-31836f07-7f01-4f1e-9c67-36aaf3aba98a.png)

I thought it was worth bringing up in case it's something that can or should be fixed on mGBA's end.
Perhaps I'm just adding the code incorrectly? I wouldn't rule it out since I can be tremendously dumb at times.

The gameshark code being used: `F3A9A86D 4E2629B4 18452A7D DDE55BCC`
And just in case it's relevant, the ROM Hack is called "Pokémon Shadow Specter".
**EDIT**: Oh yes, and after introducing the code I reset the game by going to File -> Recent too, not sure if it was needed or not.

**Comment by endrift** [comment]
You need to split it into two lines. The fact that it even lets you put it in as one long line is...a bug.

**Comment by LOuroboros** [comment]
> 
> 
> You need to split it into two lines. The fact that it even lets you put it in as one long line is...a bug.

Since it's 2 lines of 16 characters each without counting blank spaces, couldn't mGBA handle it automatically?

Less troubles for the user :eyes:

Thanks for the clarification though.

**Comment by endrift** [comment]
Yes, that's why I called it a bug and not user error.

**Comment by RunisDauphin** [comment]
What year was released VBA-M r878? I think VBA-M 2.0.0 Beta 2 was released in 2015.

**Comment by LOuroboros** [comment]
> 
> 
> What year was released VBA-M r878? I think VBA-M 2.0.0 Beta 2 was released in 2015.

June 17, 2009 or somewhere around that.

**Comment by endrift** [comment]
Please keep it on topic.
