### ISSUE TITLE
Lag in Mega Man Zero (USA, Europe)

### ISSUE THREAD

**Issue by SilverKnight-Z** [mgba-emu/mgba#2298]
Hello, this time I report lag in Mega Man Zero (USA, Europe) for the Game Boy Advance. I noticed it when I first played it using mGBA version 0.9.2; then I decided to try with version 0.7.3 and it turns out that the game runs flawlessly. After this, I did more tests to determine since when the lag appears.

To do this, I ran the same ROM with the same save file and played the same stage in different versions of mGBA.

Evaluating the FPS at which the game ran along with the gameplay feeling, I established a numerical scale according to the behavior I noticed; it goes from 1 to 5, where 1 is the best result and 5 is the worst. By means of this scale, I estimated the lag present in the gameplay, in the pause menu and the level of audio distortion overall.

Below I show the results I got in different versions of mGBA, specifically from 0.7.3 stable to dev build 0.10-7106-19c57e0c1 from 02/09/2021:
![Lag MMZ1 FINAL](https://user-images.githubusercontent.com/82909608/132072601-3072fc43-2cad-4c7b-b576-8234ab1fa5fc.jpg)

Lastly, it should be noted that I did this test with a ROM from the No-Intro set; plus there is also lag in Mega Man Zero 2, 3 and 4 but I'll open their respective issues immediately after this one.

My PC specs:
Processor: Intel Atom N450 1.66 GHz
GPU: Intel GMA 3150 (Integrated)
OS: Windows 7 Starter SP1 32-bit
RAM: 1 GB

Without further ado, thank you for your attention.

**Comment by endrift** [comment]
I cannot accept bug reports that are simply "the game runs slow on my ancient computer" with a graph that shows only subjective metrics.

**Comment by SilverKnight-Z** [comment]
Can you recommend me anything for providing more reliable information? I don't know how to measure FPS in a specific time basis

**Comment by endrift** [comment]
I mean, there's an FPS counter on the top of the window if you haven't disabled it. Further, if you have the display driver set to Software, say, because of a bug like #2136, then it's gonna be slow regardless on an old computer; the computer simply doesn't have the horsepower to draw it to the screen quickly in software.

**Comment by SilverKnight-Z** [comment]
> I mean, there's an FPS counter on the top of the window if you haven't disabled it.

Of course I didn't disable the FPS counter, but i don't know how to extract that information and put it in a way that I can show something to prove what is going on. That was the only way I could think of

>  Further, if you have the display driver set to Software, say, because of a bug like #2136, then it's gonna be slow regardless on an old computer; the computer simply doesn't have the horsepower to draw it to the screen quickly in software.

Oh I get it. I didn't know that

**Comment by endrift** [comment]
I hadn't realized it when I first closed the bug, sorry. I'm still working on getting my netbook in such a shape where I can debug that issue.
