### ISSUE TITLE
Sonic Advance - Minor Graphic Bug on Character Select Screen

### ISSUE THREAD

**Issue by Awakened0** [mgba-emu/mgba#23]
There's an odd white layer on the left and right during character select:

![whitebug](https://cloud.githubusercontent.com/assets/4565863/7648033/e40175c2-faab-11e4-8275-9d7829a801d6.png)

**Comment by endrift** [comment]
Oh huh, all this time I thought this was intentional, but it doesn't reproduce on hardware. I'll take a peek shortly.

**Comment by endrift** [comment]
Fixed in ec529a86c795b46f08d92f20cffed3920ce7b3c8
