### ISSUE TITLE
[Regression] Magical Vacation JPN - bad Audio

### ISSUE THREAD

**Issue by exhalatio** [mgba-emu/mgba#230]
I've get the great Audio in previous 2016-02-11 build.
However, I don't get some part of Audio in 2016-02-15 build and newest.

I use the BIOS file and enable Skip BIOS intro.

**Comment by endrift** [comment]
Probably caused by the audio overhaul. I'm in the middle of cleaning it up; it's known to be really buggy.

**Comment by exhalatio** [comment]
I'm sorry, I reported the regression seem to be in a hurry.
Thank you for caring the issue.

**Comment by endrift** [comment]
Should be fixed as of b8ed859, which just missed the cutoff for the most recent nightly.
