### ISSUE TITLE
Homebrew game doesn't boot while using the GBA BIOS and not skipping the BIOS intro

### ISSUE THREAD

**Issue by Bobsican** [mgba-emu/mgba#2301]
Okay, so I converted a video to a GBA game file by using that one Meteo homebrew for the fun of it and stuff. Anyways, if I boot the game while using the GBA BIOS file *and* not skipping the BIOS intro, it hangs.

![2021-09-03 (2)](https://user-images.githubusercontent.com/62492805/132077723-6ba24efa-fb3b-4171-ac26-2c5835b99442.png)

This also happens to the current main 9.2 version of the emulator, by the way.

Here's also the game file, given that this is a homebrew and can't really be obtained elsewhere
https://drive.google.com/file/d/1P9soqhNkW9T-qYsPUUVODK7TKeyvBnPW/view?usp=sharing

Maybe it's related to the game file size?

**Comment by endrift** [comment]
The BIOS doesn't permit games without a valid Nintendo logo embedded in the header to boot. mGBA does not check this, but if you emulate the BIOS intro, then you emulate the check itself, which consequently fails. This is a bug in the tool generating the ROM, not mGBA.
