### ISSUE TITLE
[PC, mGBA 0.9.2] Audio clipping in Donkey Kong Country 3 (caused by misaligned 32-bit loading against SOUNDBIAS)

### ISSUE THREAD

**Issue by gocha** [mgba-emu/mgba#2307]
### Expected Behavior
![dkc3-expected](https://user-images.githubusercontent.com/332500/133291980-e058da2b-d455-4e19-b271-2c77c117dd7d.png)

Waveform of the song "Chase".

**Tip**: You can access the in-game music player by entering "MUSIC" in the Cheats screen.

### Current Behavior
![dkc3-actual](https://user-images.githubusercontent.com/332500/133292009-74c76700-89a9-469c-9484-f32a0014862a.png)

The upper part of the waveform is unnaturally compressed.

- Version: 0.9.2

### Additional Context
From the I/O Viewer, I can see that the SOUNDBIAS is set to 0x4300. Changing the Bias value from 768 to 512 will eliminate the problem. The SOUNDBIAS is modified by the following code.

```asm
LDR    R0, =(REG_SOUNDBIAS+1)
LDR    R1, [R0]  ; Misaligned 32-bit load, mGBA reads a meaningless value 0x91439143
MOVS   R2, #0xC0
BICS   R1, R2    ; Clear the resolution
MOVS   R2, #0x40
ORRS   R1, R2    ; Set the resolution to 1
STRB   R1, [R0]  ; Therefore, 0x43 is stored
```

**Comment by endrift** [comment]
Good catch, thanks.

**Comment by gocha** [comment]
@endrift Thank you. Maybe I should have mentioned that the output I expect is not what I get from real hardware. Please verify if necessary.
