### ISSUE TITLE
Loading some GBA save states created before 0.9.0 will freeze emulation

### ISSUE THREAD

**Issue by clobber** [mgba-emu/mgba#2308]
macOS 11.6
mGBA 0.10-7113-2ac692023

I've found that loading some GBA states created before mGBA 0.9.0 will freeze emulation. The issue still persists with the latest development build (2ac692023).

Steps to replicate:
* Save a state in mGBA 0.8.4 using game "Mario Kart - Super Circuit (USA).gba" (MD5 784a036ff1aae709e90167186639b75e)
* Launch the game in mGBA 0.9.0, 0.9.1, 0.9.2 or the latest development build and then load the state.
* Emulation will freeze.

I've attached an example "Mario Kart Super Circuit" save state created with mGBA 0.8.4 that will replicate the freeze: [mksc-0.8.4.ss0.zip](https://github.com/mgba-emu/mgba/files/7174395/mksc-0.8.4.ss0.zip)

Few other games I've tried also affected are "Beyblade V-Force - Ultimate Blader Jam" (I recall there was significant work to fix an audio issue https://github.com/mgba-emu/mgba/commit/5c58186f03fb053038ee804b44051f21623ec62c) as well as some homebrew: [2004MBit](https://gbadev.org/index.php?showinfo=1272), [Anguna](https://github.com/OpenEmu/OpenEmu-Update/blob/master/Homebrew/GBA/Anguna/anguna.gba), [Blast Arena Advance](https://github.com/OpenEmu/OpenEmu-Update/blob/master/Homebrew/GBA/Blast%20Arena%20Advance/blastarenaadvance.gba). More examples may exist but these are all I've tried so far.

**Comment by endrift** [comment]
I've seen temporary freezes, relating to the GB audio channel 4 being behind. I'll see if this is that.

**Comment by endrift** [comment]
This was caused by the HLE BIOS layout shifting around somewhat in 0.9. It cannot be fixed. It's worth noting that there's no guarantee that savestates will work between major versions.
