### ISSUE TITLE
mGBA RetroArch Core Connect Dolphin

### ISSUE THREAD

**Issue by DJRM2021** [mgba-emu/mgba#2315]
Hi, 

Not an issue or bug, but rather, an enhancement/feature request.
Would it be possible to have the same "Connect to Dolphin" functionality of the stand-alone mGBA emulator, on the mGBA retroArch core?

It would be really nice to be able to play Legend of Zelda: Four Swords Adventures on Dolphin in Windows and connect to it via retroarch running on my phone. The ultimate dream is to have Zelda on Dolphin(Windows) + 4 separate Android phones running the mGBA RetroArch core (connected via TCP), that would be the best gaming experience and an emulation milestone.

Thanks in advance.

**Comment by Papermanzero** [comment]
That would be one of the greatest features

**Comment by endrift** [comment]
I don't even think this is _possible_ with the way RetroArch works.
