### ISSUE TITLE
Super Mario Advance 4 - Super Mario Bros. 3 - Graphics glitch

### ISSUE THREAD

**Issue by acepow3r** [mgba-emu/mgba#2320]
Windows 64bit port. Happens to anyone else? There are graphical glitches around some sprites and text but most notably in the title screen, after the intro, you can see the background is all garbled.

**Comment by Testsr** [comment]
Nope?

**Comment by acepow3r** [comment]
Anyone else doesn't see this? Tested on two different computers, Windows 8.1 64bit and Windows 10 64bit, mGBA 0.9.2

![Super Mario Advance 4 - Super Mario Bros  3 (USA)-0](https://user-images.githubusercontent.com/24828777/136660000-86e31892-ad69-4b46-a80a-edce89fabd17.png)

**Comment by endrift** [comment]
The debug BIOS don't work properly with shipped games.
