### ISSUE TITLE
Colours appear washed out

### ISSUE THREAD

**Issue by RunisDauphin** [mgba-emu/mgba#2321]
Name: mGBA
Executable location: 
Portable: Yes
Configuration directory: 
Version: 0.10-7132-40d4c430f
Git branch: master
Git commit: 40d4c430fc36caeb7ea32fd39624947ed487d2f2
Git revision: 7132
OS: Windows 10 Version 2004
Build architecture: x86_64
Run architecture: x86_64
Qt version: 5.15.2
FFmpeg versions: Lavc58.54.100, Lavfi7.57.100, Lavf58.29.100, Lavu56.31.100, SwR3.5.100, SwS5.5.100.%2
libedit not linked
libelf linked
libpng version: 1.6.37
libzip version: 1.7.3
libLZMA version: 19.00
minizip not linked
SDL version: 2.0.16
SQLite3 version: 3.16.2
zlib version: 1.2.11

CPU: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
CPU manufacturer: GenuineIntel
CPU family ID: 06h
CPU model ID: 9eh
Supports ABM: Yes
Supports AVX2: Yes
Supports AVX: Yes
Supports BMI1: Yes
Supports BMI2: Yes
Supports CMPXCHG16: Yes
Supports CMPXCHG8: Yes
Supports MOVBE: Yes
Supports POPCNT: Yes
Supports RDRAND: Yes
Supports SSE2: Yes
Supports SSE3: Yes
Supports SSE4.1: Yes
Supports SSE4.2: Yes
Supports SSE4a: No
Supports SSE: Yes
Supports SSSE3: Yes
OpenGL type: OpenGL
OpenGL supports legacy (1.x) contexts: Yes
OpenGL supports core contexts: Yes
OpenGL renderer: Intel(R) HD Graphics 630
OpenGL vendor: Intel
OpenGL version string: 3.0.0 - Build 27.20.100.9416

Size: 1600x900
Location: 0, 0
Refresh rate: 60 Hz
Pixel ratio: 1
Logical DPI: 96x96
Physical DPI: 91.7381x91.8072

Window size: 1200x821
Window location: 199, 3
Screen: 2
ROM open: Yes
Game: Kirby and the Amazing Mirror (Europe), maybe more games.
Configuration: 1

[gba.input.SDLB]
keyRight=-1
keyDown=-1
axisUpValue=-12288
hat0Up=6
axisLeftAxis=-0
axisLeftValue=-12288
axisRightAxis=+0
keyR=-1
keyL=-1
hat0Right=4
hat0Left=5
keyB=-1
keyUp=-1
keySelect=-1
keyLeft=-1
axisRightValue=12288
keyA=-1
hat0Down=7
axisDownValue=12288
keyStart=-1
axisUpAxis=-1
axisDownAxis=+1

[gba.input.QT_K]
keyRight=16777236
keyDown=16777237
keyR=88
keyL=90
keyB=83
keyUp=16777235
keySelect=32
keyLeft=16777234
keyA=65
keyStart=16777220

[ports.qt]
fullscreen=0
showOSD=1
update.dev.size=13415898
suspendScreensaver=1
logFile=
update.stable.size=13118583
width=1200
skipBios=0
gb.pal[4]=16777215
gb.pal[5]=11184810
update.medusa.dev.commit=4d137e7f85e1e0a1f17f53aa1ac126a855559b37
pauseOnMinimize=1
useDiscordPresence=1
autoload=1
allowOpposingDirections=0
muteOnMinimize=0
gb.bios=.\BIOS\mgb_bios.bin
logToStdout=0
lockIntegerScaling=1
gb.pal[0]=16777215
update.dev.rev=7132
logLevel=7
pauseOnFocusLost=0
frameskip=0
hwaccelVideo=0
update.dev.path=build/mGBA-build-2021-09-30-win64-7132-40d4c430fc36caeb7ea32fd39624947ed487d2f2.7z
height=800
rewindBufferCapacity=0
autofireThreshold=1
showFilename=0
vbaBugCompat=1
savestatePath=.\Archivos de Partida
gb.pal[10]=5592405
sampleRate=44100
shader=
update.bucket=https://s3.amazonaws.com/mgba/
lockAspectRatio=1
cheatsPath=.\Trucos
lastDirectory=
logLevel.core.status=111
cgb.model=CGB
fastForwardRatio=-1
resampleVideo=0
autosave=0
scaleMultiplier=5
showLibrary=0
loadStateExtdata=14
interframeBlending=0
gba.audioHle=0
sgb.borders=1
videoScale=1
updateAutoCheck=1
gb.pal[2]=5592405
update.medusa.dev.size=10034982
showFps=1
cheatAutoload=1
gb.colors=1
update.dev.sha256=eacdb196014ad6c1f57c2212b14c7bc8b811f96fc8df7161c1ca53600b01112f
audioSync=1
fastForwardVolume=256
sgb.model=SGB
fastForwardHeldRatio=-1
gbc.bios=.\BIOS\gbc_bios.bin
sgb.bios=.\BIOS\sgb2bios.bin
screenshotPath=.\Pantallazos
savegamePath=.\Archivos sav
idleOptimization=ignore
gb.pal[1]=11184810
gb.pal[8]=16777215
dynamicTitle=1
gb.model=DMG
update.medusa.dev.rev=5518
fastForwardMute=0
update.stable.path=release/mGBA-0.9.2-win64.7z
volume=256
videoSync=1
rewindEnable=1
logLevel.gba.bios=33
preload=0
cheatAutosave=1
gba.forceGbp=0
cgb.sgbModel=SCGB
cgb.hybridModel=CGB
libraryStyle=0
mute=0
fpsTarget=60
gb.pal[6]=5592405
gb.pal[9]=11184810
update.stable.sha256=d4128d77ea3dac0ca87c360c67eb600f94741e551c03587bf17ed29af0bdc084
update.dev.commit=40d4c430fc36caeb7ea32fd39624947ed487d2f2
gba.bios=.\BIOS\gba_bios.bin
muteOnFocusLost=0
patchPath=.\Parches
audioBuffers=1536
saveStateExtdata=28
update.stable.version=0.9.2
useBios=1
logToFile=0
update.medusa.dev.path=build/medusa-build-2018-01-31-win64-5518-4d137e7f85e1e0a1f17f53aa1ac126a855559b37.7z

[General]
audioDriver=1
displayDriver=1
cameraDriver=0
camera=@ByteArray(@device:sw:{860BB310-5D01-11D0-BD3B-00A0C911CE86}\\{A3FCE0F5-3493-419F-958A-ABA1250EC20B})
language=fr
multiplayerAudio=active
windowPos=@Point(0 0)
maximized=false
lastUpdateCheck=@DateTime(\0\0\0\x10\0\0\0\0\0\0%\x87\x64\x3\xfd'\xfe\x1)

[shortcutKey]
autofireR=V
autofireL=C
autofireB=F
autofireA=D
holdGSButton=
settings=Ctrl+P
cheatsWindow=Ctrl+C
fpsTarget.60=I
fpsTarget.30=O
mute=\xd1
frame.1x=1
frame.2x=2
frame.3x=3
frame.4x=4
frame.5x=5
frame.6x=6
frame.7x=7
frame.8x=8
fullscreen=
exitFullScreen=Esc
reset=Tab
pause=Pause
frameAdvance=
holdFastForward=Backspace
fastForward=P
holdRewind=
rewind=
frameRewind=
increaseLuminanceLevel=+
decreaseLuminanceLevel=-
about=F1
connectDolphin=F2
loadState=Ctrl+L
saveState=Ctrl+S
quickSave.9=
quickSave.8=
quickSave.7=
quickSave.6=
quickSave.5=
quickSave.3=
quickSave.4=
quickSave.1=
undoSaveState=
quickSave.2=
quickLoad.9=
quickLoad.8=
quickLoad.7=
quickLoad.5=
quickLoad.6=
quickLoad.4=
quickLoad.2=
quickLoad.3=
undoLoadState=
quickLoad.1=
multiWindow=F3
romInfo=F4
shutdown=Shift+Tab

[shader.default.0]
gamma=1
scale%5B0%5D=2
scale%5B1%5D=2
scale%5B2%5D=2
bias%5B0%5D=0
bias%5B1%5D=0
bias%5B2%5D=0
desaturation%5B0%5D=0
desaturation%5B1%5D=0
desaturation%5B2%5D=0

[mru]

ISSUE:
For some weird reason, when I play this game (known for its colourful graphics), most of the tiles appear close to white or lighter in tone. I put everything that your Bug Report Generator redacts, so it helps you find why does this happen.
When I tried this game Sunday 27th September with its latest version and with an i3-6100 and 8 GB of RAM, this error was not present (at least, I could not perceive it). I am going to post an image of the title screen so you can makean idea of what do I mean:
![GBA Kirby's Amazing Mirror (Europa)-0](https://user-images.githubusercontent.com/49384468/135907659-de294acf-2704-4e0a-85e0-02c47ae12028.png)

**Comment by RunisDauphin** [comment]
In my screen does not appear like the image captured by the game:
![Kirby and the Amazing Mirror (Europe)-0](https://user-images.githubusercontent.com/49384468/135908270-db9d89c1-af3e-41bc-a75c-5032b8747409.png)

The first image is captured by the emulator, the second one by Windows.

**Comment by endrift** [comment]
Your shader settings are screwed up. Set turn the scale back down to 1 for all of them. This isn't a bug.

**Comment by RunisDauphin** [comment]
It happens with all shaders inactive, without touching anything.

**Comment by RunisDauphin** [comment]
Let me check before answering.

**Comment by RunisDauphin** [comment]
Sorry, I touched the scaling to 2 instead of 1. My fault.
