### ISSUE TITLE
Roms keep freezing no matter what driver is used

### ISSUE THREAD

**Issue by Emerald-Greens** [mgba-emu/mgba#2327]
Hi, been having this issue for a few days, especially on the rom hack Inclement Emerald, but it's also been happening with other roms as well, and I'm not sure what I might be doing wrong. I'm using version 0.9.2 of mGBA, and I've tried 6 or 7 other roms besides the patched trashman emerald rom i'm using (nightmare in dream land, sonic advance, mega man battle network, metroid fusion, a link to the past, and mario & luigi: superstar saga all have the same issue i'm describing). I'm also on the latest version of windows (Windows 10 Home 64-bit), and I'm not 100% sure of my graphics card, but I've got an i7-5500U CPU. Basically, I'll load up the rom, play for a little while, but i only get like about a minute into playing whatever it is before everything freezes. Then the program stops responding, and i have to close it in order for anything to happen. I've tried openGL, and openGL (forced version 1.x), and both have this issue, and Software QT doesn't even load the program, just a white screen! Sorry this is so long, but if anyone has any idea what's going on here, I'd love to know.

**Comment by endrift** [comment]
Please retest with mGBA 0.9.3
