### ISSUE TITLE
Controller no longer works

### ISSUE THREAD

**Issue by bentley** [mgba-emu/mgba#233]
Since 13dfb144e88290b0e747ac51391f0882e57ce4b2, my controller (RetroUSB USB Super RetroPort) no longer works in either the SDL or Qt interfaces; the buttons have no effect, and I can only provide input through z, x, etc on the keyboard.

The controller config in Qt doesn't work either—the buttons appear to be configured (because I have a config file), but if I clear a button I can’t fill it again, as pressing buttons still has no effect.

Platform is OpenBSD, with qt5-5.4.1/sdl2-2.0.4.

**Comment by endrift** [comment]
This was fixed in dc62c52faad0cd269506fa7e1f27a70fcff3538d.
