### ISSUE TITLE
Feature request: add a menu option for closing full screen mode

### ISSUE THREAD

**Issue by ashelleyPurdue** [mgba-emu/mgba#2331]
From time to time, I accidentally press the keyboard shortcut that switches the emulator to full screen mode.  Every time this, happens, I need to alt-tab to my browser so I can google the keyboard shortcut to change it back.

If there were a menu option I could use to toggle full-screen, then I wouldn't need to do that.  The "audio/video" dropdown would be a good place for it, I think.

**Comment by endrift** [comment]
There...already is one. It's under the window size submenu.
