### ISSUE TITLE
[PS Vita] Bad sound quality in Metroid Zero Mission

### ISSUE THREAD

**Issue by x5f3759df** [mgba-emu/mgba#2336]
The sound is cracking badly, making this game barely playable with sound sometimes. The worst case - first mini-boss (big worm with charged beam).

This is related to PS Vita standalone vpk and libretro core too.

**Comment by endrift** [comment]
This is probably due to the game running slower than full speed. Please turn on the FPS counter and verify.

**Comment by shkuratov-d** [comment]
Yes, fps counter shows 56 fps max in a first level. Skip frame setting set to 2-3 fixes issue, but it's unplayable.

**Comment by x5f3759df** [comment]
Yes, fps counter shows 56 fps max at first level. Skip frame setting set to 2-3 fixes issue, but it's unplayable.

**Comment by x5f3759df** [comment]
I guess there is no way to fix that on Vita.
