### ISSUE TITLE
Emulator keeps crashing when I try to save a game + Fast forward lag/glitch

### ISSUE THREAD

**Issue by DXPKMN** [mgba-emu/mgba#2338]
Recently, I have been experiencing an issue where whenever I try to save a game (I'm playing Pokemon Rom Hacks), the game sometimes freezing and crashes or it lags and then continues. Also, most times when I fast forward, the game lags like crazy or it gets stuck in fast forward mode and forces me to reset the whole emulator. These have really put a damper on my playthroughs and I'd appreciate it if the dev team could tackle this as soon as they possibly can.

**Comment by endrift** [comment]
Closing due to lack of reply.
