### ISSUE TITLE
Rumble not working

### ISSUE THREAD

**Issue by ddubs13** [mgba-emu/mgba#2341]
mGBA's website claims to support rumble. I'm playing Super Mario Advance 4 and enabled rumble in the options, but have no rumble through my Dualshock 4. Is this feature only available through a libretro core? Or is there some way to get it working on the desktop app that I don't know about?

**Comment by endrift** [comment]
SMA4 requires that Game Boy Player features be enabled for rumble to work. Did you enable them?

**Comment by ddubs13** [comment]
> SMA4 requires that Game Boy Player features be enabled for rumble to work. Did you enable them?

Yes.

**Comment by ddubs13** [comment]
I figured out the problem. It was my Dualshock 4. For some reason, rumble won't work with it, but I eventually got it working with a Wii U Pro Controller using WiinuSoft.

**Comment by kode54** [comment]
Are you using it over Bluetooth? At least in macOS land, the rumble does nothing over Bluetooth, only wired over USB.

**Comment by ddubs13** [comment]
> Are you using it over Bluetooth? At least in macOS land, the rumble does nothing over Bluetooth, only wired over USB.

Wii U Pro is the only other controller I have, and it doesn't work via wired. Rumble is working over bluetooth for SMA4, but not Drill Dozer. It also doesn't work for a romhack for SMA4 that gives it cartridge rumble.

**Comment by kode54** [comment]
I was referring specifically to the DS4 controller not working over Bluetooth. I have no idea how that Wii U controller works out for that.

**Comment by ddubs13** [comment]
> I was referring specifically to the DS4 controller not working over Bluetooth. I have no idea how that Wii U controller works out for that.

DS4 was wired.

**Comment by endrift** [comment]
Please retest with the latest dev build; this may have gotten fixed today.

**Comment by HookedBehemoth** [comment]
Rumble works with ds4 on 0.9.3 with or without DS4Windows.

Is this supposed to only work on selective games? Custom rumble patches are a thing now.

**Comment by kode54** [comment]
Rumble can only work if Gameboy Player support is turned on.

**Comment by endrift** [comment]
No...? Drill Dozer and WarioWare support it via the cartridge. I assume custom rumble patches use that interface.

**Comment by kode54** [comment]
Oh, I was confused about which feature this was.
