### ISSUE TITLE
mGBA CTD when opening ROM

### ISSUE THREAD

**Issue by cosnaigh** [mgba-emu/mgba#2343]
I have a new computer with WIndows 10 LTSC 1809 64-bit, Ryzen 5 5600H CPU, Nvidia Geforce GTX 1650 GPU.  I have installed the latest drivers for the above. I am unable to load any ROM in the emulator without the emulator immediately crashing to desktop. There is no error message.  I do not believe the issue is with the ROMs as I have copied the ROMs from an older computer where they ran without issue on version 0.9.0.  I have tried to open the ROMS with each of the version 0.9.x releases and have seen no change in performance.

**Comment by endrift** [comment]
Please upload the bug report zip (File > Report Bug)

**Comment by cosnaigh** [comment]
[Issue 2343 Report.zip](https://github.com/mgba-emu/mgba/files/7488298/Issue.2343.Report.zip)
Is this it?

**Comment by endrift** [comment]
You do not appear to have graphics drivers installed. Please install the Nvidia drivers.

**Comment by endrift** [comment]
Please confirm if that worked.
