### ISSUE TITLE
Saved state on mGBA 0.8.2 is Corrupted 

### ISSUE THREAD

**Issue by YellowFlamingXL** [mgba-emu/mgba#2346]
Processor	Intel(R) Pentium(R) CPU  N3540  @ 2.16GHz   2.16 GHz
Installed RAM	8.00 GB (7.89 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Home
Version	20H2
Installed on	‎2020-‎11-‎08
OS build	19042.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0

Version of MGBA Emulator: 0.8.2

Name of game affected: Final Fantasy 5

When I play on mGBA I save by going to the "save state option" and press "load state" to return to where I last left off, everything was fine yesterday but today when I go to  "load state" the saved state says "Corrupted" how do I fix it? this has never happened before until today and the game that I am playing is Final Fantasy 5

https://cdn.discordapp.com/attachments/874826684942131240/906705659121246268/Screenshot_631.png (this is how it looks like, highlight the link, and then right click it and then go on "go to.....")

**Comment by endrift** [comment]
mGBA 0.8.2 is very old and no longer supported. There isn't really much I can do here.
