### ISSUE TITLE
mGBA stuck going up

### ISSUE THREAD

**Issue by davidrf257** [mgba-emu/mgba#2351]
When I downloaded mGBA, every ROM I tried worked perfectly.  I even recorded the video and audio and managed to edit into a proper video.  Less than a week later, every single ROM suddenly has the up button being perpetually pressed.  I tried restarting my computer and deleting/redownloading mGBA multiple times, neither way works no matter how many times I try.
[mGBA-perpetuallyup.zip](https://github.com/mgba-emu/mgba/files/7524501/mGBA-perpetuallyup.zip)

**Comment by endrift** [comment]
I've seen this happen with some peripherals plugged in, like tablets. Can you see if the controller mapping shows anything unusual?

**Comment by davidrf257** [comment]
So it turns out that I had a pro controller plugged in without knowing, so my controls are fine now; however, I can no longer record using the built-in recording function.  Ever since I unplugged the pro controller, when I try to record it gives me a pop-up titled "An error occurred" and it says "Failed to open output video file: (file name)".  I'm wondering if somehow in my uninstall/reinstall troubleshooting it changed the file paths and now it doesn't know where to save it to but that's just my guess.

**Comment by RetroEdit** [comment]
It sounds like the original issue was fixed. If there's further issues with recording after a fresh install and deleting the configuration in `%AppData%/mGBA`, then a new issue can be opened.
