### ISSUE TITLE
Menu disappears 

### ISSUE THREAD

**Issue by ConfuseGhost** [mgba-emu/mgba#2354]
Idk what i did but while i was playing pokemon fire red my screen went into full screen mode and the menu disappeared, i tried changing the menu (tho idk what to change) and uninstalling and reinstalling Mgba but nothing is working

**Comment by endrift** [comment]
The menu should reappear if you exit full screen, pause the game (Ctrl-P) or if no game is loaded...

**Comment by endrift** [comment]
Did you ever confirm if pausing worked?
