### ISSUE TITLE
No Text In Pokemon Fire Red

### ISSUE THREAD

**Issue by moonkeyAvM** [mgba-emu/mgba#2355]
[Bug-NoText.zip](https://github.com/mgba-emu/mgba/files/7565960/Bug-NoText.zip)

Whenever I speak to someone in Pokemon Fire Red, only a blank box appears. If it requires a yes/no response, I can still select a response, but no follow up text appears and I don't know what I am agreeing to or refusing. This also occurs when I can't complete an action during a pokemon battle. For example, if I am trying to switch pokemon but the other pokemon has arena, or an ability that doesn't allow me to switch, a blank box will flash for a frame, sometimes leaving me wondering why I can't switch pokemon.

**Comment by endrift** [comment]
This is an issue with a ROM hack. Without a copy of the patch, I cannot verify if this is a real bug or if the ROM hack just targeted inaccurate emulators.

**Comment by endrift** [comment]
Forward-duped to #2806 since this was never given the needed info.
