### ISSUE TITLE
OpenGL video renderer under Enhancements caps FPS and disables fast-forward

### ISSUE THREAD

**Issue by SilentCrescend0** [mgba-emu/mgba#2356]
Title, I tried everything I knew to do to uncap it, but to no avail. Wouldn't go above 144fps (which is my monitor refresh rate, so maybe it's something to do with V-/G-Sync). The only thing that worked is changing back to the software renderer. Fast forward does not do anything when OpenGL is selected for me.

**Comment by goliv04053** [comment]
I think that we are having the same problem. Mine issue is: #2425

**Comment by endrift** [comment]
This was fixed in 0.10.1.
