### ISSUE TITLE
Feature Request: Cemuhook integration for Motion sensor games

### ISSUE THREAD

**Issue by GaussTek** [mgba-emu/mgba#2362]
Wondering if it would be possible? Cemu hook is already integrated in emus like Cemu, Dolphin, Citra, etc for Windows and uses the motion sensors in controllers like Dualshock 4, Dualsense, Switch Pro Controller etc to play motion sensor games. And works pretty great in those.

https://wiki.dolphin-emu.org/index.php?title=DSU_Client

Could something similar approach be implemented for mGBA?

Many thanks!!

**Comment by endrift** [comment]
mGBA dev builds already directly support the motion controls in those controllers so I'm not sure this will be necessary.

**Comment by GaussTek** [comment]
Omg, you are right, I should have tried the dev builds before lol. It works just perfect with all the games, thanks a lot!! 😭
