### ISSUE TITLE
Feature Request: .sav files should be organized into the saves folder much like how TwilightMenu++ does that

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#2363]
to be more organized with the save files and roms, and don't forget to add that feature sometime around in the mGBA lifespan before 2022-2024 
![Twilight Menu++ Saves](https://user-images.githubusercontent.com/95099583/143618047-11c621ab-4094-4eb1-a2a6-1c0ca36a19a5.png)
![Twilight Menu++ Saves2](https://user-images.githubusercontent.com/95099583/143618051-43fc7f45-c806-448f-aaf4-1bc731dc981d.png)
https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v23.1.0

**Comment by f1660t0982143** [comment]
this feature especially needs to be added before medusa releases aka 2.0.0, the best time to add that save folder feature is in version 0.10.0.

**Comment by endrift** [comment]
You really don't get to make demands about the release schedule you know. This software is free and I'm the only major contributor. Plus you can already do this, you just need to make manual changes to the config file. I believe there's already an open bug about it.

**Comment by endrift** [comment]
Oh you deleted your account. Okay.
