### ISSUE TITLE
[BizHawk] While within the BIOS, loading a savestate made on frame 6 or 7 crashes BIOS

### ISSUE THREAD

**Issue by CasualPokePlayer** [mgba-emu/mgba#2365]
Hindsight is 20/20 and reporting this now here https://github.com/TASEmulators/BizHawk/issues/2938

**Comment by endrift** [comment]
I can't reproduce this on standalone. Can you make a crashing savestate to see if loading it crashes standalone?

**Comment by CasualPokePlayer** [comment]
Standalone rejects BizHawk states it seems.
