### ISSUE TITLE
[3DS] V-Rally 3 (JP), Stuntman (US) arm11 exception bug?

### ISSUE THREAD

**Issue by qamichele5959** [mgba-emu/mgba#2374]
I've started the games all run fullspeed, but V-rally 3 japanese actually gets into the Atari logo exclusively then throws a error, and stuntman usa not getting to the Atari logo actually then black screens with errdisp error message on bottom screen, so any to fix this? Now all work on GBARunner2.

**Comment by endrift** [comment]
If you do not give me the information I have requested twice now I will be blocking you from this organization, as you are impossible to work with, much as you were from the discord.
