### ISSUE TITLE
GB Pallete only apply when i hit apply on the settings menu

### ISSUE THREAD

**Issue by Skeledon1** [mgba-emu/mgba#2377]
im on the newest version: 0.10-7164-2f8526a0b
let me explain if i start the game it starts with the GBC color palette i have to open the settings and just hit apply everytime i start a game to apply the GB pallete idk if that is intented 
![image](https://user-images.githubusercontent.com/93798212/145224625-21022900-8c50-4cf0-be63-3c8ff15a87b5.png)
these are my settings. its not the biggest problem in the world but i just wanted to mention it

**Comment by endrift** [comment]
I'm pretty sure I fixed this at some point. Can you verify?

**Comment by Skeledon1** [comment]
Omg this thread is so old, but yeah u fixed it THanks :D

**Comment by Testsr** [comment]
This thread can be closed now.
