### ISSUE TITLE
few Gameboy bugs

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#238]
Altered Space - A 3-D Alien Adventure (USA)
during the intro the spaceship graphics are messed up
and when you start the gameplay it freezes up straight away

Mortal Kombat & Mortal Kombat II (USA, Europe)
if you choose one or two it just resets back to the developers screen

Super Chinese Land 1.2.3. Dash (J)
which ever game you choose it resets back to the title screen

Namco Gallery Volume 2 (J)
choose galaxians and during the game the top two galaxians are shown the rest are invisible

Pokemon Red-Blue 2-in-1 (U)
doesn't load either game

**Comment by taisel** [comment]
Torpedo range IIRC has some special IRQ or HALT issue some GB emulators don't handle, don't know what the case is for mgba though.

**Comment by endrift** [comment]
It also uses MBC2, which mGBA hasn't implemented yet. Zerd no Densetsu seems to jump to $0038 and get stuck, though.

**Comment by endrift** [comment]
Pushed some changes that should fix Zerd no Densestu, Torpedo Range and Hercules Eikou.

**Comment by benderscruffy** [comment]
Urusei Yatsura (J)
just a white screen

Super Chinese Land 1.2.3. Dash (J)
which ever game you choose it resets back to the title screen

Namco Gallery Volume 2 (J)
choose galaxians and during the game the top two galaxians are shown the rest are invisible

Pokemon Red-Blue 2-in-1 (U)
doesn't load either game

Sumou Fighter (J)
just a white screen

**Comment by sczther** [comment]
The Mortal Kombat compilation and possibly other compilations use their own mapper which needs to be supported. I know gekkio did some tests with it.

**Comment by endrift** [comment]
It doesn't even work in BGB. It seems extremely low priority to get working.

**Comment by benderscruffy** [comment]
works in KiGB

**Comment by sczther** [comment]
KiGB is a cluster**** of game specific hacks, no wonder everything looks like it works there :P 
Just wait until somebody makes some documentation for that specific mapper

**Comment by taisel** [comment]
^ kigb "magically" works with games that rely on behavior tested by blargg's sound test roms which it fails.

**Comment by benderscruffy** [comment]
who really cares if it is full of hacks
nearly all emulators have a hack or two in them :)

**Comment by taisel** [comment]
People who write emulators trying to validate behavior by comparing to other emulators. In this case avoid validation by comparing to kigb.

**Comment by profi200** [comment]
If an emulator has to rely on patches to work correctly the platform is either totally underpowered or the emulator is crap.

**Comment by endrift** [comment]
Pushed a fix for Sumou Fighter and Urusei Yatsura.

**Comment by endrift** [comment]
MBC1M support is unlikely to arrive in 0.5, but other bug fixes may be targeted for 0.5.

**Comment by endrift** [comment]
Altered Space fixed in master, but it breaks a handful of other games so it'll take some flattening out.

**Comment by endrift** [comment]
The Galaxian bug seems to have gotten fixed at some point. The rest are MBC1M bugs, so I'm punting this now that the rest have been fixed.

**Comment by sczther** [comment]
A few more:
Alleyway  - can't move the paddle (this may have something to do with link port, the game for example doesn't function on hardware when a printer is inserted)
Pinball Deluxe/Dreams/Fantasies - sometimes doesn't star, quickly gets corrupt and borks (a well known bug, which happens only on ACCURATE emulators, yet not on hardware)
Prehistorik Man - garbage on the left of the scrolling screen

**Comment by endrift** [comment]
MBC1-M issues fixed in f84af911739274c9e4ea24b37d8b4f784f040f84. Pokemon Red-Blue 2-in-1 is an unlicensed bootleg and thus doesn't actually have a proper MBC in it, so it likely wouldn't really work in anything.

Note that there's a 528kiB dump of Mortal Kombat I & II floating around that claims to be a good dump. The proper dump size is in fact 1MiB and the 528kiB version won't work. (It's literally just bank 0 with banks $10-$1F (MK1) and $20-$2F (MK2) slapped on immediately after, and banks 0x30-0x3F missing.)
