### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by RGProgrammer** [mgba-emu/mgba#2380]
When i build the project as LIBMGBA_ONLY ( with software rendering) and integrate the library in an android app the emulation video freeze a random locations and does not respond to the any key inputs.

**Comment by endrift** [comment]
There isn't Android support. This sounds like you haven't understood what's needed to port to Android.

**Comment by RGProgrammer** [comment]
sorry i'm a noob in this field but i dove a little in the cmake file and
the DS part of the project and i didn't see why it won't work on android.
Anyway thanks for the help and I will see what I can do from my side to
make it work.
