### ISSUE TITLE
libavcodec error

### ISSUE THREAD

**Issue by Blad3forc3** [mgba-emu/mgba#2382]
[ 52%] Linking C shared library libmgba.so
/usr/bin/ld: /usr/local/lib/libavcodec.a(vc1dsp_mmx.o): relocation R_X86_64_PC32 against symbol `ff_pw_9' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/mgba.dir/build.make:2668: libmgba.so.0.10.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:340: CMakeFiles/mgba.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

Or can this be disable during the cmake command?

**Comment by endrift** [comment]
This is an issue with your version of libavcodec, not mGBA. You need to rebuild libavcodec or disable using it in mGBA.
