### ISSUE TITLE
[3DS] Dai-Mahjong Probably throws a Arm11 "undefined instruction" exception bug?

### ISSUE THREAD

**Issue by newestdodain475** [mgba-emu/mgba#2383]
It actually loads this one game but everything is so showed me a Arm11 "undefined instruction" error before the game starts so any question?

**Comment by newestdodain475** [comment]
Gericom/GBARunner2/issues/241

**Comment by newestdodain475** [comment]
Gericom/GBARunner2/issues/127

**Comment by endrift** [comment]
I'm pretty convinced at this point that you've messed up your 3DS somehow, and it's not actually a problem with mGBA itself.

Also, if you're qamichele this is ban evasion and I will ban this account too. You do not actually listen to me so I can't actually help you.

**Comment by Epicpkmn11** [comment]
they're definitely qamichele, we've already banned from DS-Homebrew and they've been spamming GBARunner2 with the exact same type of issues

**Comment by endrift** [comment]
I figured, I just wanted to confirm first. It's unfortunate that he doesn't seem to understand that he's just being disruptive and unhelpful.

**Comment by Epicpkmn11** [comment]
yeah... I honestly don't understand what he wants, I've tried to answer his questions and he'd just ignore it...

**Comment by endrift** [comment]
That's exactly what happened on the Discord and why he's banned from it.
