### ISSUE TITLE
PSV Golden sun 2 Still doesn't support

### ISSUE THREAD

**Issue by Dsseed** [mgba-emu/mgba#2384]
Been waiting for mgba 0.9.3，
Because the new  PSV RetroArch  core has been perfectly supported Golden sun 2，And it's working perfectly

But I don’t like RetroArch，Hope that PSV mgba can achieve the effect of PSV RetroArch GBA，thanks for your hard working

**Comment by endrift** [comment]
What do your mean by "doesn't support"? I haven't tried that game specifically, but I'm unaware of it being broken in any way.

**Comment by Dsseed** [comment]
The game can run, but The specific manifestations are pauses and pops

**Comment by endrift** [comment]
That's not a bug; that's the game not running full speed since the Vita is slow (less than 500 MHz). The Retroarch gpSP core is a lot less accurate so it's less CPU intensive.

**Comment by Dsseed** [comment]
I found that psv mgba did not call psv gpu，If mgba calls psv gpu, can this problem be improved?

**Comment by endrift** [comment]
It's possible, but there would need to be custom shaders for mGBA, which would be a lot of work to port. I do not know how well they would work and it would be a lot of work to write them.

**Comment by Dsseed** [comment]
Thank you, I've now understood
