### ISSUE TITLE
Cannot choose between different GB modes

### ISSUE THREAD

**Issue by MrKnytt** [mgba-emu/mgba#2388]
Linux Build 0.9.3 - Run on pop_os

I've been completely unable to switch between DMG, GBC, SGB or AGB palettes and loading modes when trying to open GameBoy (DMG) games in mGBA. Sometimes I get color and am unable to choose DMG mode, sometimes I get DMG only and end up with a broken palette when trying to use game overrides. I don't really know what I'm doing wrong, could anyone help me out here?

**Comment by MrKnytt** [comment]
For clarification, it seems to start in SGB mode almost forced, but then it just goes back to whatever the ROM file is with no way to change it once I try and override it. Trying to override before loading the ROM ends up increasing "contrast", or making shades of gray in the palette appear solid black.

**Comment by endrift** [comment]
What games are you trying and what do you expect the results to be? DMG-only games do not have special features on other platforms, though palettes are a thing for _some_ DMG games (but are still running in DMG mode). These palettes are only available in 0.10 (in development) currently, I believe.

**Comment by MrKnytt** [comment]
So far it's with Pokemon Blue and Super Mario Land 2, but any game with color enhancements in some way just doesn't work when I try and use game overrides. Using that feature at all seems to completely break the emulator's system auto-detection, and forcing it to use another system just breaks the black and white palette.

**Comment by MrKnytt** [comment]
It seems to work if I delete my .config file, and I managed to get it to change systems with the gameboy tab in the settings menu, but still it seems like game override is busted.

**Comment by endrift** [comment]
Well, of course it breaks the auto -detection. You're manually telling it to ignore it. DMG games don't run in CGB mode on a CGB. The CGB applies a palette and then turns it down to DMG mode. That's what the "use CGB colors" button is for.

**Comment by MrKnytt** [comment]
Ohhh okay. I see what you mean by that. 

Out of curiosity, what does the game override do?

**Comment by MrKnytt** [comment]
Because using that option breaks the "use CGB colors" option. Like when I use that I can't get any DMG game to display color anymore even though it could before.

**Comment by endrift** [comment]
One of the things you can do with it manually configure a palette for that specific game.

**Comment by MrKnytt** [comment]
The problem is the game already comes with a palette, the palette works normally, and I even figured out how to change it with the button you pointed out. However, when I use the override function, all color just breaks for DMG games, despite having palettes built into the system already. That's the big bug I want to point out, cuz turning the options on and off, changing which palettes get used for SGB or CGB enhanced stuff doesn't matter, it always goes black and white.

**Comment by endrift** [comment]
First of all, it's not the game that comes with a palette. It's the e.g. CGB that comes with a palette for the game. Second, the point of the overrides view is to _override_. If you save the override in there and that override contains a palette, that overrides the palette included in the CGB. That said, if anything the bug is the palette override being stored even if you don't set a different palette while setting up overrides.
