### ISSUE TITLE
Sprite conflict in Drill Dozer (regression)

### ISSUE THREAD

**Issue by Chariblaze** [mgba-emu/mgba#2391]
In the Area 4-2 miniboss fight, the bottom-left door sprite disappears when the miniboss tumbling around is on the same line.

![Drill Dozer (USA)-0](https://user-images.githubusercontent.com/25140801/147392308-1db05f38-59e5-4e7d-a4ae-ff648efca0b6.png)

Tested with mGBA 0.9.3 using default settings on Windows 10 64-bit and Switch. The issue is not present in old builds. It seemed to break specifically with 6199-d61d9ef.

[Bug report ZIP](https://github.com/mgba-emu/mgba/files/7776211/mGBA.Drill.Dozer.sprite.bug.report.zip) (added a save state that works in 6198-ff0b7af)

0.9.3 and [6199-d61d9ef](https://github.com/mgba-emu/mgba/commit/d61d9ef6a6132d6d890053a483b00da74a92f5e5):

https://user-images.githubusercontent.com/25140801/147392321-0231eb7d-2637-40ec-bce3-60cba9b3e752.mp4

[6198-ff0b7af](https://github.com/mgba-emu/mgba/commit/ff0b7af48b701112e007e5e66835c4ee9cf5c8ec) (correct behavior afaik):

https://user-images.githubusercontent.com/25140801/147392569-8b18844a-6b98-4d1c-8c44-7b29fe634eca.mp4

(builds are currently available on this page: https://mgba.io/builds/49/)

**Comment by endrift** [comment]
https://github.com/mgba-emu/mgba/commit/d61d9ef6a6132d6d890053a483b00da74a92f5e5 doesn't affect emulation at all, so that's kinda strange.

**Comment by Chariblaze** [comment]
Ah whoops, 6199 is labelled with & links to d61d9ef on the builds page, but the actual commit in the title bar is 031049cd0.

![drill-dozer-sprite-bug-6199-031049cd0](https://user-images.githubusercontent.com/25140801/147397955-95478816-5571-49a4-85f5-687a0174b316.png)

**Comment by endrift** [comment]
I thought I fixed that bug.
