### ISSUE TITLE
Recorded Gifs save a static image on Windows 10?

### ISSUE THREAD

**Issue by bparisi** [mgba-emu/mgba#2393]
[mgba-bug-zip.zip](https://github.com/mgba-emu/mgba/files/7777698/mgba-bug-zip.zip)

Hey all! Great piece of software!

I'm not sure if this is a bug or not, but I couldn't find anything about it online. I'm using 0.9.3 on Windows 10, (revision 1163869139a4cf38027e567ad77854691958ae84), and it seems like recording a .gif isn't working. Instead it appears that I get a file with the extension .gif, that Windows (in Properties > Details) says is "Item Type: GIF File", but which is in fact only a static image of whatever was showing on-screen when I hit Start.

APNG and webp seem to work fine; I can start and stop with the tool open and I get an image that animates when I open it in a web browser. And I can take a mGBA-generated webp and use a free online tool to convert it into a gif, and it works fine, so this is hardly pressing. But if it is a bug, I thought you should know, and if it's just me being stupid somehow, maybe someone can help me.

Let me know if you need anything else. It happened to me with 3 different games. My graphics card is an RTX 2070 super. Thanks again for great software!

**Comment by AsparagusEduardo** [comment]
Can confirm, it happens in 0.9.3 but not in 0.8.3
