### ISSUE TITLE
The savefile for the 2nd window in a local link connection doesn't get saved

### ISSUE THREAD

**Issue by LOuroboros** [mgba-emu/mgba#2394]
I linked up 2 ROMs of Pokémon Emerald to test something, and the savefile that I made on the 2nd multiplayer window of mGBA is nowhere to be found. In the folder where the ROM is, there's only 1 .sav file that corresponds to the first window,

![explorer_2958](https://user-images.githubusercontent.com/4485172/147423831-9c401e9b-b984-4c7c-b5dd-5ff85969421f.png)

**Comment by endrift** [comment]
There is one save that corresponds to both. Whichever saves more recently overwrites it.

**Comment by LOuroboros** [comment]
> There is one save that corresponds to both. Whichever saves more recently overwrites it.

That's troublesome. What if I wanted to have 2 separate savefiles, and re-test the linking later? I'd have to start a 2nd save all over again which is a bit of a waste of time.
Couldn't a second window get its own savefile? Like `filename_2.sav`, `filename_w2.sav` or something like that?

**Comment by endrift** [comment]
You make a second copy of the ROM.

Anyway this has been a suggested feature and I'll probably do something similar when I get to doing some revamp of the linking stuff.

**Comment by endrift** [comment]
This got added in 0.10 and I apparently forgot to close the file. It's .sav, .sa2, .sa3, and .sa4 respectively.
