### ISSUE TITLE
[Feature Request] Show a checkmark on the Frame size submenu so we know which one is being used

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#24]
Currently (as of the 0.3-2082-e787d00), when you select a Frame size, mGBA doesn't put a checkmark next to the option you chose. I think it would be useful to have one there.

OS: Windows 8.1 x64

**Comment by endrift** [comment]
Fixed in 8e735a4668be274168ff2ef6a32dfb498f7a23fc.
