### ISSUE TITLE
[GBA] Enable writing RTC state/saving in save file

### ISSUE THREAD

**Issue by necomarkro** [mgba-emu/mgba#240]
In Rockman EXE 4.5 Real Operation there is a menu option for setting the RTC time. On console, when you start a new game it asks you to set the time. You can then go back at anytime to the main menu and change the time at the cost of in-game money and removal from on-going story events. However in mGBA (and every other GBA emulator I have tested) setting the RTC through "New Game" and the mentioned menu option does nothing, regardless of "Gamepack sensors" settings.

How to recreate:
1. Select top main menu option to create a new game.
2. Set the time to anything
3. Continue creating the new game until you get to the in-game menu. Note the time on the top of the screen is not the one you set, rather the emulator's sensor.
4. Save and reset the game
5. Select the bottom menu option to set the game time
6. Say yes to the saving prompt then set the time.
7. Select the 3rd menu option to load the save game. Note the time on the top of the screen is not the one you set

Due to all the events in the game being based on the RTC, it gets really annoying to mess with your system time (often causing issues with other programs that rely on it). I'd really like to see an emulator support it as it works on console.

(Not sure this will help but when testing the game in VBA-RR, setting the RTC through "New game" and main menu causes an "Unknown RTC command 64" error.)

**Comment by endrift** [comment]
Strange, it seems to work on my end. Which version of mGBA are you running, and on what OS?

**Comment by necomarkro** [comment]
I'm using mGBA 0.4.0 on Windows 7

**Comment by endrift** [comment]
I won't have a chance to test on that OS until tonight, but in the meantime, make sure you have a clean ROM and not one patched for any reason.

**Comment by necomarkro** [comment]
I recently tried a nightly of mGBA (0.5-3783-9eb8faf) and I am still having the issue. My ROM is not patched (CRC32: a646601b). 

While you can use the emulator options to tweak the RTC time or manually change your windows time, you cannot set the time using the in-game menu option.
This is a big deal for speedrunners as the emulator runs cannot be compared to the console runs and it makes practicing the game is a pain on emulator.

Also, the game time seems to be off from the sensor time by [6 hours](http://i.imgur.com/mOH44jW.png) when set to "Fixed time" and "Start time at". However, "System time" is not off by 6 hours

**Comment by endrift** [comment]
I'm guessing you're in EST? Timezones might be screwing this up.

As for the actual timer issue, I misunderstood your request. mGBA does not save the value stored back into the RTC by the game, which does in fact cause some issues on the GB games that use the RTC. Right now, the best way to work around this is to use the "start time at" setting every time you load the game. This will keep the time incrementing properly, but you get to set what time the game thinks it is when you boot it. I'll see if I can improve this behavior in the future.

**Comment by endrift** [comment]
Partially fixed by ffa7e9b, but to save the value you set the RTC to would require changes to the savegame format.

**Comment by endrift** [comment]
Retargeting this bug report for adding RTC writeback (which is not what the Pokemon games use for some reason), since the other stuff seems to have been fixed by now.

**Comment by profi200** [comment]
@lesserkuma
A bit later than i wanted but let's talk about the format you described in #2431. Is there a reason you choose this split design with RTC date + time and a timestamp? I assume you calculate the actual correct time and date (difference between RTC and timestamp plus difference between timestamp and current date and time).

I personally think saving the RTC as offset would be easier to work with.

**Comment by lesserkuma** [comment]
@profi200 
I looked at existing RTC-state implementations (e.g. Game Boy MBC3 and HuC-3) on emulators, and that seems to be the scheme that had been agreed on; raw values as you would read them from the RTC component plus a timestamp that is used for synchronization.
In the case of the GBA GPIO RTC, there’s also the weekday value which can be a bit odd. I observed two different things with it. In Pokémon games, the RTC seems to be never written to (I may be wrong), and all values just count up from their smallest possible value, but that also means it uses the Sunday value for 2000/1/1. Boktai properly initializes the weekday value to Saturday for 2000/1/1. I didn’t check other RTC games yet.

**Comment by profi200** [comment]
I thought the Pokémon games reset the RTC to 2000.1.1 00:00 each time you start a new game? But yeah, these games don't use the day of week counter. I have not pushed it yet but i implemented the weekday stuff (0 = sunday like most RTCs).

https://gist.github.com/profi200/8c617f3ea4366474cb3ffcb54e41393a

**Comment by lesserkuma** [comment]
Just re-tested it with a retail Pokémon Ruby cartridge! Just starting a new game keeps the old RTC values, but when pushing SELECT+UP+B on the title screen and deleting everything, this will reset the RTC back to 2000/1/1 00:00:00 @ Sunday. So when synchronizing/forward-adjusting the RTC values in software, one could count the days passed since the timestamp and then do `weekday += days_passed % 7` to account for all game-specific oddities.

**Comment by profi200** [comment]
Yeah, that should work. I guess we will go with that format then. Annoying for me since i have to convert back and forth multiple times. I only have BCD and that weird offset in hardware. No unix like timestamps.
