### ISSUE TITLE
ROM Replacement doesn't function as cartridge removal

### ISSUE THREAD

**Issue by SonoSooS** [mgba-emu/mgba#2401]
Short backstory: I'm trying to run code in GBA mode without a GBA flashcart using Pokémon Emerald ACE.
The ACE works on real hardware as intended, but in mGBA it gets stuck in an infinite loop.

Here's the ACE code:

> 01 C3 A0 E3 81 CF 8C E3
> 08 10 4F E2 00 00 9C E5
> 02 09 10 E3 11 FF 2F 01
> 26 00 00 EF

which should disassemble to

```ARM
MOV r12, #0x04000000
ORR r12, r12, #0x204

SUB r1, PC, #8
LDR r0, [r12]

TST r0, #0x8000
BXEQ r1

SWI 0x26 ;@ undocumented HardReset
```

What this should do is upon inserting a GB(C) cartridge, the loop should break, and the undocumented HardReset SWI should be executed, which reboots the BIOS, which detects that a GB(C) cartridge is inserted, and boots it.
However in mGBA, while the game is running this code, using "Replace ROM" to load a GB ROM will never break out of this loop. In fact, the game doesn't even crash, even though a GB(C) ROM should be loaded!

This seems to not be a bug with the core(?), as upon using the "Replace ROM" option, using "ROM Info" says that I still have Pokémon Emerald instead of whatever Game Boy game I loaded.

Using mGBA 9.0.3 on Windows, extracted from the .7z archive.

**Comment by endrift** [comment]
Replace ROM absolutely does not support swapping from a GBA ROM to a GBC ROM in any sense, and would require actually hotswapping the core to do so, which is also not supported.
