### ISSUE TITLE
mGBA Simple Dunnos ?

### ISSUE THREAD

**Issue by inukaze** [mgba-emu/mgba#2403]
Hi there, thanks for create this awesome program :D 

Well i had the follow simple dunnos : 
1 - the SDL version had internal gui in future ? for example like "[DOSBox-X](https://dosbox-x.com)" project, they had too [github page](https://github.com/joncampbell123/dosbox-x/) ?

![sdl-gui](https://user-images.githubusercontent.com/1647332/147813837-e23695b3-3d5f-4f1f-b157-0e52ede53fad.png)

is an internal functional gui on sdl dosbox-x versions :D 

2 - In future release, can be possible use "[Video Filters from RetroArch](https://github.com/libretro/RetroArch/tree/master/gfx/video_filters)" after you compile each ?

i prefer use this "Video Filters" because some "Shaders" can be really slow on my machine.

3 - in future release the user can login to [retroachivements.org](https://retroachievements.org/) account like in retroarch but directly from mGBA (not libretro core) ? 

4 - Bios Checker & Tester, for when the user select files of Bios, can check from the emulator and you can add test.rom for test each bios ?

i had dumps of my bios of gb, gbc, gba and sgb, because when i emulate using mame needs that specific program files. and well the gbc are two files i don't know which file need mGBA for works fine "gbc_boot.1" (256 Bytes) or "gbc_boot.2" (1,8 Kb) or both like MAME for GameBoy Color bios emulation.

Well that is all dunnos i had for now.

Making latest test of year 2021 XD : 
mGBA-QT5 (32 Bits running from native GNU/Linux trought Xephyr on 64 Bits Host)
![mgba-x32-on-x64_001](https://user-images.githubusercontent.com/1647332/147843062-51845404-f648-426e-b2e8-b2dc7f56a6f0.png)

Like i prefer organize structure dirs/files, for make possible had two versions, for 32 Bits & 64 Bits, and all libs each version need to run fine : 
![mgba-x32-on-x64_002](https://user-images.githubusercontent.com/1647332/147843070-176a36be-0ffc-43e8-9fad-b99e6004d3cb.png)

Looks Good
![mgba-x32-on-x64_003](https://user-images.githubusercontent.com/1647332/147843081-8eab2a1f-a70d-41f3-9245-d04c70ee763a.png)

Nice FPS on GBA : 
![mgba-x32-on-x64_004](https://user-images.githubusercontent.com/1647332/147843083-b4fa702d-b0bc-40fa-853a-475ac222dc8c.png)

Well that was all for this year :D. Happy New Year 2022

**Comment by endrift** [comment]
1. This is planned.
2. No, they would need to be manually ported.
3. It is under consideration, but is a low priority feature at this time.
4. Automatically scanning for BIOS to import might be a good idea, if that's what you meant.
