### ISSUE TITLE
Fast Forward is at maximum even when disabled

### ISSUE THREAD

**Issue by KaeliusKonchu** [mgba-emu/mgba#2412]
So I just started up the latest version of MGBA, and my roms are all permanently fast forwarded to Unbonded. Obviously that's unplayable, so I don't know what to do. I've shut off every setting I could think of that was causing it

**Comment by endrift** [comment]
You need to have a sync setting *on* or else it has nothing it can use to know how fast to run.

**Comment by KaeliusKonchu** [comment]
> You need to have a sync setting _on_ or else it has nothing it can use to know how fast to run.

I've enabled video sync but that only gives me a pure white screen. I think I broke something somewhere but resetting it isn't something I know how to do

**Comment by endrift** [comment]
Set the display driver to OpenGL, audio sync on and video sync off. That's the default.

**Comment by KaeliusKonchu** [comment]
> Set the display driver to OpenGL, audio sync on and video sync off. That's the default.

thank you, this solved the problem
