### ISSUE TITLE
Record video function crashes the emulator.

### ISSUE THREAD

**Issue by chowder908** [mgba-emu/mgba#2416]
0.9.2 recording a video works perfectly fine, but in the recent 0.9.3 release video recording crashes no matter what settings you use. I can record a video using the lossless option, but once you press stop it crashes the emulator every other option just crashes when you press start. Tested on both windows and Linux along with a friend being able to replicate it.

**Comment by endrift** [comment]
This was fixed shortly after 0.9.3 came out. You'll have to download a dev build or wait until a new stable version comes out.
