### ISSUE TITLE
[mGUI] Settings menu cut off

### ISSUE THREAD

**Issue by wl418159425** [mgba-emu/mgba#2424]
![微信图片_20220118224455](https://user-images.githubusercontent.com/50484041/149959208-f80578b5-dca0-48d9-b5eb-94fd37a19d9f.jpg)

**Comment by Testsr** [comment]
Title translates as The settings menu on 0.9.3 on PS Vita do not show fully.

**Comment by endrift** [comment]
I thought there was already an open issue for this, but I couldn't find one

**Comment by endrift** [comment]
Looks like this was already fixed for 0.10 in #871 -- hence the duplicate I couldn't find.
