### ISSUE TITLE
(mGBA Development build 0.10-7209-ddca55347) No image on the screen using OpenGL, only Software is working properly

### ISSUE THREAD

**Issue by goliv04053** [mgba-emu/mgba#2425]
OS: Windows 10
CPU: AMD Ryzen 5 3600G Mobile
GPU: Nvidia GTX 1650
RAM: 16 GB
Issue: No image on the screen using OpenGL, only Software
How to replicate this issue?:
1. Use the Development build 0.10-7209-ddca55347
2. Put OpenGL as Video Renderer
3. Done, now your screen doesn't work
Here in the report are attached the report and a video showing this issue:

[mgbareport.zip](https://github.com/mgba-emu/mgba/files/7909665/mgbareport.zip)

https://user-images.githubusercontent.com/22873288/150450161-227bfb6b-ca06-45ad-b768-0eabaf682533.mp4

**Comment by goliv04053** [comment]
I think that my issue is the same as #2356

**Comment by goliv04053** [comment]
Sorry, it's a complete different issue. But it involves the OpenGL video renderer under Enhancements

**Comment by endrift** [comment]
Yeah, this was pointed out to me on the DIscord a few hours ago. I'm working on a patch right now. It should be easy.
