### ISSUE TITLE
Pause + Mute at the same time crashes consistently

### ISSUE THREAD

**Issue by Dowotdashdotdot** [mgba-emu/mgba#2426]
I'm using a SNES controller to play Mother 3 with the English patch. Since modern controllers have an X and Y button as well, I have them bound via the shortcuts in the settings to be "pause emulator" and "mute audio". But if I accidentally (or absentmindedly rubbing my thumbs on my controller because trying to hurry up cutscene or mad because bad) press BOTH at the same time, it completely craps itself and freezes. This happens on all of my controllers, and keyboard. now, I can just disable those bindings. It's nice to have, but unnecessary. However, this does bring to light a critical crash. it also sometimes crashes even if I only hit one. There's like a 20% chance pausing or muting will crash. I'm not sure if this is specific to just this game, but it seems like this would apply everywhere (since both features are part of the emulator and not the original GBA)... Or maybe I have something acting funny elsewhere? I only just started using this program yesterday. Version 0.8-27-4b92176, master branch, Revision: 4b92176aeb9b0b85eff81746d647825043c4e71e. Installed from the snap, running Ubuntu 20.04.3 64 bit.

**Comment by Dowotdashdotdot** [comment]
It appears it has re-surfaced since issue #1612. No screen blanking or anything, but the whole window freezes (including the menu bar at the top) and requires using task manager to kill.

**Comment by endrift** [comment]
0.8 is very old. I cannot support it, please upgrade to a newer version and retest.

**Comment by endrift** [comment]
Also that commit doesn't exist in mGBA. You appear to be using an unsupported fork.
