### ISSUE TITLE
CMake Error - i dont know the directory for the libraries

### ISSUE THREAD

**Issue by m4mfr3d** [mgba-emu/mgba#2427]
Hello, 

its not an issue in the code. 
I can't find any information about the not included libraries.

If i run "cmake -DCMAKE_TOOLCHAIN_FILE=../src/platform/psp2/CMakeToolchain.vitasdk ..", i get these errors:

CMake Error at src/platform/psp2/CMakeLists.txt:40 (add_executable):
  Target "mgba.elf" links to target "BZip2::BZip2" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at src/platform/psp2/CMakeLists.txt:40 (add_executable):
  Target "mgba.elf" links to target "LibLZMA::LibLZMA" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at src/platform/psp2/CMakeLists.txt:40 (add_executable):
  Target "mgba.elf" links to target "OpenSSL::Crypto" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

I know, i have to download the libraries (source code i think ?) but in which folder do I have to put the libraries?
And how do the libraries folders have to be named.

My system: Ubuntu 20.04 (vitasdk is already installed)

I hope its not a dumb question.
Please help me :pray:

**Comment by endrift** [comment]
cmake . -DUSE_LIBZIP=0
