### ISSUE TITLE
Saving GBA Real Time Clock state inside save data file

### ISSUE THREAD

**Issue by lesserkuma** [mgba-emu/mgba#2431]
Similar to MBC3 on Game Boy, the RTC state of Game Boy Advance games could be synchronized between cartridge and emulator by using added values to the save data file. This would allow for playing on both the cartridge and emulator without the clock messing up when transferring the save data back and forth.

Things can easily get messed up if the emulator always returns the current actual time instead of a synchronized RTC state. Unlike Boktai games, the Pokémon games do not set RTC values to the actual date and time but instead use an offset to the currently seen RTC values at time of creating a new save file.

Saving and restoring RTC state is currently supported by the GBxCart RW cart reader with the FlashGBX software. 0x10 bytes are added to the end of the save file. The format mostly uses the raw values of the cartridge’s RTC component and adds a timestamp:
```
04 05 31 01 97 14 15 01 A4 95 F2 61 00 00 00 00
                        ↑---------------------↑ 64 bit little endian timestamp
                     ↑↑ 24h Flag (usually 01)
                  ↑↑ Seconds in BCD format
               ↑↑ Minutes in BCD format
            ↑↑ Hours in BCD format (+0x80 if post meridiem)
         ↑↑ Weekday index (on Boktai: 00 = Sunday, 06 = Saturday)
      ↑↑ Days in BCD format
   ↑↑ Months in BCD format
↑↑ Years in BCD format
```
This example resolves to RTC state 2004-05-31 17:14:15 (Monday) with timestamp 1643288079.

When loading a save data file with these extra values, the software can calculate the number of seconds passed since the 64 bit timestamp and adjust the RTC values.

**Comment by profi200** [comment]
I would personally store the RTC time and date in a separate file. I'm about to implement this for open_agb_firm because it seems there are games not happy at all with the RTC jumping right to the current date and time when the game expects something else. I would like to have one format most emulators and other solutions could agree with.

Note:
There is some additional complexity for me because the hardware on 3DS uses weirdly formatted date and time offsets. See below:
https://problemkaputt.de/gbatek-3ds-config-arm7-registers-gba-nds-dsi-mode.htm

HEX_TIME and HEX_DATE is actually what stores the offsets and flags.

**Comment by endrift** [comment]
@profi200 What games?

**Comment by lesserkuma** [comment]
Oh yes, we should definitely find a solution everyone can agree with. Btw. I chose to do it in the same file because I understand .sav files to hold the complete state of a game cartridge’s variable data. Just like MBC6 .sav files include both the SRAM data and the 8M flash memory data, resulting in a 1,081,344 byte file. Or like MBC3 where RTC register values are also appended at the end. I figured since save data and RTC state are linked together, they shouldn’t be separated.

**Comment by profi200** [comment]
@endrift 
Quoting from my notes:
> 39  | 1908    | Game requires Flash 1m with RTC. Oddly the maximum year selectable is 2010. Unplayable without proper RTC offset implementation.

That's "1908 - Sennen Kazoku (Japan)". The game will just spam (almost) endless events on next boot when the time and date jumps ahead. Some Pokemon ROM hacks are also not happy displaying the wrong time.

**Comment by endrift** [comment]
ROM hacks are their own bundle of mess and shouldn't be expected to do things right.

**Comment by profi200** [comment]
Yes but technically they are not in the wrong using the hardware how it's supposed to be. A RTC is a RTC.

Anyway, on the weekend i will test a first implementation of RTC offsets to see if the hardware works the way i think it does. Then we can see if we can work out a format that fits all purposes.
