### ISSUE TITLE
Pokémon Jade Version (SA7 bootleg) refuses to boot after BIOS

### ISSUE THREAD

**Issue by AlexField442** [mgba-emu/mgba#2435]
The bootleg game _Pokémon Jade Version: Special Pikachu Edition_ (a hack of _Sonic Adventure 7_) refuses to load after the BIOS screen; also seems to crash after Level 1 on hhuggba, although this could also be a bug with the game itself.

**Comment by endrift** [comment]
This appears to use the NT (newer) mapper, which I don't believe mGBA supports yet. The NT bootleg mappers are on the roadmap for 0.10, though.

**Comment by AlexField442** [comment]
Makes sense, also probably explains why it doesn't work on most flash carts (trust me, Redhotsonic tried).
