### ISSUE TITLE
3DS (BLOCKED: Needs Info): Arm11 prefetch aborts when booting Test Drive 6 GBC and Hello Kitty no Cube Frenzy GBC and Mario Tennis GBC roms

### ISSUE THREAD

**Issue by qahellokitty5947** [mgba-emu/mgba#2438]
I'm running Luma3DS. The game was most likely cause of the error at boot. This happens with both games:

> Test Drive 6: After Infogrames logo, the game will CRASH instant.
> Hello Kitty no Cube Frenzy: Crashes after loading level.
> Mario Tennis: Before starting the intro, the game will give an ARM11 error.

So you want to fix this issue? Thanks @endrift and @mgba-emu.

**Comment by endrift** [comment]
What do you think "blocked: needs info" means?

**Comment by endrift** [comment]
I can't reproduce any of these crashes. There is probably something wrong with your 3DS.
