### ISSUE TITLE
Remove prebuilt files from the tarball

### ISSUE THREAD

**Issue by sergiobenrocha2** [mgba-emu/mgba#244]
Hey endrift!

Is it possible to remove binary files from the tarball, like this:

src/third-party/zlib/contrib/dotzlib/DotZLib.chm

https://lintian.debian.org/tags/source-contains-prebuilt-ms-help-file.html

**Comment by endrift** [comment]
Hmm I don't really want to mess with anything in the third-party folder, just so I can drop in new versions without having to remember what I did to mess with them each time. If it's something that lintian can detect, it might be fine though.

**Comment by endrift** [comment]
Is this still needed?

**Comment by sergiobenrocha2** [comment]
Not really. I had to delete zlib and libpng folders in the packaging... closing.
