### ISSUE TITLE
WINDOWS: mGBA crashes when booting Dai-mahjong. (Japan) ROM

### ISSUE THREAD

**Issue by qahellokitty5947** [mgba-emu/mgba#2440]
The game will throw an "Jumped to invalid address: FE080ADE" error after GBA bios.

### View for Screenshots here ;)
![bandicam 2022-02-07 21-56-50-597](https://user-images.githubusercontent.com/99000291/152870977-335e02cf-806e-49c3-85b8-51dc85e31261.jpg)

Thanks @endrift and @mgba-emu.

**Comment by endrift** [comment]
You almost certainly have a bad dump. Stop filing issues for this game.
