### ISSUE TITLE
0.9.3 - Hamtaro Ham-Ham Heatbreak - New Game and Load stuck during screen transition

### ISSUE THREAD

**Issue by Dawnblairr** [mgba-emu/mgba#2442]
When loading a file or starting a new game the screen is blacked out with this shrinking circle, but it's getting stuck about halfway through the transition (see screenshot). The music continues to play and the background continues to animate. 
First noticed this in Retroarch on a raspberry pi 4, but checked the latest release on my PC (Windows 11) and the same bug is present.

![image](https://user-images.githubusercontent.com/857345/153658360-e785f403-628e-40c8-aabf-e04c919f3c35.png)

**Comment by endrift** [comment]
Dupe of #2131
