### ISSUE TITLE
Large 2D sprites that use a tile index close to the right edge should wrap without advancing to next row

### ISSUE THREAD

**Issue by velipso** [mgba-emu/mgba#2443]
If a sprite is 16x8, and set to tile index 63, then the right half of the sprite should be taken from tile index 32.  However, mGBA pulls from tile index 64.

I've included a small test ROM.  On mGBA 0.9.3-0.10, it will display a white+red sprite, but on hardware it displays a white+green sprite.

[obj.gba.zip](https://github.com/mgba-emu/mgba/files/8054728/obj.gba.zip)

**Comment by velipso** [comment]
This fixes the test ROM... there's probably a better way to do this by having `charBase` mean the start of the row.  I also have no clue how to fix the GL renderer, or deal with other sprite cases (256, windowing, etc).  At least it's a start:

```
diff --git a/src/gba/renderers/software-obj.c b/src/gba/renderers/software-obj.c
index 3fb364f56..371a95957 100644
--- a/src/gba/renderers/software-obj.c
+++ b/src/gba/renderers/software-obj.c
@@ -74,7 +74,7 @@
 #define SPRITE_YBASE_16(localY) unsigned yBase = (localY & ~0x7) * stride + (localY & 0x7) * 4;
 
 #define SPRITE_DRAW_PIXEL_16_NORMAL(localX) \
-	LOAD_16(tileData, ((yBase + charBase + xBase) & 0x7FFE), vramBase); \
+	LOAD_16(tileData, ((((charBase & ~1023) + yBase + (((charBase & 1023) + xBase) & 1023)) & 0x7FFE)), vramBase); \
 	tileData = (tileData >> ((localX & 3) << 2)) & 0xF; \
 	current = renderer->spriteLayer[outX]; \
 	if ((current & FLAG_ORDER_MASK) > flags) { \
```

**Comment by endrift** [comment]
Do you have a repro for 256 color sprites? It'd be nice to have one for both

**Comment by velipso** [comment]
sure, here you go, I modified the original to have both 16 and 256 color sprites... mGBA displays white+red, but hardware displays white+green.

[obj.gba.zip](https://github.com/mgba-emu/mgba/files/8858025/obj.gba.zip)

**Comment by endrift** [comment]
Perfect, thanks. I have a patch prepared, but I'm testing it to make sure it doesn't break anything. I noticed that this does *not* apply to 1D-mapped sprites, only 2D-mapped, which makes a lot of sense, so I'm glad I checked.
