### ISSUE TITLE
mGBA 3DS does not update the file timestamp (.sav)

### ISSUE THREAD

**Issue by HumanixSaektati** [mgba-emu/mgba#2444]
**Files**

https://github.com/mgba-emu/mgba/commit/9cfa7120b186b125406a850d373d86e5be40a7bd

[Please don't link to ROMs]

https://datomatic.nointro.org/index.php?page=show_record&s=23&n=1003

**Description**
The game is made so that it saves automatically, I do not have to save extra, as in Pokemon games. Just win or lose a duel and then it should be saved automatically.
When I start this game and play for a few minutes the file timestamp (Date Modified) is not updated. The **.sav** file I mean.

Started the game for the first time, it automatically creates a .sav file:
Date Created: 15 Feb 2022 03:00
Date Modified: 15 Feb 2022 03:00

A few minutes played:
Date Created: 15 Feb 2022 03:00
Date Modified: 15 Feb 2022 03:00

**Description 2**
If I do the same with mGBA Windows version there are no problems, I immediately see in File Explorer that the timestamp is updated.

Started the game for the first time, it automatically creates a .sav file:
Date Created: 15 Feb 2022 03:00
Date Modified: 15 Feb 2022 03:00

A few minutes played:
Date Created: 15 Feb 2022 03:00
Date Modified: 15 Feb 2022 03:05

**Comment by HumanixSaektati** [comment]
@endrift 
https://github.com/mgba-emu/mgba/commit/a1945cb57a9015f08770e9d572265df25c27bba4

Hi I tested it again and it does not work, the **.sav** file is not updated (file modification time).
Date Created: 15 Feb 2022 03:00
Date Modified: 15 Feb 2022 03:00

Autosave state and Autoload state are Off.

**Comment by HumanixSaektati** [comment]
Here are the results of the mGBA Windows version (https://github.com/mgba-emu/mgba/commit/a1945cb57a9015f08770e9d572265df25c27bba4) with this GBA rom.

1) Started the game for the first time, it automatically creates a .sav file:
Date Created: 15 Feb 2022 03:00
Date Modified: 15 Feb 2022 03:00

2) A few minutes played:
Date Created: 15 Feb 2022 03:00
Date Modified: 15 Feb 2022 03:05

3) Exit mGBA:
Date Created: 15 Feb 2022 03:00
Date Modified: 15 Feb 2022 03:05

4) Open mGBA and open the same game:
Date Created: 15 Feb 2022 03:00
Date Modified: 15 Feb 2022 03:05

5) Click on Continue:
![Yu-Gi-Oh! - Worldwide Edition - Stairway to the Destined Duel](https://user-images.githubusercontent.com/98705868/154814917-210bb982-303e-44c7-b22f-215257925fa5.png)

6) After Continue the .sav file is updated:
Date Created: 15 Feb 2022 03:00
Date Modified: 15 Feb 2022 03:07

7) Exactly this behavior does not work in mGBA 3DS.

**Note:**
Under point 4 it is important that mGBA 3DS does not update the .sav file when only the game is opened, because many forget this point.

**Comment by endrift** [comment]
As weird as this sounds, I haven't been able to confirm this is even possible. The 3DS has a function to update the timestamp when writing to a file, but it doesn't seem to...work. I am unsure under what circumstances the update time is actually updated, but Nintendo seems to have left bugs in their filesystem driver for cases where it's _supposed_ to work already.
