### ISSUE TITLE
Weird audio artifacts or "ticks"

### ISSUE THREAD

**Issue by LOuroboros** [mgba-emu/mgba#2445]
Title.
I'm noticing strange "ticks" in the different music tracks of Pokémon Emerald.
At first I thought this was a result of implementing a custom mixer created by **[Ipatix](https://github.com/ipatix)**, but then I noticed it was also happening with a clean ROM of Pokémon Emerald.

https://user-images.githubusercontent.com/4485172/154258622-6f212f80-b1b8-4ed2-a071-c4f08020a121.mp4

Pay close attention to moments such as 00:05, 00:10 to 00:13, 00:18 to 00:20, 00:35 and 00:36, 00:42 to 00:45, and also 00:47 by the end of the video just before I cut it off.

This is not caused by ShareX, the program I recorded the video with, btw. It happens even without recording.
Also, I'm using mGBA v0.10-7265.

Here's my config.ini and qt.ini files, reformatted to .txt because GitHub doesn't like .ini files, in case they can be useful.
[config.txt](https://github.com/mgba-emu/mgba/files/8079614/config.txt)
[qt.txt](https://github.com/mgba-emu/mgba/files/8079615/qt.txt)

**Comment by endrift** [comment]
This sounds like audio artifacting from samples being dropped or duplicated. Can you use the built-in recording feature to confirm if it's still present in those recordings?

**Comment by LOuroboros** [comment]
> This sounds like audio artifacting from samples being dropped or duplicated. Can you use the built-in recording feature to confirm if it's still present in those recordings?

They seem to be. Check around 00:20: https://www.dropbox.com/s/d1yhosqwqmx1jvz/mGBA.mp4?dl=0

***Note**: I had to drop a download because for whatever reason, GitHub is not visualizing it in the preview. It's like the resultant video, despite being a .mp4 video, is not compatible or something.*

I used the Lossless Quality and the Native Resolution Preset options, in case that matters.

**Comment by endrift** [comment]
I'm not able to notice it this time, though that might just be me.

**Comment by LOuroboros** [comment]
> I'm not able to notice it this time, though that might just be me.

It does feel harder to notice the ticks in mGBA's own recorded footage.

Idk if it matters, but VBA v1.7.2 doesn't have them.

So, what you said earlier, "audio artifacting from samples being dropped or duplicated". What should I do about it?

**Comment by endrift** [comment]
Fiddle with the audio settings. Try the different audio drivers and buffer sizes, mostly.

**Comment by LOuroboros** [comment]
Meaning it's more of a config matter than an issue with either the emulator or the game, correct?

Good to know. Closing this then. Thanks for your help :eyes:
