### ISSUE TITLE
window freezes upon pausing after unbounded fast-forward

### ISSUE THREAD

**Issue by Dsm0** [mgba-emu/mgba#2447]
I'm on Manjaro (linux), latest version of mgba.

Whenever I fast-forward and then pause, the window freezes up for a while. The time it freezes for is variable, but tends to be at least 15 seconds long.

I'll gladly post more info if people ask.

**Comment by endrift** [comment]
Please attach the bug report zip from the Report Bug dialog

**Comment by Dsm0** [comment]
> Please attach the bug report zip from the Report Bug dialog

forgot, sorry.
here it is:
[mgba_bug_report.zip](https://github.com/mgba-emu/mgba/files/8084783/mgba_bug_report.zip)

**Comment by Dsm0** [comment]
addendum: this only happens on *unbounded* fast-forwarding

**Comment by endrift** [comment]
Does this reproduce with 0.9.3? 0.9.2 had some freezing bugs with fast forwarding that were fixed.

**Comment by endrift** [comment]
Closing due to lack of reply.
