### ISSUE TITLE
Doesnt work on windows... requires hole in the wall vista+

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [mgba-emu/mgba#245]
could you guys do something right and make it runnable on windows?
also would be nice to have downloads avaliable just for the library part of it...
without all the junk that comes included.... 

i will try to compile it myself... but i think i will regret even trying
since it will want to force me to download a bunch of useless dependencies...

**Comment by endrift** [comment]
already works on Windows unless you're a fossil

**Comment by taisel** [comment]
Darn, there goes my hopes of OS/2 warp support.

**Comment by MyTDT-Mysoft** [comment]
well if it could work on windows i wouldnt be posting this :)
