### ISSUE TITLE
mGBA keeps freezing after two minutes of running

### ISSUE THREAD

**Issue by FgThRngd** [mgba-emu/mgba#2457]
I was trying to play Pac-Man Collection for speedrunning but after a few minutes of playing, the application just freezes for no reason and I have to close it. Do I need to get a newer version or is it a recording software issue. I use OBS for recording.

**Comment by endrift** [comment]
If you're using 0.9.1 or 0.9.2 you'll need to update to 0.9.3. You should usually put the version of the software you're using in a bug report.

**Comment by FgThRngd** [comment]
I'm sorry. I use 0.9.1 currently. Thanks for the advice though

**Comment by endrift** [comment]
Yeah, there were freezing bugs fixed in 0.9.2 and 0.9.3. Please upgrade and retest.
