### ISSUE TITLE
monitor(s) go black for a couple of seconds and OBS stops recording after (mgba 0.9.3)

### ISSUE THREAD

**Issue by Qpalz98** [mgba-emu/mgba#2458]
I had an issue come up (only with mgba 0.9.3) which actually makes running games (Pokemon LeafGreen in my case) impossible, namely: 

After a random amount of time, both my monitors would go black for a couple of seconds, making the OBS recording of the run freeze.  

I had this happen around 45 minutes in, but also between 4 - 20 minutes. I tried everything i could to fix the issue: updating my drivers, updating OBS, switching around video drivers in mgba itself, but nothing worked.

I tried running the game with mgba 0.9.2, and the freezing issue didn't occur even once

**Comment by endrift** [comment]
That sounds like your graphics driver crashing. What's your graphics card and driver version? And can you upload the ZIP from the Report Bug dialog?

**Comment by Qpalz98** [comment]
Not sure why, but my device manager shows 2 graphic cards:
- Intel HD Graphics 530, version: 27.20.100.8854
- NVIDIA Quadro M1000M, version: 27.21.14.5296

ZIP from Report Bug Dialog: [bug report.zip](https://github.com/mgba-emu/mgba/files/8123384/bug.report.zip)

**Comment by endrift** [comment]
Your graphics driver is over a year old. Please update and see if that fixes it:

- Nvidia driver: https://www.nvidia.com/Download/driverResults.aspx/186958/en-us
- Intel driver: https://downloadmirror.intel.com/691496/igfx_win_101.1191.exe
