### ISSUE TITLE
[3DS] Audio stuttering and low frame rate

### ISSUE THREAD

**Issue by HumanixSaektati** [mgba-emu/mgba#2460]
https://datomatic.nointro.org/index.php?page=show_record&s=23&n=1359

https://github.com/mgba-emu/mgba/commit/64d8dd1b6967ba8cf610444a621b6fbaa434011c

**Description**
Start the game with mGBA 3DS and make a duel. Then comes audio stutter and low frame rate (48 fps - 50 fps).

mGBA Windows has no problems getting constant 60 fps and no audio stutter.

**Comment by HumanixSaektati** [comment]
> The 3DS is just slow. Especially the old 3DS. Not a bug, just insufficient hardware.

https://buildbot.libretro.com/nightly/nintendo/3ds/
https://buildbot.libretro.com/nightly/nintendo/3ds/2022-02-27_RetroArch_cia.7z

When I test with RetroArch 3DS and gpSP Core there are no problems. It has constant 59 fps and no audio stuttering, when I open and close the menu it also stays at 59 fps. With mGBA 3DS it happens very often when I open and close the menu during the game, then mGBA 3DS shows unrealistic fps values like, 200 fps to 1000 fps for a short moment, a bug I guess. Also mGBA 3DS file browser view is not optimized for the 3DS bottom screen. 

Can you fix these problems and optimize the performance?

**Comment by endrift** [comment]
gpSP is faster because it's significantly less accurate. You can point to it and say it's possible but I can tell you that it doesn't matter because there are significant detriments that come along with that. mGBA is already extremely optimized compared to any other accurate GBA emulator.

**Comment by profi200** [comment]
mGBA will probably never run fullspeed on 3DS with all games. Its just lacking the horsepower to do it while emulating accurately. The only thing that can speed it up significantly is a dynarec (which gpSP uses) but it may make mGBA less accurate.

If you want both accuracy and speed your only option is GBA VC/open_agb_firm which uses the real GBA hardware built into each 3DS.

**Comment by HumanixSaektati** [comment]
> gpSP is faster because it's significantly less accurate. You can point to it and say it's possible but I can tell you that it doesn't matter because there are significant detriments that come along with that. mGBA is already extremely optimized compared to any other accurate GBA emulator.

I understand, but you can fix the other problems? Like file browser view and the unrealistic fps values. Additionally I found another problem, when Savestates is used in the same slot in a row, the current screenshot of the game is not saved immediately. It looks like the mGBA 3DS version has not been up to date. Therefore the question if you are still happy with the mGBA 3DS version or if you have little interest in mGBA project in general?

**Comment by HumanixSaektati** [comment]
> mGBA will probably never run fullspeed on 3DS with all games. Its just lacking the horsepower to do it while emulating accurately. The only thing that can speed it up significantly is a dynarec (which gpSP uses) but it may make mGBA less accurate.
> 
> If you want both accuracy and speed your only option is GBA VC/open_agb_firm which uses the real GBA hardware built into each 3DS.

Yes I tested it, but from the design I do not like it, the performance is very good, but would like to have such a settings design, like mGBA 3DS or RetroArch 3DS. The ability to enable options in settings and decide where to create the save data, for example, in another directory or in the same directory as the game.

In addition, I would like to have this (https://github.com/mgba-emu/mgba/issues/2444) in [open_agb_firm](https://github.com/profi200/open_agb_firm/).

**Comment by profi200** [comment]
I know it's bare bones but maybe i get around to adding a real GUI. The biggest blocker is having no proper GPU acceleration.

As for save file time stamps:
Are they really that important? Do you use some kind of backup software that compares time stamps or something?

**Comment by HumanixSaektati** [comment]
> I know it's bare bones but maybe i get around to adding a real GUI. The biggest blocker is having no proper GPU acceleration.

It would be enough if you make a similar setting as godmode9, only that it is possible to enable and disable options.

> As for save file time stamps:
> Are they really that important? Do you use some kind of backup software that compares time stamps or something?

Yes I use backup programs and generally want to know when the save file was created and last modified.
