### ISSUE TITLE
A bug hides a sprite and change it location

### ISSUE THREAD

**Issue by raulpy271** [mgba-emu/mgba#2461]
I'm trying to execute the following code: 

```asm
INCLUDE "hardware.inc"

SECTION "Header", ROM0[$100]
    jp EntryPoint

    ds $150 - @, 0 ; Make room for the header

EntryPoint:
    ; Shut down audio circuitry
    ld a, 0
    ld [rNR52], a

    ; Do not turn the LCD off outside of VBlank
WaitVBlank:
    ld a, [rLY]
    cp 144
    jp c, WaitVBlank

    ; Turn the LCD off
    ld a, 0
    ld [rLCDC], a

    ; Copy the tile data
    ld de, Tiles
    ld hl, $8000
    ld bc, TilesEnd - Tiles
CopyTiles:
    ld a, [de]
    ld [hli], a
    inc de
    dec bc
    ld a, b
    or a, c
    jp nz, CopyTiles

    ld hl, $9800 ; TileMap area
    ld bc, 1024  ; Tilemap size
FillTileMapLocation:
    ld a, 0
    ld [hli], a
    dec bc
    ld a, b
    or a, c
    jp nz, FillTileMapLocation

    CALL SetupObj

    ; Turn the LCD on
    ld a, LCDCF_ON + LCDCF_BGON + LCDCF_BG8000 + LCDCF_OBJON
    ld [rLCDC], a

    ; During the first (blank) frame, initialize display registers
    ld a, %11100100
    ld [rBGP], a
    ld [rOBP0], a

Done:
    LD C, $FF
    LD B, $FF
    CALL Wait
    CALL ChangePos
    JP Done

ChangePos:
    LD HL, $FE00
    LD a, [HL];  y location
    CP 120
    RET Z ; stop to increment when y == 120
    INC a
    LD [HL], a ; increment the y position
    RET

Wait:
    DEC BC
    LD A, C
    OR B
    CP 0
    JP NZ, Wait
    RET

SetupObj:
    LD HL, $FE00
    LD a, 30; y location
    LD [HL], a
    INC HL
    LD a, 30 ; x location
    LD [HL], a
    INC HL
    LD a, 1 ; tile number
    LD [HL], a
    INC HL
    LD a, 0
    LD [HL], a
    RET

SECTION "Tile data", ROM0

Tiles:
    db $00,$00, $00,$00, $00,$00, $00,$00, $00,$00, $00,$00, $00,$00, $00,$00
    db $7E,$7E, $FF,$81, $FF,$A5, $FF,$81, $FF,$81, $FF,$BD, $FF,$81, $7E,$7E ; Smile face
TilesEnd:
```
This code display a sprite on the screen and move it from the position `y= 30` to `y = 120`. The emulator hides the sprite in some point. I executed the same code in another emulator and this behavior don't happens, so I think that this is a bug, and I don't know where it is. 

The following video show the bug, in the left side is the program running in mgba and in the right it's running in another emulator: [video](https://drive.google.com/file/d/1cwJgpCI59evMTNgRhZu7q1AI5ELq29Nu)

**Comment by endrift** [comment]
Please update mGBA to 0.9.3 and retest. mGBA 0.7.0 is several years old and there have been many, many fixes since then. Please also upload a precompiled ROM; there are several different toolchains with different semantics and I don't know offhand which one this was built against.

**Comment by raulpy271** [comment]
I retested and the bug still remains. The commands that I used to generate the rom files is the following:

```sh

rgbasm -L -o smile.o smile-bug.asm
rgblink -o smile.gb smile.o
rgbfix -v -p 0xFF smile.gb

 mgba-qt smile.gb
```

The attached zip has the ROM file and the asm files used to generete the ROM.

[mgba-bug.zip](https://github.com/mgba-emu/mgba/files/8152603/mgba-bug.zip)

**Comment by endrift** [comment]
The bug is in your code, and the other GB emulator. Your ROM exhibits the same "bug" in SameBoy and BGB too, two of the most accurate GB emulators.
