### ISSUE TITLE
Better graphics for menus in Windows 11

### ISSUE THREAD

**Issue by Jaizu** [mgba-emu/mgba#2462]
![image](https://user-images.githubusercontent.com/18596778/155973685-6fc26a14-d29b-49f7-ad15-6e6693e2bf6b.png)

It would be nice so have something that doesn't look as bad as they look in Windows 11.

Example from Google Chrome menu:
![image](https://user-images.githubusercontent.com/18596778/155973750-d74b2ed8-2a21-4df9-830e-040f21c7ab7c.png)

**Comment by kode54** [comment]
It uses the stock Qt menu controls. What do you want, to rip the custom menu code out of Chromium?

**Comment by endrift** [comment]
Simmer down, kode. They don't need to know anything other than "it looks bad" to file a bug. Unfortunately, if it's rendering wrong that's either a Qt bug or Windows 11 being garbage at backwards compat. I could go either way, but it can't change without updating to Qt 6, which will probably happen at _some_ point.

**Comment by Jaizu** [comment]
> It uses the stock Qt menu controls. What do you want, to rip the custom menu code out of Chromium?

I want a less asshole reply, to start off.

> Simmer down, kode. They don't need to know anything other than "it looks bad" to file a bug. Unfortunately, if it's rendering wrong that's either a Qt bug or Windows 11 being garbage at backwards compat. I could go either way, but it can't change without updating to Qt 6, which will probably happen at _some_ point.

So I guess we are stuck for a while then. Which version of Qt is mGBA using atm? I use other apps for windows that are Qt based that don't have that problem, so I didn't know. And example could be qBitorrent using QT 5.15.2

**Comment by endrift** [comment]
It should say if you go to the Report Bug dialog, hit generate, and click on the System info tab. On latest dev builds it uses 5.15.2, and I believe it does in 0.9.3 as well.

**Comment by lotharsm** [comment]
FYI, qBittorrent 4.4.1 using Qt 5.15.2 has exactly the same appearance than the menu screenshots shown in the first post. But yeah <rant>Windows 11 was a real downgrade regarding the menus. Most of the time they simply look weird</rant>.

**Comment by Jaizu** [comment]
I have no idea if this is a fix by mGBA or Windows 11, but it seems to be way better now -and it's been for a while I think-
![image](https://user-images.githubusercontent.com/18596778/222887036-379f6ea3-59d3-40f8-8f1c-751d58075006.png)

**Comment by endrift** [comment]
I don't think I changed anything, but I might have updated Qt. Seems I can close this now, regardless.
