### ISSUE TITLE
Where do you find the index.html???

### ISSUE THREAD

**Issue by MonnM** [mgba-emu/mgba#2466]
There is a bunch of folders and i cant find where you open the emulator. Can anyone help??

**Comment by endrift** [comment]
...? Index.html? There is none. It's a program. Why would there be an index.html?

**Comment by MonnM** [comment]
isnt it supposed to be a html game?

**Comment by endrift** [comment]
No? I have no idea where you got that idea.

**Comment by MonnM** [comment]
on youtube

**Comment by endrift** [comment]
Please link to the video in question.
