### ISSUE TITLE
Fast-forward + mute shortcut?

### ISSUE THREAD

**Issue by Darkmaster006** [mgba-emu/mgba#2467]
Hello there, thank you for all the work on this emulator, after I found this one, I left any others for good, it's just excellent. I was just wondering if it could be possible to add a 'fast-forward + mute' shortcut, I say this because, I'm playing Pokemon, and I speed up in fights and stuff, and when I speed up the sound gets... pretty annoying as it's all broken up by the speed, hence I mute it sometimes when it's sped up, but it'd be nice to have it done both at once. Anyways, just a little feature request, thanks!

**Comment by endrift** [comment]
There's already a setting to just have mute on while fast-forwarding. Settings > Emulation I believe.

**Comment by Darkmaster006** [comment]
> There's already a setting to just have mute on while fast-forwarding. Settings > Emulation I believe.

Thank you, I vaguely remembered there was a setting like this when you mentioned it. It seems to be in 'Audio/Video' in Settings, though, where you have to set 'Fast Foward Volume' to '0'.
