### ISSUE TITLE
Entire program freezes when resetting emulation in debugger break mode

### ISSUE THREAD

**Issue by SonoSooS** [mgba-emu/mgba#2468]
Trying to debug why my homebrew jumps to garbage address, I stumbled across this freezing bug while trying to reset while in a break state.

Is it possible to reset while in break state, so emulation breaks on the first branch instruction in the cartridge header?

Steps to reproduce:
- Open debugger console
- Execute a break by typing `b` and ENTER
- Reset from Emulator --> Reset
- The entire program will hard freeze, and will have to be closed from Task Manager

**Comment by endrift** [comment]
You can just type `reset` into the debugger. It'll start in the BIOS.

Anyway, this is definitely a bug.

**Comment by endrift** [comment]
Can you see if this is fixed in 7311-bc9bb43 or newer? https://mgba.io/builds/1/

**Comment by SonoSooS** [comment]
Sorry for the late response!

I absolutely love how you solved this issue! I can just click Reset, and the next instruction will be in the BIOS at 0x20!
Even better, if I break before loading a ROM, it will remember the break state, and it'll break in the reset vector! BRILLIANT!

Thank you, it works better than expected.
