### ISSUE TITLE
Galidor: Defender of the Outer Dimension visuals are broken when using the OpenGL 2x Mode 7 upscaler

### ISSUE THREAD

**Issue by Superstarxalien** [mgba-emu/mgba#2471]
title says all
issue is present on builds 0.10-7926-54bccfd2c, 0.10-7289-64d8dd1b6
issue is not present on 0.9.3
![mGBA_yry9sAApX2](https://user-images.githubusercontent.com/8278830/157591113-2e7520de-7083-45b0-9efa-d06f8a3a8143.png)
![mGBA_ERqpQPrugE](https://user-images.githubusercontent.com/8278830/157591781-b33b93b9-c044-4c1e-bf73-0c324f5a7b11.png)
![mGBA_S8bHTmkSyS](https://user-images.githubusercontent.com/8278830/157591851-a80e57fa-83ee-4325-b352-ea2f88b207b0.png)

**Comment by endrift** [comment]
I believe this was fixed in 095481ae2ef26d3e0e5f07cd357a7ecb795a0de1; please retest.

**Comment by Superstarxalien** [comment]
as of 0.10-7299-50e0fe997 the trademark screen and title screen are displayed correctly and so is the game (at least the first level), but parts of the intro fail to display
this screenshot from the intro in 0.9.3 is completely black in 50e0fe997
![imagen](https://user-images.githubusercontent.com/8278830/158278142-81023f82-c099-4bbc-b906-fc97ba6fde88.png)

**Comment by endrift** [comment]
It seems to work properly on my end. Can you upload the bug report zip from File > Report Bug?

**Comment by Superstarxalien** [comment]
so uh as of build 770b121b10ba9ff500e1e8ad946d57b87d8e58dc you can get to see the 2x upscaling both work and not work at all
starting galidor without a save file being made and with 2x upscaling enabled will display the intro properly
starting galidor after choosing a language then restarting the game (by which the game will have a save file) will cause the bug to occur
what's more is that the same happens with 4x upscaling except it only works under more specific conditions:
-Set mGBA's Frame size to 2x
-Start without a save file
failing to do either will make the intro not display properly
[Galidor Bug Report 2x.zip](https://github.com/mgba-emu/mgba/files/8536147/Galidor.Bug.Report.2x.zip) - this one is on 2x Frame size 2x upscaling
[Galidor Bug Report 4x Saved.zip](https://github.com/mgba-emu/mgba/files/8536148/Galidor.Bug.Report.4x.Saved.zip) - this one is on 1x Frame size 4x upscaling
[Galidor Bug Report 4x Saveless.zip](https://github.com/mgba-emu/mgba/files/8536149/Galidor.Bug.Report.4x.Saveless.zip) - this one is on 2x Frame size 4x upscaling
