### ISSUE TITLE
Feature request: Command line option for e-Reader dotcodes

### ISSUE THREAD

**Issue by Zowayix** [mgba-emu/mgba#2474]
Discussed this on the Discord like 2 years ago and should have filed an issue about it but I forgot, and only realised 2 years later that I forgot.

For the purposes of integrating e-Reader stuff with frontends, I want to be able to specify e-Reader dotcode files from the command line (presumably along with the e-Reader ROM) using the batch scanning feature, so something like:
`mgba-qt e-Reader (USA).gba --dotcodes strip1.raw strip2.raw strip3.raw`

Or perhaps `--dotcode strip1.raw --dotcode strip2.raw1` etc if that's how parsing command line arguments works.

And then ideally one would then select Scan Card and it automagically scans all the cards, as though they were opened from the file menu. Bonus points if there is a way to avoid having to autofire/mash A to get through all the cards (having it automatically press the button when it's done scanning), though that might be another story and not entirely possible any time soon.

Bonus points if it would be possible to load an m3u file containing paths to multiple e-Reader dotcode files instead.

**Comment by endrift** [comment]
This is feasible, minus the bonus. It'd be the latter syntax.

**Comment by endrift** [comment]
Ended up going with `--ecard`, which you can specify multiple times. It will also recursively attempt to scan the paths presented in a file if it looks like an m3u, as requested.
