### ISSUE TITLE
MGBA Isn't opening after downloading it

### ISSUE THREAD

**Issue by RedT6591** [mgba-emu/mgba#2479]
When I downloaded MGBA I tried to open the application and it didn't run at all, if you can't figure out this issue is there a different gba emulator I can use?

**Comment by endrift** [comment]
Going to need more information, like which system you're trying to run it on (mGBA runs on a broad variety of systems), where you downloaded it from (to make sure you have an up-to-date official build), what your CPU and GPU are if you're on a PC, and really anything else you can think might be relevant.

**Comment by RedT6591** [comment]
I'm trying to run mGBA on my Lenovo Laptop, and I downloaded it from the mGNA website from the windows option, my windows is update and I'm not sure why it isn't opening because my ds emulator works on it.

**Comment by Testsr** [comment]
Try using the portable version at https://github.com/mgba-emu/mgba/releases/download/0.9.3/mGBA-0.9.3-win64.7z
You will need 7zip to open it.

**Comment by endrift** [comment]
I assume you're on Windows? Lenovo is a brand, not an OS. Further, which file did you download? What did you try to do once downloading it? I still have next to no info.

**Comment by endrift** [comment]
Closing due to lack of reply.
