### ISSUE TITLE
"Gejmbåj" demo isn't fully working

### ISSUE THREAD

**Issue by waddlesplash** [mgba-emu/mgba#248]
pouët: http://www.pouet.net/prod.php?which=56367
YouTube: https://www.youtube.com/watch?v=QyvBNhzshKQ

Author recommends real hardware but strongly recommends the BGB emulator otherwise.

AFAICT, the entire demo works properly on mGBA except for the "vertical twisting things" (0:37 in YT video) scene.

**Comment by endrift** [comment]
Fixed in 7539742689990be0687f82b19d3bc9b312ed528d.
