### ISSUE TITLE
Ability to load debug info from an external file?

### ISSUE THREAD

**Issue by EvilJagaGenius** [mgba-emu/mgba#2480]
I work on a fork of the Goomba Color GB/C emulator for GBA and use mGBA to test my builds.  However I don't have a good way to debug it.  When I compile, I come out with a .gba and .elf file as per normal, and Goomba Color works by concatenating ROMs to the end of the .gba file.  When I try to do the same thing and build a test ROM with the .elf file, the emulator doesn't detect any ROMs.

Would it be possible to add a debugger command to load debug info from an external .elf file, like GDB does with its add-symbol-file and symbol-file commands?  Then I could build a working test ROM and have all my function/variable names in the debugger too.

Thanks!

**Comment by endrift** [comment]
It should autoload .elf symbols if there is an .elf in the same directory with the same filename. However, I can add a manual loading command.
