### ISSUE TITLE
[libretro port] Rumble causing emulation slowdown

### ISSUE THREAD

**Issue by shinji257** [mgba-emu/mgba#2482]
Device: Retroid Pocket 2+
Version: RetroArch/LibRetro 1.9.14 - 0.10-dev 5d48e07
Game: Drill Dozer (GBA, English)

I apologize if this is a duplicate.  I did a quick search and didn't see one but discussing with another individual suggested this is a common issue as they get it with Pokémon Pinball.

When playing the game with Rumble turned on (toggling in game is enough) it slows down by up to 25% when the rumble motor is actively engaged.  I don't see this kind of slowdown on other emulators.  If I disable the rumble feature, there is no more slowdown, but the game isn't really the same after that.

**Comment by endrift** [comment]
Does the same behavior exist in other emulators with rumble, e.g. N64 with the Rumble Pak or PS1 with DualShock? You said other emulators but didn't specify if it was limited to emulators with rumble or not.

**Comment by shinji257** [comment]
No it does not happen with other emulators. Tested with Duckstation and Mupen64 FZ on

**Comment by Takiiiiiiii** [comment]
Can confirm this issue only happens with RA cores.

**Comment by endrift** [comment]
That sounds like a bug with RA then. I've been able to reproduce it, but afaik it's not a bug on mGBA's side.
