### ISSUE TITLE
When i try to run Conker's Pocket Tales in gb mode mgba loads gbc version.

### ISSUE THREAD

**Issue by kotenok2000** [mgba-emu/mgba#2486]
I have changed extension to .gb, but mgba still loads gbc  version.
Wikipedia says that rom should be able to work in gb mode.
I am using https://github.com/mgba-emu/mgba/releases/download/0.9.3/mGBA-0.9.3-win64.7z
https://en.wikipedia.org/wiki/Conker%27s_Pocket_Tales#:~:text=The%20cartridge%20is%20dual%2Dformat%2C%20allowing%20it%20to%20also%20run%20on%20the%20original%20Game%20Boy%20with%20some%20gameplay%20differences.

**Comment by endrift** [comment]
This is not a bug in mGBA. The file extension is ignored. To force it to GB mode, you need to either use the override view to force the model to Game Boy before loading the game, or going to settings and changing the GB + GBC model to GB (DMG).
