### ISSUE TITLE
[OpenGL] Diagonal line of corrupted pixels in Golden Sun 1 & 2

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2491]
This bug shares some similarities with #2262, but the corruption is different. As I'm not sure if it's the same bug, I decided to send it as a different issue. If you consider this issue a duplicate, you can delete it

**Details:** When using OpenGL mode with any resolution, several corrupted pixels distributed diagonally appears on screen when you boot certain games (for now, only Golden Sun 1&2) for the first time.

The issue disappears if you reset the game, if you change the resolution or graphical modes, if you boot another game first.

Apparently, this issue only affects AMD cards: I can only trigger it by booting mgba with my iGPU Radeon (w/OEM Drivers), whereas my RTX 2060 is immune.

**GS2 x1:**
![GOLDEN_SUN_B-2](https://user-images.githubusercontent.com/16591467/161165569-160d5096-f43a-4683-98bc-d9c1a9650385.png)
**GS1 x1:**
![Golden Sun (Spain)-0](https://user-images.githubusercontent.com/16591467/161165582-42f38257-6165-43cc-af13-09770af7191c.png)
**GS1 x6**
![Golden Sun (Spain)-0](https://user-images.githubusercontent.com/16591467/161421934-aaad8087-19ce-44c9-9dbb-7a346ae80f9c.png)

Since the issue only happens during the first time I boot a game, I wonder if there's something wrong with the mGBA's OpenGL mode initiation or how AMD driver manages the initiation.

Build:
0.10-7305-1dcdf14fb win64

Specs:
Laptop legion 5 15arh05h (82b1)
CPU: AMD Ryzen 7 4800H @ 2.9-4.2 GHz (8/16)
GPU: NVIDIA GeForce RTX 2060 @ 6GB @ 120hz + Radeon iGPU* (OEM Driver VGA_27.20.11028.5001_ACP_2.89.0.59)
RAM: 16 GB @ DDR4
OS: Windows 10 x64

*Note: The iGPU is a Radeon RX 5500M or a Radeon Graphics 448SP. Neither Windows nor AMD want to tell me its name, identifying as just "Radeon".

**Comment by endrift** [comment]
It's funny because I've seen this bug before, but thought I fixed it ages ago.

**Comment by RafaelTrepaUnCarballo** [comment]
Quick note: The issue continues after updating my OEM drivers to the latest official AMD drivers (Adrenaline 22.3.2) (21.50.19.01-220322a-377867E-AMD-Software-Adrenalin-Edition).

So it's not a driver bug **exclusive** of the OEM Lenovo drivers (which currently are 1 year old). Either it's a bug of all AMD drivers, or it's mgba.

**Comment by endrift** [comment]
Is this still an issue with latest drivers? It's definitely an AMD driver bug, but I can't reproduce it on my AMD desktop--it's a much newer GPU though.

**Comment by RafaelTrepaUnCarballo** [comment]
The bug seems fixed with latest AMD driver and mgba 0.11-8489-eb1b5718c
