### ISSUE TITLE
[Linux Build] Can't build with OpenGL (no GLES) since about January

### ISSUE THREAD

**Issue by Silver-D** [mgba-emu/mgba#2492]
Hello! I am no longer able to build mgba from git on Fedora since about the start of the year. The commit that broke it was b6e2faaba9106ffd3f7dbf378f145451188f47f9 in qt/DisplayGL.cpp,  void PainterGL::create() { on line 454 at the time of that commit.

This is the build error: 
![image](https://user-images.githubusercontent.com/6107417/161445012-c2060cff-2d74-4e7a-893c-730ef2f749f4.png)

I do not have GLES2/3, I have mesa-libEGL-devel (from SDL2-devel and qt5-qtbase-devel), and the mesa-libGL which it links against.

The revision tries to use GLES without checking if GLES is available.

This is my cmake line: `cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DBUILD_GL=yes -DBUILD_GLES2=no -DBUILD_GLES3=no`

OpenGL is found by cmake and is reporting `OpenGL support: OpenGL`

Thank you!

**Comment by endrift** [comment]
It should be noted that calling it OpenGL|ES 2/3 in this context is misleading (on my part) because it just means OpenGL 2.1 or OpenGLES 2/OpenGL 3.3 or OpenGL|ES 3. I've fixed the build though.
