### ISSUE TITLE
Fast-forward inconsistency when using OpenGL renderer

### ISSUE THREAD

**Issue by Shideravan** [mgba-emu/mgba#2493]
When i start the fast-forward, it runs until the desired speed (eg.: 2x as selected)
After few seconds, the sound keeps fast, but the game speed drops to something like the normal game speed.
I'm using latest Windows x64 build, with sync in audio active (but I already tried to turn on and off audio and video sync and the problem persists).

Expected behavior: when selecting x2 for fast-forward, when I keep <Tab> pressed, the game would runs at that speed.

Computer Specs:
Windows 10 x64
16 GB RAM
i7-4790
Geforce 1070

**Comment by endrift** [comment]
This is a known issue when using the OpenGL renderer (under enhancements, not the display driver) that I keep forgetting to fix. Can you check if that's enabled.

**Comment by endrift** [comment]
Can you see if the same issue occurs with both an 0.10 development build (available at the bottom of the download page) and 0.9.3? I'm having trouble reproducing it on dev at the moment but I am anything but convinced it's fixed.
