### ISSUE TITLE
Add More Super Game Boy Borders (For Game Boy / Color Games On SGB Hardware), Add Super Game Boy BIOS (For SGB Hardware, SGB Borders Enabled/ON), Add Extra Sound Effect From Donkey Kong '94

### ISSUE THREAD

**Issue by CraftFan22** [mgba-emu/mgba#2495]
Super Game Boy (USA) Border
![Screenshot_20220410-224152~2](https://user-images.githubusercontent.com/103258834/162639053-f8215e97-a594-43ef-b228-8b304c230b1d.jpg)
Super Game Boy 2 (Japan) Border
![Screenshot_20220410-224157~2](https://user-images.githubusercontent.com/103258834/162639074-052393ce-4913-4f79-9345-5c978dff7e39.jpg)

Add Super Game Boy BIOS

Add Extra Sound Effect From Donkey Kong '94

Super Game Boy Border (Super Game Boy (USA) BIOS)

Super Game Boy 2 Border (Super Game Boy 2 (Japan) BIOS)

**Comment by endrift** [comment]
All of these things require an actual SGB ROM, and many involve emulating components of an SNES itself. This cannot be baked into the emulator.

**Comment by GerbilSoft** [comment]
For what it's worth: This person has been repeatedly spamming multiple emulator GitHub repos with issues like this, including Genesis Plus GX. (in that case, repeatedly demanding TMS mode colors in SMS games) He registers multiple alt accounts every time, including to sockpuppet himself. (In some cases, he registers a sockpuppet to complain about himself, which is unusual.)

**Comment by CraftFan22** [comment]
I'm 14 Years Old, I'm From Europe, I'm Using Android Phones (8.0.0 Oreo Version) With 2GB RAM, I Like Retro Emulators, Minecraft, Mario & More. I'm Used Spamming On Emulator Repository (Include Genesis Plus GX For Bug On **Super Boy I (Korea) (Unl), Super Boy II (Korea) (Unl), Super Boy III (Korea) (Unl)** On **SG-1000** Emulation On Genesis Plus GX Because **SG-1000** Uses **TMS9918,** **Master System / Game Gear** Uses **Dark Colors** **(TMS9918-Compatible, Backward Compatible With SG-1000),** **Mega Drive / Genesis** Uses **Black Display Screen With Audio Sound** On **SG-1000** Games **(Mega Drive / Genesis Has No TMS9918-Compatible).** But Not Bug On **Gearsystem.** I Tested **Gearsystem** On **RetroArch**

On Gambatte For **SGB Enhanced Support**

On FCEUX For **Famicom Expansion (FDS, MMC5, VRC6, VRC7, N163, S5B) On/Off From EverDrive N8, Nestopia UE**

On Snes9x For **Game Boy Support** Because Super Game Boy Exist



Some Retro Emulators For Android Are Unless Because It Contains Ads / Adverts On Free Version, On Pro/Paid Version Doesn't Contain Ads / Adverts.

I Will Use RetroArch When I Have A 4GB RAM & Up Phones. RetroArch Also Works On 2GB RAM, 1GB RAM & More.

**Comment by SteveCraft27** [comment]
@CraftFan22 Wants For Android. But Android Uses Touch Control For Emulators (Requires Transparent). This Is When He Spammed To Genesis Plus GX For KEGA Fusion Not Available On Android. KEGA Fusion Is Closed Scoure.

_________________________________________________

Highly Accurate SG-1000/SMS/GG/MD Emulator (Alternative Of KEGA Fusion):

- **Genesis Plus GX**
- **Gearsystem**
- **SMS Plus GX**
- **blueMSX**
_________________________________________________
