### ISSUE TITLE
Directory problem when using mGBA in portable mode with a front end.

### ISSUE THREAD

**Issue by TomTurbine** [mgba-emu/mgba#2496]
Noticed when using EmulationStation Desktop edition.

When you launch it in portable mode from the front end, it tries to create directories in the folder with the EmulationStation executable instead of with the mGBA executable.

Can just move the bios, saves and all to that directory, but does make it less organized which can drive someones OCD nuts.

**Comment by endrift** [comment]
Windows, I presume?

**Comment by TomTurbine** [comment]
Yes sir, using Windows 10. Sorry for the delayed response.

But yeah, been setting up EmulationStation on it and actually setting up a USB drive with a portable setup for the kids to be able to use too. Noticed it while looking over stuff.

**Comment by endrift** [comment]
I'm having trouble reproducing this. Can you pull up the bug report dialog and generate a report while a game is running from EmulationStation having launched it?

**Comment by endrift** [comment]
I was talking about the report generated by File > Report Bug

**Comment by TomTurbine** [comment]
Ah, my bad. I launched mGBA from EmulationStation and hit the Report Bug while it was running from it. Hopefully this helps.

[Bug_Report.zip](https://github.com/mgba-emu/mgba/files/8516148/Bug_Report.zip)

**Comment by endrift** [comment]
According to this bug report, the config file should be located in F:/EmulationStation-DE/Emulators/mGBA. It claims this is the same directory as the executable. And that's not the config file it uses?

**Comment by TomTurbine** [comment]
Haven't been playing GBA for a bit but the issue was that when you launched it from a front end, it no longer saved the stuff in the home directory of the emulator but instead it saved stuff to the home directory of the front end that launched it.

**Comment by TomTurbine** [comment]
The directory issue seems to be fixed with the newest update, much appreciated.

Tested it with Save games and Save states configured into relative directories inside the mGBA folder and worked perfectly with nothing left in the front ends folder.
