### ISSUE TITLE
GBA Tiles viewer: Clicking on tiles in "Only OBJ tiles" view shows information for BG tiles instead of OBJ tiles

### ISSUE THREAD

**Issue by tgsm** [mgba-emu/mgba#2497]
Build: 0.10-7321-7093d083d, Qt
<details>
<summary>System information:</summary>
<ul>
<li>Operating system: Arch Linux</li>
<li>CPU: i5-6600K</li>
<li>Graphics card: RX 480</li>
</ul>
</details>

This works normally for the "Only BG tiles" and "Both" views, however clicking on a tile in the "Only OBJ tiles" view shows the information for the BG tile that would normally be there at the position clicked.

This was tested with [SFC's Five Finger Discount](https://www.pouet.net/prod.php?which=24571) and Kirby: Nightmare in Dreamland.

![mgba-tiles-bug](https://user-images.githubusercontent.com/11739422/163078095-71b47a8d-556a-46fa-9a83-f18b8131e409.gif)

**Comment by endrift** [comment]
oops, good catch
