### ISSUE TITLE
rumble doesn’t work

### ISSUE THREAD

**Issue by Northwemko** [mgba-emu/mgba#2498]
Drill Dozer, gba player mode Pokemon Pinball etc 0.93 windows version rumble doesn't work
but 0.92 rumble work

**Comment by endrift** [comment]
What controller are you using?

**Comment by Northwemko** [comment]
> What controller are you using?

xinput,xbox360 and xbox one

**Comment by Hexaae** [comment]
Same here. Was fixed long ago (see #2146)

**Comment by Hexaae** [comment]
mGBA 0.11-8612-49bddb92e
Today I played again Pokemon Pinball (GBA), WarioWare (GBA) and Drill Dozer (GBA) with Switch Pro Controller (EasySMX x10).
The only one with working rumble is WarioWare.

(List of GBA games with rumble support: https://consolemods.org/wiki/GBA:List_of_GBA_Games_with_Rumble_Support )

**Comment by endrift** [comment]
This issue is definitely stale; it's been fixed broken and fixed several times in the meantime.
