### ISSUE TITLE
ROM saving error in "Crash & Spyro Super Pack Volume 1 (Europe) (En,Fr,De,Es,It,Nl)".

### ISSUE THREAD

**Issue by MM2WOOF** [mgba-emu/mgba#2499]
I have a saving problem in the ROM of Crash & Spyro Super Pack Volume 1 (Europe) (En,Fr,De,Es,It,Nl), I do not know if in other packs of Crash and Spyros that came out for the GBA have this error but it is that unless I do not disable these options in the Settings the saves of my games so many of Crash N Tranced and Spyro Season on Ice do not appear, and the worst thing is that when I turn off the computer I have to do this procedure again until the saves of both titles of the package appear, I also tried altering the save types in Game Overrides but no. I have not been able to do it. 
![imagen](https://user-images.githubusercontent.com/79426851/163831546-db5d10ec-082e-440f-b59d-b3d2eb252fe0.png)
![imagen](https://user-images.githubusercontent.com/79426851/163833560-0ffddd40-63f5-41f6-bc8a-3b4c9a62e3f8.png)
![imagen](https://user-images.githubusercontent.com/79426851/163831941-5e1127bd-bb5e-4411-a868-8dd656513e2a.png)
![imagen](https://user-images.githubusercontent.com/79426851/163832035-f89c4be6-35d7-414d-9ba1-dfda1ee00adc.png)

**Comment by endrift** [comment]
Those options are all off by default. Please post the bug report zip (File > Report Bug), as I think there's something wrong with how you've set things up. Are you ignoring a dialog box that comes up when you start the game?

**Comment by endrift** [comment]
Closing due to lack of reply.
