### ISSUE TITLE
mGBA not showing a checkmark next to the default FPS target

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#25]
As of the latest nightly (0.3-2082-e787d00 at the time of writing), mGBA will not show a checkmark next to '60' under the 'FPS Target' submenu, even though that's the FPS target it's using by default.

<s>Another thing to note is that the default width and height values included in the config.ini do not correspond to any 'Frame size' option in the mGBA UI and according to @endrift are too big to be defaults (specially the 699 height). Default should be changed to something like 4x, which is 960x480, instead of the 1024x699 that it is now.</s> Fixed by the time 0.3.0 stable rolled around.

OS: Windows 8.1 x64

**Comment by CharlesCorrin** [comment]
Little more: If you select something from the FPS target dropdown, the checkmark will appear. If you then go to Settings, the checkmark will disappear again.

**Comment by karasuhebi** [comment]
I have no idea why I closed this. This is still an issue even on 0.5.2.
