### ISSUE TITLE
"Oh!" by Snorpung is totally busted past title screen

### ISSUE THREAD

**Issue by waddlesplash** [mgba-emu/mgba#250]
```
[STUB] GB I/O:  Writing to unknown register FF4F:00
[STUB] GB I/O:  Writing to unknown register FF68:00
[STUB] GB I/O:  Writing to unknown register FF6A:00
[STUB] GB I/O:  Writing to unknown register FF70:01
[STUB] GB I/O:  Writing to unknown register FF51:FF
[STUB] GB I/O:  Writing to unknown register FF52:FF
[STUB] GB I/O:  Writing to unknown register FF53:FF
[STUB] GB I/O:  Writing to unknown register FF54:FF
[STUB] GB I/O:  Writing to unknown register FF15:00
[STUB] GB I/O:  Writing to unknown register FF1F:00
```

http://www.pouet.net/prod.php?which=54175
https://www.youtube.com/watch?v=dfDXXSCB2Ro

**Comment by endrift** [comment]
Fixed in 98922b7a87f6d18bc0d63bc2fd9db092ee4b8318. It was *extremely* sensitive to the video timings, so it's still a bit fragile and may break again later.

**Comment by endrift** [comment]
Yeah this actually re-broke several releases ago when I fixed mode 2 timing. I haven't put the time into re-figuring out what's wrong.

**Comment by endrift** [comment]
Believe it or not, I have a fix for this in testing.
