### ISSUE TITLE
HiRes Missing gfx in Castlevania - Harmony of Dissonance (U)

### ISSUE THREAD

**Issue by lordmedo** [mgba-emu/mgba#2500]
![Castlevania - Harmony of Dissonance (USA)-1](https://user-images.githubusercontent.com/13256611/164268283-1de7a927-d9e6-452c-a40a-507fe3d67d92.png)
![Castlevania - Harmony of Dissonance (USA)-2](https://user-images.githubusercontent.com/13256611/164268291-a98c7ce6-2cc0-4fd7-8da4-360650e827d9.png)
With high resolution setting set to 2x or more, cut scene text and portraits are missing.
mgba version 0.10-7323-5b7780620
w10x64, gtx960

**Comment by endrift** [comment]
Seems to work on my iGPU. I'll check Nvidia soon.

**Comment by endrift** [comment]
Can you try updating your GPU drivers and seeing if it's fixed?
