### ISSUE TITLE
SGBC Mode: Border Update Trigger Visual Errors

### ISSUE THREAD

**Issue by SoraHjort** [mgba-emu/mgba#2503]
Build: mGBA-build-2022-04-21-win64-7330-770b121b10ba9ff500e1e8ad946d57b87d8e58dc
OS: Win1064
HW: Ryzen 9 3900x / GeForce RTX 2080
Game: Pokemon Clear Crystal 2.5.1 (romhack. Tested both normal and color corrected)

Animated PNG Demonstrating the issue: 
![border_error](https://user-images.githubusercontent.com/18604504/164590663-37b11040-7bc7-4496-91bf-93a89ed292e9.png)

As shown above, in the Pokemon Crystal Clear romhack, when exiting the pokedex, the border bugs out when it tries to update the border. It can be fixed without rebooting by entering and leaving the PC, as well as exiting a battle. 

I have tested it on a fresh save, and it does occur then as well.

This also does not occur in the only other emulator (that I know of) that supports the SGBC mode (that being bgb). 

I suspect that the Pokedex is doing a different type of border update than what mGBA is expecting, since other moments that would also update the border as intended.

Still waiting on a reply from anyone on the CC discord on info on how the romhack handles border updates to provide additional information in relation to this bug. If they do I'll come back and add any additional info they provide that may help make the Super Game Boy Color mode better.

**Comment by SoraHjort** [comment]
Additional info was provided on the issue: 
![image](https://user-images.githubusercontent.com/18604504/164609746-17bc5527-49de-41af-8281-254446c02c9a.png)

**Comment by endrift** [comment]
This is caused by the VRAM transfer routines not clearing the CGB tile attributes before doing the transfer. BGB appears to ignore those when doing a VRAM transfer, but mGBA doesn't. Given that this is CGB-only, the result is not well defined. However, I have to imagine that if SGBC hardware existed, those attributes would not be ignored. I can "fix" this, but it really raises the question of where the bug actually is.

**Comment by CasualPokePlayer** [comment]
> if SGBC hardware existed, those attributes would not be ignored.
The real SGB doesn't have explicit access to VRAM anyways, all it actually has is the video rendered by the GB. That's the whole reason for the "VRAM" transfer, as that's the only bulk data access given to the SNES.

If a real SGBC actually existed it's more likely to use something else over just direct access to VRAM, Hell maybe some DMA with a separate WRAM bank, who knows ¯\_(ツ)_/¯

**Comment by endrift** [comment]
It looks like the palette still messes up when you get a Gym Badge so I guess I have more stuff to look at too

**Comment by endrift** [comment]
Turns out it Crystal Complete also doesn't disable rendering OBJs. I would strongly recommend that the author of the hack disable OBJ rendering before doing a transfer.

**Comment by bea-tsf** [comment]
> Turns out it Crystal Complete also doesn't disable rendering OBJs. I would strongly recommend that the author of the hack disable OBJ rendering before doing a transfer.

Seems like this has been fixed as of 2.5.3 thanks to your suggestion, but the behavior of the SGB border when exiting the Pokedex is still bugged like shown in the OP. The software used for testing was Crystal Clear 2.5.6 (March 30th, 2023) and mGBA 0.10.1 (Jan 10, 2023).

Admittedly, this is a bug on 1. a niche feature 2. in a game that's not even official and that 3. requires an also niche emulator-only SGB+GBC mode. But it might be a pointer to more bugs in the SGB+GBC mode, and as someone who quite likes this emu and uses it across platforms, it'd be lovely to be able to play all of my preferred GBC games on mGBA.
