### ISSUE TITLE
(arch linux) mgba does not launch when launched by either rofi or terminal

### ISSUE THREAD

**Issue by reisscake** [mgba-emu/mgba#2505]
when i launch mgba in the terminal, it comes with an error message:

mgba: error while loading shared libraries: libmgba.so.0.10: cannot open shared object file: no such file or directory

**Comment by endrift** [comment]
So did you install it or did you just build it and try to run it from the wrong directory? This is 0% a bug either way.

**Comment by reisscake** [comment]
i just installed it from the aur using paru

**Comment by endrift** [comment]
AUR should build it from source and install it. Can you give me the output of `pacman -Ql libmgba` and `pacman -Ql libmgba-git`?
