### ISSUE TITLE
mGBA the settings are missing

### ISSUE THREAD

**Issue by MGR0** [mgba-emu/mgba#2508]
As the title says, the settings menu is missing.

**Comment by endrift** [comment]
Gonna need more information here. You've told me basically nothing. If you're on macOS for example, which I have no idea if you are from what you told me, it's under the mGBA menu, as is normal for applications on macOS.

**Comment by MGR0** [comment]
Yes I am on macOS and I thought it was in the tool menu.
Thanks!
