### ISSUE TITLE
Cenotaph "rolly thingy" on credits is cut off on lower half of screen

### ISSUE THREAD

**Issue by waddlesplash** [mgba-emu/mgba#251]
Only happens when the thingy is going left. When it's going right, it works and looks fine.

YouTube: https://www.youtube.com/watch?v=tp0ZqXNwtTs (~2:25 in that)
pouet: http://www.pouet.net/prod.php?which=59139

**Comment by endrift** [comment]
Fixed in the extremely cryptic 73777259524e6ffc48f330f7c77f2e0bb86ad706. I need to add comments...
