### ISSUE TITLE
mGBA will not reopen after the first launch

### ISSUE THREAD

**Issue by JKhaeros** [mgba-emu/mgba#2510]
Release Version: 0.9.3
OS: Windows 10 64bit

As stated in title, mGBA will not launch again after the first instance is closed. Presumably due to the file library.sqlite3 being added after launch. Deleting library.sqlite3 fixes the issue.

**Comment by endrift** [comment]
Do you have a crash log? It should be in the Windows Event Viewer

**Comment by JKhaeros** [comment]
> Do you have a crash log? It should be in the Windows Event Viewer

Faulting application name: mGBA.exe, version: 0.9.3.0, time stamp: 0x00000000
Faulting module name: mGBA.exe, version: 0.9.3.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000000000021d9e9
Faulting process id: 0x4014
Faulting application start time: 0x01d85d992fb243cc
Faulting application path: C:\Users\jk\Desktop\Emu\GBA\mGBA.exe
Faulting module path: C:\Users\jk\Desktop\Emu\GBA\mGBA.exe
Report Id: 5b9f1bd5-5868-434a-b0ba-427fc239e427
Faulting package full name: 
Faulting package-relative application ID:

**Comment by endrift** [comment]
This might be fixed by 492ba2478c58ae5db090b07c816edd2965907cdd. Please download a development build of 7339-492ba24 or newer to see if it's fixed for you

https://mgba.io/builds/1/

**Comment by JKhaeros** [comment]
Yup, this build fixed the issue. Thanks a lot!
