### ISSUE TITLE
Dear ImGui frontend support

### ISSUE THREAD

**Issue by zzxzzk115** [mgba-emu/mgba#2513]
I want to embed mgba into a ImGui window, but I'm a green hand here. If anyone knows how to implement it, please give me some ideas, thanks!
I tried to build libmgba only, but I didn't know how to use the static library, is there a Wiki or some development tutorials/examples about developing a custom frontend?

**Comment by endrift** [comment]
Take a look in `src/platform/example` for example code of using libmgba

**Comment by zzxzzk115** [comment]
> Take a look in `src/platform/example` for example code of using libmgba

Thanks!

**Comment by zzxzzk115** [comment]
I try to use Thread.Sleep in emulating main loop:
```csharp
// ......
               while (m_isEmulating)
               {
                    byte[] keysBytes = new byte[2];
                    keysBytes[1] = (byte)m_buttonInput;
                    m_compTcpClient.Send(keysBytes);
                    int expected = m_bufferSize;
                    int gotten = m_compTcpClient.Receive(expected, out byte[] frameBufferBytes);
                    m_frameBufferBytes = frameBufferBytes;
                    Thread.Sleep(12);
                }
// ......
```

Then the result is good but seems to lack of some shaders.  I guess I had bad frame because I sent key input so fast.
 Maybe I can use other techniques rather than Thread.Sleep.

![LackOfShaders](https://user-images.githubusercontent.com/33739170/166473511-49946799-0cfb-46f7-8499-f2bce60af2df.gif)

GIF is slower than video. Checkout video here. 

https://user-images.githubusercontent.com/33739170/166474425-4819a23f-9cee-4656-84f6-5a151ffa6012.mp4

How can I load shaders to mgba tcp server?

**Comment by endrift** [comment]
1. This is not a support forum. It's for reporting bugs. You do not appear to have found any bugs in mGBA.
2. That's just...example code structured as client/server. You aren't supposed to actually just write a new client and run the server if you want to use it in a program.
3. Shaders are a frontend feature. You have to put them in the frontend yourself.
4. You're probably treating the buffer as having an alpha channel. It doesn't. There are some flags used by the rendering process stashed there by default. You should ignore those bits.

**Comment by zzxzzk115** [comment]
I'm sorry. I'll read the source code. Thanks for your answers!
