### ISSUE TITLE
Issue: Game Boy/Super Game Boy/Game Boy Color Emulation's Sound Seems Wrong

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#2514]
On Game Boy / Super Game Boy / Game Boy Color Emulation: It Seems Has Terrible **PSG Audio Emulation** Than **Gambatte, TGB Dual, BGB** Such As: Not Horrible PCM Sound Like GBC PCM Sound On **GB/SGB Emulation** On Yong Yong (Bootleg) Games Including **Rockman 8, Sonic 3D Blast 5/Sonic Adventure 7/Sonic Adventure 8, Super Mario Special 3 & Other Yong Yong Games**

**Comment by CraftFan24** [comment]
Fix
