### ISSUE TITLE
More Super Game Boy Borders For GB/GBC Games Feature

### ISSUE THREAD

**Issue by LeopoldCraft06** [mgba-emu/mgba#2515]
Is It Possible To Add More Super Game Boy Borders For GB/GBC Games Feature:

> mGBA (Default) (Arealdy Added)

![sgb-border](https://user-images.githubusercontent.com/104325267/167132405-693f0465-a797-4229-b61a-89bc5fd6836b.png)

> Super Game Boy (Need To Add)

![Super Game Boy (World) (Rev 2)000](https://user-images.githubusercontent.com/104325267/167132471-1b1882a3-2775-4947-9c6f-4fe97e937e3a.png)

> Super Game Boy 2 (Need To Add)

![Super Game Boy 2 (Japan)000](https://user-images.githubusercontent.com/104325267/167132542-226dfe8c-3d36-4dbc-9dbd-e7351b7e6dcc.png)

**Comment by CasualPokePlayer** [comment]
The point of having a generic mGBA centric border is to avoid including the copyrighted official borders.

The only way I'd see these borders getting used is an option for a user provided border to be used (like bgb has).

**Comment by endrift** [comment]
You were already told no. Don't open this issue again.

**Comment by LeopoldCraft06** [comment]
I AREALDY TOLD YOU **YES YES YES YES.** SGB & SGB2 BORDER IS 256x244!

**Comment by LunarLambda** [comment]
These images belong to Nintendo. Just because you can download them does not mean that it is OK to add them in mGBA.

**Comment by LeopoldCraft06** [comment]
That Is OK Or I Will Upload Copyrighted On YT

**Comment by LeopoldCraft06** [comment]
I Uploaded Copyrighted On YouTube And I Got Blocked.

See: https://youtu.be/U8lpXf64Nv0

You Must Be Nightmare

- SuperMarioFan2007 (YouTube), LeopoldCraft06 (GitHub)

**Comment by SirYodaJedi** [comment]
Would it be too out of scope to be able to load these from a user-provided sgb or sgb2 rom, like how the user is able to use the official bioses if they provide them? This would avoid the aforementioned copyright issues by not actually bundling them.

**Comment by endrift** [comment]
I actually looked into how to do that a while ago, but didn't wind up getting deep enough for it to work. I'd need to find out where in the ROM it's located, and I couldn't find that without learning more about the SNES itself.
