### ISSUE TITLE
Add Change SGB Borders (For GB/GBC Games on SGB Emulation Mode)

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#2516]
Original Super Game Boy (World) Border Screen:
![167132471-1b1882a3-2775-4947-9c6f-4fe97e937e3a](https://user-images.githubusercontent.com/104325267/167266562-9916cb1c-34e5-4cba-89e9-dc1344a3ce07.png)

Super Game Boy 2 (Japan, Europe) Border Screen:
![167132542-226dfe8c-3d36-4dbc-9dbd-e7351b7e6dcc](https://user-images.githubusercontent.com/104325267/167266580-66881027-8d55-4d15-a5df-92d6a2d5713d.png)

**Comment by MrKrabs05** [comment]
I know it will be added. YES!

**Comment by CraftFan24** [comment]
It will be added. YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES!
