### ISSUE TITLE
Harry Potter palette+scrolling problems

### ISSUE THREAD

**Issue by Sanqui** [mgba-emu/mgba#252]
The palettes and/or scx in Harry Potter sometimes blink out.  This is easily noticeable on the title screen, where it happens seemingly at random but consistently about a second from when it shows up.

![2016-04-16t21 15 24-mgba-harrypotter 15 3fps -0 5-3558-d300903](https://cloud.githubusercontent.com/assets/289437/14583110/583b7e8a-0418-11e6-975c-826455107f5c.png)

ROM md5sum: ba85a2ae8aa5829c440eef2d5549506c
mgba built from d30090375f8d663091b5ef25eaaddcef87e74dd9

The game might also have some problems like that on hardware, I've never seen it live myself, unfortunately.

**Comment by endrift** [comment]
Weeks of debugging later, I finally fixed this in 13c882411a03ce2adbd1492f7f4fef877b526c7f. The Harry Potter games now run about 300% more stably, although they're still kinda glitchy.
