### ISSUE TITLE
[BUG] Ace Lightning crashes on my PC

### ISSUE THREAD

**Issue by subad31155** [mgba-emu/mgba#2521]
After BBC's logo, the game throws an "The game has crashed with the following error: Jumped to invalid address E35FFFFC" and then after choosing "OK" button, it appeared:
```
A problem has been detected and Windows has been shut down to prevent damage
to your computer.

The problem seems to be caused by the following file: myfault.sys

SYSTEM_SERVICE_EXCEPTION

If this is the first time you've seen this stop error screen,
restart your computer. If this screen appears again, follow
these steps:

Check to make sure any new hardware or software is properly installed.
If this is a new installation, ask your hardware or software manufacturer
for any Windows updates you might need.

If problems continue, disable or remove any newly installed hardware
or software. Disable BIOS memory options such as caching or shadowing.
If you need to use safe mode to remove or disable components, restart
your computer, press F8 to select Advanced Startup Options, and then
select Safe Mode.

Technical Information:

*** STOP: 0x0000003b (0x0000000080000003, 0xfffff80269901cb3, 0xffff91007ae7ef60, 
0x0000000000000000)

*** myfault.sys - Address 0xfffff80269901cb3 base at 0xfffff80269900000 DateStamp 
0x5d014645

```
Your ROM has been corrupted or missing, so any fix? Also there is no use in telling us that it works on visualboy. It has nothing to do with gbarunner2. Thanks

**Comment by GerbilSoft** [comment]
myfault.sys isn't a standard Windows component. It appears to be from Sysinternals' "NotMyFault" tool: https://docs.microsoft.com/en-us/sysinternals/downloads/notmyfault

Have you used NotMyFault previously and/or now? If so, the .sys file might be left over, and may need to be removed manually.

**Comment by subad31155** [comment]
> myfault.sys isn't a standard Windows component. It appears to be from Sysinternals' "NotMyFault" tool: https://docs.microsoft.com/en-us/sysinternals/downloads/notmyfault
> 
> Have you used NotMyFault previously and/or now? If so, the .sys file might be left over, and may need to be removed manually.

Yes, it is a myfault.sys?

**Comment by CyberYoshi64** [comment]
This issue can be closed, this person is known to report bogus issues, be it by using NotMyFault or his faulty SD Card and pass it off as an issue with others' projects.

**Comment by endrift** [comment]
How does one copy/paste a BSoD anyway?

**Comment by subad31155** [comment]
> This issue can be closed, this person is known to report bogus issues, be it by using NotMyFault or his faulty SD Card and pass it off as an issue with others' projects.

YES OR NO?
