### ISSUE TITLE
rpath set even when it is a system directory

### ISSUE THREAD

**Issue by Jan200101** [mgba-emu/mgba#2527]
the executable rpath is set to the libdir, even when that directory is a system directory.

This creates problems for rpm packaging under Fedora since they have a strict requirement to remove [Broken RPATHs](https://fedoraproject.org/wiki/Changes/Broken_RPATH_will_fail_rpmbuild).

Originally added in this commit https://github.com/mgba-emu/mgba/commit/22f4b1fef9c8942d56658fd7353566b7f1c8a3fe

**Comment by endrift** [comment]
Can you confirm if this is fixed by https://github.com/mgba-emu/mgba/commit/542824e3c077f35f1c559b88d962071182790482?

**Comment by Jan200101** [comment]
Can confirm
