### ISSUE TITLE
Sample in Telefang doesn't play properly

### ISSUE THREAD

**Issue by Sanqui** [mgba-emu/mgba#253]
Keitai Denjuu Telefang plays a sample on the title screen that sounds roughly like "_KRRCHRRRR DNCHHJHRRRR TRRRFFNFGGCHU_".  Unfortunately in mgba it only sounds like "_krch dnch trnfch_".

ROM md5sum: bfc1243e827a274b7b0bc5ec806beede
mgba built from d30090375f8d663091b5ef25eaaddcef87e74dd9

**Comment by endrift** [comment]
I think I fixed this with e1a4acec9f39a1f7081d56b69c851747caada807, but my hearing's not so great, so let me know.

**Comment by MoochMcGee** [comment]
Any updates on this issue?

**Comment by endrift** [comment]
Fixed in 8ac6f83bc58e9d846ca6c8d546c7eb2f6665fc1a, although there are still problems with channel 4.
