### ISSUE TITLE
how to use mGBA-0.9.3-switch.7z in Nintendo Switch ？

### ISSUE THREAD

**Issue by kwenZh** [mgba-emu/mgba#2535]
i download mGBA-0.9.3-switch.7z  and put it in tf cards, path：switch dir
![image](https://user-images.githubusercontent.com/38367518/170816309-3affc4c9-1ee0-4c06-8561-51fa98eed478.png)

![image](https://user-images.githubusercontent.com/38367518/170816330-da1a4a33-7b13-41ad-8520-c3e4924fed1a.png)

![image](https://user-images.githubusercontent.com/38367518/170816337-380487bc-4509-4f56-b5d6-566be6a1eb90.png)

but in switch  album, no emulator is seen。 in readme.md i saw it is support Nintendo Switch
![image](https://user-images.githubusercontent.com/38367518/170816364-17e43c31-7e84-4043-98f9-0080d004f789.png)

Is there any usage documentation about mGBA-0.9.3-switch.7z?

**Comment by endrift** [comment]
You just need to put the nro in the /switch directory. So long as you have homebrew working on your Switch already, that's all that's needed.
