### ISSUE TITLE
Windows 64-bit 0.10-7496: Faceball 2000 is SLOW

### ISSUE THREAD

**Issue by Pr3ttyF1y** [mgba-emu/mgba#2537]
So I know that this game had bad FPS back in the day and unfortunately I do not have real hardware to test, but I was testing out the Faceball 2000 DX romhack that patched the game to supposedly run better in GBC mode - and it was barely playable in this patched state.

So I went back to the original rom (verified to No-Intro hashes), and game play is SUPER slow. Like slightly worse than a slide show slow. 

Interestingly, the demo that plays before the title seems to be about the appropriate speed, but there definitely is something wrong with the game play. It's way too slow to the point that it's not playable (each tick of the time = about 7 real time seconds per my phone's stop watch).

mGBA is running the ROM in straight DMG mode as it's not a Super Game Boy enhanced ROM (per my config).

**Comment by Testsr** [comment]
Can confirm that Faceball 2000 is slow, relative to Sameboy. I am attaching bugreport zip
[Reports.zip](https://github.com/mgba-emu/mgba/files/8803956/Reports.zip)
.

**Comment by endrift** [comment]
My mistake. The hardware testing label was specifically in reference to it being a ROM hack, but that was in error so I removed both.

**Comment by Pr3ttyF1y** [comment]
I've done some more testing, now with version Revision 7567-c1b1f72 and I believe the issue is related to link cable polling.

If you generate a new multi-player window and load up Faceball 2000 in both and play the game linked, while there is some graphical glitching (blinking of the status bar) on player #1's HUD, the game otherwise plays at a reasonable speed. I'm not sure if it's 100% perfect, but I'm thinking something must be going on relating to the link cable ability of this game when being played in single player mode that's crushing the performance.

**Comment by endrift** [comment]
@Pr3ttyF1y's analysis was correct, it was link cable related.
