### ISSUE TITLE
Dolphin connection isnt working!

### ISSUE THREAD

**Issue by Adanas2009** [mgba-emu/mgba#2538]
I was trying to connect the mGBA to Dolphin to play Pac-Man Vs., and it says it is connected, but both screens just freeze when connected! What do I do now?

<img width="661" alt="Screen Shot 2022-05-30 at 2 20 14 PM" src="https://user-images.githubusercontent.com/106552987/171044427-e9603d21-c1ca-4d83-9873-0924acfb1084.png">

**Comment by JMC47** [comment]
You need a newer version of Dolphin; the protocol has been changed a lot since Dolphin 5.0.

If you use a newer build of dolphin, you also have the option of using the integrated mGBA instance, which might make things easier.

**Comment by Adanas2009** [comment]
> You need a newer version of Dolphin; the protocol has been changed a lot since Dolphin 5.0.
> 
> If you use a newer build of dolphin, you also have the option of using the integrated mGBA instance, which might make things easier.

I can't download a newer emulator because my type of computer doesn't have a required update to launch the emulator. I can download the emulator but I can't launch it because I cant update my computer yet. I guess I am going to have to wait a long while to launch the newer update.

**Comment by endrift** [comment]
I can't support Dolphin that old.
