### ISSUE TITLE
Pokémon TCG noise channel does weird things

### ISSUE THREAD

**Issue by Sanqui** [mgba-emu/mgba#254]
On the title screen and the main menu, it just produces odd sounds.

ROM md5sum: 219b2cc64e5a052003015d4bd4c622cd
mgba built from d30090375f8d663091b5ef25eaaddcef87e74dd9

**Comment by endrift** [comment]
Should be fixed by af96ee70879f65255c11e1cc28a88f2afd23894c. An optimization I put in place to prevent churn turned out to be wrong.
