### ISSUE TITLE
Super Game Boy 2 & Game Boy Pocket Emulation mode

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#2542]
Try [gb240p](https://drive.google.com/file/d/12QH7ldZ4RKJDs5bx6hDh-bli_L4k-U5W/view?usp=drivesdk) 

add Super Game Boy 2 & Game Boy Light Emulation mode

Super Game Boy 2 (SGB2)
![170128704-3e9043a4-3d9e-42ba-bc85-c8d4435a6bb5](https://user-images.githubusercontent.com/105673473/171655533-7e25fffa-5f97-46b4-b0a6-7b8cfb4d7fa1.png)
Game Boy Pocket (pocket)
![170128496-3e951d2c-1ae0-4648-9e3f-d4019478a824](https://user-images.githubusercontent.com/105673473/171655622-010da793-5df1-4fa1-bd1e-ac9c9a80acf3.png)

**Comment by SteveCraft2244** [comment]
It will be added! YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES!
