### ISSUE TITLE
Save file load date error. Wii mGBA ver.0.9.3

### ISSUE THREAD

**Issue by ZoarTwili** [mgba-emu/mgba#2543]
Hello, I am using *mGBA 0.9.3* version on Wii using an SD card where I put app and roms. 
Everything is going well, I have been using it for a long time, the save files work without problem, except for a detail that I discovered yesterday. 

While playing "Megaman Battle Network 5 Team Protoman" (USA), I paused through the mGBA toogle menu, before that I put save in game, and at that moment the Wii power went out due to a storm; When the power came back on, I turned on the console, I chose the same game and, to my surprise, the progress was not saved on "June 2 at 00:00 am and 6:06 am", the save file recorded the last time I saved it did not load the current data, instead, it loaded the data for "May 31 at 6:14am", two days ago.

![IMG_20220602_060733](https://user-images.githubusercontent.com/106746661/171781587-41d3de2f-6d37-4db9-ac55-ba6be19114b2.jpg)

That obviously frustrated me because it's the first time this has happened, so I repeated the cause of the save file error, saved again, disconnected the console power cable, turned it back on, chose the game and the data loads the same date " 6:14 a.m. / May 31.

I put to check if the error is the game/save file, so I used VBA GX last update, I did the procedure to disconnect the console power cable and the save file loads the new record where I saved. 

Now I used *mGBA Development version 0.10-7512-0a674dd37* and my save data loads at its current date and time with no problem (although it gives me a loud *beep* every time I save data in "Megaman Battle Network 5").

That will have fixed my problem, but it persists in version *0.9.3* so I'm reporting that bug.

**Comment by endrift** [comment]
If it's already been fixed then it means the next version will have the fix. It was fixed after 0.9.3 came out, so it'll be fixed in 0.10 when that comes out.

**Comment by ZoarTwili** [comment]
Thanks for the clarification. 
Waiting for version 0.9.4.
