### ISSUE TITLE
SNES/SFC (Super Nintendo / Super Famicom) support

### ISSUE THREAD

**Issue by SopTheSop27** [mgba-emu/mgba#2545]
Is it possible to add support for SNES/SFC

SNES/SFC file extensions:

.smc
.sfc
.fig

SNES is backward compatibility with Game Boy, Game Boy Color (using Super Game Boy CARTGRIDE)

Screenshots for example:
![Super Mario World (USA) 000](https://user-images.githubusercontent.com/101358042/171996835-e18e4533-333f-455a-bd0a-eb59d05eab56.png)
![Super Mario World (USA) 001](https://user-images.githubusercontent.com/101358042/171996839-db527f55-15bb-451b-94ca-1a6d4053be3b.png)
![Super Mario All-Stars (U) 000](https://user-images.githubusercontent.com/101358042/171996843-3ee49b9e-f430-40f4-8de3-710685272893.png)
![Super Mario All-Stars (U) 001](https://user-images.githubusercontent.com/101358042/171996846-6960249e-65a5-41a9-a554-c4a984f8f9ce.png)
![Super Game Boy (World) (Rev 2) 000](https://user-images.githubusercontent.com/101358042/171996853-6996f012-de77-46e5-8618-03d316cb1271.png)
![Super Game Boy 2 (Japan) 000](https://user-images.githubusercontent.com/101358042/171996862-71c9e644-46c9-4b5d-85c7-f4d3387338f1.png)

**Comment by endrift** [comment]
No
