### ISSUE TITLE
Gba games not saving and savestates not working (ps vita)

### ISSUE THREAD

**Issue by musicman928** [mgba-emu/mgba#2546]
I don't know if I'm missing something but I've used other gameboy advance emulators and there is usually a .sav file that pops up when I make a save file but I'm not seeing anything and my vita doesn't seem to either. After saving in game and restarting the emulator my progress is lost. The savestates just don't work. I press x to save to save slot one, go over to load slot one and there is no change.

Games I tried: Fire Emblem: the Sacred Stones, Mother 3 (untranslated)

Knowing me it's probably something I missed but I'm not sure what to do. Any help would be appreciated.

**Comment by endrift** [comment]
Are you running in safe or unsafe mode? What directory is the ROM located in?

**Comment by musicman928** [comment]
I think unsafe mode. It's in a _games_ folder in ux0. Is there a particular place I have to put it? for it to save?

**Comment by musicman928** [comment]
Wait sorry the saves are working now idk what happened but thank you for trying to help :)

**Comment by musicman928** [comment]
Because before it was just on the root of ux0 and I think putting it in a folder for roms fixed it. (I hate to be _that_ guy)

**Comment by Ray12334** [comment]
Hi I am having the issue now. Did you find a solution?
