### ISSUE TITLE
Robopon doesn't start

### ISSUE THREAD

**Issue by Sanqui** [mgba-emu/mgba#255]
It doesn't get past a splash screen.

AFAIK, it uses a weird Hudson mapper.  It's also probably compiled so forget about disassembling it...  I still have nightmares.

ROM md5sum: 398f7b60ea114b90b24503178f47e8d8
mgba built from d30090375f8d663091b5ef25eaaddcef87e74dd9

**Comment by endrift** [comment]
Known issue. HuC1 is unimplemented due to lack of documentation.

**Comment by endrift** [comment]
Looks like a mock implementation of HuC-3 doesn't fix this. The issue must be deeper. The assembly is hard to trace, but it looks like it's swapping to the wrong bank at some point and then just kinda dies.

**Comment by Sanqui** [comment]
The assembly is /impossible/ to trace.  This game is compiled and stores absolutely everything on the stack.  Every important operation is lost in a sea of stack manipulation garbage.  I'm sorry if you tried to trace it.

**Comment by endrift** [comment]
gdgdfsgsdfgdfg that assembly is garbage.

Fixed in 59938208abdaa8a223ac237667c3a679cf4b280c with some HuC-3 support.
