### ISSUE TITLE
Building mgba-qt from source?

### ISSUE THREAD

**Issue by alexwennerberg** [mgba-emu/mgba#2552]
I'm following the *nix instructions in the `README`, and it builds the sdl version fine, but it doesn't seem to build or install `mgba-qt` anywhere. I'm not super familiar with cmake, but I'm wondering if I'm missing something obvious

**Comment by endrift** [comment]
The build product winds up in the qt subdirectory, assuming you have qt installed. What's the output of the CMake command?

**Comment by alexwennerberg** [comment]
Ah, I think I was missing the right qt libraries. It works now :)

Going to try out the lua scripting, will let you know if I find any issues!
