### ISSUE TITLE
Possibility of maintaining the faster hle bios?

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#2554]
Before https://github.com/mgba-emu/mgba/commit/6f4398a3b9e531f3397187863db587608eb0c63a  certain games had full speed where on real hardware or by using an original bios they would slow down.

For example the Fire Emblem games, when using a "fire tome" to attack, the decreasing HP bar would always count slower as the animation plays.

But there is another game that benefits greatly from this, a Japan-only title: Konjiki no Gash Dream Tag Tournament, whenever there's a screen transition the BGM stutters noticeably, so when on the 'stage select' screen it becomes very annoying.

I understand that since this is quite niche and inaccurate to boot, it might not be worth it, but I'm curious to know if this could be considered as a potential enhancement?

**Comment by endrift** [comment]
I don't intend to maintain a separate version just for a small handful of games that benefit. It would be easier to make ROM hacks that fix these issues, to be honest.
