### ISSUE TITLE
Flickering and slowdown issues in DDR

### ISSUE THREAD

**Issue by Sanqui** [mgba-emu/mgba#256]
Dance Dance Revolution GB flickers the screen a lot and that probably causes slowdown as well.

ROM md5sum: c7cf1e919682b3ee613dd155cc12a15a
mgba built from d30090375f8d663091b5ef25eaaddcef87e74dd9

**Comment by endrift** [comment]
Can you check if this behavior has changed recently?

**Comment by endrift** [comment]
Wow okay no this is still totally broken.

**Comment by endrift** [comment]
Flickering is fixed in 0c59856fe364ff949eaee7f76f266292d600dada. I don't think there's any slowdown?
