### ISSUE TITLE
0.9.3 and latest dev show only a white screen

### ISSUE THREAD

**Issue by shenef** [mgba-emu/mgba#2561]
I'm pretty sure mGBA previously worked on this machine, not sure what changed since.
Tested on a fresh download of the latest dev and 0.9.3.
The result is the same independent of the game.
![image](https://user-images.githubusercontent.com/20268890/174597484-18878ec5-66f1-49b7-bff9-b18f157464c6.png)
[error log.zip](https://github.com/mgba-emu/mgba/files/8940403/error.log.zip)
Windows 10 21H2

**Comment by ILiveOnSaturn** [comment]
Same problem here, loading a rom will make mGBA show a white screen, no matter the rom. I currently have the 0.9.3 version.

**Comment by Animepurush** [comment]
Same problem

**Comment by endrift** [comment]
Please ensure you have a working audio device.

**Comment by Animepurush** [comment]
thanks,it starts working

**Comment by shenef** [comment]
Can confirm, no audio devices was also the cause for the issue on my end.
Feel free to close this as it's most likely a duplicate.
