### ISSUE TITLE
Opening mGBA and sub-windows causes a application selection popup

### ISSUE THREAD

**Issue by shenef** [mgba-emu/mgba#2562]
Clicking on the "search microsoft store" button brings up the "Xbox Game Bar" app which is not installed on this machine.
![image](https://user-images.githubusercontent.com/20268890/174598683-891be291-4278-4553-9100-87169e26945b.png)
Windows 10 21H2 | 0.9.3 and latest dev

**Comment by endrift** [comment]
This isn't something that's explicitly done in mGBA, it seems to be something Windows wants to do. See if these steps help: https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-get-rid-of-ms-gaming-overlay-pop-up/f572b5c0-f1dd-40f8-a16b-7bcbe62b4690
