### ISSUE TITLE
black screen when opening game

### ISSUE THREAD

**Issue by ajbeastmod** [mgba-emu/mgba#2567]
when I open a game the screen is black, but if I double-click to full-screen mode, I see the game. looked on the internet and couldn't find shi so now I'm here

**Comment by endrift** [comment]
You're gonna need to tell me literally anything about your setup. I don't know if you're running on a gaming rig or a toaster, or a recent version or a prehistoric one.

**Comment by ajbeastmod** [comment]
11th gen core i7 and an rtx 3060, it happens on all 5 on my roms, pokemon fire red, leaf green, ruby, sapphire, emerald

**Comment by endrift** [comment]
Please upload the bug report zip generated by File > Report Bug. This gives me a lot more information so I don't have to actually ask you piecemeal

**Comment by ajbeastmod** [comment]
[bug.zip](https://github.com/mgba-emu/mgba/files/8972245/bug.zip)

**Comment by endrift** [comment]
Thanks, I'll take a closer look a bit later

**Comment by ajbeastmod** [comment]
well, i fixed it, i found something saying it could be a shader i instaled and it was, i just turned it off
