### ISSUE TITLE
mGBA dev crashes on M1 MacBook Pro

### ISSUE THREAD

**Issue by brainard52** [mgba-emu/mgba#2568]
mGBA version: mGBA 0.10-7567-c1b1f7200 (c1b1f72005f26c4aaca098c3cb8c860215895dc9)
macOS version: 12.3.1 (21E258)

If it runs natively and I double-click the app, I get:
[mgba_crash_run_app.txt](https://github.com/mgba-emu/mgba/files/8973474/mgba_crash_run_app.txt)

If I run the bin from the terminal:
[mgba_crash_run_bin.txt](https://github.com/mgba-emu/mgba/files/8973473/mgba_crash_run_bin.txt)

This occurs for both Native and Rosetta2.

**Comment by endrift** [comment]
Looks like...paintGL gets called before initializeGL? That's not supposed to happen. Oh well, I can work around that.

**Comment by endrift** [comment]
Fixed in 5349cab4b258b636c1e2b988d9539243edccfc82
