### ISSUE TITLE
gba games not saving 

### ISSUE THREAD

**Issue by 1heck** [mgba-emu/mgba#2571]
normally games create a .sav file to save but when I try to save, nothing happens, the box just says empty and no file is created.

I've only tried on Pokémon fire red which is about all I've played so far but is there a way to fix or should i try getting an earlier version of mGBA.

I may be missing something but idk.

**Comment by endrift** [comment]
What folder are your ROMs in? If it's under Program Files, that won't work. Any directory that needs a UAC prompt to put files into it will break, since mGBA doesn't invoke UAC.

**Comment by 1heck** [comment]
If I take it out of the program files then when I need to load the rom it just makes another folder in the program files, I'm not sure what to do with the UAC because once again taking it out doesn't work.

**Comment by endrift** [comment]
I don't understand what you mean. Can you upload the zip generated by File > Report Bug while a game is loaded?

**Comment by 1heck** [comment]
[sagve.zip](https://github.com/mgba-emu/mgba/files/9023878/sagve.zip)

is this it?

**Comment by endrift** [comment]
Yes it is.

As I thought, the problem is that you have the ROM under Program Files: C:/Program Files/mGBA/Pokemon - Fire Red Version (U) (V1.1).zip

You need to move the ROMs, not the program itself (not the EXE or any of the other files) somewhere like Documents or your Desktop

**Comment by 1heck** [comment]
that worked, thank you very much
