### ISSUE TITLE
My File not working

### ISSUE THREAD

**Issue by Lennyfuhr** [mgba-emu/mgba#2572]
My file does not want to open when I drag it into the programme and it then says this 
![mgba](https://user-images.githubusercontent.com/108426926/176506885-2cd8148f-deec-49ca-b966-28d5b6e4f2cb.PNG)

so can someone help me with this now?

**Comment by endrift** [comment]
It looks like you extracted the game to a temporary directory, which might have since been deleted. I'd recommend extracting it to a permanent location.

**Comment by endrift** [comment]
Closing due to lack of reply.
