### ISSUE TITLE
Where can I find GBATimerFlagsIsEnable symbol?

### ISSUE THREAD

**Issue by tjwink** [mgba-emu/mgba#258]
Greeting.
Where can I find GBATimerFlagsIsEnable symbol?
Some function like GBATimerXXXX can not found in source code,are they all in other library?

**Comment by endrift** [comment]
What's the bug here?

Those are autogenerated by theGBATimerFlags bitfield definitions. https://github.com/mgba-emu/mgba/blob/master/src/gba/gba.h#L62

**Comment by tjwink** [comment]
Sorry,I asked a question in a wrong place,I will close it.
