### ISSUE TITLE
Recording problems

### ISSUE THREAD

**Issue by Ckosmick** [mgba-emu/mgba#2580]
all the record options have been busted since 0.9.3 in my experience.

GIF recording doesn't record beyond frame 1.
Video recording regardless of codec selected causes the emulator to crash either once user hits Start, or Stop.

my system:
intel core i7-6700k 4.0GHz
32GB ddr4-3600
amd rx-6700XT (driver 22.5.1)
windows 10 (controlled folder access is OFF)

**Comment by Ckosmick** [comment]
This has happened to me on both team red and blue, idk about nvidia

**Comment by Ckosmick** [comment]
if it helps at all I have multiple drives. mgba is installed to drive C:\ while I am trying to record to H:\

**Comment by endrift** [comment]
This has been fixed in development builds for a while, and will work in 0.10 when it comes out (soon). If you can't wait, development builds are available on the website.
