### ISSUE TITLE
ROM wont stop speeding up

### ISSUE THREAD

**Issue by Mycoxate** [mgba-emu/mgba#2581]
Ive reinstalled and unistalled multiple times but every time i load any ROM it automatically speeds up and i cant get it to stop, its not like i can play with it on either its so fast i cant get through 1 space holes in pokemon or even start thje game before the intro starts

**Comment by endrift** [comment]
Make sure sync is enabled: https://mgba.io/faq.html#i-did-something-and-now-the-game-always-runs-too-fast

**Comment by Mycoxate** [comment]
> Make sure sync is enabled: https://mgba.io/faq.html#i-did-something-and-now-the-game-always-runs-too-fast

THANK YOU SO MUCCCCHH ive been suffering and just remembered to check here, you saved me a headache!
