### ISSUE TITLE
"corrupted size vs. prev_size while consolidating" when recording APNG or WebP (GIF not tested)

### ISSUE THREAD

**Issue by Heath123** [mgba-emu/mgba#2584]
Whenever I try to record I get this after I try to save it:
```
corrupted size vs. prev_size while consolidating
fish: Job 1, 'QT_QPA_PLATFORM=xcb mgba-qt' terminated by signal SIGABRT (Abort)
```

**Comment by Heath123** [comment]
The same thing happens with lossless record A/V

**Comment by endrift** [comment]
This has been fixed in dev builds for several months; there just hasn't been a stable release since
