### ISSUE TITLE
Glibc problem??

### ISSUE THREAD

**Issue by Griphcode** [mgba-emu/mgba#2587]
Hello i am trying to run Mgba on Linux debian 11 but it required Glibc_2.34 but i already installed it so it should work but it didn't this is the error message that is showing in my terminal once i run it:

`griphcode@penguin:~$ mgba
mgba: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.34' not found (required by mgba)
mgba: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.33' not found (required by /lib/libmgba.so.0.9)
mgba: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.32' not found (required by /lib/libmgba.so.0.9)
mgba: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.34' not found (required by /lib/libmgba.so.0.9)
`

If you have an answer to this type of problem please be sure to let me know!

**Comment by endrift** [comment]
You can't install the Ubuntu debs on Debian and have them work. There _may_ be some that work, but not the newer versions. Try the 20.04 debs.

**Comment by Griphcode** [comment]
Do you know where i can get the 20.04 debs

**Comment by endrift** [comment]
https://mgba.io/downloads.html
