### ISSUE TITLE
OpenGL renderer is broken on AMD 5600xt and steam deck in lattest dev build

### ISSUE THREAD

**Issue by aldelaro5** [mgba-emu/mgba#2588]
This happens only in the latest dev build (0.10-7617-b8087c1d9) and not in the flatpak release and only if the "display driver" in the settings is set to either OGL options with any ROM:

![Screenshot from 2022-07-09 18-37-39](https://user-images.githubusercontent.com/8932978/178126667-e137c048-ba8a-44b2-b4b6-83c8d1c55fcb.png)

The same thing happen with the same deck, just the corrupted data looks different, but similar.

I am using a 5600xt.

**Comment by endrift** [comment]
I think this is specific to AMD GPUs. On my Intel GPU it works, but on AMD GPUs it spits out Mesa/radeonsi issues. It might be an ABI incompatibility.

**Comment by endrift** [comment]
It is indeed an ABI incompatibility...with libelf. mGBA linked against one libelf implementation, and mesa linked against another. The API was compatible, but the ABI wasn't, so it broke horrifically.
