### ISSUE TITLE
Add .dmg, .sgb, .cgb FILE Extension

### ISSUE THREAD

**Issue by Squidward22** [mgba-emu/mgba#2596]

**Comment by endrift** [comment]
There already is one for .sgb, but I've never, ever seen .dmg or .cgb, so I must ask why

**Comment by Squidward22** [comment]
There is .sgb, .cgb, .dmg on VisualBoyAdvance-M

**Comment by endrift** [comment]
That is not an adequate justification, especially since .dmg is the extension for macOS Disk Images. If there are no files that use this extension I'm not going to bother.

**Comment by Squidward22** [comment]
.dmg file extension on Gambatte - Game Boy / Color emulator
