### ISSUE TITLE
.sgb file extension for Pokémon Gold/Silver Spaceworld 1997 Demo ROMs

### ISSUE THREAD

**Issue by SteveCraft28** [mgba-emu/mgba#2599]
@endrift is it possible to add .sgb FILE EXTENSIONS to Pokémon Gold/Silver Spaceworld 1997 Demo ROMs

It's duplicate of #2596

**Comment by Squidward22** [comment]
Will be added / implemented .sgb to Pokémon Gold / Silver Spaceworld 1997 Demo

**Comment by endrift** [comment]
I said the first time there already is support for .sgb

and what do you think these replies accomplish

**Comment by Squidward22** [comment]
It's already. But not in LIBRETRO port. LIBRETRO is way difference than official original Emulators.

**Comment by endrift** [comment]
Nah libretro has it too. If you're going to be annoying about it, you should at least do your homework, otherwise I'll ban you again for being disruptive.
