### ISSUE TITLE
Pokemon Pinball Ruby&Sapphire (U) White Screen

### ISSUE THREAD

**Issue by FormalHellhound** [mgba-emu/mgba#260]
When booting Pokemon Pinball Ruby&Sapphire (U) in linux with sdl, all I get is a white screen after the bios intro.

**Comment by endrift** [comment]
Which version of mGBA? Also, what's the MD5 of the ROM? I was just testing this game a few days ago in Linux.

**Comment by FormalHellhound** [comment]
It was version .5 from the ppa for mgba, the md5 is 3a31c9382d4a93abf5e5ff48c6219d73 , I am running ubuntu 15.10, and the rom was from emuparadise. I am getting some other weird issues too, like games freezing for brief periods of time while I play them, and whenever I try to switch to Qt5 it just crashes. I am almost wondering if something isn't functioning properly on my computer. Keep up the awesome work on this man!

**Comment by endrift** [comment]
Ugh, a scene dump with an inserted intro. Those things like to do weird shit for no apparent reason. But it looks like it works on hardware, so I fixed it in b5ff48a74e73fcf0dc3d555ebcd39e5250bb9646.
