### ISSUE TITLE
[Feature Request] "TV Mode" from VBA

### ISSUE THREAD

**Issue by anzz1** [mgba-emu/mgba#2600]
Feature request:

Porting the "TV Mode" filter from VBA to mGBA  
(C "filter" -> GLSL .fs fragment shader)

As found here: 
https://github.com/x3ro/VisualBoyAdvance/blob/master/src/scanline.cpp#L125

The file contain multiple filters/shaders, but only the "ScanLinesTV" part is relevant (The "Scanlines" function is already ported as "Simple Scanlines", and the -32 versions of both functions are leftover/unused code). 

The "TV Mode" shader is perfect as-is, no configuration options needed. In my opinion, it strikes a perfect balance between smoothing out artifacts of the low resolution on bigger screens and keeping the "authentic" feel of source material, giving a unobtrusive retro look.

**Comment by endrift** [comment]
Unfortunately I cannot incorporate (or port) code from a GPL project such as VBA into mGBA without changing the license for mGBA, which I am not going to do.
