### ISSUE TITLE
Bug / Feature request: Fast Forward speed limit for "Fast Forward (Held)"

### ISSUE THREAD

**Issue by AudioDuplication** [mgba-emu/mgba#2604]
I am using 0.10-7634-4247fd0be rev 4247fd0be36bd72503f7bbeb74540767ffad2035.
When I set a speed limit for fast forwarding it is honored when using "fast forward", however when using the shortcut "Fast forward (held)" the game speeds up unbound, instead of the 2x max speed limit that I have set.

I don't know if this is intentional or not, and I couldn't find a duplicate issue on this issue.

Screenshot:
![image](https://user-images.githubusercontent.com/108935890/181663875-59e6f758-6ede-4908-ac1e-20c13b24f60d.png)
![image](https://user-images.githubusercontent.com/108935890/181663657-c64fadf8-9122-4746-8e31-6f00bcd77127.png)

**Comment by endrift** [comment]
There's already a setting for this, in the settings dialog. It's a bit confusing to have this menu as a result so I wasn't sure what to do.

**Comment by AudioDuplication** [comment]
Oh I see it now, its in settings > emulation > fast forward (held) speed. I had to untick "unbounded" here and set a speed.
I probably never looked in the settings hard enough, since it was already in the dropdown.

Thanks!

**Comment by Ninjistix** [comment]
Sorry to reopen this, but i'm still having the similar issue, with trying to map the fast forward speed held (im getting upwards of 3-5k fps)
