### ISSUE TITLE
Black Screen issue

### ISSUE THREAD

**Issue by FuchsCrafter** [mgba-emu/mgba#2609]
Hello, I got an issue where the emulator is just a black screen.
I've looked into the FAQ and it suggested to change the display driver, but there is no documentation to do this.
Im using Arch linux with the mgba-sdl package [(see here)](https://archlinux.org/packages/community/x86_64/mgba-sdl/)
The QT version shows just a logo when it's opened.

System Information
Kernel: 5.18.14-zen1-1-zen
DE: Plasma 5.25.4
WM: KWin 
CPU: Intel i7-6500U (4) @ 3.1GHz
GPU: AMD ATI Radeon R5 M330
GPU #2: Intel Skylake GT2 [HD Graphics 520]
Memory: 12GiB

**Comment by XVicarious** [comment]
(The QT version) In `Tools -> Settings -> Audio/Video` there is a `Display Driver` option. `Software (Qt)` worked for me. It is odd to me that OpenGL isn't working. 

Also on Arch, KDE, Some recent linux-zen kernel. i5 Tigerlake (using it's GPU).

**Comment by endrift** [comment]
Strange, I have a similar setup for my daily driver: Arch, KDE, i7 Tiger Lake using the iGPU. I wonder if the zen kernel is just busted.
