### ISSUE TITLE
Ubuntu 16.04 compilation issues.

### ISSUE THREAD

**Issue by whistlebee** [mgba-emu/mgba#261]
/src/platform/qt/Window.cpp seems to have compilation issues 

home/paul/Downloads/mgba-0.4.0/src/platform/qt/Window.cpp:` In member function ‘void QGBA::Window::updateTitle(float)’:
/home/paul/Downloads/mgba-0.4.0/src/platform/qt/Window.cpp:734:22: error: ‘isnan’ was not declared in this scope
  } else if (isnan(fps)) {
                      ^
/home/paul/Downloads/mgba-0.4.0/src/platform/qt/Window.cpp:734:22: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:85,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qdatetime.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QDateTime:1,
                 from /home/paul/Downloads/mgba-0.4.0/src/platform/qt/Window.h:9,
                 from /home/paul/Downloads/mgba-0.4.0/src/platform/qt/Window.cpp:6:
/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^

Changing to std::isnan as suggested seems to fix it.

**Comment by endrift** [comment]
This has already been fixed in both the 0.4 branch and master.
