### ISSUE TITLE
[GB] Prehistorik Man seems to have Channels 1 and 2 muted

### ISSUE THREAD

**Issue by CasualPokePlayer** [mgba-emu/mgba#2614]
Tried on 0.9.3 and 519968d37eee630662cd3c84c722d9d6dd321689. Seems to sound identical to disabling Channels 1 and 2 in bgb.

**Comment by endrift** [comment]
Can you see if this worked in previous releases? I swear it worked at some point.

**Comment by CasualPokePlayer** [comment]
Tried 0.8.4, 0.7.3, 0.6.3, all bugged.

**Comment by endrift** [comment]
That's probably far enough back, though I suppose there's a chance it worked in 0.5.2. I won't treat it as a regression then.

**Comment by endrift** [comment]
This was definitely _not_ a regression. This is really old code. I guess I just misremembered.
