### ISSUE TITLE
Super Game Boy & Super Game Boy 2 border correction

### ISSUE THREAD

**Issue by SteveCraft08** [mgba-emu/mgba#2619]
Super Game Boy
![183757270-6a7381c2-f9bc-40e3-af65-9c867c6b0df7](https://user-images.githubusercontent.com/110945884/183781370-492d6781-e6c7-49fa-83bf-675e4a121372.png)
Super Game Boy 2
![183757280-cbb583a2-93a4-4f6e-8396-631cd2595b9c](https://user-images.githubusercontent.com/110945884/183781374-a17ff313-cb05-4ad4-82da-fd353a0d7cb2.png)

**Comment by endrift** [comment]
Enjoy getting permabanned from GitHub.
