### ISSUE TITLE
Battery Saves

### ISSUE THREAD

**Issue by Alexpoke19** [mgba-emu/mgba#2622]
I Exported A Battery Save But i don't know how to load it is there any way it's possible?

**Comment by endrift** [comment]
What do you mean "exported"? What menu?

**Comment by Alexpoke19** [comment]
> What do you mean "exported"? What menu?

I exported a save file from another emulator but don't know how to put it in the mgba emulator because there's no option to import the save file. The type of file was (.sav)

**Comment by Testsr** [comment]
You are expected to place the .sav file next to your rom.

**Comment by Alexpoke19** [comment]
> You are expected to place the .sav file next to your rom. That is how you load a sav file.

What do you mean by "next to your rom"?

**Comment by Testsr** [comment]
@Alexpoke19 Put it in the same folder as the rom.

**Comment by Alexpoke19** [comment]
> @Alexpoke19 Put it in the same folder as the rom.

Oh Ok thank you
