### ISSUE TITLE
Fast Forward bug

### ISSUE THREAD

**Issue by SantiAle15** [mgba-emu/mgba#2624]
Hi, i have a issue. I usually play my pokemon game in fast forward, but now all the games I play are in fast forward and i cant remove it, help
[Fast foward bug.zip](https://github.com/mgba-emu/mgba/files/9324753/Fast.foward.bug.zip)

**Comment by RetroEdit** [comment]
From the FAQ (https://mgba.io/faq.html):

> **I did something and now the game always runs too fast!**
> Make sure Fast forward is unchecked under emulation and at least one of Sync to audio or Sync to video is checked. I recommend Sync to audio only.

**Comment by RetroEdit** [comment]
Without further information, there's not really much that can be done here. There are some other potential causes, like toggling fast-forward on, which has the default key bind `Shift+Tab`.
