### ISSUE TITLE
Updater does not detect new versions - AppImage only?

### ISSUE THREAD

**Issue by WhenGryphonsFly** [mgba-emu/mgba#2627]
### Issue
The updater is unable to find any available version for download. This appears to only affect AppImage builds; at the very least, it does not affect Ubuntu 22.04 builds.

Ubuntu 22.04 0.10-7647-feec147f0
![image](https://user-images.githubusercontent.com/84215159/184939159-bff8fbae-a1bd-443e-bf72-9a32d4c9555f.png)

AppImage 0.10-7647-feec147f0
![image](https://user-images.githubusercontent.com/84215159/184939364-47bdef29-dad1-46ce-a6d9-572e95577f38.png)

AppImage 0.10-7623-004f317ab
![image](https://user-images.githubusercontent.com/84215159/184939653-e63eb8c5-81ba-495e-ba13-d92d580c6f7d.png)

AppImage 0.10-7622-8997eda00
![image](https://user-images.githubusercontent.com/84215159/184939763-abf8cd34-2553-4e9e-8544-0161a8636837.png)

### Builds
Affects 0.10-7623-004f317ab through the latest development build (0.10-7647-feec147f0). Does not affect 0.10-7622-8997eda00.

### System Information
- Linux Mint 21 Cinnamon
- AMD Ryzen 9 3900X
- AMD Radeon RX 5500

### Bug Report ZIPs
[AppImage7622.zip](https://github.com/mgba-emu/mgba/files/9353081/AppImage7622.zip)
[AppImage7623.zip](https://github.com/mgba-emu/mgba/files/9353082/AppImage7623.zip)
[AppImage7647.zip](https://github.com/mgba-emu/mgba/files/9353083/AppImage7647.zip)
[Ubuntu2204_7647.zip](https://github.com/mgba-emu/mgba/files/9353084/Ubuntu2204_7647.zip)

**Comment by endrift** [comment]
That's strange, it seems to work on my machine, and there's nothing in r7623 that should have broken it. The only thing I see wrong on your bug report zips is that the bucket is missing, but that shouldn't happen unless you downloaded a corrupted manifest file. What happens if you delete the line `update.bucket=` from your config file (while mGBA is closed) and then checking for updates again?

**Comment by WhenGryphonsFly** [comment]
For 7622 and Ubuntu, after deleting the line and then opening and closing the program, the line is `update.bucket=https://s3.amazonaws.com/mgba/`. For 7623, 7647, and 7634 (in a different directory; the same process results in `update.bucket=`. Manually checking for updates changes nothing (I suspect this is because I have it configured to automatically check for updates).

Running all 5 versions from the command line results in the following messages (the last one is 7634):
![image](https://user-images.githubusercontent.com/84215159/185005779-f3d8962e-e74e-4dc1-9575-aa5745b0b03b.png)

**Comment by endrift** [comment]
Ah, it sounds like the last time I updated the AppImage Docker image it broke TLS, then.

**Comment by endrift** [comment]
Please recheck with 7648-8a87eaa or newer.

**Comment by WhenGryphonsFly** [comment]
I have confirmed it works with 7648 through 7652. Thank you!
