### ISSUE TITLE
Feature request: Rewind intervals/Rewind speed

### ISSUE THREAD

**Issue by negativeiqtest** [mgba-emu/mgba#2628]
Currently, when rewinding you go back in near real-time or it jumps all the way back to the frames you had set,
Is there any way to either increase the speed you go back or increase the time between saved frames so you can jump back further/quicker? 
I saw an earlier issue #36  ([https://github.com/mgba-emu/mgba/issues/36](url)) where it seemed like this was a possibility, before being changed around #66  ([https://github.com/mgba-emu/mgba/issues/66](url)).
Any chance this could be implemented? It would make rewinding longer animations or turn-based games so much nicer.

**Comment by sam-gupta-git** [comment]
May I work on this issue?

**Comment by endrift** [comment]
This isn't a great starter issue.

Also, you can already do fast-forward and rewind at the same time to rewind faster, but it's kind of a rough way to handle it.

**Comment by martinmurtiono** [comment]
I actually got this working already... https://github.com/mgba-emu/mgba/commit/ec92714ad1dfc1fb47557a0d152de11f9d285f89

**Comment by endrift** [comment]
You can still file a PR, even if I didn't think it was a great starter issue.
