### ISSUE TITLE
[Feature Request] Async Audio Emulation

### ISSUE THREAD

**Issue by LOuroboros** [mgba-emu/mgba#2629]
Hi. I'm not sure if this is possible to implement in a GBA emulator at all, but I imagine it's worth bringing up.

I'd like to ask if asynchronous audio emulation could be implemented in mGBA someday.

This is a feature that certain emulators for other consoles have, and that would allow the music of the game that is being emulated to play at a normal speed even if the user were to use Fast Forward functionality to speed-up said game.

Feel free to close if it's way too hard or plain impossible.

**Comment by endrift** [comment]
Unfortunately due to the fact that audio processing is on the CPU, not a discrete APU/DSP, this isn't really possible. You can thank Nintendo for that choice.
