### ISSUE TITLE
Pokemon Ruby plays static with the background music if you savestate and loadstate multiple times

### ISSUE THREAD

**Issue by ds84182** [mgba-emu/mgba#263]
Title says it all. 
![Relevant Save State](https://cloud.githubusercontent.com/assets/2268005/15307659/3565cd96-1ba3-11e6-9588-3dbd1d397b0d.png)
The music seems to go back to normal if you leave the current area.

**Comment by ds84182** [comment]
d3fa698 is the commit that initially breaks the audio in Ruby (the middle part of the song gets progressively more staticy, but it doesn't get better or worse with savestating).

**Comment by ds84182** [comment]
adf20be is the commit where the actual issue starts (ignore the previous message, that one got fixed before this commit)

**Comment by endrift** [comment]
This absolutely isn't static--it's a square wave. Regardless, it's fixed in 2f33cd70f601c06809c34ee58bf4ca964cec7318.
