### ISSUE TITLE
[Feature Request] Disable double-clicking toggle for full screen.

### ISSUE THREAD

**Issue by RumaoS** [mgba-emu/mgba#2632]
I (and a of close friend of mine) would love to have a way to disable the double-clicking which currently triggers fullscreen ON-OFF.

The reason: Options and freedom of choice are always welcome :)
Always, if it were not much to ask. Thanks!

**Comment by endrift** [comment]
I mean, "more options" is an absolutely terrible justification for adding complexity, but I was planning on just removing it since it would be broken in medusa down the line.

**Comment by Joewawaw** [comment]
Has this been removed? I'd like to see it be disabled. A hotkey for toggling fullscreen (which already exists) is sufficient for this shortcut

**Comment by endrift** [comment]
Not yet.

**Comment by anthonydo8196** [comment]
Hello my name is Anthony and I'm part of Tam's group (we are a group of 4) for CS 360V at UT. May we work on this issue?

**Comment by endrift** [comment]
Sure, it's pretty easy to do.
