### ISSUE TITLE
Commit 6fc6562 is broken.

### ISSUE THREAD

**Issue by CharlesCorrin** [mgba-emu/mgba#2633]
Commit: 6fc656296dba663164b16b9410565c2c83d0bd81

is broken in my PC with Windows 10 64-bit. The program never loads except in the background. You need to end its task to get rid of it afterward. I tried deleting my config files and the problem remains. This is the only info the program saves in the config afterward:

[ports.qt]
fullscreen=0
height=299
width=480

**Comment by endrift** [comment]
Can you check with a8dcf87e70523b02a9d07593fec4234b9566eaa2?

**Comment by CharlesCorrin** [comment]
Yep. That fixed it. Or, more specifically, I tried commit:2a9f32a84069592e305741a8460cd87308913ceb and you definitely fixed the problem since the commit I stated in the post above. Thank you. :3
