### ISSUE TITLE
mGBA no longer remembers its window size

### ISSUE THREAD

**Issue by LOuroboros** [mgba-emu/mgba#2634]
Title.

After seeing that the issue I brought up in #2578 was fixed, I updated to the latest nightly build.

I only opened the emulator once yesterday, so I figured that its weird window size was a one time occurrence because the program needed to adapt to the changes or something like that, but I'm noticing that whenever I open mGBA anew, instead of opening with the same window size it had at the time I closed it, its window looks vertically stretched.

https://user-images.githubusercontent.com/4485172/185622627-7fff6fcd-480f-4918-a22a-4d6fe94dd284.mp4

***Note**: I'm not sure if the kinda problem that can be seen from 0:13 to 0:24 in which mGBA was taking too long to startup again that I had to manually finish the process using `taskkill` is related to Windows or mGBA, but I'm leaving this written note just in case.*

**Comment by endrift** [comment]
Seems to be Windows specific.

**Comment by endrift** [comment]
Are you using Windows 11? I don't seem to be able to repro this on Windows 10.

**Comment by LOuroboros** [comment]
> Are you using Windows 11? I don't seem to be able to repro this on Windows 10.

No, I'm on Windows 10. More specifically, Windows 10 v21H2 Build 19044.1415.

**Comment by endrift** [comment]
Very strange. I wonder why I can't repro. Can you upload your config.ini and qt.ini? The bug report zip should put bundle them.

**Comment by endrift** [comment]
Can you retest with the latest commit?

**Comment by LOuroboros** [comment]
> Can you retest with the latest commit?

It seems to work normally now 🥳 !

> Very strange. I wonder why I can't repro. Can you upload your config.ini and qt.ini? The bug report zip should put bundle them.

I guess I'll still do that just in case, but since the problem was fixed I doubt it's necessary now.

[config.txt](https://github.com/mgba-emu/mgba/files/9389098/config.txt)

[qt.txt](https://github.com/mgba-emu/mgba/files/9389099/qt.txt)

***Note**: I renamed them to .txt files because GitHub doesn't like .ini files for whatever reason.*
