### ISSUE TITLE
libretro gbc opposite accelerometer direction android

### ISSUE THREAD

**Issue by soundsnow** [mgba-emu/mgba#2635]
Korokoro Kirby (Japan)
Kirby - Tilt 'n' Tumble (USA)

left is right
right is left
up is down
down is up

**Comment by endrift** [comment]
What system is this running on? An Android phone?

**Comment by soundsnow** [comment]
> What system is this running on? An Android phone?

yes! Android phone
sorry, I don't know what's accelerometer

**Comment by soundsnow** [comment]
What is the difference between them

**Comment by soundsnow** [comment]
I followed the game instructions to tilt the phone, but got the opposite result

**Comment by endrift** [comment]
> What is the difference between them

Gyroscopes detect rotation, accelerometers detect acceleration or gravity (so, basically downward acceleration). The difference here isn't super important. I'll see if I can find an Android device to test.

**Comment by GaussTek** [comment]
I wanted to report that I also have this issue, using Android. Other motion sensor games like WarioWare, etc, work fine. Just the GBC (Kirby and Command Master) which require Motion sensor. Hopefully something can be done about this, thank you!

**Comment by endrift** [comment]
What about Yoshi's Topsy-Turvy? WarioWare uses a different sensor type thank Kirby, but Yoshi uses the same sensor type

**Comment by GaussTek** [comment]
Just tried Yoshi and it also works fine, and also this other game Koro Koro Puzzle Happy Panechu!, which I also think uses accelerometer. Movement is correct in those.

It's just the Kirby game and the other GBC one which are having issues here :(. Perhaps it's something related to this or something? http://kirbyconfirmed.blogspot.com/2013/06/kirby-tilt-and-tumble-for-gameboy.html

**Comment by endrift** [comment]
Maybe. I'll try to hunt down an Android phone for testing soon. I know I have one around here somewhere.

**Comment by endrift** [comment]
Yup, that was definitely very backwards for me too.

**Comment by outlandernwah** [comment]
Hi. Sorry for the bump. Is there any way to control the sensitivity of the accelerometer/tilt? I'm having a hell of a time controlling things. In Wario: Twisted! it's kind of manageable but in Kirby Tilt 'n' Tumble it's pretty much impossible to play due to the sensitivity. Is there a config file I can edit? 

I'm on an Android to be clear (Odin 2)
