### ISSUE TITLE
The ' key cannot be used as a controller button.

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#2636]
When setting up keyboard bindings for controller buttons, I set the / key as L and the ' key as R. However, the ' key doesn't do anything when used. I spoke to others, and it seems that key in specific doesn't work as a key binding at all. I'm unsure why this is. I first noticed this issue in A Link to the Past -- Four Swords; as I oddly could not grab/pick up anything until I changed 'R' to another key. However, I still wanna use '.

I attached the report file as suggested.

[Report.zip](https://github.com/mgba-emu/mgba/files/9384313/Report.zip)

**Comment by endrift** [comment]
This appears to be because the ' key is bound to the gameshark button by default. I should unbind that.
