### ISSUE TITLE
Gameshark Save Files Won't Open

### ISSUE THREAD

**Issue by Zernek** [mgba-emu/mgba#2638]
I'm trying to load a Gameshark Save for Megaman Battle Network 6 (Japan), and no matter what I do, my emulator will not take GameShark saves.

The website won't let me load the SPS file, but I tried 3 different Japanese Gameshark Save Files under this website https://gamefaqs.gamespot.com/gba/929993-mega-man-battle-network-6-cybeast-gregar/saves

I did the top 2 Japanese saves with Nigoli and the 2 TitaniumMegaman saves. I can't find anything like this online where the emulator just does nothing upon trying to open it. Is there something I can do to fix this?

**Comment by endrift** [comment]
Please don't upload ROMs.

I assume you're trying to use the import GameShark save dialog to import this?

**Comment by Zernek** [comment]
> 

Yes, I am using that. Also, my apologies, I wasn't aware uploading ROMs wasn't allowed. But yes, the Import GameShark Save dialogue is how I'm importing the file and literally nothing happens once I do my game just carries on like nothing happened. I mainly tried it on the english translation patched version of the game but I also did it on the original japanese version just to be sure and it still didn't work, and I tried 4 different saves. Any suggestions for how to fix this, 100%ing the game is really painful without gameshark saves and using gameshark or action replay codes to get the missing stuff for 100% completion can cause some bugs to occur.

**Comment by endrift** [comment]
Did you reset after restoring the save? Games often won't notice if you don't.

**Comment by Zernek** [comment]
> Games

What do you mean by “restoring” the save? All I did was do Import Gameshark File. Should I import the file then reset then import again?

**Comment by endrift** [comment]
Generally what I do is load the ROM, do the import, then reset the game (using the Reset option in the emulation menu, or reloading the ROM itself).

**Comment by endrift** [comment]
Did you try resetting after importing the save?
