### ISSUE TITLE
[Win 11] Qt New Multiplayer Window weird size

### ISSUE THREAD

**Issue by Testsr** [mgba-emu/mgba#2639]
After a8dcf87, when I add a multiplayer window in windows 11, the new multiplayer window is very small. 
<img width="1248" alt="2022-08-21 (1)" src="https://user-images.githubusercontent.com/31809837/185780367-a98d8e7b-d0f4-4899-87e1-cb0dfcda862d.png">
Bug report is attached here:
[bug.zip](https://github.com/mgba-emu/mgba/files/9388621/bug.zip)

**Comment by endrift** [comment]
This is _almost certainly_ a duplicate of the other, still open window sizing issues...

**Comment by Testsr** [comment]
I think this issue is fixed for me/
