### ISSUE TITLE
add Super Game Boy 2 model

### ISSUE THREAD

**Issue by EnderCraft22** [mgba-emu/mgba#2643]
Super Game Boy 2 uses different border in **Tetris DX**

Super Game Boy 2
![Tetris DX Super Game Boy 2](https://user-images.githubusercontent.com/111684306/186485823-1442a40e-2710-4326-97bb-859af7718ba0.png)
Super Game Boy
![Tetris DX Super Game Boy](https://user-images.githubusercontent.com/111684306/186485838-3438ec5f-c3d2-49b6-ac5f-431f3bf9de99.png)

**Comment by combo-pizza** [comment]
Seems that way, I stuck the game into my super gameboy and it only showed the second border even when I reset the console. Never knew that

**Comment by endrift** [comment]
I dunno what you're even trying to accomplish when you know I'm just blocking and reporting your accounts at this point.
