### ISSUE TITLE
Can't change the emulator into english.

### ISSUE THREAD

**Issue by TouhouJevil** [mgba-emu/mgba#2644]
Ok i downloaded mgba and it was on my language, but i normally prefer using stuff in english so i went to the language settings and english is not there???
![GIF 30-08-2022 03-00-33](https://user-images.githubusercontent.com/47754093/187361114-2430fee8-f8bc-44ad-bc84-725634a8d04c.gif)
Using mgba 0.9.3 that i downloaded from the website, using windows 7 64 bits, if this issue could be solved (or if you know how i can solve it) it would be nice.

**Comment by endrift** [comment]
One of those is Portuguese options is actually English, and one of the translators thought that translating the word "English" into "Portuguese" was a good idea. This should be fixed in the dev builds, I believe.
