### ISSUE TITLE
Gif recording outputs a static image

### ISSUE THREAD

**Issue by Stevoisiak** [mgba-emu/mgba#2646]
### Issue

The "Record GIF/WebP/APNG..." tool output a static image instead of an animated gif.

### System

- Windows 11 Pro (Build 22000)
- mGBA 0.9.3
- Intel(R) UHD Graphics 620
- Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz, 1896 Mhz, 4 Core(s), 8 Logical Processor(s)

### Steps to reproduce

1. Open mGBA.
2. Load rom of Donkey Kong for Game Boy.
3. Select "Audio/Video" > "Record GIF/WebP/APNG..."
4. Click "Select File" and choose output folder.
5. Keep default selections of GIF, loop enabled, and Frameskip 2.
6. Click "Start"
7. Play for a little bit
8. Click "Stop"
9. Open the newly created gif

### Expected result

Output an animated .gif of gameplay

### Actual result

Output a static .gif of the first frame when recording started.

### Recording

https://user-images.githubusercontent.com/1330770/187506707-e3999add-d0ee-465b-9256-20b930352480.mp4

![test](https://user-images.githubusercontent.com/1330770/187507494-ad098ae6-4289-4560-b312-9926efb18b1c.gif)

**Comment by foopod** [comment]
Same experience here on linux.


https://user-images.githubusercontent.com/3768616/187530247-3a988b05-0ea9-41b8-9734-02886a4475a8.mp4

These three lines repeat themselves in the logs while recording.

```
[buffer @ 0x5627b4ce5780] filter context - w: 240 h: 160 fmt: 121, incoming frame - w: 0 h: 0 fmt: -1 pts_time: 46.6619
[buffer @ 0x5627b4ce5780] Changing video frame properties on the fly is not supported by all filters.
[swscaler @ 0x5627b4f98980] bad dst image pointers
```

Output .gif from the above recording...

![record](https://user-images.githubusercontent.com/3768616/187530386-8f2d2460-f589-4f5a-a91c-66c4e955298b.gif)

**Comment by endrift** [comment]
This should have been fixed in the dev builds months ago. Please retest.

**Comment by Stevoisiak** [comment]
> This should have been fixed in the dev builds months ago. Please retest.

Confirming Issue is fixed in dev build. Gifs record properly.
