### ISSUE TITLE
random crash/game restarts in mgba 0.93

### ISSUE THREAD

**Issue by pirategreg** [mgba-emu/mgba#2659]
I'm playing pokemon emerald on mgba and ever since i used a the gameshark cheat for rare candies my game keeps restarting and going back to the opening screen for pokemon emerald. when i load up the save file and go back to where i was, i can continue to play as normal until it happens again. it keeps happening and each time the interval between it occurring again seems to get smaller.

**Comment by endrift** [comment]
The cheat code is probably bad. There are lots of bad cheat codes online.

**Comment by pirategreg** [comment]
Thanks for responding so quick. I assumed so, its not actually shortening time intervals it was random as the game is working fine now after a while. Its manageable so just a minor issue but thanks again
