### ISSUE TITLE
[libretro] add multiplayer support

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#266]
The [TGB Dual core](https://github.com/libretro/tgbdual-libretro) for GB/GBC already has this feature as an example implementation

**Comment by tony971** [comment]
Although [this](https://github.com/libretro/tgbdual-libretro/issues/4) should be brought up as an asterisk to TGB Dual's multiplayer support.

**Comment by endrift** [comment]
Make sure to poke the libretro people to let them think up an API and control scheme that may or may not make sense before I can actually really do this.

Like really, TGB Dual multiplayer in libretro is a gigantic hack. Closing this until libretro's API officially supports this.
