### ISSUE TITLE
0.9.3 freezing issue

### ISSUE THREAD

**Issue by sunvulture** [mgba-emu/mgba#2664]
Been playing some Pokemon roms (Ultra Violet and gen2 games), and I've encountered the freezing bug. It's completely random. Anywhere from 5 to 15 minutes in it'll just freeze. I have to save after doing anything or risk losing all my progress. Can't figure out a solution since everywhere says it's been fixed already.

**Comment by endrift** [comment]
Please try downloading a development build. There have been fixes since 0.9.3, but no stable version has come out since. The dev builds are at the bottom of the downloads page.
