### ISSUE TITLE
[Wii port] Stretch video doesn't fully stretch

### ISSUE THREAD

**Issue by roflcopter777** [mgba-emu/mgba#267]
Starting with version 0.40 (and the concurrent nightly builds up to 5/30/16, enabling "stretch" in the video options does not truly stretch as black borders remain on the sides and earlier versions prior to 0.40 did in fact do just that.  Pixel perfect doesn't resolve this as it makes it, well smaller, I don't know why no one else reported this issue but now's the time, and hopefully isn't too hard to implement, I don't know. 

Version tested: 0.40 official, as well as 2/27/16 2/29/16 and 5/30/16 nightly builds, all results were the same, stretch doesn't stretch video all the way as previous versions have.  

Screenshots
![image](https://cloud.githubusercontent.com/assets/15101626/15654775/4c345df6-2654-11e6-956e-76c9eb51a35b.png)

![image](https://cloud.githubusercontent.com/assets/15101626/15654789/5d133138-2654-11e6-9760-0e60d556b0e3.png)

http://i.imgur.com/36jJ3A3.jpg
http://i.imgur.com/r6L30jK.jpg
http://i.imgur.com/36jJ3A3.jpg

**Comment by GB-CG** [comment]
I wonder about this too, but then I use my Framemeister to correct it.

**Comment by roflcopter777** [comment]
That doesn't really help those that don't or can't afford outside devices, one shouldn't have to do that though.

**Comment by endrift** [comment]
This was somewhat intentionally done to avoid issues with TVs that have overscan issues cutting bits off, which was a common complaint. The real fix would be to let users have more control over how much it's stretched, but I haven't gotten around to doing that yet.

**Comment by roflcopter777** [comment]
Damn, I was afraid of that *sigh* guess I might as well close this and the thread I made on the mGBA forums. I know you're busy and neither ShadowOne333 nor I have a right to complain or make false bug reports. Now I feel like an idiot.

**Comment by roflcopter777** [comment]
Well, yeah, gonna close this because you're busy and it looks like both of us are doing nothing but complaining when we should be grateful, *sigh*. I've been ungrateful and I haven't meant to. Ugh, dammit all to hell.

**Comment by endrift** [comment]
I mean, it's a known issue and it *is* an issue, I just haven't been prioritizing the Wii stuff recently.

**Comment by roflcopter777** [comment]
So that tells me that I shouldn't have reported it at all, because you're busy with this and real life issues, I have no right to make it known or make an bug report about it. *sigh*  Now I feel like garbage.

**Comment by GB-CG** [comment]
@roflcopter777 It's true about the cost thing. we're just curious that's all. :)

(I'm actually fine with the Wii port the way it is.)

**Comment by endrift** [comment]
Just because it's a known issue doesn't mean that I actively think about it. I generally encourage filing issues so I can keep track of things, as I am known to forget issues. I didn't mean to imply that filing this was bad in any way, and it will help me keep track of this issue, even if I knew about it already. I just haven't gotten around to fixing it yet.

**Comment by roflcopter777** [comment]
@GB-CG  @endrift  I still feel kinda bad about reporting this at all because I feel like it's me being ungrateful, and I'm not trying to convey that at all. *Sigh* I do that it does get fixed at some point, that's all, and thank you.  Sorry about that, I wasn't sure and the last thing I want to do is anger you :(

**Comment by GB-CG** [comment]
@roflcopter777 It's cool :)

**Comment by endrift** [comment]
I'm certainly not angry, so don't worry about it.

**Comment by roflcopter777** [comment]
So what should I do in the mean time, test GB/GBC games and report any crashes/code dumps? I'm testing the 5/30/16 build, so I just want to be sure I can help somehow with looking for issues. And good to know that the stretching will be controlled by the user at some point, and thank you guys again.

**Comment by endrift** [comment]
Reporting any bugs in GB/C games is a good way to go, as I'm trying to clean that up before I release 0.5, although that's still a long way off I think (unless I punt like every feature). Crashes or code dumps are significantly less likely than just general bugs in emulation. Also you can just use the builds without having to worry about being helpful. I made them for people to enjoy, not for people to stress about giving back to the project.

This is veering a bit off topic though. If you want to talk about how to be helpful to the project, the forums are a better place than a single bug report.

**Comment by roflcopter777** [comment]
Fair enough, I'll keep this open for the stretch video option but other issues I have I can just put on the forums, thank you again for your hard work.

**Comment by endrift** [comment]
By the way, this is now configurable by editing the config file directly: https://forums.mgba.io/showthread.php?tid=449&pid=1117#pid1117

A config menu will be added in 0.6.0.

**Comment by endrift** [comment]
The config menu has been added now, but I fear the overscan may still break it.

**Comment by roflcopter777** [comment]
Wow, I admittedly forgot about this GitHub report. My apologies, and thank you.

**Comment by endrift** [comment]
I'm pretty sure this has been fixed by now. I'll reopen if it's not.
