### ISSUE TITLE
[Bug Retroarch] Rumble only works for Port 1

### ISSUE THREAD

**Issue by yontekh** [mgba-emu/mgba#2673]
When using Retroarch mGBA core. And the controller you need to rumble is set to port 2*, it wont rumble. only port 1* will rumble.

*_Clarification (because Retroarch's settings are a maze and a mess):_
If under Settings>Input>MaxPlayers = >1
And under Settings>Input>Port 2 is the controller you wish to rumble, mGBA core wont rumble it no matter what.
If you change said controller to port 1, mGBA will rumble it.

Not to be confused with QuickMenu>Input>Port 1. Those are different things in Retroarch eventhough they label them the same (bad design).

**Comment by endrift** [comment]
This has to be a RetroArch bug. mGBA can't differentiate controllers beyond knowing it sends everything to the only controller it is. If those are mapped weirdly in RetroArch, and things rumble wrong, that's a RetroArch bug.
