### ISSUE TITLE
mGBA freezes upon loading a ROM after moving the window to a monitor with a lower resolution

### ISSUE THREAD

**Issue by OceanBagel** [mgba-emu/mgba#2674]
I have a multi-monitor setup with two monitors at 1440p resolution and one at 1080p resolution. If I open mGBA on one of the 1440p resolution monitors and then move the window to the 1080p monitor, opening a ROM causes mGBA to freeze. Opening mGBA on a 1080p monitor and moving it to 1440p monitor or moving the window between the 1440p monitors does not cause the freeze to happen.

This issue occurs on release 0.9.3 as well as dev build 0.10-7699-e4a5a3f2d. It also only occurs when using the OpenGL display drivers. It does not occur when using the Qt display driver. I'm using the Windows 32-bit versions.

**Comment by endrift** [comment]
Does this problem manifest with other programs? I have different resolution monitors on my desktop and haven't seen this. Please also upload the bug report zip.

**Comment by OceanBagel** [comment]
I managed to reproduce the same issue on Gambatte-Speedrun with the same conditions (OpenGL and moving the window to the other monitor before opening a ROM). So it may just be an issue with OpenGL on my system. In any case, I've included the bug report zip.
[bugreport_issue_2674.zip](https://github.com/mgba-emu/mgba/files/9751428/bugreport_issue_2674.zip)

**Comment by endrift** [comment]
This is almost certainly a driver bug. Closing unless you find evidence that it's not.
