### ISSUE TITLE
Auto-Updater treats older versions as new versions

### ISSUE THREAD

**Issue by Dreadtroid** [mgba-emu/mgba#2678]
![Screenshot 2022-10-12 003724](https://user-images.githubusercontent.com/97256932/195251662-abe8a642-ab7a-4c0f-b33a-a3f723705a26.png)

mGBA's auto-updater will display an older version as new even when using the latest version. This is mGBA build 0.10.0 on Windows 11 64-bit.

**Comment by endrift** [comment]
~~The updater had one job~~

There was a hitch with getting the latest counter working--it said 0.1 is less than 0.9, and 0.10 starts with 0.1. That's been fixed now. Can you try hitting check again?

**Comment by Dreadtroid** [comment]
![Screenshot 2022-10-12 004909](https://user-images.githubusercontent.com/97256932/195252745-96feb96f-0de5-4b8b-ad2f-c6ccf28291c5.png)

Works fine now!

**Comment by endrift** [comment]
Perfect, thanks.
