### ISSUE TITLE
Select the stable update channel by default

### ISSUE THREAD

**Issue by anewuser** [mgba-emu/mgba#2679]
The portable 0.10.0 version has the `Development` update channel checked by default. Wouldn't it be better to set it to `Stable`?

**Comment by Mirza101** [comment]
Seems also bugged, can't select stable, at all, and while it's in development, it always prompts for a download of the latest version even though you already have it installed.

**Comment by endrift** [comment]
I'll need to spin a new build with the branch set as ref/heads/0.10.0 to get this working in 0.10.0, but the code change is better going forwards as either that or 0.10.0 would work with this code change.
