### ISSUE TITLE
FPS Target

### ISSUE THREAD

**Issue by CartridgeGen** [mgba-emu/mgba#268]
Hello, I've made an ARMHF port with GLES2,SDL2 and QT. Problem is... It's running at 500+ frames a second. Fast forward is off, removed audio sync or else I get 1.1 frames, tried leaving it on with different audio samples and rates with some success but it jitters a lot when it gets to 60fps. Frameskip can't save me from the jitterring. Tried video sync, same thing 1.1 frames, tried both on, again same thing. FPS Target does not seem to cap my frames at said rate... I wish it would lock at the said frames i chose and not suggest to the frames to be at 60 frames. Funny thing is, GLES2 does not work, white screen and so does SDL2. My main problem I want to be fixed is the FPS Issue I'm having, so yes, I'm running in software mode QT. If I put Fast forward on with 2x I'm getting a 58-60fps but with once again major jittering. What can I do to achieve a locked speed of 60fps? Or else FPS Target is a misleading name for the option if it's not actually "aiming at a target". Ran on ODROID Xu3 Debian Jessie.

**Comment by endrift** [comment]
FPS target only works with audio sync enabled, as it uses the audio clock to time the frame rate.

**Comment by CartridgeGen** [comment]
Thanks for clearing that up. I can now get a more seamless jitter-type now that I understand how FPS Target works. I have to be at 65FPS for any game and Frameskip 1 for those that has lots of Mode 7 and 3D-type models like Need For Speed. And I have to say, WOW! This is the first of the many emulators (including libretro) where I can play Need For Speed at a reasonable speed and somewhat good sound. This one tops every other GBA Emulator I've known since. This is going in my thread of ports. I sure wish I could really fix the jittering though but now that's it's more seamless, it's ok I guess. Thanks for making this great Emulator and I support this.

On other emulators (On Xu3/U3/U2/C1) I get around 45-50 fps on Need for speed Underground 1 and a real laggy sound. On yours it's more than playable and this highly configurable emulator is more than I could ask for.

**Comment by endrift** [comment]
Closing, as the issue ended up being a misunderstanding. Perhaps I should add a clearer explanation for FPS target, though.
