### ISSUE TITLE
Updater don't work properly

### ISSUE THREAD

**Issue by NVHT** [mgba-emu/mgba#2681]
You have to manually extract the file from the zip. The updater only downloads the file.

**Comment by NVHT** [comment]
Windows.

**Comment by endrift** [comment]
I *definitely* fixed this before releasing 0.10.0. What version are you currently running.

**Comment by NVHT** [comment]
Build 0.10-7710-225369f2b right now. But it broke a long time ago from what I remembered.

**Comment by endrift** [comment]
Then you should have reported it a long time ago instead of today when I fixed it 5 hours ago in ded409f0da14ccc83dcd6d62d5756e0b75b382e1 after finding it on my own right before I was about to release.

**Comment by NVHT** [comment]
0.10-7736-686eee4e2 not fixed.

**Comment by endrift** [comment]
I just downloaded 0.10-7736 and tried the updater to 0.11-7738; it works fine.

**Comment by endrift** [comment]
Oh, but there is a bug renaming the file when "updating" from 0.11-7738 to 0.10.0; it's a different bug though.

**Comment by NVHT** [comment]
> I just downloaded 0.10-7736 and tried the updater to 0.11-7738; it works fine.

Like I said, it downloaded the update file. However, when prompt to install the update, mGBA don't restart and the update also isn't applied.
