### ISSUE TITLE
SGB+GBC doesn't load SGB border for Polished Crystal (romhack)

### ISSUE THREAD

**Issue by ShadowOne333** [mgba-emu/mgba#2684]
I am having one slight issue when trying to use SGB+GBC mode with a specific hack, Polished Crystal. 
This hack has a special border made for it:
![image](https://user-images.githubusercontent.com/13888698/195713755-71f2aede-ab5f-4d3f-a886-ec74bd7b5171.png)

However, when booting it with SGB+GBC, it loads the default mGBA border (meaning it doesn't detect it?)
And the only way to make this border appear is by selecting SGB in the SGB+GBC model, but then it refuses to boot and stays at a white screen (like in the picture).
This is what I get with SGB+GBC set in the SGB+GBC model setting:
![image](https://user-images.githubusercontent.com/13888698/195713824-f07e9907-95ac-4d83-a9ac-4c53e8d48a23.png)

The only way to make the custom border appear with mGBA is by forcing the SGB+GBC mode to be SGB, then it loads the border, but the romhack refuses to boot (probably because it's trying to load it up as normal GB game instead of GBC).

In case it is needed, here's a link to the romhack for testing and debugging purposes:
https://github.com/Rangi42/polishedcrystal/releases/tag/v3.0.0-beta-nightly

**Comment by endrift** [comment]
This appears to be a bug in Polished Crystal. The SGB upload bails out if the game is run on a CGB, but it also intentionally crashes if the game isn't run on a CGB. As such, it will never upload the border.

**Comment by CasualPokePlayer** [comment]
Seems this hack actually expects a GBC + SGB which boots into SGB mode to acquire the border then resets to CGB mode. The border does sucessfully upload on bgb if booted in SGB mode (or with GBC + initial SGB border). This might be more intentionally done to have the best support for GBC + SGB emulators.

**Comment by bootmii** [comment]
This is how VBA(-M) does GBC+SGB, seemingly for vanilla Crystal's sake.

**Comment by endrift** [comment]
Yes, see #2832 for tracking that approach.
