### ISSUE TITLE
You should add MBC30 to your list of supported mappers

### ISSUE THREAD

**Issue by ReNardier** [mgba-emu/mgba#2686]
i know you support it, an im sure it works as guy said https://github.com/higan-emu/higan/issues/98 but it would be nice if it where on your list

**Comment by endrift** [comment]
The bank 0x80 mapping might not actually work as mentioned there, I'm not sure. MBC30 is basically just MBC3 with a tiny change though, and it's only used by one game.

**Comment by CasualPokePlayer** [comment]
I had bank 0x80 tested before on an actual JPN Crystal cart and it did behave as mentioned (this is also in line with how the mapper and other mappers work in general with the bank 0 -> 1 trick).

**Comment by endrift** [comment]
I meant might not work in mGBA as mentioned, not on hardware. As in, mGBA might not get it right.

**Comment by ReNardier** [comment]
im glad i made this issue, did a bit more digging and found this
https://gekkio.fi/files/gb-docs/gbctr.pdf page 44
"MBC30 is a variant of MBC3 used by Japanese Pokemon Crystal to support a larger ROM chip and a larger RAM chip. Feature wise MBC30 is almost identical to MBC3, but supports ROM sizes up to 32 Mbit (256 banks of 0x4000 bytes), and RAM sizes up to 512 Kbit (8 banks of 0x2000 bytes). Information in this section is based on my MBC30 research."
looking at your doc https://mgba-emu.github.io/gbdoc/#mbc-3 it seems to be correct, although as you mentioned the wrap-around might not be quite there in mgba, but there is more on that page
"The circuit board of Japanese Pokemon Crystal includes a 1 Mbit RAM chip, but MBC30 is limited to 512 Kbit RAM. One of the RAM address pins is unused, so half of the RAM is wasted and is inaccessible without modifications. So, the game only uses 512 Kbit and there is a mismatch between accessible and the physical amounts of RAM."
if true then it makes me want for an unofficial(i mean, its what nintendo put on the board so it cant be unlicensed... or can it?) mapper that gives the full 16 banks of ram that the chip on the board would have allowed, call it MBC31 for the previously unused pin being used if you will, makes me wonder how they handled it in the 3ds virtual console, did they take a look at the cart speck, view 1mb ram and simply go "ok" or was there a note on the cart specks that said "this pin unused"?
if that thing about the pin is true, would need some confirmation, and the heuristics to make sure that japanese crystal and i assume crystal clear and polished crystal get the MBC30 mapper and not MBC31

**Comment by ReNardier** [comment]
followed your advice and opened https://github.com/tzlion/hhugboy/issues/62 for the Identifiers
i have told him nothing about the "MBC31" mapper, before i say anything about it to him, could i ask your thoughts and plans on it?
and yes, i do count "im not making it" as a comprehensible plan

**Comment by endrift** [comment]
MBC31 isn't "useful" on anything for anything other than homebrew, and homebrew can just use MBC5 unless they care about RTC. But most homebrew doesn't.

**Comment by ReNardier** [comment]
yes, it though that would be the case
i assume the fact you only edited the readme means that the bank switching looping works as intended and that despite there being no "GB_MBC30 = 0x130," in interface.h the emulator gives japanese crystal its correct number of rom/ram banks, right?
if so great to know, thanks for your efforts.
if so goo to know

**Comment by endrift** [comment]
MBC30 is basically just a tiny modification to MBC3, the same way the RTC is just a tiny modification to MBC3. The difference is not significant enough to warrant any other flags, as it can be detected just fine as a specific RAM size on MBC3. There were no code changes needed.
