### ISSUE TITLE
Prehistorik Man - garbage on the left of the scrolling text in intro

### ISSUE THREAD

**Issue by sczther** [mgba-emu/mgba#269]
Here is a comparsion between the BGB emulator and todays nightly build of mGBA:
![bgb00001](https://cloud.githubusercontent.com/assets/17219314/15773439/25424d0e-2977-11e6-8c30-8b93b755c09a.png)
![prehistorik man usa europe -0](https://cloud.githubusercontent.com/assets/17219314/15773466/46b6dd60-2977-11e6-8dc4-3c5f023d96fa.png)

**Comment by endrift** [comment]
Hmm, I thought I fixed this. I guess it broke again at some point.

**Comment by endrift** [comment]
For reference, this is a cycle counting/IRQ timing bug.

**Comment by endrift** [comment]
Turns out it was a PPU timing issue, not an IRQ timing issue.
