### ISSUE TITLE
Mario Bros Card 5 strip 2 does not scan. [Regression]

### ISSUE THREAD

**Issue by Testsr** [mgba-emu/mgba#2693]
In mGBA 0.10.0, the Mario Bro-e card 5 strip 2 does not work with mGBA e-Reader support. The e-reader rom believes you have not scan a card at all. And says time delay error.
0.9.3 scans this card properly.
Attached report, and if allow, I will attach the card.
[report.zip](https://github.com/mgba-emu/mgba/files/9796354/report.zip)

**Comment by endrift** [comment]
I can reproduce.
