### ISSUE TITLE
Multiple different GBA games have multiple instances of missing audio instruments happening on 0.10.0

### ISSUE THREAD

**Issue by MrBareBones** [mgba-emu/mgba#2695]
Just started playing PMD Red Rescue Team on the latest update of MGBA and I noticed right away that some of the audio was messing up and sounding very garbled and scratchy. Opened up the log and whenever the audio issue would occur the log would say as follows 
[ERROR] GBA Audio:	Audio track has invalid instrument
Decided to try a few other GBA games as well to make sure it wasn't an issue with just that game, and a bunch of others like the Sonic Advance Trilogy have the exact same issue.
Is this a new issue that cropped up with the latest release, or has this been something that's always been around?
Also as a side note updated to latest Dev build afterwards to see if maybe the issue was already fixed with another update, and it's still just as bad

**Comment by endrift** [comment]
You're using the experimental XQ audio feature, which is known broken (it's marked as experimental for a reason). Please turn it off and reload the game.
