### ISSUE TITLE
Discord Rich Presence does not update if the game name is too long

### ISSUE THREAD

**Issue by Miss-Inputs** [mgba-emu/mgba#2697]
Apparently rich presence details is limited to 128 bytes per line and this isn't really documented anywhere and you only become aware of the limit once some other project finds out the hard way. Fun!

This almost seems like it wouldn't happen with the inbuilt No-Intro database for game names being used, but there are some multicarts, e.g.: `2 Games in 1 - The SpongeBob SquarePants Movie + SpongeBob SquarePants and Friends in Freeze Frame Frenzy (Europe) (En,Fr,De,Es,It,Nl+En,Fr,De,Es,Nl)`

As for the actual issue with mGBA, I guess it would be more ideal if it was truncated or something, so that all of my friends and peers and loved ones still know how cool I am for playing a 2-in-1 compilation cartridge. Right now nobody would ever know, and I would have to tell them about it manually, which is terrible.

**Comment by endrift** [comment]
Does that include a null terminator or not?

**Comment by endrift** [comment]
I hope you like the commit message
