### ISSUE TITLE
Sound glitching on GBA bios boot

### ISSUE THREAD

**Issue by Enigma776** [mgba-emu/mgba#2698]
Whenever I use a bios in GBA, on boot the audio glitches out which in turn causes the games audio to be glitchy. This happens on every game. If you either skip the bios or don't use the bios the audio is fine. 

Version - 0.10.0 & 0.11-7757-75da9f0a9
System - I9-10850k, RTX 2080Ti 
Games Tested - N/A (All of them do it)

**Comment by Squall-Leonhart** [comment]
afaict, this is due to having XQ GBA Audio enabled

**Comment by Enigma776** [comment]
> afaict, this is due to having XQ GBA Audio enabled

I don't have XQ audio enabled, its not even an option. I use SDL audio

**Comment by endrift** [comment]
Please upload a bug report zip, generated by the File > Report Bug dialog.

**Comment by Enigma776** [comment]
[Log.zip](https://github.com/mgba-emu/mgba/files/10613971/Log.zip)
Here you go.

**Comment by endrift** [comment]
It appears you do have XQ audio enabled, but you were looking at the wrong screen in settings. It's under Enhancements, and it's marked as experimental (and you can probably see why now)

**Comment by Enigma776** [comment]
> It appears you do have XQ audio enabled, but you were looking at the wrong screen in settings. It's under Enhancements, and it's marked as experimental (and you can probably see why now). Please disable it before loading a game and confirm if it fixes things.

Well thats odd as I never enabled it, but yes that has indeed fixed it. bizarre

**Comment by endrift** [comment]
That is strange, but XQ audio is known to be...buggy, and is pending a rewrite.

**Comment by user18081972** [comment]
@endrift before anyone rewrites XQ audio, give this thread a read:
[https://gbatemp.net/threads/hq-sound-in-native-gba-games-is-entirely-possible.625549/ ](https://gbatemp.net/threads/hq-sound-in-native-gba-games-is-entirely-possible.625549/ )
very interesting development I think.
