### ISSUE TITLE
Pokemon Ruby (E) mgba crashes

### ISSUE THREAD

**Issue by ivasim** [mgba-emu/mgba#27]
Returns this in console: 
mgba-qt: ../../src/xcb_conn.c:186: write_vec: Assertion `!c->out.queue_len' failed.

**Comment by endrift** [comment]
This is not a bug in mGBA. Please see:

* http://lists.freedesktop.org/archives/xcb/2013-December/009027.html
* https://bugreports.qt.io/browse/QTBUG-38221
