### ISSUE TITLE
Alleyway - can't move the paddle

### ISSUE THREAD

**Issue by sczther** [mgba-emu/mgba#270]
"Alleyway needs serial to report correct stuff, otherwise it hangs on boot. Fun fact is it can also hang if you plug a gameboy printer into a DMG while alleyway is running." Taisel of GameBoy Online fame

The game quickly flashes garbage, skips the title screen, gets into the game and pauses. When unpaused, the game proceeds as normal, yet you can't move the paddle, rendering the game unplayable.

**Comment by endrift** [comment]
Fixed in 7bcda2daa9cae93ec37e3806d22cb0fe1f259588.
