### ISSUE TITLE
GBA and GBC link issues

### ISSUE THREAD

**Issue by AquaticTyphoon** [mgba-emu/mgba#2702]
Version: 0.10.0
OS: Windows 11 64-bit

Opening a GBC game then GBA in Multiplayer causes a crash.
Opening a GBA game then GBC in Multiplayer causes a speedup in the GBC game.

**Comment by schwjm** [comment]
I can confirm that the second game appears to have synchronization issues in general. In my case, I first observed the second game was running 5-10% fast when trying to figure out why it sounded odd. After trying to proceed further, at some point the frame limiter came off entirely, and the game ran at ~5000fps, while the original window continued to run correctly at ~60fps.

Version 0.10.0 Windows 10 64-bit, as well as latest development build.

**Comment by endrift** [comment]
That's unrelated. There are known synchronization issues, but this is about being "able" to link systems that aren't actually compatible.

**Comment by AmodeusR** [comment]
If the multiplayer opened is a GBC game it gets speed up. I tried to use it with two GBC games and this same issue happened.

**Comment by poesdelal** [comment]
Also, opening 3 multiplayer windows with GB/GBC games cause emulator crash.

**Comment by endrift** [comment]
Again. Not a related bug. You should file a separate bug report.
