### ISSUE TITLE
Backwards motion sensor in Koro Koro Puzzle Happy Panechu!

### ISSUE THREAD

**Issue by GaussTek** [mgba-emu/mgba#2703]
So, motion sensor games work great now, just there's a minor problem with this game Koro Koro Puzzle: Happy Panechu!, which motion seems to be backward (right is left, and left is right) using the Windows build. I'm mentioning "minor" because there's an official way to reverse the tilt sensor in cases you have a GBA SP as this game was designed for normal GBAs (going to game's options once tutorial is done), but would be cool to get these controls right from the beginning.

All other games that use Motion work fine in Windows using a DS4 controller. Yoshi's Topsy Turvy allows you to calibrate motion controls right from the beginning, so I'm not sure if the game was also affected by this. The rest are fine. WarioWare works fine without any calibration, and also the Game Boy Games (Kirby Tilt n' Tumble and Command Master), all these are fine right from start.

Using the latest dev build and also 0.10.0. Thanks a lot for your time on this, you are amazing!

**Comment by endrift** [comment]
Well I found a blending bug in the OpenGL renderer while testing this :sweat_smile: 

Still need to figure out why my Dualsense is weirding out, but maybe I can just grab my DS4 instead.

**Comment by endrift** [comment]
It's definitely backwards with my DS4. However, I need to check on Vita, 3DS and Wii to make sure if it's a problem with the GBA specific implementation or with the tilt API.

**Comment by endrift** [comment]
It's backwards on Vita, 3DS and Switch. I haven't tested on Wii but it's pretty clear it's backwards on ever GBA port.

**Comment by GaussTek** [comment]
Just wanted to confirm that this was fixed. Now all the motion games work as intended. Thank youuuu! ❤️
