### ISSUE TITLE
(PSVita) Audio Issue

### ISSUE THREAD

**Issue by OmegaZeroXIII** [mgba-emu/mgba#2705]
I don't know if this is already reported but it happens that in some Pokemon roms, especially in Hackroms, the audio is delayed at times, sounding terrible even though the game works correctly.

I am using the latest version of the Emulator available (0.10.0) on the PS Vita

**Comment by endrift** [comment]
Please enable the FPS counter and tell me what the value is (roughly) when audio issues occur. The game is probably just running too slow so it sounds weird.

**Comment by endrift** [comment]
Please confirm if it's running at less than 60 fps or not.

**Comment by DriveTGPR** [comment]
> 

I can confirm that I am playing a pokemon hackrom between 40-55 fps on average. Audio is laggy, while gameplay seems fluid.

**Comment by endrift** [comment]
You can't fill the audio buffer if you're not running at full speed.
