### ISSUE TITLE
Audio missing in Superman Game Boy Game

### ISSUE THREAD

**Issue by Dave-Ryder** [mgba-emu/mgba#2711]
Version 0.10.0 and current 0.11. dev version (installed with default settings on Win10, experimental gba sound disabled) have missing sounds and audio in the Superman Game Boy Game.
No sound effect when: 
- picking up items
- killing enemys
Missing music:
- when dieing there should be the Superman theme playing, it is not
- in all background music there seems to be a whole channel missing that should output the main melody

All of this is working in other emulators, like kigb

**Comment by elunesgraces** [comment]
It appears to be an issue across the board, not just in Superman.

I tested the issue in stable 0.10.0 and it also exists in Golden Sun 2 (no sound on selection of actions, etc) but music plays fine.

It works in 0.9.2, so something broke along the way.

**Comment by Squall-Leonhart** [comment]
Not reproducible with 0.10.1

**Comment by endrift** [comment]
I can confirm that this is fixed in 0.10.1.
