### ISSUE TITLE
Incorrect Save File Size on Pokemon Sapphire

### ISSUE THREAD

**Issue by ohyocbz** [mgba-emu/mgba#2712]
I have a save file size issue with Pokemon Sapphire (Rev 2) USA/EUR while using the latest stable release of mGBA 0.10.0

I started playing a new game save from the said ROM and emulator on my computer around this month.

When I tried to dump my save file onto my New 3DS XL via GodMode9 (I have an injected GBA game from NSUI3DS using the same ROM I was playing from my PC), I was surprised that the injecting saves didn't work.

I see no problem on my 3DS CFW (everything up to date), but I noticed that from the Battery folder of my stored save file, the file size for Pokemon Sapphire was displayed as **_129 KB_** instead of 128 KB like my other Pokemon saves.

I attempted to use my former emulator if it could open, but it leads to a new game w/o my save file. The .sav file data couldn't read on PKHex too.

It's weird that my save file only works properly with mGBA emulator for now.

Attached here is the bug report with some screenshots provided:
[20221031_BugReport.zip](https://github.com/mgba-emu/mgba/files/9896312/20221031_BugReport.zip)

Currently running on:
Windows 10 21H2 x64
Intel Core i7-1065G7
NVIDIA GeForce MX110

**Comment by endrift** [comment]
mGBA now appends the RTC data to the savedata. PKHeX now knows what to do with this in the dev builds. It seems GM9 has no idea and just marks it as an error. Please report this to GM9 instead @d0k3

**Comment by d0k3** [comment]
@endrift @ohyocbz - can you give me some more info on that RTC data? Is there some way to recognize the appended data is actually intended (from the save header, or a magic number appended maybe?) and not just garbage data? What would also help is a copy of the 129kb save game (no copyrighted data in there, so it should be fine).

**Comment by CasualPokePlayer** [comment]
It's a footer, not a header. Just ignore anything past 128KB.

**Comment by d0k3** [comment]
I'd still rather properly recognize the data. Maybe you could point me to the place in the mGBA code?

**Comment by CasualPokePlayer** [comment]
https://github.com/mgba-emu/mgba/blob/225369f2b6d784907f0b128098bfd7efba852714/src/gba/savedata.c#L592-L596
https://github.com/mgba-emu/mgba/blob/bb711d311fdfd0bcd2e0925176090e3ea2c2b07e/include/mgba/internal/gba/savedata.h#L97-L101

Even if you don't recognize the data, perhaps it should be a warning rather than an error that it seems to be now?

**Comment by d0k3** [comment]
@CasualPokePlayer - thanks a lot! Well, I'll look into it. For now, it may be best to just ignore it when it's exactly 16byte.

**Comment by endrift** [comment]
It's just the 7 bytes of the RTC's time command, the contents of the control register, and a 64-bit unix timestamp of the unix time this was last updated/latched/whatever. So if you read from a cartridge whatever its time bytes are, and the timestamp you read it at, you can use that in mGBA and it'll know how to correlate that RTC time to the computer's time. It also works when restoring a save to the cartridge. It's supported in FlashGBX atm, maybe more soon.

**Comment by d0k3** [comment]
@ohyocbz - can you open an issue on the GodMode9 repo? I'd still need some more info, like the exact error message. And maybe the svae file. Thanks @endrift and @CasualPokePlayer !

**Comment by ohyocbz** [comment]
@d0k3 hello good day! sure i'll go report in there and try it on my 3ds right away
