### ISSUE TITLE
Game Bug?

### ISSUE THREAD

**Issue by Echdeath85** [mgba-emu/mgba#2715]
So I was playing Pokemon Glazed when I interacted with an NPC and the game froze. Then I proceeded to fall into darkness. I can hear what can only be the Poke Center music. When I move I can hear myself hitting an invisible box and there is no way for me to get out. I saved the game and the state so there is "no" way to get back to a previous save. Please help! ;(((

**Comment by endrift** [comment]
This is a tracker for bugs in mGBA, not a help forum. This is almost certainly a bug in the ROM hack. Please ask them for help instead.

**Comment by Echdeath85** [comment]
I see. Thanks for your info! :)
