### ISSUE TITLE
loading state overwrites existing cheats

### ISSUE THREAD

**Issue by SUCM** [mgba-emu/mgba#2719]
if I have cheats entered and enabled on a game where mGBA created the corresponding *.cheats file, loading a saved state would wipe the cheats and *.cheats file empty

I have saved states on some hard to achieve moments of games for me to go back whenever I want, but loading them would wipe my existing cheats with no way to recover the lost cheats

also, some out of topic questions regarding cheats

1. I tried using search memory feature to create my own cheats, but it doesn't look like mGBA's memory search can find the right data (ex. a unique 32-bit dec value of 3512514). memory view looking at the offset written by working cheats doesn't show the same value as what cheats are writing
2. in cheats window, Remove can't remove a few lines (Remove Lines?)
3. in cheats window, selecting multiple groups and clicking Remove doesn't remove cheats properly. sometime it removes one group, other times it doesn't remove anything
4. in cheats window, is there a way to change line order within a group?
5. in cheats window, is there a way to change orders of groups?

**Comment by endrift** [comment]
![image](https://user-images.githubusercontent.com/605502/200689123-4eea8e08-8398-4b63-bf2c-b2679fa26880.png)
Turn the Cheat codes setting here off.

**Comment by SUCM** [comment]
thanks. that worked

I had thought loading state only change the current ryunning state of the game itself, not cheat nor save, but it looks like default is to overwrite both save and cheat

**Comment by endrift** [comment]
When loading a state the save will always be loaded, otherwise it can break save states, especially in GB games. The load save option will make it write it back to disk; otherwise it's only written back to disk after the game itself attempts to save.
