### ISSUE TITLE
Simple GameShark ROM patch code does not work

### ISSUE THREAD

**Issue by camthesaxman** [mgba-emu/mgba#2724]
I am trying to create a cheat to always enable the National Dex on Pokemon Fire Red by patching the `mov r0, #0` (0x2000) instruction at 0x0806E2A8 to `mov r0, #1`. Using this site https://gamehacking.org/system/gba I generated the code `600DC550 00002001` to accomplish this. Entering it into mGBA's cheats has no affect, and the instruction is not patched. However, by manually patching said instruction using the memory viewer, the National Dex does get enabled.

## Steps to reproduce:
1. Load a clean ROM of Pokemon Fire Red English v1.1 (sha1: dd5945db9b930750cb39d00c84da8571feebf417) into mGBA.
2. Play the game up until obtaining the Pokedex (walk into grass, choose starter, go up to Viridian City PokeMart to obtain parcel, deliver parcel to Professor Oak in Palette Town lab, Oak gives Pokedex - takes less than 5 minutes).
3. Save the game.
4. Open the Tools -> Cheats dialog.
5. Enter the code `600DC550 00002001`, select GameShark for the code type, and click Add New Code. The code should be enabled (checked), and you may give it a name if you wish.
6. Verify that the .cheats file created for the game matches the following:
```
!GSAv1
# National Dex
600DC550 00002001
```
7. In the game, press start to open the menu, and press A on the Pokedex option.

## Expected result:
The 16-bit value at address 0x0806E2A8 should be patched to 0x2001 and the **National** Pokedex should be unlocked (green bars and both "NUMERICAL MODE: KANTO" and "NUMERICAL MODE: NATIONAL" options).

## Actual result:
The cheat has no effect, and only the Kanto Pokedex is unlocked (brown bars and only has the NUMERICAL MODE option under Pokemon List). As mentioned above, changing the byte at 0x0806E2A8 to 01 using the memory viewer does allow the National Pokedex to appear, but the cheat does nothing.

**Comment by endrift** [comment]
@camthesaxman Please try with the changes mentioned; the gamehacking.org converter _does_ appear to be broken after all.

Use `60037154 00002001` though, since the patch code shouldn't include the base address of the ROM, and is in fact filtered out.

**Comment by autofire372** [comment]
Strangely enough, that code does not work on its own, but _does_ work if it's encrypted first (`D3C95F54 156F2ECC` according to AR Crypt).
