### ISSUE TITLE
Libretro Core has no sound

### ISSUE THREAD

**Issue by 123randomuser321** [mgba-emu/mgba#2734]
There seems to be an issue with outputting sound when using the Libretro Core.
I tried multiple output drivers (Pulse, Alsa, etc) and none made a sound. Menu (RetroArch 1.13.0) worked fine.
Qt-Frontend built from the same Revision outputted sound just fine.

Tested:
0.10.0 (686eee4e20cc555b90810811f2d0d6f8b9b393c5);
Latest Git (6aa558c4a0525c72ed69bf86f5c387779751012c)

Funnily enough, the downstream fork (https://github.com/libretro/mgba/commit/ec5ecb26deba8d7ac830fc66ade9fac0eeaeb4ae) did output sound.

**Comment by CasualPokePlayer** [comment]
https://github.com/libretro/mgba/blob/ec5ecb26deba8d7ac830fc66ade9fac0eeaeb4ae/src/platform/libretro/libretro.c#L1697-L1728

Sees this code (with the audioCallback) is not present upstream. The only invocation of audioCallback is in _postAudioBuffer (which is only used in GB/C mode).

**Comment by endrift** [comment]
Broke in f7d594a8b5b254f1e12258d9a3fe065d312ae6bc. Looks like I did a partial-resync with the downstream, and forgot to pull all of the audio code.
