### ISSUE TITLE
OSD broken on Modern macOS build (?)

### ISSUE THREAD

**Issue by kappndolphin** [mgba-emu/mgba#2736]
When I use shortcuts to to Quick Saves, I’m never quite sure if it worked. Having the option to display alerts would help for that and many other functions.

**Comment by endrift** [comment]
This is already present, just turn on the OSD in interface.

**Comment by kappndolphin** [comment]
It was enabled, but no messages appear. Did some googling. I can see what they’re supposed to look like now, but really, nothing appears. Disabled/enabled/applied, nothing.

M1 Mac Mini, Ventura, latest. Latest mGBA.

**Comment by endrift** [comment]
It's possible they're broken on M1 Mac. I'll check a bit later.

**Comment by endrift** [comment]
I can confirm it's broken.
