### ISSUE TITLE
emu:runFrame() Freezes Emulator

### ISSUE THREAD

**Issue by ann4belle** [mgba-emu/mgba#2738]
As the title says - when calling `emu:runFrame()` in the scripting interface, the emulator freezes. Not sure what I'm doing wrong here.

**Comment by endrift** [comment]
Are you running it in a loop? If so, don't do that. You're supposed to use callbacks.

**Comment by ann4belle** [comment]
I am not - I'm calling it once. Just "emu:runFrame()" in the entry box.

**Comment by ann4belle** [comment]
<details open>
<summary>Like this</summary>
<br>
![image](https://user-images.githubusercontent.com/18199611/204470147-176414d4-dd40-402f-8457-ba2de400d6fc.png)
</br>

Loading a ROM of Ruby, pausing with CTRL+P, then running `emu:runFrame()` like this causes the emulator to freeze up, and I have to forcibly kill it.

**Comment by ann4belle** [comment]
Tried on build 686eee4e20cc555b90810811f2d0d6f8b9b393c5, it works literally once per pause. If I pause, the first time I run `emu:runFrame()`, it properly advances one frame as if I'd press CTRL+N. Running it a second time without resuming and re-pausing emulation causes a freeze. This is not the behavior in v0.10.0 - it freezes each time.

More details: when the freeze occurs, `emu:runFrame()` remains in the command entry textbox rather than moving to the list of previous commands. Also, running `emu:runFrame()` while the game isn't paused does not trigger a freeze.
