### ISSUE TITLE
MGBA not opening

### ISSUE THREAD

**Issue by Metalboy76** [mgba-emu/mgba#2745]
Hello since the last month I have been having a problem, where MGBA will not open, it used to open but now it will not. I thought that maybe it was because I was using an older version, so I searched and downloaded the latest version, 0.10.0 but it still does not work.
If you have any suggesting it would be appreciated.

**Comment by endrift** [comment]
Can you upload the config.ini and qt.ini files? There have been scattered similar reports, especially on 0.10.0. If you used the installer, they'll be in %APPDATA%/mGBA. If you used the portable version, they'll be in the folder with the program.

**Comment by Metalboy76** [comment]
No, it says i doesn't support that file type.

**Comment by endrift** [comment]
Zip them first.

**Comment by Metalboy76** [comment]
[config.zip](https://github.com/mgba-emu/mgba/files/10189117/config.zip)

**Comment by endrift** [comment]
Can you check if the latest development build launches fine? If so, can you attach the zip generated by File > Report Bug? You'll need to make the filename end with .zip agian.

**Comment by dftf-stu** [comment]
Just to say I have the same issue on my laptop.

**The latest stable-release, 0.10.1, does not work**.  I extract the portable 7z archive (64-bit version) to a folder, double-click the "mGBA.exe" file and it creates some additional files (config.ini, library.sqlite3, nointro.sqlite3).  But after about 3 seconds, the "mGBA.exe" process just disappears from _Task Manager_, and no UI appears.  But a crash-dump file does get added to "%UserProfile%\AppData\Local\CrashDumps".

However the **latest development version** (0.11-7891-d08b307be) **does work**.

**Comment by endrift** [comment]
@Metalboy76 I still need you to test with a dev build as mentioned above

**Comment by Metalboy76** [comment]
I used the portable version  of the dev and it didn't work.(all my other emulators work its just MGBA that doesn't)

**Comment by Metalboy76** [comment]
I downloaded the Wii version, I eventually found where it was located and it works. The only problem is that ss0 saves don't load  ss1 saves do though.

**Comment by endrift** [comment]
I need information about your computer. OS, graphics card, are graphics drivers installed, etc.

**Comment by Metalboy76** [comment]
The OS is Windows 10 home 64-bit (10.0, build 19045) I don't know how to find graphics card or drivers.

**Comment by endrift** [comment]
Run dxdiag (you can just type it into the start menu). The information is on the Displays tab. Just take a screenshot of it and post it here.

**Comment by Metalboy76** [comment]
![Screenshot (1)](https://github.com/mgba-emu/mgba/assets/34409338/9c8a63eb-be1e-4c5c-94dd-e5799051abfb)

**Comment by endrift** [comment]
That's a Radeon Vega 8 integrated GPU. Please download and install drivers from AMD's website using the auto-detector: https://www.amd.com/en/support

Then try again.

**Comment by Metalboy76** [comment]
I downloaded  the drivers and it works now, thank you, fare thee well.
