### ISSUE TITLE
OpenGL renders a black screen as of build 7787

### ISSUE THREAD

**Issue by TheGershon** [mgba-emu/mgba#2746]
As of revision [7787-6aa558c](https://github.com/mgba-emu/mgba/commit/6aa558c4a0525c72ed69bf86f5c387779751012c), OpenGL renders a black screen while Software and OGL 1.x display normally. 
Running Windows 64-bit, portable, nvidia GPU
![asdf](https://user-images.githubusercontent.com/6880780/206177233-90d8d33f-cda7-494a-8b19-e7243ae7526e.png)
![fdsa](https://user-images.githubusercontent.com/6880780/206177241-b7ebb3ea-eb19-4f7e-a7c2-e12146967ff3.png)

**Comment by endrift** [comment]
Please upload the zip file generate by the Report Bug dialog.

**Comment by TheGershon** [comment]
> Please upload the zip file generate by the Report Bug dialog.

[black screen 7787.zip](https://github.com/mgba-emu/mgba/files/10187885/black.screen.7787.zip)

**Comment by endrift** [comment]
Hm, strange. Nothing stands out as unusual in your config or your hardware. Does this happen if you turn off the OpenGL Renderer in the Enhancements tab? Make sure to turn it off before loading the game, just to make sure.

**Comment by Testsr** [comment]
I can replicate this. This black screen only happens when both Video Renderer and display driver are OpenGL, any other combination has a normal screen, including Open GL (force 1.x).
[report.zip](https://github.com/mgba-emu/mgba/files/10193367/report.zip)

**Comment by TheGershon** [comment]
> Does this happen if you turn off the OpenGL Renderer in the Enhancements tab?

It does not
![image](https://user-images.githubusercontent.com/6880780/206704657-ad4319f5-d7e5-4bed-91d4-6a97ceb31ae5.png)

**Comment by endrift** [comment]
I can only seem to reproduce this on Nvidia cards. Which is, you know, most users. Bumping to release blocker.
