### ISSUE TITLE
Multiplayer - Player 0 of 2

### ISSUE THREAD

**Issue by JonathonAshworth** [mgba-emu/mgba#275]
On Ubuntu 15.10, mgba v0.5.0, I can't seem to get multiplayer connectivity working. Both windows show "Player 0 of 2", and don't appear to be connected.

Any ideas what might be causing this?

![screenshot from 2016-06-06 14-42-39](https://cloud.githubusercontent.com/assets/1953116/15812194/083c3384-2bf5-11e6-8c0f-37cf49f152d6.png)

**Comment by PannenkoekenNL** [comment]
Is one player host and the other join?

**Comment by JonathonAshworth** [comment]
I'm not sure. I just opened the second window using "File -> New Multiplayer Window", do I have to do something else to connect the two?

**Comment by PannenkoekenNL** [comment]
I mean in the game itself.

**Comment by JonathonAshworth** [comment]
Oh, I don't think there's any concept of host in the game when using the link cable, at least not by this point. When you try the wifi/bluetooth/whatever it is next to it it just says "the device is not configured properly" or similar

**Comment by hartloosli** [comment]
I'm seeing this same error on Mac osx 10.11, mgba 0.5.0

**Comment by endrift** [comment]
Multiplayer support in 0.5 is currently in a transitional stage. It'll be rewritten soon; what you're seeing now is just a standin until it's put back. Until then, please use 0.4.1 for multiplayer.
