### ISSUE TITLE
GBA Multiboot ROMs Do Not Have BIOS Force Skipped

### ISSUE THREAD

**Issue by CasualPokePlayer** [mgba-emu/mgba#2753]
Buggy code is here: https://github.com/mgba-emu/mgba/blob/694b80d289cdd1eadf47223bc2d4f2bbef0393e6/src/gba/core.c#L703

MB is held in gba->mbVf rather than gba->romVf, so gba->romVf will just be null.

**Comment by endrift** [comment]
If this is present in 0.10.0, you should add a changelog entry.
