### ISSUE TITLE
[Feature Request] RetroAchievements support on desktop/homebrew builds

### ISSUE THREAD

**Issue by darkreader2636** [mgba-emu/mgba#2756]
The offical GBA emulator of RetroAchievements is VBA-M and inaccuracy sometimes makes playing games harder. https://github.com/RetroAchievements/RAIntegration can help

**Comment by shenef** [comment]
Duplicate of #2232
In the meantime you can try BizHawk (uses mGBA for GBA games) which has recently added RetroAchievements support ([#3407](https://github.com/TASEmulators/BizHawk/pull/3407)), it's not yet part of the latest release but it is in the development builds and will be in version 2.9
