### ISSUE TITLE
Cannot access game override (bug) and display filters (feature request).

### ISSUE THREAD

**Issue by GauravSahare1993** [mgba-emu/mgba#2757]
Hello sir, all ROM hacks are working properly, only problem is "I cannot access game override settings (realtime clock)"
I request to add more display filters (which is available on VBA-M), because games are showing either very sharp or very blur. if both are fixed, then mGBA will be incredible. 😊
![Screenshot (7)](https://user-images.githubusercontent.com/109745579/208226687-0fe73579-7d33-4e0a-a2e2-da38a8c1b476.png)

**Comment by endrift** [comment]
You can turn on an override while the game is running. You have to set the overrides *before* loading the game.

There's already a ticket tracking adding additional shaders (which mGBA already has several of): #304
