### ISSUE TITLE
Pokemon Pinball R&S Stuttering

### ISSUE THREAD

**Issue by Jobenblue** [mgba-emu/mgba#2763]
I have provided https://youtu.be/ATHX1bkZRwU for video footage of this. When I load into any area, the game stutters, even though fps is still high. The game massively slows down for initial animations to play and then resumes as normal. Entering the same area twice, like Kecleon's Minigame on Ruby table, STILL has the same long initial load. Default settings. I think this is a sync issue

Windows 10, 3080laptop, i9-10980HK. I run some 10 to 7 program like StartIsBack and OldNewExplorer, I know that causes issues with PCSX2

**Comment by Jobenblue** [comment]
Sounds like #2199

**Comment by endrift** [comment]
It's not. I assume this is with Game Boy Player features enabled?

**Comment by Jobenblue** [comment]
enabling/disabling enhancements> idle loops> "Enable Game Boy Player features by default" has no effect.

I went back and ran on 0.9.0 win64 and it works like it should. will test further

**Comment by endrift** [comment]
That helps a lot, thanks.
