### ISSUE TITLE
Radical Red new glitch

### ISSUE THREAD

**Issue by austinh579** [mgba-emu/mgba#2766]
After leaving the pokemon center, my screen turned black and started making a humming noise. This is the first time it has happened, and I have no idea how to fix it.

Here is the file from the bug report:
[gba bug report.zip](https://github.com/mgba-emu/mgba/files/10326787/gba.bug.report.zip)

**Comment by endrift** [comment]
These things are usually bugs in the hacks themselves.

**Comment by austinh579** [comment]
> These things are usually bugs in the hacks themselves.

Do you have an idea how to fix it?

**Comment by endrift** [comment]
No, you should contact the mod maker instead. Unless it's shown to be a bug in mGBA and not in the ROM hack itself, I'm going to tentatively close this.
