### ISSUE TITLE
No fast forward method generates any increase in FPS

### ISSUE THREAD

**Issue by alpaca-ninetynine** [mgba-emu/mgba#2767]
Running commit: 0a4cafcd57637b17c8efba9b607f81d5e4511584. I built from source.
OS: archlinux x86_64, kernel 6.1.1-arch1-1
Hardware: AMD Ryzen 7 5700G with Radeon Graphics

Under normal circumstances, pressing the tab key, pressing shift + tab, or checking the "fast forward" box under emulation should cause speedup, however the game remains at 60fps. I have confirmed the keybinds for fast forward are still set as in the screenshot below:
![2022-12-30-193027_307x240_scrot](https://user-images.githubusercontent.com/121699663/210126818-11a3cc96-30d6-4c14-9635-4a291c7fdb84.png)

Additional info: Changing "Video renderer" from "OpenGL" to "Software" in the "Enhancements" settings tab gives working fast forward. At Endrift's request, I rolled back to 0271f122809f8c009549543f3084f4a9c8762a7e and confirmed I could fastforward, then moved to 6aa558c4a0525c72ed69bf86f5c387779751012c and fastforward stopped working again (both tested with OpenGL enhancements on).

My bug report zip can be found here:
[fastforward_bug_123022.zip](https://github.com/mgba-emu/mgba/files/10326872/fastforward_bug_123022.zip)

**Comment by endrift** [comment]
Seems to only affect AMD Vega GPUs.

**Comment by endrift** [comment]
It is _unlikely_ this will affect anything, but does changing the Audio Driver in settings affect this at all?

**Comment by alpaca-ninetynine** [comment]
The audio driver was SDL in this report. I don't see any change from setting the audio driver from SDL to Qt Multimedia.

**Comment by endrift** [comment]
This appears to be an issue with Mesa's glthread and the radeonsi driver. Running with mesa_glthread=false works around the issue. I'm unsure if this is an mGBA bug or a radeonsi bug. I will be filing a bug on the mesa tracker soon and link it here.

**Comment by endrift** [comment]
Filed here: https://gitlab.freedesktop.org/mesa/mesa/-/issues/8035

Probably going to have to deschedule this and release with it still as a problem.

**Comment by endrift** [comment]
Worked around in 9df06383b575c0fad5fc4a2846bcb65cfcdd99c9, hopefully.

**Comment by alpaca-ninetynine** [comment]
Built and tested 9df06383b575c0fad5fc4a2846bcb65cfcdd99c9 and fast forward functionality is restored. Thank you!
