### ISSUE TITLE
[3DS][Link Cable] Feature Request support link cable on 3ds over wifi

### ISSUE THREAD

**Issue by headhunter45** [mgba-emu/mgba#2768]
This would be really cool to do link cable stuff with pokemon gba games like the virtual console games for gb and gbc do it.

**Comment by endrift** [comment]
This isn't feasible on 3DS, given the hardware constraints.

**Comment by WinUser-Generic** [comment]
gpsp is better for that, includes the function in retroarch core of 3ds, but the performance is not best
