### ISSUE TITLE
Freezeing when I go to load the rom. I am Us 0.10.0

### ISSUE THREAD

**Issue by Jeremia0207** [mgba-emu/mgba#2770]
Everytime I try to go load a rom my thing freezes and says that my mgba is not responding. So what I mean is that I go and click load rom and then a soon as I do that it freezes I can click recent files and load a recent one but I cant load a rom regularly

**Comment by endrift** [comment]
Please attach a zip generated by File > Report Bug. Also upgrade to 0.10.1 while you're at it.

**Comment by endrift** [comment]
Closing due to lack of reply.
