### ISSUE TITLE
mGBA adds an extra line of data to save file making it incompatible with 3DS VC injection

### ISSUE THREAD

**Issue by AustinZM** [mgba-emu/mgba#2772]
Rom: Pokemon Unbound

I don't know if this is exclusive to Unbound or if it presents in other games as well, but saving inside of mGBA generates excess code that makes it impossible to bring a save file back to a 3DS VC environment without manually editing and removing the line with a hex editor. Does this extra line of data serve any purpose?

The line in reference: 

> 00020000 23 01 03 02 14 04 16 40 30 7C B4 63 00 00 00 00

[Save Files.zip](https://github.com/mgba-emu/mgba/files/10339152/Save.Files.zip)

**Comment by metroid-maniac** [comment]
That's the data from the game RTC and the system time. What tool are you using to inject the save to the 3DS VC?

**Comment by endrift** [comment]
Not a bug. I'm probably gonna add an "export without RTC data" option at some point but this is actually important for getting full compatibility with saves from hardware.
