### ISSUE TITLE
Kirby Tilt'n' Tumble sound issue with voices is back again in latest builds

### ISSUE THREAD

**Issue by GaussTek** [mgba-emu/mgba#2775]
This issue which was fixed a few months ago https://github.com/mgba-emu/mgba/issues/2655, is happening again in the latest dev build mGBA-build-2023-01-01-win64-7820-819d19ddd. Dunno from what build it started to happen again.

Thanks for your amazing work as always!!

**Comment by endrift** [comment]
I'm...not sure how that's possible. But I'll look into it.

**Comment by endrift** [comment]
I figured out how it was possible.
