### ISSUE TITLE
Enhancement: Option to load a different battery save file

### ISSUE THREAD

**Issue by adcgx** [mgba-emu/mgba#278]
I'm missing the ability to load an arbitrary battery .sav/.sav2 - it can be useful for multiplayer, and allows for importing/exporting saves from/to other emulators.
Currently, the workaround is to place/replace the [romFileName].sav file next to the [romFileName].gba, but this is very cumbersome, especially for local multiplayer.

**Comment by endrift** [comment]
Would this be for loading a temporary save, or would it write back to the file, too? This should be super easy to implement either way.

**Comment by adcgx** [comment]
I think it's more intuitive to have it import a temporary save and keep the convention of always writing battery saves to [romFileName].sav

I know this might be a lot to ask, but I would LOVE to have this feature in the next nightly! I've been hosting a Pokémon tournament, and wanted to use mGBA for multiplayer fights - however, people played on different emulators, so my idea was to grab their battery-files, boot them up in mGBA, and do a multi-moniter setup with xbox controllers etc... Sadly, the workaround I mentioned apparently does NOT work and makes mGBA crash :(
I really need a version of mGBA with support for battery import saves ASAP - the only other GBA emulator with network emulation AND support for multi-window input I could find is a beta of VGA-M, but the network emulation is sooo bad.

**Comment by endrift** [comment]
Well I meant that it would save back to that file until you reloaded the ROM, at which point it would revert--but loading the foreign save again would give you what you'd saved since loading it the first time, as opposed to the pristine file you, say, downloaded off the internet, or the version before you copied it.

Unfortunately I am out of the country for another week and won't be able to test an implementation of this until I get back, although I can in theory push untested code; it's just not a really good idea.

**Comment by adcgx** [comment]
That seems like a better implementation, and would avoid a 'Are you should you want to do this?'-warning.

I just found and that it's actually not the foreign battery save that causes mGBA to crash, but something entirely different - apparently, loading a ROM from the same folder as mGBA.exe (or a nested folder) causes it, for odd reasons - I could have sworn I've done that before. I'll test a little more and post separate issue for it.

**Comment by endrift** [comment]
I just pushed a half-baked, untested implementation. The saves you load will vanish into the ether after you quit the game, so saving back to it will do nothing. I'll add a separate thing for loading a foreign file you can save back to, but I'll have to do that later.

**Comment by endrift** [comment]
_Finally_ fixed in c207675.
