### ISSUE TITLE
Setting Fast Forward Speed Is Incorrect For Me In 0.10.0

### ISSUE THREAD

**Issue by InvisibleHunt** [mgba-emu/mgba#2780]
I recently downloaded the new 0.10.0 mgba, coming from the 0.5.0 I like the zoomed in Gameboy. Anyways Whenever I try setting the fast forward speed to anything, like 2x or 5x speed, it doesn't apply and it just increases the speed by an unknown amount. 60 fps -> ~780-900+ fps. Still occurs if I set it to 2x speed so it's supposed to be 120fps but still ends up at the ~780-900+ fps.

Windows 10 OS 64bit, Intel i7-7700 cpu 3.6ghz, 16 GB Ram, Nvidia 1060 3gb.

Saves were created by the 0.5.0 and using the 0.10.0 version causes this bug for me. Games I tested this on were Super Mario Advance 4 Super Mario Bros 3, Pokemon Fire Red, and Pokemon Emerald.
Anyways thanks for the continous updates to mgba.

**Comment by endrift** [comment]
I don't have enough information. Please upload the bug report zip generated by File > Report bug.

**Comment by InvisibleHunt** [comment]
[BugReportIH.zip](https://github.com/mgba-emu/mgba/files/10387437/BugReportIH.zip)

**Comment by endrift** [comment]
You've only set the fast forward (toggle) ratio, not the fast forward (held) ratio. How are you engaging fast forward? If you're holding tab, then, well, that's expected behavior: you didn't set the ratio for that style.

**Comment by InvisibleHunt** [comment]
Thank you it seems I was used to the 0.5.0, where you can change the held and the toggle from the emulation tab.

Thank you for your assistance.
