### ISSUE TITLE
Freeze after crash and hard reset

### ISSUE THREAD

**Issue by alpaca-ninetynine** [mgba-emu/mgba#2784]
Running commit: 9df06383b575c0fad5fc4a2846bcb65cfcdd99c9
OS: archlinux x86_64, kernel 6.1.4-arch1-1, X.org, awesomewm
Hardware: AMD Ryzen 7 5700G with Radeon Graphics

I've attached my debug zip with a state for reproduction of the crash here.
Steps to reproduce: Load the attached state, press A for a crash. Then press ctrl R for a hard reset and attempt to interact with the window. The window should be completely unresponsive. 
[reset_freeze_011323.zip](https://github.com/mgba-emu/mgba/files/10413348/reset_freeze_011323.zip)

**Comment by endrift** [comment]
Oops, I meant to close this one instead of #2785.
