### ISSUE TITLE
Sacred Stones all the sudden can't load save state, resets progress.

### ISSUE THREAD

**Issue by felix1600** [mgba-emu/mgba#2787]
[1.13.23.zip](https://github.com/mgba-emu/mgba/files/10415531/1.13.23.zip)

[WARN] GBA Savestate:	Old savestate: expected 01000007, got 01000001, continuing anyway
[WARN] GBA Savestate:	Savestate created using a different version of the BIOS: expected 5A262303, got 590E6155
[INFO] Status:	State 1 loaded

After a few nearly identical successful attempts, all the sudden my save state opened as an image and did not start the game. When opening the game normally, all progress was wiped as if it were a fresh open. Why does it not recognize my save or why can't my save state open?

**Comment by endrift** [comment]
Your savestate is ancient. Savestate support between versions is best effort and never guaranteed to work.
