### ISSUE TITLE
Cannot run multiboot ROM if BIOS file is used

### ISSUE THREAD

**Issue by LunarLambda** [mgba-emu/mgba#2789]
Even if "Skip BIOS Intro" is used, trying to open a multiboot ROM only runs the BIOS startup without loading the ROM into the emulator's memory at all.

If no BIOS file is used, the ROM runs correctly from EWRAM, both as ELF and as a raw ROM.

On 0.10.0 and 0.11-7778-694b80d28.

**Comment by endrift** [comment]
I thought this got fixed recently. Can you check a dev build?

**Comment by endrift** [comment]
See also #2753

**Comment by LunarLambda** [comment]
ah yeah, the 0.10.1 appimage works. thank you!
