### ISSUE TITLE
Enhancement : Android build project

### ISSUE THREAD

**Issue by zminhquanz** [mgba-emu/mgba#279]
you can see the beginning of UI , sorry i'm not done yet
![image](https://cloud.githubusercontent.com/assets/11285640/15885140/408aa550-2d7f-11e6-86fb-e8b1c3a8d654.png)
![image](https://cloud.githubusercontent.com/assets/11285640/15885159/5f8c7adc-2d7f-11e6-8a7d-f14f2331742f.png)
![image](https://cloud.githubusercontent.com/assets/11285640/15885147/4e42830c-2d7f-11e6-865a-6fca7dc53722.png)

**Comment by endrift** [comment]
I already have work on an android version. You can help with it when it gets further along, but it's closed source for the time being. (It will be open-sourced when it is released.)
