### ISSUE TITLE
Mgba not opening after downloading it

### ISSUE THREAD

**Issue by EthanGhoul** [mgba-emu/mgba#2791]
mgba won't open after downloading it. i have tried x64, portable x64, x32, portable x32(newest versions) even though it used to work (version 0.10.1.)

**Comment by endrift** [comment]
Can I get some information about your computer? What version of windows? What GPU and CPU? How big is your screen?

**Comment by ultrasuperpingu** [comment]
I don't know if my problem is identical but sometimes, when I launch mGBA (with command line, with the rom file as argument), the window just doesn't show up. It happens maybe once in 10-20. But the process is launched and consume processor resources.
My setup is:
 * mGBA version is 0.10.0: (2022-10-11) (portable)
 * Windows 11
 * AMD Ryzen 5 5600H with Radeon Graphics, 3301 MHz, 6 cœur(s), 12 processeur(s) logique(s)

**Comment by endrift** [comment]
Closing due to lack of reply. I know there was an issue fixed recently (in latest dev builds), but without a reply it's impossible to know if this fixes that.

**Comment by ultrasuperpingu** [comment]
Just tried the last dev build and my problem is still present. Is there a command line argument or something to get more data ? I tried `mGBA rom.gba -l 4095 > log.txt 2>&1` but it doesn't write anything until the program quit gracefully (which it doesn't when the windows does not show up).
When it does, I got:

`QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined`

If this could help...
