### ISSUE TITLE
ARM builds

### ISSUE THREAD

**Issue by pattmax00** [mgba-emu/mgba#2792]
Just a question. Are there any 32bit arm builds of mgba available? I have been trying to cross compile this for two-days and am finding it quite difficult.

If not, what is the path of least resistance for cross compiling this, OS doesn't matter I will setup anything at this point to try and compile.

**Comment by endrift** [comment]
There are builds for 3DS and Vita. I suspect that's not what you meant, so you should probably be more specific.

Also, this isn't a help forum, and this isn't a bug.
