### ISSUE TITLE
Loading savestates break PSG channels

### ISSUE THREAD

**Issue by getCursorsExe** [mgba-emu/mgba#2793]
Savestate implementation does not capture the state of PSG channels, causing minor audio glitches after loading a savestate.
This relates to #496 but that issue only occured due to PSG and FIFO channels desyncing on state load.

**Comment by endrift** [comment]
This is categorically false. It's possible that some state isn't captured properly, but it absolutely does capture the state. Please give me an example of a game and scene in the game where I can actually reproduce this glitching.

**Comment by endrift** [comment]
Next time please file a real bug report, not a nonsensical analysis of a poorly described bug with no real information. I managed to fix this based on https://github.com/TASEmulators/BizHawk/issues/2749, which is not a bug report you filed, nor contributed to at all. This bug report alone was useless.
