### ISSUE TITLE
EWRAM waitstate setting crashes mgba when set to 0

### ISSUE THREAD

**Issue by Lorenzooone** [mgba-emu/mgba#2802]
Even though real GBAs do not crash from executing the included ROM (and properly set EWRAM waitstates to 0 for a while, to then change it), mgba does.
You should really never do this anyways, so it's up to you deciding on whether to keep the behaviour as is, or not. I'll adapt my code. :)

Thanks!
[ewram_reg_test.zip](https://github.com/mgba-emu/mgba/files/10514817/ewram_reg_test.zip)

**Comment by endrift** [comment]
As discussed on Discord, I currently have no intention of changing this behavior.
