### ISSUE TITLE
Cascading timers need to be enabled to count

### ISSUE THREAD

**Issue by LunarLambda** [mgba-emu/mgba#2812]
```c
bool sioWait()
{
    // 50 ms timeout
    REG_TM0CNT = TIMER_FREQ_16KHZ;
    REG_TM0VAL = 65536 - 819;
    REG_TM1CNT = TIMER_FREQ_CASCADE;
    REG_TM1VAL = 0;
    REG_TM0CNT |= TIMER_ENABLE;

    while (!REG_TM1VAL);

    return hadTrans;
}
```

Had this code hang on hardware, despite working fine in mGBA. Turns out hardware demands the TIMER_ENABLE flag be set on both TM0 *and* TM1 for TM1 to count up.

**Comment by endrift** [comment]
This sounds like a simple oversight on my part.

**Comment by endrift** [comment]
![image](https://user-images.githubusercontent.com/605502/216566693-515b8a89-c09a-42b3-a1dc-9ca6a30ffb6f.png)
I really should look for more of these TODOs in my code.

**Comment by LunarLambda** [comment]
😅
