### ISSUE TITLE
Last Modified Date for SRAM Saves are not updating 

### ISSUE THREAD

**Issue by ugoplatamia** [mgba-emu/mgba#282]
Was playing FF5 Advance, and after saving, the last modified date doesn't get updated. This is problematic because I use a syncing application to keep everything up to date. It checks aganist the last modified date and the updated file isn't synced.

**Comment by endrift** [comment]
I have a patch for this, but I haven't tested it on Windows yet.

**Comment by endrift** [comment]
Confirmed the patch works on Windows, and has been committed.
