### ISSUE TITLE
mGBA won't use the correct paths when launched by an associated .gba/.gbc/.gb file

### ISSUE THREAD

**Issue by Mateo-Git** [mgba-emu/mgba#2826]
Hi, I'd like to report a bug I found while using mGBA the other day under Windows (tested on Windows 10 x64). When launching a game via an associated .gba/.gbc/.gb file with mGBA the game won't use the correct paths. Instead of using the Save/State/Cheats folders inside the mGBA folder, the emulator will create new folders where the .gba/.gbc/.gb file is located and use those instead.
This bug is still present in the latest version. Thanks.

**Comment by endrift** [comment]
This is likely related to #2496. I'll take a look soon.

**Comment by endrift** [comment]
I believe I've fixed this issue, but I won't be able to include the fix in 0.10.2. It will be in 0.11.0 and dev, however.
