### ISSUE TITLE
mgba can't create a save for the game Ueki no Housoku Shinki Sakuretsu! Nouryokumono Battle

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#283]
I think the cause of the problem is that mgba thinks this game uses a Flash 512Kb save whereas the game actually needs EEPROM (VBA-M works fine with the game and it uses an EEPROM save).

I wanted to overwrite the mgba default save type but I couldn't change it (the Game override options are disabled for some reason)

**Comment by endrift** [comment]
Game overrides are currently disabled after adding GB games and I need to put them back. I'll add an override for this right now.

**Comment by RafaelTrepaUnCarballo** [comment]
Thanks, endrift!

**Comment by endrift** [comment]
Fixed in https://github.com/mgba-emu/mgba/commit/fb7ecb8079aa848c1b6811c8a5fdc692dd201bed, along with DBZ: Legacy of Goku II, which was reported as broken by a user.
