### ISSUE TITLE
Add shortcuts for increase and decrease fast-forward speed

### ISSUE THREAD

**Issue by pmbarrett314** [mgba-emu/mgba#2830]
It would be useful to be able to bind a shortcut for incrementing or decrementing the fast-forward speed. My use-case is using mGBA on Steam Deck or with Steam Controller, where it would be nice to be able to bind the otherwise unused shoulder buttons or back paddles to give fine grained control of the fast-forward setting without having to use a point-and-click menu. For example if I'm fast-forwarding and having trouble moving a cursor to a specific point on a map, I could slow it down slightly so I don't overshoot.

**Comment by endrift** [comment]
I've been tempted to add analog fast-forward support where you can pull an analog trigger a different amount for a different ratio. This is a bit different, but it sounds good too.

**Comment by TamTrongNguyen** [comment]
Hello, my name is Tam Nguyen and I'm a student at UT taking the virtualization class cs360v. Can I request to work on this issue?

**Comment by endrift** [comment]
This seems like a decent first issue, yeah. It has nothing to do with virtualization though.

**Comment by sam-gupta-git** [comment]
^ I am also in Tam's group, and I have added this enhancement here #2903
