### ISSUE TITLE
[feature request] Screen Filters like Nintendo Switch Online GBA Emulator

### ISSUE THREAD

**Issue by rrrcabral** [mgba-emu/mgba#2834]
nintendo recently added Gameboy Advance to Switch Online, and their emulator screen filter is absolutely BEAUTIFUL!
really feels like original hardware,
pixels no longer appear square and jagged.
is there a possibility to extract this and add in the MGBA something just as good?

**Comment by endrift** [comment]
It cannot be extracted, but it might be able to be reproduced. However, I don't have NSO+ so I can't even eyeball it directly like I did when writing the AGB-001 and AGS-001 shades.

**Comment by rrrcabral** [comment]
the NSO can be played in Ryujinx switch-emulator for example, maybe you can study the code this way

**Comment by rrrcabral** [comment]
the Ares emulator(emulator of Wonderswan and NeoGeoPocket) also has a beautiful shader called "phosphorish" that looks like a real screen too

**Comment by profi200** [comment]
The filters which reproduce the AGB-001 colors the closest are these: https://forums.libretro.com/t/real-gba-and-ds-phat-colors/1540/220
Specifically the "gba-color" shader. [Comparison](https://i.ibb.co/MBXQtmC/all-sbs.png) i made a few weeks ago (no color correction vs. gba-color).

The ones Nintendos GBA emu uses on Switch are a trade off between reproducing the colors and saturation if i understand right. So they are by no means accurate. Pokefan531 is trying to reproduce these filters anyway but the current implementation is not completely right yet according to his posts.

**Comment by endrift** [comment]
I've ported pokefan531's shader over
