### ISSUE TITLE
Dragon Ball Z: Buu's Fury override

### ISSUE THREAD

**Issue by Axiphel** [mgba-emu/mgba#284]
Sorry I didn't realize sooner but it needs an override just like Legacy of Goku II.

**Comment by Axiphel** [comment]
Nevermind it doesn't!

**Comment by endrift** [comment]
Well, it DID, but I added that one a while back.

**Comment by Axiphel** [comment]
Cool.  Now to play the waiting game until the libretro core is updated. :)
