### ISSUE TITLE
mGBA is hella slow for some reason but a few days ago was amazing.

### ISSUE THREAD

**Issue by altea1566** [mgba-emu/mgba#2841]
I am using mGBA 0.10.1 appimage on lenovo chromebook linux beta

I tried everything by resetting the settings and going for the best settings. The sound and video is so laggy, cracky, and slow even when its on 60 fps with 59.something native.

This problem started from yesterday and I reinstalled it 4 times now. Even tried 0.10.0 and same thing. Please help. If their are steps including settings, please tell me. Thanks!

I will show a short video of all my settings. Please leave suggestions for changes in my settings. THANKS!!!!!!!!

**Comment by altea1566** [comment]
here is the video: 

btw ignore the clideo sign because that was me compressing the video to put on here because the size was too big

https://user-images.githubusercontent.com/111645958/221373346-2a0cdfb9-abe3-4b33-83df-0ef8f7a226fa.mp4

**Comment by endrift** [comment]
There's nothing other than the main screen in that video. Regardless, you should use the File > Report Bug dialog, like it's meant for.

**Comment by altea1566** [comment]
your right sorry, here: 
![297va9q38fka1](https://user-images.githubusercontent.com/111645958/221558883-16a7c164-6c94-422c-b124-b326b0d5b8b2.png)
![hdqx0i338fka1](https://user-images.githubusercontent.com/111645958/221558887-341526f1-71f6-4598-9805-2c070fc61a70.png)
![3aftg7i18fka1](https://user-images.githubusercontent.com/111645958/221558888-97d08daf-a023-48d1-b5c2-627155462bd8.png)
![rk7va9e28fka1](https://user-images.githubusercontent.com/111645958/221558890-1e7ffdb1-88e2-46dd-a6f8-691f4d78eaa4.png)
![wj8rbrt08fka1](https://user-images.githubusercontent.com/111645958/221558894-2dd4f557-3da1-4f1d-8c86-b1e93803e31d.png)
![x78d225z7fka1](https://user-images.githubusercontent.com/111645958/221558896-353408e7-cc81-4392-9a9a-94551c7f2787.png)
![84i9wp5x7fka1](https://user-images.githubusercontent.com/111645958/221558897-8fa3ff53-dace-4ab2-8300-4945065b75bf.png)
![cfifaeiw7fka1](https://user-images.githubusercontent.com/111645958/221558900-dac488ed-e705-4783-bdd4-a85cab8cdae1.png)
![malyshtv7fka1](https://user-images.githubusercontent.com/111645958/221558901-2a885e1b-50a3-4815-ac24-0814c4510104.png)
![9m5yglxu7fka1](https://user-images.githubusercontent.com/111645958/221558903-68f26153-6614-433c-9a51-630132fbe38b.png)
![odl36ztt7fka1](https://user-images.githubusercontent.com/111645958/221558904-399ca419-439f-4a40-86cc-6f28da5530fa.png)

**Comment by endrift** [comment]
Change the display driver to OpenGL

**Comment by Aieldail93** [comment]
Audio/video - audio driver SDL 
Buffer - 1536
Sample - 44100 Hz

Solves
