### ISSUE TITLE
[ASLE][ASLP] Stuart Little 2 creates 32KB sram file despite being known not to have any backup ram.

### ISSUE THREAD

**Issue by Squall-Leonhart** [mgba-emu/mgba#2843]
This seems to be a game specific edge case,  My (unfounded) theory is that the game board has some registers that result in auto-detect mechanisms assuming it to have either sram or flashram without the backup ram actually being present on the board, in vba-m this was resulting in termination in our Flash Save detect incorrectly, despite the auto-detect code being adequate enough otherwise to determine it has no backup memory available.

MGBA on the otherhand creates an empty 32KB sram sav file, instead of the usual 0KB files that mgba creates for most other games with no backup memory, this is not so much an issue to be corrected as just a matter of documenting this difference, should anyone ever wish to look into the carts hardware.

**Comment by endrift** [comment]
This is caused by what appears to be a bug in the game where it writes to 0x0FFFFFFC, which is interpreted by mGBA as trying to write to SRAM. There are no "registers" involved here, only shovelware with poor quality control.
