### ISSUE TITLE
Random Slowdowns

### ISSUE THREAD

**Issue by s0meone247** [mgba-emu/mgba#2844]
Ironically this faster emulator seems to have a problem where after about a minute the fps drops dramatically and the audio gets loud and irritating. I've tried every setitng possible but nothing works.

**Comment by endrift** [comment]
Gonna need that bug report zip (File > Report Bug) to do literally anything with this report.

**Comment by s0meone247** [comment]
oh sorry. here it is
[Random Slowdowns 3-2-2023.zip](https://github.com/mgba-emu/mgba/files/10876935/Random.Slowdowns.3-2-2023.zip)

**Comment by endrift** [comment]
Nothing in here looks too weird. For a basic test, I'd recommend setting sync to audio on, sync to video off (as it already is), and turn the renderer (under the enhancements tab) to Software (it's currently set to OpenGL--this is not the same as the display driver under Audio/Video, which you should leave as OpenGL). These are the default settings, though.

What do you mean by "loud and irritating"? Is it playing weird garbage, or just the usual game audio gets louder?

**Comment by s0meone247** [comment]
It sounds similar to original audio but on a lower frame rate and slightly louder. I'll try to change the renderer and send back my results

**Comment by s0meone247** [comment]
seems to have fixed it!
Thanks.
