### ISSUE TITLE
Add shortcut to reset and re-load the most recent script

### ISSUE THREAD

**Issue by 40Cakes** [mgba-emu/mgba#2845]
I'm learning LUA for mGBA at the moment and while developing I think it could speed up testing scripts by having a hotkey to reset and re-load the latest script without needing to open Tools > Scripting > File > Load recent script > latest file... every time. It would be especially helpful to quickly re-connect TCP sockets for example

Thank you 😊

**Comment by sam-gupta-git** [comment]
My name is Sam and I am a student in the CS 360V Virtualization class at UT Austin. May I work on this issue?

**Comment by endrift** [comment]
This has absolutely nothing to do with virtualization, but sure.

**Comment by endrift** [comment]
Closed by #3266
