### ISSUE TITLE
Medarot 5 text boxes are jumpy

### ISSUE THREAD

**Issue by Sanqui** [mgba-emu/mgba#285]
![medarot5mgba](https://cloud.githubusercontent.com/assets/289437/16203011/8c4b05d2-3718-11e6-809a-e5d45e6332f7.gif)
Right after it scrolls up, the message box jumps a little bit.  Does not happen on bgb.

Commit: e1a4acec9f39a1f7081d56b69c851747caada807

**Comment by endrift** [comment]
Seems to have been fixed, likely by 488bc56d3c76debc4cb3cd5ab9f3e54f389450bf.
