### ISSUE TITLE
BGM in fast forward request,

### ISSUE THREAD

**Issue by FrostKnight** [mgba-emu/mgba#2850]
Been meaning to ask this for a while, but wondered if its possible to make fast forward have no effect on the soundtracks in the background but yet, affect everything else like usual.

I like fast forward, but I don't like the music being fast forwarded too.

:D

This would be a very nice thing for mgba, if you guys know how to do this.

**Comment by endrift** [comment]
This isn't possible without an audio HLE, which itself is in the works, but a bit far off.

**Comment by FrostKnight** [comment]
@endrift 
Do you have any vision as to when this will be accomplished? Approximation, etc?

But yeah, glad to know that's being worked on.

This is very much appreciated.
