### ISSUE TITLE
Сontrol key stuck

### ISSUE THREAD

**Issue by Arachn1dsGrip** [mgba-emu/mgba#2856]
Tried different roms and in every game my left contol key is perma stuck
also tried rebinding keys - no effect
please help me XD
[bug_report1.zip](https://github.com/mgba-emu/mgba/files/11008290/bug_report1.zip)

**Comment by endrift** [comment]
I don't understand. If you don't have control mapped, how does it being "stuck" matter?

**Comment by Arachn1dsGrip** [comment]
Idk, i have every gba button mapped. When it comes to typing or moving, cursor or player just running left infinitely 🥲
Maybe it’s some sort of setting and i pressed shortcut accidentally but i checked settings and tried turning “autofire” on/off for the left button.

**Comment by Arachn1dsGrip** [comment]
Idk, i have every gba button mapped. When it comes to typing or moving, cursor or player just running left infinitely 🥲
Maybe it’s some sort of setting and i pressed shortcut accidentally but i checked settings and tried turning “autofire” on/off for the left button.

**Comment by endrift** [comment]
You have left mapped to the left analog stick and the A key on your keyboard according to this. Does it just start out moving left when you load the game?

Also, you're using mGBA 0.9.3, which is out of date and not a version that support is provided for. Please update to 0.10.1.

**Comment by Arachn1dsGrip** [comment]
Yes this problem was “out of the box”, it was the first thing happened when i installed emu XD.
Oh idk I thought this is the last up to date version for my system, i clicked the link for ubuntu 22.04 on the site.
Maybe this will solve the problem, I’ll try to find 0.10.1!

**Comment by endrift** [comment]
It should be this link https://github.com/mgba-emu/mgba/releases/download/0.10.1/mGBA-0.10.1-ubuntu64-jammy.tar.xz

**Comment by Arachn1dsGrip** [comment]
thank you, i updated version but the problem is still remains...
[bug_report2.zip](https://github.com/mgba-emu/mgba/files/11010477/bug_report2.zip)

**Comment by endrift** [comment]
Your keyboard appears to be...presenting as a gamepad...for some reason. Try clearing all of the bindings in the controller section.

**Comment by Arachn1dsGrip** [comment]
![image](https://user-images.githubusercontent.com/113133859/226162671-83c590cc-7ed8-42dd-8042-93751c2d9f1f.png)
Omg, thank you! I cleared the controller bindings and it worked! Very strange behaviour as i just installed emu yesterday and didnt touch settings, wonder if someone had the same issue before, i tried to check all similar issues before posting. Thank you so much <3

**Comment by endrift** [comment]
There have been other people who've had weird things that aren't controllers show up as controllers, like a drawing tablet. It's very strange.
