### ISSUE TITLE
Setting broken after updating

### ISSUE THREAD

**Issue by NVHT** [mgba-emu/mgba#2858]
![image](https://user-images.githubusercontent.com/8341213/226178258-db879324-b241-4383-bf91-d1022f6462fe.png)

This only happened after updating. Closing and reopening will make the setting page normal again.

**Comment by endrift** [comment]
I have approximately a 0% idea how this could possibly happen without something being very wrong with your computer.

**Comment by NVHT** [comment]
It gone now. Not sure what happened.
