### ISSUE TITLE
[v0.10.1] Streaming to Discord before going full-screen crashes my PC

### ISSUE THREAD

**Issue by Ckosmick** [mgba-emu/mgba#2859]
mGBA version 0.10.1

System information:
OS: Windows 10 22H2
CPU: Intel i7-6700K
GPU: AMD Radeon RX 6700XT [Driver v22.11.2]
RAM: 32GB
Display: Dell D2719HGF [Set to 60Hz, Freesync on/off doesn't matter]

Reproduce steps:
1.) Enter a voice channel on discord
2.) Open mGBA
3.) Load a ROM in mGBA
4.) Stream mGBA window to Discord
5.) press alt-enter to go full screen

The screen goes black and I lose control of my keyboard/mouse.

**Comment by endrift** [comment]
This is almost certainly a Windows or Discord bug, not an mGBA bug. I have no idea how mGBA could even trigger this, and there's no way a well-behaved OS would let mGBA do this regardless.

**Comment by Ckosmick** [comment]
One of the times it happened I had left it sitting for a while and it tried to reinstall my gpu drivers so i'm guessing it's related to my GPU.

**Comment by Ckosmick** [comment]
Update on this: Discord's overlay was on.... And with it toggled off, the crashing might be gone now?

**Comment by endrift** [comment]
Yeah gonna chalk this one up to Discord.
