### ISSUE TITLE
Pokémon Puzzle Challenge: Prof. Oak

### ISSUE THREAD

**Issue by Sanqui** [mgba-emu/mgba#286]
Oak has a row of white pixels above him when he wiggles.  Looks like he also wiggles in parts instead of whole.  Doesn't happen on hardware.

![ppc_mgba](https://cloud.githubusercontent.com/assets/289437/16203514/f4e76cd2-371a-11e6-9d69-90d3b99d343a.gif)

Commit: e1a4acec9f39a1f7081d56b69c851747caada807

**Comment by taisel** [comment]
Animation in that gif looks like it's running slow-mo. Is it being giving enough CPU cycles there?

**Comment by Sanqui** [comment]
The gif is slow because browsers refuse to play gifs at 60fps.

**Comment by taisel** [comment]
What about webm?

**Comment by Sanqui** [comment]
I made the gif with mgba's built in gif maker.  Since the issue lasts a single frame, I wasn't even concerned about it slowing down: it's easier to notice this way. 
I don't know much about webm, including how to convert to it, whether it can do lossless videos, and whether Firefox supports it (I know it doesn't support webp).  I don't think it's important.

**Comment by endrift** [comment]
Fixed in 31cf1622a7a91c2c4b4c5713ec1354063d37db17. The window variables were getting latched at the beginning of vblank instead of the end.
