### ISSUE TITLE
Using lua scripts on Android 

### ISSUE THREAD

**Issue by HierarchyMan** [mgba-emu/mgba#2868]
Although the emulator is available through retro arch I couldn't find an option regarding scripting
I want to use the script function on Android specifically for Pokemon fire red multiplayer script (https://github.com/TheHunterManX/GBA-PK-multiplayer)
Is there a way to use the mgba scripting feature on Android?

**Comment by endrift** [comment]
The Android version is not first party, it's a Retroarch project. Retroarch cores in general do not and cannot ship with advanced features like this because of how they are architected.

**Comment by HierarchyMan** [comment]
But my question is, mgba is available for so many platforms... Why not android?

**Comment by endrift** [comment]
mGBA is available on the following platforms via first-party support:

- Windows
- Mac
- Linux (and things like FreeBSD)
- 3DS
- Wii
- Vita
- Switch

Any other port is unofficial. That includes the Android port. I'd like to add Android support someday, but the number of people behind this project is roughly one. It's a lot of work.

**Comment by HierarchyMan** [comment]
I totally understand keep up the good work
Mgba is one of the best emulators for pc and the only usable emulator on some platforms
I hope one day you get the time and motivation to make a fully functional android version
Thanks
