### ISSUE TITLE
Record A/V: MP3, Opus and Vorbis codecs fail to initialize

### ISSUE THREAD

**Issue by SuperSamus** [mgba-emu/mgba#2869]
When trying to record A/V using either the MP3, Opus or Vorbis audio codec, mGBA will show an error dialogue saying: "Failed to open video file: \<file\>".
By looking at the logs, however, it seems to be an error with ffmpeg. Respectively:
```
[libmp3lame @ 0x1c83000] Specified sample rate 65536 is not supported
[libopus @ 0x15bb340] Specified sample rate 65536 is not supported
[libvorbis @ 0x1c83f00] encoder setup failed
```

Linux NixOS unstable.
Tested with latest master (45762c8f9f5c5ecd73696d786dbfc6f9a869b525).
(Related #2731)

**Comment by endrift** [comment]
Can you confirm if this happens with 0.10.1?
