### ISSUE TITLE
Jumped to invalid address: 200600C4

### ISSUE THREAD

**Issue by RezzScapeAlt** [mgba-emu/mgba#2872]
Hi! I was playing the romhack Pokemon Unbound and I was messing around with MGBA's settings, pretty sure I pressed "Yank game pak" like an idiot and it caused a boat load of crashes to pop up, minimum 100. I had to force close it through task manager and whene
ver I try to use that save file now, it won't work. I really don't wanna start over again, is there a way to fix this?

**Comment by endrift** [comment]
Unless you have an in-game save that works (not a save state), or took some save state and some random other time, then no, your save is dead.
