### ISSUE TITLE
Using `require` in a Lua script has stopped working

### ISSUE THREAD

**Issue by shplack** [mgba-emu/mgba#2877]
## System Info
Version: `0.11-8044-dfb6055ae`
OS: Windows 11 Pro 64-bit `10.0.22621 Build 22621`

## Background
I have been using the development-branch for a few weeks now. Until yesterday I had been using a build from about 3-4 weeks ago. Unfortunately I don't know which commit I was using at the time. Nevertheless, somewhere along the past 3-4 weeks has this bug been introduced.

I have been working on a hobby project that consists only of scripting on mGBA. I have earlier not encountered this issue until I updated to the most recent build, yesterday.

## The Issue
Using `require` has resulted in the engine not being able to find the correct module to import.

For example, in the directory `C:\Users\cfahe\Workspace\Gen3Multi` exists `test.lua`:
```lua
require("connection.server")
```

The file `server.lua` exists in the directory `connection` which resides in the same directory as `test.lua`, yet this error occurs:
![image](https://user-images.githubusercontent.com/62137686/230864823-b3ee7991-23f7-4d16-a8eb-897e510e58f4.png)

I suspect that the engine truncates the filepath of the directory which the script is located due to the error message not printing the `i` at the end of ``Gen3Multi`. The exact same behavior is observed when moving the file into the same folder as the script to be imported, as you can see here:

![image](https://user-images.githubusercontent.com/62137686/230865782-f93761b1-76c7-4208-8989-4b342806e9c4.png)

**Comment by endrift** [comment]
Can you check if it works in 8037-2f54d98?

**Comment by shplack** [comment]
> Can you check if it works in 8037-2f54d98?

Yes it does work in that commit

**Comment by endrift** [comment]
Should be fixed now, sorry about that.
