### ISSUE TITLE
Alice in Wonderland - wrong palettes

### ISSUE THREAD

**Issue by Sanqui** [mgba-emu/mgba#288]
Left: mgba, right: bgb
![2016-06-20t19 25 05-selection](https://cloud.githubusercontent.com/assets/289437/16203889/bcfeb134-371c-11e6-8718-6a71dc4a386c.png)
![2016-06-20t19 26 01-selection](https://cloud.githubusercontent.com/assets/289437/16203918/d5123962-371c-11e6-81be-f2d48f10c840.png)
![2016-06-20t19 26 13-selection](https://cloud.githubusercontent.com/assets/289437/16203919/dd0538ea-371c-11e6-9099-8d83403b0afd.png)

Fade-ins and fade-outs in particular look poor.

Commit: e1a4acec9f39a1f7081d56b69c851747caada807

**Comment by endrift** [comment]
Fixed in 74caccd6df2298b0d123c677fabc5b751251156c, although the game is still kinda buggy.
