### ISSUE TITLE
Double-Tapping A toggles fullscreen back and forth.

### ISSUE THREAD

**Issue by Traedran** [mgba-emu/mgba#2880]
Hello. I'm not a very tech-savvy person, so I'm unsure what might have caused this. Before, I could double-tap the A button to go from a windowed view to fullscreen, and once in fullscreen, I could double-tap A to my heart's content. Now, for some reason, whenever I double-tap A, it will toggle fullscreen back and forth. Needless to say, any button-mashing intensive game becomes nearly useless with this, constantly popping back and forth between two screens while I'm navigating a flying area in Kirby or so forth, or whenever trying to skip dialogue boxes on a game you've played many times before.

I'm not seeing any direct toggle option for this feature, and it's really cutting into the number of games I can play given the constant screen size swapping and Windows' little chime that indicates if something's gone fullscreen.

My mGBA version appears to be 0.10.1, if I am reading this right, and I run this on Windows 10. Any other pertinent information, I wouldn't really know how to report.

**Comment by Traedran** [comment]
Additional: I should specify I'm using a generic gamepad, an IFYOO-V108. It worked flawlessly before, not the slightest hiccup or inconsistency in controls, but now it doesn't. I don't think I did anything, but I don't know enough to be confident in that fact.

**Comment by endrift** [comment]
It should only do this if you're clicking on the window with every A press. Do you have something installed like joy2key that is translating buttons to keypresses?

**Comment by Traedran** [comment]
Oh, jeepers, it really was that simple. I somehow turned on controller companion. This is the exact same issue that made Yakuza 0 unplayable for me but months ago, and I've already forgotten it. Well! Can't say you didn't solve my problem perfectly. Just toggled that off and now the control is completely flawless. Thank you for the assistance!
