### ISSUE TITLE
mGBA crashes when I open a Game Boy Camera ROM with QT Multimedia enabled

### ISSUE THREAD

**Issue by stehley** [mgba-emu/mgba#2884]
mGBA crashes crashing when I open the GB Camera ROM when I have QT Multimedia selected.

The crash occurs upon opening the ROM. This is happening no matter what webcam I select under QT Multimedia. When I have None (Still Image) selected, it works fine (shows "no cam" screen in GB Camera - not sure if this is expected behavior).

**mGBA version**: 0.10.1
**OS**: MacOS Ventura 13.3.1 (22E261) (Latest)
**CPU**: Apple M1 Pro
**Memory**: Whatever Apple puts in the M1 mac

Let me know if I can provide any other info to help troubleshoot!

**Comment by endrift** [comment]
This appears to be a privacy feature in modern macOS where it kills programs that don't declare the camera usage. However, if I declare that it still crashes when mGBA tries to access the microphone. Unfortunately, I have no idea why mGBA is trying to access the microphone, and I'd rather not declare usage of the microphone when I'm not actually _intentionally_ accessing the microphone.

**Comment by endrift** [comment]
I believe this works with the latest development builds, either due to an update in Qt or due to the new signing process. Please check a current development build https://mgba.io/downloads.html#preview-downloads
