### ISSUE TITLE
Speedy Gonzales: HUD is cut off

### ISSUE THREAD

**Issue by Sanqui** [mgba-emu/mgba#289]
The topmost row of the HUD is cut off.  Probably a window problem.

![speedy gonzales-0](https://cloud.githubusercontent.com/assets/289437/16204258/5d080d32-371e-11e6-8fe0-5dcdb9a9b235.png)

Commit: e1a4acec9f39a1f7081d56b69c851747caada807

**Comment by endrift** [comment]
Fixed in f5663675a5ac78c2927fe0796df92f72be421535. Was not a window problem.
