### ISSUE TITLE
Frame anomalies in OpenGL mode

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2890]
At lower resolutions (x1-x4), mgba repeats an 2 frames-old frame, creating a weird shuttering.
At higher resolutions (x5 and more), this effect only affects part of the screen, creating some kind of square screen tearing.

The game seems to run at fullspeed, as the audio sounds silky at 1024 samples (less, and the framerate gets choppy).

This issue doesn't happen before, and it isn't like #827 frameskipping issue.
It's been a while since I used mgba, specially in OpenGL mode, so I'm not sure if the cause it's an mgba update or the drivers update.

I attack 2 videos recorded with Windows tool, since mgba built-in recorder doesn't reflect these frame anomalies.

OpenGL x1
https://user-images.githubusercontent.com/16591467/233314173-6dd85d08-401b-4692-ba24-e8da2c08c277.mp4

OpenGL x5
https://user-images.githubusercontent.com/16591467/233313976-847f92b4-9b83-481b-a0c0-1f5d0596e760.mp4

SW Specs:
mgba 0.11-8060-9fa607b30
Windows 10 (22H2)
Nvidia driver 531.61

HW Specs:
Laptop Legion 5 15arh05h (82b1)
CPU: AMD Ryzen 7 4800H @ 2.9-4.2 GHz (8/16)
GPU: NVIDIA GeForce RTX 2060 @ 6GB @ 120hz (Radeon disabled)
RAM: 16 GB @ DDR4

**Comment by endrift** [comment]
This should have been fixed yesterday. Please update and try again.

**Comment by RafaelTrepaUnCarballo** [comment]
I confirm it's fixed.
Sorry for not testing it with today's build.

**Comment by endrift** [comment]
Honestly I'm super glad you're able to confirm it's fixed, more than anything.
