### ISSUE TITLE
[macOS] mGBA stuck on opening screen when attempted to open legacy and modern version

### ISSUE THREAD

**Issue by ComradeShrub4** [mgba-emu/mgba#2895]
Not sure if this is really a common issue amongst Mac users, however I didn't see anything relating to what is happening on my screen when I attempt to open mGBA. I double clicked to open the software and it just opens to a picture of the logo, like it was attempting to load the actual software, but did not. I tried an older version, digging through the contents, even getting past the Mac's built in protection. Is this something I can fix, or is there nothing I can do about it?

Thank you!

(attached screenshot is all I see, it gets stuck like this.)
![Screen Shot 2023-04-24 at 12 16 38 AM](https://user-images.githubusercontent.com/131637946/233898937-e39e13d0-80d4-4e7b-a820-e07b1c2dd7c7.png)

**Comment by endrift** [comment]
You need to open a ROM for it to do anything. Use the File menu.

**Comment by ComradeShrub4** [comment]
Ah, that makes sense-
