### ISSUE TITLE
[3DS] Soft-patching does not appear to work

### ISSUE THREAD

**Issue by Nemris** [mgba-emu/mgba#2899]
It seems that IPS patches aren't detected and loaded. Initially, I simply dropped one in the same directory as the ROM, with the same filename except for the extension (as detailed in #51), but fruitlessly. On the contrary, on Arch Linux soft-patching the same ROM with the same patch works as expected.

Afterwards, I modified my `config.ini` to set a directory for patches, which mGBA successfully creates. However, dropping the patch in there makes no difference.

Moreover, the log file appears to contain no reference to the IPS file at all. The log I examined was collected after setting `logLevel = 0x10`.

## Device info
System: New3DS
OS Version: v11.16.0-49E
Luma3DS Version: v12.0.1
mGBA Version: v0.10.2 (.3dsx variant)

**Comment by endrift** [comment]
logLevel is a bitmask, and also I'm not sure hexadecimal will even be parsed in the config file. But regardless, this was an oversight in mGUI.

**Comment by Nemris** [comment]
I might be remembering wrong - but I think that mGBA picked up `logLevel` as both an integer and a hex number. Plus, on Arch's QT port, it seems that the config file's `logLevel` is populated with an integer after editing the logging settings from within the GUI.

At any rate, thank you for the fix!

**Comment by SuperfieldCU** [comment]
It seems as though this issue regressed. I am unable to get softpatching to work on 3DS. .ips file is in the same directory as the ROM with the same name other than the extension, but the patch isn't loaded.

**Comment by endrift** [comment]
Are you using 0.10.5? I'm not sure this patch made it into any of the releases yet.

**Comment by SuperfieldCU** [comment]
Yes, I am on 0.10.5.

**Comment by endrift** [comment]
Yeah, the fix isn't in that version. It should work in the development builds.
