### ISSUE TITLE
Video issues on Radeon card

### ISSUE THREAD

**Issue by Danfun64** [mgba-emu/mgba#29]
For some reason graphics aren't showing properly. I tried with the stable version (0.2.1) first, then I tried the latest nightly build download. Same result. You would think it was the game itself at first, but the bios didn't show anything either. Fraps worked however, so here is a lovely video of me doing...something...

(Rename the .jpg to .mp4; yes, the compressed video is that small)
![mgba 2015-05-31 20-34-47-25](https://cloud.githubusercontent.com/assets/4473635/7904740/6fd3690c-07d6-11e5-9adc-dd1e18058292.jpg)

**Comment by endrift** [comment]
Looks like all of the layers except for the backdrop got disabled. Try screwing with the video layers option under Audio/Video. That option doesn't exist in 0.2.1 though, so it's kind of curious.

What's your OS and video card/drivers? I'm guessing Windows of some kind because you're using fraps.

**Comment by Danfun64** [comment]
Windows 7 64-bit using AMD Radeon HD 6520G using (what I think are) the latest official drivers. I just noticed that when I point my mouse curser inside the emulation window, it disappears. Somehow I doubt that's supposed to happen.

**Comment by endrift** [comment]
That's actually intentional so that the cursor doesn't obscure the game when it's full screen. I should probably change it so it doesn't do that when it's windowed, though.

**Comment by endrift** [comment]
I can't seem to find a case where this would happen. Are you using a clean (not patched) ROM? Which version (region, etc)? It's Pokémon FireRed, but that's all I can tell.

**Comment by endrift** [comment]
I wonder if this is a problem with the GL context being sized wrong, potentially due to lack of OpenGL < 3.x support. Does resizing the window change anything?

**Comment by Danfun64** [comment]
No, and I just tested the latest trunk build.

**Comment by endrift** [comment]
This isn't a proper fix, but using the nightly from today (or later, if you see this later), can you add a line to the file %APPDATA%\mGBA\qt.ini that says this:

    videoDriver=1
And see if the issue still occurs?

**Comment by Danfun64** [comment]
videoDriver=1 doesn't fix the issue. Before you ask, nor does videoDriver=0

**Comment by endrift** [comment]
=0 is the default without the setting. I wasn't planning to ask.

You've tried recording a video using mGBA's built-in video recording tools and still the same results? I'm really at a loss to how this could happen.

**Comment by Danfun64** [comment]
"You've tried recording a video using mGBA's built-in video recording tools and still the same results?"
No, I haven't. I'll try tomorrow.

**Comment by endrift** [comment]
It turns out the revision I told you to use was broken. Please download the latest nightly and switch Display driver (in settings) to "Software (Qt)", then restart mGBA to see if the problem persists.

**Comment by Danfun64** [comment]
I downloaded the latest trunk build. Opengl works perfectly now, but now i have a new problem. In Software (Qt), the emulation acts like it's paused. I can fast forward, but it's still paused when i stop.

**Comment by Danfun64** [comment]
I take it back. Software (Qt) *does* work, but at a ridiculously slow speed (0.5 fps)

**Comment by endrift** [comment]
Software display isn't really meant to be fast. It will slow down a lot as you increase the window size. It's mostly just for debugging issues like this. There's a reason it's hardware accelerated by default.

**Comment by monyarm** [comment]
I'm having this exact same issue (on a 260x) on the latest nightly (0.50).
