### ISSUE TITLE
Trimmed GBA Roms

### ISSUE THREAD

**Issue by user18081972** [mgba-emu/mgba#2909]
I couldn't find any info on this.

Are there known problems when using GBA roms that are trimmed, with for example NDSTokyoTrim v3.11?

**Comment by endrift** [comment]
Generally, you should provide an explanation of what's wrong that you're seeing, not a question of if anything is wrong, as the answer is usually "I dunno, what do you think is wrong?" Thus, abstract questions like this are unhelpful.

Anyway, in general trimmed ROMs should work fine unless said ROM depends on open bus behavior. Trimmed ROMs will be treated as 32 MB ROMs with blank data past how big it was. This will cause problems for ROMs that expect open bus behavior, which games _shouldn't_ do, but many (e.g. Minish Cap) do.

So please, tell me what you're seeing.

**Comment by Dimensional** [comment]
Trimming a rom may lead to important data getting cut off by being mistaken as padding. Information for trimming and compressing can be found here:
 https://emulation.gametechwiki.com/index.php/Save_disk_space_for_ISOs#Trimming_2
