### ISSUE TITLE
[Debug] [Feature][Question/Request] debugfile specification

### ISSUE THREAD

**Issue by Bunkai9448** [mgba-emu/mgba#2910]
Hi, 

Reading around some posts about reverse engineering and debugging roms I found about debug files. (Not to be confused with debugger implementation).

Here's a documentation example about them for gb
https://github.com/aaaaaa123456789/gb-debugfiles/blob/master/debugfile.md

After a search I didn't find about this on mgba. I guess It could be because you said the debugger is still in "early stages" but I wanted to be sure, is this feature planned? or if it's there, where can I find it?

[I guess many of those actions can be done  through scripting and manual input but I believe it could be a really good feature, and it also helps to give feedback for/to you when using it]

**Comment by endrift** [comment]
I'm not sure what I'm looking at. This seems to be some sort of scripting format? The ".mrc" files are literally just lists of commands you execute in the debugger. Scripts proper are separate and not fully integrated so all they have right now are .mrc files.

**Comment by Bunkai9448** [comment]
First, let me thank you for the answers, and for all your dedication on creating mGBA. (I've asked things previously but never said it, so it was about time).

Alright, then it seems like those ".mrc" files are somehow what I was looking for. I guess this thing about naming is a problem when google is flowed with non related info (trying to look for debug files and mrc files showed a lot about debugging features and other programs cli but nothing about this, so I was lost).

Last question and you can close this.

How or where can I find info about mgba ".mrc" files? These are the places I'd go https://github.com/mgba-emu/mgba/tree/master/src/debugger
https://mgba.io/docs/scripting.html

But there's no reference to ".mrc" files in there. Are those the things I have to 'just' do? Or am I wrongly understanding something?

**Comment by endrift** [comment]
I just told you. It's list of debugger commands just like in the command line interface. Just type "help" to get a list of commands, and it's those.

It's not really that useful at the moment.

**Comment by Bunkai9448** [comment]
OK, I guess I was overcomplicating things. 
Thank you.
