### ISSUE TITLE
Request: Have the auto-updater preserve your portable/not portable preference

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#2915]
A feature request: It'd be nice if the auto-updater detected when you're running mGBA without portable.ini so that it deletes the new portable.ini that gets created when the new version is decompressed and copied over to the mGBA folder.

Leaving the portable.ini in there when the user wasn't using one to begin with seems like bad UX and might leave users confused.

**Comment by endrift** [comment]
It...does this already.
