### ISSUE TITLE
mGBA slow down on FF6A battle scene

### ISSUE THREAD

**Issue by Yave-Yu** [mgba-emu/mgba#2917]
Run FF6A, when in battle, mGBA runs slower.
This issue doesn't happen on older version like 0.9.3 and backwards, but happen on 0.10.0 and onwards.

**Comment by endrift** [comment]
Which platform are you running mGBA on?

**Comment by Yave-Yu** [comment]
Windows 10

**Comment by Yave-Yu** [comment]
What the... the latest dev build doesn't have this issue! But 0.10.2 I've tested before has it.
