### ISSUE TITLE
PSG channel suddenly silent for unknown reason

### ISSUE THREAD

**Issue by Yave-Yu** [mgba-emu/mgba#2918]
Just run a game for a while, especially a game that uses PSG audio, such as Pokemon. After some time, one (maybe more) of PSG channel will suddenly silent... or by unknown way make it re-output, but it will have unpleasure, electric-ly effect (noise?).
This issue doesn't happen on <=0.9.3 version, but happen on >=0.10.0 version.

**Comment by endrift** [comment]
I believe this was fixed a week or so ago, please test in a dev build.

**Comment by Yave-Yu** [comment]
OK I will test 0.10.2, I just tested it in latest BizHawk with mGBA core, it has this issue, but I now realize that core is before 0.10.2.

**Comment by endrift** [comment]
I said dev build. 0.10.2 is latest stable. You need newer.

**Comment by Yave-Yu** [comment]
Tested latest dev build 0.11-8103-abf084842, run Pokemon a while… oh yeah, this issue seems gone.
