### ISSUE TITLE
playing pokemon leaf green and tried loading a save state

### ISSUE THREAD

**Issue by JuderDuder516** [mgba-emu/mgba#2919]
i tried to load a save state in Pokemon LG and upon loading the screen is frozen with audio still playing in the background. Im trying my hardest to get this to just run normally again because i have a shiny lugia onscreen that id like to catch lol. any help would be appreciated 

[bug report.zip](https://github.com/mgba-emu/mgba/files/11419662/bug.report.zip)

**Comment by endrift** [comment]
Can you upload the save state you're trying to load?
