### ISSUE TITLE
Conditional breakpoints with GDB don't work

### ISSUE THREAD

**Issue by fl4shk** [mgba-emu/mgba#292]
Here's the version of mGBA I've tested with (I built it from source):  mgba 0.5.0 ((unknown))
I run Arch Linux (64-bit)

The main thing about this issue is that breakpoints appear to trigger without taking the condition into account.  I worked around this by putting the conditions in my code itself, but that was painful when I wanted to change the condition.

**Comment by Touched** [comment]
GDB requires that PC be equal to the address the breakpoint was set on when program execution is halted via SIGTRAP (See [Stop Reply Packets - swbreak](https://sourceware.org/gdb/onlinedocs/gdb/Stop-Reply-Packets.html#swbreak)). Without this, GDB has absolutely no idea what breakpoint was triggered so it cannot do conditional breakpoints or run commands upon breaking.

**Comment by endrift** [comment]
I thought I fudged the PC for GDB.

**Comment by Touched** [comment]
I didn't see any code for that. I get conditionals working when I manually set PC to the address from the breakpoint info before sending SIGTRAP. I can send in a PR but I'm not sure if that's safe.

**Comment by endrift** [comment]
Fudged it in a967f9aac433c817fbca981c5e254e5107457f47. I disabled writing to the PC via one of the GPR write routines since the way that was being done isn't safe (whoops! I didn't notice that when I merged the PR) so I need to fix that.
