### ISSUE TITLE
The latest version of mgba Development running the Jin Yong Qun Xia Zhuan without sound

### ISSUE THREAD

**Issue by Helloworld996** [mgba-emu/mgba#2921]
Latest Development Version: 8104-36e62c085
game: Jin Yong Qun Xia Zhuan
problem：8104-36e62c085  running without sound。Other simulators can operate normally. For example, myboy gba. emu VBA
Jin Yong Qun Xia Zhuan downloads:
https://drive.google.com/file/d/1Il6MPrf9yiEijN-KmQ5j8TGvo6jSxqHJ/view?usp=share_link

**Comment by endrift** [comment]
Audio doesn't seem to work in SameBoy either, which is more accurate than VBA, MyBoy or mGBA. That said, it works in BGB, which is also more accurate than mGBA. Will test on hardware soon, but based on what I'm seeing, it looks like a bug from whoever ported this to GBC.

**Comment by endrift** [comment]
@LIJI32 did some hardware testing and found that it works properly on hardware and SameBoy is bugged too.
