### ISSUE TITLE
mgba v0.11-8113-bb6613888 black screen on initial start up on both gba and gbc games.

### ISSUE THREAD

**Issue by Darius851** [mgba-emu/mgba#2924]
I've recently received a new laptop device outfitted with a rtx4090, intel i9-39000h and Windows 11 OS and have noticed that the games black screen on 1st boot, sometimes it even takes two or three tries for thing's to properly display.

On my old machine with a rtx 2080, 9900k with a Windows 10 OS things had appeared alright, but after updating to the current version that is also being used on my new device the problem has appeared on the older one as-well.

Is there any solution to this?

**Comment by endrift** [comment]
I believe this was fixed in 8b4818c3d80eb58e2293072f85c59c0c44a0eb0d. Please test a recent build and confirm.

**Comment by Darius851** [comment]
It has, but it appears the new file will not install any of the new dev
updates, as the file only gets downloaded but the application closes out
when it finishes.

**Comment by endrift** [comment]
Yes, that's a known bug that's been fixed, and the fix will be in 0.10.3. In the meantime you can work around it by deleting the shaders directory and then updating.

**Comment by Darius851** [comment]
I shall wait then, thank you for heads up!

Happy Holidays.
