### ISSUE TITLE
Super Mario Advance 4: SMB3 Link with e-Reader communication error

### ISSUE THREAD

**Issue by DesertWolf29** [mgba-emu/mgba#2925]
As of version 10.2, the link function between Super Mario Advance 4 and the e-Reader will fail. The last known working version is 10.0. 10.1 will have the e-Reader ROM speed up when in a multiplayer window, but I successfully scanned a card over to SMA4. With 10.2, and the latest development build, the link fails to establish between the two ROMS, resulting in a communication error. The same speed-up issue persists as well.

Edit: Also of note, when using the installed version of 10.0, the communication fails. When using the portable version, it works.

[SMA4 Bug Report.zip](https://github.com/mgba-emu/mgba/files/11475196/SMA4.Bug.Report.zip)

**Comment by Dusk595** [comment]
Having this issue too.

**Comment by Testsr** [comment]
Can reproduce. Communication after getting the save is unaffected.

**Comment by Testsr** [comment]
I have bisected the issue to commit 395fa2d. The speed up issue is from 8e58dca.

**Comment by Testsr** [comment]
@endrift Can we add this to a milestone,so that it gets fixed

**Comment by Testsr** [comment]
I have traced down the bug lines 517 - 534 of lockstep.c(removing the lines fixes the bug), and know the issues is caused by the GBAs having different transfer modes. I don't know what causes the transfer mode desync, however. My best guess is a race condition in setting the SIOCNT.
