### ISSUE TITLE
Cannot select certain encoders when trying to record with non english locale

### ISSUE THREAD

**Issue by ipatix** [mgba-emu/mgba#2927]
When using mGBA with a non English locale for recording, it's impossible to select certain encoders from the drop down menu (they become immediately red):

![grafik](https://github.com/mgba-emu/mgba/assets/8502545/d803bf81-3ae5-4fa5-8009-51cf036b7c21)

When the correct english term is manually typed in, it still works:

![grafik](https://github.com/mgba-emu/mgba/assets/8502545/97c0e59f-c6fd-497a-b80d-225060421cc4)

**Comment by endrift** [comment]
Hopefully fixed in fdfa73a7f5b5da84a46d9977a2413d7c640af5d6.
