### ISSUE TITLE
Command line switch for starting GDB doesn't work with mgba-qt

### ISSUE THREAD

**Issue by fl4shk** [mgba-emu/mgba#293]
Here's the version of mGBA I used (I built it from source):  mgba 0.5.0 ((unknown))
I don't know why it's got ((unknown)).
I use Arch Linux (64-bit).

It doesn't seem like any command line switches at all work with mgba-qt, and in particular, the -g switch doesn't appear to start gdb right away.

**Comment by endrift** [comment]
`-d` does not work with the Qt version and likely won't ever, due to the very different setup. Beyond that, most of the rest seem to work. `-g` I'll add right now.

**Comment by endrift** [comment]
`-g` fixed in 4e4a266d5307f1686f61ab251beb00bca69fb110.
