### ISSUE TITLE
Controller input Issue

### ISSUE THREAD

**Issue by 6Flash9** [mgba-emu/mgba#2932]
When connected to Dual sense controller can't move in game. Somehow game is not taking movement inputs but in ui I can navigate.
And in controller settings movement mapping is not present.

**Comment by endrift** [comment]
Do you have DS4Windows installed? That interferes with SDL, which mGBA uses.

**Comment by 6Flash9** [comment]
I am Using Android.

**Comment by endrift** [comment]
There is no official version of mGBA for Android. Whatever you're using has a frontend that's nether provided by nor supported by us.
