### ISSUE TITLE
Cannot run (any) rom - video driver problem in VM?

### ISSUE THREAD

**Issue by DunhamGitHub** [mgba-emu/mgba#2934]
**Problem:** mGBA (0.10.2) inside Windows11-VM does not run roms (VisualBoyAdvance works)

**Environment:** Windows-11 VM (Parallels) inside MacOS -13.4.

```
[DEBUG] GBA Serial I/O:	Lockstep 0: Node init
[DEBUG] GBA Serial I/O:	Lockstep 0: Node init
[GAME ERROR] GBA I/O:	Write to read-only I/O register: 006
[GAME ERROR] GBA DMA:	Invalid DMA source address: 0x00000000
[GAME ERROR] GBA DMA:	Invalid DMA source address: 0x00000000
[GAME ERROR] GBA DMA:	Invalid DMA source address: 0x00000000
[GAME ERROR] GBA DMA:	Invalid DMA source address: 0x00000000
[GAME ERROR] GBA DMA:	Invalid DMA source address: 0x00000000
[GAME ERROR] GBA DMA:	Invalid DMA source address: 0x00000000
[GAME ERROR] GBA DMA:	Invalid DMA source address: 0x00000000
[GAME ERROR] GBA DMA:	Invalid DMA source address: 0x00000000
[GAME ERROR] GBA Video:	Invalid video register: 0x04E
[GAME ERROR] GBA Video:	Invalid video register: 0x056
[GAME ERROR] GBA Video:	Invalid video register: 0x058
[GAME ERROR] GBA Video:	Invalid video register: 0x05A
[GAME ERROR] GBA Video:	Invalid video register: 0x05C
[GAME ERROR] GBA Video:	Invalid video register: 0x05E
[INFO] GBA DMA:	Starting DMA 3 0x08000248 -> 0x03002750 (8400:0200)
[INFO] GBA DMA:	Starting DMA 1 0x030066D0 -> 0x040000A0 (B600:4000)
[INFO] GBA DMA:	Starting DMA 2 0x03006D00 -> 0x040000A4 (B600:4000)
[GAME ERROR] GBA Memory:	Bad BIOS Load8: 0x0000000A
[INFO] GBA DMA:	Starting DMA 1 0x030066D0 -> 0x040000A0 (B600:0004)
[INFO] GBA DMA:	Starting DMA 2 0x03006D00 -> 0x040000A4 (B600:0004)
```

<img width="50%" alt="Screenshot 2023-05-26 at 08 54 18" src="https://github.com/mgba-emu/mgba/assets/6884752/7d5c4382-1fed-4f78-821f-ec3383bc369c">

<img width="50%" alt="Screenshot 2023-05-26 at 08 56 05" src="https://github.com/mgba-emu/mgba/assets/6884752/18622e56-0e86-4a45-8af2-8f427c3d2b5e">

<img width="50%" alt="Screenshot 2023-05-26 at 08 57 02" src="https://github.com/mgba-emu/mgba/assets/6884752/40706dcb-66ee-48ff-b9ff-3870a0076784">

**Comment by DunhamGitHub** [comment]
> This is almost certainly a lack of proper graphics drivers.

I agree that there is _some_ problem with the graphics driver inside the VM, however, May I kindly point out that I indicated that _VisualBoyAdvance_ does indeed work.

> Why not just run it on the macOS host?

Since you ask: I have various Windows-only apps for rom-hijacking and I want one sandbox environment for all stuff "emulation"

> There's a Report Bug dialog to get a better set of information.

File attached! (Steps: open mGBA, load rom, start bug report, reset rom)
[buglog.mvl.zip](https://github.com/mgba-emu/mgba/files/11573021/buglog.mvl.zip)

**Comment by endrift** [comment]
This is the wrong file. This is a video log. I said Report Bug.

Also VBA working means nothing. If you want it to just work regardless of hardware acceleration, turn the video display driver to Software. It's supposed to do that if it detects a broken driver, but if the driver is...too clever for being broken it might not work.

**Comment by DunhamGitHub** [comment]
Works with following 2 adjustments (from vanilla)

<img width="30%" alt="Screenshot 2023-05-26 at 10 41 10" src="https://github.com/mgba-emu/mgba/assets/6884752/91235dfe-91b2-4593-9547-afc2f657638f">

...

<img width="50%" alt="Screenshot 2023-05-26 at 10 41 33" src="https://github.com/mgba-emu/mgba/assets/6884752/2375c7be-91c6-42d3-bd24-f1929914d834">

...
*Display driver: OpenGL (default)
