### ISSUE TITLE
Widescreen support?

### ISSUE THREAD

**Issue by perguto** [mgba-emu/mgba#2937]
Would it be possible to add an extended viewport functionality like in [bsnes-hd](https://github.com/DerKoun/bsnes-hd) or [Genesis Plus GX Wide](https://github.com/DerKoun/bsnes-hd)? By using the `Adjust layer placement...` menu, I noticed that you could already get extra pixels in all directions (just not at the same time), so it shouldn't be too difficult to extend the resolution like that, right?

**Comment by endrift** [comment]
Duplicate of #1960. There are also a bunch of complexities for this that aren't obvious, such as the inherent limit of 256 pixels wide that would need modifications in the MMIO API to bypass.
