### ISSUE TITLE
Unable to build due to "Windows requires epoxy module!" even with libepoxy installed

### ISSUE THREAD

**Issue by Margen67** [mgba-emu/mgba#2939]
I ran a command similar to what the [README](https://github.com/mgba-emu/mgba#visual-studio) says: `vcpkg install --triplet=windows-x64 ffmpeg[vpx,x264] libepoxy libpng libzip lua sdl2 sqlite3`
And I still get this error when trying to open CMakeLists.txt in Visual Studio:
![image](https://github.com/mgba-emu/mgba/assets/3462541/5f3493bd-cf44-4fef-ac0a-9509879f95d9)
![image](https://github.com/mgba-emu/mgba/assets/3462541/67167523-fa45-45b9-804a-be5e9539ec1d)

**Comment by endrift** [comment]
You didn't set up vcpkg properly. You need to follow the vcpkg setup instructions for MSVC to see it.
