### ISSUE TITLE
"Bibi und Tina - Ferien auf dem Martinshof" crashes randomly

### ISSUE THREAD

**Issue by jrschreiber** [mgba-emu/mgba#294]
"Bibi und Tina - Ferien auf dem Martinshof" (GBA) crashes randomly in the overworld, which doesn't happen e.g. with VBA-M. After walking around sooner or later the textures fall apart, this phenomenon isn't fixed to a specific location. You may try it out for yourself – I'll upload a savestate to begin with (at the EOP – end of post).

![111](https://cloud.githubusercontent.com/assets/14123747/16544833/d71a9824-4114-11e6-9318-324e96b2fe03.gif)

I'm using mGBA 0.5-3655-ca46fed (somewhat most current version) on Windows 10.
I'm absolutely curious what causes the error!

Save State:
![bibi und tina - ferien auf dem martinshof ss1](https://cloud.githubusercontent.com/assets/14123747/16544852/8cace6d8-4115-11e6-9af4-5f52e92714ac.png)

**Comment by endrift** [comment]
The player appears to somehow get teleported out of bounds. Not sure what's causing it yet.

**Comment by MoochMcGee** [comment]
Does this happen on hardware at all? If VBA-M isn't hitting this, then I'm thinking it might be some sort of hardware race condition or something. If that's the case, then maybe it happens on hardware too in certain circumstances.

**Comment by endrift** [comment]
It seems to happen across loading zones, but I'm not sure why or with what frequency. Regardless, I highly doubt this happens on actual hardware.

**Comment by jrschreiber** [comment]
I can certainly verify, this doesn't happen on actual hardware.

**Comment by endrift** [comment]
Fixed by fa92b4cd0e461ede2a70077c8acf87078a931d05.
