### ISSUE TITLE
ARMv4 / GBA: Behavior of mGBA differs from hardware when using LDM

### ISSUE THREAD

**Issue by Teufelchen1** [mgba-emu/mgba#2942]
Hi :otter: 

mGBA does not correctly implement the behavior of the GBA cpu when an `ldm` op is encountered that affects the banked registers which is immediately followed by an access of one of the banked registers. If the devolper wants to, a `nop` can be added after the `ldm` to ensure correct behavior according to the ARM manual. The ARM docs can be found [here](https://documentation-service.arm.com/static/5f8dacc8f86e16515cdb865a), in section A4.1.21 LDM (2). It states:

  >  In ARM architecture versions earlier than ARMv6, this form of LDM must not be
  >  followed by an instruction that accesses banked registers. A following NOP is a good
  >  way to ensure this.

On mGBA,  such a situation "works" fine, just as the programmer would expect it. This differs from the real GBA hardware, where such a situation ends up as undefined behavior. In my experience, the accessed register(s) contain an random offset between 4 to 64, highly depending on the previous state of the pipeline.

Here is an real-world example of this bug: https://github.com/RIOT-OS/RIOT/pull/19619 The code shown (before the patch) worked fine in mGBA but showed UB on the GBA. With this patch, RIOT runs fine on hardware & mGBA. 

I would suggest emitting a warning when this situation is encountered. "Fixing" is not an option imho, as that would result in a lot of wasted debugging hours for homebrew developers accidentally triggering this bug.

**Comment by endrift** [comment]
I'm unsure I can fix this or add a warning, simply because both are equally expensive and would require doing a delayed operation. In fact, adding a warning would probably be even more expensive, as the register accesses themselves are not and cannot be checked. Figuring out and emulating the UB might be easier.

**Comment by fleroviux** [comment]
-Just for documentation purposes-

The behavior of the ARM7TDMI appears to be that in the cycle following the LDM^ instruction banked reads bitwise OR the user bank register with the current bank register and banked writes write to both the user bank register and the current bank register.

**Comment by endrift** [comment]
DS and 3DS GBA mode are probably identical. The 3DS's ARM7/9 is basically the same as the DSi's, and I'm not sure the ARM7 changed between the DS and DSi, beyond clock rate.

Unfortunately, I don't think this is viable to implement in mGBA. Sorry.
