### ISSUE TITLE
GB Classic: Mystic Quest (G) doesn't load battery save

### ISSUE THREAD

**Issue by Pat86** [mgba-emu/mgba#2943]
I dumped my german version of Mystic Quest (Final Fantasy Adventure) with the latest epilogue operator version and mgba doesn't load the battery save correctly, eventhough it works fine in other gb emulators (bgb in my case). It just starts a new game when i click on continue. 

savefile: https://drive.google.com/file/d/1WOnA6wjm4I9RaGhe2I2MYl25FXQ0rOvo/view?usp=sharing

**Comment by endrift** [comment]
If the file is 512 bytes, please use the Save Converter to convert it to the 256 byte format mGBA uses. This game uses the MBC2 save format, which is represented differently between emulators.

The link doesn't work. It says I need to request access. Please share it publicly.

**Comment by Pat86** [comment]
Ups, sorry. Link should be public now. 

And yes, it's 512 byte and converting it to 256 byte format did the trick. So Epilogue Operator extracts it incorrectly (?).

**Comment by endrift** [comment]
I wouldn't call it incorrect as much as mGBA is opinionated. MBC2, the mapper that that game uses, exposes a 512 byte range for save files, but the top half of each of those bytes is unusable. Most emulators and dumpers leave that top half as unused, but mGBA packs it to be half the size with the top half removed, for efficiency reasons.
