### ISSUE TITLE
Trouble with speed up

### ISSUE THREAD

**Issue by Zivion6** [mgba-emu/mgba#2944]
I was playing the pokemon outlaw file and I accidentally pressed the yank game pak button, since I've reloaded it, the frame rate has jumped from 60 to around 1100. The speed up option isnt turned on but it sure is sped up. Ive redownloaded the outlaw file and mgba. If anyone has a fix for this I would love to hear it.

**Comment by endrift** [comment]
Please ensure Sync to Audio or Sync to Video (preferably just the former) is enabled in settings.

**Comment by Zivion6** [comment]
Under which tab in 0.10.2 is that setting?
