### ISSUE TITLE
white screen when loading rom

### ISSUE THREAD

**Issue by Finalmtg** [mgba-emu/mgba#2946]
every time I try and load a game the rom only loads a white screen. normally I just mess with the audio/video settings and it fixes it but this time no luck. not sure if I am doing something wrong
[just loads whte screem.zip](https://github.com/mgba-emu/mgba/files/11716753/just.loads.whte.screem.zip)

**Comment by endrift** [comment]
Usually that manes your audio device is broken in some capacity. Try switching off sync to audio, and switching the audio driver, as well as updating your system's audio drivers. Make sure you also have speakers or headphones attached.

That said, this isn't a support forum, it's a bug reporting system. If you need technical support, please join the forums or discord linked on the website.
