### ISSUE TITLE
Multiplayer Not Working 

### ISSUE THREAD

**Issue by Dusk595** [mgba-emu/mgba#2949]
Hello there. I'm on the latest version of mGBA. I'm playing Super Mario Advance 4. I am planning to scan some digital dotted codes. I opened the multiplayer option. When I tried to connect the e-Reader with the game, there has been a communication error. 

I have tried the same thing connecting MegaMan Battle Network 5 with the e-Reader. I can't seem to connect the game with the e-Reader. What seems to be the problem with multiplayer? Has anyone had this issue?

**Comment by Dusk595** [comment]
> Reference issue number: 2925. I’ve found the portable version 10.0 works for me on SMA4. Anything newer I haven’t been able to get to connect. Don’t forget to generate a bug report and attach.

I just use version 10.0 instead?
And generate a bug report? How do I do that?

**Comment by DesertWolf29** [comment]
File > Report Bug click on generate a report and attach the zip file to this thread. I would try 10.0 the portable version. It's the one you don't have to install. I have managed to get the e-Reader communication to work on this version.

**Comment by Dusk595** [comment]
> Here ya go: https://s3.amazonaws.com/mgba/release/mGBA-0.10.0-win64.7z

I appreciate it. I have tried No$GBA for e-Reader content. That emulator always exits me out and I can never get back on it unless I reinstalled it. Glad another emulator that supports the multiplayer and e-Reader like mGBA exists.

**Comment by Dusk595** [comment]
> Here ya go: https://s3.amazonaws.com/mgba/release/mGBA-0.10.0-win64.7z

I appreciate it. I have tried No$GBA for e-Reader content. That emulator always exits me out and I can never get back on it unless I reinstall it. Ridiculous. I'm glad another emulator like mGBA supports the multiplayer and e-Reader exists. 

Edited: It's still not connecting. How did you get yours to connect?

**Comment by Testsr** [comment]
I was one of the testers for 0.9.0, and EReader supported worked in that version.

**Comment by Dusk595** [comment]
> I was one of the testers for 0.9.0, and EReader supported worked in that version.

Really? Multiplayer as well? I wonder why it doesn't work in the later versions.

**Comment by Dusk595** [comment]
[Window1.zip](https://github.com/mgba-emu/mgba/files/11772255/Window1.zip)
[Window2.zip](https://github.com/mgba-emu/mgba/files/11772256/Window2.zip)

**Comment by Dusk595** [comment]
![IMG_20230616_122716583](https://github.com/mgba-emu/mgba/assets/122160475/a03489aa-2942-4a97-8f30-33e60e8d2fc1)

This is what I got.

**Comment by Testsr** [comment]
> ![IMG_20230616_122716583](https://github.com/mgba-emu/mgba/assets/122160475/a03489aa-2942-4a97-8f30-33e60e8d2fc1)
> 
> This is what I got. 
 
Firstly, try having the E-Reader as second player. Secondly, we should probably close this issue, as the guidelines states that this place is not a support forum.
