### ISSUE TITLE
Iridion II verification?

### ISSUE THREAD

**Issue by taisel** [mgba-emu/mgba#295]
- Pressing all buttons to do a soft reset with the pause menu open during gameplay will crash the game.
- Intro to each level has the sample played too fast.

Can someone validate these? It afflicts all emulators I think. I haven't done so myself, although I should. The game seems too well designed to have a crash situation for soft reset.

**Comment by sergiobenrocha2** [comment]
I can reproduce the first issue, it happens in the intro too

![retroarch-0710-151703](https://cloud.githubusercontent.com/assets/5431285/16715280/90e78da6-46b1-11e6-9883-4756a351be3f.png)

**Comment by endrift** [comment]
Soft reset crash confirmed on hardware. Will need to take a bit of a closer look at the second issue.

**Comment by taisel** [comment]
Wow, they actually let it crash on that button combo?

**Comment by endrift** [comment]
They probably never noticed.

**Comment by taisel** [comment]
I'll close for now, but I'm wondering if a flash cart on HW has a weird way of instigating this, if that's how it was tested.
