### ISSUE TITLE
[Wii Question] Is Super Gameboy Borders a working feature on wii version?

### ISSUE THREAD

**Issue by almircanella** [mgba-emu/mgba#2957]
I can see in the options menu, but it does not seem to work with any sgb compatible game. Only black borders...I'm using 0.10.2, love play gb/c/a games on my crt 240p with my classic controller pro.

**Comment by endrift** [comment]
Yes it is. If a game is SGB compatible _and_ GBC compatible, it will run in GBC mode, which does not support SGB borders.
