### ISSUE TITLE
[e-reader] How do I use with Pokemon Emerald?

### ISSUE THREAD

**Issue by ablakely** [mgba-emu/mgba#2962]
I've loaded up an e-reader rom and so far haven't got it to scan anything.  I'm not sure if it's the image I'm trying to use or what as I haven't been able to find much on this feature.  When I try selecting mystery gift on the pokemon start menu it says the wireless adapter is not connected.

Edit:  After some more research I found that Ereader doesn't work on US version of Emerald.  I still could use some info about the format the card data should be in

**Comment by endrift** [comment]
1. This is a bug reporting platform, not a support forum. I don't know why people think it is. The Discord or forums are appropriate venues for this. I am unsure how to make it clearer this isn't a support forum.
2. Most common e-Reader formats are supported (e.g. .raw and .bin, and pre-loaded .sav files). Scanning images is more complicated but (somewhat) supported.
