### ISSUE TITLE
The Legend of Zelda: Link's Awakening DX has dark colors when in GBA mode

### ISSUE THREAD

**Issue by PikaSamus** [mgba-emu/mgba#2968]
I don't have a physical copy of LADX to check this on, so this might be accurate behavior.

Version: 0.10.2 and 0.11-8144-c5a7b1a9b (makes no difference)
OS: Windows 11
CPU: Ryzen 5 5600
GPU: Nvidia GTX 1660

GBA mode:
![image](https://github.com/mgba-emu/mgba/assets/63016614/aae41819-4b03-426a-a697-ee79d9998f7d)![image](https://github.com/mgba-emu/mgba/assets/63016614/ae4e51fe-3e83-4af4-908c-884829084a19)

GBC mode:
![image](https://github.com/mgba-emu/mgba/assets/63016614/45e94331-7355-4b03-bc7b-45a4e9a46da4)![image](https://github.com/mgba-emu/mgba/assets/63016614/aa4509fd-4ab0-4529-8f70-963b9697def5)

**Comment by endrift** [comment]
The GBA screen has a higher gamma than the GBC screen. This is an attempt to emulate the fact that GBC games look darker on GBAs, as well as canceling out the brighter colors late GBC games use when running on a GBA. It's a feature.

**Comment by PikaSamus** [comment]
I feel stupid now.
However, in my opinion, that doesn't really make sense as a feature. It is still pretty incorrect colors, and GBA games don't have higher gamma on mGBA despite using the same screen. IMO, it should just be left to the GBA-Color shader, otherwise to get good colors you need to run in GBC mode and use the shader (using ROM hacks to use GBA mode for the select games that make use of it).

**Comment by endrift** [comment]
Given a conversation I had on discord about this yesterday, I'm beginning to agree. It was done in the core side so it worked on systems without shaders (e.g. 3DS, Wii) but the implementation is far from ideal, and it's definitely weird that it's only on GBC games.
