### ISSUE TITLE
HLE BIOS does not redirect undef exception to DACS

### ISSUE THREAD

**Issue by LunarLambda** [mgba-emu/mgba#2972]
Not sure if this is intended to be a wontfix but encountering an undefined instruction (and all of the aborts, though they are unused) redirects to the FIQ handler in the official BIOS, which in turn jumps to the DACS entry point if the debug bits are set in the cartridge header. The HLE BIOS simply returns immediately from the undefined instruction vector.

Here's an example ROM (displays a white screen with HLE bios, shows 3 pixels "first demo" with official BIOS):
https://cdn.discordapp.com/attachments/890931966432641054/1125738901424832532/example-dacs.gba

On that note, `bkpt`, due to being used internally by the debugger, never throws undefined instruction (the ROM uses `blx r0` instead). It would be nice if this could be controlled somehow, via  a setting or detecting that the debugger is not in use.

**Comment by endrift** [comment]
This is largely because DACS is unemulated, as there's no known documentation or hardware, at least that's publicly available. If I were to add DACS support I would change that in the BIOS. That said, returning immediately from UNDEFINED is not really great if that's not what the official BIOS does, and I would consider that a bug.

**Comment by LunarLambda** [comment]
Well, it doesn't need to be emulated really. The entry point address is within the 32 MB ROM address space, and is called in ARM mode. At least that's all I need.

**Comment by endrift** [comment]
It's supposed to detect that there's no debugger attached if you call bkpt without one attached. Did I mess that up?

**Comment by LunarLambda** [comment]
Didn't seem to work for me. Also, after trying to step through it with the debugger console, in the bkpt case the console freaked out on me. I'll test a bit more in a bit.

**Comment by endrift** [comment]
I looked at the code and it seems to be just missing. I thought it used to be in there, but it's nowhere in the code.

**Comment by endrift** [comment]
bkpt handling fixed in 3f0d06e3070fece03efd5e68482d657b9e6dbcc7.

**Comment by LunarLambda** [comment]
Nice, thank you. Any plans to support the dacs entry point thing? If not, feel free to close.

**Comment by endrift** [comment]
Yes, I can do that. Is the information in GBATEK accurate?

**Comment by LunarLambda** [comment]
Yes it is. The bios checks part of the nintendo logo for the byte 0xA5, if present then jumps to either 0x09FFC000 or 0x09FE2000 depending on the value of byte 0xB4 of the header (picking the lower address if the byte has bit 7 set)

Return address to bios is in LR, and I *believe* it unconditionally switches to FIQ mode (even for undef/abort)

**Comment by LunarLambda** [comment]
Let me know if you need a description (not exact code) of the calling sequence

**Comment by endrift** [comment]
Added in 44e074a15e9651481f7f652ac006a7c9d58cbeb9. Dunno why this didn't get auto-closed.
