### ISSUE TITLE
Feature request: Update GBA-Color shader

### ISSUE THREAD

**Issue by PikaSamus** [mgba-emu/mgba#2976]
The GBA-Color shader is out of date and has since been greatly improved, so the one in mGBA is not as good as it could be (though still better than having no shader).

The current version is available in a Google Drive link here: https://drive.google.com/file/d/0B5KxdoFEcyTkZ3I0WWZkM00zT0k/view?usp=sharing

A workaround is to use the Reshade LUT downloadable in that folder which will have a more up-to-date version of the color fix.

Unfortunately, the only version available other than the Reshade LUT is in Retroarch's .slang format instead of the one used by mGBA, so I believe it would require rewriting.

**Comment by RafaelTrepaUnCarballo** [comment]
@PikaSamus  Can you make the Drive link public and available to any visitor? For easier testing

**Comment by Testsr** [comment]
Can not access even with a Google Drive account. Can an alternative link be provided?

**Comment by endrift** [comment]
https://forums.libretro.com/t/real-gba-and-ds-phat-colors/1540/214 It looks like he's aware of the issues, but hasn't addressed them yet. Hopefully at some point.

**Comment by PikaSamus** [comment]
I can upload it.
![Color-LCD-Pack zip](https://github.com/mgba-emu/mgba/assets/63016614/e9f821aa-0ae9-40d9-baec-1fbd46b12fae)
I uploaded it here, rename from .png to .zip (I think this will work).

**Comment by Ocatopuss** [comment]
The author has upgraded his color shaders, with a downloadable mega.nz link.

https://forums.libretro.com/t/real-gba-and-ds-phat-colors/1540/220
