### ISSUE TITLE
Emulator doesn't recognize shaders?

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#2980]
Version 0.10.2

I'm trying to apply shaders to the games, but when I click "Load New Shader", the files aren't accessible. When you open the folder for the shader, nothing's there.

![Screenshot 2023-07-15 192936](https://github.com/mgba-emu/mgba/assets/139659502/629c3288-4583-4c43-8c3b-fa8c23f2eba3)
![Screenshot 2023-07-15 192956](https://github.com/mgba-emu/mgba/assets/139659502/bbb884b6-8af2-4d6b-b89f-a617656718b3)

OpenGL is selected in both Audio/Visual and Enhancements.

**Comment by Livey1** [comment]
UPDATE: I didn't know what OpenGL is and don't have it installed. Feel free to close or delete this issue.

**Comment by endrift** [comment]
You uh, still don't know what OpenGL is apparently. You're supposed to click "Select Folder" in the corner. The UI is weird and doesn't show a folder selection dialog like it's supposed to.

**Comment by endrift** [comment]
I finally remembered to change the flow so mGBA ships zipped versions of those folders, which solves this issue with the weird UI as well as making them easier to distribute.

**Comment by jcchimaera** [comment]
Help... i have the same problem, it was normal before. but when i unload the shaders and try to pick another one it's just nothing there.

**Comment by kubistonek** [comment]
I JUST made an account to comment that it is indeed make in a really, really shitty way. i was struggling to load it for half a day then saw @endrift comment.

i thought it might only use .sf .gsls or specific video option but no, its just shitty menu

**Comment by endrift** [comment]
Yeah, it was supposed to show a folder select menu, not a file select menu, but for some reason the UI toolkit decided that's not what that option should do.

**Comment by profi200** [comment]
Interestingly this is not an issue under Linux. Is this a Windows specific bug in Qt?

**Comment by endrift** [comment]
Yep, it sure is. Probably why it took me so long to notice. I think Qt has a specific reason they do it, but I can't imagine why they don't offer a way to get a proper folder select dialog
