### ISSUE TITLE
[Wii] Add motion and solar sensor, please.

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#299]
Visual Boy Advance GX can detect which games support solar sensor, gyroscopic or rumble and uses the wiimote for that.

About the solar sensor, it shows a button in the menu to change the solar value. It can also detect the solar intensity using the IR sensor of the wiimote.

Regarding the gyroscopic, it uses the built-in gyro inside the wiimote. The same for the rumble.

Could you add this options to mGBA so those games became playable in Wii?

**Comment by endrift** [comment]
??? These are already supported. Solar sensor is a bit buried in the menus, but accelerometer works out of the box (Yoshi's Topsy-Turvy and Happy Panechu) and gyro (WarioWare Twisted!) requires a Wii MotionPlus at the moment, but they're all supported.
