### ISSUE TITLE
mGBA isn't classified under the 'emulator' topic

### ISSUE THREAD

**Issue by RetroEdit** [mgba-emu/mgba#2995]
I happened to be perusing all GitHub repos in the [emulator](https://github.com/topics/emulator) topic and noticed mGBA was missing from the list.

mGBA does have the topics [gameboy-emulator](https://github.com/topics/gameboy-color-emulator), [gameboy-color-emulator](https://github.com/topics/gameboy-color-emulator), and [gameboy-advance-emulator](https://github.com/topics/gameboy-color-emulator), but having the more broad `emulator` topic might be good for discoverability.

GitHub does have a [limit of 20 topics per repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics), but mGBA at time of writing only has 11 topics.

**Comment by endrift** [comment]
Good catch. Fixed now.
