### ISSUE TITLE
[Linux AppImage] qt.qpa.wayland: EGL not available

### ISSUE THREAD

**Issue by kimhbryan** [mgba-emu/mgba#2996]
Build version: 0.10.2
Operating System: openSUSE Tumbleweed 20230808
CPU: AMD Ryzen 7 6800U

Upon launching the AppImage, a warning shows up as below:
```
bryan@tumbleweed:~/Downloads/gba> ./mGBA-0.10.2-appimage-x64.appimage 
qt.qpa.wayland: EGL not available
```
and the app launches with the following error:
![image](https://github.com/mgba-emu/mgba/assets/67667838/7d2595bd-5fdf-44d0-af63-894754af8144)

Here is the bug report generated by mgba: [bug.zip](https://github.com/mgba-emu/mgba/files/12317286/bug.zip)

**Comment by fmnm04** [comment]
The same happens for me in both GNOME and Sway desktops

**Comment by Impasse52** [comment]
Same happens to me on KDE Plasma 5.27.8 on Wayland. Also, in my case the menu (File, Emulation, etc.) doesn't appear anywhere. Both OP's issue and this menu issue disappear when running the AppImage as sudo. Weird.

**Comment by endrift** [comment]
Please check if this happens with the newest dev build.

**Comment by Impasse52** [comment]
I'm assuming that you're referring to the one downloadable from https://mgba.io/downloads.html#development-downloads. Sadly this still does not solve it for me - nor the problem in the original post, nor the problem with the global menu that I mentioned.

**Comment by fmnm04** [comment]
The latest app image is still giving me the same error with this log

./mgba.AppImage

qt.qpa.wayland: EGL not available
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
QFSFileEngine::open: No file name specified

**Comment by endrift** [comment]
I believe this is fixed in this dev build, please download it and test it: https://s3.amazonaws.com/mgba/build/mGBA-build-2023-12-29-appimage-x64-8282-d83b2f99cd3d35509cf110bb47cbc72f569a31ed.appimage

**Comment by FranMUex** [comment]
It does, this error is now fixed (at least for me).

**Comment by fmnm04** [comment]
It does, this error is now fixed (at least for me).

**Comment by Impasse52** [comment]
Can confirm it's fixed for me as well, thank you for your hard work :)

**Comment by Dangonizer** [comment]
Still borked for me on the linked dev build as well as 0.10.3.
Console output:
qt.qpa.wayland: EGL not available
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
QFSFileEngine::open: No file name specified
