### ISSUE TITLE
Blank Qt window in the gif and video

### ISSUE THREAD

**Issue by sergiobenrocha2** [mgba-emu/mgba#30]
I can't select the directory to save gif and videos if I already loaded a game:

![mgba - bug](https://cloud.githubusercontent.com/assets/5431285/7944003/7f3f2c0a-093e-11e5-8940-ce76f27053fd.png)

**Comment by sergiobenrocha2** [comment]
ugh, forgot to say, 0.2 git branch

**Comment by endrift** [comment]
This is a known bug. It's fixed in 0.3, and I'm not sure I'll be able to backport the fix. I can see about a fix specifically for the 0.2 branch though. The workaround is to pause the game before opening that window.

**Comment by endrift** [comment]
Yeah, I'd have to backport way more than I'd want to to actually fix this in 0.2. Best I can do is either pause the game while that screen is open, or pass around some objects that aren't need except to pause it while the file dialog is open. I'm not sure why the file dialog is breaking things, but...it is. And only on Linux.

**Comment by endrift** [comment]
Just merged a bunch of stuff (way more than I wanted to) to fix this.
