### ISSUE TITLE
[Wii] Add the GX graphic interface to mgba

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#300]
A lot of emulators for Wii uses a beautiful open source interface called Libwiigui.
It would be great if mgba used it too.

http://wiibrew.org/wiki/Libwiigui

**Comment by GB-CG** [comment]
Personally, I like it the way it is; black & white simplicity. I'm not too keen on the way VBA-GX, SNES9x GX or Retroarch looks. But it's up to Endrift though.

**Comment by endrift** [comment]
All of the console ports of mGBA share the same codebase for the UI. I'm not adding a Wii-specific GUI just so it can use this one library.
