### ISSUE TITLE
GBA Audio: GBA BIOS intro audio is distorted (overblown)

### ISSUE THREAD

**Issue by Chariblaze** [mgba-emu/mgba#3006]
Systems tested: Windows 10, Ubuntu 22.04, Nintendo Switch

Using "out-of-the-box" settings: SDL audio driver, sync gameplay to audio. Switching to Qt Multimedia did not fix the issue.

---
This is how it sounds in 8210 16fe12c - listen to the second half with the Nintendo logo:

https://github.com/mgba-emu/mgba/assets/25140801/46633f60-bf4a-41c5-bfce-f2b69fc9e36e

[8210 bug report.zip](https://github.com/mgba-emu/mgba/files/12385397/8210.zip)

---
It changed in 8135 1c41e1e.

8134 c358f22 - normal sound:
(video was broken in this commit I guess)

https://github.com/mgba-emu/mgba/assets/25140801/25d1fd99-9a7b-48a0-80e9-ecaf8601a8f4

[8134 bug report.zip](https://github.com/mgba-emu/mgba/files/12385402/8134.bug.report.zip)

&nbsp;
8135 1c41e1e - overblown:

https://github.com/mgba-emu/mgba/assets/25140801/aa425bf4-cf9d-46c2-8ff3-e11ff99dc083

[8135 bug report.zip](https://github.com/mgba-emu/mgba/files/12385407/8135.bug.report.zip)

**Comment by endrift** [comment]
Thanks for tracking down when it broke. I knew it had broken but hadn't looked into it yet.
