### ISSUE TITLE
FE7 & FE8 periodically stop playing certain sounds for a while

### ISSUE THREAD

**Issue by GriffinRhein** [mgba-emu/mgba#3008]
I've done a full playthrough of Sacred Stones on mGBA version 0.10.2, and the entire time there would be seemingly random periods where neither the sound from dialogue appearing nor the sounds of menu/map navigation would play, but the music and the combat sounds still worked fine. In the case of the dialogue, I sometimes noticed a faint buzzing in place of the appropriate sound.

These periods usually last about 5 minutes before the sounds come back just as suddenly, and I found no pattern in when they would occur. Afterward, I started up a playthrough of Blazing Blade and the same thing happened on the very first map.

I'd previously used version 0.9.2 for a long time, and I don't believe it had this glitch.

**Comment by endrift** [comment]
Please try a development version--I believe this has already been fixed, but I haven't released 0.10.3 yet.
