### ISSUE TITLE
Sonic Pinball Party - Crash when resuming arcade mode

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#301]
In every emulator I've tried(mGBA, vba-m, my boy!) it always freezes when resuming arcade mode, I thought this was how the game is supposed to be but I tried the same rom on 3DS VC and it works fine.

Exact steps:
- Start arcade mode for either series.
- Once in game press start to save and quit.
- Exit out of the rom or emu, start it again and select continue.

I can only test mGBA on Wii.

**Comment by endrift** [comment]
Looks like the game forgets to initialize the value at 0x02017570 when you load from a save on a fresh boot.

**Comment by SuperrSonic** [comment]
Just realized it's not a crash, it's just ultra delayed. It actually just takes around 2 minutes to load.

**Comment by endrift** [comment]
Fixed in 93633ea60
