### ISSUE TITLE
[NixOS] lua crash when selecting existing file when converting savegames

### ISSUE THREAD

**Issue by DarkKirb** [mgba-emu/mgba#3011]
When selecting an existing save file in the savegame conversion utility, a “This file already exists, do you want to overwrite it?” popup appears, followed by the application crashing with the message:

```
PANIC: unprotected error in call to Lua API (core and library have incompatible numeric types)
```

## To Reproduce

1. on any nix-enabled linux distribution run: `nix-shell -p mgba --run mgba-qt`. This will automatically download and run the affected mgba version
2. select File→Save Games→Convert save game…
3. Select any output file that already exists

## Expected behavior

mgba should prompt you if you want to overwrite the file, and if you select yes, close the file picker and the popup, and list the selected file in the output file tab

## Actual behavior

mgba promptly crashes after showing the file overwrite warning (but before it is closed), with the message:

```
PANIC: unprotected error in call to Lua API (core and library have incompatible numeric types)
```

The full coredump summary according to coredumpctl: https://thermalpaste.technogothic.net/p/ta72u1.txt

## Potential cause

Lua version mismatch between mgba and libvlc. So packaging error. However the time at which vlc initializes is kind of strange, so that may be a bug on its own. This does not occur with the appimage.

## System info
Linux Distribution: NixOS unstable (also happens on 23.05)
CPU Architecture: amd64
mgba version: 0.10.2
DE: KDE Plasma Wayland 5.27.7, also happens on XWayland

If desired I can send you the full coredump

**Comment by DarkKirb** [comment]
Okay different potential cause, since neither mgba nor the nixos derivation depends on libvlc:

the KDE filepicker (libKF5KIOFileWidgets?) tries to play a warning sound when selecting a file that already exists for saving (together with the user prompt). This is accomplished through phonon (libphonon4qt5experimental), which loads libvlc through the phonon_vlc plugin. This results in two versions of lua being loaded simultaneously (5.2 for vlc and 5.4 for mgba), which confuses glibc’s dynamic linker?

In that case it could in principle be an issue on other distros that run KDE as well. I am not sure who is responsible for this bug, but it’s probably not here.

**Comment by endrift** [comment]
I suppose the question then is who's pulling in phonon? There are different phonon backends, so maybe you can swap out the phonon_vlc with phonon_gstreamer

**Comment by DarkKirb** [comment]
It seems that phonon_vlc is the only backend actively maintained? https://invent.kde.org/libraries/phonon-gstreamer/-/issues/1, https://community.kde.org/Distributions/Packaging_Recommendations#Non-Plasma_packages

but the archwiki article did link me to phononsettings, which i’ll have to try later
