### ISSUE TITLE
Where is the "Camera" setting on Vita?

### ISSUE THREAD

**Issue by eightbitgiraffe** [mgba-emu/mgba#3012]
On my Vita 1000 with the latest release and dev release of mgba, the Camera option in configure doesn't show up at all even when using a Gameboy Camera rom.
![Screenshot of the configure screen in mgba scrolled to the bottom. Notice the lack of a Camera option.](https://github.com/mgba-emu/mgba/assets/128985070/55d93eae-3b01-43ec-9ad4-e66fd93900bc)
I decided to look through the source for vita to check and see if that setting is still there, and sure enough, it's still right there in the `/src/platform/psp2/main.c` file.
![Screenshot of some code inside that `/src/platform/psp2/main.c` file, only containing the section of the code relating to this setting.](https://github.com/mgba-emu/mgba/assets/128985070/2d9cae8d-3f84-4141-ba07-56474864e794)
I would compile it myself, but I'm not really in the mood to set up a Vita development environment right now, maybe later.
Does anybody know what may be causing this?

**Comment by eightbitgiraffe** [comment]
I feel like I should also mention that the camera works perfectly fine, it's just locked to the front-facing camera.

**Comment by endrift** [comment]
Good catch, it's definitely missing
