### ISSUE TITLE
7zipped GBA ROMs fail to load on the 3DS version

### ISSUE THREAD

**Issue by childishbeat** [mgba-emu/mgba#3013]
I get a "Load failed!" error (or a system crash for some files), forcing me to switch to ZIP or GBA. 7zipped GB(C) ROMs work, though. I'm using a New 3DS BTW.

**Comment by endrift** [comment]
Please check to see if this is fixed on a current dev build https://mgba.io/downloads.html#development-downloads

**Comment by childishbeat** [comment]
I still get the same behaviour as before.
