### ISSUE TITLE
Does not distinguish between left shift and right shift

### ISSUE THREAD

**Issue by jeffythedragonslayer** [mgba-emu/mgba#3018]
Steps to recreate:

1. Load TONC's key_demo.gba
2. Tools->Settings->Keyboard
3. Click L and press left shift
4. Click R and press right shift
5. Observe that "Shift" is printed in both text boxes.
6. Click "OK"
7. Observe that only right shift is effective in the ROM

**Comment by endrift** [comment]
Duplicate of #1766
