### ISSUE TITLE
about rumble support

### ISSUE THREAD

**Issue by Northwemko** [mgba-emu/mgba#3019]
1.EZ ODE rom mods added vibration function to the game
https://www.romhacking.net/hacks/8027/
https://www.romhacking.net/community/6863/

can u  add mgba support for EZ ODE rumble function 

2.i'm check lua script,how to use lua add rumble for rom?
maybe u can create a tutorial

**Comment by endrift** [comment]
It's already supported, just not enabled by default on games that aren't known to have rumble. You need to enable it per-game by opening the game overrides menu before loading the game, and setting rumble to enabled.

**Comment by Northwemko** [comment]
> It's already supported, just not enabled by default on games that aren't known to have rumble. You need to enable it per-game by opening the game overrides menu before loading the game, and setting rumble to enabled.

1.i opened rumble but doesn't work
only for gba player mode work,some game only for EZ ODE cartridge rumble will not rumble
2.i'm check lua script,how to use lua add rumble for rom?
maybe u can create a tutorial
