### ISSUE TITLE
input device consumed - DEV || MANJARO 

### ISSUE THREAD

**Issue by LeannAlexandra** [mgba-emu/mgba#3026]
[system]
ROG Strix G531GT (2019)
intel i7-9750H (mobile)
32Gb ram
NVidia gtx 1650 , 4Gb (ddr5 i think)
operating system: MANJARO KDE

[Problem:] 
Starting mGBA removes xbox controller from evtest results (dev/inputs/event7) making it undetected in another emulator.  I doubt resolving this issue is necessary, as it is very niche - but I do want to do it anyway as I do not think it is an intended 'feature' of the app - please advise on where I can start looking.

[longer version]
when i start mGBA up it removes my xbox controller from the list - the only way to get it back is close mGBA, unplug controller, replug it. - I am working on a project where I want to emulate virtual controllers (this part is working, repository below) but as soon as mGBA is opened it consumes my input device leaving the others virtual devices sterile (without parent input): currently I am providing a passthrough of main controller, but mGBA supercedes my grab and removes is even from my evtest resutls. 
[github](https://github.com/LeannAlexandra/virtualController)

[the embarrassing part]
The best I can see is in the "QT" section - the input classes - but I fail to see how and how I can use this fo my goals - please help me in understanding why mGBA consumes my controller completely? So after opening mGBA - my evtest dev/input/event7 xbox controller is missing from list after opening the mGBA app. it also then seize to work with retro arch meaning it 
- i do not want to run mgba in a container as i feel an extra layer of emulation is just unnecessary. 

I do not need this issue resolved, I am just asking for a lead on where to find out what happens to the device and how to "hook/grab" it back without interfering the process. I believe I'll be able to assist in solving it.

**Comment by endrift** [comment]
This probably has something to do with how SDL is interacting with the controller; that's what I use for controller input.

**Comment by CasualPokePlayer** [comment]
Does setting `SDL_HIDAPI_JOYSTICK_DISABLE_UDEV` environment variable when launching mGBA end up avoiding this behavior?

**Comment by LeannAlexandra** [comment]
> Does setting `SDL_HIDAPI_JOYSTICK_DISABLE_UDEV` environment variable when launching mGBA end up avoiding this behavior?

You will have to deduct about 3 years of perceived experience from me and please tell me how to set that environment variable.

**Comment by LunarLambda** [comment]
you can run mgba from a terminal with it set:

```sh
SDL_HIDAPI_JOYSTICK_DISABLE_UDEV=1 mgba-qt
```
(or just `mgba` for the SDL frontend) (I think the Qt frontend still uses SDL for input?)

**Comment by LeannAlexandra** [comment]
didn't work; Back to the drawing board - I doubt that the error is within mGBA, so I will mark this as resolved
