### ISSUE TITLE
mGBA doesn't seem to like ELF binaries output by LLD

### ISSUE THREAD

**Issue by ketsuban** [mgba-emu/mgba#3043]
Version number: 0.10.2 (revision `2fb55450610a4d10479a1eed1408f905d79318e3`)

Unbeknownst to me, at some point between the last time I fiddled with Rust on the GBA and now they changed the `armv4t-none-eabi` and `thumbv4t-none-eabi` targets to use LLD. It seems like an inappropriate decision since (last I checked) LLD only supports ARMv5 and above, but whatever, the build succeeds and `objcopy` gives me a functioning ROM. The only problem is if I try to load the ELF binary into mGBA directly I get "could not load game, are you sure it's in the correct format".

I have only the most basic knowledge of the structure of an ELF binary, so I'll just share my hello-world program and hope you have the necessary skillz to figure out what's going wrong.

[finisterre.zip](https://github.com/mgba-emu/mgba/files/12842008/finisterre.zip)

**Comment by endrift** [comment]
The problem appears to be the linker script, not mGBA itself. This ELF has the entry point set to 0x00000000, which mGBA rejects since the entry point for a ROM is 0x08000000.
