### ISSUE TITLE
Discord Rich Presence setting missing in the UI

### ISSUE THREAD

**Issue by NimbusFox** [mgba-emu/mgba#3045]
OS: Windows 10 Home 22H2 64-bit
Version: 0.10.2 Release

The discord rich presence setting is nowhere to be found in the UI compared to when it was introduced. Not sure which version it was removed. The only way to turn it on at the moment is by editing the config.ini file. I have supplied images below showing that the tick box for Discord Rich Presnce is no longer available compared to 0.8.0

### 0.10.2
![0.10.2](https://github.com/mgba-emu/mgba/assets/7228476/d9f8505a-b650-4a1b-802e-623cf085a3cc)

### 0.8.0
![0.8.0](https://github.com/mgba-emu/mgba/assets/7228476/ac675b78-98d6-4fe7-801d-5d0e6ea5882a)

**Comment by endrift** [comment]
It moved to the Gameplay tab when that tab got added.
