### ISSUE TITLE
How about support the unicode string ROM path?

### ISSUE THREAD

**Issue by Jayatubi** [mgba-emu/mgba#305]
I tried these emulator on new 3DS which works great. However, I have to rename all the ROM to the ascii character path. Is there any plan to support the unicode string path such as with Chinese or Japanese characters?

**Comment by endrift** [comment]
You mean the fact that the filenames show up as ? instead of the character? Yeah, I'd like to fix that at some point. The font I ship with mGBA doesn't contain those glyphs, but I'm going to try to use the system font, which does.

**Comment by Jayatubi** [comment]
@endrift Not only the displaying. If the ROM is under a path with unicode characters the mGBA was unable to load it. Once I rename the path to remove the unicode characters it works well.

**Comment by endrift** [comment]
Oh...huh. The fact that it can't load it properly is definitely a bug I'll need to look into.

**Comment by endrift** [comment]
4f1dffa5bd12ca514ee71ea4ac8594f3731a4779 lets unicode filenames be loaded, but they'll still show up as ?s. I'm working on a branch that uses the system font so it'll have all the glyphs needed.

**Comment by endrift** [comment]
376c3e715e1b849077febe956aa954be53fad810 uses the system font, but this is on a branch at the moment. Once that branch is merged, both issues will be fixed.

**Comment by endrift** [comment]
Merged.
