### ISSUE TITLE
[Scripting] Crash when reading memory inside a watchpoint callback

### ISSUE THREAD

**Issue by ahigerd** [mgba-emu/mgba#3050]
Discord user "Karathan" caused a crash in mGBA with the following code:

```lua
logBuffer = console:createBuffer("Log")

function watchTest()
    logBuffer:clear()
    local value = emu:read8(0x0203FFFC)
    logBuffer:print(string.format("value: %i\n", value))
    logBuffer:print("watchpoint hit!\n")
    
end

function initBus()
    console:log("[MGBA-BUS] init")
    emu:setWatchpoint(watchTest, 0x0203FFFC, C.WATCHPOINT_TYPE.WRITE)
    console:log("[MGBA-BUS] Watching Memory...")
end

callbacks:add("start", initBus)

if emu then
    initBus()
end
```

Relevant chat quotes:

> <@endrift> I should make sure the callbacks only happen during the inter-instruction event instead

> <@ahigerd> Um... blink Hey, um, @endrift, what happens if you read from a read watchpoint callback? Does it trigger the watchpoint again? Or is that protected against? 
> <@endrift> I knew I forgot to test some edge cases

**Comment by SBird1337** [comment]
Some information on this:

* I could not reproduce the actual mgba crash, but the script does not work correctly either, the read call crashes the Lua handler
* mgba was built using the w64 docker container
