### ISSUE TITLE
SIO UART mode

### ISSUE THREAD

**Issue by mcejp** [mgba-emu/mgba#3053]
Hi!
Looking at the source for [SIO emulation](https://github.com/mgba-emu/mgba/blob/master/src/gba/sio.c), I don't see any reference to [UART mode](https://problemkaputt.de/gbatek.htm#siouartmode). Am I missing something or is this not implemented?

I was thinking about running mGBA headless to do automated benchmarking of some homebrew code, and it would be very convenient to dump the measured cycle counts through SIO registers to the emulator's standard output.

**Comment by endrift** [comment]
This is not implemented at this time. You can use the libgba extension in opt/ to do debug printing to stdout however.

**Comment by mcejp** [comment]
Thanks, I'll check it out :)

**Comment by mcejp** [comment]
The mGBA print extension works great. If you're curious, I wrote up what I'm doing with it: https://mcejp.github.io/2023/10/30/gba-benchmarking.html
