### ISSUE TITLE
Vita: L2/R2 and L3/R3 (touch buttons) not working

### ISSUE THREAD

**Issue by Disonantemus** [mgba-emu/mgba#3054]
I know that from: [`0.8.0: (2020-01-21)`](https://github.com/mgba-emu/mgba/blob/master/CHANGES) and [Issue #1292](mgba.io/i/1292) was closed (Vita: L2/R2 and L3/R3 can now be mapped on PSTV), and should be working. 

I did try with:
- mGBA-0.10.2
- mGBA-0.10.1
- mGBA-0.10.0
- mGBA-0.9.3
- removing `ux:/data/mGBA/config.ini`
- remapping other physical buttons works (Like: X, O, T, S, L, R, Select, Start)
- I did try front|back touch screen|pads
- Same works ok with RetroArch (Vita), but I prefer mGBA (Vita), because the UI it's a lot faster.

---

I'm doing something wrong?
I was trying 2 remap Menu (Cancel) button to R3 (and other things like: fast forward) when I found this.

**Comment by endrift** [comment]
There is are no L2/R2 or L3/R3 buttons on the PS Vita, only the PS TV.

**Comment by Disonantemus** [comment]
> PS Vita has two touchpads, one in front screen, and the other one at the back, both are used for:

- Native Vita games that use touch features.
- PS1 games that needs L2/R2 and L3/R3 input.
- PSP games custom mappings.
- RetroArch Vita: you can map L2/R2 and L3/R3 to useful features (Like: Menu, Fast Forward, Pause, Quick Save, Quick Load, and more), and free physical buttons 4 something else. Also allows combos (combinations like: L2+R2) to avoid mistakes.

---

> Vita has those physical buttons with accessories like [this](https://amzn.com/dp/B01ERA94BY), that allows:

  - Some native Vita games use this (Borderlands 2, Ratchet and Clank trilogy, Darkest Dungeons or any game that uses back touchpad corners).
  - Better PS1 games control.
  - Better PS3/PS4 remote play control.
  - Better PSP games control, allows extra button mappings.

---

When I did ask, was thinking about similar functionality 2 RetroArch.

**Comment by endrift** [comment]
Despite closing this previously, I've added support for this now.
