### ISSUE TITLE
[Feature Request] Import/Export Save

### ISSUE THREAD

**Issue by headhunter45** [mgba-emu/mgba#3058]
I thought "Load Temporary Save" was the import I wanted, but I was wrong.

I want something that let's me load a save file with a different name, but keep saving to my current save file. I would also like something that copies my current save to a new file, but doesn't change what file is being saved to.

The way I see this working is the import would overwrite the current save file with the data from the new save file and probably reboot the game. Export would just copy the current save file/buffer to a new file.

I'm doing rom hacking and I have a few different .gba files for the same game. I want to load up known backup saves, do something in game, save, and see if it worked without copying files around all the time.

**Comment by endrift** [comment]
Can't you just use the file browser for this? It doesn't seem like this would be much more convenient.

**Comment by headhunter45** [comment]
I've been swtiching to a terminal and rerunning the last command, but it would be nice to be able to bind a shortcut to it. Also at least the export would be nice in case I've loaded an alternate save and forgot which one.

That's more of an edge case though, and I understand if you don't want to complicate the menu further.

**Comment by endrift** [comment]
I think I meant to add a field to the ROM info dialog that had the filename of the loaded save file, which would address the latter point. That said, this feature is too niche and I don't think it's worth adding as described.
