### ISSUE TITLE
Using multiplayer for GB-games in nightlies

### ISSUE THREAD

**Issue by professorDODO** [mgba-emu/mgba#306]
Hi

I'm not sure, if the issues for the nightlies version belong here as well, but I give it a try.
Yesterday I found the emulator for the first time and play with a friend pokemon blue and red. Everything worked fine until we tried to use the "link cable". Apparently the two windows weren't connected via the multiplayer function. Thanks for the work you're doing and keep it up :)

**Comment by endrift** [comment]
GB multiplayer hasn't been implemented yet.

**Comment by professorDODO** [comment]
Tried it yesterday with Pokemon Smaragd for gba and it also didn't work.

**Comment by endrift** [comment]
GBA multiplayer is currently disabled in the nightlies due to some refactoring, and it's going to be rewritten and improved at some point soon.

**Comment by endrift** [comment]
GBA multiplayer has been restored, and GB multiplayer will be coming in 0.6.

**Comment by endrift** [comment]
GB multiplayer is partially done now.
