### ISSUE TITLE
DMG envelop change without retriggering sounds wrong

### ISSUE THREAD

**Issue by copyrat90** [mgba-emu/mgba#3067]
In the hardware, the envelop starts as expected, but in mGBA the envelop never starts.

## Hardware -> mGBA recording

https://github.com/mgba-emu/mgba/assets/34793045/d79eeb5b-0948-498f-88e6-3569fa5f1a08

## Test ROM

[F0_F7_no_retrig.zip](https://github.com/mgba-emu/mgba/files/13360772/F0_F7_no_retrig.zip)

## Code

```c
#include <tonc.h>

int main(void) {
    irq_init(NULL);
    irq_enable(II_VBLANK);

    REG_SNDSTAT = SSTAT_ENABLE;
    REG_SNDDSCNT = SDS_DMG100;
    REG_SNDDMGCNT = SDMG_LVOL(7) | SDMG_RVOL(7) | SDMG_LSQR1 | SDMG_RSQR1;

    REG_SND1CNT = SSQR_IVOL(15) | SSQR_TIME(0);
    REG_SND1FREQ = SFREQ_RESET | SFREQ_RATE(416);

    int wait = 45;
    while (1) {
        if (--wait == 0)
            REG_SND1CNT = SSQR_IVOL(15) | SSQR_TIME(7);
        VBlankIntrWait();
    }
}
```

**Comment by profi200** [comment]
Almost forgot. I wanted to mention that this specific regression also exists on DS and 3DS GBA hardware since it's not documented anywhere. So technically it's accurate emulation just not of GBA/GBA SP behavior. GB micro is unknown/untested.

**Comment by Dartz150** [comment]
> Almost forgot. I wanted to mention that this specific regression also exists on DS and 3DS GBA hardware since it's not documented anywhere. So technically it's accurate emulation just not of GBA/GBA SP behavior. GB micro is unknown/untested.

I must add that this works correctly in GBmicro, so only the DS/3DS GBA hardware modes have this bug.

**Comment by Gericom** [comment]
The problem might be that `_writeEnvelope` does not update `nextStep`. When the envelope changes from dead to not dead it should probably do that, because otherwise the envelope update will not happen (or I guess only after a very long wait depending on overflow behavior).

It's kinda peculiar that mgba has the same bug as ds and 3ds hw btw.

**Comment by endrift** [comment]
I'm unsure this change is correct, but I'll do a bit more in-depth checking later. I'm not 100% sure how writing to the envelope on an active channel works, but generally it's understood to be "buggy"

**Comment by profi200** [comment]
Good to know the GB micro is unaffected.
