### ISSUE TITLE
Save type

### ISSUE THREAD

**Issue by Shimmer2** [mgba-emu/mgba#3068]
GBA Pokemon Emerald cannot save archives. We hope the emulator can support changing the archive type to flash 128k

**Comment by endrift** [comment]
Pokémon Emerald uses 128 kB saves by default in the emulator and works, and always has. You probably have a bad ROM.

**Comment by Shimmer2** [comment]
My version is a modified ROM. Is there any way to save it?

**Comment by endrift** [comment]
Do not change the four letter code in the ROM header--it's usually BPRE, BPRJ, BPRP, or similar. You should leave it as-is.
