### ISSUE TITLE
Henkaku version > crash while in file browser on 1st time

### ISSUE THREAD

**Issue by DrLuthor** [mgba-emu/mgba#307]
Hi,

I can't tell you which version is used since I downloaded a vpk package from this link.
https://usercontent.irccloud-cdn.com/file/8I27YdEj/mgba.vpk

The app crashed on the first launch while I was in the file browser, going in and out a folder . I wasn't able to reproduce it, but I thought it was worth notifying you.

Keep up the good work

**Comment by endrift** [comment]
If you go up a folder too many times, it crashes the GPU while trying to exit the app, which is a known bug.

**Comment by DrLuthor** [comment]
So I'm closing this
