### ISSUE TITLE
Sped up by default?

### ISSUE THREAD

**Issue by Ghost-Konig** [mgba-emu/mgba#3075]
Hey, I'm not sure what happened, but I installed and reinstalled multiple times in hopes to fix it but I cannot fix this issue. For some reason, my audio and game is permanently sped up and I have no idea how to fix it. It happens with any GBA game I play.

**Comment by endrift** [comment]
First, this isn't a support page. Please use the Discord or the forums, both linked to on the site. It's a bug report page.

Anyway, you probably have both sync types disabled. Enable sync to audio in settings and the issue should go away.
