### ISSUE TITLE
gb rom screen size

### ISSUE THREAD

**Issue by Shimmer2** [mgba-emu/mgba#3076]
When running gb/gbc cassette games on the gba game console, the LR button can scale the screen size. I'm not sure if the emulator can add this feature to achieve a more realistic restoration effect. Thank you!!

**Comment by endrift** [comment]
I have no plans for this. You can make the screen wider by turning off lock aspect ratio already.

**Comment by Shimmer2** [comment]
I hope to add this feature to make it more convenient to realistically restore the actual scene of playing gba games
