### ISSUE TITLE
Autopatched ROM with BPS patch doesn't boot

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#3077]
When putting certain BPS patchs and the ROM with matching names, mGBA only shows a white screen.
If you patch the ROM, it runs fine in mGBA.

This bug is observed with this colorizing patch:
https://www.romhacking.net/hacks/7413/

**Comment by endrift** [comment]
I suspected BPS patching was still buggy but had never found a reproducer. I'll try to take a look at this soon.

**Comment by tdellion** [comment]
ive got some carts I thought were legit but when trying to back up I get white screen and logs with errors on boot but carts work fine in real GBA... are these batterless patched? how do we correctly get those to work with mGBA? or not possible?
