### ISSUE TITLE
Selected shader not applying

### ISSUE THREAD

**Issue by PatchSalts** [mgba-emu/mgba#3078]
Note: the second issue below turned out to be user error.

Hello! I've found 2-ish issues with regards to settings not being set properly when mGBA starts. They may be related, maybe not.

Some system info: I'm running EndeavourOS (Arch-based Linux distro), I have an AMD Ryzen 5 3600 and an AMD Radeon RX 5700 XT.

First: when I start mGBA, the shader is not loaded, even though it is present in the config files. I can apply the shader and save the settings to the config files, but the shader will not be loaded next time I open mGBA. This occurs on the development build I am using (0.11-8252-d75d26bcc via the AUR) but not on the release build I am using (0.10.2 via the Arch Linux extra repository (the package is versioned as 0.10.2-2)).

~~Second: when I launch a GB-only game, I'm pretty sure the game uses the default GBC color palette until I hit "Apply" on the Settings page, even though I have the GB-only model set to DMG and I have the GB palette set to DMG Green, with "GBC color palette if available" checked. This appears to be the same issue as #2377, and this happens on both builds I mentioned in the first bug, not just the development build.~~

I have attached a video of what this looks like, and a bug report from each of the builds I mentioned. I recorded the bugs with the development build, but the process I did before generating the bug report for the release build was identical.

[mGBA Shader + Palette Bug Report.zip](https://github.com/mgba-emu/mgba/files/13461653/mGBA.Shader.%2B.Palette.Bug.Report.zip)
[mGBA Shader + Palette Bug Report (release build).zip](https://github.com/mgba-emu/mgba/files/13461670/mGBA.Shader.%2B.Palette.Bug.Report.release.build.zip)

https://github.com/mgba-emu/mgba/assets/9244116/f574e1f7-ebba-4982-b537-f60eb15202b2

**Comment by endrift** [comment]
Please only file one issue per...issue. It's harder to keep track of what's been fixed if you put more than one in the same issue.

0.11 stores shaders as zip files renamed to .shader, whereas 0.10.x has them as folders. The config should be able to support both though. I know there was a bug report about this sort of thing happening, but I can't find it right now.

The second one is not a bug, it's misunderstanding the feature. The game is running in DMG mode, but with a custom palette. That's how it works on a real GBC too. If you don't want a DMG game to use the GBC palette, don't set that setting. If it were running in GBC mode it'd break due to difference between how the modes operate--an actual GBC will just set the palette then switch down to DMG mode before it starts the game.

**Comment by PatchSalts** [comment]
All right, my apologies. I will make sure not to do that in the future. Assuming there's already an issue for one and a... non-issue for the other, I guess there's no reason to keep my issue open.

Just to clarify, you mean that running GB-only games with "GBC color palette if available" checked will always use that red-and-blue palette once launched, but hitting "Apply" turns it back to the palette I've selected because the palette was only set once when the game launched? In that case "default" refers to my selected palette, and "Default color palette only" is probably the option I'm looking for?

**Comment by endrift** [comment]
I actually couldn't find an open issue for the other one, so let's leave it open for that.

The GBC color palette is different per-game, and only a few games have them. The one for Kirby's Dreamland is this garish one (maybe it looks better on a real GBC?). By hitting apply, you've told it to override that palette with the one you've set in settings (this part is very unintuitive and could be considered a bug), which in this case is the Game Boy green palette. Indeed, here "default" refers to the one you've set there and turning it to "default color palette only" is probably what you're looking for here.

**Comment by PatchSalts** [comment]
All right, sounds good to me. Seems to me like I need to do some more research, I didn't even know Kirby's Dream Land had a color palette, but I found some documentation explaining how that works.

I'll go ahead and edit the original post to indicate that the second issue is a non-issue.
