### ISSUE TITLE
Autoscrolling in Gen 3 Pokemon Party Menu

### ISSUE THREAD

**Issue by MatandoYT** [mgba-emu/mgba#3084]
Build: mgba - 0.11-8262-dc9a2572d (latest git rev as of issue opening)
OS: Kubuntu 23.10
CPU: AMD Ryzen 9 3900X
RAM: 128GB DDR4 3200 ECC
GPU: Nvidia 3070Ti 8GB

When playing through any mainline Pokemon game and entering the party menu the game automatically scrolls through the list even when no controllers are connected and the keyboard button mapping settings are set to blank. I've tested with Fire Red, Leaf Green, and Emerald. Ruby and Sapphire have not been tested but are presumed to also be effected.

The issue occurs with both X11 and wayland although I still, sadly, use X11 primarily....... because Nvidia.

I was going to report the memory leak too but that had been recently fixed before me opening this issue. It was causing game play lag overtime which is kind of funny given the insane amounts of RAM I have in my system.

Please let me know what other information you would like provided or what else I can to do help debug this. I can provide whatever information is necessary.

**Comment by Jaizu** [comment]
I didn't experience any issue like that but if any dev wants some technical input, this is the function that takes the inputs in the party menu in pokemon emerald: https://github.com/pret/pokeemerald/blob/master/src/party_menu.c#L1455

**Comment by Jaizu** [comment]
I use windows 11, latest mgba public release.
The party menu and contest move select use a different way to get the inputs, at least in the code.

**Comment by AlexDresden** [comment]
After much figuring out, I've discovered that if the "Right Bumper" is bound to a button, you need to have it removed.  The right bumper in the settings has no actual use and causes this disruption.

**Comment by endrift** [comment]
I pushed a revision to the controller handling last night that should resolve mapping issues regarding analog values (e.g. triggers and sticks), so please update, remap your controller, and see if it's fixed.

**Comment by endrift** [comment]
I don't understand how that's possible...can you please upload a bug report zip? Generated by File > Report Bug

**Comment by MatandoYT** [comment]
I've just double checked and remapped my controller. For some reason after the update the program picks up both a button press and analog input when I press up on my d-pad but only the up direction. Same with L/R buttons. After clearing the just the analog inputs on those specific mappings the controls work as intended. 

I'm going to close the issue as it appears from this point that it's an issue with individual controllers unless someone wants to add an option in the controller mapping to disable analog input. Regardless, I shouldn't suggest features I'm not willing to implement myself, heh.

Thank you for your help Endrift.
