### ISSUE TITLE
Gen 3 Pokemon Games Innaccurate Healing Sound (Mgba 10.2)

### ISSUE THREAD

**Issue by DarthPidgey** [mgba-emu/mgba#3086]
The Sound when you heal a pokemon with an item from the bag like a potion is inaccurate compared to real hardware, I have included a recording of a real GBA for what it should sound like 
[Heal Sound.zip](https://github.com/mgba-emu/mgba/files/13643763/Heal.Sound.zip)

**Comment by Dartz150** [comment]
To easily reproduce this, use this save, is located in Birth Island which is an area with no music. Enter your bag and use Calcium on Ho-Oh.

[Pokemon Emerald SAV.zip](https://github.com/mgba-emu/mgba/files/13725955/Pokemon.Emerald.SAV.zip)

**Comment by endrift** [comment]
I can reproduce, but I'm not really sure what's going on here. It might be a GB APU bug but I can't tell without more investigation.
