### ISSUE TITLE
Issues with sound effects of Super Mario Land 2: 6 Golden Coins

### ISSUE THREAD

**Issue by MinecraftMario27** [mgba-emu/mgba#3087]
I heard the problem with sound effects on SML2: 6 Golden Coins for the Game Boy on mGBA

https://github.com/mgba-emu/mgba/assets/137607853/cfd22421-0ff3-4e42-9cba-239f50b3d77f

On other emulator, it works just fine

https://github.com/mgba-emu/mgba/assets/137607853/89945259-c573-4399-a882-2df862825fdb

**Comment by endrift** [comment]
Sounds like it might be an issue with the sweep. Which version of mGBA are you using?

**Comment by MinecraftMario27** [comment]
> Sounds like it might be an issue with the sweep. Which version of mGBA are you using?

Latest on RetroArch

**Comment by endrift** [comment]
This appears to have been fixed in c5a7b1a9b7b1581a6cf348cf20d755f5df08dc5a, which was merged into the libretro branch shortly after this was filed.
