### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by luc-git** [mgba-emu/mgba#3089]
gba resolution scaling seems to be ineffective. Game looks identical with both resolutions

![image](https://github.com/mgba-emu/mgba/assets/102831178/748e9c98-cb6c-415f-991b-b217bfa63f64)

![image](https://github.com/mgba-emu/mgba/assets/102831178/68e8fd33-46fa-4772-b6d3-dc157a30c8f8)

The last mgba preview version is used in the above screenshots

**Comment by endrift** [comment]
This only works on scenes that use linear transformation effects, e.g. rotating sprites or "mode 7" effects. Otherwise, it just makes the pixels bigger because there's no additional data to sample from. I guess this could be documented better, but it's not a bug.
