### ISSUE TITLE
[Qt] [Bug] Binding "File > Exit" action to "Esc" yields no result

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#309]
If you go into "Tools > Settings > Shortcuts" and set the "File > Exit" action to the "Esc" keyboard key, nothing happens when you press Escape. It's worth noting that other keys work. I tried binding the action to both "K" and "Return" and those worked fine.

**OS:** Windows 10 Pro x64
**Build at time of writing:** 0.4.1 stable

**Comment by Testsr** [comment]
@karasuhebi Tested in latest nightly build. This bug can be closed, because Escape now works, to exit the program.

**Comment by endrift** [comment]
Please stop saying "this bug can be closed" if you can't confirm that you could reproduce it prior. Just because you can't reproduce it now doesn't mean it's fixed.

**Comment by Testsr** [comment]
OK.

**Comment by karasuhebi** [comment]
Retested and confirmed fixed. Closing issue.
