### ISSUE TITLE
[ARM] Torus Games's GBA games have a noticeable slowdown

### ISSUE THREAD

**Issue by freq-mod** [mgba-emu/mgba#3093]
This affects Doom (II) and Duke Nukem Advance. I didnt test other Torus games yet.

While the rest 3D games (VRally 3, GBA NFS demakes and such) run reasonably on weak devices, Doon 2 and DNA have horrendous speed issues, to the point where these games are unplayable without heavy frameskip. That happens even on mobiles devices with 4 Cortex-A7 cores and Mali GPU. Stronger dvices run these games fine, but considering other 3D GBA games run perfectly fine, one would expect Torus' software to run as well, which makes me suspect its some kind of an emulator issue.

Sorry if its invalid, or a libretro specific issue.

**Comment by endrift** [comment]
This appears to just be the game using more CPU time. I've tried to optimize it some, but none of that seemed to pan out. While I do want to improve performance in the long run, that's broad and not to a schedule. As such, this bug isn't, well, a bug.
