### ISSUE TITLE
OpenGL compilation logs don't get piped through

### ISSUE THREAD

**Issue by pineapplemachine** [mgba-emu/mgba#3095]
I've been working on custom shaders for mGBA 0.10.2. When something goes wrong, it's proving to be very tricky to debug and troubleshoot. The shader pass seems to just be ignored if there's any issue loading the shader code, and I haven't been able to find a place where GLSL errors are being logged. Have I just missed where they're being logged? (Or, if they aren't being logged currently, then please consider this a feature request!)

To be clear, the issue is not needing help with any specific shader, but with wanting to get visibility into the error messages when a shader fails to compile, since it is more difficult to write custom shaders if these error messages are not passed through to a log somewhere.

**Comment by endrift** [comment]
Shader compilation failures should be logged to the OpenGL category with the ERROR severity.

**Comment by pineapplemachine** [comment]
> Shader compilation failures should be logged to the OpenGL category with the ERROR severity.

Unfortunately this did not seem to be happening for me with 0.10.2.

I configured mGBA to output to a log file, while I fiddled around a lot with a shader. Here's the log, and the log settings, just below. The log doesn't include any shader-related errors, even though I wrote and had to fix quite many of them. (I didn't see any shader-related messages in the window opened by the View Logs option, either.)

Relatedly, what would be the best way to submit a new shader for inclusion with mGBA? Just a PR? The shader I've written (despite pinning down syntax errors being a bit of a challenge) imitates a GBC LCD subpixel arrangement, with an added backlight, and it supports quite a few customization options. (In fact, it's very loosely based on your own ags001 shader @endrift - thank you for that.)

![image](https://github.com/mgba-emu/mgba/assets/7266412/24113b64-55bc-4977-b053-3bd0dc3e1542)

```
[GAME ERROR] GB I/O: Writing to unknown register FF15:00
[GAME ERROR] GB I/O: Writing to unknown register FF15:00
[GAME ERROR] GB I/O: Writing to unknown register FF15:00
[GAME ERROR] GB I/O: Writing to unknown register FF15:00
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[INFO] GB Memory: Savedata synced
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[INFO] GB Memory: Savedata synced
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[INFO] GB Memory: Savedata synced
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[INFO] GB Memory: Savedata synced
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[INFO] GB Memory: Savedata synced
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[INFO] GB Memory: Savedata synced
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] GB Memory: Savedata synced
[INFO] Status: State 1 saved
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[INFO] GB Memory: Savedata synced
[INFO] Savestate: Loading screenshot
[INFO] Savestate: Loading savedata
[INFO] Savestate: Loading RTC
[INFO] Status: State 1 loaded
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[INFO] GB Memory: Savedata synced
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[INFO] GB Memory: Savedata synced
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[INFO] GB Memory: Savedata synced
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[INFO] GB Memory: Savedata synced
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[DEBUG] GB Serial I/O: Lockstep 0: Node init
[INFO] GB Memory: Savedata synced
[INFO] Status: State 1 saved
```

**Comment by endrift** [comment]
Hmm, I bet this is a threading issue with the fact that the GL rendering is running on a different core from the other loggers.
