### ISSUE TITLE
mGBA doesn't automatically switch audio output devices in Windows

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#31]
As of the latest nightly (0.3-2130-31993af), mGBA won't change the audio device it's outputting to when it's changed in Windows. Steps to recreate this:
1. Fire up mGBA
2. Load a ROM
3. Switch your default audio device (right-click the speaker icon, click on 'Playback devices')
4. ???
5. Profit

OS: Windows 8.1 x64

P.S. A workaround for this is pausing the emulator (Ctrl+P), which causes it to switch audio sources upon resuming.

**Comment by endrift** [comment]
I don't think that SDL or Qt Multimedia will inform the program when the default changes, so I'm not sure what I can do here, but I'll look into it.

**Comment by endrift** [comment]
There's no really good way to detect when the device has changed, and I don't think switching audio devices is a thing apps generally do. Punting to 0.4.

**Comment by wareya** [comment]
Some do, but it's not a general behavior. It's still nice to have, though.

**Comment by endrift** [comment]
SDL does not have a way of re-running audio detection device. This means it can't be done with the SDL driver, and the Qt Multimedia driver isn't shipped on Windows due to being rather buggy. Gonna have to close this unless SDL fixes this :/

**Comment by wareya** [comment]
SDL 2.0.4 added support for detecting device hotplugging, but I have no idea whether it works correctly:

    13 * Added events for audio device hot plug support:
    14     SDL_AUDIODEVICEADDED, SDL_AUDIODEVICEREMOVED

https://hg.libsdl.org/SDL/file/6ad89111cb4f/WhatsNew.txt

**Comment by endrift** [comment]
The problem here isn't device hot plug so much as the default device changing. Maybe there's a way to do it, but I'm a bit skeptical that there's a GOOD way to do it with SDL.

**Comment by karasuhebi** [comment]
Thanks @wareya :D

**Comment by karasuhebi** [comment]
No idea when this was fixed but as of 0.5.2 this is confirmed working on Windows 10 x64. Should we wait for someone on Windows 7 or 8.1 to close it?

**Comment by endrift** [comment]
I...guess something caused this to start working? Alright then.

**Comment by karasuhebi** [comment]
Confirmed working on Windows 7 by IRC user Extrems.
