### ISSUE TITLE
Misaligned pixels with OpenGL

### ISSUE THREAD

**Issue by Sonoob132** [mgba-emu/mgba#3101]
Build: 0.10.2
OS: Windows 10 64-bit
Hardware: Ryzen 5 5600X / RX 6600
Display 1920x1080

Using OpenGL (and OpenGL force version 1.x) as the display driver causes the pixels to misalign vertically. Software mode completely mitigates this issue. Other maybe related settings consists of; Video Renderer: OpenGL, Resolution Scale: 1x

This issue occurs on Windows 10 64-bit, Debian Bookworm and Ubuntu 22.04, the screenshots are taken from the Windows version however.

OpenGL with the problem. Most obvious with the planks:
![OpenGL](https://github.com/mgba-emu/mgba/assets/155564147/6f41d4a7-cd11-40ad-9d57-d1da5947d8ab)

Software; the intended:
![Software](https://github.com/mgba-emu/mgba/assets/155564147/0d4104b0-7e9c-4de0-9ad8-ec9991a752e6)

The issue didn't seem to occur while I took a screenshot of it ingame using the built in screenshot function so I cropped the whole screen.

**Comment by endrift** [comment]
This appears to be a texture mapping issue. I've seen it before on some drivers but I'm not quite sure how to fix it.

**Comment by endrift** [comment]
Just to confirm, do you have integer scaling enabled in the a/v settings?

**Comment by Sonoob132** [comment]
Sorry for the late response.
Force integer scaling? No.
When I enabled it though, it just shrunk the game screen and added more "black bars" but it fixed the problem
I would take a screenshot of the whole screen, but It doesn't work for some reason.
Tried both in Windows 10 and 11.

**Comment by endrift** [comment]
Yes, that's expected. The pixels are misaligned because at non-integer scales the number of pixels it takes to represent a single game pixel isn't consistent. Integer scaling fixes that but can only scale to multiples of the original size. The only other possibility is to smear game pixels across multiple screen pixels, which I think is what the Pixellate shader does.
