### ISSUE TITLE
Psvita henkaku mgba issue

### ISSUE THREAD

**Issue by nearsou** [mgba-emu/mgba#311]
Hi, i have a little problem, I install henkaku for psvita and mgba when I play pokemon silver for exemple my game is accelerated, its unplayable, thanks for your help
sorry for my english :(

**Comment by endrift** [comment]
This was fixed last night; please download a newer build from https://s3.amazonaws.com/mgba/mGBA-nightly-latest-vita.7z

**Comment by nearsou** [comment]
Thank you it works !
