### ISSUE TITLE
Zelda A link to the past henkaku psvita

### ISSUE THREAD

**Issue by nearsou** [mgba-emu/mgba#312]
Hi, I have huge fps drop on "Zelda A link to the past + four sword" gba game, is this normal ?

**Comment by endrift** [comment]
The Vita's just really slow.

**Comment by nearsou** [comment]
ok no optimization then, in snes there is no lag, thanks anyway, keep the great work !

**Comment by endrift** [comment]
Yeah, sorry, I hope to speed up mGBA even more, but it's not really a bug.
