### ISSUE TITLE
Pokemon Emerald Save File

### ISSUE THREAD

**Issue by Piewy** [mgba-emu/mgba#3122]
I've been trying to find the .sav file for my pokemon emerald save file but I think I've made a mistake by putting the rom in program/mgba as the only way I can access or see the save file is by launching the game. I can't find it in the mgba folder but the save file itself is working fine, is there anyway I can trace or find where the .sav files are without losing my 21 hours of playtime?

**Comment by endrift** [comment]
I think they're under C:\ProgramData or something like that.

Anyway, this isn't a support channel, it's a bug report form.

**Comment by Piewy** [comment]
Oh my bad, didn't mean to post it under the wrong channel, anyway thanks for the help.
