### ISSUE TITLE
PSVita (henkaku) > pb with ingame saves

### ISSUE THREAD

**Issue by DrLuthor** [mgba-emu/mgba#313]
Hi,

I played 14min Metroid Zero Mission and save in game. I load my save later and it worked perfectly.
I played for 2h, saving each time I was supposed to in the game without any problem. 
Then I quit the emulator (PSVita button + tearing appart the "page".
When I re-launched the game later, my in game save was the one I made at 14min :'(

**Comment by nearsou** [comment]
you can also use save state by pushing triangle button for the moment.

**Comment by DrLuthor** [comment]
Crash on loading on that specific game. Hadn't another one at the moment I was testing

**Comment by DrLuthor** [comment]
Ok, so I updated to the last nightly build.
Save state and in-game saves are working ! \o/
I assume it was fixed by the 1st August commit. Thanks
