### ISSUE TITLE
Can't use Shift as Fast Forward (Held) Bind?

### ISSUE THREAD

**Issue by Sartaryon** [mgba-emu/mgba#3131]
When I try to bind Fast Forward (Held) or Fast Forward to shift, fast forwarding doesn't work.

I removed every bind in Shortcuts that had Shift+Something bound.

**Comment by endrift** [comment]
Yes, this is a known limitation. I believe there's already a bug open about this but I'll have to find it.

**Comment by endrift** [comment]
Duplicate of #3007.
