### ISSUE TITLE
Wrong save type on libretro

### ISSUE THREAD

**Issue by Takumiboo** [mgba-emu/mgba#3135]
[Wrong save type used for Pokemon Fushigi no Dungeon - Aka no Kyuujotai (Japan)](https://github.com/mgba-emu/mgba/issues/2862)

I made PR to libretro/mgba.
https://github.com/libretro/mgba/pull/288

**Comment by endrift** [comment]
Yeah this is a downstream issue, it's already been fixed upstream. Once https://github.com/libretro/mgba/pull/291 gets merged the associated PR can be closed since the associated changes would already have been merged.
