### ISSUE TITLE
Mouse location will sometimes register as movement controls with touchpad on linux

### ISSUE THREAD

**Issue by SirFireball3521** [mgba-emu/mgba#3136]
Note: This is almost certainly related to #2630.

I am running mGBA on a panasonic toughbook CF-53 (cpu i5-3340M), with Arch Linux. My primary DE is i3, but I have also reproduced this on sway and lxde. This is kind of a difficult issue to describe, but in short when I move my mouse around the screen, it registers as movement commands in-game. This wouldn't be an issue if I could leave my mouse in one place and avoid this, but for some reason when the mouse is left in certain locations on the screen, it will register continuously as movement. For example, if I leave my cursor on some spots on the right half of my screen, mGBA will continuously register right-arrow inputs. It seems like there is usually sort of a "dead zone" somewhere on my screen that I can leave my cursor in safely. The location of these zones *might* depend on where the cursor is when the mGBA window gains focus, but I'm not sure. I also have this issue in DeSmuME on my laptop. I don't have this issue on my PC running Arch Linux with KDE at home. 

I'm happy to provide any more information or test things here if needed.

**Comment by endrift** [comment]
Please post the zip file generated by File > Report Bug

**Comment by SirFireball3521** [comment]
[report.zip](https://github.com/mgba-emu/mgba/files/14316053/report.zip)

Sorry for the delay.

**Comment by endrift** [comment]
Yeah, your trackpad is showing up as a gamepad for some reason. This is probably either a bug in the synaptics driver or a bug in SDL, my best guess being the former. I do need to add a way to disable gamepad input if not desired, but in the meantime you can clear the bindings manually in the settings. If you want help debugging further, ask me in the mGBA Discord where I can ask for more specific details more easily.
