### ISSUE TITLE
Clock based events won't happen.

### ISSUE THREAD

**Issue by gamer909090** [mgba-emu/mgba#3140]

**Comment by endrift** [comment]
In general, yes they do. The major exception is ROM hacks that try to be cutesy with how they change the file header in non-standard ways, breaking mGBA's heuristic. If you provide literally any information about what you're doing beyond "loading something that expects a clock" I might be able to help. But in general, this page is for reporting _bugs_, not tech support.

**Comment by gamer909090** [comment]
Ohh, I am probably playing a ROM hack then, seeing as I found the emulator
on a website, sorry.

**Comment by endrift** [comment]
Which ROM hack?

**Comment by endrift** [comment]
This is a fork of IodineGBA, an entirely unrelated GBA emulator. It's not a bug in mGBA.

**Comment by gamer909090** [comment]
Ok, I am so sorry for bothering you then.

**Comment by gamer909090** [comment]
One last question though, I downloaded your software, extracted the file,
(It took 1 minute), and I didn't see any way to start the software. How do
you do it, I am somewhat new to this.
