### ISSUE TITLE
Incorrect Gyro Values In WarioWare Twisted

### ISSUE THREAD

**Issue by CasualPokePlayer** [mgba-emu/mgba#3141]
The gyro values WarioWare Twisted receive appear to be half of their expected values. This results in TASers unable to do certain strategies RTA runners are able to do.

Example TAS Run: https://youtu.be/wDAfECnju24?t=326
Example RTA Run: https://youtu.be/fb40Vu8fVhc?t=324

Here is a pastebin noting the exact read/writes WarioWare Twisted uses to read out gyro state: https://pastebin.com/tgQfUhgx

I suspect the issue is that starting the ADC conversion process (or perhaps unsetting the ADC conversion process bit) should output bit 15 of the gyro state immediately, and subsquently triggering a serial clock afterwards should set bit 14 in the serial bit, not bit 15.

Attached are testroms (mb and cart variants both provided) to prove/disprove this theory.

[adc_clear_test.zip](https://github.com/mgba-emu/mgba/files/14276727/adc_clear_test.zip)
[read_gyro_test.zip](https://github.com/mgba-emu/mgba/files/14276739/read_gyro_test.zip)
[src.zip](https://github.com/mgba-emu/mgba/files/14276747/src.zip)

**Comment by CasualPokePlayer** [comment]
The second link is the "more test code."

**Comment by endrift** [comment]
Confirmed. On a stationary GBA the values I get are roughly 702/703 for test 1, E0A/E0C for test 2 and 705/706 for test wario, compared with 360/6C0/360 in mGBA.

**Comment by CasualPokePlayer** [comment]
What did the adc_clear_test show?

**Comment by endrift** [comment]
Didn't run it. You gave them the same filename and I was lazy. I can test that again in a bit.

**Comment by endrift** [comment]
Setting gyro ADC start cleared old serial data
Clearing gyro ADC start cleared old serial data

**Comment by CasualPokePlayer** [comment]
The latter sentence is more meaningless given the result of the first sentence (kind of bad test on my part, but eh). The first sentence confirms my theory that starting the ADC conversion process should output bit 15 of the gyro state immediately.

**Comment by endrift** [comment]
I'm honestly wondering if the data is actually on rising edge, not falling edge, and the reset counts as a rising edge.
