### ISSUE TITLE
Mgba controller buttons don't config properly 

### ISSUE THREAD

**Issue by thatsjustcray** [mgba-emu/mgba#3146]
i have tried two different controllers and it's the same issue. the controller setup config is just off, the right button is not syncing properly. i have used the controllers on every other emulator and they are working perfectly fine. 

thanks

**Comment by endrift** [comment]
This isn't very specific at all. Please use the report bug dialog under File to generate a bug report zip file to attach to this, show me a screenshot of the controller screen, elaborate on what "is just off" entails, and explain what "not syncing properly" means.

**Comment by endrift** [comment]
Never got that info...
