### ISSUE TITLE
PSP2 > game crash after a few minutes

### ISSUE THREAD

**Issue by DrLuthor** [mgba-emu/mgba#315]
After playing Metroid Zero Mission for a few minutes (bios enabled), the still crash everytime I try to play. This append on different part of the game, not in the same room. On a fresh start, it happens after 5 to 10 minutes. 
Maybe there's a buffer overloaded.

I attached my .sav file (extension changed to png) for easier testing.
![metroid - zero mission europe en fr de es it](https://cloud.githubusercontent.com/assets/1106909/17339478/63f14524-58ec-11e6-9679-b5234796ae25.png)

**Comment by endrift** [comment]
This should be fixed in the next nightly.
