### ISSUE TITLE
How do I start the emuler?

### ISSUE THREAD

**Issue by AllGoodNamesRTaken** [mgba-emu/mgba#3157]
Hi everyone, this might sound a silly question but after cloning the repo and executing  docker run --rm -it -v ${PWD}:/home/mgba/src mgba/ubuntu:groovy.

What do I have to do to actually start the mgba and enter some games there?

Thanks in advance!

**Comment by qeeg** [comment]
Why are you even doing that in the first place if you don't know how to compile stuff on Linux? Just download the AppImage or something from mgba.io. Also, upgrade your Ubuntu version, 20.10 has been EOL for a while now.

**Comment by endrift** [comment]
Or install it from a package manager, though that will generally be an older version. The groovy builder is old and probably won't work properly with modern mGBA.

Anyway, this isn't a troubleshooting forum, it's a bug report tracker, and this isn't a bug.
