### ISSUE TITLE
mBGA 10.3 not recognizing L button

### ISSUE THREAD

**Issue by erickrollano** [mgba-emu/mgba#3161]
after playing for a while and everything working properly, suddenly the in game system is not recognizing any L button commands, changing it randomly between other buttons whenever the L button is pressed.

Examples of how the issue is seen:
-Using a USB connected X-Box controller recognizes the L button as the SELECT button.
- Using default keyboard settings makes the selected L button to be recognized as the A button.
- Changing to personalized settings on keyboard has changed the button to either the B button or the START button.

**Comment by endrift** [comment]
Closing due to lack of reply.
