### ISSUE TITLE
Save and Load State menu's not visible while in Fullscreen

### ISSUE THREAD

**Issue by jaryth000** [mgba-emu/mgba#317]
### **Issue:** When in fullscreen Save/Load State menu's do not display on screen.

**Details:** While in fullscreen pressing the Save or Load state button (F10/Shift+F10/Square/Triangle on DS3) the menu does not display on the screen. The menu still works, and options can still be selected, but they do not display on screen. It acts as if the menu is still being rendered over the Window instead of the fullscreen viewport.

The menu's work fine while in windowed mode.

**Expected behavior:** Menu's should display while in full screen the same way they do while in Windowed.

**Builds Tested:**
_Current stable build;_ 0.4.1
Branch: heads/0.4.1
Revision: 64b68054693937601e5531456c10ecff37f1635f

_Current nightly build;_ 0.5-3719-1547768
Branch: master
Revision: 15477688d7d5df7199e0af97e6e07ebfce0ee500

Both had the same error.

Primary game tested: Final Fantasy V
Tested with several other games as well. With and without a BIOS loaded.

**System info:**
Windows 7 Ultimate SP1 x64
Intel Core i7-4930k (6 cores, 8 threads)
nVidia GTX 780 Ti

More information available on request if needed.

**Comment by endrift** [comment]
This is an old bug but I've only been able to reproduce it sometimes. I guess I need to look into this more.

**Comment by jaryth000** [comment]
Can I provide any additional information or testing to assist in nailing this bug down?

**Comment by endrift** [comment]
Can you verify if this still reproduces with r5046 or newer?

**Comment by endrift** [comment]
Please retest with latest dev builds. I haven't been able to reproduce this in a while.

**Comment by benderscruffy** [comment]
this has been fixed
it can be closed
