### ISSUE TITLE
Issues Mapping Controller 

### ISSUE THREAD

**Issue by thatsjustcray** [mgba-emu/mgba#3171]
[MGA Controller.docx](https://github.com/mgba-emu/mgba/files/14736061/MGA.Controller.docx)

I am having issues mapping my controller to the GBA, i have tired different controllers and it's the same issues. 

I use VisualBoyAdance with no issues and a few other emulators as well and they all work perfectly fine.

**Comment by endrift** [comment]
A...docx with a screenshot? Why not just upload the screenshot directly?

Anyway, for each of the buttons with a / in them, press both "clear analog" and "clear button" and remap them.

This isn't a bug, just bad UI design on my part, and this isn't a tech support forum, so I'm closing it.
