### ISSUE TITLE
Random crash on quit

### ISSUE THREAD

**Issue by Hexaae** [mgba-emu/mgba#3173]
Windows 11, 23H2
Started mGBA, launched a game and while running I close its window to quit the emulator...

Nome dell'applicazione che ha generato l'errore: mGBA.exe, versione: 0.11.0.0, timestamp: 0x00000000
Nome del modulo che ha generato l'errore: ntdll.dll, versione: 10.0.22621.3235, timestamp: 0xa2c4352c
Codice eccezione: 0xc0000264
Offset errore 0x000000000010f1bd
ID processo che ha generato l'errore: 0x0x1FE4
Ora di avvio dell'applicazione che ha generato l'errore: 0x0x1DA808057320293
Percorso dell'applicazione che ha generato l'errore: C:\Users\Luca\mGBA\mGBA.exe
Percorso del modulo che ha generato l'errore: C:\WINDOWS\SYSTEM32\ntdll.dll
ID segnalazione: f7f8985a-2b8b-44dd-b147-3ffc36ab046c

[config.ini.txt](https://github.com/mgba-emu/mgba/files/14780876/config.ini.txt)

[qt.ini.txt](https://github.com/mgba-emu/mgba/files/14780877/qt.ini.txt)

[mGBA.exe.31696.zip](https://github.com/mgba-emu/mgba/files/14780795/mGBA.exe.31696.zip)

**Comment by Hexaae** [comment]
I can randomly reproduce it (maybe 1/7?)

**Comment by endrift** [comment]
You already filed #3148 on this.

**Comment by Hexaae** [comment]
Ooops, sorry I totally forgot.

**Comment by Hexaae** [comment]
More info on this Exception Code: 0xc0000264 error...
Made some more tests and it seems a Input device issue: if I don't use NS Pro Controller I can't reproduce it.
This kind of crash/freeze doesn't happen on quit only, but also switching games (e.g. Metroid Fusion, WarioWare, Drill Dozer)... if you do this in loop continuously switching game rom mGBA will freeze. I couldn't reproduce when controller was off.
