### ISSUE TITLE
Lua isKeyActive() function gives "Error calling function (invoking failed)"

### ISSUE THREAD

**Issue by Real96** [mgba-emu/mgba#3175]
Tested this on commit e3edca1. When i try to check if the `Shift` keyborad key is pressed, using `input:isKeyActive(8388658)` (`8388658` is the special value tied to the Shift button according to the [docs](https://mgba.io/docs/dev/scripting.html#constant-KEY)), i get the error `Error calling function (invoking failed)`

**Comment by endrift** [comment]
Should be fixed in 5ff777d301d0d674b124eac0cf56021997078c3a.
