### ISSUE TITLE
Madden NFL 06 (USA) - flickering

### ISSUE THREAD

**Issue by Max833** [mgba-emu/mgba#3177]
Start a game and you will see that the screen is flickering. This doesn't happen with mesen.

![image](https://github.com/mgba-emu/mgba/assets/53529402/29fa4698-84bc-41ed-9baa-1d2caabaeac5)

**Comment by endrift** [comment]
This happens on hardware. Please see https://mgba.io/2020/01/21/mgba-0.8.0/#interframe-blending for more info about why games do this and how to work around it.
