### ISSUE TITLE
Rhythm Tengoku - Audio is static-y

### ISSUE THREAD

**Issue by debigulator** [mgba-emu/mgba#318]
I'm using an english patched rom, but that probably shouldn't matter? What do I know.

**Comment by endrift** [comment]
What OS and version?

**Comment by debigulator** [comment]
Vita and the nightly from the third.

**Comment by endrift** [comment]
It's probably just too slow. What does the framerate counter say?

**Comment by debigulator** [comment]
During gameplay it is ~56.

**Comment by endrift** [comment]
Yeah, there's your problem. If it's sub-59, audio starts to get crackly. I need to make the Vita version faster, basically.

**Comment by debigulator** [comment]
Got it. I'm new to this, so I'm a little surprised that such a small difference would matter.

**Comment by jaryth000** [comment]
It makes sense if you think about it, even at 56fps, thats 4 out of every 60ish frames that are behind, meaning every second you're missing/skipping 1/15th of that second. Just imagine watching something and every minute 4 seconds just disappear.
I'm sure with time emulation on Vita will become more stable (Wonder if the new HENkaku version with Dynamic Recompilation will help?).

**Comment by endrift** [comment]
Mass-closing all "audio is bad" bugs on PS Vita and 3DS unless you can repro on desktop.
