### ISSUE TITLE
mGBA Controller setup

### ISSUE THREAD

**Issue by AlexDresden** [mgba-emu/mgba#3180]
I got my Xbox One controller setup completed.  But anytime I play a game for example Pokemon Fire Red and I'm scrolling through either the boxes or the pokemon team list, the window automatically starts scrolling.  In the boxes, it goes to the next box nonstop and cannot be interrupted or anything.  When switching among the "6" pokemon for example it can be interrupted but if I leave it be, it will start scrolling from top to bottom as if the button is mashed down.  This doesn't just happen on this controller.  I have tried on different types and the same issue happens.  How do I stop this disruptive scrolling issue?

**Comment by endrift** [comment]
This isn't a support forum, it's a bug tracker. This is a controller mapping issue caused by confusing UI. Press both "Clear button" and "clear analog" on all of the buttons that are getting pressed "by accident" and remap them. You shouldn't have any extra /'s in places you aren't expecting, or your controls are wrong.

**Comment by AlexDresden** [comment]
![image](https://github.com/mgba-emu/mgba/assets/165860248/0bc6ac76-7984-4410-9ba3-f72442dcf8ca)
Here is my button layout.  I have already hit the clears for both button and analog but still no resolution.

**Comment by endrift** [comment]
Probably a duplicate of #3084 then.

**Comment by AlexDresden** [comment]
So no solution then.  So I'm stuck playing this on keyboard...

**Comment by AlexDresden** [comment]
After much figuring out, I've discovered that if the "Right Bumper" is bound to a button, you need to have it removed.  The right bumper in the settings has no actual use and causes this disruption.  You can use the controller bumper for another option, but in the mGBA emulator settings for controller - radical red > unbind the right bumper settings.
