### ISSUE TITLE
Visible stutter despite good framerate

### ISSUE THREAD

**Issue by NineKain** [mgba-emu/mgba#3181]
I've been having this isue on latest mGBA, latest dev build and latest RetroArch core, the games have perfect performance (I have an overkill PC), but the games have visible visual stutter and the frames "jump" (0 audio stutter tho)

https://github.com/mgba-emu/mgba/assets/72826232/b77fa83c-c44a-487b-8d9d-52b2f85884c5

https://github.com/mgba-emu/mgba/assets/72826232/7ce9c84c-082b-4e66-a968-da16bb824e3b

No matter what I do, settings I choose, the issue is still there, I'm using a 165hz monitor, and I have G-Sync activated, with solves this issue in all other emus, but not this one, is this a known issue? Thanks.

**Comment by endrift** [comment]
What games is this happening with? It could just be the game lagging.

**Comment by NineKain** [comment]
I've been testing and... Yeah just this one (Pokémon Unbound), I could've sworn it happened on some others.

How come the game could be lagging? my computer has overkill specs and it runs at a constant 60fps, or do you mean the GBA itself lags because mGBA emulates the original clockspeeds? If so, can we increase said clockspeeds?

**Comment by endrift** [comment]
Sometimes games just lag on original hardware. Overclocking on a GBA is tricky since if you naively just turn up the clock speed everything goes faster. Decoupling them is extremely difficult. I have some ideas for making things "overclocked" but not in the traditional sense. Anyway, since this seems to be an issue with the ROM hack I'm gonna close this bug.

**Comment by NineKain** [comment]
Update: the issue was on the romhack itself, it has a "high quality music" option which causes the stutter, turning it down to normal fixes it, sorry for the inconvenience
