### ISSUE TITLE
mGBA fails to launch when running from the command line. 

### ISSUE THREAD

**Issue by RylanYancey** [mgba-emu/mgba#3182]
# The Problem

When I try to run mGBA from the command line using `mgba <rom.gba>`  I get the following error:

```fish
wade@determination ~> mgba ~/Desktop/LegendOfZeldaTheMinishCap/LoZMinishCap.gba
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 152 (GLX)
  Request Minor code 6 ()
  Error Serial #111
  Current Serial #110
```

This is perplexing because when I run mgba using its start menu shortcut everything works perfectly. 

# Information

- OS: Ubuntu 22.04 LTS
- AMD Cpu + Nvidia Gpu
- mGBA was installed through the snap store
- `mgba --version` returns 0.8-27

I'm building a TUI to launch roms because Retroarch is ugly AF. Awesome project BTW keep it up.

**Comment by voloved** [comment]
@RylanYancey ,

How did you resolve this issue?
I'm getting a similar issue and cannot find any missing drivers on my end.
https://github.com/mgba-emu/mgba/issues/3451
