### ISSUE TITLE
"Load alternate/temporary save game..." doesn't work properly when the interface language is Simplified Chinese.

### ISSUE THREAD

**Issue by Hambaka** [mgba-emu/mgba#3187]
If the interface language is Simplified Chinese, the `Select save game` window shows nothing even those save files do exist:
![0](https://github.com/mgba-emu/mgba/assets/20476755/f1dac9f5-a9e4-4d70-b554-250d551cf596)

If the interface language is English, it works properly:
![1](https://github.com/mgba-emu/mgba/assets/20476755/5dabc522-b66b-4456-8129-2a9c5b3b1f0c)

**Affected versions:** from `0.10.0` to the latest development build `(2024-04-08-win64-8379-4652bbb4271af4054acfbf779df8720e424ad80b)`

**Comment by endrift** [comment]
Does this fail with any other load/save dialogs that have other file types?

**Comment by endrift** [comment]
The issue appears to stem from the use of fullwidth parentheses in the translation instead of ASCII parentheses.

**Comment by endrift** [comment]
Fixed in 2037e97fc9e4d58ed9565dd4f6b0b25f813841ef
