### ISSUE TITLE
PS Vita FFVI music clipping

### ISSUE THREAD

**Issue by masterrite** [mgba-emu/mgba#319]
Final Fantasy VI has really bad music clippings, both on the restored version and the original ROM. FPS around 26, though Pokemon Emerald runs fine (I'm sure a lot of people tested this game already).

Just thought you know and show my support!

**Comment by endrift** [comment]
Are you sure it's not just the audio being bad from it being so slow?

**Comment by Zeroba** [comment]
Ya, I'm pretty sure all the issues relating to bad audio are just because the emulation is slow.
I notice audio begins to 'crackle' as soon as you drop below the 59 FPS mark (Most of the time)

**Comment by endrift** [comment]
Mass-closing all "audio is bad" bugs on PS Vita and 3DS unless you can repro on desktop.

**Comment by masterrite** [comment]
It runs at a stable 30 fps

**Comment by endrift** [comment]
30 fps is half frame rate.
