### ISSUE TITLE
mGBA 0.11-8409 Hotkey Menu broken on Pop_OS! (Ubuntu 22.04) 

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#3192]
Attempting use the hotkey menu results in very broken behaviors, where the hotkey tree seems to repeat.  If I keep going deep enough sometimes some options will actually show up (and configuring them does work?!) but even further down the tree the emulator will crash.  The behavior is deterministic, and the same order of clicks each time will result in the same corruption.

![image](https://github.com/mgba-emu/mgba/assets/6598209/917bb34e-3fc1-4a4d-bf31-982ed420e6a4)

I have yet to find a workaround for this issue.  Note that I compiled mGBA myself, so potentially could be some other issue?  Screenshot of the titlebar just to be sure.

![image](https://github.com/mgba-emu/mgba/assets/6598209/90771317-5b9b-42c3-9e1d-91b19bd387e1)

**Comment by endrift** [comment]
Well I got a crash while trying to reproduce this, which is definitely exciting.

**Comment by endrift** [comment]
Please retest in 0.11-8430 or newer.
