### ISSUE TITLE
Mgba/Game is not recognizing any L button inputs

### ISSUE THREAD

**Issue by CorruptArrow** [mgba-emu/mgba#3199]
I have been playing radical red and after a certain bit the game just didn't take any L button inputs at all, I have changed the controls, tried using a controller, and it still doesn't work. I'm stumped

**Comment by endrift** [comment]
This is probably a binding mapping issue. This isn't a support forum, but just in case it's an actual bug please upload the zip generated by File > Report Zip. I can't tell either way without additional information that you haven't provided.

**Comment by endrift** [comment]
Closing due to lack of reply. If the information requested is provided I can reopen this.
