### ISSUE TITLE
Changes to the Fast forward speed multiplier only take effect on resume

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#32]
As of the latest nightly (0.3-2130-31993af), changing the fast forward speed multiplier won't take effect unless you pause and resume the emulator. If you're already paused, only resume is required.

OS: Windows 8.1 x64

**Comment by endrift** [comment]
I can't reproduce this on OS X. I will try Windows 7 later tonight, but I don't have Windows 8 to try on.

**Comment by karasuhebi** [comment]
@JMC47 wasn't able to reproduce on Win7. Might be an issue on my end.

**Comment by rincebrain** [comment]
Happens for me as well on 8.1 x64, tried with 0.3-2142-bbcf40e.

**Comment by endrift** [comment]
I likewise cannot reproduce this on Windows 7. I wonder if there's some race condition somewhere that I'm not seeing.

**Comment by karasuhebi** [comment]
Looks like @1a4ed6f fixed it. @rincebrain, can you test?

**Comment by endrift** [comment]
This is being reported as being fixed, closing.
