### ISSUE TITLE
Golden Sun Worldmap background is shaking

### ISSUE THREAD

**Issue by renecatharsis** [mgba-emu/mgba#3203]
When entering the Worldmap in Golden Sun,  the background looks like it's shaking. The player character and moving object don't seem to be affected. Find attached a gif showcasing the issue plus a matching savestate.
For what it's worth: The shaking is way less prominent when using Software Renderer, however the shaking is identical to OpenGL in video and gif/webp output.

![goldensun-shaking](https://github.com/mgba-emu/mgba/assets/1114906/78da3fdd-4848-4988-82f2-fcc9ce30501f)

Some YouTube playthrough video showing how it looks on (maybe) console:
https://youtu.be/9IEUOiixyEA?si=h7P05JBG0Wt2Gj6w&t=116

Build used: mGBA-0.10.3-win64 (1c61b54208ca6266129d0f2394c04bd8c44f98c5)
OS: Win11 Pro, 64-bit
System specs: AMD Ryzen 9 5900X, NVIDIA GeForce RTX 3070
BIOS used: mGBA BIOS and GBA BIOS (World Version)
ROM CRC: e1fb68e8

Not sure if it's related to any of the existing issues regarding Golden Sun:
https://github.com/mgba-emu/mgba/issues/3186
https://github.com/mgba-emu/mgba/issues/2558

[goldensun-savestate.zip](https://github.com/mgba-emu/mgba/files/15205154/goldensun-savestate.zip)

**Comment by endrift** [comment]
This is intended behavior by the game devs, see http://mgba.io/2020/01/21/mgba-0.8.0/#interframe-blending for more information and a workaround.
