### ISSUE TITLE
PS Vita -- when trying to load save state, application crashes

### ISSUE THREAD

**Issue by dgsmith** [mgba-emu/mgba#321]
I'm running the nightly build (08-03-vita-6e47d4...) and have just reinstalled the app. I have pokemon yellow at `ux0/` and am trying to save/load save states. I start the game just fine and can proceed to create a save state, but the moment I select `Load Save` the application immediately crashes. I've uploaded the output from the crash below. Am I perhaps supposed to have my ROM in a separate folder or something? I tried putting it inside `ux0/mGBA/` but that didn't seem to help. Inside that folder I now have the `.gbc`, a `.sav`, and a `.ss1`.

Thanks!

[psp2core-1470405994-0x0003ab26ad-eboot.bin.psp2dmp.zip](https://github.com/mgba-emu/mgba/files/403907/psp2core-1470405994-0x0003ab26ad-eboot.bin.psp2dmp.zip)

**Comment by DrLuthor** [comment]
Aside from the idea to fix the emulator / if you really wanna play the game, have yout tried [https://github.com/xerpi/realboy-vita/](realboy-vita/) ?

**Comment by dgsmith** [comment]
I have, I was able to save once (using native save within Pokémon), but then my next save didn't work :/ Do you know if realboy has save states? I wasn't able to find it

**Comment by DrLuthor** [comment]
I tried the last version of realboy w/ a euro (multi5) version of Pokemon Yellow. The in-game save works perfectly (played 15min, saved 4 times). If you got the las version, maybe you should try to un-install/re-install it, and delete save files if not done by automaticaly)

But yes, there's no save state at the moment. The emulator is quite new and the PSVita port is not a complete port right now : 
- no option menu
- haven't see any way to add the boot rom
- scale options are very limited
- no way to disable the experimental Super Game Boy option (which works fine but not great)
-

**Comment by endrift** [comment]
* What do you mean by "no option menu"? There's totally settings.
* Savestates are broken since I moved rendering to another core. I merged the branch too soon. I'll fix that today.
* Boot ROM is only missing for GB/C, but it's basically irrelevant there.
* There's no SGB support, period. There is GBC support.

**Comment by DrLuthor** [comment]
I'm talking about realboy here, which is a GB/GBC emulator. Sorry about that by the way. 
I just tried to help dgsmith to play his game another way since we had no idea when you'd fix the savestate in mgba.

**Comment by endrift** [comment]
whoops, sorry, just woke up

**Comment by DrLuthor** [comment]
No, my fault. I knew talking about another product in an issue might provoke that sort of misunderstanding.
Just couldn't help helping dgsmith ^_^

**Comment by endrift** [comment]
Fixed in 63a06ecc05ef5fd2dd350532e685192bb383052f.

**Comment by dgsmith** [comment]
@endrift oh I see, I had to compress for GitHub. Thanks both!
