### ISSUE TITLE
Performance on old 2DS

### ISSUE THREAD

**Issue by LIlaUraraka** [mgba-emu/mgba#3215]
I have mGBA on both my 2DSes, my 2DS XL, and the old slab 2DS, the performance on the XL is really good, except when saving (I exclusively play the GBA Pokemon games), and entering or exiting buildings. However, on the old 2DS, the performance is absolutely unplayable [`Video here`](https://share.icloud.com/photos/0e4MDhBpbaSSQlywGunE2wHQw)

**Comment by endrift** [comment]
Known issue. The old 2DS is just too damn weak to emulate the GBA effectively.
