### ISSUE TITLE
Unable to save game on pokemon cartridge dump

### ISSUE THREAD

**Issue by JustAnotherGameDevWasTaken** [mgba-emu/mgba#3217]
I recently dumped some gba games to play on this emulator, they all work other than pokemon Ruby and leaf green.

These are the symptoms that only seem to affect those two files:

The rom names are replaced with the actual filenames, all the other game dumps show the title instead of the filename.

the automatic save type on the emulator doesn't work so I have to manually override the save type to sram every boot otherwise it gives the "save failed" screen.

When loading the game or saving, the log shows "game error gba memory: bad cartridge store 16: " then a bunch of hex number.

Finally, if I reset or shut down the emulator from the emulation menu, when it loads back up, I get the "save file was deleted" message.

Sorry for the wall of text, I don't know what to include so I'm including everything I noticed. I'm using the flatpak 0.10.3 version under steam os.

**Comment by endrift** [comment]
These are probably bootleg versions and not the official release. Can you turn on logging to file and upload the log file?

**Comment by JustAnotherGameDevWasTaken** [comment]
I completely forgot I made this issue until I got an email about it, it turned out they were bootlegs, changing save type to 64ksram fixed the saving, but I still get the "bad cartridge store 16" messages, but they don't seem to be affecting anything???

**Comment by PSMGoossens** [comment]
I've the same problem. In the attachment you find me debug log. 
[logging fail save.zip](https://github.com/user-attachments/files/15596456/logging.fail.save.zip)

**Comment by endrift** [comment]
Yep, that's a bootleg there.
