### ISSUE TITLE
[BIOS] Unable to load alternative BIOS ~ EXEQ Game Box SP

### ISSUE THREAD

**Issue by OmDRetro** [mgba-emu/mgba#3227]
Hi,

I've mentioned it via [GBA Temp thread](https://gbatemp.net/threads/exeq-gamebox-bios-dump-for-possible-emulation-purposes.655495/) that an alternative BIOS doesn't seem to be compatible with the mGBA emulator. Is it possible to skip the logo check in order to use the EXEQ Game Box BIOS?

![](https://gbatemp.net/attachments/exeq_gamebox_bios-png.435829/)

**Comment by endrift** [comment]
You are misunderstanding what the logo check is. That's a check on the loaded game, not the BIOS. The BIOS checks to make sure the game has the correct Nintendo logo before booting it. If it doesn't, it just sits on the BIOS screen until you turn it off. If you load a game that won't pass this logo check, mGBA skips the BIOS display as it'd just fail and sit on it.

That is: the logo check has nothing to do with which BIOS you are loading, and only to do with which ROM you are loading. If that ROM triggers this, it wouldn't boot properly on a real GBA either.

**Comment by OmDRetro** [comment]
Ok, so that homebrew ROM shows the same text even with the GBA BIOS. Thanks for the explanation there.

However, trying to boot the EXEQ Game Box BIOS still just yields a white screen in comparison to an authentic GBA BIOS where the intro sequence shows. I'm not sure how to validate if it works or not apart from using another emulator.

This isn't that much of a big deal since there's also [an open source BIOS replacement](https://github.com/Nebuleon/ReGBA/tree/master/bios), but I do want to know if I dumped my EXEQ Game Box SP's BIOS properly as the logo of EXEQ does not show. 😀
