### ISSUE TITLE
mgba-qt crashes in Ubuntu 22.04 LTS due to undefined symbol

### ISSUE THREAD

**Issue by JORGETECH** [mgba-emu/mgba#3229]
I updated mGBA today to the latest development version available as of writing this issue (8465-e16dfc264), using the Ubuntu 22.04 packaged version.

When executing the "mgba-qt" executable through the terminal I get this error:

`mgba-qt: symbol lookup error: mgba-qt: undefined symbol: mScriptCanvasUpdateBackend`

This error causes mGBA to crash, it worked before in a previous development version from some months ago. The Qt version I'm using is 5.15.3 if that helps.

**Comment by endrift** [comment]
Did you update libmgba at the same time?

**Comment by endrift** [comment]
Never got a reply, so I'm assuming no.
