### ISSUE TITLE
Weird clicking (static?) sound on PS Vita when playing a game

### ISSUE THREAD

**Issue by mvaneijgen** [mgba-emu/mgba#323]
My sound is all the way down when playing a game and last night I noticed (when it was completely quite) that there was a weird clicking sound coming from my Vita speakers it sounds a bit like static like on a radio. When I click out of mGBA the sound disappears. 

Any idea? 

Vita PCH-1104 (3.60)
mGBA `mgba-threads.vpk` (can't find a version number)

**Comment by endrift** [comment]
It's just the game slowing down slightly, so it audio can't keep up. Not a bug, just mGBA not being fast enough on the Vita yet.

**Comment by mvaneijgen** [comment]
@endrift but my sound is off. I know the sound is not working therefore I turn my sound off. And I hear static from the speakers when my vitas sound is all the way off and this is not happing outside the mGBA app.

**Comment by mvaneijgen** [comment]
@endrift I thought that I would not be able to catch it witha microphone, but I can.[ Here is the sound its making](https://drive.google.com/file/d/0B3vLcFU70FD3eGZ2dEJrRzNINzQ/view?usp=sharing) when the vita volume is all the way off.

**Comment by endrift** [comment]
Yeah I'm able to reproduce this, but under a number of situations. It seems to be a hardware issue with the Vita, not a software bug.

**Comment by rsn8887** [comment]
It happens on PCH-2000, too. I have two Vitas. One clicks, one doesn't. It sounds like a hardware issue, some crosstalk between electrical traces on the motherboard or some such. It goes away when I plug in headphones, and it is not present on the headphone sound.
