### ISSUE TITLE
Another World boot up in black screen

### ISSUE THREAD

**Issue by pasha06** [mgba-emu/mgba#3235]
When i tried to boot up Another World (GBA port by Foxy) on mGBA, it does boot up. But for some reason, its shows black screen yet when tried to take screenshot it does show. However when tried on VisualBoy Advance, it does work and boot up into title screen.

(NB: this screenshot on the top is taken from VBA)
![Home](https://github.com/mgba-emu/mgba/assets/80947896/76b058aa-374b-4eb6-b73e-cd4f54d278c0)
![image](https://github.com/mgba-emu/mgba/assets/80947896/52a650ba-c64c-4e98-800a-022db32eb22e)

Top is VBA
Bottom is mGBA window

What it should have looked:
![Another_world-0](https://github.com/mgba-emu/mgba/assets/80947896/5a952acf-1926-4558-91d4-58635da7708e)
[Uploading anotherworldblackscreen.zip…]()

**Comment by endrift** [comment]
Please first update to 0.10.3, then generate a bug report ZIP using File > Report Bug, then attach it here.

**Comment by pasha06** [comment]
> Please first update to 0.10.3, then generate a bug report ZIP using File > Report Bug, then attach it here.

Ok i will try

**Comment by endrift** [comment]
Forward duped to #3236
