### ISSUE TITLE
.Deb packagings.

### ISSUE THREAD

**Issue by MesaBlack** [mgba-emu/mgba#3237]
I use a Chromebook to directly run deb applications without using the terminal. I've looked in releases, and there's no .deb files.

**Comment by endrift** [comment]
There are .deb files, they're the Ubuntu releases. I don't know what the base system they use so I don't know which .deb files you need.

**Comment by MesaBlack** [comment]
huh the three deb files in the 10.3 mantic have trouble installing due to
those... unmet dependencies
