### ISSUE TITLE
WarioWare Twisted Vita Issues

### ISSUE THREAD

**Issue by xperia64** [mgba-emu/mgba#324]
WarioWare Twisted at least on the PS Vita has a couple of issues.
1. The gyroscope input is reversed. (e.g. when tilting left, the game behaves as if it was tilted right)
2. This game in particular dips in framerate a lot and has crackly audio. I'm assuming this has to do with gyroscope polling as frameskip doesn't really help, and other games run more or less fine.

This is on a development build from this commit: https://github.com/mgba-emu/mgba/commit/8a68de198cd39e351ea84e040ecf5882b6234c03

**Comment by endrift** [comment]
1. The game is a bit weird with which direction it thinks is left and is right, sometimes counterintuitively. I'd need to get my hands on a copy to compare (I borrowed a friend's copy when I was implementing the gyro, and then he moved away).
2. No, the game's just really fucking slow. It taxes the CPU way more than most other games, so the emulation slows down. Frameskip is also mostly worthless now that mGBA is multicore on the Vita. I don't know if it even works.

**Comment by xperia64** [comment]
Flipping the sign of this: https://github.com/mgba-emu/mgba/blob/master/src/gba/hardware.c#L346
corrects the gyroscope direction the Vita. I don't know if this is correct for the 3ds or the Wii and other platforms, but it now matches my actual cartridge of the game.

**Comment by endrift** [comment]
That's the wrong place to do it, but ok I'll reverse the rotation.

**Comment by endrift** [comment]
Fixed in 68393718eb8b023f0ea27479615921c629c91ebc. I toyed with reducing the gyroscope polling, but it didn't really affect much.
