### ISSUE TITLE
radical red 4.1 bugging 

### ISSUE THREAD

**Issue by carlo661** [mgba-emu/mgba#3251]
i was playing pokemon radical red 4.1 and suddenly my character started to move slowly and when i tried to enter som buildings the game bugs and goes in loop and i can't do nothing, please help. 

[Radical Red.zip](https://github.com/user-attachments/files/16134096/Radical.Red.zip)

this is the save

**Comment by endrift** [comment]
Have you confirmed that the bug is in the emulator and not the ROM hack? ROM hacks tend to be buggy on real hardware too.

**Comment by carlo661** [comment]
> Have you confirmed that the bug is in the emulator and not the ROM hack? ROM hacks tend to be buggy on real hardware too.

i  think the problem isn't the emulator beacause if i open another game it runs normally but the problem is that i don't wanna lose the current save, do you know what can i do?

**Comment by endrift** [comment]
You should be saving in-game from the game's menu and not relying on save states.

**Comment by carlo661** [comment]
> You should be saving in-game from the game's menu and not relying on save states.

if i try to save ing-game the game kinda crashes and doesn't open the menu, i don't know what to do
