### ISSUE TITLE
[Bug] Unable to Multi-Select Pokemon in PC Storage in Pokemon Games [build-2024-07-11-win64-8487-9b598d2fe4c5ae49180fd381c742e5cb8a0973f0]

### ISSUE THREAD

**Issue by Priestyle** [mgba-emu/mgba#3257]
I'm unable to multi-select pokemon in pc storage in pokemon games. When you press select, the cursor turns yellow and you can multi-select pokemon to help organize faster. However, when I press A after turning the cursor yellow, it doesn't select multiple pokemon.

**Comment by CasualPokePlayer** [comment]
Are you actually playing FireRed/LeafGreen or Emerald?

**Comment by Priestyle** [comment]
Yeah, I actually tested this on Ruby and Emerald. I also tested this on mGBA-0.9.3-win64.

**Comment by CasualPokePlayer** [comment]
Ruby does not have this feature, it was introduced in FireRed/LeafGreen.

Are you actually holding A to have multiple Pokemon selected before letting go of A to "finalize" the selection.

**Comment by Priestyle** [comment]
Then why does the cursor change the exact same way in pokemon ruby and sapphire as it does in firered, leafgreen and emerald. What does the yellow cursor do in ruby and sapphire?

**Comment by CasualPokePlayer** [comment]
It lets you grab a Pokemon without having a menu of options.

**Comment by Priestyle** [comment]
Hey I just tested this on a real cartridge on my gameboy advance sp and pressing SEL in pc box and holding down A while moving the cursor allows you to select multiple pokemon at once for faster organization. I think this is a bug. Please look into this.

**Comment by endrift** [comment]
I have no idea what you're talking about. https://github.com/user-attachments/assets/914bf409-f443-4911-9a17-aa74cc3f211d

**Comment by endrift** [comment]
I've also confirmed that it works the same in Emerald on hardware and in emulator. I'm pretty convinced that either something is wrong with your controls, you're hitting a key rollover/jamming issue, or you're just very confused.

**Comment by Priestyle** [comment]
Um Endrift, you're saying that multi-select doesn't work on Emerald just like how you showed on your video of you trying to do it on Ruby? But on emerald, multi-select works on mgba. I'm really confused.

**Comment by endrift** [comment]
I'm saying that multi-select doesn't work on Ruby on hardware or in mGBA but it does work on Emerald on both hardware and in mGBA. There's no discrepancy between hardware and mGBA, and therefore no bug.
