### ISSUE TITLE
[libretro] Saving on Switch didn't get persisted to disk

### ISSUE THREAD

**Issue by vmsh0** [mgba-emu/mgba#3267]
Hi,
I'm playing Pokémon Sapphire on mGBA through RetroArch on Switch.

I've now lost my progress twice, the first time about 2 hours worth, and the second time about 4 hours worth.

The first time I thought I turned off the Switch and forgot to save the game after the last 2 hours of progress. I.e. human error. So for the next 4 hours, I compulsively saved every 15/20 minutes of progress.

Then I restarted the Switch, and I was taken back to the very same state again.

I.e. mGBA silently fails to save the game.

Needless to say, this has killed my run; I don't feel like playing through the same stuff for the third time and then lose it again. But if there's anything I can to do help pinpoint the issue, I'll do my best

**Comment by endrift** [comment]
When using RetroArch, it's RA that's responsible for writing the file back to the SD card. I doubt mGBA itself is at fault here.

**Comment by vmsh0** [comment]
Hi,

I'm sorry to have impulsively opened this report; I should have checked
more thoroughly how saves worked in libretro mode before opening a report.

Ultimately, that is also the reason why I lost the hours: RetroArch might
have stupid writeback defaults, but it's not like they keep it a secret.

I imagine this can be closed. I apologize once again. I will raise my
perplexities to RetroArch directly.

Riccardo


Il mer 31 lug 2024, 02:42 Vicki Pfau ***@***.***> ha scritto:

**Comment by endrift** [comment]
I understand your frustration. I just don't think there's much I can do about it.
