### ISSUE TITLE
Cannot select shaders within mGBA

### ISSUE THREAD

**Issue by VGF64** [mgba-emu/mgba#3268]
I just don't have the option to select shaders whatsoever. I go into the shaders within mGBA, click on one of the shader folders and I can't select them at all? How can I get this to work??

![Screenshot (371)](https://github.com/user-attachments/assets/1fc4052a-9787-4d5c-9898-2911e73c5139)

I click the "open" and it's not doing anything.

**Comment by endrift** [comment]
This is a bad interaction between Qt (the thing I'm using to make the GUI) and Windows. You have to open the folder itself. I'm not sure how you do this on Windows 11. This is "fixed" in the development build so the shaders are files (zip archives) instead of folders. If you want to switch to a dev version via the updater make sure to delete the shaders directory first.

**Comment by VGF64** [comment]
I updated to a development build before reading this message, unfortunately I didn't delete the shaders directory beforehand. Is there another way to get the shaders zip archives?

**Comment by endrift** [comment]
Wait, you did? Are you using the installer version or the portable version? The portable version should fail to update if you don't delete that directory; that's why I mentioned that.

**Comment by VGF64** [comment]
Oohhhh, I think I'm using the installer version. I updated using the emulator's updater and then it installed a whole new separate mGBA program without actually updating the one I'm currently using.

**Comment by Squall-Leonhart** [comment]
> This is a bad interaction between Qt (the thing I'm using to make the GUI) and Windows. You have to open the folder itself. I'm not sure how you do this on Windows 11. This is "fixed" in the development build so the shaders are files (zip archives) instead of folders. If you want to switch to a dev version via the updater make sure to delete the shaders directory first.

Windows shell browser button appears as "Select Folder" and tests fine here.

**Comment by endrift** [comment]
Functional UI can still be confusing. This issue has been resolved already. You have no reason to be digging at it.
