### ISSUE TITLE
[Vita] Opening Menu tanks fps by 10+

### ISSUE THREAD

**Issue by Zeroba** [mgba-emu/mgba#327]
Title says it all, opening the menu seems to almost always cause the framerate to tank once you close it, even if you don't change anything.
Tested on latest nightly

**Comment by endrift** [comment]
Is this still an issue? I haven't seen it in a while.

**Comment by Zeroba** [comment]
On the last nightly, it didn't seem to be. I'll fiddle with it and come close this if it turns out to be fixed.

**Comment by Zeroba** [comment]
Unfortunately still seems to be happening. If you'd like to try it on your own build, I went into the menu, changed a control map, saved it, and saved in the menu.
Went from 58-59 to 48 FPS in zero 3.
Perhaps I need to nuke the entire install rather than deleting it from the livearea next time I install.

**Comment by OTFree** [comment]
I've only had it happen once in a blue moon when I'm playing the Pokemon
titles, but I haven't really tested it with anything else.

**Comment by Zeroba** [comment]
Would be odd if it was game-specific. 
Did you try changing any settings when trying to replicate, or simply open and closing the menu? That seems fine.

**Comment by endrift** [comment]
Fixed in a43c465f9fe18b5959121b0fe6dd5cfc358e83c2.
