### ISSUE TITLE
mGBA won't open and crashes.

### ISSUE THREAD

**Issue by SmasherNicko** [mgba-emu/mgba#3273]
For some reason mGBA has recently stopped working properly on my main PC, where it doesn't open at all. I know it has worked in the past from using it some time ago, but suddenly it's just no longer working. I've tested mGBA on a laptop and seems to work fine, but with the main PC it just refuses to open and crashes, based on Task Manager showing it running for a few seconds and then it just disappears.

I've tried re-downloading the latest version and slightly older versions and all of them crash. I've tried downloading the latest developer build and the same result happens. I've also tried deleting certain files that mGBA creates when it's not set as a portable install in case that was causing some issues.

I also tried updating my OS and NVidia graphics drivers based on seeing [this thread](https://github.com/mgba-emu/mgba/issues/2745) but that didn't work either.

mGBA is producing crash dumps but I don't know how to read/access them to understand what might be the issue. I've included two crash dumps, one for 10.3 and the latest dev build;

[mGBA 10.3 crash.dmp](https://github.com/user-attachments/files/16645374/mGBA.10.3.crash.dmp)
[mGba latest dev crash.dmp](https://github.com/user-attachments/files/16645375/mGba.latest.dev.crash.dmp)

My PC Specs;

OS: Windows 10 Pro 64-Bit
CPU: 12th Gen Intel(R) Core(TM) i7-12700K   3.60 GHz
Motherboard: ASUSTeK COMPUTER INC. ROG STRIX Z690-A GAMING WIFI D4 (LGA1700)
Graphics Card: NVIDIA GeForce RTX 4080
RAM: 32GBs

If someone can find a solution that doesn't resort to re-installing the OS just to play GBA games then it would be much appreciated. Especially if this issue ends up causing problems for other stuff in the future too.

**Comment by SmasherNicko** [comment]
Okay I figured out the problem on my own later in the day after posting this, but I still have no idea why this causes mGBA to crash before it even gets to the window.

For some reason, the issue is related to my 8BitDo USB adapter that I use to connect a Switch Pro controller to my PC. If I turn on my Switch Pro controller and change it to "Switch Mode" then mGBA just boots up as intended with no issue. I've also tried this with the dev builds I downloaded recently too and they work now. 

I have no clue as to why a wireless adapter and the state of a Switch Pro controller would cause an emulator to crash.

**Comment by auroraourania** [comment]
I had a similar issue pop-up with my Xbox adaptive controller, and the issue turned out to be that it was trying to both connect via the cord and Bluetooth, and whenever it temporarily succeeded at connecting via Bluetooth, the game would crash instantly. I'm wondering if it can't handle something around that, and if that could be related to your issue

**Comment by estebanovic** [comment]
I had the same error, it just wouldn't open. Turned out I was charging my 8bitdo SN30 on my PC via USB, and unplugging it fixed it. Connected via Bluetooth I haven't had any issues.
If it wasn't for finding this issue, I never would've thought that was the reason.
I'm using version 0.10.5
