### ISSUE TITLE
mGBA-qt crashes on startup

### ISSUE THREAD

**Issue by freq-mod** [mgba-emu/mgba#3276]
fresh master as of Aug 21 2024:
`QWaylandGLContext::makeCurrent: eglError: 0x300d, this: 0x7076fc001630 
`
```mgba-qt: ../libepoxy/src/dispatch_common.c:872: epoxy_get_proc_address: The assertion condition `0 && “Couldn't find current GLX or EGL context.\n”' was not met.
Aborted (memory dump)```

Arch Linux, KDE, intel UHD 620

**Comment by endrift** [comment]
Does this happen with the latest dev build? I recently updated the builder so EGL stuff _may_ be working better now. I haven't tested yet.

**Comment by freq-mod** [comment]
It still does that. Sorry for keeping you waiting.

**Comment by freq-mod** [comment]
Only thing that changed is now `this` address in `QWaylandGLContext::makeCurrent: eglError: 0x300d, this: 0x73dc80001660 ` is different

**Comment by endrift** [comment]
This might have been fixed by 377ddf50810a5cd1889e0cdfd86298c577b8a956. Can you try latest dev build again?

**Comment by freq-mod** [comment]
it seems it works now, thanks!
