### ISSUE TITLE
controls remap for ''select'' and ''start'' to x/y keep resetting to default

### ISSUE THREAD

**Issue by amarantsnipersnake** [mgba-emu/mgba#3277]
i dont know if its bug. but everytime i remap my control minus and plus to x/y. when i switching a game or exiting the homebrew it keeps resetting to default

**Comment by endrift** [comment]
I'm going to need more information, including the config.ini, mGBA version, and which system you're running this on (presumably Switch?)...also there's no X nor Y keys on GBA so you'll need to be clearer as to what you mean.

**Comment by amarantsnipersnake** [comment]
> I'm going to need more information, including the config.ini, mGBA version, and which system you're running this on (presumably Switch?)...also there's no X nor Y keys on GBA so you'll need to be clearer as to what you mean.

sorry, what i mean to say is that i want to remap the ''select'' and ''start'' to ''Y'' and ''X'' buttons and yes im using nintendo switch and im using the latest version 0.10.3. the issue here is that when i remapped the desired buttons and when i restart or exiting the game the remapped buttons keeps resetting to defaults.. and heres is the config found in the mgba folder.

[gui.input.NXP1]
keyDown=15
keyRight=14
keyTake screenshot=-1
keyBack=1
keyCancel=8
keyIncrease solar brightness=-1
keyScreen mode=9
keyFast forward (held)=-1
keyUp=13
keySelect=0
keyLeft=12
keyDecrease solar brightness=-1
keyMute (toggle)=-1
keyFast forward (toggle)=-1

[gba.input.NXP1]
keyRight=14
keyDown=15
keyR=7
keyL=6
keyB=1
keyUp=13
keySelect=11
keyLeft=12
keyA=0
keyStart=10

[ports.switch]
showOSD=0
fastForwardCap=2
screenMode=2
gb.pal[4]=16316664
gb.pal[5]=11053224
gb.pal[7]=0
autoload=0
gb.pal[0]=16316664
frameskip=0
hwaccelVideo=0
gb.pal[10]=5263440
lastDirectory=/Emulator ROMS/GBA/
gb.pal=0
fpsCounter=0
autosave=0
interframeBlending=0
gb.pal[2]=5263440
videoScale=1
sgb.borders=0
sgb.model=DMG
gb.pal[8]=16316664
gb.pal[1]=11053224
useLightSensor=0
filterMode=1
fastForwardMute=0
gb.pal[11]=0
gba.forceGbp=0
lastGame=/Emulator ROMS/GBA/Tales of the World - Narikiri Dungeon 2 (English v2.30).gba
sgb.borderCrop=0
gb.pal[6]=5263440
gb.pal[9]=11053224
mute=0
gb.pal[3]=0
useBios=0

**Comment by JB-W4** [comment]
Looks like this issue also happens on my N3DS. Select and start keeps reverting after remapping them to Y and X respectively.
It happens on the latest dev builds. 0.10.3 seems to be unaffected.

**Comment by endalchemist** [comment]
> Looks like this issue also happens on my N3DS. Select and start keeps reverting after remapping them to Y and X respectively. It happens on the latest dev builds. 0.10.3 seems to be unaffected.

how do you prevent the mGBA menu from opening with "X"? so far i haven't seen any way of rebinding it and i'm also on N3DS

**Comment by endrift** [comment]
It's listed as "cancel" in the remap menu. I need to change the wording.

**Comment by endrift** [comment]
I don't think this is present in 0.10.3. I have however fixed it for 0.11.
