### ISSUE TITLE
How can I provide useful information when the MacOS version crash while emulating games?

### ISSUE THREAD

**Issue by stephane-archer** [mgba-emu/mgba#3282]
I find mgba to be crashing often on MacOS on Intel Mac but I have no idea how I can provide useful information to help you make things better, how can I help you?

**Comment by endrift** [comment]
Generally, a macOS crash includes a big blob of text that has things like a backtrace of all the threads. That's extremely useful information, and stuff I don't get from Windows crashes (much to my dismay). Also, there's a Report Bug option under the File menu that generates a zip file with a bunch of info that you can attach to the bug.

But generally, this isn't the right place to be asking questions like this if there isn't an associated bug. It's better to file a bug and then ask how to provide enough information, or asking on the Discord or forums.
