### ISSUE TITLE
Windows 11 has rounded corners

### ISSUE THREAD

**Issue by Jaizu** [mgba-emu/mgba#3285]
There might be a way to disable rounded borders on the windows release.
Dolphin did it recently, but I have now clue if that means a single thing in terms of the mgba ui.

![image](https://github.com/user-attachments/assets/9067afa4-4863-484c-ac54-be70d8250422)

![image](https://github.com/user-attachments/assets/7fae654f-7ed3-4ca1-91c1-a347234b7a40)

**Comment by endrift** [comment]
This looks easy enough to fix.

**Comment by YoshiRulz** [comment]
The relevant code: https://github.com/dolphin-emu/dolphin/pull/12743
