### ISSUE TITLE
[Vita] Pokemon Fire Red & Leaf Green Crash

### ISSUE THREAD

**Issue by Heratiki** [mgba-emu/mgba#329]
mGBA Nightly 08/07/16 refuses to play either just crashes and dumps a file to ux0/data.  No clue what's causing it either.  They worked fine on your previous releases.  I attempted to attach the tmp dump but git doesn't allow it. (Zipped it and posted anyways)

EDIT: 08/06/16 Nightly also shows the same behavior.  I've also tested Emerald and it crashes as well.  I'll keep testing and adding.

[psp2core-1470618979-0x00001d2cb5-eboot.bin.psp2dmp.zip](https://github.com/mgba-emu/mgba/files/405868/psp2core-1470618979-0x00001d2cb5-eboot.bin.psp2dmp.zip)

**Comment by endrift** [comment]
Should be fixed by b28030c98ced576def581f2f3ead551fc890890b. I'll reopen if it's not.
