### ISSUE TITLE
mGBA glitch.

### ISSUE THREAD

**Issue by HughGamer** [mgba-emu/mgba#3290]
When i run my ROM more than once it occasionally will just fade the screen white and say mGBA is not responding. this is really annoying. also I am on windows 10 laptop with windows 11 on it.

**Comment by endrift** [comment]
You need to give me something to work with. "It hangs sometimes" is not nearly enough information to narrow down what's going on literally at all. Please upload the bug report generated by File > Report Bug and try to give me some information about when this happens.

**Comment by Squall-Leonhart** [comment]
Probably [Nahimic](https://github.com/ocornut/imgui/issues/5354)

**Comment by endrift** [comment]
Can't do anything with no info. I can reopen this if I get anything though.
