### ISSUE TITLE
The brazilian portuguese translation isnt on mgba

### ISSUE THREAD

**Issue by Felipefpl** [mgba-emu/mgba#3291]
There are 2 portuguese files inside mgba and none of them is the brazilian portuguese language file. Both are files with the portuguese translation from portugal. Another problem is that the name itself doesnt say if the translation belongs to portugal or brazil. This should change to avoid confusion and the brazilan file must be added of course. ;)

I downloaded and saw this on latest nightly:
![2024-09-14 09_35_37-Greenshot](https://github.com/user-attachments/assets/223205d0-99f8-4eaf-8a67-649f5458d801)

**Comment by endrift** [comment]
One of them absolutely is pt_BR, which I'm surprised you don't know given _[you contributed to it](https://github.com/mgba-emu/mgba/blob/master/src/platform/qt/ts/mgba-pt_BR.ts)_. It is mislabeled, but I think that's Qt's fault. It's not the only one that's mislabeled, but I'm not sure where the names come _from_ (I just query Qt for the name of the language), so I'm not sure how to fix it.
