### ISSUE TITLE
Boktai failing to load save file

### ISSUE THREAD

**Issue by tchukw25** [mgba-emu/mgba#3304]
After about 12 hours of gameplay, Boktai rom stopped loading the save file. I'm not sure what the issue could be exactly but it looks like it could be similar to #1251. I'm unsure if the same fix has been applied to the libretro port on Android and I can't seem to find the issue anywhere else. Any help would be appreciated.

Retroarch version: 1.19.1
mgba core version: 0.11 -dev 3e349d5

**Comment by endrift** [comment]
Honestly not sure I can do anything with this report. The RetroArch version is extremely out of date (even the PR to update it is 5 months old: https://github.com/libretro/mgba/pull/291), and a report of "my save in this game broke" in a vacuum doesn't do much. It could be a ton of different things, and starting with RetroArch support channels is more likely to yield a result.

**Comment by crashGG** [comment]
> Honestly not sure I can do anything with this report. The RetroArch version is extremely out of date (even the PR to update it is 5 months old: [libretro#291](https://github.com/libretro/mgba/pull/291)), and a report of "my save in this game broke" in a vacuum doesn't do much. It could be a ton of different things, and starting with RetroArch support channels is more likely to yield a result.
Hi, could you port  the forked libretro code to your mainline so that we can build our own version of libretro with mingw?
Or add libretro-win64 build to your build robot so we can keep up with the latest version for testing. Thanks a lot.
