### ISSUE TITLE
MBGA Will no longer open. 

### ISSUE THREAD

**Issue by BloonsTD** [mgba-emu/mgba#3305]
I was able to run MGBA last night, but now it's unable to open. When I try it seems as if the computer is loading, but then nothing happens, and I can't find it in task manager. I tried uninstalling and reinstalling the Windows .exe version but it didn't help, and have reset my computer multiple times. Running as administrator also doesn't make it work.

![2024-10-02 12_33_09-DirectX Diagnostic Tool](https://github.com/user-attachments/assets/8b8cdb05-7b87-4be4-a31c-bee19a3ee02a)
Here are my computer specs for reference. The OS is Windows 10.

Let me know if there's any more information I can give.

**Comment by BloonsTD** [comment]
Note: After posting this I tried VBA to see if it'd work until I get MGBA working. It didn't work satisfactorily, and after trying to launch the ROM one more time, MGBA finally opened. I don't know what the issue was, or why it only started working now. 

I'm not sure whether or not to close the thread since while the issue resolved itself, I don't know what to do if the issue reoccurs in future. I'll leave this up to the devs as to whether or not they want this closed, my apologies for the inconvenience.

**Comment by endrift** [comment]
Generally speaking, this is a bug reporting platform, not a troubleshooting platform. The latter should be done on either the discord or the forums.
