### ISSUE TITLE
Shaders trying to load a shader file not a folder

### ISSUE THREAD

**Issue by ajbeastmod** [mgba-emu/mgba#3308]
[
![Problem 2](https://github.com/user-attachments/assets/6072e4eb-796f-4d1c-ac43-2faf22af6505)
![Problem 1](https://github.com/user-attachments/assets/d9651de8-b333-43b1-9252-4bf26ea75934)
](url)
I cant use any shaders because of this. I've restated and reinstalled mGBA. I have open GL selected for both audio/video and enhancements.

**Comment by endrift** [comment]
See #3268 and #2980. This has already been fixed in dev builds to be less confusing.
