### ISSUE TITLE
[Nintendo Switch] mgba emu crashes

### ISSUE THREAD

**Issue by RetroMarioBros** [mgba-emu/mgba#3309]
It's been a while since I updated the emulator and today I decided to update it to the latest version (Development build) on the Nintendo Switch console. And the result is that it doesn't load any rom, the console simply crashes the app.
[01728064525_01008cf01baac000.log](https://github.com/user-attachments/files/17262219/01728064525_01008cf01baac000.log)

**Comment by endrift** [comment]
To be clear, you mean the latest stable version, 0.10.3?

**Comment by endrift** [comment]
Managed to correlate that log with [8569-c71cd4a](https://github.com/mgba-emu/mgba/commit/c71cd4a81b8ad0d09084d28d56d1ebaadcb7d468) and fixed it.

**Comment by RetroMarioBros** [comment]
Oh! That was quick.
Thank you very much, it's working fine now.
