### ISSUE TITLE
[PSTV Port] This application is not supported on PSTV

### ISSUE THREAD

**Issue by SpooneyH20** [mgba-emu/mgba#331]
Ive installed the .vpk via Henkaku on my PSTV, and when i load into the application i get an error stating that its not PSTV compatible, maybe im doing something wrong? Or is something in the source stopping it from executing on the PSTV. Any help is much appreciated.

**Comment by endrift** [comment]
You need to install the PS TV whitelist. It's pretty easy to find on Google.

**Comment by endrift** [comment]
I've verified that the whitelist is all that's needed. Otherwise, it works fine.
