### ISSUE TITLE
Savestate file blank when using "Save state file..."

### ISSUE THREAD

**Issue by aplerdal** [mgba-emu/mgba#3320]
Using mgba Version: 0.11-8579-67c3c4098

When saving savestates using the "Save state file..." option and the settings under "Save state extra data:" all disabled the resulting save state file is created and set to a certain size, but filled with zeros when viewed in a hex editor. The normal "Save state" and "Load state" options work completely fine. This occurred in Mario Kart Super Circuit. I have not tested it in other games. I have attached the savestate file zipped below. If I am doing something wrong or there is any more information you need let me know.

[mksc.zip](https://github.com/user-attachments/files/17452243/mksc.zip)

**Comment by endrift** [comment]
I can reproduce.

**Comment by endrift** [comment]
What OS are you running? I've found a fix for this on *nix, but I'm not sure it affects Windows.

**Comment by endrift** [comment]
I *think* this should fix it on Windows too

**Comment by aplerdal** [comment]
I am on windows 10, and it works now. Thank you!
