### ISSUE TITLE
Request: restore the rounded window corners of version 10.3

### ISSUE THREAD

**Issue by extherian** [mgba-emu/mgba#3322]
Recent developer builds have changed the appearance of the mGBA program window to have sharp, pointed corners, in contrast to the general Windows 11 aesthetic of having rounded corners on open windows. This gives mGBA a rather non-standard look compared to other programs and emulators that conform to the Windows 11 look. Please consider reverting the window appearance to the rounded corners seen in version 10.3. Thank you for considering this request.

**Comment by CasualPokePlayer** [comment]
Windows 11 giving mGBA rounded corners was opened *as an issue* before: https://github.com/mgba-emu/mgba/issues/3285

The rounded corners on the main window is not exactly great for anyone wanting the entire GBA display, since it's cutting into the emulated screen space.

**Comment by extherian** [comment]
Weird, that issue didn't show up when I did a search for an existing issue.

Anyway, I suppose there's no chance of making this a toggle in the GUI for those that prefer how it looked before?

**Comment by endrift** [comment]
Sorry, though it could conceivably be possible to toggle this, an excess of options for tiny things like this is not really something I want to have.
