### ISSUE TITLE
No way to turn it back to normal speed

### ISSUE THREAD

**Issue by dacompfixor1** [mgba-emu/mgba#3343]
I am playing Pokemon red version game boy game on your mgba emulator. The fast-forward speed is unbounded in the emulation and there is no way to turn it back to normal speed unless I don't know how. I mean turn off the fast-forward speed is what I want to do.
[Archive.zip](https://github.com/user-attachments/files/17788310/Archive.zip)

**Comment by pubct** [comment]
Press again the button that you used to speed up?

I tried the same game with unbounded fast forward, and I was able to speed up & return back to normal speed.

**Comment by endrift** [comment]
There are two kinds of fast forward: held (tab by default) and toggled (shift-tab by default). Presumably you did the latter without realizing it. It also shows up in the emulation menu whether or not it's enabled.

Since this probably isn't a bug, I'm closing it unless shown otherwise.

**Comment by endrift** [comment]
By pressing shift tab again (if you haven't rebound it) or unchecking it in the emulation menu.
