### ISSUE TITLE
opengl not work on linux appimage

### ISSUE THREAD

**Issue by Nassi88** [mgba-emu/mgba#3345]
![Bildschirmfoto_20241117_181012-1](https://github.com/user-attachments/assets/74675c29-65b8-4dfd-8e0e-c346d0366644)
im using manjaro

**Comment by endrift** [comment]
Could have sworn there was already an open bug for this, but I can't find it.

**Comment by endrift** [comment]
This is specifically an issue with EGL on Wayland. It doesn't happen with GLX so for now you can do QT_QPA_PLATFORM="xcb" when starting the program

**Comment by endrift** [comment]
This should be fixed in latest dev, please retest.

**Comment by Nassi88** [comment]
Yes it works. Im wating vor stable Release. Thanks 👍
