### ISSUE TITLE
A strange save issue

### ISSUE THREAD

**Issue by leoxxx** [mgba-emu/mgba#3346]
First, create a Pokemon Emerald hack version FLASH 128K save with VBA 1.7.2. Size = Size on disk = 128 KB (131,072 bytes). Then I save and Overwrite the save in mgba.The save file size has been changed. Size = 128 KB (131,088 bytes) & Size on disk = 132 KB (135,168 bytes). I open the rom with VBA again. It note the save error, but can load it. After loading the save is previous one with VBA 1.7.2. Close it without save the game, open the rom with mgba, has same note, but after loading, the save is mgba's save. It mean the save file have 2 different save. If saving the game with VBA again, the save will be broken. The file will be changed 64K. 
I found mgba open the rom will create a correct size save file, it same as VBA. But after savin the game, the file size will not equal the size on disk, it is different from VBA.
Why?

**Comment by endrift** [comment]
Not an mGBA bug. The extra 16 bytes contain the state of the RTC that VBA does not record.

**Comment by leoxxx** [comment]
> Not an mGBA bug. The extra 16 bytes contain the state of the RTC that VBA does not record.

So if I want to the size equal size on disk, it must be close RTC in mGBA, right?

**Comment by endrift** [comment]
Why do you want it to be equal? Windows will just round up all files to be a multiple of the sector size due to how the filesystem works. This is true regardless of file contents. It really doesn't matter unless you have a ton of tiny files.

**Comment by leoxxx** [comment]
> Why do you want it to be equal? Windows will just round up all files to be a multiple of the sector size due to how the filesystem works. This is true regardless of file contents. It really doesn't matter unless you have a ton of tiny files.

Some save edtior not support it. I have reply in discord general.

**Comment by leoxxx** [comment]
@endrift 
I try the dev bulid can slove it.
BTW, when the new release out?
