### ISSUE TITLE
[Qusetion] How to save the 2P setting?

### ISSUE THREAD

**Issue by leoxxx** [mgba-emu/mgba#3348]
I have known mGBA not support keyboard background input. I have a joypad. But I find all player use the same setting, if I set either of the windows, the others also have been changed to same setting.
So how can I set the key for all players separately?
VBA LINK: a player has his own ini.
NO$GBA:define controls for 12 players.(although GBA just need 4 players)
mgba:???

**Comment by endrift** [comment]
This is not a troubleshooting page, it's a bug reporting page.

You are on the discord, which is appropriate for this.
