### ISSUE TITLE
Qt frontend segfaults during boot after selecting new bios through menu

### ISSUE THREAD

**Issue by snickerbockers** [mgba-emu/mgba#335]
If I select a new bios through File=>Load BIOS and then boot a rom (or just boot the bios), mgba-qt crashes with a segmentation fault.

It does print this right before crashing, so I don't think I'm using a botched bios image.
GBA: BIOS Checksum: 0xBAAE187F
GBA: Official GBA BIOS detected

I've verified this on two different linux boxes.  On one of them it will somehow automatically load the bios file without crashing next time I start a rom, but it will crash again if I do File=>Load BIOS or File=>boot BIOS.  The other computer I've verified this on boots the default mgba bios instead next time I start the emulator (again without crashing).

**Comment by endrift** [comment]
Let me know if  f73bc930809e76f01a13cd9c7850667f73a70f3a fixes this.

**Comment by snickerbockers** [comment]
Yes, that fixed it.

Thank you!
