### ISSUE TITLE
RetroArch Citra core not working with MGBA

### ISSUE THREAD

**Issue by Wave3prime15** [mgba-emu/mgba#3353]
When i run MGBA it gives me a black screen i think or it just boots to the menu and when i select a game it doesent work

**Comment by endrift** [comment]
That's a bug with Citra, not mGBA.

**Comment by Wave3prime15** [comment]
ok

**Comment by Wave3prime15** [comment]
well vicki can you tell the MGBA team to fix the citra error?

**Comment by endrift** [comment]
mGBA is not the one who needs to fix things, it's Citra. If it works on the 3DS, but not Citra, then Citra is at fault.

Also I'm the primary developer of mGBA.

**Comment by Wave3prime15** [comment]
ok
