### ISSUE TITLE
0.11 rumble not working

### ISSUE THREAD

**Issue by Hexaae** [mgba-emu/mgba#3360]
mGBA 0.11-8612-49bddb92e
Today I played again Pokemon Pinball (GBA), WarioWare (GBA) and Drill Dozer (GBA) with Switch Pro Controller (EasySMX x10).
The only one with working rumble is WarioWare.
Game Boy Player features enabled by default.

I also tried Pokemon Pinball (GBC) and rumble is working.

(List of GBA games with rumble support: https://consolemods.org/wiki/GBA:List_of_GBA_Games_with_Rumble_Support )

**Comment by Squall-Leonhart** [comment]
With " Game Boy Player features enabled by default." checked, the Rumble setting ungreys out on the Options screen where it defaults to 'Off'.

Rumble is immediately felt upon switching it to 'On'.

Tested 0.10.3, and nightly.

**Comment by endrift** [comment]
Squall, you're missing the context here: https://github.com/mgba-emu/mgba/issues/3147

**Comment by Squall-Leonhart** [comment]
Is this an initial amplitude problem?, some of those 3rd party controls have an underated motor controller for their minimum rotation to actually move.

This was a problem with the original Xbox controller, once 360 brought compatibilitly to pc the driver always did an initial full strength kick off (iirc, we did similar in X360CE to emulate the behavior?) which would explain the Xbox mode being fine.

**Comment by endrift** [comment]
Actually wait, the title says 0.10.3, but the text says 0.11. We already knew there were issues in 0.10.3, but I at least partially fixed those. Is the title wrong?

**Comment by Hexaae** [comment]
> Actually wait, the title says 0.10.3, but the text says 0.11. We already knew there were issues in 0.10.3, but I at least partially fixed those. Is the title wrong?

Ooops, yes sorry. Correct version is in the first msg.

**Comment by Squall-Leonhart** [comment]
Just to be clear Hexxae, i was talking about the games own options screen, 

Running the game without GB Player being force abled in mgba will force the option back to Off on the next start, 

You said drilldozer was broken in the previous bugs case which uses a small motor, while warioware uses a bigger motor but both are working in this case?

**Comment by endrift** [comment]
The cartridge interface to both Drill Dozer and WarioWare is identical. The size of the physical motor is irrelevant, only how much software keeps it on for. Last time we determined that the Switch mode firmware for the controller itself was buggy and handled frequent updates poorly. I don't know what exactly it did wrong but I was able to reproduce issues with the controller itself with an actual Switch. I attempted to make updates less frequent which fixed it on my end. I am unsure if there was a firmware update in the meantime.

Also, *Hexaae.

**Comment by Squall-Leonhart** [comment]
I moved my testing over to Windows 11, with an Xbox Series control and rumble is indeed not working in the latest nightly.

**Comment by Hexaae** [comment]
In game(s) rumble was enabled of course, checked. 

Tested X10 controller both in BT/XBox and BT/NS with rumble 5/5... But feel no rumble in Drill Dozer or Pokemon pinball. Wario Ware is ok.

Checked also with GameSir Tarantula Pro (T3), same issue...

**Comment by Squall-Leonhart** [comment]
0.10.3
Forced GB Player = Rumble
Default = Rumble

0.11.8523
Forced GB Player = No Rumble
Default = Rumble

**Comment by Hexaae** [comment]
@Squall-Leonhart 
Are you using an original XBox One BT controller?
Have to check with mine...

**Comment by Squall-Leonhart** [comment]
>  Are you using an original XBox One BT controller?

I have one of the Xbox One S/X variants, and several Series variants, using an official receiver because Bluetooth has had some historic problems with the rumble crashing the controller.

PS: mgba doesn't uncheck the GB Player override if you have started a game with "enable gb player features by default", shut it down and then uncheck "enable gb player features by default" - Restart or unchecking it yourself is required - If we're seeing the same thing Drill Dozer rumble _should_ work as long as it is booted without GB Player features.

**Comment by Hexaae** [comment]
Tested with my original XBox One BT (1708) controller and rumble is not working with those games, except Wario Ware as always.

**Comment by endrift** [comment]
Looks like GB Player rumble broke during the SIO revamp. I know I tested it when it was in progress, but it seems I broke it again at some point.

**Comment by Hexaae** [comment]
Yeah! Rumble working great again with all controllers, confirmed (0.11-8614-9388ee55d4)!
Thank you! 👍🏻

**Comment by Hexaae** [comment]
It happened again: today updated MGBA to 0.11.8852-eca3f0f45 and gyro is not working anymore (WarioWare etc.)
