### ISSUE TITLE
The sav file seems weird.

### ISSUE THREAD

**Issue by Chieh-Huang** [mgba-emu/mgba#3363]
I am using mGBA 0.11-8612-a9bddb92e.
The game I’m playing is Pokémon, and the save file should be 128 KB.
Game saves often have an extra 16 bytes, which I find strange.
If I delete the extra 16 bytes and then run the game using VisualBoyAdvance-M, the save file remains 128 KB.
However, if I run the game with mGBA 0.11-8612-a9bddb92e, the save file will once again have an additional 16 bytes.
![16_byte](https://github.com/user-attachments/assets/14d12580-708b-4fc5-988d-3eed6686548b)

**Comment by endrift** [comment]
The extra 16 bytes contain the state of the RTC that VBA doesn't record. Not a bug.
