### ISSUE TITLE
"The encoder bitrate is negative" when recording with H.264

### ISSUE THREAD

**Issue by glu8716** [mgba-emu/mgba#3368]
Whenever I try to record videos with H.264 I get the following error message
`[libx264 @ 0x555675a19380] The encoder bitrate is negative.`
which result in a "Failed to open output video file" message.

I'm on git version (0.11-8614-938ee55d4).
Operating system: Artix Linux

**Comment by Squall-Leonhart** [comment]
This shouldn't happen, in https://github.com/mgba-emu/mgba/blob/f4595f4578cf9943ae787519eb3346837484cb89/src/feature/ffmpeg/ffmpeg-encoder.c#L445 it is already clamped 0 if negative.
