### ISSUE TITLE
Extend watchpoint callback system

### ISSUE THREAD

**Issue by DBM89** [mgba-emu/mgba#3369]
In VBA-RR, when running the following function
local function func(address)
local addr = memory.readbyte(address)
end
memory.registerwrite(0x4000130, func)
Variable addr would contain new written value
In mGBA, below code will fail, since mGBA passes no values
emu:setWatchpoint(func, 0x4000130, C.WATCHPOINT_TYPE.WRITE)
Moreover, when you check memory it doesn't provide new value
BizHawk passes the address that receives an event action as well as the new value.
Please fix the Lua engine so it behaves like VBA-RR or at least pass same values that BizHawk.
I want to know new value, I have no need for old value

**Comment by endrift** [comment]
The callbacks now receive a table as the first argument that contains information:

Breakpoints and watchpoints:
- address
- segment (if available)
- width (if available)

Watchpoints only:
- oldValue
- newValue (if applicable)
- accessType
