### ISSUE TITLE
mGBA crashes upon specific keypresses

### ISSUE THREAD

**Issue by grawlinson** [mgba-emu/mgba#337]
This is for the vita port of mGBA.

Upon startup, at the default root directory (ux0), if triangle or circle are pressed, the entire system freezes and a hard reset of the vita has to be performed.

I think that the port is just trying to traverse to a directory that doesn't exist, so maybe a simple check could be done to avoid this.

**Comment by MoochMcGee** [comment]
What could this MEAN?

**Comment by endrift** [comment]
This bug was fixed ages ago. Please update your build.
