### ISSUE TITLE
Golden Sun crashes and stays crashed

### ISSUE THREAD

**Issue by GamerXYZ2** [mgba-emu/mgba#3378]
Golden Sun suddenly restarts and the save cannot be opened anymore (automatic restart), sometimes even a new game cannot be started (automatic restart as well) without deleting the save. I'm not entirely sure what causes the problem as I'm getting inconsistent results (sometimes I can skip some steps but not others to get the bug to happen, sometimes it's the other way around), so the steps may be redundant and the scene that crashes may just be chance whether it crashes or not (so, it may take several tries to recreate the problem):

1. Start a new game
2. Once you get control of your character, go through the game's settings (no need to change anything)
3. Save the game
4. Talk to the guy (Garet) at his treasure chest (instead of moving on and having him talk with you)
5. Try to go to the north so that Garet stops you from going north
6. Proceed. Past the bridge at the part where the scene starts of the Mt. Aleph falling but being stopped for the moment, the game instead resets
7. You can't load the save anymore, sometimes you can't even start a new game anymore though usually you still can. The save still works on other emulators though, just not on mGBA.

mGBA version: 0.10.4
OS: WIndows 10 64-bit

**Comment by endrift** [comment]
Do you have auto loading states turned on? Try turning that off and seeing if it works then. There's a known bug in 0.10.4 that affects save states in Golden Sun that has since been fixed in development builds. It's bad enough that I intend to release 0.10.5 just to fix it and a few other minor bugs.

**Comment by GamerXYZ2** [comment]
Going by that information, it seems savestates are indeed the problem. Without loading a savestate and with the option you mentioned turned off I can't reproduce the problem anymore, but as soon as I make and load a savestate the game immediately again crashes at the point I described (and also at all points with a small boulder falling down to block the path).

**Comment by endrift** [comment]
Yup, thankfully that problem was fixed a few days ago. It also doesn't affect 0.10.3, so you can use that or a dev build in the meantime.
