### ISSUE TITLE
[Vita] Megaman Battle Network Series has Severe Slowdown

### ISSUE THREAD

**Issue by OTFree** [mgba-emu/mgba#338]
Of the 6 core titles in the series, "Megaman Battle Network (1)" definitely runs the best based on my testing (using the latest nightly), but in areas w/ many sprites or objects, begins to have considerable (and noticeable) lag. This is also the case with Net areas and battles in general.

The other entries have far worse lag, the worst of which seemed to be "Megaman Battle Network 3" ("Blue" and "White" respectively), to the point where it's nearly unplayable.

Just wanted to give you feedback since I hadn't seen anyone else mention it. Keep up the great work! (:

**Comment by OTFree** [comment]
[EDIT: Forgot to mention, I tried using proper BIOs and without.]

**Comment by endrift** [comment]
The Vita's just slow. But I can try adding some idle loop overrides.

**Comment by OTFree** [comment]
Yeah, if I'm recalling correctly, the N3DS nightly recently had a second
core implemented for speed up. Is such a thing possible for Vita yet, or
something in the foreseeable future?

**Comment by endrift** [comment]
That was already done on the Vita.

**Comment by OTFree** [comment]
Ahhh, alright. Strange, I remember the post mentioning that the N3DS port
is currently running better and I'm curious as to why that is.

But yeah, I'd be more than willing to test your theory on how to improve it
and I'd let you know how it goes :)

On Aug 11, 2016 9:58 PM, "endrift" <notifications@github.com> wrote:

That was already done on the Vita.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mgba-emu/mgba/issues/338#issuecomment-239343845>, or mute
the thread

**Comment by BetaLeaf** [comment]
This is still an issue on the 3ds.

**Comment by BetaLeaf** [comment]
Was this fixed?

**Comment by endrift** [comment]
"This game runs slowly on underpowered hardware" isn't a bug. I try to get things faster, but that's not always possible.
