### ISSUE TITLE
Win64 - Updater unable to complete due to shader files

### ISSUE THREAD

**Issue by Conza89** [mgba-emu/mgba#3384]
The built in updater seems to have issues with replacing the .shader extension files and doesn't complete.

Steps to reproduce
1. Download Windows 64bit portable (0.10.4), extract to a location
2. Tools > Settings > Update. Switch "Update Channel" to "Development", hit apply
3. Hit "Check Now", follow the prompts to trigger the updater and observe the results.

Expected results
Updater downloads, mGBA closes down, starts up again and the program is updated successfully to the latest development build.

Actual results
Updater downloads, mGBA closes down, mGBA does not start up again and the updater.log file stops at "extract /shaders/agb001.shader" followed by an error occurred.

Workaround 1
In the \shader folder, compress all .shader files (or folders) to back them up, then retry the updater. Updater should complete as expected.

**Comment by endrift** [comment]
I swear this was fixed in 0.10.3. I'm not sure how it could have regressed.
