### ISSUE TITLE
Win64 - Update channel preference doesn't save between sessions

### ISSUE THREAD

**Issue by Conza89** [mgba-emu/mgba#3385]
The Update channel doesn't retain user preference between either Development or Stable between sessions.

Steps to reproduce 
1. Download the Win64 version of mGBA (either 0.10.4 or latest development build at time of reporting)
2. Go to Tools > Settings > Update. Change "Update channel" to the alternative option, either from Development to Stable or Stable to Development depending on the version.
3. Hit Apply, Ok, then File > Exit or close application
4. Relaunch application, go back to Tools > Settings > Update and observe the "Update channel" value

Expected results
Update channel retains user selection after closing and reopening

Actual results
Update channel reverts to original value, either Development on Development builds, or Stable on Stable builds.

Reported builds:
Stable: 0.10.4
Development: r8639-08430fc05

Notes
1. Is consistent behaviour between 0.10.4 and this build, presumably all builds in between.
2. This may be an intentional design choice, in which case this can be resolved, but I am uncertain if the choice selection should be discarded with the session and defaulted to the current branch type, or saved 'as expected' above.
3. There may be other Settings values that are not saving in between sessions, but this does not appear to be the case in light testing.

**Comment by endrift** [comment]
This was an intentional choice, as there is no use case for this. If you switch the channel and then don't download it, why should it save? You haven't actually switched channels.
