### ISSUE TITLE
[3DS Family] Save states not loading, the game freezes

### ISSUE THREAD

**Issue by ViWalls** [mgba-emu/mgba#3388]
Hi,

I'm using latest 0.10.4 in a New 2DSXL with CFW.

I can make a save state but when I load one, the game freezes and some tiles are messed up or dissapear, as you can see in the screenshot provided. There is also a save state file attached as proof, for this purpose I'm using a good dump "Wario Land - Super Mario Land 3 (World)" but I have tried other games and this issue still happens. This worked fine in the previous release.

I tried manual install and through Universal Updater, both give the same issue. Other emulators can use this feature, so it doesn't look like an issue with access to my SD card.

![Wario Land - Super Mario Land 3 (World)-0](https://github.com/user-attachments/assets/af651edf-8a0d-4cfc-a24a-829c1c31fd85)
[Wario Land - Super Mario Land 3 (World).zip](https://github.com/user-attachments/files/18267826/Wario.Land.-.Super.Mario.Land.3.World.zip)

**Comment by endrift** [comment]
I can't get this save to load properly on _any_ version of mGBA--0.10.0, .1, .2, or .3. What version did you make this save in? Which other games are having problems?

**Comment by ViWalls** [comment]
As I mentioned in the issue I'm using latest 0.10.4 in a New 2DSXL with CFW, not PC. I also tried manually installing from repo and through Universal Updater. In both cases save states are having the same behavior.

Previously in 0.10.3 save states were loading, that's for sure. I have tried different roms, same issue. I'm sure there are good dumps and stuff because I play a lot of hacks and it's mandatory use as base the proper checksum and related stuff.

What I haven't tried it's on PC, mostly because I play GB/GBC games and use bgb, not GBA games at all. It's possible that this issue can be related with 3DS and not other systems, but I'm sure something is wrong.

If you need more detailed info or check something specific feel free to ask, I'm happy to help because I'm using this emulator for this handheld and it's a great experience overall (specially when you play tons of roms and hacks, but you want to avoid Virtual Injection and 2957264027 icons in menu).

Happy new year ;)

**Comment by endrift** [comment]
Ah I misunderstood, I thought you meant that you made the state in 0.10.3 but it didn't load upon updating to 0.10.4. Let me start taking a look into this.
