### ISSUE TITLE
[Feature Request] Remapping the Scaling button in config (Vita)

### ISSUE THREAD

**Issue by OTFree** [mgba-emu/mgba#339]
I imagine this will likely be implemented in a stable release, but it would be really nice if we could map the scaling feature to a button other than square, since I saw other users as well requesting this on the r/vitahacks subreddit.

I know that scaling can also be accessed on it's own, but when I try to assign the 'a' button to square for example, the screen stretches with every press. 

Again, I'm sure this is known, it's just something I wanted to highlight since I knew a few others who'd appreciate this as well :D

**Comment by endrift** [comment]
I've been planning to make it (and most of the UI buttons) remap-able for a while now, but I haven't had the time to get to it yet.

**Comment by endrift** [comment]
Fixed in c191ec88b83d9a989586d5590f5443031d82c68c.
