### ISSUE TITLE
[Request] [Wii port] 240p Support

### ISSUE THREAD

**Issue by Dockolm** [mgba-emu/mgba#343]
I'm playing on my old CRT with SCART RGB cable it looks really nice ! However mgba outputs 480i right? It would be cool to add an option for 240p output for more 2D retro consoles feeling, so CRT produces more scanlines.
In addition, if I'm right, Pixel accurate render is bigger and more comfortable in 240p.

**Comment by endrift** [comment]
I'd implement this if I had a capture device that supported 240p, so I could check if it works. But as it stands, I don't.

**Comment by GB-CG** [comment]
@Dockolm This was already discussed in #136

**Comment by Dockolm** [comment]
@GB-CG Yeah it's a cool idea.

@endrift Do you have any idea if it would have big impacts on the code? Maybe I'll give it a try myself if it's not that hard and if I have some free time. I'm gonna check how other Wii homebrews implement this.

**Comment by endrift** [comment]
I'm not sure how I'd recommend implementing it, to be honest. Maybe another screen mode? I'm not very familiar with how it's done in other homebrews. It shouldn't be too intrusive though, seeing as only src/platform/wii/main.c will need to change.

**Comment by GB-CG** [comment]
@endrift The Micomsoft sc-512n1-l/dvi & the external X-Capture 1 can do true 240p capture, but they're crazy expensive.
There is a PDF courtesy HD Retrovision of capture cards that support 240p, but it's an incomplete list atm. http://www.hdretrovision.com/s/240p-Cap_Cards_20141227.pdf

**Comment by endrift** [comment]
Oh! I actually have an HD PVR 2 Gaming Edition, I'll see if I can get that working if my new TV doesn't support it over component.

**Comment by endrift** [comment]
Turns out my new TV _does_ support 240p. Added in d9964ee727f7eebf2da0a97b0c0f2ddd9c7c73c4, but be careful, you'll need to edit your config file directly if you set it to something your TV doesn't support. I'll add the "if you can see this, press A to continue" thing at some point too.

**Comment by GB-CG** [comment]
Well, it works on my end but the game display is narrow.
![- screen shot 21 08 2016 16 30](https://cloud.githubusercontent.com/assets/11931125/17838134/1796ccfa-67bd-11e6-8352-b0dcff5553e7.png)  
Choosing 'Stretched' mode can correct the ratio, but I'm not a fan of stretched pixels.

**Comment by endrift** [comment]
I had troubles getting the aspect ratio looking right. I'll see if I can fix that.

**Comment by endrift** [comment]
Looks like there was a copy/paste error when I committed it. Can you try again with the latest nightly?

**Comment by GB-CG** [comment]
Will do. BTW, did you by chance input the aspect ratio the wrong way round before?

**Comment by nateify** [comment]
My Wii is set to 4:3 ratio, and the latest nightly is the correct aspect ratio on my CRT when set to 240p, unstretched, unfiltered.

**Comment by GB-CG** [comment]
So I tried 0.5-3807: Much better. :)
![mgba_240](https://cloud.githubusercontent.com/assets/11931125/17893040/0ef3683a-693c-11e6-9c90-4dbd1710af84.png)

However, GB games still look a bit squished on 4:3.
![4-3 gb](https://cloud.githubusercontent.com/assets/11931125/17893105/4f817d4c-693c-11e6-8599-2c1a35b7ee6b.png)
