### ISSUE TITLE
[VITA] [Feature Request] Remap menu options and framerate limiter or Vsync.

### ISSUE THREAD

**Issue by ma16v3** [mgba-emu/mgba#345]
We can remap the controls for gameplay, but we cannot remap controls for the menu. I play Megaman Zero games with the main attack button mapped to Square, but this also changes the screen mode. So every time I use an attack, the screen size changes. I have mapped back to default for now.

While the Megaman Zero games aren't completely full-speed(this will be addressed as time goes on, so not a request here), there are parts that go faster than full-speed, which tells me we need a framerate limit option as well.

**Comment by endrift** [comment]
Please don't bundle two things into one request.

Remapping controls is covered by #339

The second is a bug. There is a frame limiter, it might just be acting up.

**Comment by ma16v3** [comment]
I apologize. Thanks for your quick response.

**Comment by endrift** [comment]
Please retest this. Remapping was added, but the frame limiter bug I'm not sure I was able to reproduce in the first place.
