### ISSUE TITLE
Touch screen map to a button

### ISSUE THREAD

**Issue by Zeroba** [mgba-emu/mgba#346]
It's a small feature that maybe only I'll want, but I find when advancing through dialogue, that I have the urge to tap the screen.
It'd be neat if we could bind either part of the screen or just the entire screen to multiple or a single buttons.
Though for now, I'm sure you're quite focused on other things, such as hotkey remapping for the emu. I'd hope, hehe. I want my precious square button back.

**Comment by endrift** [comment]
This would be...rather difficult. Also, UI remapping landed last night.

**Comment by Zeroba** [comment]
That's alright, like I said I had no idea how difficult it'd be to do. It's not exactly demanded, so don't worry hehe.
