### ISSUE TITLE
[Vita] Pokemon Leaf Green runs Slower with Latest Nightly

### ISSUE THREAD

**Issue by OTFree** [mgba-emu/mgba#347]
Not sure what it is, but it seems the game now overall dips at a lower framerate than previous revisions.

**Comment by ongamex** [comment]
Probably the same issue with those games:

Metroid : Fusion and Zero Mission
Mario Cart Super circuit

**Comment by endrift** [comment]
These reports are useless without telling me exactly which versions were performing how (including numbers).
