### ISSUE TITLE
Vita and save files/states

### ISSUE THREAD

**Issue by Zeroba** [mgba-emu/mgba#349]
Are save files and states stored as files, or within another file?  I was going to transfer a .sav to mGBA, but couldn't find a save directory.

**Comment by endrift** [comment]
The issue tracker is not a support forum; there is one of those on forums.mgba.io.

Anyway, there isn't a save directory. The .sav files are in the same folder as the ROM. Savestates are stored the same way, but as .ss1 through .ss9 instead of .sav.
