### ISSUE TITLE
Cannot map "W" key.

### ISSUE THREAD

**Issue by Kered13** [mgba-emu/mgba#351]
The W key appears to be permanently mapped to the "A" button. Changing it in the settings menu does nothing.

I'm using Windows 7 64 bit. I've tested this on both the 0.4.1 and the 0.5-3778-63ed9bf dev build. I tried it in both Pokemon Emerald and Pokemon FireRed.

**Comment by endrift** [comment]
It's under shortcuts > autofire > a

**Comment by Kered13** [comment]
I see, thank you.

That fixed my problem. I'd say though that being able to map one key to multiple commands is bad UI. I'd suggest unmapping the other command, or if there is a good usecase for having two commands on one key then at least present a warning that the key is already mapped. It was not obvious that a setting buried in another menu was conflicting with the keyboard settings screen.

**Comment by endrift** [comment]
Autofire is not the same as regular pressing it--it's rapidly pressing and unpressing it, unless that broke at some point.

It should probably be unmapped by default just to avoid confusion like this.

**Comment by endrift** [comment]
I've unmapped the key by default, but the whole thing needing an overhaul is a known issue that I keep putting off.
