### ISSUE TITLE
[PSP2]Up/down file selection accuracy

### ISSUE THREAD

**Issue by DrLuthor** [mgba-emu/mgba#353]
On last nightly ( affe5e3 ), the file selection is not accurate anymore. When I go down once with the cross, the selection always go way down. Same issue with up.

By the way great job with your last updates. Framerate is perfect and sound though not perfect is WAY better.

**Comment by endrift** [comment]
I must have accidentally disabled framelimiting on the menu.

**Comment by DrLuthor** [comment]
That seems to be a good hypothesis

**Comment by endrift** [comment]
I think this was actually me forgetting to update vita2dlib on my server. Try tomorrow's nightly when it comes out.

**Comment by DrLuthor** [comment]
PERFECT!
Thanks
