### ISSUE TITLE
[Linux/QT] getOpenFileName filter is not case insensitive

### ISSUE THREAD

**Issue by grawlinson** [mgba-emu/mgba#355]
Build/OS:
Using the following pacman packages on Arch Linux -
* libmgba 0-.4.1-1
* mgba-qt 0-.4.1-1

I have a couple of files with the .GBA extension as opposed to the normal .gba extension. Using the Load ROM dialog only shows .gba extensions in the window.

I don't have much experience with QT, but I think there may be a CaseInsensitive boolean for QStrings. You could probably put another filter parameter in this [code](https://github.com/mgba-emu/mgba/blob/57c127589067d0b6e94083043134c2e5ac732449/src/platform/qt/Window.cpp#L327) or the code surrounding that line.

EDIT: I am using XFCE4 as my DE.

**Comment by endrift** [comment]
This actually look like a Qt bug. Reading up, I THINK the filters are supposed to be case-insensitive by default. But I'll need to take a closer look.

**Comment by waddlesplash** [comment]
Possibly https://bugreports.qt.io/browse/QTBUG-51712 ?

**Comment by grawlinson** [comment]
Output of `pacman -Q | grep qt`

```shell
$ pacman -Q | grep qt
mgba-qt 0.4.1-1
phonon-qt4-gstreamer 4.9.0-1
pyqt5-common 5.7-2
python2-pyqt5 5.7-2
qt4 4.8.7-9
qt5-base 5.7.0-2
qt5-declarative 5.7.0-2
qt5-location 5.7.0-1
qt5-multimedia 5.7.0-1
qt5-sensors 5.7.0-1
qt5-svg 5.7.0-1
qt5-webchannel 5.7.0-1
qt5-webkit 5.7.0-1
qt5-xmlpatterns 5.7.0-1
qtchooser 53-2
qtkeychain 0.7.0-1
```

**Comment by grawlinson** [comment]
Issue doesn't exist when using sway. Seems to be specific to XFCE4/GTK.

**Comment by endrift** [comment]
Probably a Qt bug then. Sorry :/
