### ISSUE TITLE
Rewind improvements

### ISSUE THREAD

**Issue by endrift** [mgba-emu/mgba#36]
Rewinding could use several improvements for the next release:

- [x] Diffing + compressing rewind system for low memory/long duration rewinding
- [x] Increase rewind interval cap
- [x] Better defaults
- [x] Better configuration

And maybe some other things that I'm forgetting. Feel free to add on ideas in this issue if you have any.

**Comment by tony971** [comment]
A couple more Qt issues to fix with held rewind: It should be disabled when a dropdown menu is opened. This prevents it from getting stuck if the settings menu is opened while holding it (fast forward already does this). Also, the menu bar is shown in full screen while using it.

**Comment by tony971** [comment]
I was also thinking more about the ability to customize time between steps when rewinding. The easiest terms to understand would be play speed. Similar to how fast forward can select between 2x, 3x, 4x, ... , rewind could work in a similar fashion. Say that someone wanted to rewind at 1x playing speed. This could simply be derived by taking 1000ms / [ 60fps / (frames between intervals) ]. To rewind at 1/2 speed, double this number. To rewind at 2x speed, half this number. And by making the rewind speeds select-able rather than fill in the blank, they could be added to the Emulation tab as well.

**Comment by endrift** [comment]
Very unlikely this is going to happen in 0.3.0 now.

**Comment by tony971** [comment]
Trying to explain things better than I had before, customizable rewind speed is easiest to understand as a ratio of playing speed. Granted, time between interval jumps is more directly saying what you're customizing. However, this obfuscation is more meaningful than the raw data (e.g. displaying estimated mile range vs remaining gallons of gasoline). The conversion is going to roughly happen in users' heads, anyway. Why not make it easy for them? Here's what I propose: Similar to capped fast forward, the user can select between pre-defined "rewind speeds." Each speed selects a different time between interval jumps. Here's the formula for determining this value:

[ 1000ms * (frames between intervals) ] / [ (desired FPS) * (desired rewind speed) ]

So let's say that someone plays at 60fps and records a rewind interval every 6 frames. They want to rewind at 2x playing speed. Their time between rewinding intervals would be this:

(1000 * 6) / (60 * 2) = 50ms between interval jumps.

If they wanted to change it to 1/3 playback speed, it would become this:

(1000 * 6) / (60 * (1/3)) = 300ms between interval jumps.

Throw in some rounding protection for non-integers and this formula can be extrapolated for any combination of desired fps, time between intervals, and desired rewind speeds.

**Comment by tony971** [comment]
One reason to implement it like this is to eventually parallel the fast forward feature set. In my mind, after selecting how often to create a rewind state and how long to keep a history, rewind should act identically to fast forward. You select your rewind / fast forward speeds in relation to play speed. The held versions will rewind/fast forward as long as the button is held. The non-held versions will do the same thing except triggered on and off by a button toggle. (I believe that the "one giant jump" feature only clutters the UI and confuses the user. Single jumps should work similar to a frame by frame.) Making rewind as similar to fast forward as possible will definitely help with usability and cleanliness of the UI.

**Comment by endrift** [comment]
I fixed the menu bar issue.

**Comment by tony971** [comment]
Thanks, I updated my comments to reflect the current state.

**Comment by endrift** [comment]
Most of this should land tonight.
