### ISSUE TITLE
Sonic Advance 2 - minor sprite flicker

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#361]
The character select screen shows some noticeable flicker, as well as the time attack try again screen.
It started happening since https://github.com/mgba-emu/mgba/commit/5e50a635cf1ba6a02d9591fc623dc68aa8b82fa9 it appears to be more noticeable on that actual commit than the current 25th nightly but is still present. Bios made no difference.

**Comment by endrift** [comment]
I'm not seeing it on the character select screen, but I did see some on the time attack retry screen.

**Comment by endrift** [comment]
I'm seeing flickering even before that change.

**Comment by SuperrSonic** [comment]
Platform should not matter? I used August 18 Wii nightly, I can't get it to show no matter what.

**Comment by MoochMcGee** [comment]
@SuperrSonic As far as I can tell, that commit is mostly, if not all, a commit that doesn't change behavior. So it doesn't make much sense for the flickering to have started there.

**Comment by endrift** [comment]
Please let me know if this still reproduces in the next nightly--after fa92b4cd0e461ede2a70077c8acf87078a931d05.

**Comment by SuperrSonic** [comment]
Still happening.

**Comment by endrift** [comment]
Is this still happening as of the most recent nightly?

**Comment by SuperrSonic** [comment]
Yes.

**Comment by sergiobenrocha2** [comment]
I can reproduce it with 0.5.2+, but not with master

**Comment by JMC47** [comment]
In the latest development build I can see stuff flickering just starting the first stage.  Windows 10, standalone mGBA.

**Comment by SuperrSonic** [comment]
Yes, tested for a few hours now, it's fixed.
