### ISSUE TITLE
"Oh!" has an odd rectangle-sized glitch on some screens.

### ISSUE THREAD

**Issue by waddlesplash** [mgba-emu/mgba#364]
Previously it didn't boot, but that was fixed (#250). Now it just has an odd glitch, which first appears on the "twisting ropes" screen but appears after that too:

![oh_glitch](https://cloud.githubusercontent.com/assets/2175324/18035112/b3502d62-6d1c-11e6-88ef-6f11bf30bd16.gif)

This is mGBA 0083fad.

**Comment by endrift** [comment]
I believe this is known to reproduce on GBC too, so I wonder what the difference is.

**Comment by waddlesplash** [comment]
So it does not occur on GB, but does on GBC? Odd.

**Comment by endrift** [comment]
https://youtu.be/dfDXXSCB2Ro?t=34 it's not quite the same glitch, but you'll notice it is still the same scanlines.

**Comment by endrift** [comment]
This is caused by some combination of IRQ timing and PPU timings.

**Comment by endrift** [comment]
This seems to have gotten fixed at some point, but wasn't able to be verified due to #250
