### ISSUE TITLE
[Vita] Crash when going up a dir

### ISSUE THREAD

**Issue by Zeroba** [mgba-emu/mgba#367]
It seems on the latest nightly, mGBA quits to the livearea whenever I attempt to go up a directory from ux0:Data to the root of UX0, where all my roms are in a different folder lol

**Comment by endrift** [comment]
Not a bug. I had to do this to make mGBA a safe mode app. You'll have to move your ROMs, and you may need to re-upload them to your Vita, due to weirdness with safe mode apps.
