### ISSUE TITLE
Cannot manually pause emulation while having the "Pause while inactive" setting on and using it at least once.

### ISSUE THREAD

**Issue by f-unk** [mgba-emu/mgba#368]
To reproduce (for me):

1. Go to Tools > Settings... > Emulation > Check "Pause while inactive"
2. Start a ROM and click outside mGBA to make the window inactive which will auto pause the emulation.
3. Make the window active again causing the emulation to automatically start again.
4. Press Ctrl-P or go to Emulation > Pause.

Expected results: Emulation pauses.

Actual results: Emulation seems to pause for a frame then resumes automatically making it impossible to pause the emulation until the emulator is restarted. The "Pause while inactive" setting does continue to work though.

Version Used: 0.4.1
OS: Windows
Game Tested: Metroid Fusion

**Comment by endrift** [comment]
Fixed in 246efef6b960d51a6a0917d824558569cf2e6873. Thanks for reporting.
