### ISSUE TITLE
Intermittent hang? crash? or MSVC "unusual termination" box, usually with GB[C] games

### ISSUE THREAD

**Issue by waddlesplash** [mgba-emu/mgba#369]
I've noticed this now and again while using mGBA, usually right after starting games or switching them. The only thing I've found that I've been able to do to trigger it more than once (about 1 time every 10-12) is:

 * Open http://www.pouet.net/prod.php?which=63084 but don't start the actual demo, just the title screen, and hold Fast-Forward for a second or two
 * Open http://www.pouet.net/prod.php?which=7175 and fast-forward immediately. If it crashes, it'll crash before or just after the title screen check finishes, usually.
 * If it didn't crash, you can re-open the first demo (Second Reality), and the emulator may or mat not hardlock. If it doesn't, close and restart it and try your luck again.

Sometimes it crashes in a "mGBA has stopped working", sometimes in a MSVC "unusual termination". I don't have a good way to get a stacktrace without a gigantic .dmp (this is Windows 10), although @endrift if you're unable to reproduce at all, I'll see what I can do. (I tried attaching to running mGBA in Qt Creator and got nothing useful out of the stacktraces.)

**Comment by waddlesplash** [comment]
Update: I was cycling around again, and this time it hardlocked before the Open File dialog opened after I pressed the menu item (third bullet point.)

**Comment by waddlesplash** [comment]
Update 2: Holding Fast-Forward for longer while on demo in first bullet point and then trying to open another ROM resulted in another hardlock.

**Comment by waddlesplash** [comment]
Update 3: Besides the MSVC "unusual termination" box, I'm uncertain there's actually a crash at all. It seems that the times I instantly got a Windows crash box, it really was an ANR.

**Comment by waddlesplash** [comment]
## Update 4: I found a way to hardlock 100% of the time.

Open Demotronic first, once it says "OH BOY!", try to start Second Reality. Instant hardlock.

**Comment by endrift** [comment]
Yeah, fast forward is a bit buggy right now. I think it causes memory corruption somehow. I'm going to try running it in valgrind.

**Comment by endrift** [comment]
This might be fixed by c06edae71d8a236124f3068700db1204b8473af1, let me know.

**Comment by waddlesplash** [comment]
Can't reproduce, probably fixed.
