### ISSUE TITLE
Solar sensor doesn't work for Boktai 1 & 2.

### ISSUE THREAD

**Issue by CarterLi** [mgba-emu/mgba#37]
It used to work, but doesn't work now.
Tested version: 0.3-2110-bbac206 on OSX 10.10.3
Tested roms:
```
1161 - Boktai - The Sun Is in Your Hand (U), MD5: FF75C62AB690410CC8FCA24204D783E9
1719 - Boktai 2 - Solar Boy Django (U), MD5: 31231965D6A43D935E3629A67E06E0BB
```

PS: It works for 2069 - Shin Bokura no Taiyou Gyakushuu no Sabata (J)

**Comment by endrift** [comment]
Boktai (same MD5) seems to work for me, same OS. Did you try recalibrating to darkest level when in the options? I haven't tried Boktai 2 yet.

**Comment by CarterLi** [comment]
Weird. If I start the game with my battery save, the solar sensor doesn't work.

![1161 - boktai - the sun is in your hand u sav](https://cloud.githubusercontent.com/assets/6134068/8022941/4e6e17e6-0d24-11e5-9cfa-6667430b7c31.png)

Have no idea what's happening...

**Comment by endrift** [comment]
Recalibrating the solar sensor (setting it to lowest, going into options, selecting "calibrate") seems to fix it on my end.

**Comment by CarterLi** [comment]
Tested, it works fine.
Thanks.
