### ISSUE TITLE
[Vita] No 0.4.1 VPK

### ISSUE THREAD

**Issue by Catarax** [mgba-emu/mgba#370]
The 0.4.1 is only available in VELF, I can't install it through VitaShell. 
Only the Nightly Build can be installed in my case and apparently, this version has some slowdown.
I want to check the difference.

Is it possible to get a link of this version in this format?

Thanks!

**Comment by endrift** [comment]
Not a bug. 0.4.1 was released before HENkaku, and would have severe issues trying to run on HENkaku. Plus, it's much slower than the nightlies. The Vita is just freaking slow, at only 444MHz.
