### ISSUE TITLE
[PSP2] Can't go to uxO

### ISSUE THREAD

**Issue by DrLuthor** [mgba-emu/mgba#371]
Hi,

Now the file browser always starts in ux0:data
The (Up) option returns to live area instead of showing me ux0's content.
Is this the new behavior? I haven't see any note on this.

If we need to store the roms in ux0:data it's fine. But what if we want to upgrade to a new version of mgba and have to delete the previous version? Will the files in ux0:data/mgba remain?

**Comment by endrift** [comment]
This was required to make mGBA a safe mode app. You'll need to move the ux0:/mGBA folder into ux0:/data/mGBA to copy your settings over, and if you have trouble seeing your ROMs or any other files, install and run this program: https://github.com/endrift/vita-fix-permissions/releases
