### ISSUE TITLE
Advance Wars 2, crash on shutdown/setting OpenGL

### ISSUE THREAD

**Issue by Timecrash** [mgba-emu/mgba#375]
mGBA a20061e925f00eb6bcfd1387a498d0db51bd6f23, Windows 10 64-bit, Core i7-4790K and Nvidia GTX 970. Display driver set to OpenGL, **not** forced 1.x OpenGL. I'm also using a GBA BIOS file.

Starting up Advance Wars 2, then selecting Emulation -> Shutdown will cause the emulator to crash.

Also, setting the emulator to forced 1.x OpenGL, starting up AW2, then selecting Emulation -> Shutdown, then putting the emulator back onto regular OpenGL causes the emulator to crash. I also get a crash re-enabling the BIOS file after disabling it then running/shutting down AW2.

Yeah, weird issues.

**Comment by endrift** [comment]
These were fixed by d7f09a330b43d999c85e73e7be54090fd4a2c5be.
