### ISSUE TITLE
Rayman 3 Hoodlum Havoc - Misalignment on some scaled/rotated surfaces

### ISSUE THREAD

**Issue by GranvilleR** [mgba-emu/mgba#377]
In the GBA version of Rayman 3 Hoodlum Havoc, there are four levels that use the GBA's rotation and scaling effects on a background layer. It produces that classic fake flat "3D" look many racers and RPG's of the 16 bit era had (particularly mode7 on SNES).

On mGBA, the floor surfaces in these levels are visually misaligned with the actual track layout. You'll constantly hit invisible obstacles and fly off the track because the graphics don't match the collision. Jumping also causes the floor to jerk and shift violently.

I'll attach several savestates taken at the entrances to the affected levels (press up on the dpad to enter the levels). They're taken from the US version of the game. And here are examples of what the levels are supposed to look like without the glitch-

https://www.youtube.com/watch?v=8SVsl0gjaqc
https://www.youtube.com/watch?v=I_dUSXbUO4o

[Rayman 3 Savestates.zip](https://github.com/mgba-emu/mgba/files/466904/Rayman.3.Savestates.zip)

Incidentally, I haven't tested Rayman Raving Rabbids on mGBA yet but the game shares a lot in common with Rayman 3 GBA (same visuals and gameplay, I suspect the same engine, it's basically Rayman 3 GBA's sequel). It also shares the same kind of "mode7" levels and I wonder if they are also broken..

In case this info is necessary, this issue is present on both the 0.4.1 stable built as well as the 0.5-3929-d8c773b Nightly, both downloaded off the official mGBA site. The glitch is present across all devices i've tested on. My PC has Windows 10 64 bit, an Intel Core i5 4670k and an EVGA 1060. The newest mGBA core running via Retroarch Android also exhibits the same issue.

**Comment by endrift** [comment]
Confirmed on master. The game calculates the position of the scanlines itself, so something must be being emulated wrong inside the game, not just the graphics.

**Comment by endrift** [comment]
Can you please provide a savegame in addition to the savestates?

**Comment by GranvilleR** [comment]
Sure thing.
[Rayman 3 - Hoodlum Havoc savegame.zip](https://github.com/mgba-emu/mgba/files/467401/Rayman.3.-.Hoodlum.Havoc.savegame.zip)

Thanks for your hard work.

**Comment by endrift** [comment]
This doesn't seem to be a BIOS bug, as it affects HLE and LLE BIOS.

**Comment by endrift** [comment]
oh my god

this game *changes the video mode mid-frame*

I did NOT know you could do that.
