### ISSUE TITLE
Palette customization

### ISSUE THREAD

**Issue by sergiobenrocha2** [mgba-emu/mgba#379]
Hey, please  add palette customization to gb :D 

And add option settings in the libretro port as well please.

**Comment by endrift** [comment]
Work on this started in ba65740b159a2ce3bceecf1088f859f326d69b34. Still needs to be exposed via config UI.

**Comment by endrift** [comment]
UI is exposed via a per-game setting. Global config is config file only for the time being.

**Comment by endrift** [comment]
This has since been exposed globally.
