### ISSUE TITLE
Rumble still broken on Windows

### ISSUE THREAD

**Issue by autofire372** [mgba-emu/mgba#381]
I just tried the latest nightly, and rumble on Windows is still nonfunctional. I tried it with two separate Xinput controllers (the Razer Sabertooth Elite and a first-party wired Xbox One controller) and neither one rumbled. Both still rumble on Linux.

**Comment by endrift** [comment]
Works fine on my end. What game are you trying?

**Comment by autofire372** [comment]
Pokémon Pinball.

**Comment by endrift** [comment]
You need to turn on GBP features for Pokémon Pinball to rumble. It's just generally buggy. Make sure that it's listed as having rumble enabled when you go to options. Drill Dozer is a much better game to test with.

**Comment by autofire372** [comment]
Where do I enable that?

**Comment by endrift** [comment]
In the Overrides pane before loading a game.

**Comment by autofire372** [comment]
Thanks, I'll give it a shot.

**Comment by endrift** [comment]
Save just writes the override to disk, it doesn't actually close the window. Close, though, hm, let me look.

**Comment by autofire372** [comment]
You're not gonna like this... Drill Dozer doesn't rumble either.

**Comment by endrift** [comment]
It might just be extremely weak. I'm having the same problem on OS X right now it seems.

**Comment by autofire372** [comment]
Does Drill Dozer rumble when you toggle the rumble setting?

**Comment by endrift** [comment]
Drill Dozer doesn't need that setting.

**Comment by autofire372** [comment]
I meant turning rumble off and on from inside the game itself.

**Comment by endrift** [comment]
Oh, idk, I doubt that would affect anything.

**Comment by autofire372** [comment]
I only ask because Pokémon Pinball rumbles for a bit when rumble is toggled off, then on again from the game's own settings.

**Comment by autofire372** [comment]
...I apologize; evidently I was being unclear. I was talking about the GBC Pokémon Pinball game, not R/S.

**Comment by endrift** [comment]
This might be fixed now.

**Comment by endrift** [comment]
Check with a current nightly, please.

**Comment by autofire372** [comment]
I still get no rumble.

**Comment by endrift** [comment]
Very strange. It works quite well for me.

**Comment by autofire372** [comment]
What version of Windows are you testing on?

**Comment by endrift** [comment]
Windows 10. I only have a 360 controller as far as Xinput controllers go, though.

**Comment by autofire372** [comment]
...Okay, I no longer have any clue what is going on. I just tried mimicking your exact setup (Windows 10+First-party Xbox360 controller) and mgba STILL didn't rumble.

What version of SDL is used for the nightlies?

**Comment by endrift** [comment]
Should be 2.0.4 I think. If it's not, I need to update it. Actually, I need to update all of the deps before the release.

**Comment by autofire372** [comment]
Just tried the latest nightly; it's fixed. I'm guessing commit d97d2b9 did the trick?

**Comment by endrift** [comment]
No, I updated the version of SDL being used. I think it was 2.0.3 before, actually.
