### ISSUE TITLE
Black screen with GL

### ISSUE THREAD

**Issue by sergiobenrocha2** [mgba-emu/mgba#383]
I'm getting a black screen with GL drivers in Ubuntu 14.04, switched to Software and it worked.

Btw, the default option in a clean install is "OpenGL (force version 1.x)"

**Comment by endrift** [comment]
Can't reproduce. What GPU/drivers are you using?

**Comment by sergiobenrocha2** [comment]
Intel Graphics from core i7 4700hq

```
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
```

kernel 3.13.0-96-generic (ubuntu 14.04)
mesa 10.1.3

**Comment by endrift** [comment]
Please verify if this bug is still present.

**Comment by endrift** [comment]
Closing due to lack of reply. Will reopen if it still reproduces.
