### ISSUE TITLE
Street Fighter 2: Rendering issue

### ISSUE THREAD

**Issue by orbea** [mgba-emu/mgba#385]
OS: `Slackware64-current`
`mgba-0.5.0-x86_64-1_SBo`

In any Street Fighter 2 match the screen will strobe between the correct state and garbage.

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mgba/2016-09-19-235109_1680x1050_scrot.png)
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mgba/2016-09-19-235117_1680x1050_scrot.png)
![3](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mgba/2016-09-19-235110_1680x1050_scrot.png)

This issue also occurs in the libretro mgba and tgb dual ports, but not with gambette.
https://github.com/libretro/tgbdual-libretro/issues/8

**Comment by endrift** [comment]
Mostly fixed by 1cb054ec67ea7b1e7e9162c1e74bd4ab254efb74, but it still flickers sometimes.

**Comment by orbea** [comment]
Thanks, that reduced mostly fixed it here too.

**Comment by endrift** [comment]
Can't reproduce on the 0.6 branch. Probably fixed. Let me know.

**Comment by orbea** [comment]
I can not reproduce this anymore either with the 0.6 branch or master, it appears fixed!
