### ISSUE TITLE
Provide an option to install mgba_libretro.so to a different directory

### ISSUE THREAD

**Issue by bentley** [mgba-emu/mgba#386]
Most packagers put libretro cores in someplace other than the default library directory.

* OpenBSD: libs in `/usr/local/lib`, mgba_libretro.so in `/usr/local/lib/libretro`
* FreeBSD: libs in `/usr/local/lib`, mgba_libretro.so in `/usr/local/libexec/libretro`
* Arch: libs in `/usr/lib`, mgba_libretro.so in `/usr/lib/libretro`

[C.f. this discussion.](https://github.com/rdanbrook/nestopia/pull/198) It would be helpful if there were a CMake variable representing “libretro cores directory.”

**Comment by endrift** [comment]
Fixed in 7ae3640bb54302527bd7e1726a588f020ae455c6.
