### ISSUE TITLE
Certain encrypted codebreaker cheats not working

### ISSUE THREAD

**Issue by clobber** [mgba-emu/mgba#390]
mGBA 0.5.0, OS X 10.11

Game: Super Mario Advance (USA, Europe)
Source: http://gamehacking.org/game/6155

The following codebreaker cheat is not working. My only point of reference is that it does work as expected with VBA-M.

Master Code:
```
9005744C362C
034BBC9BD418
F5AC01A7E2B9
```

Moon Jump:
```
712E29965C2A
DD96A6BE81CB
```

Expected result: When holding 'jump', Mario should continually float up higher as if defying gravity.

Input as:
![screen shot 2016-09-21 at 3 46 21 pm](https://cloud.githubusercontent.com/assets/1303132/18728657/d47a795c-8013-11e6-8a07-5d8327b08279.png)

**Comment by endrift** [comment]
Fixed in 78af66c9d5847a6281947143016b931c18b1a075.
