### ISSUE TITLE
Tetris (GB) demo does not play.

### ISSUE THREAD

**Issue by SuperFlomm** [mgba-emu/mgba#391]
The demo that plays in tetris when you wait on the title screen does not play in mGBA. Instead the demo shows up for a few frames and then it goes immediately back to the title screen.

Tested in 5c744a3 (latest nightly at the time I'm writing this) and 0.5.0.

**Comment by endrift** [comment]
Fixed in 05edd2fe52a2f50ba3774c06175cd176fe328984.
