### ISSUE TITLE
Dr. Mario (GB) does not work at all.

### ISSUE THREAD

**Issue by SuperFlomm** [mgba-emu/mgba#392]
Dr. Mario is completely broken. It does not respond to any inputs and instead loops the beep sound at the title screen indefinitely. It is a really obnoxious sound, so be warned.

Tested on latest nightly (5c744a3) and 0.5.0.

**Comment by endrift** [comment]
Fixed in 05edd2fe52a2f50ba3774c06175cd176fe328984.
