### ISSUE TITLE
German keyboard layout

### ISSUE THREAD

**Issue by SuperFlomm** [mgba-emu/mgba#393]
On the German keyboard the letters Y and Z are switched. So by default the B button in mGBA is bound to the key between T and U, which is a little inconvenient. I know this is not really a huge deal because you can just re-bind the B button in the settings, but I thought I should mention it anyway.

![german_keyboard](https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/KB_Germany.svg/550px-KB_Germany.svg.png)

**Comment by endrift** [comment]
Closing in favor of #905, which is more general.
