### ISSUE TITLE
[Request] nocash-style debug info buffer

### ISSUE THREAD

**Issue by adamschackart** [mgba-emu/mgba#395]
The non-free version of no$gba had a feature that allowed homebrew GBA software to write to a string that could be displayed by the emulator, for debugging purposes. This was presumably done by writing to an invalid GBA address recognized by the emulator.

It would be an extremely helpful feature for those of us who don't enjoy using GDB, and don't have the screen real estate to blit debug info.

**Comment by endrift** [comment]
This has been planned for basically as long as mGBA has been a thing, I just haven't gotten around to it yet as it was relatively low priority compared to more user-facing features. I'll try to get this in for 0.6.

**Comment by endrift** [comment]
Added in e79963b007a0feee6c241774609808061c288f1b, with the C interface added in 65b4a76952d5e1cb5e9c3cd031517622851891f1. It should show up in the Logs panel in mGBA.
