### ISSUE TITLE
Sprite glitching on random frames in Wacky Racers (GBC)

### ISSUE THREAD

**Issue by gourdcaptain** [mgba-emu/mgba#397]
In Wacky Races (GBC, US release) during a race, sprites glitch out every second or two for a frame. Seems to be more common at certain speeds, but I can't make a definitive call.
Version of mGBA tested: 0.5.0, 0.6-1-40fb750-dirty (built from Arch AUR package)
OS: Arch Linux 64-bit
CPU/GPU: Intel Core m5-6Y54/Intel HD Graphics 515.

Example:
![wacky races usa en fr es -0](https://cloud.githubusercontent.com/assets/7662067/18776227/d6033d40-8135-11e6-92ca-7852caaf5522.png)

**Comment by endrift** [comment]
I can't reproduce. Has it been fixed on your end?

**Comment by gourdcaptain** [comment]
Yeah, I'm no longer getting it on 0.5.1.
