### ISSUE TITLE
FREEART Intro V1,V2,V3 (PD) [C] bugs

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#401]
FREEART Intro V1 (PD) [C]
speech doesnt play properly

FREEART Intro V2 (PD) [C]
nothing but a black screen

FREEART Intro V3 (PD) [C]
speech doesnt play properly

**Comment by endrift** [comment]
V2 is broken on hardware (so I am told).

The speech has (mostly) been fixed, enough to where I'm satisfied closing this bug.
