### ISSUE TITLE
 Stadin Brankkari by amuQ Creations bugs

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#404]
http://www.pouet.net/prod.php?which=3351
a few of the effects are missing and then it freezes up on the credit screen

**Comment by endrift** [comment]
Water effect seems to be running at a weird framerate. Otherwise it works fine right now.

**Comment by endrift** [comment]
Only bug I can see at the moment appears to be an issue that should be resolved by the pending PPU rewrite (SCX changing mid-scanline). Since that's a known shortcoming I'm going to close this.
