### ISSUE TITLE
Men in Black - The Series (USA, Europe) (SGB Enhanced)

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#407]
using Mgba 0.5.0
nothing  but a blank screen

**Comment by endrift** [comment]
Fixed by 3cfdad192c2e54ad6a94430008bf8f99c1c831cc, although there are still issues with the screen being cleared when it's not supposed to be.

**Comment by endrift** [comment]
Fixed in f73fd7f.
