### ISSUE TITLE
[Qt] Toggle fullscreen shortcut

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#41]
It's currently impossible to map fullscreen and exit fullscreen to the same button. A toggle feature would be nice.

**Comment by endrift** [comment]
The enter fullscreen button should be toggle fullscreen already. Does this not work?

**Comment by karasuhebi** [comment]
It toggles just fine for me. I even remapped it to Ctrl+A and it still toggles fine. I think @tony971 just assumed it wasn't going to toggle because there's a separate key for fullscreen and exiting fullscreen even though the fact is that the fullscreen shortcut is a toggle.

**Comment by tony971** [comment]
It does. Sorry I'm dumb.
