### ISSUE TITLE
VBlankIntrWait with interrupts disabled crashes emulator

### ISSUE THREAD

**Issue by adamschackart** [mgba-emu/mgba#410]
The following program (using libGBA) causes the emulator to hang:

#include \<gba.h\>
int main(void) { VBlankIntrWait(); return 0; }

**Comment by MoochMcGee** [comment]
For one, that's not an emulator crash, for another thing, that's entirely accurate to the hardware. If you wait for an interrupt with interrupts disabled, what do you THINK will happen?

**Comment by MoochMcGee** [comment]
@endrift Close please.

**Comment by endrift** [comment]
I mean, you're half right. it shouldn't hardlock the emulator UI though.

**Comment by MoochMcGee** [comment]
That is true, I didn't notice that in their wording. I guess that means there is a bug here, but this issue report is still utter garbage.

**Comment by endrift** [comment]
Fixed in 6f9a0d9758537b80df5291bd05dff26a626113ff. @MoochMcGee, please don't harass bug reporters. Even if the reports are vague or missing info, there's generally an actual bug to be discovered when someone reports a bug. I don't want to scare off people who report the bugs.

**Comment by adamschackart** [comment]
1. The emulator should not hang or crash under any circumstances, even in the face of an antagonistic user (the GBA was also designed to keep chugging along no matter what the user throws at it).

2. I included a 100% full repro of the bug. My miswording of the effects of this bug do not make my report utter garbage.

3. I won't be discouraged from contributing to one of my favorite development platforms because of one Dunning-Kruger. :)
