### ISSUE TITLE
Small transitions bugs in Harry Potter 1 (Europe) (GBC)

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#411]
I notice a pair of bugs that make part of the screen white for a few frames:

-In the game menu, when I choose to create or load a save.

![harry potter and the sorcerer s stone usa europe en fr de es it pt nl sv no da fi -4](https://cloud.githubusercontent.com/assets/16591467/18808210/1dd119cc-825c-11e6-9ead-4b9f542d9f61.png)
![harry potter and the sorcerer s stone usa europe en fr de es it pt nl sv no da fi -3](https://cloud.githubusercontent.com/assets/16591467/18808211/2450c2c0-825c-11e6-97a3-6bd3295c447d.png)

-In a scene in the beginning of the story, after I press A to close it.

![harry potter and the sorcerer s stone usa europe en fr de es it pt nl sv no da fi -6](https://cloud.githubusercontent.com/assets/16591467/18808214/33654b8c-825c-11e6-8f66-f57d4e6fd40b.png)
![harry potter and the sorcerer s stone usa europe en fr de es it pt nl sv no da fi -5](https://cloud.githubusercontent.com/assets/16591467/18808215/3ac4f274-825c-11e6-8a65-2a1055fda535.png)

I only played it for a few minutes, so probably there are more similar bugs in the game.

A decade ago I had the game and I don't remember to see those glitch. Also, I tested the game in BGB and VBA-M and none of them show those white zones during the transitions.

**Comment by endrift** [comment]
I can no longer reproduce these. Are they still reproducible for you?

**Comment by RafaelTrepaUnCarballo** [comment]
it looks like the bug was fixed. Many thanks.

Although I noticed a new performance bug related to this. The framerate drops for 2 seconds each time there is a transition (when you go inside or outside a room, when you finish a battle...).

**Comment by endrift** [comment]
Please file a separate bug for that.
