### ISSUE TITLE
Sonic Advance crash on Act 2 end

### ISSUE THREAD

**Issue by DarkD** [mgba-emu/mgba#414]
As in title Sonic Advance U ROM crashes after you beat Robotnik and setting free animals.
mGBA 0.6-4020 (and on 0.5.0). Save state before crash http://www93.zippyshare.com/v/Lwk5H48u/file.html

**Comment by endrift** [comment]
Fixed in 9c4de0e30cad0f60c70b78a91b74b7a2f5449850. It was an issue with savestates, not with Sonic Advance.
