### ISSUE TITLE
Little Mermaid II, The - Pinball Frenzy (USA) (En,Fr,De,Es,It) (Rumble Version) blank screen

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#418]
using Mgba 0.5.0
nothing but a blank screen

**Comment by endrift** [comment]
Blank screen was fixed by 3a0b8af70ae0a4b27b124342abbf3b63cef0820d but graphics are still really bugged.

**Comment by endrift** [comment]
Fixed in d68a21fc26d23e87931eac01e9e8a74c964fe51c.
