### ISSUE TITLE
Freeze toggling fullscreen while using fast forward

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#42]
Using 5/13 nightly (0.3-2184-e9d8f1c), mGBA will freeze if toggling fullscreen while using fast forward.

**Comment by tony971** [comment]
There are other times that toggling fullscreen freezes the emulator, but this is the easiest to reproduce.

**Comment by endrift** [comment]
Cannot reproduce on OS X. I'll try another OS next.

**Comment by tony971** [comment]
Unable to reproduce anymore. Closing.

**Comment by endrift** [comment]
I was actually able to reproduce this on Linux earlier this week, but the issue appeared to be a GL driver bug (not 100% sure), so I don't know if there's much that can be done.
