### ISSUE TITLE
Cannon Fodder (USA) (En,Fr,De,Es,It) bugs

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#420]
using Mgba 0.5.0
glitchy lines during the intro and music and speech sound staticy
then it freezes up at the start of level one

**Comment by taisel** [comment]
If this is glitchy then crystalis should be checked too.

**Comment by endrift** [comment]
At some point the freezing stopped, but the intro is still glitchy, and Crystalis seems to work fine.

**Comment by endrift** [comment]
Intro is not glitchy on master. Must have been fixed at some point.
