### ISSUE TITLE
(GBC) Dance Dance Revolution GB: Disney Mix does not work.

### ISSUE THREAD

**Issue by SuperFlomm** [mgba-emu/mgba#426]
mGBA can not load Dance Dance Revolution GB: Disney Mix for GBC.
![ddrgbdm](https://cloud.githubusercontent.com/assets/21297175/19089927/8c63024c-8a7c-11e6-8eed-acd99ba7e5d3.png)
Strangely the other DDR games for GBC work just fine. Tested on 0a791a2.

**Comment by endrift** [comment]
Fixed in 2bd8dd2fa299679629972e3a66c28e6004307e0c.
