### ISSUE TITLE
mGBA crashes when I try to record a GIF

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#428]
As soon as I press "start", it crashes.
This bug happens with the 0.5.1 and nightly builds. It affects any game and any frameskip.

**Comment by endrift** [comment]
Which OS? I tested this on OS X and it worked, maybe the Windows build is broken.

**Comment by RafaelTrepaUnCarballo** [comment]
Windows 10 x64

**Comment by Prof9** [comment]
Getting the same issue on 0.5.2 stable, Windows 10 x64 also.

**Comment by endrift** [comment]
Last time I checked, I was pretty sure this was a problem with the build of ImageMagick that was being bundled. I never looked too deeply into it though.

**Comment by endrift** [comment]
Can you check to see if this works in the latest nightlies, both the x64 and x86 versions? They have different builds of ImageMagick but otherwise are the same codebase.

**Comment by Prof9** [comment]
I've just tried the Windows [nightlies](https://mgba.io/nightlies/1/) dated 2017-05-23 on Windows 10 x64 1703. x64 nightly seems to work fine, but x86 still crashes.

**Comment by endrift** [comment]
Thanks for checking. I should probably refresh the build for the x86 nightly then, since that's probably the problem. Some combination of the various versions of libpng in use or something...

**Comment by endrift** [comment]
Rebuilding ImageMagick appears to have fixed it. Next nightly will be working.
