### ISSUE TITLE
Pokémon Emerald (U) codes not working

### ISSUE THREAD

**Issue by 2nubis** [mgba-emu/mgba#429]
Was playing Pokémon Emerald and tried to put in these Gameshark Codes but they didn't work. Any help?
<img width="423" alt="screen shot 2016-10-06 at 17 18 48" src="https://cloud.githubusercontent.com/assets/22669113/19171072/02149b14-8be9-11e6-9a1f-f1980fdc9909.png">

**Comment by endrift** [comment]
Try pressing Add Pro Action Replay instead of Add or Add GameShark and see if they work. Code sites like to lie about what type of code something is.

**Comment by 2nubis** [comment]
@endrift Thank you so much, they are working now!! Props to you for being the fastest mod to respond to anything :)

**Comment by endrift** [comment]
Glad I could help :)
