### ISSUE TITLE
OSD messages can be displayed late

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#43]
If saving or loading save states in rapid succession, the OSD messages of "State [x] saved/loaded" will stack their timers, rather than having the new message override the old one. This can cause a big queue of OSD messages if someone spams saves/loads on a platforming game.

**Comment by endrift** [comment]
The only timers the OSD uses are for the removal; overriding them should work fine. Although I admittedly have seen this bug as well, so I'll need to dig a bit.
