### ISSUE TITLE
Small and brief glitching in the portraits of "Rebelstar - Tactical Command"

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#430]
During a long conversation part of the portrait of the speaker blinks for an instant (It doesn't always happen, but in long conversation you may see it a few times.

This bug is present in the nightly and the 0.5.1 version. It looks like VBA-M isn't affected.

**Comment by endrift** [comment]
Does this still reproduce?

**Comment by RafaelTrepaUnCarballo** [comment]
It's still there.

**Comment by endrift** [comment]
Does this still reproduce?

**Comment by RafaelTrepaUnCarballo** [comment]
I can't reproduce the bug. I think it's fixed.

Thank you, endrift.
