### ISSUE TITLE
Win32: Drag-and-Dropping .gb/.gbc roms freezes

### ISSUE THREAD

**Issue by Hking0036** [mgba-emu/mgba#431]
When drag-and-dropping gb roms on mGBA it loads up and seems frozen. Sometimes it fixes itself by waiting a few seconds, other times by pressing turbo, sometimes it just sticks, dragging-and-dropping over another game running just leaves it frozen, pressing turbo might make it go into a white screen. I don't know if that's because I don't do a proper shutdown or what. This was an issue in 0.5.0 too, but it wasn't frozen, it would run at about 3-5 fps until it hit the intro screen of each game. I tested both with Pokemon Red and Kirby's Block Ball, as well as with Donkey Kong GB for GBC.

I'll try and get a video up if I can figure out recording software.

Here's a video: https://www.youtube.com/watch?v=yHmMC9_I1tw

**Comment by endrift** [comment]
Are you using an EmuCR build?

**Comment by Hking0036** [comment]
I'm using the official 0.5.1 build from the downloads page.

**Comment by Hking0036** [comment]
Also, unrelated but have you taken a look at the battle network Virtual Console patches [here](http://forums.therockmanexezone.com/topic/8947437/1/)?

There's a version of Mega Man Battle Network 5 dumped from the VC that currently doesn't run on any emulator. I don't know how feasible it is to get it running in mGBA (and in fact I think the fixed version is superior because it doesn't have motion blur), but I thought if you hadn't heard or seen that it might be of interest. Also, I personally dumped final fight one from the wii u and it freezes after the capcom screen.

**Comment by endrift** [comment]
Does this still reproduce in 0.5.2, 0.6.0 or a dev build?

**Comment by Hking0036** [comment]
Downloaded 0.6 and looked, seems to have been resolved.
