### ISSUE TITLE
(GB) Bubble Ghost transition bug.

### ISSUE THREAD

**Issue by SuperFlomm** [mgba-emu/mgba#432]
I noticed a difference between 2 emulators and went on to test it on my GBA SP. The transition between screens in Bubble Ghost shows a white screen on hardware. While mGBA doesn't.
mGBA:
![1](https://cloud.githubusercontent.com/assets/21297175/19205902/7ee80106-8ce5-11e6-9ba6-6dc3ac452747.gif)

BizHawk (Gambatte): Same as hardware.
![2](https://cloud.githubusercontent.com/assets/21297175/19205905/80cb2bd8-8ce5-11e6-990e-5b5f2ad93486.gif)

**Comment by endrift** [comment]
Did you test this on 0.5.1?

**Comment by SuperFlomm** [comment]
Yes, I did test it on 0.5.1.

**Comment by SuperFlomm** [comment]
Here is a side by side comparisson of both emulators with the same input:
(I couldn't unpause both emulators at the same time, so there is a slight delay before the title screen.)
![sidebyside](https://cloud.githubusercontent.com/assets/21297175/19304872/b41b123c-906e-11e6-82c2-df22d0734128.gif)

**Comment by endrift** [comment]
Seems to work fine in master.
