### ISSUE TITLE
Unplayable White Screen and Not Sure How Cheats Work

### ISSUE THREAD

**Issue by sarosen12** [mgba-emu/mgba#437]
I was recently playing my mGBA when I turned it off after I was done. Then when I turned it back on, it appears as normal but when I plug any game it it goes on this continuous white screen. I have tried with different ROMs, I have tried uninstalling and reinstalling it and nothing helped. Ive tried everything, you name it I tried it. It was working fine up until this point. It was Leaf Green.

Also, how do you get the cheats to work on mGBA?

EDIT: It is on a mac laptop.

**Comment by endrift** [comment]
The config file is in ~/.config/mgba/config.ini. Try deleting that to see if it fixes anything.

**Comment by sarosen12** [comment]
Where exactly do I find the config file? Do I delete the whole file or just a portion? The only files I see are "CHANGES" , "LICENSE" , "mGBA" , "READ ME" , and a "third party" folder with nothing about configuration in it. What exactly should I do? And thank you for the help I really appreciate it.

**Comment by endrift** [comment]
Um, as I already said, the config is in ~/.config/mgba. That's a folder. Hit cmd+shift+g in finder and type that in.

**Comment by sarosen12** [comment]
Works! Thank you!
