### ISSUE TITLE
[Windows][GBA] Attempting to use MidiKey2Freq to dump BIOS crashes emulator

### ISSUE THREAD

**Issue by modwizcode** [mgba-emu/mgba#438]
Using this code [link](https://gist.github.com/modwizcode/b4afc78ea74fb453be3bcaf3d3bc8adc)

I get a crash of the emulator when running latest nightly (0.6-4056-f3856f2) and stable, this happens only when I use a dumped BIOS file, the program completes successfully when I don't use the dumped BIOS and instead use the built-in.

The address it gets to for dump address is `0x3ff4` and part is `A`, which means it was able to perform the first MidiKey2Freq call and read at `i-4` (i.e. `0x3ff0`). When loading with the dumped BIOS the log shows that it's detected an official GBA BIOS. When loading with the HLE BIOS (which runs fine), I get game errors reported in the log for each read, 

`[GAME ERROR] GBA Memory:	Bad BIOS Load32: 0x000017C3` is one such example.

I haven't had time to dig into the code to determine the cause of the crash, but my perliminary poke into the error suggests that the HLE memory reads being done for HLE MidiKey2Freq don't get marked as being read from code in the BIOS section as they would with LLE or a hardware GBA, so the memory read code throws the error and complies (I don't know what would happen on hardware, I would assume a hang maybe?). 

I know this isn't used by most (any?) games, but if emulation accuracy is a goal I would think fixing this is important.

**Comment by endrift** [comment]
I don't understand the bug report. I tried it with both the official BIOS and the HLE BIOS and neither crashed.

But then you go on to talk about something else that seems unrelated to the issue at hand, and is only HLE BIOS related? Is this one issue or two that you're talking about here?

**Comment by modwizcode** [comment]
That's the exact size I have. I am on Windows 10 Build 14926.rs_prerelease.160910-1529 if that helps. I don't have this crash when using the mGBA core for BizHawk but I doubt that's really related.

 This is two issues I guess, when I run the HLE BIOS as I said, the emulator does not crash, but if I view the log and enable "Game Error" output, that error is printed for every address that the HLE Bios accesses with MidiFreq2Key, which shouldn't be the case.

**Comment by endrift** [comment]
Crash fixed in 4cbcc41e35665f7b5fcd5fd0f911c80a0efbe81c, HLE BIOS reads fixed in 8ac697f31085caab31dc7652aabfac876a452b25.
