### ISSUE TITLE
Problem with cheats

### ISSUE THREAD

**Issue by sarosen12** [mgba-emu/mgba#439]
Hi-

Whenever I input cheats for leaf green they do not work. How do you actually activate them after putting the codes in? There is no way to put the codes in before loading the game and I cannot find a button to make them activate. Does it do it automatically?

Thanks for the help!

**Comment by endrift** [comment]
This is probably due to cheat sites lying about which type of cheat it is, not due to them being inactive (they are active by default, as indicated by the checkmark). Try downloading the latest nightly; I added some heuristics for determining what type of cheat is entered.

**Comment by endrift** [comment]
Closing due to no response from submitter. Will reopen if I get information back and it's not fixed.
