### ISSUE TITLE
[Feature Request] Auto-hide cursor when no mouse movement is detected

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#44]
As it stands, mGBA hides the mouse cursor immediately and permanently while you're in full screen mode. I'd like to be able to still see my mouse when I move it, and have it instead to where it auto-hides itself after a certain number of seconds of inactivity. Look at programs like PCSX2 and MPC-HC for the behavior I'm describing.

Thanks!

**Comment by endrift** [comment]
Working on this, but it seems to be broken in fullscreen, which is the most important place for it to work.

**Comment by karasuhebi** [comment]
Glad to hear you're working on it, but sad that it seems to be broken at the moment. Which I could help. :-\ Thanks for looking into it though! :D

**Comment by endrift** [comment]
Can you verify in the upcoming nightly (in a few hours) if fullscreen cursor hiding works on Windows? On OS X, it would hide for about a second, then reappear.

**Comment by endrift** [comment]
Seems to work fine on Windows 7.

**Comment by karasuhebi** [comment]
I have no idea how I missed the last message. Sorry endrift! I'll check it out tomorrow in Windows 8.1 and report back.

**Comment by karasuhebi** [comment]
It works beautifully in Windows 8.1. Although I'd like the delay to be a bit shorter, a second seems like too much time.

**Comment by endrift** [comment]
It's actually 2 seconds at the moment. I can probably halve it and still be ok.

**Comment by karasuhebi** [comment]
Sounds good to me. Thanks again for doing this!
