### ISSUE TITLE
Pokemon Crystal Crashes After Loading Save State

### ISSUE THREAD

**Issue by larrydalitllama** [mgba-emu/mgba#440]
The game crashes after loading a save state, once I go in to a battle and try to attack, that is when it crashes. I tried to read previous post about this but couldn't find the solution

**Comment by endrift** [comment]
Update to 0.5.1.

**Comment by larrydalitllama** [comment]
I am using 0.5.1

**Comment by endrift** [comment]
Ok, I'll take a look sometime tomorrow.

**Comment by larrydalitllama** [comment]
Thank you

**Comment by endrift** [comment]
Fixed in 900700aa41680ca80a7d2d8d824054313b0f88d4. Thanks for reporting it.

**Comment by larrydalitllama** [comment]
Thank you for fixing this, now how do I fix it on my end?

**Comment by endrift** [comment]
Download a nightly. https://mgba.io/downloads.html#development-downloads-nightlies

**Comment by profi200** [comment]
Damn it. Ninja'd.
I would wait for 0.5.2 though.

**Comment by endrift** [comment]
You'll be waiting a while. I've slowed down recently to avoid burnout (again), so 0.5.2 won't be out for about a month.
