### ISSUE TITLE
Music in Spot (GB) doesn't sound right.

### ISSUE THREAD

**Issue by SuperFlomm** [mgba-emu/mgba#442]
The following zip contains the title screen music from Spot (GB). Recorded from a Game Boy Color and mGBA. The difference should be obvious.
[Spot_mGBA.zip](https://github.com/mgba-emu/mgba/files/530311/Spot_mGBA.zip)

**Comment by endrift** [comment]
This appears to be a problem with channel 3.

**Comment by endrift** [comment]
Fixed by setting the waveram to the values it would be on a GBC in 974c41e8cfbaa31a0b1534f76843f476970647e6. Still needs tweaking for what a GB would hear, but that's for when I get around to non-deterministic boot.
