### ISSUE TITLE
window size resets when window minimized

### ISSUE THREAD

**Issue by stubl** [mgba-emu/mgba#444]
the window size management changes are something I really appreciate - I like to re-size the gba emulator window to have black borders on the top/bottom

there is 1 small glitch I notice however - if you change the window size, and then minimize the mgba window, the window size reverts back to the previous window size (doesnt remember recent change)

this doesnt happen when merely pressing alt-tab to a new window, but minimizing does this

**Comment by endrift** [comment]
Fixed in c549db69f1774b4b06edb3b555b53c682ec43a49.
