### ISSUE TITLE
Allow mapping Gyroscope to single axis

### ISSUE THREAD

**Issue by tomaszkam** [mgba-emu/mgba#449]
Allow to map gyroscope to an single axis, instead of two of them. This would be very usefull in case of using DualShock 4 controller on Linux, where gyroscope axis are exposed.

**Comment by endrift** [comment]
Are there any specific drivers I need for testing DS4 on Linux?

**Comment by tomaszkam** [comment]
Works out the box with bluetooth connection on the 4.8.0-22-generic kernel (Ubuntu 16.10). There was a bug in 4.4 kernel (16.04) that was preventing anything other than touchpad from working.

**Comment by endrift** [comment]
I have an Arch box that dual boots between a 4.4 LTS and current, so I'll try booting current sometime soon to look into this.

**Comment by endrift** [comment]
Unfortunately it looks like the events the DS4 sends don't have fine-grained enough gyroscope data for WarioWare to be playable. It only sends gyro data when you really fling it, which makes the game completely unplayable.
