### ISSUE TITLE
Fullscreen option is messing with mGBA's frame size/window size.

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#45]
As of the latest nightly, e9d8f1c, the act of exiting fullscreen causes mGBA to add exactly 21 to the height value in the config.ini file upon closing mGBA. This creates a letterboxing effect in games the next time you open mGBA.

OS: Windows 8.1 x64

**Comment by endrift** [comment]
I have managed to reproduce this on Windows 7. I'll take a closer look tomorrow.

**Comment by endrift** [comment]
I lied, I took a closer look today.

**Comment by karasuhebi** [comment]
Confirmed working in Windows 8.1 x64
