### ISSUE TITLE
Rotate the screen.

### ISSUE THREAD

**Issue by SuperFlomm** [mgba-emu/mgba#455]
I don't know if there are any commercial games that requires you to hold your GBA sideways or upside down. [But there is a homebrew Flappy Bird clone that does.](https://youtu.be/SNm9kNV9rnw?t=11s)

So, I think there should be an option that allows you to turn the screen by 90, 180 and 270 degrees.

**Comment by endrift** [comment]
Dupe of #179. #187 did some work towards it but my nits were never fixed so it didn't get merged.

**Comment by Korubiiii** [comment]
so is this just never going to be added as a feature?

**Comment by jtolio** [comment]
Dr Mario and Puzzle League have a mode where the screen is sideways.
