### ISSUE TITLE
DK: King of Swing Crash On Level Treacherous Twister

### ISSUE THREAD

**Issue by wildgoosespeeder** [mgba-emu/mgba#457]
mGBA 0.5.1
* Windows 8.1 Pro 64-bit
* NVIDIA GeForce 610M
* Intel Core i5-3210M @ 2.5Ghz
* 12GB DDR3-12800 RAM

"The game has crashed with the following error: Jumped to invalid address: E1DA19B4"

Some weird things to note with this error:
* Many of the same window pop-up
* 3DS port just stalls where the error occurs
* Just Treacherous Twister it seems

More info about the level:
http://www.mariowiki.com/Treacherous_Twister

I used a GameShark save so it should be quite easy to load the level:
http://www.gamefaqs.com/gba/920791-dk-king-of-swing/saves

**Comment by endrift** [comment]
This seems to be just a problem with the save. Can you try to get to that level from a fresh save?

**Comment by endrift** [comment]
Verified that the save works fine on an actual GBA.

**Comment by wildgoosespeeder** [comment]
Oh wow. It's been a while since I reported this bug. I didn't check this until now. Thanks for verifying the bug. Do you have any idea what is causing it?

**Comment by endrift** [comment]
Not yet. I'll take a closer look at it at some point, but it oddly also crashes in VBA-M in exactly the same way, so I'm really curious about what's causing it. There are a handful of "this affects every emulator" bugs, such as #190 and the Lady Sia bug (which never got filed for some reason), which makes them an interesting target but also a huge pain.

**Comment by endrift** [comment]
Turns out no emulators were properly masking the top bit of the WAITCNT register.

**Comment by wildgoosespeeder** [comment]
Strange, an old version of VBA (2004) doesn't have DKKoS crash (unless it found a way to ignore it so the game remains playable). Anyways, thanks for fixing. Can't wait for 0.5.2!
