### ISSUE TITLE
Request - Load Memory Dumps

### ISSUE THREAD

**Issue by wildgoosespeeder** [mgba-emu/mgba#458]
In VisualBoyAdvance (before VBA-M), there was an ability to load memory dumps. This was really useful for a tool that allowed you to create tracks for F-Zero Climax externally that had a memory dump option so you don't have to type in the long and cryptic password at the password entry screen. It would be nice if mGBA had such an option to load the memory dumps that the editor can generate:

* http://www.romhacking.net/utilities/414

**Comment by endrift** [comment]
This was actually added a few days ago in 27545462e4b14f77929d9469382299fe2a7510e1, although the UI is probably a bit difficult at the moment.

**Comment by wildgoosespeeder** [comment]
Oh wow! Thanks for implementing for the next release before I even submitted a feature request!
