### ISSUE TITLE
Crash when start Pokemon Rom

### ISSUE THREAD

**Issue by dedetok** [mgba-emu/mgba#463]
Description
Faulting Application Path:	D:\game\mGBA-0.5.1-2016-10-05-win32\mGBA.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	mGBA.exe
Application Version:	0.5.1.0
Application Timestamp:	00000000
Fault Module Name:	StackHash_2beb
Fault Module Version:	0.0.0.0
Fault Module Timestamp:	00000000
Exception Code:	c0000005
Exception Offset:	PCH_8A_FROM_ntdll+0x00093930
OS Version:	10.0.14393.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	2beb
Additional Information 2:	2beba6fb4680d73a8c78ca7c24ccdb46
Additional Information 3:	acf2
Additional Information 4:	acf2e3f0ca50528396b0f46e1ee20a66

Extra information about the problem
Bucket ID:	99f22248ee1f2149406865130f00b53a (108446331411)

Environment:
OS Name	Microsoft Windows 10 Home
Version	10.0.14393 Build 14393
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	FUJITSU
System Model	LIFEBOOK MH330
System Type	X86-based PC
System SKU	
Processor	Intel(R) Atom(TM) CPU N455   @ 1.66GHz, 1667 Mhz, 1 Core(s), 2 Logical Processor(s)
BIOS Version/Date	FUJITSU // Phoenix Technologies Ltd. Version 1.05, 6/24/2010

**Comment by endrift** [comment]
Well you've given me almost no useful information, but try using a nightly instead of 0.5.1 and see if that changes anything.

**Comment by endrift** [comment]
Closing due to lack of communication. If you still have this issue, please comment and I can reopen it.
