### ISSUE TITLE
mGBA crashes upon Loading ROM if path contains special character

### ISSUE THREAD

**Issue by chbnm** [mgba-emu/mgba#465]
Hi,

mGBA always crashes upon loading a ROM if the file path contains a special character like "é" (as in "Pokémon") or German "ß".
Probably nasty to work around (let alone notice) if your Windows account name has one in it.

I'm running v0.5.0 on Windows 7 x64.

Thanks for your work!

**Comment by endrift** [comment]
This was fixed in 5418f25d85f756b7d8028351b17ad7c7ee50a065. Please either update to a nightly build, or wait for mGBA 0.5.2 to ship with this fix.
