### ISSUE TITLE
Pokemon Puzzle Challenge: message slightly cut off

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#466]
The inferior part of the text in the corner is cut off by a pixel wide white line.
BGB and VBAM visualize the text right.

mGBA
![pokemon puzzle challenge europe en fr de es it -mgba](https://cloud.githubusercontent.com/assets/16591467/20322520/bf53f3e6-ab79-11e6-928b-d45f256b381d.png)
BGB
![pokemon puzzle challenge europe en fr de es it -bgb](https://cloud.githubusercontent.com/assets/16591467/20322521/bf543ac2-ab79-11e6-9cb6-eb908168a04f.png)
VBAM
![pokemon puzzle challenge europe en fr de es it -vbam](https://cloud.githubusercontent.com/assets/16591467/20322522/bf5611a8-ab79-11e6-92fe-0f93024cad7c.png)

An extremely insignificant bug.

**Comment by taisel** [comment]
You probably should provide a save state from each. GB hardware is full of hardware bugs that are seldomly documented. IIRC there's a ton of windowing/BG layer bugs and mid scanline variable timings.

**Comment by RafaelTrepaUnCarballo** [comment]
Ok, but that shouldn't be necessary. The issue is easily reproducible, you only have to start a new Challenge game at any difficulty. It always happens, affects both EUR and USA editions and any version of mGBA.

Savestates of mgba
[Savestates Pokemon P. Challenge USA PAL.zip](https://github.com/mgba-emu/mgba/files/593144/Savestates.Pokemon.P.Challenge.USA.PAL.zip)

Savestates of VBAM last beta
[pok puzzle challenge savestates VBAM.zip](https://github.com/mgba-emu/mgba/files/593156/pok.puzzle.challenge.savestates.VBAM.zip)

BGB
[Pokemon Puzzle Challenge savestates USA EUR - BGB.zip](https://github.com/mgba-emu/mgba/files/593171/Pokemon.Puzzle.Challenge.savestates.USA.EUR.-.BGB.zip)

**Comment by endrift** [comment]
This was caused by STAT IRQs firing on line 0x77 twice, once for Hblank and once for LYC=LY.
