### ISSUE TITLE
[Qt] Toggle Fullscreen keyboard shortcut not working.

### ISSUE THREAD

**Issue by MasterLaser** [mgba-emu/mgba#47]
In the menu Alt+Enter is shown for toggling fullscreen however this key combo does nothing.
Effects Windows, not sure about Linux.

Tested on commit bd2c472cb355f96ad5a30a52964ed7606ead6ddb

**Comment by endrift** [comment]
Shoot, I changed the shortcut a few days ago and forgot to check if it worked.

**Comment by endrift** [comment]
Fixed in df79ee19c31a6c8202b2e4a19e88fdcde9a66c25 (it did not affect 0.2)
