### ISSUE TITLE
Compilation fails with GLES2, SDLSoftwareRenderer hasn't been defined anywhere

### ISSUE THREAD

**Issue by k3388t** [mgba-emu/mgba#470]
I'm trying to build mgba on ARM, debian 8, using the flags:
`cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBUILD_QT=OFF -DUSE_DEBUGGERS=OFF -DBUILD_GL=OFF -DBUILD_GLES2=ON -DUSE_FFMPEG=OFF ..`
Because building with GLES1 conflicts with GLES2, but that's another bug.

Building fails with:
`/home/user/mgba/src/platform/sdl/gles2-sdl.c:12:34: warning: ‘struct SDLSoftwareRenderer’ declared inside parameter list
 static bool mSDLGLES2Init(struct SDLSoftwareRenderer* renderer);
                                  ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:12:34: warning: its scope is only this definition or declaration, which is probably not what you want
/home/user/mgba/src/platform/sdl/gles2-sdl.c:13:40: warning: ‘struct SDLSoftwareRenderer’ declared inside parameter list
 static void mSDLGLES2RunloopGBA(struct SDLSoftwareRenderer* renderer, void* user);
                                        ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:14:36: warning: ‘struct SDLSoftwareRenderer’ declared inside parameter list
 static void mSDLGLES2Deinit(struct SDLSoftwareRenderer* renderer);
                                    ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c: In function ‘mSDLGLES2Create’:
/home/user/mgba/src/platform/sdl/gles2-sdl.c:17:17: warning: assignment from incompatible pointer type
  renderer->init = mSDLGLES2Init;
                 ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:18:19: warning: assignment from incompatible pointer type
  renderer->deinit = mSDLGLES2Deinit;
                   ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:19:20: warning: assignment from incompatible pointer type
  renderer->runloop = mSDLGLES2RunloopGBA;
                    ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c: At top level:
/home/user/mgba/src/platform/sdl/gles2-sdl.c:22:27: warning: ‘struct SDLSoftwareRenderer’ declared inside parameter list
 bool mSDLGLES2Init(struct SDLSoftwareRenderer* renderer) {
                           ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:22:6: error: conflicting types for ‘mSDLGLES2Init’
 bool mSDLGLES2Init(struct SDLSoftwareRenderer* renderer) {
      ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:12:13: note: previous declaration of ‘mSDLGLES2Init’ was here
 static bool mSDLGLES2Init(struct SDLSoftwareRenderer* renderer);
             ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c: In function ‘mSDLGLES2Init’:
/home/user/mgba/src/platform/sdl/gles2-sdl.c:93:19: warning: passing argument 1 of ‘mSDLGLCommonInit’ from incompatible pointer type
  mSDLGLCommonInit(renderer);
                   ^
In file included from /home/user/mgba/src/platform/sdl/gles2-sdl.c:8:0:
/home/user/mgba/src/platform/sdl/gl-common.h:11:6: note: expected ‘struct mSDLRenderer *’ but argument is of type ‘struct SDLSoftwareRenderer *’
 void mSDLGLCommonInit(struct mSDLRenderer* renderer);
      ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:96:10: error: dereferencing pointer to incomplete type
  renderer->d.outputBuffer = memalign(16, VIDEO_HORIZONTAL_PIXELS * VIDEO_VERTICAL_PIXELS * 4);
          ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:97:10: error: dereferencing pointer to incomplete type
  renderer->d.outputBufferStride = VIDEO_HORIZONTAL_PIXELS;
          ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:99:31: error: dereferencing pointer to incomplete type
  renderer->gl2.d.filter = renderer->filter;
                                   ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:103:10: error: dereferencing pointer to incomplete type
  renderer->gl2.d.swap = mSDLGLCommonSwap;
          ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:104:10: error: dereferencing pointer to incomplete type
  renderer->gl2.d.init(&renderer->gl2.d, 0);
          ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:104:32: error: dereferencing pointer to incomplete type
  renderer->gl2.d.init(&renderer->gl2.d, 0);
                                ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:105:10: error: dereferencing pointer to incomplete type
  renderer->gl2.d.setDimensions(&renderer->gl2.d, renderer->width, renderer->height);
          ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:105:41: error: dereferencing po
inter to incomplete type
  renderer->gl2.d.setDimensions(&renderer->gl2.d, renderer->width, renderer->height);
                                         ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:105:58: error: dereferencing pointer to incomplete type
  renderer->gl2.d.setDimensions(&renderer->gl2.d, renderer->width, renderer->height);
                                                          ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:105:75: error: dereferencing pointer to incomplete type
  renderer->gl2.d.setDimensions(&renderer->gl2.d, renderer->width, renderer->height);
                                                                           ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c: In function ‘mSDLGLES2Runloop’:
/home/user/mgba/src/platform/sdl/gles2-sdl.c:114:16: error: dereferencing pointer to incomplete type
  while (context->state < THREAD_EXITING) {
                ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:114:26: error: ‘THREAD_EXITING’ undeclared (first use in this function)
  while (context->state < THREAD_EXITING) {
                          ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:114:26: note: each undeclared identifier is reported only once for each function it appears in
/home/user/mgba/src/platform/sdl/gles2-sdl.c:116:4: warning: implicit declaration of function ‘mSDLHandleEventGBA’ [-Wimplicit-function-declaration]
    mSDLHandleEventGBA(context, &renderer->player, &event);
    ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:119:3: warning: implicit declaration of function ‘mCoreSyncWaitFrameStart’ [-Wimplicit-function-declaration]
   if (mCoreSyncWaitFrameStart(&context->sync)) {
   ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:119:39: error: dereferencing po
inter to incomplete type
   if (mCoreSyncWaitFrameStart(&context->sync)) {
                                       ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:120:28: error: ‘struct mSDLRenderer’ has no member named ‘d’
    v->postFrame(v, renderer->d.outputBuffer);
                            ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:122:3: warning: implicit declaration of function ‘mCoreSyncWaitFrameEnd’ [-Wimplicit-function-declaration]
   mCoreSyncWaitFrameEnd(&context->sync);
   ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:122:33: error: dereferencing pointer to incomplete type
   mCoreSyncWaitFrameEnd(&context->sync);
                                 ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c: At top level:
/home/user/mgba/src/platform/sdl/gles2-sdl.c:132:6: error: conflicting types for ‘mSDLGLES2Deinit’
 void mSDLGLES2Deinit(struct mSDLRenderer* renderer) {
      ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:14:13: note: previous declaration of ‘mSDLGLES2Deinit’ was here
 static void mSDLGLES2Deinit(struct SDLSoftwareRenderer* renderer);
             ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c: In function ‘mSDLGLES2Deinit’:
/home/user/mgba/src/platform/sdl/gles2-sdl.c:145:15: error: ‘struct mSDLRenderer’ has no member named ‘d’
  free(renderer->d.outputBuffer);
               ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c: At top level:
/home/user/mgba/src/platform/sdl/gles2-sdl.c:12:13: warning: ‘mSDLGLES2Init’ used but never defined
 static bool mSDLGLES2Init(struct SDLSoftwareRenderer* renderer);
             ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:13:13: warning: ‘mSDLGLES2RunloopGBA’ used but never defined
 static void mSDLGLES2RunloopGBA(struct SDLSoftwareRenderer* renderer, void* user);
             ^
/home/user/mgba/src/platform/sdl/gles2-sdl.c:14:13: warning: ‘mSDLGLES2Deini
t’ used but never defined
 static void mSDLGLES2Deinit(struct SDLSoftwareRenderer* renderer);
             ^
sdl/CMakeFiles/mgba-sdl.dir/build.make:169: recipe for target 'sdl/CMakeFiles/mgba-sdl.dir/gles2-sdl.c.o' failed
make[2]: *** [sdl/CMakeFiles/mgba-sdl.dir/gles2-sdl.c.o] Error 1
CMakeFiles/Makefile2:145: recipe for target 'sdl/CMakeFiles/mgba-sdl.dir/all' failed
make[1]: *** [sdl/CMakeFiles/mgba-sdl.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2`

Reading that and doing a little grep implies that
`struct SDLSoftwareRenderer`
hasn't been defined anywhere in the code.

**Comment by k3388t** [comment]
Here is the cmake output in a more readable format http://termbin.com/q0m2
Thanks.

**Comment by endrift** [comment]
The GLES2 SDL frontend hasn't been maintained in a while because I don't have a good way to compile and test it at the moment. Once I get one of those, and can put it in CI, I can start maintaining it again.

**Comment by k3388t** [comment]
I could fix it. Is SDLSoftwareRenderer the same thing as a mSDLRenderer?

**Comment by endrift** [comment]
Fixed in fbb29de1606f1489fc5aa7f7492e9a610cd95fcd, thanks.
