### ISSUE TITLE
Perfect 2x scale on Wii version for GC/GBA games?

### ISSUE THREAD

**Issue by TwilightSlick** [mgba-emu/mgba#473]
I've been very satisfied with the Wii port of mGBA, and I was just wondering something that I think would make the experience that much more satisfying.

VBAGX, the previous king of the crop for Game Boy emulators on Wii, offers a 2x perfect-pixel scale option for GB, GBC and GBA.

However, mGBA does not offer this feature as of the latest version. The only options are either 1x perfect pixel or stretched.

GBA games look fine, but GB/GBC looks a bit too small. Stretch doesn't look good; I'd like to keep the aspect ratio.

Is it possible to add a 2x integer scale option (or even 3x) to the Wii version of mGBA like what VBAGX does? It doesn't have to be just for GB/GBC, it can also be helpful for GBA as well.

Any response is appreciated. Thank you so much!

**Comment by endrift** [comment]
Pixel perfect stretches the screen up to the maximum size allowable by the screen while maintaining an integer scale. GB games are 160x144, so on a 480p screen, it's 3x (480x432). Likewise, for GBA, it's 3x (720x480). But on other resolutions, it may be different, e.g. for 240p it'll be much smaller.

**Comment by TwilightSlick** [comment]
OK, I understand. However GB/GBC display smaller on 240p than in 480i when using my CRT.
I have screenshots of both below, taken off my CRT. Using 0.50

240p:


![240p screen]
(https://lh3.googleusercontent.com/ymrJCM0kdstY4_LWan4IVUgYt1dTl60eKv17VqRkVz3XYtXTR0hrsUmXk9tU8cSb_iUag1GYBdXX3A_a5m1Mo-T-tTxJC9dYQN0YCGRTG4csq39UWR2o5NNkK9Sxm2Sc3UqPgRtALARvwb7u2VYUSApqZ9tKHvIdL3Dj_z30cpJS-g0INR9Jq2KyEtgVf-F9m0s0WiuYUUTnpO_Yaue-2OtJ3tJYsBogoFZmPFMvjR97NcHk0oAk-HwQ8FtyhQp7DwD7oNZR0HOpWqGkRNIlO64WOO2oXFk4BC9KaoFqStYohLs_sVSEmz7BAzHfDlmuV3EjMSeqFZb_F2iy2hHYhP8gaCU3BbKguoXu6kfmgcsUpQYOif6DplCvM8NI0R72YEPLZwItHLeKeOofMM2LsUmWaEOwZv7fR3iA8dM8-ZKKbqfk_JwL3GLq0DE27jGlT4ytiLMW6G2vp9f6OMnJT64AesqtHz5h2HFOT-iVFNiSypcriNHMoMkGSp7BBeNnPgO41g6nemWe4zXWUR3iogVSZqks4ZppJ_SjVvJA5NqedljLJ_-QUA5rbUbaCEmpLrrcrYqiYqxj6X5aU5R06fuBYTTOFoGis_pftFnH5vhAeZ7ZoRnG2nuCCDlWcvxktSTiaDKjKoVGJDOhL0PvDyCixenYEkZ0rMZxpr8QzQ=w2532-h1424-no)

480i:


![480i screen]
(https://lh3.googleusercontent.com/zgie65eX1aIIzpIfGZ99vIPEMSfBVQjYfKqFDnFPbPKrG25eVzBlNhQZw1vU3q9Wkq7EhWG04IxasfG0L-QJIWuM14hR1l3e4UTBkngQAZ2RGcHI7TgUzrrDzKq2FM8QXtOg8a8nO63GU83ChsAaWhWvbaQ_lekc65gTB5thIwPoZhqsC0C0r68X_XrEYp79TKqEzHSmTg7pvFu6__xKiqIdEhn6C7JmYDd_qASFI8uIjx_JZSVW8Fp2oKAtobDh2mA-RwwAEBV-lgQj19gXK1klhgcz1h91FsaDPkJXhROu9jLSrqKOzthRFMFG4rkJwf30BvDlcxYlQRZJLjbwCUZU8ZLnmWjuN7f15tSJk0586iJjqSVVQTY93H3bO3xTX5M1HwreLh52ofI9imp3-eVDaYiorJCIYJ0Aht9sXckx4hnq5PJf1z7YwraMRpo2T8qnJRgKRDd-xnLeMM4wZDYbJjWBTKec1cLsG1vfZmSi7all1xQZBtEqQOAX2DLNsGmlNcm5RszZuGUkQI7yk-UEt7V2zjTzJ7Z0TjQU70-s_wKpr1Dh_zVKjORIr574_Th70WDvAdRiLzBReytD34ZFqQzKWI6W-9pAuv7sPA5IwcDpB8BT=w2532-h1424-no)

**Comment by endrift** [comment]
Uh, yes, because 144 only goes into 240 once, so it's displaying at 144 tall (60% of the screen), whereas in 480, 144 goes in three times adding up 432, which is 90% of the screen. That's just the way the math works out.

**Comment by TwilightSlick** [comment]
Looks like I might have to stick with VBAGX when it comes to playing GB/GBC games.
I'll still use this for GBA games.
However VBAGX doesn't support 240p like this does, unless there's some mod out there that supports it.

**Comment by endrift** [comment]
Okay but. Can you actually describe the problem? I can't make it taller in 240p without cropping or making it pixel imperfect. And likewise, if I make it 2x in 480i, it will be much shorter.

**Comment by TwilightSlick** [comment]
Okay, I understand. This is only for GB and GBC.
GBA is the same size in both modes.

Besides, I think this is the same size that the Game Boy Player outputs at in 480i on the GameCube without turning borders off. I don't think this even really matters.

Just close this.

**Comment by endrift** [comment]
I'm still not sure what you want, since there seems to be some pretty bad miscommunication going on here, but if you want me to close the issue, I will.
