### ISSUE TITLE
Savestates break savefiles (Pokemon Pinball - Ruby and Sapphire)

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#474]
Make a savestate after making an in-game save and attempt to load the in-game save after reloading the savestate.  Will result in a heavily corrupted pinball machine or emulator crash.  You can save in-game by pausing and selecting to save and quit.  Then in the main menu, make the savestate.  Load said savestate and then hit continue and you will usually reproduce this bug.

**Comment by ROMaster2** [comment]
My best guess from just reading it is the game makes constant minor save change. Save states alters the state it's in and reads/writes the wrong information causing corruption.

**Comment by endrift** [comment]
Seems to be working for me right now?

**Comment by JMC47** [comment]
I can no longer reproduce this glitch.
