### ISSUE TITLE
[Feature Request] - Support GBA/GBC Games with rumble hardware

### ISSUE THREAD

**Issue by MarcoEstevez** [mgba-emu/mgba#475]
There were a few GBA and GBC games that had small hardware to bring Rumble features (Drill Dozer.... )

It would be really cool support them om mGBA if you own a capable controller.

**Comment by endrift** [comment]
This has been supported for a while.

**Comment by MarcoEstevez** [comment]
Thanks, I did not know, sorry  :-D
