### ISSUE TITLE
mgba-qt does not display any graphics

### ISSUE THREAD

**Issue by MarkSill** [mgba-emu/mgba#476]
I'm using mGBA 0.5.1 with the Ubuntu 16.04 package on Linux Mint Cinnamon 18. mgba-qt does load roms (in this case Pokemon Ruby), plays sound, and _is_ emulating the game, but there is nothing displayed. mgba-sdl does display the game.

Changing the renderer to QT (instead of OpenGL) does work. Forcing OpenGL 1.x also works. The default OpenGL setting does not.
glxinfo reports: OpenGL version string: 3.0 Mesa 11.2.0

**Comment by endrift** [comment]
Possibly a dupe of #383. What is your GPU?

**Comment by MarkSill** [comment]
It's integrated Intel. Reported in two entries: "Intel Corporation Sky Lake Integrated Graphics" and "Intel Corporation Device 9d35"

It does look like it could be a dupe. Feel free to close this one if you want.

**Comment by endrift** [comment]
Closing as dupe, and I might have just fixed the original too.
