### ISSUE TITLE
Nightly Build 2016-12-09 - Mother 3 now crashes when trying to load saves.

### ISSUE THREAD

**Issue by TheGoatManfan** [mgba-emu/mgba#477]
Encountered this while updating the emulator to the latest nightly, and decided to play the game again.

When selecting the option to load the game's save menu, it crashes on a black screen, making a similar static noise to when you eject a game while it's running on a real GBA.

No idea why this happens, though. Might be a issue with save detection? Moved to the last version until fixed.

**Comment by endrift** [comment]
Fixed in 85367c37135577de88ed18cf1fe19b226c178b7b, thanks for catching this.
