### ISSUE TITLE
"Apply" button in "Tools > Settings" does nothing

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#479]
Changing a setting and then clicking on the Apply button does not save the setting change. The only way to save a setting change is to click on the OK button.

Also tested the latest nightly (**0.6-4157** at the time of writing) and it has the same issue.

**OS:** Windows 10 Pro x64
**Build at time of writing:** 0.5.1 stable

**Comment by endrift** [comment]
Works fine on macOS. Wonder if it's OS-specific.

**Comment by karasuhebi** [comment]
Maybe it's only certain screens where Apply doesn't work? I believe I tested it on the Shortcuts page.

**Comment by endrift** [comment]
Couldn't reproduce this on Win10 either, and the Shortcuts thing is covered by #480.

**Comment by karasuhebi** [comment]
I meant to say Controllers page, not Shortcuts. Sorry. Can you reproduce it there?

**Comment by endrift** [comment]
Fixed in c83833bfd47f7dc31455d53f92e1dc83fa506746.

**Comment by karasuhebi** [comment]
Thanks! :)
