### ISSUE TITLE
Games do not load automatically

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#48]
There is a weird issue that I seem to be the only one suffering from, so I apologize profusely in advance for wasting your time. Whether I use a real GBA BIOS or not, or the simulated/HLE BIOS, games do not load automatically, the emulator shows a white screen, an FPS counter, but no splash screens for the actual ROM. I have to press control+P to pause, then un-pause and from there the game loads fine. I dont know why this is happening on my end, my computer has a quad core Core i5 3570, 8 GB RAM, 2 x 1 TB HDDs, 2 GB GPU...my PC is more than powerful enough, so it can't be the specs....

Why don't the games boot up on their own with either option? Is there anything I can do? 

Versions using: 0.21 official and developer builds, both yield the same results.

**Comment by endrift** [comment]
Does changing the number of audio samples in the menu make it start? What about disabling audio sync (and if that works, is there any audio)?

**Comment by therandomizer85** [comment]
I haven't thought about changing those, actually, but I'll give it a shot.

**Comment by therandomizer85** [comment]
Sorry for the double post, but to reiterate:

- Changing samples from 2048 to 1024 after the white ROM boot screen makes game boot up, but it creates a serious degradation in performance, dropping the emulator speed to 30 frames per second.

- Disabling audio sync also forces the ROM to boot up, but there is no audio, but the framerate is a full 60/60

I believe another video capturing this is in order, at least, if need be.

**Comment by endrift** [comment]
Ok, I think I know how to fix this (assuming you're using the SDL audio driver). I'll hit this later today, probably.

**Comment by therandomizer85** [comment]
Actually, no, the drive I'm using is the default one, called QT Multimedia, is that a problem? I mean, it didn't even occur to me, but I never thought to use the SDL API option. Ah crap, this had better not be.....hold on.

**Comment by therandomizer85** [comment]
Ah dammit all to hell.....using the QT API was the problem, I didn't even think to use the SDL driver, with audio sync....


I KNEW this would happen-!

**Comment by endrift** [comment]
Moving to 0.3.0 since there's clearly stuff that needs to be fixed, but it's not as urgent as I thought it might be.

**Comment by therandomizer85** [comment]
Well, I still feel bad for wasting your time over such a foolish triviality of mine :/

**Comment by tony971** [comment]
Isn't SDL the default option?

**Comment by therandomizer85** [comment]
I don't know, for some reason, it wasn't, at least when I tried it, if it was, maybe I stupidly changed it, I don't know. I'll try a developer build next time and let you know. I still feel bad though.

**Comment by skullpanda86** [comment]
sadly im having a similar issue with the audio,ether being really scratchy upon boot or not having any audio with some games till the buffer size has been changed

**Comment by karasuhebi** [comment]
@skullpanda86 On 0.2.1 or a nightly?

**Comment by therandomizer85** [comment]
I no longer have this issue, it was due to the audio API, for some reason, and it was not initializing the ROM boot process, I changed the API to SDL and began to load fine. For @skullpanda86 , I recommend trying a different audio driver in the emulator settings.

**Comment by skullpanda86** [comment]
Sorry about the late response,um nightly svn 0.3-2329-0ecdc1a and yeah changing the the driver seemed to resolve the issue with games not booting properly,thanks :)

**Comment by therandomizer85** [comment]
No problem, though I am curious as to why changing the driver/API option fixes the issue, for some reason, the API in question wasn't set as the default option. Not an issue, just a minor discrepancy.

**Comment by endrift** [comment]
I've disabled the Qt Multimedia driver on Windows due it just being broken all the time. I hope to take a closer look in the future.

**Comment by endrift** [comment]
Closing since OP is no longer here and can't confirm my fix.
