### ISSUE TITLE
Shortcut bindings get applied regardless of user clicking OK or Cancel

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#480]
If you go under Tools > Settings, click on Shortcuts and set a binding for an action, it will get applied without the user clicking OK, or even if the user clicks on Cancel.

**OS:** Windows 10 Pro x64
**Build at time of writing:** 0.5.1 stable

**Comment by endrift** [comment]
This is due to the fact that the keybindings rebind immediately; there's no intermediate layer saying "here are the modifications". It will be difficult to fix this, but it is a valid usability concern.

**Comment by endrift** [comment]
Fixed in the input revamp branch.
