### ISSUE TITLE
[regression] Top Gear Rally vanishes graphics

### ISSUE THREAD

**Issue by sergiobenrocha2** [mgba-emu/mgba#485]
The graphics sporadically vanishes in Top Gear Rally, tested in last 0.5 branch and master, using GBA bios. Tested on Linux & Android

![top gear rally usa -161226-191225](https://cloud.githubusercontent.com/assets/5431285/21487372/86069044-cbae-11e6-9113-e82054f807c2.png)

![top gear rally usa -161226-191231](https://cloud.githubusercontent.com/assets/5431285/21487371/85f00522-cbae-11e6-8311-6c431928a29c.png)

**Comment by sergiobenrocha2** [comment]
Seems it's a regression, it was working fine in 0.4 branch.

**Comment by sergiobenrocha2** [comment]
It may be totally unrelated, but it's the same game and it was not crashing in pre 0.4.0

https://libretro.com/forums/showthread.php?t=7869

**Comment by endrift** [comment]
Broke in f34f45257a6c52ea2e96e8ba75e8f7bfe8d5e245.

**Comment by endrift** [comment]
Reverted in 2d02719fa57d4e4a33168955a8e0c34dfabc301a, but I don't remember what that commit fixed. Sigh.
