### ISSUE TITLE
Pocket Monsters - Ao (Japan) don't save in retroarch

### ISSUE THREAD

**Issue by wwark** [mgba-emu/mgba#486]
Hello,

I tried today to play Pocket Monsters - Ao (Japan) in retroarch but when i save the game. There is no file written on my disk and the save is not present if i restart the game.

I could manage to save with the save state but not with the normal state.

How to handle the save working maybe there is something i don't configure correctly.

Thanks for your help,
Wark.

**Comment by endrift** [comment]
what platform are you using retroarch on

**Comment by wwark** [comment]
i tried linux (64 bits) and android. The same issue for the two platforms.

**Comment by sergiobenrocha2** [comment]
I can confirm that, I can see this in the terminal:

```
RetroArch [libretro INFO] :: GB Memory: Savedata synced
```

**Comment by sergiobenrocha2** [comment]
I'm testing master branch, I think it's not saving any of game boy games

**Comment by wwark** [comment]
Many Thanks for the fix and the backport.

The core GB is really good and with this fix it will be used on libretro.
