### ISSUE TITLE
[Win] "Maximized" setting is not restored

### ISSUE THREAD

**Issue by lotharsm** [mgba-emu/mgba#487]
First, let me thank you for creating mGBA!

I have an issue with the window size of mGBA running on Windows 10. When you maximize the window, close mGBA and start it again, the "maximized" setting seems to be not restored properly. The window *seems* to be maximized, but it isn't (you can maximize the window again).

Sometimes, the window is shifted upwards (like it's too big for the screen resolution) which make it hard to use the menu settings. You have to resize the window to make all menus accessible again.

I used mGBA 0.5.2, but the issue is also present in 0.5.1. I try to find a version that is not affected later today to check if it's a regression.

**Comment by endrift** [comment]
I believe I fixed this in master. Can you recheck?

**Comment by lotharsm** [comment]
Unfortunately, I can still replicate with the current master.
