### ISSUE TITLE
Multiplayer shortcut profiles

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#49]
Since the button mappings are identical for two matching controllers, shortcuts could apply to any multiplayer window. Currently, shortcuts are applied to the window in focus. It would better to have the controller shortcuts binded to the window that is using the controller for its primary controls.

**Comment by tony971** [comment]
Basically, force controller shortcuts to be used in the same window that the controller is mapped to. If window two uses controller two, then whenever controller two uses a shortcut, it should apply to window two, regardless of which window is focused.

**Comment by therandomizer85** [comment]
I love how people don't reply to the issues we report.

**Comment by tony971** [comment]
Let's not make passive aggressive demands. Endrift owes us nothing. We don't pay for mGBA and she's invested her own time and capital into the project. We have not.

**Comment by endrift** [comment]
I don't have infinite time, sorry. mGBA is already progressing slower than I want it to. I don't have shortcut profiles at ALL yet, so multiplayer ones are blocked on having those be implemented.

**Comment by taisel** [comment]
Yeah... was gonna say this isn't non-free software. Endrift's not on a payroll for this.

**Comment by endrift** [comment]
Actually, come to think of it, I'm pretty sure that this is already how shortcuts work. If it's not, that's a serious bug that I need to fix.

**Comment by endrift** [comment]
Confirmed that the events are being sent to the active window and not the controller's window.

**Comment by endrift** [comment]
Fixed in 75fb2548bbb6dea49e6d1040e3b59d76f5548fa6.
