### ISSUE TITLE
Slow startup times due to parsing the nointro.dat file

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#490]
As of the 2015-12-28 build, mGBA has been taking longer than previous versions to start up. This is due to it having to parse the nointro.dat file introduced in bbe10619efaf5c691e57747101029b3d194add3b.

If one removes or renamed the nointro.dat file, mGBA goes back to starting up as quickly as it did previous to this change.

Thanks to /u/Im_Special who pointed this out in a Reddit thread that started me on this endeavor:
https://www.reddit.com/r/emulation/comments/5l969t/mgba_052_bugfix_version_released/dburfz2/

**Comment by rootfather** [comment]
I can confirm that for mGBA 0.5.2 on my Windows 10 laptop.

With nointro.dat, mGBA takes about 20 seconds to load on my low-end laptop, while it opens in under 3 seconds with nointro.dat renamed.

**Comment by endrift** [comment]
I'm going to look into parsing the file once and replacing it with a sqlite3 database. Not sure how well that will work, and it'll add another (small) dependency.

**Comment by endrift** [comment]
Fixed in 9e7d2edd4f15e3e8d5c2fe7c078aba4538545285
