### ISSUE TITLE
[Enhancement] Better controller hotplugging support

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#493]
As mentioned in Issue #92, you currently need to go to Tools > Settings > Controller every time you plug a controller in if you want mGBA to detect it. It would be nice if mGBA could automatically detect hotplugged controllers without the need for user interaction.

**Comment by endrift** [comment]
This is a bit difficult because it means it would need to be constantly polling--it doesn't have an event that can get called when a controller is plugged in, due to the hacky way it integrates with SDL. I could have it check every second, but that may break things. It would require testing.

**Comment by endrift** [comment]
Partially fixed in 2da3d3e6ba282d437c69a8d80b0a2e0f46214a39. It will now detect controllers with 50ms of them being plugged in, but it will only map them properly if the controller has already been configured (that is to say, if you start with it plugged in, unplug it, and replug it)

**Comment by endrift** [comment]
Finished in d2bf16b8723f69224cdeaa20699c61144df66a66.

**Comment by karasuhebi** [comment]
Works like a charm. Thanks @endrift!
