### ISSUE TITLE
Question : Android version ?

### ISSUE THREAD

**Issue by zminhquanz** [mgba-emu/mgba#494]
In the past , i have a question for a android build , but it's postponed , no one else to announcement this ( not about using RetroArch) , so i have to ask a question when android version it's released

**Comment by zminhquanz** [comment]
#279

**Comment by endrift** [comment]
It is being worked on a little bit, but it is not a priority for anyone, so it languishes.

Please do not open issues that are just questions on the issue tracker. That's what the forums are for.

**Comment by itsarjunsinh** [comment]
Hi @endrift. As there has been no (public) progress on the Android port, I'd like to give it a shot. Before I start working I'd like to know if there is a particular roadblock that has been delaying the Android port. I don't have any past experience with working on emulators so any info will be helpful.
