### ISSUE TITLE
Gundam Seed Destiny end game bug

### ISSUE THREAD

**Issue by montiblanc** [mgba-emu/mgba#498]
At the end of main mode, at the credits, i'm supposed to press start & spam "A" for some graphical effects & bonus points; this does not happen/work on retroarch mGBA core.

**Comment by endrift** [comment]
Can you please upload a savestate?

**Comment by montiblanc** [comment]
a save state of the end or any save state? i would upload what i have, but when i drag here, site says "We don’t support that file type"; the save state is an srm file & i cant find another attach option.

**Comment by endrift** [comment]
A savestate near the end, right before the credits roll. Also, just zip the srm file and it'll work.

**Comment by montiblanc** [comment]
[Gundam Seed Destiny.zip](https://github.com/mgba-emu/mgba/files/752810/Gundam.Seed.Destiny.zip)

credits started rolling sorry; doesn't matter though, it supposed to work anytime like i remember.

**Comment by endrift** [comment]
So...I can't find any evidence that that "press start and spam A" thing even exists in the game apart from a (downvoted) bit on GameFAQs. Are you sure this works on console?

**Comment by endrift** [comment]
Closing due to lack of response.
