### ISSUE TITLE
Shader not saved on Windows

### ISSUE THREAD

**Issue by Catarax** [mgba-emu/mgba#499]
0.5.2 stable release

Everytime I load a XBR shader, when I re-launch the exe, it disappear, have to reload it manually.
Tried as admin also.

**Comment by endrift** [comment]
This is a known issue, although apparently there wasn't an issue for it open.

**Comment by endrift** [comment]
Fixed in 2f14f58911539fd67228c9113665c5df26061154.

**Comment by Catarax** [comment]
Thanks a lot for having a look on it!
