### ISSUE TITLE
Loading patch feature doesn't work

### ISSUE THREAD

**Issue by CarterLi** [mgba-emu/mgba#50]
1. Open a game
2. File => Load patch... then choose an ips file

Game rebooted as expected, but nothing changed. Did I miss anything?
mGBA 0.3-2231-262cbf0 on OSX 10.10.3

**Comment by endrift** [comment]
.ups seems to be working for me. I'm not sure I have any .ips files floating around to test at the moment. Have you tried other games and/or other patches?

**Comment by endrift** [comment]
This is likely a regression from when I futzed with ROM loading and yanking.

**Comment by CarterLi** [comment]
Tested patch: http://forums.therockmanexezone.com/topic/8886349/1/ with rom 2253 - Rockman EXE 6 - Dennoujuu Faltzer (J).gba
Same patch works on VBA-M

**Comment by endrift** [comment]
I've verified that several patches that used to work are failing in the 0.2 branch as well.

**Comment by CarterLi** [comment]
Thank you.
Another request: could you add a feature that loads the patch automatically which has the same filename with the running rom? An option in settings to enable / disable this feature is preferred

**Comment by endrift** [comment]
I can manage that, but please post that in a separate issue report so I can keep track of it separately.

**Comment by CarterLi** [comment]
Done: #51

**Comment by endrift** [comment]
This wasn't a regression, I was just testing the wrong patch for this ROM. Fixed in 0aef1bc6df48a302284fee37b8834d8aec09b379 regardless.
