### ISSUE TITLE
GBC/GBA Games won't load from command line (Windows 0.5.2)

### ISSUE THREAD

**Issue by kencinder** [mgba-emu/mgba#501]
Simply put, trying to load a ROM from the command line works fine with GB games, however GBC and GBA games do not.
mGBA loads up as if it was executed with no arguments. Games load fine from the UI File Menu. Zipped or not doesn't matter.

**Comment by kencinder** [comment]
And I feel like an idiot...issue was on my end, but the fact it presented itself on multiple machines made it appear otherwise. Closing.

**Comment by endrift** [comment]
Don't worry about it, it happens to all of us 😄
