### ISSUE TITLE
Logitech F310 gamepad can not be configured/used

### ISSUE THREAD

**Issue by Nicholas-Steel** [mgba-emu/mgba#502]
Windows 10 Pro AU x64
MGBA v0.5.2

The software simply doesn't recognize the gamepad. I can't rebind the buttons nor do any of the buttons do anything when using the default gamepad configuration. I have tried both XInput and DirectInput modes (restarting emulator after each change.

The UI is also really clunky, there seems to be no indication of which one you're currently attempting to rebind and no indication of which are treated as analog and which aren't.

Edit: Oh https://github.com/mgba-emu/mgba/issues/452

**Comment by CharlesCorrin** [comment]
I have that exact gamepad and mine works fine in mgba. The DPad included. I don't need to use the mode button at all.

**Comment by Nicholas-Steel** [comment]
As noted in the bug report I linked to in the original post, it will be re-implemented in v0.6.0 so it isun't too surprising if the functionality has already been restored in the source code.
