### ISSUE TITLE
Sonic Advance 3 - vertical line after final boss

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#503]
When you beat the final boss without going to the extra zone, the following scene shows one of the light effects getting stuck for a bit.

![sonic advance 3-0](https://cloud.githubusercontent.com/assets/6880539/22180184/279d04e6-e01e-11e6-8dd8-96c82d2d7d27.png)

I've been checking other emulators, this seems to be a common issue. The only case I've seen where it doesn't happen is the Japanese Wii U VC.

**Comment by endrift** [comment]
Does this still happen?

**Comment by SuperrSonic** [comment]
Yes.

**Comment by endrift** [comment]
I finally managed to reproduce this. It looks like it's probably _not_ a graphical glitch; somehow the game leaves it in this bad state that draws this way.

**Comment by SuperrSonic** [comment]
It looks like eaee4228bad46a23f2f6805437d239d2b41e5373 fixes this issue!

VBA-m and most of the other emulators have this issue, even injecting SA3 into SA2 for WiiU VC.
The 'gbarunner2' loader for DS has it too, despite relying less on emulation. Surprisingly, gpsp doesn't have it.

**Comment by endrift** [comment]
Oh excellent! That's for keeping track of this.
