### ISSUE TITLE
mGBA Vita port crashes upon loading TLoZ: The Minish Cap (PAL)

### ISSUE THREAD

**Issue by Doigt** [mgba-emu/mgba#505]
Upon attempting to load The Legend of Zelda - The Minish Cap PAL/EU version, the Vita port of mGBA crashes. The same file loads fine on the same version of the emulator running on Windows 7 x64. If any additional details are needed, let me know!

![2017-01-25-083120](https://cloud.githubusercontent.com/assets/5321699/22281753/d8ebf088-e2d8-11e6-9f15-111b80ae8bdf.jpg)

Referenced dump file, if it helps to identify the issue: https://dl.dropboxusercontent.com/u/7046011/0x00008b2cd9.zip

**Comment by endrift** [comment]
Which version of mGBA are you using? 0.5.2, a nightly, and old stable?

**Comment by ml-** [comment]
I can confirm this crash with the latest nightly version (2017-01-25).
Rom MD5: 2af78edbe244b5de44471368ae2b6f0b

**Comment by endrift** [comment]
Confirmed failing. It looks like something's wrong with the configuration system.
