### ISSUE TITLE
Games not booting when external BIOS enabled

### ISSUE THREAD

**Issue by CharlesCorrin** [mgba-emu/mgba#507]
Starting with build 8bcd987 Windows version, GBA games won't boot if you give the emulator an official external BIOS and enable it. Disabling the BIOS allows games to boot. It worked fine on build 54b889d.

My PC is a Windows 10 64-bit.

**Comment by endrift** [comment]
Regressed in 37f5feb713d5768f2bf5405e5a9db8765248efc2.

**Comment by endrift** [comment]
I'm going to revert the affecting changes for now, since they don't really add much but are incredibly risky changes anyway.

**Comment by endrift** [comment]
Fixed in 1e7a62fbb33a0063c30a2bd597c243ad3e4e1c22 by reverting the changes that broke it.
