### ISSUE TITLE
Regression in how timers work in master (compared to 0.5)

### ISSUE THREAD

**Issue by fl4shk** [mgba-emu/mgba#519]
Here is also a commit from my project where I discovered the issue:  https://github.com/fl4shk/sherwin_adventure/tree/ef45fb171c96709fa7cb0ba4cdd013ff4a18f87c

The following C code works properly in 0.5, but not in master:

```
INLINE void profile_start()
{
    REG_TM2D= 0;    REG_TM3D= 0;
    REG_TM2CNT= 0;  REG_TM3CNT= 0;
    REG_TM3CNT= TM_ENABLE | TM_CASCADE;
    REG_TM2CNT= TM_ENABLE;
}

INLINE u32 profile_stop()
{
   REG_TM2CNT= 0;
   return (REG_TM3D<<16)|REG_TM2D;
}

volatile u32 temp;
void some_func()
{
  profile_start();
  temp = profile_stop();
}
```

After calling some_func(), the "temp" variable should be a very low number (as it is in 0.5) , but, in master, temp is in the thousands (my tests show numbers  like this:  26738, 26702, 26629, 26629, 26629, 26629, 26629, 26629, 26629, 26629, 26629, 26629, 26116, 26116, 26116, 26116, 26116, 26116, 26116, 25703).

The value I expected should have been less than 100.

**Comment by endrift** [comment]
if you remove the REG_TM2CNT= 0; from profile_stop(), does it fix things?

**Comment by fl4shk** [comment]
Yes, it fixes things.

**Comment by endrift** [comment]
Ok, then try removing these lines, putting back the stuff in profile_stop(), and recompiling: https://github.com/mgba-emu/mgba/blob/fa884d071ecaa3e05ff20b45a67bf9500dd3d6b6/src/gba/timer.c#L135-L137

**Comment by fl4shk** [comment]
It does indeed work with that change made.
