### ISSUE TITLE
3DS crashes with freshly saved config

### ISSUE THREAD

**Issue by Pitel** [mgba-emu/mgba#521]
Version: daily build from 9. February 2007

1. Delete `mGBA` directory.
2. Start mGBA with (probably) any game.
3. Press `Y` to switch screen size.
4. Press `X` to open menu and `Exit game`, and kill mGBA.
5. Repeat steps 2 and 4, everything works as expected.
6. Repeat steps 2 and 4, but before exiting, go to config and save it, the exit and kill.
7. Do step 2, crash.

This is the diff between default and saved config.
```diff
 [ports.3ds]
 screenMode=4
+useBios=1
+filterMode=2
+darkenMode=0
 lastDirectory=/roms/gba/
+frameskip=0
+fpsCounter=0
```

It's not problem with `fpsCounter`, I tried to enable that by manual edit, and it still works. Unfortunately, I don't have time right now to test each of these parameters.

I also noticed there is some log file in `mGBA` directory, but it's always empty.

**Comment by endrift** [comment]
Possibly related to #516

**Comment by endrift** [comment]
Does this still crash?

**Comment by Pitel** [comment]
Fixed! :tada:
