### ISSUE TITLE
[Feature request] Add support for translations in libretro-mgba

### ISSUE THREAD

**Issue by lotharsm** [mgba-emu/mgba#522]
Currently, RetroArch doesn't have it's own API for translating the Core options.

Is it possible to implement it on the Core level?

**Comment by endrift** [comment]
Looks like this is possible using the RETRO_ENVIRONMENT_GET_LANGUAGE environment option.

**Comment by endrift** [comment]
I believe this is handled in `libretro_core_options_intl.h` now.
