### ISSUE TITLE
Window losing focus unpauses game while frame advancing

### ISSUE THREAD

**Issue by Prof9** [mgba-emu/mgba#524]
While frame advancing (Ctrl+N), if the mGBA window loses focus or you open one of the toolbar menus, the game unpauses. The Emulation -> Pause option stays enabled. This occurs regardless of whether emulation was paused prior to frame advancing.

An alternative way to trigger this is to hold Tab (fast-forward) for a bit; this will also unpause the game (which makes sense), but the Pause option stays enabled.

Using the latest nightly (17cfee0) on Windows 10 x64.

**Comment by endrift** [comment]
Yeah, there are a bunch of bugs about this that I need to fix.

**Comment by endrift** [comment]
Fixed in fb7715f6ac8e3e31869ceeef92ab9dd2ae7546b4.
