### ISSUE TITLE
Dual Control and Auto Pause addon

### ISSUE THREAD

**Issue by Vortaka** [mgba-emu/mgba#528]
Hi!  Just tried the emulator today and it's great!  Fast and efficient!  Good work!  These are gliches not bugs...  Haven't found one yet!  Oh, and the xbr shader is nice!

1- I think this was a glitch...  I tried to link the "fast forward" shortcut to my joystick but the only way it worked was to "clean" the keyboard (TAB).  But doing the link for the pause button worked like a charm...  Weird!

2- You should add an option to auto pause the emulator when not in foreground (so when I'm not using it).  Always needing to press a button or CTRL-P is (very) slightly annoying!  You know, sometimes things happens...  Door bells, food ready, phone call, etc...

Keep up the good work!!!

**Comment by endrift** [comment]
1. I've never seen that before. That's very strange, as it works fine for me.
2. This feature already exists. Try looking over the settings again.

**Comment by Vortaka** [comment]
1. It's very weird then!  (But not THAT important!)
2. My bad...  That's what happens when you don't give yourself enough time to check everything!
Thank you!
