### ISSUE TITLE
Rewind feature not working with GB/GBC games

### ISSUE THREAD

**Issue by rootfather** [mgba-emu/mgba#529]
## Description

While rewinding works properly with GBA games, this feature does not work with GB/GBC games. Instead, it will crash the emulated software and eventually mGBA itself.

### Expected behavior

Rewinding for GB/GBC games should work as expected and as it currently does for GBA games. As soon as you hit the rewind hotkey (default: ~), the gameplay should rewind the number of frames you selected in the settings.

### Actual behavior

For GBA games, it works as expected. However, for GB/GBC, the emulated software will crash as soon as you hit the rewind hotkey. In most cases, you will hear the ingame sound looping or hanging at one note, and a few seconds later or if you try to click anything inside the Qt GUI, mGBA will stop responding. Sometimes, ingame graphics gets corrupted before mGBA crashes.

### Steps to reproduce the bug
Reproducing this is very easy. I used the following ROMs for testing:
_(for the record, yes, I own original cartridges of those games)_

- Pokemon - Saphir-Edition (Germany) (GBA)
- Pokemon - Kristall-Edition (Germany) (GBC)
- Pokemon - Rote Edition (Germany) (DMG/GB)

Those ROMs are not corrupted and verified against the No-Intro database.

1. Load a ROM either for GB or GBC
2. Enable the rewinding feature
3. Run the emulation
4. Hit the "Rewind" hotkey

### Version/Commit
I did those test with commit ba3b068df4a8fcb34c66b1bc5725a205a36d5807, but it was broken in previous versions too. I was unable to find a working release, otherwise I would have done a bisect.

### Environment information

- OS: Windows 10, x64
- Compiler: GCC 6.3.0 via MSYS2 (x86_64-w64-mingw32)

**Comment by endrift** [comment]
Fixed in 40ff1ea0c4dc514817d81dc7b2bd56659f4345dd.
