### ISSUE TITLE
Golden Sun The Lost Age loading bad memory

### ISSUE THREAD

**Issue by purpasmart96** [mgba-emu/mgba#53]
This results in freezing and huge frame rate drops while the music plays normally, this was never a problem in 2.1 and builds before that.

I should also note this has only happened once so it could be something very minor.

GAME ERROR:	Bad memory Load16: 0xE55EC002
GAME ERROR:	Bad memory Load32: 0xE55EC00E
GAME ERROR:	Bad memory Load32: 0x589A589E
GAME ERROR:	Bad memory Store32: 0xE55EC012
GAME ERROR:	Bad memory Store8: 0xE55EC006
GAME ERROR:	Bad memory Store8: 0xE55EC017
GAME ERROR:	Bad memory Store8: 0xE55EC016
GAME ERROR:	Bad memory Store16: 0xE55EC004
GAME ERROR:	Bad BIOS Load8: 0x0000001B
GAME ERROR:	Bad BIOS Load32: 0x00000254
GAME ERROR:	Bad memory Load32: 0xE55EC00E
GAME ERROR:	Bad memory Load16: 0xE55EC002
GAME ERROR:	Bad memory Load32: 0xE55EC00E
GAME ERROR:	Bad memory Load32: 0x589A589E
GAME ERROR:	Bad memory Store32: 0xE55EC012
GAME ERROR:	Bad memory Store8: 0xE55EC006
GAME ERROR:	Bad memory Store8: 0xE55EC017
GAME ERROR:	Bad memory Store8: 0xE55EC016
GAME ERROR:	Bad memory Store16: 0xE55EC004
GAME ERROR:	Bad BIOS Load8: 0x0000001B
GAME ERROR:	Bad BIOS Load32: 0x00000258

**Comment by endrift** [comment]
Which build are you using? I don't seem to be able to reproduce this on latest master (bddebef90b5726534b04e921c2f19c2059c343ea). Where in the game are you getting this? Can you take a savestate?

**Comment by purpasmart96** [comment]
This was on the latest master, I haven't been able to reproduce the problem so far as of now.
