### ISSUE TITLE
Crackling sound / static noise in Metroid games on N3DS

### ISSUE THREAD

**Issue by accolon** [mgba-emu/mgba#530]
I'm running mGBA 0.5.2 on my N3DS (installed as CIA) and I'm experiencing crackling sound while playing the Metroid Games (both Fusion and Zero Mission, EU versions). I tried a few other games, but could not find the issue there. I could not reproduce the issue with the macOS version of mGBA.

With Fusion, the music often starts to crackle when you switch rooms. Pressing START to view the map screen and going back usually fixes the issue until it comes back after a while.

With Zero Mission, the issue mostly affects the music in save rooms.

It doesn't matter whether I use a GBA BIOS or not. I also tried a current nightly build of the 3DS mGBA, but it crashes when loading a ROM.

**Comment by endrift** [comment]
The game is probably just not running full speed. Also, the crash should be fixed by now.
