### ISSUE TITLE
Writing to unknown register

### ISSUE THREAD

**Issue by wesleydecock** [mgba-emu/mgba#531]
made a save state from a game, it froze up, can't do anything in-game now. So basically I lost all progress.
The logs window (stub level) says "[STUB] GB I/O:	Writing to unknown register FF15:00"

**Comment by endrift** [comment]
The stub register write is unrelated to savestates not working, most likely.

**Comment by endrift** [comment]
Probably fixed by 40ff1ea0c4dc514817d81dc7b2bd56659f4345dd. Try tomorrow's nightly and let me know.
