### ISSUE TITLE
Minor layer issue in Kirby & The Amazing Mirror intro

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#532]
After the intro stage a small cutscene plays:
![test](https://cloud.githubusercontent.com/assets/6880539/23312742/3186d94a-fa91-11e6-8512-399d4fa98051.gif)
Taken from VBA-M.

But in mGBA the star graphic behind the mirror can be seen before the mirror breaks.
![kirby and the amazing mirrors3](https://cloud.githubusercontent.com/assets/6880539/23313387/d96f48f2-fa93-11e6-8fd6-f29a34a027e5.png)

State before the cutscene.
![kirby and the amazing mirrors1](https://cloud.githubusercontent.com/assets/6880539/23313348/b843b960-fa93-11e6-92e6-ed841869dbda.png)

**Comment by vaguerant** [comment]
Per the ```category:needs hw testing``` tag, I tried this out (on a DS Lite). I can confirm the correct behavior is as shown in SuperrSonic's GIF of VBA-M. In mGBA, part of the mirror becomes translucent during the flashing screen effects, making the background's archway clearly visible where it should be blocked by the (opaque) mirror.

To supplement SuperrSonic's screenshot of the error in mGBA, here's a GIF of mGBA's behavior.
![kirbyerrormgba](https://user-images.githubusercontent.com/5259025/30534911-8c0fa7ca-9ca3-11e7-948b-0f99ce8067a2.gif)

**Comment by endrift** [comment]
Can you confirm that the mirror and dark Meta Knight are brightened during the flash on hardware, and not just plainly visible during? Fixing that could be a major pain for me, and everything I know about the GBA's video hardware tells me they should be.

**Comment by endrift** [comment]
...that commit message is wrong.

Regardless, I'm pretty sure that hack is still wrong, so let me know if you find anything else.
