### ISSUE TITLE
[Windows 0.5.2] Crash when saving controller settings

### ISSUE THREAD

**Issue by voltagex** [mgba-emu/mgba#534]
After fighting with mGBA to map my control settings, it crashed while trying to save.

I've got an Xbox One wireless adapter with one paired controller.

![image](https://cloud.githubusercontent.com/assets/159567/23584962/f411776a-01c4-11e7-99fd-a8e9e5b97fdb.png)

I have a minidump but I'm not sure how much help it would be - it's 222MB uncompressed so it'll have to go on Mega or similar.

**Comment by endrift** [comment]
Does this still reproduce?

**Comment by endrift** [comment]
Closing due to lack of reply.
