### ISSUE TITLE
Image flipped horizontally when using WiiU shader

### ISSUE THREAD

**Issue by rootfather** [mgba-emu/mgba#536]
When using the WiiU shader, the image is horizontally flipped as seen on the attached screenshot. It seems that this issue is specific to the Intel HD graphics driver, because I don't remember seeing this behavior on my old AMD Radeon based laptop.

The WiiU shader is the only affected shader, the other ones work perfectly.

OS: Windows 10, build 14393
mGBA: 40ff1ea0c4dc514817d81dc7b2bd56659f4345dd, nightly
Graphics hardware: Intel HD Graphics 620 (Intel Core i5 7th Gen)

![wiiu shader flipped image](https://cloud.githubusercontent.com/assets/11882577/23831213/e359aec6-071c-11e7-956c-52ac53d4fea6.PNG)

**Comment by endrift** [comment]
This means the shader wasn't compiled correctly, so there's a bug in the shader that's causing it to work on some shader compilers and not others. cc @Prof9 who wrote it.

**Comment by rootfather** [comment]
Yeah, seems that the Intel compiler is way more sensitive than the compilers from other vendors, I have similar problems with some retroarch shaders. Hopefully they will be some driver updates in the future...

**Comment by Prof9** [comment]
I'm guessing I used the wrong OpenGL version. Looking at [gles2.c](https://github.com/mgba-emu/mgba/blob/master/src/platform/opengl/gles2.c) it looks like mGBA uses OpenGL ES 2.0 (#version 100) or OpenGL 2.1 (#version 120) depending on the supported OpenGL version (please correct me if I'm wrong), whereas I was using some features from OpenGL 3.0+. It worked fine on my machine, but I suppose the shader compiler for my hardware wasn't being strict enough with OpenGL version checking.

Here's a version that passes glslangValidator and should work on OpenGL ES 2.0/OpenGL 2.1. Can you try unpacking this into the `shaders` folder and see if this works? If so, I'll submit a PR.

[wiiu.shader.zip](https://github.com/mgba-emu/mgba/files/837315/wiiu.shader.zip)

**Comment by rootfather** [comment]
Thanks @Prof9, the new shader files fix the issue for me.

**Comment by Prof9** [comment]
Thanks! This was my first foray into GLSL, so apologies for the error.

As a side node, the Wii U shader is based on the GBA VC one, so it probably won't result in an accurate representation for GB/GBC games. Maybe I'll look into producing similar shaders for those based on the 3DS VC colors. Although there's nothing stopping you from using this one, of course.

**Comment by rootfather** [comment]
No need to apologize. Compared to AMD, it seems that the Intel OpenGL driver is a lot more sensitive when it comes to the syntax and stuff. I have the same issues with the retroarch shaders - all GLSL shaders work perfectly on my old AMD laptop, but a whole bunch refuses to compile on my Intel HD 620 system.

**Comment by endrift** [comment]
@Prof9 You want me to merge them myself or do you want to file a PR?
