### ISSUE TITLE
James Pond - Codename Robocod black screen

### ISSUE THREAD

**Issue by CromlechDE** [mgba-emu/mgba#539]
After selecting the language the screen goes black and just music playing.

Retroarch 1.5.0
Win 7 64bit

**Comment by endrift** [comment]
Can confirm.

**Comment by endrift** [comment]
Gets stuck at 0800CB48.

**Comment by endrift** [comment]
The loop condition at that address can only pass if the interrupt fires *after* the value of scanline 160 is read from the VCOUNT register...which isn't possible in mGBA and is only possible in exceedingly narrow cases on hardware. Easy fix...to the game. Not sure how to fix the emulator. ***grumbles***
