### ISSUE TITLE
Get building with Visual Studio 2015

### ISSUE THREAD

**Issue by endrift** [mgba-emu/mgba#54]
Left to do:
- [x] Get replacement for `getopt` (possibly [from Napoleon-OS/libc](https://github.com/Napoleon-OS/libc/blob/master/src/misc/getopt_long.c)).
- [x] Port `vfs-dirent.c` to MSVC.
- [x] Get extern symbols working.
- [x] Figure out how to handle dependencies.
- [x] Add AppVeyor integration.

**Comment by karasuhebi** [comment]
Yay, I should be able to build mGBA soon :D Too bad I have 2013 so I'll probably need to upgrade XD

**Comment by endrift** [comment]
I did post instructions for setting up a self-contained build system using MSYS2 to the readme last night (11098b3). You don't get VS' debugger, but you get a functional Windows build still!

**Comment by endrift** [comment]
A bit late in the game for this. I'll try to do it early in 0.4.

**Comment by endrift** [comment]
VDir support added in 3a51c59768a0e4bbba9dc516b0554eb520474c05.

**Comment by endrift** [comment]
getopt and general build fixes merged in #257!

**Comment by endrift** [comment]
VideoView.cpp fails to build in MSVC due to the use of C99isms. I'll fix that in the next version. Beyond that, managing dependencies is still an issue.

**Comment by endrift** [comment]
cc @waddlesplash, how do you think I should handle dependencies for MSVC, specifically ImageMagick and ffmpeg being the biggest obstacles?

**Comment by rootfather** [comment]
I would include the necessary header files for all dependencies in the repository itself. Would be the best option in my opinion. But let's what what @waddlesplash says.

**Comment by waddlesplash** [comment]
I guess my recommendation would be to add some sort of script that can download binaries of all the dependencies.

For FFmpeg: FFmpeg itself doesn't distribute binaries, but their official website sends you to to the [Zeranoe builds](https://ffmpeg.zeranoe.com/builds/) (and everybody under the sun who uses FFmpeg on Windows does use those). There are static+devel versions available, so that should work.

ImageMagick: If you have a custom ImageMagick build, maybe throw it up on the ImageMagick fork on @mgba-emu as a release, and download that as well? I don't know, I don't have very much experience with ImageMagick.

**Comment by waddlesplash** [comment]
Er, scratch the FFmpeg comment; it looks like Zeranoe doesn't provide MSVC builds anymore :/ (or if they do I can't find them.) Drat.

**Comment by endrift** [comment]
I could, in theory, create a bundle of the prebuilts and toss attach them to the dependencies repo, but the problem there is that now I have to compile them for MSVC, and also figure out how to get CMake to properly detect them in the absence of pkg-config.

**Comment by waddlesplash** [comment]
Most things that use pkg-config also support passing something like `-DTHING_LIBRARY=...` and `-DTHING_INCLUDE=...` to CMake args. That's how I'm building with SDL2 at present.

**Comment by endrift** [comment]
Seems like a pain to not autodetect them.

**Comment by waddlesplash** [comment]
Yep, it is, but I'm not sure of a better method, because Windows sux. :/

**Comment by endrift** [comment]
Now you see why there's a checkbox for it. I'm thinking maybe you toss all of the libs and headers into a directory structure and it automatically searches that if it finds it?

**Comment by nico-abram** [comment]
Has that merged pull request fixed external symbols?
Aside: Shoud this issue still be about vs2015, or should it be changed to target 2017 or 2019?

**Comment by endrift** [comment]
It should yes. And I'm not sure if this needs to be changed. 2015 is new enough, I think.

**Comment by endrift** [comment]
Oh hey it works now, with `vcpkg` instructions added in the README. I'll try to get appveyor stuff set up sometime soon.

**Comment by endrift** [comment]
AppVeyor integration added in 8cdd8497ba6f7ac6ded3b8842fe31824eff34863. This completes this task.
