### ISSUE TITLE
crash on New 3dS

### ISSUE THREAD

**Issue by Klauserus** [mgba-emu/mgba#542]
The Problem is, mGBA crashed when i try to load a Game (matter what). The .3dsx or cia starts correct. FileBrowser works, but it show the loading screen...and crash. The System show a Message: "An Error Has Occurred...save lost...system restart."

My System Settings:
- Firmware 11.1 E
- I try it on SysNand and Emunand (same Problem)
- 32 GB micro SD Card Samsung
- with bios file and without
- I try different Versions of mGBA (official 5.2 release, Nightly from 01-27-17 and other) same error

![img_20170312_195523](https://cloud.githubusercontent.com/assets/26491758/24061964/e29ca678-0b59-11e7-9410-1f6d7906c319.JPG)

I cant upload a zip file with dumps. Github error?!

**Comment by endrift** [comment]
I need to know the EXACT version a dump is from, or else it's worthless.

**Comment by Klauserus** [comment]
Sorry, i dont know what you mean. The Dump is from a New 3ds make it with luma3ds v6.6 but i cant upload the file, Github does not leave me

**Comment by endrift** [comment]
The exact version of mGBA. Which build.

**Comment by Klauserus** [comment]
ah ok. thanks. I try so many versions. i make a new picture with mgba Version: mGBA-nightly-2017-03-17-3ds-15b4df3b2b021e9fa08f179316c4945ea0125e7a

![crash](https://cloud.githubusercontent.com/assets/26491758/24063698/085b2888-0b61-11e7-829e-614655dbba64.jpg)

**Comment by endrift** [comment]
I fixed an issue with BIOS loading just now. Let me know if the next nightly (in about 12 hours) fixes this.

**Comment by Klauserus** [comment]
Awsome! Thank You. It runs whithout a crash 👍
