### ISSUE TITLE
Small but noticiable framedrops every 2-3 seconds

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#545]
The 0.5.2 build doesn't suffer this shuttering, but the latest development builds does. Neither enabling nor disabling audio/video sync affect this bug.

I also notice that increasing the audio buffer worsen this problem.

**Comment by rootfather** [comment]
I have the same issue with the latest development. I'm currently testing it a bit and then write a comprehensive bug report.

**Comment by rootfather** [comment]
@RafaelTrepaUnCarballo Can you please share some more details about your system? CPU, graphics hardware, the frequency of your monitor, driver versions...

**Comment by endrift** [comment]
This fixed it for @rootfather, lmk if it doesn't fix it for you.
