### ISSUE TITLE
Quick load doesn't work sometimes

### ISSUE THREAD

**Issue by CarterLi** [mgba-emu/mgba#55]
I found this when playing Boktal 3. I can't always reproduce it, but it happened for several times.
![2069 - shin bokura no taiyou gyakushuu no sabata j ss1](https://cloud.githubusercontent.com/assets/6134068/8457325/4ce3e36a-2043-11e5-9350-7df56e3054bd.jpg)
For the quick save uploaded above ( I changed the file extension to jpg ), the emulator plays only 1 frame after you load it, then returns back to the old state immediately. If you pause the emulator, you will see the screenshot shown as the image. It goes away after you unpause the emulator.

0.3-2251-bddebef on OSX 10.10.4

**Comment by endrift** [comment]
WARN:	Savestate is corrupted: audio channel 4 register is negative

Ah geez this one is going to be rough to fix.

(btw, savestates are embedded in PNGs, so rename to .png not .jpg)

**Comment by endrift** [comment]
Vaguely fixed in b3ea09e1500072f97ad15c93ba7c90f418742afc, but the savestate that was made is in kind of a bad state and I'm curious how it got into that state. 5afa24c6568e7fc1187cdf7e3ffc0f45e4b0c7d4 fixes showing the "load failed" message that was supposed to show up, but wasn't.
