### ISSUE TITLE
[Win32/mayor?] Video synchronsation is currently completely broken

### ISSUE THREAD

**Issue by rootfather** [mgba-emu/mgba#556]
My system:
Intel Core i5 7200U with Intel HD Graphics 620, no dedicated graphics solution
Windows 10 14393.969
All drivers up to date.

In the current nightlies, the video synchronsation seems to be severely broken which completely breaks the "Sync to video" option and causes severe framedrops with "Sync to audio" that only get slightly better with a buffer size of 512.

In the following test cases, I use a stock mGBA configuration file. Test ROM was the GBC game "Monsters Inc" because it has a nice scroller right at the beginning (and I own the original). GB, GBC and GBA games are all affected.

## mGBA 0.5.2
**Synchronize to audio:** Smooth scrolling, no audio stuttering. Works as expected.

**Synchronize to video:** Smooth scrolling, slight audio stuttering which I think is to be expected unless I increase the audio buffer size. Takes about 3 seconds until emulation starts.

## mGBA nightly [aff1486ec5fe3185de59d20665c4042b715853ae]
**Synchronize to audio:** Severe framedrops and video stuttering. Smooth audio. Setting the audio buffer to 512 helps a bit, but there are still some frame drops. **_Definately a regression since 0.5.2_**.

**Synchronize to video:** Emulation won't start. mGBA itself is responsive, but the game doesn't even start. In the title bar, I get some random FPS values between 2 and 60. Restarting the emulator won't help. Only way to start the emulation is to untick the video synchronisation and restart the emulation by reloading the ROM file.

This bug was first reported in #545, but I don't know if the creator has the same issues with the broken video synchronisation.

My build environment is currently somewhat broken, so I'm afraid I cannot bisect now.

Please let me know if I should test something else.

**Comment by endrift** [comment]
Vsync issues fixed in 5d13a00cf751daa51aae95a0d064a3070ca0ee72. The framedrop issues are I think a separate issue, covered by at least one other bug report.

**Comment by rootfather** [comment]
Thanks a lot endrift, it is fixed. Closing this and investigating the other issue in #545.
