### ISSUE TITLE
[Issue] Short, Unknown Freezes

### ISSUE THREAD

**Issue by John-Enigma** [mgba-emu/mgba#557]
Whenever I use mGBA or any of its dev builds, the game runs but stops for a short time. What do I mean? I play a game in mGBA and when it runs, it freezes for one or two (sometimes three) seconds, then it gets back to normal, then repeat. (This even happens when the BIOS are either enabled or disabled.)

Is this normal? I don't even know if I have to check or uncheck something.

I checked my computer. It can't be computer issues, because the emulator runs okay. 

EDIT: I am using mGBA 0.5.2, btw. As for my PC, I have a Gateway SX2110G-UW24, and these are its [specs.](https://www.cnet.com/products/gateway-sx2110g-uw24-e1-1500-1-48-ghz-6-gb-500-gb-led-19-5/specs/)

**Comment by endrift** [comment]
Resolved off-site as a configuration issue.

**Comment by Zerowalker** [comment]
so what was the solution, i got the same problem?

**Comment by Hexaae** [comment]
> so what was the solution, i got the same problem?
VSync (?) seems broken: disable Emulation > Sync to video. This solved random freezes here.
