### ISSUE TITLE
NSMB: World map on bottom screen is missing the entire background

### ISSUE THREAD

**Issue by waddlesplash** [mgba-emu/mgba#561]
![untitled](https://cloud.githubusercontent.com/assets/2175324/24832747/89524500-1c84-11e7-9d96-e9a4cfddfb0d.png)

**Comment by waddlesplash** [comment]
According to @StapleButter:
> The game writes the background outside of the 'normal' BBG VRAM range. This relies on mirroring.

**Comment by endrift** [comment]
Hm, I thought I supported mirror writes to VRAM.
