### ISSUE TITLE
NSMB: Star Coins are white, not the proper gold color

### ISSUE THREAD

**Issue by waddlesplash** [mgba-emu/mgba#562]
![new super mario bros-1](https://cloud.githubusercontent.com/assets/2175324/24832774/4eeb0374-1c85-11e7-8100-6110a9f9957f.png)

**Comment by waddlesplash** [comment]
Probably another manifestation of the same bug: The bottoms of spring-catapults are also incorrectly white.
![new super mario bros-4](https://cloud.githubusercontent.com/assets/2175324/24834322/c796d0b2-1caf-11e7-9cc1-87080798f9aa.png)

**Comment by waddlesplash** [comment]
Oh, and Invincible (Rainbow) Mario has a case of the whites, too:
![new super mario bros-1](https://cloud.githubusercontent.com/assets/2175324/24834380/28f45a54-1cb1-11e7-9239-a42c9974ea6d.png)

**Comment by endrift** [comment]
Almost certainly toon shading not being implemented

**Comment by endrift** [comment]
Okay so I'm pretty sure these are actually distinct bugs. The coin being white is due to the texture matrix being incorrectly multiplied by 0, but I haven't figured out why it's 0. The not-rainbow Mario is still almost certainly toon shading being missing, though.

**Comment by endrift** [comment]
I figured out why it was 0.
