### ISSUE TITLE
Animal Crossing: River water has strange rendering gliches

### ISSUE THREAD

**Issue by waddlesplash** [mgba-emu/mgba#563]
![ac](https://cloud.githubusercontent.com/assets/2175324/24832780/5e9e5942-1c85-11e7-9751-55c0baa0d045.png)

**Comment by waddlesplash** [comment]
Unsure if this actually counts as a separate bug, but it seems that if the "touch to start" text appears in the water/glitched zone, it sometimes appears *behind* it:

![untitled](https://cloud.githubusercontent.com/assets/2175324/24832783/6ca5bd46-1c85-11e7-83d3-41c889eefdc0.png)

**Comment by endrift** [comment]
No idea when this got fixed, but it appears to work fine now.
