### ISSUE TITLE
Etrian Odyssey: Broken fonts in European version

### ISSUE THREAD

**Issue by xdanieldzd** [mgba-emu/mgba#572]
Rendering of normal, non-graphical text (i.e. intro, dialog text, character and item names, etc.) in the European version of Etrian Odyssey for DS is broken in medusa-a1; the Japanese and US versions render their text correctly. All three of them use different fonts.

(Japanese & US versions)
![JPN](https://cloud.githubusercontent.com/assets/7199225/24832826/dd0d20b4-1cb8-11e7-9e16-fc3280b79700.png)![USA](https://cloud.githubusercontent.com/assets/7199225/24832827/e367dc38-1cb8-11e7-87f1-0cc166fe9f9f.png)

(European version, medusa-a1 & other emulator)
![EUR bad](https://cloud.githubusercontent.com/assets/7199225/24832828/e98a5b5e-1cb8-11e7-8e40-aab538210304.png)![EUR good](https://cloud.githubusercontent.com/assets/7199225/24832849/98d42b80-1cb9-11e7-9bd5-57d31b26bd4e.png)

**Comment by endrift** [comment]
Probably the same issue that plagues a few games, including Star Fox Command.

**Comment by endrift** [comment]
The Star Fox bug is fixed in 9379290050a648905d937498987c1611529694ef, but I haven't tested EO to see if it fixes that too.

**Comment by xdanieldzd** [comment]
Can confirm that 9379290 also fixes European EO's fonts; they're 2bpp as well, while the Japanese and US versions (unnecessarily) use 4bpp font textures.

![Fix 1](https://cloud.githubusercontent.com/assets/7199225/24880095/5a30a530-1e39-11e7-9f44-a9801a0645e6.png)![Fix 2](https://cloud.githubusercontent.com/assets/7199225/24880106/5fd71ff0-1e39-11e7-93da-555bec6c8c8f.png)
