### ISSUE TITLE
NSMB: Missing sound effects and instruments

### ISSUE THREAD

**Issue by waddlesplash** [mgba-emu/mgba#574]
I know @endrift has said that the audio code is very incomplete, but here's a basic list of what's missing in NSMB:
 * Coin sound effect is missing (both in game and on Nintendo logo)
 * Koopa-squash sound effect is missing
 * Goomba-squash sound effect is missing
 * The melody instrument track is missing in the overworld theme (World 1-1, etc.)
 * The melody instrument track is missing in the "game over" theme
 * Flagpole slide sound is missing

**Comment by endrift** [comment]
Yeah this is PSG being missing.

**Comment by endrift** [comment]
Fixed in e9c1a53cfbf03252db40b5a19b830f8eb968c684.
