### ISSUE TITLE
Kirby Mass Attack: White screen on startup

### ISSUE THREAD

**Issue by ds84182** [mgba-emu/mgba#576]
"Logs":

```
[STUB] DS I/O:	Stub DS7 I/O register read: 000134
[STUB] DS I/O:	Stub DS7 I/O register write: 000134:8100
```

**Comment by endrift** [comment]
correlation is not causation. That message is unrelated to why it's not booting.

**Comment by ds84182** [comment]
Forgot to add that the game spams this over and over again... sorry

**Comment by endrift** [comment]
Yeah, most games do at the moment, even the ones that work.
