### ISSUE TITLE
NSMB: Ground-pounding on a large mushroom as Giant Mario produces a graphical glitch

### ISSUE THREAD

**Issue by waddlesplash** [mgba-emu/mgba#577]
![new super mario bros-3](https://cloud.githubusercontent.com/assets/2175324/24833077/7cc7d95a-1c8c-11e7-8a59-8dde7e17e7a9.png)

Triggering the bug is rather annoying because you either have to wait until a flying ? box with a mega mushroom in it goes to that level, or get far enough in the game to purchase a mega mushroom.

**Comment by endrift** [comment]
There's a mega mushroom in 1-1.

**Comment by waddlesplash** [comment]
Yes, but I don't recall seeing this bug on 1-1; although I may not have ground-pounded above the bottom of the screen... I'll check.

**Comment by endrift** [comment]
You don't need to check, it is in 1-1; I've seen it.

**Comment by waddlesplash** [comment]
Ah, okay.
