### ISSUE TITLE
Medusa: "Keyboard" and "Controllers" are missing from settings

### ISSUE THREAD

**Issue by disk64** [mgba-emu/mgba#578]
Running 0.1-medusa-4789-ebb0b60 on Ubuntu 14.04, the options to configure the keyboard and controller(s) are missing.

It's a little hard for me to determine if this is worth opening a separate issue over, but I'm also finding that my controller settings from mGBA only partially carried over to medusa- my D-pad (which is mapped to two axes) works, but none of the buttons I had mapped work.

**Comment by disk64** [comment]
Ahhh, shoot, I'm stupid.
It seems that "Shortcuts" has been renamed to "Bindings", and controller bindings can be set there.
I'll go sit in the corner and cry now ToT

**Comment by endrift** [comment]
Yeah, they've been moved but the revamp isn't done yet. It'll be more apparent what needs to be done when it's done.
