### ISSUE TITLE
Issue to compile Medusa on debian Strech

### ISSUE THREAD

**Issue by wwark** [mgba-emu/mgba#585]
Hello,

I have the package libqt5network5 present on my computeur but i have this warning.

CMake Warning (dev) at src/platform/qt/CMakeLists.txt:242 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "medusa-qt" links to target "Qt5::Network" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

Thanks for the support, Regads,

**Comment by wwark** [comment]
[ 91%] Linking CXX executable medusa-qt
/usr/bin/ld: cannot find -lQt5::Network
collect2: error: ld returned 1 exit status
qt/CMakeFiles/medusa-qt.dir/build.make:1781: recipe for target 'qt/medusa-qt' failed
make[2]: *** [qt/medusa-qt] Error 1
CMakeFiles/Makefile2:216: recipe for target 'qt/CMakeFiles/medusa-qt.dir/all' failed
make[1]: *** [qt/CMakeFiles/medusa-qt.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by endrift** [comment]
Should be fixed in f0ea421feada3a4960ed37e32cb7096103e275ab (merged as d4edbcf4491a5a7bbf961367c9bde21be3620024 onto the medusa branch)

**Comment by wwark** [comment]
Thanks a lot ! The compilation is ok.
