### ISSUE TITLE
medusa for macOS

### ISSUE THREAD

**Issue by azoreseuropa** [mgba-emu/mgba#587]
I would like to compile it but I can't because of MSYS. I am not sure if it exist for Mac users. Please let me know so I can compile it and test it for you. Thanks.

**Comment by endrift** [comment]
There's already a macOS build up. To compile on macOS does not require MSYS; you just need to install the dependencies through brew and compile it using the command line instructions for Linux.

**Comment by azoreseuropa** [comment]
Where ? I don't see it. I went to: https://github.com/mgba-emu/mgba/tree/medusa/

Yes, I have the tools to compile like Dolphin, Citra and want to do this one too.

**Comment by endrift** [comment]
https://github.com/mgba-emu/mgba/releases/download/medusa-a1/medusa-a1-osx.tar.xz

You should be going to https://mgba.io/downloads.html

**Comment by azoreseuropa** [comment]
Thanks and downloading it now but can't I compile it when you update regularly ? That's what I am looking for and I love to learn to compile the emulators for my macOS.

**Comment by endrift** [comment]
Just....install the dependencies (brew install qt5, for example), and then run these commands in a source checkout https://github.com/mgba-emu/mgba/blob/master/README.md#compiling

**Comment by azoreseuropa** [comment]
Yeah.. I already have brew install qt5 as usually. Great.. That's what I am looking for but I cannot find git clone for medusa.. you only have mgba git clone. Where is git clone medusa ? Sorry to bother you.

**Comment by endrift** [comment]
same repo, different branch. Checkout the medusa branch.

**Comment by azoreseuropa** [comment]
You mean I can use this:

git clone https://github.com/mgba-emu/mgba.git ??

it is mgba and not medusa. ;)

**Comment by endrift** [comment]
then do `git checkout medusa` to get medusa.

**Comment by azoreseuropa** [comment]
I type git checkout medusa and I got this:
fatal: Not a git repository (or any of the parent directories): .git

**Comment by kode54** [comment]
You must be inside the directory of the repository to check out the medusa branch.

```
git clone https://github.com/mgba-emu/mgba.git
cd mgba
git checkout medusa
```

**Comment by endrift** [comment]
Just ignore it. The installation isn't needed on macOS. There should be a folder called qt with in it medusa.app now

**Comment by azoreseuropa** [comment]
I went to mgba folder>Build>qt>cmake_install.cmake,CMakeFiles folder, and makefile. Thats it. Cannot find medusa.app.

**Comment by azoreseuropa** [comment]
Hello? ^_^

**Comment by endrift** [comment]
It probably didn't find Qt when building. From the build directory, try running `cmake . -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/`

**Comment by Shizmob** [comment]
You are not allowed to install to `/usr` in modern macOS versions, that's where the error comes from (and why recommending setting the prefix to `/usr` in the README is a bad suggestion, among other reasons). Clear out your build dir, run `cmake ..` again, without the `-DCMAKE_INSTALL_PREFIX:PATH=/usr` argument, re-build and install.

**Comment by azoreseuropa** [comment]
First I do this in clean:

git clone https://github.com/mgba-emu/mgba.git
cd mgba
git checkout medusa

successfully

Then do this:

mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
make
sudo make install ???

But you said don't use came - DCMAKE_INSTALL_PREFIX:PATH=/user ..

I don't understand. Can you give me a fully instruction so I can do the compile ?

**Comment by azoreseuropa** [comment]
Hmmm ? ^_^

**Comment by endrift** [comment]
```bash
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH:PATH=`brew --prefix` ..
make
```

Don't do `make install`. It's not needed.

**Comment by azoreseuropa** [comment]
I understand that but when it was succeed and no install and medusa.app isn't there anyway.

**Comment by endrift** [comment]
sorry, I got the cmake wrong:

```bash
cmake -DCMAKE_PREFIX_PATH:PATH=`brew --prefix`/opt/qt5 ..
```

Which I told you to do earlier, and you did not.

**Comment by azoreseuropa** [comment]
Successfully! medusa.app is there. Thank you so much. Much appreciate for your patient.

**Comment by azoreseuropa** [comment]
I have a problem again. Haven't complied it since April 10 2017. I decided to compiled it again. I got this an error message:

/Users/azoreseuropa/mgba/src/platform/qt/LoadSaveState.cpp:59:24: error: 
      allocation of incomplete type 'QAction'
        QAction* escape = new QAction(this);
                              ^~~~~~~
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qwidget.h:68:7: note: 
      forward declaration of 'QAction'
class QAction;
      ^
/Users/azoreseuropa/mgba/src/platform/qt/LoadSaveState.cpp:60:19: error: 
      incomplete type 'QAction' named in nested name specifier
        connect(escape, &QAction::triggered, this, &QWidget::close);
                         ^~~~~~~~~
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qwidget.h:68:7: note: 
      forward declaration of 'QAction'
class QAction;
      ^
/Users/azoreseuropa/mgba/src/platform/qt/LoadSaveState.cpp:61:8: error: member
      access into incomplete type 'QAction'
        escape->setShortcut(QKeySequence("Esc"));
              ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qwidget.h:68:7: note: 
      forward declaration of 'QAction'
class QAction;
      ^
/Users/azoreseuropa/mgba/src/platform/qt/LoadSaveState.cpp:62:8: error: member
      access into incomplete type 'QAction'
        escape->setShortcutContext(Qt::WidgetWithChildrenShortcut);
              ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qwidget.h:68:7: note: 
      forward declaration of 'QAction'
class QAction;
      ^
4 errors generated.
make[2]: *** [qt/CMakeFiles/medusa-emu-qt.dir/LoadSaveState.cpp.o] Error 1
make[1]: *** [qt/CMakeFiles/medusa-emu-qt.dir/all] Error 2
make: *** [all] Error 2
azoress-MacBook-Pro:build azoreseuropa$ 

Am I missing something ? It was fine on 2017. Now I got a new error. :(
