### ISSUE TITLE
Metroid Prime Pinball Does boot past initial splashscreen

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#599]
![image](https://cloud.githubusercontent.com/assets/6598209/24862234/d0a3ea44-1dc9-11e7-8149-b3ddb4478c3f.png)

**Comment by JMC47** [comment]
Burnout Legends (DS) has the same problem.

**Comment by endrift** [comment]
Likely due to missing EEPROM support.

**Comment by bentley** [comment]
G.G. Series Collection + has what looks like the same problem.

**Comment by endrift** [comment]
Strange, Meteos worked fine for me a few days ago.

**Comment by bentley** [comment]
Ah, Meteos gives a save error but then continues to boot successfully.

**Comment by endrift** [comment]
Have you made sure that the ROMs are in directories you have write access to? This can happen if it doesn't initialize the savegame properly

**Comment by JMC47** [comment]
Well, my other games save fine?

**Comment by endrift** [comment]
Fixed in 5bb811a16e32a8061319af6c772a941aad9bfaa1.
