### ISSUE TITLE
Weird Select ROM window

### ISSUE THREAD

**Issue by sergiobenrocha2** [mgba-emu/mgba#6]
Load a game and try to open another by File -> Load ROM..., you will see this:

![screenshot - 02042015 - 12 43 06](https://cloud.githubusercontent.com/assets/5431285/6967485/fcfd71e4-d935-11e4-8e98-4e9896598e45.png)

You have to shutdown emulation to load another rom.

Xubuntu 14.04, amd64.

**Comment by endrift** [comment]
Does pausing emulation allow the dialog to work normally?

**Comment by sergiobenrocha2** [comment]
Yes
