### ISSUE TITLE
Undo save state load

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#60]
Feature request: A few times, I've spammed save state loads trying to get some random event to happen. When it actually happens, I'm so caught up that I accidentally load back to before the event happened. Saving an (unaccessable) state to keep as an "undo" state before loading a state would really help.

**Comment by endrift** [comment]
Should be easy enough to do this, might be able to fit it into 0.3 even.

**Comment by endrift** [comment]
Added in f50f98416bc9e5455b71732a6727eda9bf8d6064
