### ISSUE TITLE
Implement "Book" Style view for Panel De Pon DS (Planet Puzzle League)

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#601]
In this game you're meant to hold the DS Sideways in order to make "taller" screens which are better for the puzzle game.

![image](https://cloud.githubusercontent.com/assets/6598209/24862461/b0809fae-1dca-11e7-8141-e9310cde8e33.png)

Graphics are also kind of broken.

**Comment by benderscruffy** [comment]
same as bug #179 
as Endfift replied "Extremely low priority"

**Comment by endrift** [comment]
It's a bit higher priority now that there's DS support.
