### ISSUE TITLE
Strange artifacts in the distance in The Legend of Zelda: Phantom Hourglass.

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#604]
Can be spotted in the Intro movie just by watching it.  See the bottom of the bottom screen to see the vertical lines.

![image](https://cloud.githubusercontent.com/assets/6598209/24862798/2e63b4f0-1dcc-11e7-8a61-abb6a28fe8c4.png)

**Comment by Anty-Lemon** [comment]
Fixed by 9676ea1.
