### ISSUE TITLE
Everytime I reopen Medusa it readds "autofire" hotkeys for every key on my controller.

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#605]
![image](https://cloud.githubusercontent.com/assets/6598209/24862904/abdf1136-1dcc-11e7-9dff-462c72b79ba2.png)

Why.  Please.

**Comment by endrift** [comment]
Fixed in https://github.com/mgba-emu/mgba/commit/91068d14b9d6e1e028b32aa14a9ae46f99a6a89e.
