### ISSUE TITLE
compiled medusa screw up ? 

### ISSUE THREAD

**Issue by spotanjo3** [mgba-emu/mgba#607]
After I succeed and medusa.app is there. I moved medusa.app to medusa folder and deleted mgba in trash bin from /user/myname/mgba folder and my medusa.app is in medusa folder at desktop and run it but it crashes. Strange.

So, I bring mgba folder back from the trash bin to where it came from and medusa folder at desktop and run it works. Strange behave.

**Comment by azoreseuropa** [comment]
Been 2 days... Help ?

**Comment by azoreseuropa** [comment]
Hello?

**Comment by endrift** [comment]
I am, of course, several years late to replying to this, but this is probably an issue with rpath or similar. If you're still interested in trying to figure this out, hit up the discord (https://discord.gg/em2M2sG) or the forums (https://forums.mgba.io) and we can try to sort it out there.

**Comment by spotanjo3** [comment]
Thank you kindly, endrift but thats okay. I dont need it anymore because I am on PC now. I still used the macOS, thought. Just the emulators are moving to PC because it is much better than macOS. macOS is not great for emulators due to a few developers working on macOS. So no bother about it. I will closed it now. Thank you.
