### ISSUE TITLE
DS: Trials and Tribulations (GB) makes Medusa crash

### ISSUE THREAD

**Issue by Kyrio** [mgba-emu/mgba#608]
Shortly after the game loads its title screen, Medusa crashes. I've attached the last logs I can get before it happens:

![image](https://cloud.githubusercontent.com/assets/3719464/24905451/4f1e112a-1eb4-11e7-931e-6b92756df5b3.png)

![image](https://cloud.githubusercontent.com/assets/3719464/24905736/3a274d1c-1eb5-11e7-95c4-c89abb944113.png)

The version is 9379290 (32-bit since the 64-bit nightly refuses to open), but the bug is also there on medusa-a1, 64-bit.

**Comment by Kyrio** [comment]
To be precise, once the game shows its title screen, both the game and the GUI start hanging (good old "This program is not responding").

I'm not really Windows GUI-savvy so I don't know what usually triggers that kind of behavior (infinite loop?), but it does affect the whole emulator and not just the game.

**Comment by endrift** [comment]
Can confirm.

**Comment by endrift** [comment]
"Fixed" in 01738f3bf60c25f9372396c542ebb0c91d9978e0
