### ISSUE TITLE
Revamp stepping feature

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#61]
Long-term feature request: The current frame-by-frame feature is the "step backwards" function. Eventually, it would be cool to have the fast forward/rewind buttons and their held variants change to "step forward" and "step backwards" while the game is paused, similar to how a DVD player or DVR works.

**Comment by endrift** [comment]
Stepping forwards would be a bit strange due to the fact that those frames haven't actually happened yet, so you can't really skip ahead. We'll see how this works for rewinding after I get to #36, though.

**Comment by tony971** [comment]
Oh I meant once you step backwards, being able to step forward back to the current frame. Since emulation is paused, new frames aren't being created so the same set of rewind states should exist for the entire stepping process.

**Comment by endrift** [comment]
Oh, yeah, okay, that makes sense. It would require a huge redoing of the rewind feature, given how it's currently implemented, but I might be able to do it.

**Comment by tony971** [comment]
Even without the step forward feature, having the (held) rewind buttons change to step backwards while emulation is paused could save a button binding and eliminate worrying about how long to wait after the last step before resuming play.
