### ISSUE TITLE
DS: Cannot specify NDS BIOS in SDL port

### ISSUE THREAD

**Issue by Anty-Lemon** [mgba-emu/mgba#612]
Build: 0.1-medusa-4827-15496611
OS: Debian 9.0 stretch amd64

In the SDL port of medusa, only the GBA BIOS can be specified. Proposing the inclusion of option(s) to pass the NDS BIOS binaries.

**Comment by endrift** [comment]
Problem here is that you'd have to either pass `-b` twice, which I have no real infrastructure for handling at the moment, or have specific command line arguments for each.

(Also, `-b` does work for GB/C, and you can use the config file to pass in the BIOS)

**Comment by Anty-Lemon** [comment]
Alternatively, you could allow for passing a directory instead of a file.

**Comment by endrift** [comment]
There's never been a ~/.mgba?

**Comment by Anty-Lemon** [comment]
My bad. I forgot I made that directory on my own machine, for roms and savestates and such.

**Comment by endrift** [comment]
Passing a directory is a weird idea because you don't have a way of specifying the individual filenames then. At that point, you might as well use the config file, if I ever get that documented.

**Comment by Anty-Lemon** [comment]
Thank you for adding `-C`.

Closing this issue, unless you want to keep it open until a better solution is found.

**Comment by endrift** [comment]
I'm considering adding a way to pass `-b` more than once, but it's low on the list. `-C` I've been meaning to do for a while.
