### ISSUE TITLE
G. G. Series Collection + fails to boot

### ISSUE THREAD

**Issue by bentley** [mgba-emu/mgba#614]
![2017-04-12-005637_256x403_scrot](https://cloud.githubusercontent.com/assets/126009/24945128/4dd1fff4-1f1b-11e7-8d52-d2406742e9f2.png)

**Comment by endrift** [comment]
Please check after 5bb811a16e32a8061319af6c772a941aad9bfaa1.

**Comment by bentley** [comment]
Same result in a688e62123738a8a54b6efade0ab2d2515896781.

**Comment by endrift** [comment]
All three of these boot and save fine for me. Make sure either your ROMs are in a r/w directory, or you have your save path set to be a r/w directory.
