### ISSUE TITLE
Retro Game Challenge cannot save and refuses to continue

### ISSUE THREAD

**Issue by bentley** [mgba-emu/mgba#615]
After starting a new game and going through the intro cinematic, this error comes up and apparently can’t be skipped.

![2017-04-12-010240_256x403_scrot](https://cloud.githubusercontent.com/assets/126009/24945302/eac6f6fc-1f1b-11e7-9754-e8982aa594ff.png)

**Comment by endrift** [comment]
Please check this after 5bb811a16e32a8061319af6c772a941aad9bfaa1.

**Comment by bentley** [comment]
Same result in a688e62123738a8a54b6efade0ab2d2515896781.

**Comment by endrift** [comment]
See my comment on #614
