### ISSUE TITLE
Tetris DS does not start (save error?)

### ISSUE THREAD

**Issue by bentley** [mgba-emu/mgba#617]
![2017-04-12-011243_256x403_scrot](https://cloud.githubusercontent.com/assets/126009/24945588/25b67e1c-1f1d-11e7-9736-eae99d63754d.png)

**Comment by endrift** [comment]
I thought I fixed this weeks ago. Must have broken it at some point.

**Comment by endrift** [comment]
Please check this after 5bb811a16e32a8061319af6c772a941aad9bfaa1.

**Comment by bentley** [comment]
Same result in a688e62123738a8a54b6efade0ab2d2515896781.

**Comment by endrift** [comment]
See my comment on #614
