### ISSUE TITLE
My Baby - Boy - Baby is ugly

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#625]
![image](https://cloud.githubusercontent.com/assets/6598209/24980962/7bb5fe9c-1fa8-11e7-8557-87f40de77102.png)

Parts of the texture disappears too.  Observe the head.

![image](https://cloud.githubusercontent.com/assets/6598209/24980982/94c41446-1fa8-11e7-974e-a63ee8379623.png)

**Comment by Committee** [comment]
Apologies, the title, so many one-liners can be made for that, not helping I know, but cannot help it.

**Comment by JMC47** [comment]
baby is less ugly now, as of the April 27th nightly
