### ISSUE TITLE
Ford Racing 3 - Skewed and Corrupted Graphics

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#629]
![image](https://cloud.githubusercontent.com/assets/6598209/24981361/5d086e42-1faa-11e7-85e4-424f5c223ea2.png)

**Comment by endrift** [comment]
This is an issue with bitmap objects

**Comment by endrift** [comment]
Fixed in fe2f67e2aa2246e8ec2c2599a480d6ff7557f3f7.
