### ISSUE TITLE
Star Fox Command - Green Dots over Mission Intro Screens

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#636]
![image](https://cloud.githubusercontent.com/assets/6598209/24984335/aace42cc-1fba-11e7-9111-62309f5adb25.png)

**Comment by Anty-Lemon** [comment]
The green dots are expected, and match my observations on hardware. The black dots in-between some of them are bugged, but I cannot reproduce them, neither on faadb5d nor a688e62.

**Comment by endrift** [comment]
I don't see black dots in the screenshot? I think it's just scaled poorly.

**Comment by Anty-Lemon** [comment]
Ah, you're right. At closer inspection, they are indeed just rescaling artifacts.
