### ISSUE TITLE
Mario And Sonic at the Olympic Games - Cannot Save

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#637]
![image](https://cloud.githubusercontent.com/assets/6598209/24984395/0d894452-1fbb-11e7-937d-8103fbb3d96c.png)

Played on latest nightly.

**Comment by slashiee** [comment]
This doesn't happen to me on latest nightly (0.1-medusa-4882-a5f664c), I wonder if c2f43bc503e1bfd181fdd76ead42dc67eea0b4f1 fixed the issue.

![image](https://cloud.githubusercontent.com/assets/15317421/25305435/cfe082d8-272f-11e7-9287-040a9cb0868d.png)

**Comment by endrift** [comment]
Please re-test. It's probably fixed now.
