### ISSUE TITLE
mgba-qt Ubuntu 15.04 nightly - Controller assignment does nothing

### ISSUE THREAD

**Issue by craysiii** [mgba-emu/mgba#64]
Downloaded the nightly yesterday. I've got to say I'm really impressed with the emulation so far. However, when I go to change the buttons on my gamepad through the UI, nothing actually seems to change.

I am using a wired xbox360 controller. It recognizes that it's a "generic 360 pad" in the drop down menu, but clicking any of the buttons for assignment (or the assign all button) does nothing. No prompt. Clicking buttons on the pad doesn't change any value of a highlighted input. I'll try to investigate further, and see if it works on the gtk version.

**Comment by endrift** [comment]
There is no gtk version. The other version is SDL2 and has no real GUI. I made some large changes to controllers recently, so I can take a look at this soon. I have Arch as my main Linux testing environment but I do have Ubuntu in a VM I can look at.

**Comment by craysiii** [comment]
My apologies, I must have gotten confused with vba-m. Been trying a lot of emulators recently. Anyway, great work!

**Comment by endrift** [comment]
Confirmed on Arch Linux with a 360 Controller. I think it's a regression from 75fb2548bbb6dea49e6d1040e3b59d76f5548fa6.

**Comment by endrift** [comment]
I took the liberty of adding a controller profile for the 360 controller on Linux so it shouldn't need to be reconfigured.

**Comment by craysiii** [comment]
Awesome. I'll install the newest build tomorrow.
