### ISSUE TITLE
Advance Wars: Dual Strike — main menu unreadable

### ISSUE THREAD

**Issue by bentley** [mgba-emu/mgba#642]
Should display a list of options, but is solid black.

![2017-04-12-210318_256x403_scrot](https://cloud.githubusercontent.com/assets/126009/24988500/93233930-1fc3-11e7-98b2-45575cd0a66e.png)

**Comment by endrift** [comment]
This...used to work

**Comment by endrift** [comment]
Regressed in 940ba00182ac35886da977adc82fc531601b3d34.
