### ISSUE TITLE
[Regression] Polygons getting drawn way too large in various circumstances

### ISSUE THREAD

**Issue by waddlesplash** [mgba-emu/mgba#649]
For instance, it happens when Mario's head goes above the top of the screen:
![super mario 64-0](https://cloud.githubusercontent.com/assets/2175324/25013187/b6420e1e-2040-11e7-987a-9004767bec55.png)
There's also a new graphical glitch in the lower right corner of the BIS title screen; possibly the same bug?
![mario luigi - bowser s inside story us -0](https://cloud.githubusercontent.com/assets/2175324/25013216/c7f25880-2040-11e7-966b-3b988f908b7f.png)

**Comment by waddlesplash** [comment]
Animal Crossing is similarly affected:
![animal crossing - wild world-0](https://cloud.githubusercontent.com/assets/2175324/25013285/077eee1e-2041-11e7-8f8f-76fd69c2cefd.png)

**Comment by endrift** [comment]
Please bisect on your end, because I can't reproduce locally.

**Comment by Simonx22** [comment]
I can reproduce this with New Super Mario Bros and the latest nightly: 
![nsmb](https://cloud.githubusercontent.com/assets/26326692/25019846/6aba7eee-208c-11e7-9914-749112f65a5a.png)

**Comment by Simonx22** [comment]
Also the same in Mario Kart DS:
![this_doesnt_look:right](https://cloud.githubusercontent.com/assets/26326692/25020238/db800792-208d-11e7-94b5-501a0f70a841.png)
![also_broken](https://cloud.githubusercontent.com/assets/26326692/25020277/f5ba671a-208d-11e7-9a6b-2fde83b67387.png)
![broken](https://cloud.githubusercontent.com/assets/26326692/25020300/0c738176-208e-11e7-997a-964eec043795.png)

**Comment by waddlesplash** [comment]
Yep, is indeed fixed by that commit.
