### ISSUE TITLE
Allow axes and buttons to be mapped to the same key via UI

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#65]
Right now, the only way to do this is via configuration file, the location of which isn't shown to the user explicitly.

**Comment by karasuhebi** [comment]
The config.ini file is in a standard location, I don't think there's a need to show the user where that is.

**Comment by tony971** [comment]
By not having any indication of this functionality in the UI, users won't know that it's an option unless they go digging through the ini files. Most will have no clue what an ini file is. It's essentially making it a dead feature outside of the pre-configured defaults.

**Comment by karasuhebi** [comment]
I completely agree, I was just defending the decision to not disclose the location of the config.ini file, since it's in a standard location. That's all :)

**Comment by endrift** [comment]
The only reason I haven't done this yet is because I haven't figured out what the UI for this should look like. I think there's an open ticket for it in bugzilla, but I'm not sure.

**Comment by tony971** [comment]
You could go simple. Turn off the auto-progression to the next button and just keep allowing users' inputs to record. Separate the inputs by commas. "4, +1" something like that.

**Comment by tony971** [comment]
It might also be a good time to work on the UI stuff for hats. Wasn't it decided to use arrows for them? ^1, v1, <2, >2

**Comment by endrift** [comment]
I can use the actual Unicode arrows, you realize. The core doesn't support mapping hats at the moment, though. They're all hard coded to the dpad.

**Comment by endrift** [comment]
The bigger problem is UNmapping one or the other though, not supporting setting both.

**Comment by tony971** [comment]
Higan has a decent setup for controller mapping. It's not Qt, but it's a nice concept. https://gitlab.com/higan/higan

**Comment by craysiii** [comment]
You could use a datagrid to handle multiple button assignments. I've seen it done with the OnePAD plugin on PCSX2. Maybe as an advanced config UI? My 2c.

**Comment by tony971** [comment]
Actually, this is a better link for Higan http://board.byuu.org/phpbb3/viewtopic.php?f=4&t=536

**Comment by endrift** [comment]
Yes, I'm well familiar with higan :P That said, I may just add "Unmap" buttons for now. I was thinking about doing a much more in-depth UI for 0.3, but that's obviously delayed for now.

**Comment by tony971** [comment]
He has a "reset" button for clearing all bindings and a "clear" button for clearing the active button's bindings. It works well for multiple mappings.

**Comment by endrift** [comment]
Partially implemented in a08f09291362f2e9c43d7e84e864fece1a7e25bb

**Comment by tony971** [comment]
This works, but the auto-progression skips the leftmost options. Not sure how to fix that without mandating two bindings per button.

**Comment by endrift** [comment]
I'm not sure what you mean. Leftmost? They should all be equivalent. That said, you can click on a field again to set that value in specific.

**Comment by tony971** [comment]
Right, that's what I ended up doing. Let's say I started mapping the "up" button. It would allow one entry and then the auto-progression would move onto the next button. Repeat until all four directions are mapped. But it doesn't do a second pass before moving onto other buttons. The auto-progression skipped mapping buttons and jumped straight to mapping axes.

This could be fixed by having auto-progression do a second pass or wait for a double entry before moving on, but that would mandate two bindings unless pressing the same key twice made it think "oh, they're only using buttons or only using axes. move on"

**Comment by tony971** [comment]
Also, with the current implementation, only people who know the marking conventions of mGBA can intuitively use it. One way to fix this is to have a message appear saying "D Pad" while mapping a button entry and "Joystick" for an axis. But that'll also create anger and frustration with controllers that use hats for D Pads.

**Comment by tony971** [comment]
However, the double entry wouldn't make sense if those contextual messages appear. A better solution might be to have two D Pads in the UI. One labeled "D Pad" and one labeled "Joystick". They'd each initiate auto-progression for their four directions, but not move onto the other D Pad. That way users can clearly see what they're binding and skip what they don't have.

**Comment by endrift** [comment]
This is basically done now, minus the hats. That's covered by https://endrift.com/mgba/bugs/show_bug.cgi?id=144 though.
