### ISSUE TITLE
[Regression] New Super Mario Bros - missing some 2D graphics

### ISSUE THREAD

**Issue by Simonx22** [mgba-emu/mgba#654]
![8d6vmtw](https://cloud.githubusercontent.com/assets/26326692/25019177/0c00ab78-208a-11e7-891b-fef76cac92ec.png)
![t7fzk53](https://cloud.githubusercontent.com/assets/26326692/25019181/0d5ebcc6-208a-11e7-933f-968b597dadd0.png)

**Comment by endrift** [comment]
Fixed in a05d97a85cc95b935f1b0cf22cf1287239b9b9f6.
