### ISSUE TITLE
[Regression] Mario Kart DS - minimap is missing... kinda

### ISSUE THREAD

**Issue by Simonx22** [mgba-emu/mgba#656]
![0201 - mario kart ds e spliff altwfc -15](https://cloud.githubusercontent.com/assets/26326692/25020203/b827f412-208d-11e7-9e5f-9db27fc4856f.png)
![0201 - mario kart ds e spliff altwfc -16](https://cloud.githubusercontent.com/assets/26326692/25020204/b97b4120-208d-11e7-993b-8c1fdf3b132b.png)

**Comment by endrift** [comment]
Fixed in a05d97a85cc95b935f1b0cf22cf1287239b9b9f6.
