### ISSUE TITLE
[Regresion] Pokemon black edition glitch/flickering

### ISSUE THREAD

**Issue by mrcmunir** [mgba-emu/mgba#657]
![captura de 2017-04-13 23-24-32](https://cloud.githubusercontent.com/assets/1274014/25025246/bd61681e-20a1-11e7-98f1-5044633f3ac9.png)
![captura de 2017-04-13 23-23-42](https://cloud.githubusercontent.com/assets/1274014/25025247/bd6e8de6-20a1-11e7-95a8-61077432a983.png)

Happen in somezones   cause by recent change https://github.com/mgba-emu/mgba/commit/516143b170059dcb24fcb28714a7eae4cce5db1e

**Comment by endrift** [comment]
Probably related to #649

**Comment by mrcmunir** [comment]
Yep fixed   https://github.com/mgba-emu/mgba/commit/8fcf9bee070251b6f2cefc9339e2e87842d00895
