### ISSUE TITLE
GameShark Save Import Not Working

### ISSUE THREAD

**Issue by wildgoosespeeder** [mgba-emu/mgba#658]
I doubt this is mGBA's fault because this also happens in a 2004 version of VisualBoyAdvance and the current VBA-M release, even with `vba-over.ini` present and modified to account for the three Donkey Kong Country GBA games. I'm just trying to find answers why certain *.sps files don't take effect. I've had some successes and some failures with this import feature. I am having issues importing a GameShark Save for Donkey Kong Country 3 from GameFAQs. I go to the file select screen in-game after importing and I see no 101% saves. All slots are blank. Is there something wrong with the decoding algorithm in all three GBA emulators or are saves a pain in the butt (which has been an issue from the start of GBA emulation)?

https://www.gamefaqs.com/gba/928294-donkey-kong-country-3/saves

**Comment by endrift** [comment]
Please link to the GameShark Save you're using.

**Comment by wildgoosespeeder** [comment]
So quick!

**Comment by endrift** [comment]
The save looks valid. I'll investigate at some point.

**Comment by wildgoosespeeder** [comment]
Would you like to know what other GameShark saves I tried? It isn't unique to Donkey Kong Country GBA game saves.

**Comment by endrift** [comment]
Should be fixed now.

**Comment by wildgoosespeeder** [comment]
Once the nightlies section of downloads updates on your website, I hope to test this for myself.

**Comment by endrift** [comment]
That's odd. I'll look into why.

**Comment by wildgoosespeeder** [comment]
I think it's now fixed because it is now 0f356a9. I can confirm that the same successfully imported! Thanks for the bugfix!
