### ISSUE TITLE
Simple rewind history

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#66]
I decided to make a new issue for this rather than adding it to #36 because it's something that seems vastly less important and requires more Qt tomfoolery. The idea is simple. Assuming end users are dumb, hide the rewind history settings by default. Instead, statically set rewind states to be created every 6 frames or so and ask how many seconds of history users want. It's easier to understand seconds than frames/states. For users with brains, keep the frames/states options as advanced settings.

P.S. I said 6 frames because it'll play out to about 10fps,which is semi-fluid.

**Comment by tony971** [comment]
This would allow ditching the "enable rewind" option because you could default 0 as the desired number of seconds. And then add in a warning saying that the longer the history, the more memory you use.

**Comment by endrift** [comment]
It's now set to do it every frame for up to 5 seconds by default, and I swapped the "Held" and normal shortcuts, so you just hold rewind and it goes back in near-realtime for however long.
