### ISSUE TITLE
NSMB: Incorrect Z-ordering in W8-3

### ISSUE THREAD

**Issue by waddlesplash** [mgba-emu/mgba#661]
See the bubble on the left -- the plant inside the bubble appears behind the green plant.
![new super mario bros-4](https://cloud.githubusercontent.com/assets/2175324/25049300/3f2c5544-210f-11e7-92c8-23f53e568d4e.png)

**Comment by StapleButter** [comment]
Related to polygon IDs, not Z, afaict. I saw the same bug while implementing polygon IDs in melonDS. I don't remember the exact cause, but basically: the polygon ID check for translucent pixels is only done when the destination pixel was translucent too (regardless of the stored alpha), except when drawing shadows.

(this, based on what I observed and tested. may be wrong)

**Comment by endrift** [comment]
I implemented that part of polygon ID stuff already. It was, for example, causing trees to show through each other in SM64 before I fixed it. Wonder if I got it wrong somehow.
