### ISSUE TITLE
Segfault with multiple debuggers open

### ISSUE THREAD

**Issue by Anty-Lemon** [mgba-emu/mgba#662]
Build: 0.6-4426-d16df697 and 0.1-medusa-4856-8fcf9bee
OS: Debian 9.0 stretch amd64

With both GDB stub and CLI debugger active, sending a command to the CLI debugger segfaults.

Easiest way to reproduce:
- Open CLI debugger
- Break
- Start GDB server
- Send any command to CLI debugger

This does not affect the SDL port, as it will not open if both `-d` and `-g` are passed.

**Comment by endrift** [comment]
hhhh I thought I fixed this. It's supposed to detach the CLI debugger if you start the GDB server.
