### ISSUE TITLE
Segfault in CLI debugger after reset

### ISSUE THREAD

**Issue by Anty-Lemon** [mgba-emu/mgba#663]
Build: 0.6-4426-d16df697 and 0.1-medusa-4856-8fcf9bee
OS: Debian 9.0 stretch amd64

Likely related to #662.

- Reset game
- Open CLI debugger
- Send any command to CLI debugger

Opening the CLI debugger first, breaking, then restarting causes a hang instead.

Tested in Qt port. It's uncertain if this bug affects the SDL port; there is no hotkey to hard reset the game.

**Comment by endrift** [comment]
The SDL port cannot hard-reload at the moment, so this is Qt only.

**Comment by endrift** [comment]
Seems to work after fixing #662. Please verify.

**Comment by Anty-Lemon** [comment]
Segfault is fixed, the hang is not. Opening the hang as a new issue...
