### ISSUE TITLE
Solatorobo - Red the Hunter has scrambled 2D graphics in opening

### ISSUE THREAD

**Issue by gourdcaptain** [mgba-emu/mgba#665]
On Medusa r4856.8fcf9bee-1 on Arch Linux, the opening of Solatorobo: Red the Hunter has some issues with the 2D graphics at points:
![solatorobo - scrambled opening 2d](https://cloud.githubusercontent.com/assets/7662067/25057273/4d5b046c-213c-11e7-8e8a-ddcd3e77b75c.png)
This should look like:
![solatorobo - correct opening 2d](https://cloud.githubusercontent.com/assets/7662067/25057276/5482d012-213c-11e7-8bb8-eecb971a0c5a.png)

**Comment by endrift** [comment]
This was fixed by one of my changes from earlier today or yesterday.
