### ISSUE TITLE
Pokemon Black - Anti-Piracy Zero EXP trap goes off

### ISSUE THREAD

**Issue by gourdcaptain** [mgba-emu/mgba#666]
With Pokemon Black (and presumably White) on r4856.8fcf9bee of Medusa (tested on Arch Linux), the anti-piracy code trips and no Pokemon can gain XP after battle (it skips EXP allocation entirely).

**Comment by endrift** [comment]
This should be fixed by b796a689cbbb6e320654d03d2e8a300072d256ec, let me know if it's not.

**Comment by endrift** [comment]
oh man I just noticed this is issue #666. How fitting.

**Comment by gourdcaptain** [comment]
Unfortunately, b796a68 is not solving the issue for me - I still end up getting no XP after the battle with Bianca at the start of the game (I tested the first time until the first wild Pokemon encounter, but I'm currently stuck on a netbook with an Intel Core m5-6Y54. Performance is a bit pokey.

**Comment by endrift** [comment]
Hmm, maybe it's a bit more finicky than I thought. It was working for me, but I guess it's not fixed universally.

**Comment by mrcmunir** [comment]
Alternative is implemented cheat code and add these cheat code for EXP run in the emulator in early stage in Desmume working with cheat code

**Comment by endrift** [comment]
That's definitely not a fix, but it's a somewhat reasonable workaround for the short term. That said, I don't plan to implement cheats before medusa 0.2.

**Comment by Anty-Lemon** [comment]
Confirmed in Pokemon White.

Build: 0.1-medusa-4861-faadb5d6
OS: Debian 9.0 stretch amd64
Game: Pokémon White (IRAO01)

**Comment by StapleButter** [comment]
the game sends backupmem command 0x08, expects reply 0xAA

**Comment by endrift** [comment]
Thanks so much @StapleButter! It's fixed now.
