### ISSUE TITLE
Request: Ubuntu repository

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#67]
Easiest linux distribution method

**Comment by craysiii** [comment]
This would be great once #59 is resolved

**Comment by endrift** [comment]
I believe @sergiobenrocha2 wanted to help with this.

**Comment by sergiobenrocha2** [comment]
I have an working package, but it has some lintian warnings/errors yet:

```
W: libmgba: package-name-doesnt-match-sonames libmgba0.3
W: libmgba: non-dev-pkg-with-shlib-symlink usr/lib/x86_64-linux-gnu/libmgba.so.0.3.0 usr/lib/x86_64-linux-gnu/libmgba.so
E: mgba-sdl: binary-or-shlib-defines-rpath usr/bin/mgba /usr/lib
W: mgba-sdl: binary-without-manpage usr/bin/mgba
E: mgba-qt: binary-or-shlib-defines-rpath usr/bin/mgba-qt /usr/lib
W: mgba-qt: binary-without-manpage usr/bin/mgba-qt
```

I can't use chrpath to remove the rpath anymore, I don't know what happened.

In the installing, you can see:

```
-- Installing: /home/sergio/Projects/mGBA/mgba/debian/tmp/usr/lib/libmgba.so
-- Set runtime path of "/home/sergio/Projects/mGBA/mgba/debian/tmp/usr/lib/libmgba.so.0.3.0" to "/usr/lib"
[...]
-- Installing: /home/sergio/Projects/mGBA/mgba/debian/tmp/usr/bin/mgba
-- Set runtime path of "/home/sergio/Projects/mGBA/mgba/debian/tmp/usr/bin/mgba" to "/usr/lib"
-- Installing: /home/sergio/Projects/mGBA/mgba/debian/tmp/usr/bin/mgba-qt
-- Set runtime path of "/home/sergio/Projects/mGBA/mgba/debian/tmp/usr/bin/mgba-qt" to "/usr/lib"
```

@endrift needs to merge that manpage PR yet.

**Comment by sergiobenrocha2** [comment]
Ok, I can avoid that with -DCMAKE_SKIP_RPATH=ON

**Comment by endrift** [comment]
I'm not sure what's going on with some of those lintian warnings, but I can't merge #1 due to it being woefully incomplete, and it's been difficult to get ahold of @bentley to try to coordinate to fix up the manpage. I would love to do it before 0.3.0, but I'm not hugely hopeful at this point. I might just merge it and fix it up myself, although I don't know how to write troff at all.

**Comment by sergiobenrocha2** [comment]
I uploaded mGBA to this PPA: https://launchpad.net/~random-stuff/+archive/ubuntu/stable/

Any problem @endrift ?

It's the 0.2 branch. I tried to import the code to launchpad once, but it had some problem, so it's no easy to maintain a nightly version in other PPA.

**Comment by endrift** [comment]
I actually made a PPA a while ago: https://launchpad.net/~endrift/+archive/ubuntu/mgba but I never put in enough work to get it to actually do anything.

**Comment by sergiobenrocha2** [comment]
You should create a PPA with a team behind, instead your own user. So more people can be added to the team, and anyone can publish packages there. I can add you in the random-stuff

**Comment by karasuhebi** [comment]
Should this be closed?

**Comment by sergiobenrocha2** [comment]
I think so.

Stable package is in this PPA: https://code.launchpad.net/~random-stuff/+archive/ubuntu/stable

Nightly/Testing in this: https://code.launchpad.net/~random-stuff/+archive/ubuntu/ppa

Someone only needs to push manually the git source to the launchpad branch, take a look at the recipe description: https://code.launchpad.net/~random-stuff/+recipe/mgba-daily (launchpad has some limitation to import code sometimes, waiting them move to git yet). I'm doing that weekly, so you'll have more or less a new master build every week. Someone can create a cron script to do it daily, I'm just too lazy...

**Comment by RetroEdit** [comment]
Closing; it looks like this has been done since around 2016: https://launchpad.net/mgba

**Comment by endrift** [comment]
I intentionally didn't close this as that repo isn't actually properly aligned due to how PPAs work (I can't upload built packages to it, it has to do the building itself, and its version autodetection gets it wrong). But I'm not sure there will be a proper Ubuntu repo.
