### ISSUE TITLE
Spyro Eternal Night: Unnecessary lag frames

### ISSUE THREAD

**Issue by Anty-Lemon** [mgba-emu/mgba#672]
Build: 0.1-medusa-4858-b796a689
OS: Debian 9.0 stretch amd64
Game: The Legend of Spyro: The Eternal Night (A6TE7D)

The game lags a lot more than on hardware or on DeSmuME. Confirmed to be an emulation issue rather than generic slowdowns by using frame advance.

See the main menu and the first level for examples.

**Comment by endrift** [comment]
This is probably the same bug as #620.

**Comment by endrift** [comment]
Please retest after f32fbd7.

**Comment by Anty-Lemon** [comment]
Confirmed fixed.
