### ISSUE TITLE
Sonic Colors (BXSE8P) - Crashes when creating save

### ISSUE THREAD

**Issue by slashiee** [mgba-emu/mgba#674]
Tested on latest nightly (0.1-medusa-4856-8fcf9be)

Windows 10 Home 64-bit
AMD FX(tm)-6300 Six-Core Processor
AMD Radeon (TM) R7 360 Series

Booting Sonic Colors up will initialize the save data, but medusa will crash right when it starts doing this process.

![image](https://cloud.githubusercontent.com/assets/15317421/25068538/b3a61f38-221b-11e7-8f74-95acbe82e399.png)

**Comment by endrift** [comment]
This was probably fixed in c2f43bc503e1bfd181fdd76ead42dc67eea0b4f1, which was committed in between when the last nightly was built and when you filed the issue. Try the upcoming nightly.

**Comment by slashiee** [comment]
Yeah, the commit fixed it. The game now gets past that screen.
![image](https://cloud.githubusercontent.com/assets/15317421/25073167/67181124-2295-11e7-8901-253396ff158b.png)
