### ISSUE TITLE
Worms: Open Warfare 2 - game tells me it's corrupted

### ISSUE THREAD

**Issue by Simonx22** [mgba-emu/mgba#677]
![worms_open_warfare_2-9](https://cloud.githubusercontent.com/assets/26326692/25073400/4f9c509a-22e6-11e7-869f-e1b3636783f1.png)
It never goes into the game.

**Comment by endrift** [comment]
This appears to have been resolved sometime since alpha 2 and will be fixed in alpha 3, whenever that comes out.
