### ISSUE TITLE
Worms: Open Warfare 2 - graphic issues

### ISSUE THREAD

**Issue by Simonx22** [mgba-emu/mgba#678]
![worms_open_warfare_2-10](https://cloud.githubusercontent.com/assets/26326692/25073417/bd02e478-22e6-11e7-9e60-131b702d9cbc.png)
![worms_open_warfare_2-6](https://cloud.githubusercontent.com/assets/26326692/25073418/c104e42c-22e6-11e7-9222-7ceb31fd60cf.png)
![worms_open_warfare_2-3](https://cloud.githubusercontent.com/assets/26326692/25073419/c4a38bb0-22e6-11e7-85b2-9eebfb203bb2.png)

**Comment by endrift** [comment]
This also appears to have been resolved in the meantime.
