### ISSUE TITLE
Consistant recent states

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#68]
The recent save/load states are independent of each other at the moment. If you save slot two and then load slot one, saving recent will still save in slot two. Saving/loading a different slot should update the recent slots for both saving and loading.

**Comment by endrift** [comment]
That's really strange. There's only one variable for the state slot, so it shouldn't be possible for them to be separate.

**Comment by endrift** [comment]
Yeah, I can't reproduce this.

**Comment by tony971** [comment]
Actually, neither can I. False alarm.
