### ISSUE TITLE
[Regression] Brain Age 2 - fails to boot

### ISSUE THREAD

**Issue by Simonx22** [mgba-emu/mgba#680]
![more_brain_train-1](https://cloud.githubusercontent.com/assets/26326692/25073772/d80775d4-22ed-11e7-91e3-988a49d40d62.png)
It no longer boots in the latest nightly. Maybe related to #677.

**Comment by endrift** [comment]
Fixed in 7879736a44c167373c04c9381218a131ee1bd5c5.
