### ISSUE TITLE
[Non-DS Suggestion] Make the "Sync to Video" feature compatible for low-end PC's. Plus some questions.

### ISSUE THREAD

**Issue by John-Enigma** [mgba-emu/mgba#682]
Is it possible to make the "Sync to Video" feature (which is the one that makes the game appear that it's really running at 60 fps) compatible with less powerful PC's like this [one](https://www.cnet.com/products/gateway-sx2110g-uw24-e1-1500-1-48-ghz-6-gb-500-gb-led-19-5/specs/)?

Also, since mGBA is slowly going the DS route, what's gonna happen to the emulator now? I mean, no offense or anything, but the emulator name says it: it's a Game Boy Advance emulator. I mean what's gonna happen to all the bugfixes for (some, if any) incompatible GBA games? What's gonna happen to the TODO list of missing features of the emulator, like the solar power feature, the e-Reader support, the wireless link, the proposed connection with the Dolphin emulator? Will the full Gameboy (Color) support cease?

Maybe I'm being a bit paranoid? Is just that I don't want this emulator to lose its GBA support.

**Comment by endrift** [comment]
GBA support is not going away. I'm shifting gears a bit, but I still plan to add many GB and GBA features.

Also I don't really think sync to video is broken on slow computers. I'd have to break out my ancient netbook to test it on it to prove that point. I think there was just something odd about your configuration. I can see about testing it on the netbook later.

**Comment by John-Enigma** [comment]
^That's reassuring. Thanks.

Also, I still think the "Sync to Video" feature might still be incompatible with _some_ ancient/slow/low-powered computers (like the one that I posted above). Remember the stuttering that I mentioned you in the past? Who knows if this problem exists to some people and nobody knows about it. But thanks for answering, and knowing that you will look at it in the future.

I'll continue to keep on looking at the future updates.
