### ISSUE TITLE
DBZ Team Training: cannot save

### ISSUE THREAD

**Issue by quyentruong** [mgba-emu/mgba#683]
The error message shows when I launched the game.

![capture](https://cloud.githubusercontent.com/assets/22864140/25119094/be07da62-23cd-11e7-9153-37cc634957bf.JPG)

Link download of the game:
~snip~

**Comment by endrift** [comment]
Please don't attach links to ROMs.

The problem here is probably that the ROM ID changed, so the override for FRLG isn't being applied. Shut down the game, and open the override menu under tools. Then, set GBA savetype to Flash 1M, and (without closing the window), reopen the game.

**Comment by quyentruong** [comment]
Thanks, it works.

what about vita homebrew? It doesn't have override option.

**Comment by endrift** [comment]
Take a look at the config file in %APPDATA%/mGBA/config.ini. There should be a section that starts with `[override` and a four letter code. Copy that whole section into the config file at ux0:/data/mGBA/config.ini to apply it there.

**Comment by quyentruong** [comment]
Thanks, vita can save now.
