### ISSUE TITLE
Sachen GB/GBC Mapper support

### ISSUE THREAD

**Issue by ssjbrollyus** [mgba-emu/mgba#686]
Would it be possible to support both Sachen mappers for GB/GBC games?
Tauwasser has both of them reasonably well documented on his website:
https://wiki.tauwasser.eu/view/Sachen_Mappers

Sachen MMC1 is also already implemented on MAME which also has a preliminary (non-working) implementation of Sachen MMC2. I believe MAME is currently the only emulator to support these.

**Comment by endrift** [comment]
Seems like something @tzlion would know about. This article unfortunately doesn't say what (bootleg I'm assuming) games use this, so I'm not sure how I'd go about finding out.

**Comment by ssjbrollyus** [comment]
I'm not sure if I can mention specific rom details here? I can provide you any info that you need just let me know how I can get that information to you.

Without the risk of breaking any rules you can find out what games use it on MAME softlists under the names "4in1_00x" for GB (These use MMC1) and "mc_sac0x" for GBC (These use MMC2) with x being a number, the mappers they use are actually documented in the softlists already so a simple search for "rom_sachen1" in hash\gameboy.xml or "rom_sachen2" in hash\gbcolor.xml should allow you to easily find out all games that use these mappers.
These are mostly used by Sachen 4-in-1 or 8-in-1 carts that contain Gameboy ports of their MegaDuck games for the most part.

**Comment by noddy360** [comment]
One of these games is called Beast Fighter, which also works on hhugboy.

**Comment by iamthelaw2041** [comment]
Here's a list of Gameboy and Gameboy color games made by Sachen.

![FireShot Capture 011 - DAT-o-MATIC - datomatic no-intro org](https://user-images.githubusercontent.com/94656803/145194567-d16debac-e0a7-49e5-9b9c-2696db45c179.png)

![FireShot Capture 012 - DAT-o-MATIC - datomatic no-intro org](https://user-images.githubusercontent.com/94656803/145194586-26847904-da94-4356-9715-de4f76780132.png)

If support isn't coming anytime soon I think a warning that the mapper is unsupported would be helpful. When I try and load a game all I get is this cryptic message. 

![Capture](https://user-images.githubusercontent.com/94656803/145194817-741b418b-3a5a-4c42-95bb-9c175ddc2249.PNG)

**Comment by endrift** [comment]
Sachen MMC1 is now supported. I will be finishing up Sachen MMC2 tomorrow.

**Comment by endrift** [comment]
Sachen MMC2 is now implemented. Some games still don't work, but the mappers themselves and many games do. Please file individual bugs for the broken games as you come across them.
