### ISSUE TITLE
Super Mario 64 Textures Rendered Differently on Medusa than on DeSmuME

### ISSUE THREAD

**Issue by Buddybenj** [mgba-emu/mgba#687]
I assume DeSmuME is correct.

Medusa:
![Medusa](http://i.imgur.com/bbP8WZd.png)

DeSmuME:
![DeSmuME](http://i.imgur.com/Q6K0tWS.png)

**Comment by Anty-Lemon** [comment]
Checked on console. Medusa's behaviour is correct, Desmume's is not.

**Comment by Buddybenj** [comment]
Thanks for checking
