### ISSUE TITLE
Rayman DS runs "too fast", desyncs

### ISSUE THREAD

**Issue by StapleButter** [mgba-emu/mgba#688]
Seems to be the same timing issue that is affecting several other games.

The game's menu seems to run at normal speed, but skips frames. Which hints that the game detects it's running too slow and tries to compensate with a buggy frameskip system. Music and animations run too fast. During cinematics, the actual action unrolls faster than the subtitle text.

Rayman also runs too fast when playing the game.

In the first level, during the forced encounter with Murfy, there is a chance that Murfy somehow misses his target point, continues moving forever, and the dialogue never starts. Likely a consequence of Murfy moving too fast too.

Just documenting the various consequences of what appears to be the same issue.

**Comment by endrift** [comment]
Please retest after f32fbd7

**Comment by StapleButter** [comment]
it's running at the normal speed now

however there are still parts of the subtitles that disappear
