### ISSUE TITLE
Cursor hides on menu bar

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#69]
The mouse is still functional, but hidden.

**Comment by tony971** [comment]
I went back to reproduce and the cursor only disappeared after the standard timeout. It still shouldn't happen on the menu bar, though.

**Comment by karasuhebi** [comment]
This also happens in Windows.

**Comment by lifning** [comment]
Getting this behavior on Linux (in both xcb and wayland), at least on the [labwc](https://github.com/labwc/labwc/) compositor. In addition to dropdown menus, it also hides the cursor in game state tool windows (tile/map viewers, etc.), but seemingly only if that window is itself in front of the main mgba window.
