### ISSUE TITLE
Golden Sun - Several blocking issues

### ISSUE THREAD

**Issue by agarciabz** [mgba-emu/mgba#690]
On 0.5.2 (2016-12-31), using Windows 10 x64.

So far this playthrough (1h 35m) I've experienced three different issues while playing normally:

1. Crash with an error prompt. Screen is black and sound is mute. (See attachment)
![gs-error](https://cloud.githubusercontent.com/assets/27777512/25297982/a48b07d6-26f1-11e7-934a-c203ee7f8257.png)
2. Crash without prompt. Screen is frozen and sound turns glitchy.
3. Sudden reset.

Due to the random nature of these issues I've been unable to reproduce them whenever I wanted.

**Comment by endrift** [comment]
I've never seen anything like this with Golden Sun. Please verify that you have a good dump. No-Intro values are:

CRC32 e1fb68e8
MD5 1cdd7f33c9a27061201e1d1ce029a700
SHA1 5c4695205413df7db52b9a184815a07783999971
SHA256 c14f1151897e8d73f25ffdd67e21eebb6dc57973ff2458872ee89fa9060aaca1
