### ISSUE TITLE
Qt: Hangs on reset with CLI debugger

### ISSUE THREAD

**Issue by Anty-Lemon** [mgba-emu/mgba#691]
Build: 0.6-4446-69a30f95
OS: Debian 9.0 stretch amd64

If a game is reset while paused by the CLI debugger, the emulator hangs. Also affects shutdown, boot BIOS, and exit.

**Comment by Anty-Lemon** [comment]
Not fixed. Emulator still hangs on reset.

**Comment by Anty-Lemon** [comment]
Fixed by 6fb7c07

**Comment by Anty-Lemon** [comment]
...or not. Hangs inconsistently.

**Comment by endrift** [comment]
Possibly fixed by dc5c59d4dbe157bb1c6fe1e00c0893815723a16b. Please re-test.

**Comment by Anty-Lemon** [comment]
Can't test. dc5c59d causes a regression. Interacting with the toolbar while the CLI debugger has paused the game takes away control of the desktop from me, forcing me to kill the emulator on a different tty.

**Comment by endrift** [comment]
Wait. What? What toolbar? And it's specifically in that commit?

**Comment by Anty-Lemon** [comment]
The main toolbar, with File, Emulation, etc. Reverting the commit fixes the issue

**Comment by endrift** [comment]
Ugh. I'll take a look on Linux and macOS in a bit.

**Comment by endrift** [comment]
Please try again in 6c6d09e.

**Comment by Anty-Lemon** [comment]
Confirmed fixed
