### ISSUE TITLE
Qt: Buttons are not translated on the buildbot nightlies

### ISSUE THREAD

**Issue by rootfather** [mgba-emu/mgba#705]
One minor issue:

The buttons of the Qt GUI are not translated on the buildbot releases. When I compile mGBA/medusa for myself, the buttons are localized correctly. All buttons on all dialogs are affected. See screenshots for reference.

## **buildbot nightly**
![qt buttons not translated in nightly](https://cloud.githubusercontent.com/assets/11882577/25431645/b80e129c-2a81-11e7-80f7-c40d1602aa88.PNG)

## **compiled by myself**
![qt buttons translated](https://cloud.githubusercontent.com/assets/11882577/25431657/c15ca584-2a81-11e7-8689-b9da4f5f696d.PNG)

I think this is most likely a simple configuration issue with the buildbot or some missing package/dependency. This issue persists since the GUI translations were introduced, I just forgot to submit this issue.

**Comment by endrift** [comment]
Oof. I think I know what the issue here is. It might be a pain to fix.

**Comment by waddlesplash** [comment]
Probably qt*.ts files not getting included for static Qt?

**Comment by endrift** [comment]
You are correct, but I have yet to figure out why they aren't being built in the first place; the dependencies script I have (https://github.com/mgba-emu/dependencies/blob/master/buildscripts/configure-qt.sh) seems to skip that entire folder.

**Comment by endrift** [comment]
looks like when I skipped qttools it skipped qttranslations too. Rebuilding now.

**Comment by endrift** [comment]
Fixed in 253719d7a14e0002c8e987beff4c6a6a3604704f.
