### ISSUE TITLE
Offset in 3D viewport (Phoenix Wright: Ace Attorney)

### ISSUE THREAD

**Issue by Kyrio** [mgba-emu/mgba#709]
When examining 3D evidence in Phoenix Wright: Ace Attorney (fifth case) on medusa (alpha 2), you'll notice that the model appears lower on the screen that it's supposed to. Zooming in will show that the game doesn't draw in the top 192x40 rectangle of the 3D screen. It's a minor bug but I'm guessing this has to do with the viewport dimensions.

Edit: Here's a [save file](https://www.dropbox.com/s/0bh15exx0mc49vq/PW_us_Case5_Medusa.sav?dl=0) for debugging purposes.

![pw-aa-1](https://cloud.githubusercontent.com/assets/3719464/25482334/9399c8e0-2b51-11e7-9774-6e3e2de2a66c.png)
![pw-aa-0](https://cloud.githubusercontent.com/assets/3719464/25482337/962dc9d0-2b51-11e7-92f3-11ff332ffce0.png)

**Comment by Anty-Lemon** [comment]
Can you provide a save file, to make debugging easier?

**Comment by Kyrio** [comment]
Sure! [This one](https://transfer.sh/ephWL/PW-AA.sav) is for the US version.

**Comment by endrift** [comment]
I think @Gericom has a patch that would fix this from #660, but it didn't get merged yet due to some minor issues.

**Comment by Gericom** [comment]
Yes, I think it will fix it. I'll split up the commit soon.

**Comment by Kyrio** [comment]
@Gericom Any progress on that issue? :)

**Comment by endrift** [comment]
Last I heard, Gericom has been too busy with other stuff. Once I get back to medusa (probably next month, if not late this month), I can just merge the appropriate half of this patch manually. Assuming that's ok with Gericom.

**Comment by Kyrio** [comment]
Okay, thanks for the update! :slightly_smiling_face:

**Comment by endrift** [comment]
Fixed in 9dfcef3f45efe580e252ec8bc3852257e9de9fd6.
