### ISSUE TITLE
Sims 2 - music is way too fast

### ISSUE THREAD

**Issue by Simonx22** [mgba-emu/mgba#710]
The ingame music is way too fast.

**Comment by SuperFlomm** [comment]
This refers to the DS version of The Sims 2.

**Comment by StapleButter** [comment]
chances are your ARM9 timers are running twice at the normal speed, or something of that ilk

I recall causing similar issues when I was trying to fix timing issues in melonDS, and it was caused by running ARM9 timers twice too much

**Comment by StapleButter** [comment]
nevermind. I guess this is a way old issue that was not closed, the problem isn't present on most recent medusa.
