### ISSUE TITLE
3ds Pokemon fire red sound issue

### ISSUE THREAD

**Issue by Klauserus** [mgba-emu/mgba#721]
Hi
I use the mgba nightly version from yesterday. The sound have slowmos after fights. Heavy slowly sound can you hear in Vertania City, Pokémon Center when you enter the escalator. 

I use a 3ds Xl. mGBA Version: 

mGBA-nightly-2017-04-28-3ds-a5f029c2faa14f9e65d6c8413498057348100ede

If you need a save state, let me know

**Comment by Klauserus** [comment]
hi

i read on twitter that 3ds get a performance update. I test mgba Version from 2017-08-16. The issue is the same like up. i make a Video (it starts 00:36)

<a href=http://www.filedropper.com/maq01298><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >file backup online</a></div>

The Wii Version dont have this issue.

Thank you

**Comment by zeromus** [comment]
So you want to predicate a bug report on a tweet.

step 1. link to the tweet

**Comment by endrift** [comment]
It's a tweet I made and I know which one.

**Comment by endrift** [comment]
That said, this isn't a bug, it's just the emulator slowing down under load. I'd like to get more performance improvements in but I'm at my wit's end tbh. Without a dynrec this is probably not going to be fixed.
