### ISSUE TITLE
Diddy Kong Pilot 2001 and 2003 Prototypes - Illegal opcode: 0000b710 on startup

### ISSUE THREAD

**Issue by GeekyFerret** [mgba-emu/mgba#722]
https://tcrf.net/Proto:Banjo-Pilot/Diddy_Kong_Pilot_2001
https://tcrf.net/Proto:Banjo-Pilot/Diddy_Kong_Pilot_2003

Both games crash on startup.

**Comment by endrift** [comment]
That opcode means it jumped to invalid memory, for some reason. On one of those I checked and it jumps past the end of the ROM file, so...not much that can be done there. Dunno about the other one.

**Comment by Catarax** [comment]
Hello endrift,
I tried to play the game on Mednafen and mGba without success however I confirm that the no-intro prototype of Diddy Kong Pilot runs on VBA-M (sourceforge), apparently only VisualBoyAdvance is able to handle this game.

**Comment by JMC47** [comment]
Does it run if you try to run it on a real GBA?

**Comment by Catarax** [comment]
Can't test but the game was dumped from a working cartridge I guess.

**Comment by endrift** [comment]
The dumps are weird because they have different behavior depending if out of bounds addresses are open cartridge bus or read zeros. I did fix this at one point.
