### ISSUE TITLE
[Wii] Configure GB and GBC BIOS on Wii Port

### ISSUE THREAD

**Issue by nateify** [mgba-emu/mgba#724]
There are no menu options or `config.ini` options in mGBA for Wii to use the GB or GBC BIOS files. Only the GBA BIOS is accepted as a valid BIOS file in the options.

**Comment by endrift** [comment]
in config.ini you can set `gb.bios` and `gbc.bios`. I think that might be new in the nightlies though.

**Comment by endrift** [comment]
Fixed in 6f5ec7d5e46a22524fa0e4f1b1f46582a28b4101.
