### ISSUE TITLE
Video Recording - Allow For OGG Theora

### ISSUE THREAD

**Issue by wildgoosespeeder** [mgba-emu/mgba#725]
Unless I don't see it, it seems like the OGG standard only allows for audio recording. There is video recording as well called *Theora* by **Xiph.Org Foundation**:

* https://en.wikipedia.org/wiki/Ogg - Container
* https://en.wikipedia.org/wiki/Theora - Lossy video format
* https://en.wikipedia.org/wiki/Vorbis - Lossy audio format (deprecated)
* https://en.wikipedia.org/wiki/Opus_(audio_format) - Lossy audio format (newer)
* https://wiki.xiph.org/MIME_Types_and_File_Extensions - Other information

All I see for profiles are:

* High Quality
* YouTube
* WebM (by Google)
* Lossless

Advanced shows OGG Vorbis and Opus. OGG/OGV/OGA are showing prominence with HTML5 alongside MP4 and WebM formats, so it might be a good idea for mGBA to support Theora video recording.

On an unrelated note, VP8 is an older compression format for WebM. VP9 is newer.

**Comment by endrift** [comment]
You can type whatever you want in those fields, and it'll prompt ffmpeg to see if it has the codec. If your build of ffmpeg has theora support, it'll work. However, I have no intention of shipping theora with mGBA on Windows or macOS what with vpx being around.

**Comment by wildgoosespeeder** [comment]
It's not very clear how to do so. Can you show me screenshots how things should be set? This is kind of why a preset, not necessarily the Theora codec library, would be a good idea. If you still don't think it would be a good idea, what about RAW (uncompressed) video output, similar to how Snes9x can do that? Then I can just use an external program to convert properly to the video container using Vorbis/Opus for the audio and Theora for the video.

**Comment by kode54** [comment]
Does anyone even use Theora anymore in TYOOL 2017? All of the browsers that support Theora also support WebM now. The ones that don't are still limited to H.264 in MP4, unless you feel like shipping Javascript polyfills, which defeat the purpose of being lightweight by doing all of the decoding in scripted software.

**Comment by wildgoosespeeder** [comment]
For as long as it is supported in HTML5 specs, mGBA should support OGG Theora as well as WebM or MP4 recordings, but it seems @endrift doesn't want to include it, and I don't know why.

**Comment by endrift** [comment]
HTML5 does't specify which codecs "should" be supported. No one uses Theora. Your definition of what mGBA "should" do doesn't reflect any actual use case.
