### ISSUE TITLE
Request : Add gbc bios et gb bios in firmwares (optional) on retroarch 

### ISSUE THREAD

**Issue by wwark** [mgba-emu/mgba#727]
Hello,

Could you please add the gb and gbc bios on retroarch ?

Thanks,
Wark

**Comment by Papermanzero** [comment]
At least the option to change the hardware device (super gameboy, gameboy color, gameboy advance etc) would be helpful.
Some games (e.g. zelda oracle) uses gbc and gba features. So it is useful to change the gameboy hardware.

**Comment by endrift** [comment]
Fixed in ffbf509f5a75bec09969b454ec4eb363c3557f10.
