### ISSUE TITLE
Qt: Move frameAvailable signal to GUI thread

### ISSUE THREAD

**Issue by endrift** [mgba-emu/mgba#728]
The `GameController::frameAvailable` signal gets sent from the CPU thread to the GUI thread, but this can cause a ton of race conditions. It should be quickly marshaled to the main thread from the CPU thread and then dispatched from there. Possibly related to #639.

**Comment by waddlesplash** [comment]
Would using Qt::BlockingQueuedConnection be acceptable here? That should preserve the present behavior (i.e. emit() blocks until the signal is handled) while also removing the race condition (the signal is marshalled to the main thread).

**Comment by endrift** [comment]
I think that might cause deadlocks, e.g. if the main thread tries to interrupt the CPU thread after the CPU thread tries to marshal the signal but before it gets handled.

**Comment by waddlesplash** [comment]
OK, so I tried adding `Qt::BlockingQueuedConnection` to all the frameAvailable signals and ... it half-deadlocks. Meaning there isn't any video output, but audio chugs along just fine.

Would a plain Qt::QueuedConnection be okay then? Or does that add too much latency or something?

**Comment by waddlesplash** [comment]
I could also try to trace where the deadlocks are coming from and fix that.

**Comment by endrift** [comment]
Er. That sounds like a bug elsewhere. If the audio keeps going, it's not deadlocked; the video just is getting lost.

**Comment by endrift** [comment]
The goal here is to leave all of the `frameAvailable` connections as-is but have a sort of "private" version that the CPU thread uses to send the frame to the main thread.

**Comment by waddlesplash** [comment]
So, I replaced all the CPU->main thread connections with Qt::QueuedConnection, and then wired up a QElapsedTimer on both sides of the emit(), and got a lot of output that looked like this:
```
GameController::frameAvailable!0x12269551ed0 13210
DisplayGL::framePosted!0x12269551ed0 13210
GameController::frameAvailable!0x12269551ed0 13240
DisplayGL::framePosted!0x12269551ed0 13240
GameController::frameAvailable!0x12269551ed0 13250
DisplayGL::framePosted!0x12269551ed0 13250
GameController::frameAvailable!0x12269551ed0 13261
DisplayGL::framePosted!0x12269551ed0 13261
GameController::frameAvailable!0x12269551ed0 13280
DisplayGL::framePosted!0x12269551ed0 13280
GameController::frameAvailable!0x12269551ed0 13290
DisplayGL::framePosted!0x12269551ed0 13290
GameController::frameAvailable!0x12269551ed0 13320
DisplayGL::framePosted!0x12269551ed0 13320
```
Left-hand side is method name, right hand side pointer is the passed pointer (so you can see they're the same) and then the last number is the elapsed ms of the global timer. So it looks like the signals are getting marshalled through the queue in the sub-ms range, so it looks like just a straight QueuedConnection is OK here, and we don't need a custom routing system?

**Comment by endrift** [comment]
I mean that's the way it already was, wasn't it? Queued.

**Comment by waddlesplash** [comment]
Possibly, I didn't check, but it wasn't explicitly set anywhere from what I could see (I added Qt::QueuedConnection to the end of all connect()s involving frameAvailable outside of GameController itself.) So, what scenarios are there in which there are race conditions? AFAIK, QueuedConnections are a FIFO internally in Qt's event dispatcher...

**Comment by endrift** [comment]
The specific problem is thus:

- User tries to start new game
- Old game gets shutdown signal
- CPU thread starts to wind down
- CPU thread sends off one final frame, which gets queued *after* the signal for opening the new game gets inserted
- New game is opened
- Old frame is processed, but the back buffer is now the wrong size since we didn't copy the frame out in time
- Memory errors -> crash

So the problem mostly lies with the ordering of the signals being inserted into the FIFO.

That said, I'm not sure why I thought this would fix that race condition...

**Comment by endrift** [comment]
A good way to test for this is to load a GBA game, then a GB game, and then hold down Ctrl-1 with a high enough key repeat rate, which causes mGBA to rapidly switch between a GBA and GB game being loaded.

**Comment by waddlesplash** [comment]
Ah, that sounds interesting. Will test.

**Comment by waddlesplash** [comment]
OK, I did manage to reproduce a crash this way. I wonder if we should change the frameAvailable signal to use a pointer-to-a-pointer so it can get "revoked" by the GameController?

**Comment by endrift** [comment]
That...sure is one way to...ugh...no. There are far better ways of doing this than that.

**Comment by waddlesplash** [comment]
Alright, I'll just leave this as-is and let you solve it then.

**Comment by endrift** [comment]
Ok, I'll try to get to it at some point.
