### ISSUE TITLE
Golden Sun games cannot soft reset

### ISSUE THREAD

**Issue by ruadath** [mgba-emu/mgba#733]
The A+B+S+s input does not cause the soft reset on any of the Japanese, US, or European version of these games. I already check for N-key rollout and other minor issues, so its confirmed that this is an actual problem with the emulation.

endrift said something about keypad IRQs not being implemented on IRC.

**Comment by endrift** [comment]
I have not verified that this is a keypad IRQ issue, but I have been meaning to implement it and it's a sensible thing to do with keypad IRQs.

**Comment by endrift** [comment]
Verified the settings for keypad IRQ would indicate that this is the issue.

<img width="359" alt="screen shot 2017-05-10 at 4 52 57 pm" src="https://cloud.githubusercontent.com/assets/605502/25926029/57403ba4-35a1-11e7-931c-2231f55e8f0c.png">
