### ISSUE TITLE
OpenBSD: Bus error when deleting breakpoint

### ISSUE THREAD

**Issue by bentley** [mgba-emu/mgba#74]
$ egdb mgba      
    GNU gdb (GDB) 7.9.1
    Copyright (C) 2015 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-unknown-openbsd5.8".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from mgba...done.
    (gdb) run rom.gba
    Starting program: /usr/local/bin/mgba -d rom.gba
    00000000 00000000 00000000 00000000
    00000000 00000000 00000000 00000000
    00000000 00000000 00000000 00000000
    00000000 03007F00 00000000 00000004
    0000001F [-------]
    00000000:  EA000006     b $00000020
    > b 0
    > d 0
    [New thread 1025814]
    [New thread 1028073]
    [New thread 1009832]
    
    Program received signal SIGBUS, Bus error.
    [Switching to thread 1025814]
    0x00000e471d1d281a in _thread_sys___thrsleep () at <stdin>:2
    2       <stdin>: No such file or directory.
    (gdb) bt
    #0  0x00000e471d1d281a in _thread_sys___thrsleep () at <stdin>:2
    #1  0x00000e4795ab9ce1 in pthread_cond_timedwait (
        condp=condp@entry=0x7f7ffffc5358, mutexp=<optimized out>, 
        mutexp@entry=0x7f7ffffc5350, abstime=abstime@entry=0x7f7ffffc5000)
        at /usr/src/lib/librthread/rthread_sync.c:354
    #2  0x00000e47e3c997a7 in ConditionWaitTimed (timeoutMs=50, 
        mutex=0x7f7ffffc5350, cond=0x7f7ffffc5358)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/posix/threading.h:64
    #3  GBASyncWaitFrameStart (sync=sync@entry=0x7f7ffffc5340, frameskip=0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/gba/supervisor/sync.c:58
    #4  0x00000e44f3905330 in GBASDLGLRunloop (context=0x7f7ffffc5200, 
        renderer=0x7f7ffffc53b0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/gl-sdl.c:98
    #5  0x00000e44f39050e8 in main (argc=<optimized out>, argv=<optimized out>)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/main.c:131

**Comment by endrift** [comment]
This thread doesn't look like it's the crashing one. Can you inspect some other threads? This is a really weird place for a thread to crash.

**Comment by bentley** [comment]
(gdb) thread 1
    [Switching to thread 1 (thread 1026321)]
    #0  0x000000f89bf0d81a in _thread_sys___thrsleep () at <stdin>:2
    2       in <stdin>
    (gdb) bt
    #0  0x000000f89bf0d81a in _thread_sys___thrsleep () at <stdin>:2
    #1  0x000000f8f4487ce1 in pthread_cond_timedwait (
        condp=condp@entry=0x7f7ffffbaf58, mutexp=<optimized out>, 
        mutexp@entry=0x7f7ffffbaf50, abstime=abstime@entry=0x7f7ffffbac00)
        at /usr/src/lib/librthread/rthread_sync.c:354
    #2  0x000000f88dbb77a7 in ConditionWaitTimed (timeoutMs=50, 
        mutex=0x7f7ffffbaf50, cond=0x7f7ffffbaf58)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/posix/threading.h:64
    #3  GBASyncWaitFrameStart (sync=sync@entry=0x7f7ffffbaf40, frameskip=0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/gba/supervisor/sync.c:58
    #4  0x000000f62a905330 in GBASDLGLRunloop (context=0x7f7ffffbae00, 
        renderer=0x7f7ffffbafb0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/gl-sdl.c:98
    #5  0x000000f62a9050e8 in main (argc=<optimized out>, argv=<optimized out>)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/main.c:131
    (gdb) thread 2
    [Switching to thread 2 (thread 1016939)]
    #0  0x000000f89bf0d81a in _thread_sys___thrsleep () at <stdin>:2
    2       in <stdin>
    (gdb) bt
    #0  0x000000f89bf0d81a in _thread_sys___thrsleep () at <stdin>:2
    #1  0x000000f8f4487ce1 in pthread_cond_timedwait (
        condp=condp@entry=0x7f7ffffbaf58, mutexp=<optimized out>, 
        mutexp@entry=0x7f7ffffbaf50, abstime=abstime@entry=0x7f7ffffbac00)
        at /usr/src/lib/librthread/rthread_sync.c:354
    #2  0x000000f88dbb77a7 in ConditionWaitTimed (timeoutMs=50, 
        mutex=0x7f7ffffbaf50, cond=0x7f7ffffbaf58)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/posix/threading.h:64
    #3  GBASyncWaitFrameStart (sync=sync@entry=0x7f7ffffbaf40, frameskip=0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/gba/supervisor/sync.c:58
    #4  0x000000f62a905330 in GBASDLGLRunloop (context=0x7f7ffffbae00, 
        renderer=0x7f7ffffbafb0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/gl-sdl.c:98
    #5  0x000000f62a9050e8 in main (argc=<optimized out>, argv=<optimized out>)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/main.c:131
    (gdb) thread 3
    [Switching to thread 3 (thread 1003619)]
    #0  0x000000f89bf0d81a in _thread_sys___thrsleep () at <stdin>:2
    2       in <stdin>
    (gdb) bt
    #0  0x000000f89bf0d81a in _thread_sys___thrsleep () at <stdin>:2
    #1  0x000000f8f4487ce1 in pthread_cond_timedwait (
        condp=condp@entry=0x7f7ffffbaf58, mutexp=<optimized out>, 
        mutexp@entry=0x7f7ffffbaf50, abstime=abstime@entry=0x7f7ffffbac00)
        at /usr/src/lib/librthread/rthread_sync.c:354
    #2  0x000000f88dbb77a7 in ConditionWaitTimed (timeoutMs=50, 
        mutex=0x7f7ffffbaf50, cond=0x7f7ffffbaf58)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/posix/threading.h:64
    #3  GBASyncWaitFrameStart (sync=sync@entry=0x7f7ffffbaf40, frameskip=0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/gba/supervisor/sync.c:58
    #4  0x000000f62a905330 in GBASDLGLRunloop (context=0x7f7ffffbae00, 
        renderer=0x7f7ffffbafb0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/gl-sdl.c:98
    #5  0x000000f62a9050e8 in main (argc=<optimized out>, argv=<optimized out>)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/main.c:131
    (gdb) thread 4
    [Switching to thread 4 (thread 1001991)]
    #0  0x000000f89bf0d81a in _thread_sys___thrsleep () at <stdin>:2
    2       in <stdin>
    (gdb) bt
    #0  0x000000f89bf0d81a in _thread_sys___thrsleep () at <stdin>:2
    #1  0x000000f8f4487ce1 in pthread_cond_timedwait (
        condp=condp@entry=0x7f7ffffbaf58, mutexp=<optimized out>, 
        mutexp@entry=0x7f7ffffbaf50, abstime=abstime@entry=0x7f7ffffbac00)
        at /usr/src/lib/librthread/rthread_sync.c:354
    #2  0x000000f88dbb77a7 in ConditionWaitTimed (timeoutMs=50, 
        mutex=0x7f7ffffbaf50, cond=0x7f7ffffbaf58)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/posix/threading.h:64
    #3  GBASyncWaitFrameStart (sync=sync@entry=0x7f7ffffbaf40, frameskip=0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/gba/supervisor/sync.c:58
    #4  0x000000f62a905330 in GBASDLGLRunloop (context=0x7f7ffffbae00, 
        renderer=0x7f7ffffbafb0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/gl-sdl.c:98
    #5  0x000000f62a9050e8 in main (argc=<optimized out>, argv=<optimized out>)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/main.c:131

**Comment by endrift** [comment]
...These are all the same backtrace, regardless of thread. Huh??

**Comment by bentley** [comment]
(gdb) thread apply all backtrace
    
    Thread 4 (thread 1001991):
    #0  0x000000f89bf0d81a in _thread_sys___thrsleep () at <stdin>:2
    #1  0x000000f8f4487ce1 in pthread_cond_timedwait (
        condp=condp@entry=0x7f7ffffbaf58, mutexp=<optimized out>, 
        mutexp@entry=0x7f7ffffbaf50, abstime=abstime@entry=0x7f7ffffbac00)
        at /usr/src/lib/librthread/rthread_sync.c:354
    #2  0x000000f88dbb77a7 in ConditionWaitTimed (timeoutMs=50, 
        mutex=0x7f7ffffbaf50, cond=0x7f7ffffbaf58)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/posix/threading.h:64
    #3  GBASyncWaitFrameStart (sync=sync@entry=0x7f7ffffbaf40, frameskip=0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/gba/supervisor/sync.c:58
    #4  0x000000f62a905330 in GBASDLGLRunloop (context=0x7f7ffffbae00, 
        renderer=0x7f7ffffbafb0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/gl-sdl.c:98
    #5  0x000000f62a9050e8 in main (argc=<optimized out>, argv=<optimized out>)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/main.c:131
    
    Thread 3 (thread 1003619):
    #0  0x000000f89bf0d81a in _thread_sys___thrsleep () at <stdin>:2
    #1  0x000000f8f4487ce1 in pthread_cond_timedwait (
        condp=condp@entry=0x7f7ffffbaf58, mutexp=<optimized out>, 
        mutexp@entry=0x7f7ffffbaf50, abstime=abstime@entry=0x7f7ffffbac00)
        at /usr/src/lib/librthread/rthread_sync.c:354
    #2  0x000000f88dbb77a7 in ConditionWaitTimed (timeoutMs=50, 
        mutex=0x7f7ffffbaf50, cond=0x7f7ffffbaf58)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/posix/threading.h:64
    #3  GBASyncWaitFrameStart (sync=sync@entry=0x7f7ffffbaf40, frameskip=0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/gba/supervisor/sync.c:58
    #4  0x000000f62a905330 in GBASDLGLRunloop (context=0x7f7ffffbae00, 
        renderer=0x7f7ffffbafb0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/gl-sdl.c:98
    #5  0x000000f62a9050e8 in main (argc=<optimized out>, argv=<optimized out>)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/main.c:131
    
    Thread 2 (thread 1016939):
    #0  0x000000f89bf0d81a in _thread_sys___thrsleep () at <stdin>:2
    #1  0x000000f8f4487ce1 in pthread_cond_timedwait (
        condp=condp@entry=0x7f7ffffbaf58, mutexp=<optimized out>, 
        mutexp@entry=0x7f7ffffbaf50, abstime=abstime@entry=0x7f7ffffbac00)
        at /usr/src/lib/librthread/rthread_sync.c:354
    #2  0x000000f88dbb77a7 in ConditionWaitTimed (timeoutMs=50, 
        mutex=0x7f7ffffbaf50, cond=0x7f7ffffbaf58)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/posix/threading.h:64
    #3  GBASyncWaitFrameStart (sync=sync@entry=0x7f7ffffbaf40, frameskip=0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/gba/supervisor/sync.c:58
    #4  0x000000f62a905330 in GBASDLGLRunloop (context=0x7f7ffffbae00, 
        renderer=0x7f7ffffbafb0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/gl-sdl.c:98
    #5  0x000000f62a9050e8 in main (argc=<optimized out>, argv=<optimized out>)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/main.c:131
    
    Thread 1 (thread 1026321):
    #0  0x000000f89bf0d81a in _thread_sys___thrsleep () at <stdin>:2
    #1  0x000000f8f4487ce1 in pthread_cond_timedwait (
        condp=condp@entry=0x7f7ffffbaf58, mutexp=<optimized out>, 
        mutexp@entry=0x7f7ffffbaf50, abstime=abstime@entry=0x7f7ffffbac00)
        at /usr/src/lib/librthread/rthread_sync.c:354
    #2  0x000000f88dbb77a7 in ConditionWaitTimed (timeoutMs=50, 
        mutex=0x7f7ffffbaf50, cond=0x7f7ffffbaf58)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/posix/threading.h:64
    #3  GBASyncWaitFrameStart (sync=sync@entry=0x7f7ffffbaf40, frameskip=0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/gba/supervisor/sync.c:58
    #4  0x000000f62a905330 in GBASDLGLRunloop (context=0x7f7ffffbae00, 
        renderer=0x7f7ffffbafb0)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/gl-sdl.c:98
    #5  0x000000f62a9050e8 in main (argc=<optimized out>, argv=<optimized out>)
        at /usr/ports/pobj/mgba-0.2.1/mgba-fa7660020f276de6dac05db2d4d3078b741faf93/src/platform/sdl/main.c:131

**Comment by endrift** [comment]
What a strange state this has gotten into that all of the threads are showing the same backtrace.

**Comment by endrift** [comment]
Probably fixed in 3a9ac188d40abee8689126bc0bf1a5b85054f625. Please reopen if it's not.
