### ISSUE TITLE
Acrobat Kid (J) graphical issue GBA

### ISSUE THREAD

**Issue by gadesx** [mgba-emu/mgba#743]
I tried the japanese version of Aero the acrobat "Acrobat Kid (J)"
with mGBA 0.5.2 and latest nightly 0.6-4531-29d1da6 (Windows)

Just in title screen, pressing start appear a black line flashing.
Checking tools > Game log says: 
"[GAME ERROR] GBA I/O:	Read from write-only I/O register: 0DC"

![acrobat kid j -0](https://cloud.githubusercontent.com/assets/2506953/26331956/25bdc3b4-3f54-11e7-90a6-922b94133ff0.png)

**Comment by JMC47** [comment]
Confirmed

**Comment by endrift** [comment]
This appears to be caused by one of the two backgrounds it flips between (which are in theory identical) having a small region of the background blacked out. This causes the flicker.

I haven't yet tracked down why one of them has that line blacked out.

**Comment by endrift** [comment]
This happens because a VRAM DMA into OBJ RAM overflows (goes past 0x06018000) and wraps back around into the mirrored extension of BG RAM (0x06010000+). Will need to do hardware tests to see what the right behavior here is.
