### ISSUE TITLE
Lady Sia blue line, I want to help

### ISSUE THREAD

**Issue by meepingsnesroms** [mgba-emu/mgba#744]
My email address is guicrith@insiberia.net and I would like to work on this bug.

**Comment by endrift** [comment]
Good luck.

**Comment by meepingsnesroms** [comment]
Wow, quick response, could I please have your existing save state so I dont have to plat through the whole game and whatever else that might help (disassembly, sram file).

**Comment by endrift** [comment]
Here's a save file: [lady-sia.zip](https://github.com/mgba-emu/mgba/files/1039906/lady-sia.zip) It's easy to get to the level from here.

**Comment by meepingsnesroms** [comment]
I found something that is wrong, BG1VOFS goes up to 295 when the bg1 size is set to 256x256

**Comment by endrift** [comment]
That value almost certainly wraps...

**Comment by meepingsnesroms** [comment]
To where, x can wraparound to y + 1 but this is on the y axis.
Are you saying that the gba does this:
if(BG1VOFS > max_y){
BG1VOFS = BG1VOFS % max_y;
}

But in hardware?

**Comment by zeromus** [comment]
The hardware does bg_line = (vofs+scanline)%max_y
You need to read a basic tutorial on scanline based tile engine rendering before you can help here.

**Comment by meepingsnesroms** [comment]
Is an HLE patch ok, like adding +=3 to the bg1 start line in that level?
This would patch the ROM on launch with the new offset, not check what game it is every frame.
I am asking because I know some may not want this in there emulator.

**Comment by endrift** [comment]
That's called a "game specific hack" and it's absolutely not acceptable.

**Comment by meepingsnesroms** [comment]
Do you know if this happens on the GBMicro, DS, DS lite or revok101?
Sorry for asking so much but I have no testing hardware.(Not even a gba)
I do have a DSLite but lack a GBA flash cart.

I think it is caused by audio being slightly faster here than on a gba so it switches before it reaches the proper scanline.

**Comment by Squall-Leonhart** [comment]
could be just my old video driver, but Lady Sia still displays the blue line on OpenGL unless forced to 1.x or i set the video renderer to software.
