### ISSUE TITLE
Qt: Video Layer checkboxes don't correctly represent state after Shutdown->Load ROM

### ISSUE THREAD

**Issue by sn0w75** [mgba-emu/mgba#747]
OS: Ubuntu 14.04 64-bit
mGBA v0.6-4553-d240272 (compiled from source)
Tested with: Pokemon Crystal

Reproducing this bug should be possible with just about any GameBoy (GB/CGB) title. (I haven't tested GBA titles but a similar issue may occur when emulating GBA games as well.)

Reproduction steps are straightforward:

1. File-> Load ROM -> pick any GameBoy title
2. Audio/Video -> Video Layers -> turn off any of the three layers (Background/Objects/Window)
3. Emulation -> Shutdown
4. File -> Recent -> re-load the ROM you had open (or open a different GameBoy ROM)
5. Any layers you turned off for step 2 will not show now!
6. Go to Audio/Video -> Video Layers, all three layers will have their checkboxes checked, despite some of the video layers actually being disabled.
7. To re-enable the video layer, you'll have to select the video layer twice- first time will just un-check the checkbox without effectively changing anything in regards to the display of video layers, second time will properly re-enable the video layer.

I have not tested any of these cases, but similar issues might be occuring for the Audio Channels during GameBoy emulation, as well as the Video Layers and Audio Channels during GBA emulation (same goes for NDS/medusa). Might be worth checking those out to make sure they're functioning properly while fixing this bug.

I discovered this issue while writing some GameBoy software in assembly- I would toggle some video layers, only to discover things I was drawing to the screen mysteriously disappeared the next time I loaded the ROM! I went ahead and tested with a commercial game ROM as well (Pokemon Crystal) just as a sanity check.

Cheers, and let me know if you need anything else!

EDIT: I've discovered similar behavior when using Emulation->Pause.
If you choose Emulation->Pause, then Emulation->Shutdown, then load another GameBoy ROM, the Pause checkbox will still be checked upon boot, despite emulation no longer being paused.

**Comment by endrift** [comment]
I'm pretty sure I fixed this a while ago. Please comment if I'm mistaken and I'll reopen it.
