### ISSUE TITLE
Donkey Kong Country (Game Boy Color) - Graphic glitches in game

### ISSUE THREAD

**Issue by GeekyFerret** [mgba-emu/mgba#748]
In the Game Boy Color Donkey Kong Country, sprites and certain background elements will be overwritten with other graphics.

In this screenshot, Donkey Kong's sprite is overwritten with the enemy sprite and the tree is partially overwritten with a number 3 sprite near the top.
![donkey kong country usa europe en fr de es it -0](https://cloud.githubusercontent.com/assets/28161000/26804749/b8f6e826-4a0e-11e7-948a-4a1324d1b201.png)

**Comment by endrift** [comment]
This seems to have been fixed by now.
