### ISSUE TITLE
Donkey Kong Country (Game Boy Color) & Perfect Dark (Game Boy Color) - Sound samples don't play

### ISSUE THREAD

**Issue by GeekyFerret** [mgba-emu/mgba#749]
In the Game Boy Color games Donkey Kong Country and Perfect Dark, all sound samples don't play. 

Donkey Kong Country only uses them in the fishing bonus game. [Example](https://www.youtube.com/watch?v=NMuPBXNcUVE).

Perfect Dark uses sound samples many times throughout the game (Nintendo/Rare logo animations, voice acting, and most in game sound effects). [Example](https://www.youtube.com/watch?v=xeLNNsVPSCA).

**Comment by endrift** [comment]
wrong number
