### ISSUE TITLE
If a bios is used in GB and GBC games, the game will not boot

### ISSUE THREAD

**Issue by GeekyFerret** [mgba-emu/mgba#750]
If a bios is used in a Game Boy or Game Boy Color game, it will not boot. GB games will usually display the Nintendo logo once and then white screen. GBC games will display the Game Boy logo animation repeatedly and never boot the game. This doesn't appear to affect GBA games.

Alleyway overwrites the Nintendo logo with other graphics.
![alleyway ja -0](https://cloud.githubusercontent.com/assets/28161000/26805596/35564c1a-4a12-11e7-9015-f1993a8beebd.png)

Game & Watch Gallery has graphical glitches in the bios.
![game watch gallery u s -0](https://cloud.githubusercontent.com/assets/28161000/26805672/9a668af2-4a12-11e7-8b8b-4ec3e22cc380.png)

**Comment by endrift** [comment]
This...should have been fixed a few days ago. Have you checked latest nightlies?

**Comment by GeekyFerret** [comment]
Retested in the June 6th nightly and now it's working.
