### ISSUE TITLE
Spyro: season of ice NPC dialogue graphical glitches

### ISSUE THREAD

**Issue by LinAGKar** [mgba-emu/mgba#752]
There are some trash pixels above the text when talking to people in Spyro: season of ice. It was previously reported [here](https://endrift.com/mgba/bugs/show_bug.cgi?id=232). Strangely, it only seems to appear if you let the intro cutscene play for a bit when you start a new game. If you wait a few seconds, until the next frame shows up, and then skip the cutscene, the bug happens, However, if you immediately press start at the start of the cutcene to skip it, it does not happen, though you still get a similar bug where the bottom pixel row of low characters on the row above are visible. For example [here](https://user-images.githubusercontent.com/3390621/27157715-5c32ae8e-5163-11e7-8e84-bf4ea4ff5328.png) the red row at the top of the dialogue is from a g on the row above.

**Comment by endrift** [comment]
Thanks for copying this over. I tend to lose track of bugs on the old bugzilla.

I...wonder if this is the same root cause as the Lady Sia bug.
