### ISSUE TITLE
Load New Shader default path

### ISSUE THREAD

**Issue by sergiobenrocha2** [mgba-emu/mgba#767]
seems "Load New Shader" default path is the ROM path, it should be /usr/share/mgba/shaders/ on linux for example

ubuntu 17.04

**Comment by endrift** [comment]
Strange. It works fine on macOS.

**Comment by sergiobenrocha2** [comment]
And when I try to set it out, I can't:

![image](https://user-images.githubusercontent.com/5431285/27721701-7f496044-5d38-11e7-9a1a-751fe527f8c3.png)

**Comment by endrift** [comment]
I'm not at my Linux computer at the moment, but see if this patch fixes it (and make sure a .deb that's generated puts the .desktop in the right place):

```diff
diff --git a/src/platform/qt/CMakeLists.txt b/src/platform/qt/CMakeLists.txt
index 088e26d..a41e422 100644
--- a/src/platform/qt/CMakeLists.txt
+++ b/src/platform/qt/CMakeLists.txt
@@ -209,7 +209,7 @@ if(NOT DEFINED DATADIR)
 	if(APPLE)
 		set(DATADIR Applications/${PROJECT_NAME}.app/Contents/Resources)
 	else()
-		set(DATADIR ${CMAKE_INSTALL_DATADIR}/${BINARY_NAME})
+		set(DATADIR ${CMAKE_INSTALL_FULL_DATADIR}/${BINARY_NAME})
 	endif()
 endif()
 install(DIRECTORY ${CMAKE_SOURCE_DIR}/res/shaders DESTINATION ${DATADIR} COMPONENT ${BINARY_NAME}-qt)
@@ -253,7 +253,7 @@ install(TARGETS ${BINARY_NAME}-qt
 if(UNIX AND NOT APPLE)
 	find_program(DESKTOP_FILE_INSTALL desktop-file-install)
 	if(DESKTOP_FILE_INSTALL)
-		install(CODE "execute_process(COMMAND ${DESKTOP_FILE_INSTALL} \"${CMAKE_SOURCE_DIR}/res/mgba-qt.desktop\" --dir \"\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATADIR}/applications/\")")
+		install(CODE "execute_process(COMMAND ${DESKTOP_FILE_INSTALL} \"${CMAKE_SOURCE_DIR}/res/mgba-qt.desktop\" --dir \"\$ENV{DESTDIR}\${CMAKE_INSTALL_FULL_DATADIR}/applications/\")")
 	endif()
 endif()
 if(UNIX)
```

**Comment by sergiobenrocha2** [comment]
```
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

that appears when you press the Load New Shader button

**Comment by noabody** [comment]
With my daily build on Ubuntu 17.04 64-bit I also cannot load a shader.  All folders are "greyed out" not selectable.  This behaviour is not present on the win32 version in wine.  That works properly.  Adding the name of the shader folder to the "shader="  line works fine.

**Comment by endrift** [comment]
Yeah I have a fix for this that I haven't committed yet.
