### ISSUE TITLE
Buggy sound in GB/GBC

### ISSUE THREAD

**Issue by sergiobenrocha2** [mgba-emu/mgba#768]
1 - Load a GBA game (sound is fine)
2 - Load a GB/GBC game, you'll notice buggy sound / static noise in every GB/GBC game you load now
3 - Try record it in Record Output, it'll not get the buggy sound

If you first load a GB/GBC game, it'll be fine

Xubuntu 17.04

**Comment by endrift** [comment]
I can't trivially reproduce this on macOS. Can you be more specific, e.g. which GBA and GB games? Or are you having it with just any?

**Comment by sergiobenrocha2** [comment]
No, the noise is only in GB/GBC games. You can load a GBA game again, no noise

**Comment by sergiobenrocha2** [comment]
You now have to:

1 - Load a GBA game (sound is fine)
2 - Load a GB/GBC game
3 - Load a GBA game again
4 - Load a GB/GBC game, you'll notice the bug

**Comment by endrift** [comment]
Still can't reproduce on macOS. Will try again on Linux before releasing beta 2.

**Comment by endrift** [comment]
Looks like it's an SDL bug. I had to work around it.
