### ISSUE TITLE
Frame size check mark only appears after selecting same size twice

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#77]
After you select a frame size and look at the frame size window again, there is no check mark. If you select the same size again, the check mark appears.

**Comment by endrift** [comment]
Weird, this worked (at least on OS X) when I checked it in.

**Comment by endrift** [comment]
Still works on OS X. I'll look at Win7 tonight.

**Comment by endrift** [comment]
Fixed in 3dc22d9cc5c93429dabd8428bfc359132543f318.
