### ISSUE TITLE
mgba-sdl controls unresponsive

### ISSUE THREAD

**Issue by barul42** [mgba-emu/mgba#774]
Using Gentoo, I compiled 0.5.2 and the latest git version (--version says I'm on 0.6.0), but the default controls don't seem to work.
The tab key does speed up the emulator, but that's the only one that I've found to be working.

**Comment by endrift** [comment]
What keyboard layout are you using? Can you paste your ~/.config/mgba/config.ini?

**Comment by barul42** [comment]
I'm using fr layout (oss variant); same one I use on an Arch laptop, on which mgba-sdl works fine.
Here's the config.ini: https://bpaste.net/raw/989c294638ee

**Comment by barul42** [comment]
Found it! Turns out mgba needs XDG_CONFIG_HOME to be defined.
If I execute `mgba-sdl $whatever.gbc`, it doesn't work (except the tab key, I haven't figured why out.
But if I do `XDG_CONFIG_HOME="~/.config/" mgba-sdl $whatever.gbc`, the controls works just fine.

**Comment by barul42** [comment]
Got some new information, it seems that it works just fine when numlock is disabled. But if it's enabled, the problem stays the same…

**Comment by GrenderG** [comment]
Having the same issue on Ubuntu 18.04. Disabling numlock "solves" the issue.

**Comment by endrift** [comment]
I'm able to reproduce now. I'll look into it this weekend.

**Comment by endrift** [comment]
Sorry this took me a year to fix. @barul42's discovery helped a lot though, as did getting a new laptop that actually has a numlock key.

**Comment by barul42** [comment]
No worries, the important thing is that it's fixed. Thanks !

**Comment by animaone** [comment]
Still not fixed in 2020, but works fine with numlock disabled.

**Comment by endrift** [comment]
Which version are you using?
