### ISSUE TITLE
Savestate/Loadstate Menu seems to close mGBA for no reason?

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#780]
I'm not exactly sure what I did, but twice while I was testing Pokemon Pinball's crashing, I managed to completely kill mGBA while the savestate or loadstate menu was open.  Both times, I was just hitting a key on the keyboard (which was mapped to A on mGBA) and mGBA suddenly closed without warning.

I'm not entirely sure if there's some hotkey to close mGBA from that menu or maybe I'm doing something extremely wrong/loading a badstate from last year unintentionally, but, I don't think users would appreciate their game closing while the savestate menu is open and before they've made a state.

**Comment by endrift** [comment]
Having trouble reproducing this.

**Comment by endrift** [comment]
Possibly addressed by b6c0d5307f4690b796dd11e13900dcebfacdfcc9
