### ISSUE TITLE
Castlevania - Circle of the Moon (USA) 

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#781]
In Castlevania - Circle of the Moon (USA).  There is a clicking sound. here is a video so you can here it.

https://streamable.com/fjrtf

mGBA-nightly-2017-07-06

Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Pentium G3240 @ 3.10GHz	
	Haswell 22nm Technology
RAM
	8.00GB Dual-Channel DDR3 @ 698MHz (10-10-10-25)
Motherboard
	Gigabyte Technology Co. Ltd. H81-D3 (SOCKET 0)	
Graphics
	ELEFW328 (1360x768@60Hz)
	Intel HD Graphics (Gigabyte)
	1023MB NVIDIA GeForce GT 720 (EVGA)	
	ForceWare version: 365.10
	SLI Disabled
Storage
	931GB TOSHIBA DT01ACA100 (SATA)
Optical Drives
	HL-DT-ST DVDRAM GH24NSC0
Audio
	Realtek High Definition Audio

**Comment by endrift** [comment]
Probably a regression from the timer changes. Can you see if this affects 0.5.2 as well?

**Comment by endrift** [comment]
Regression on master. Does not affect 0.6 beta 1.

**Comment by Cibomatto2002** [comment]
Does not affect 0.5.2
