### ISSUE TITLE
Audio fire on some games is to fast or to slow.

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#789]
Is there a way to set the audio fire speed?

**Comment by endrift** [comment]
What is the audio fire? Do you mean auto fire?

**Comment by Cibomatto2002** [comment]
Yes auto fire.

**Comment by endrift** [comment]
It's supposed to invert every frame. I can add a setting to adjust that.

**Comment by Cibomatto2002** [comment]
Thank you I would appreciate it.

**Comment by Cibomatto2002** [comment]
Can't find the Customizable autofire speed setting. I downloaded the mGBA-build-2017-08-04-win32-4769-1733c6456125b0a49c7f7fcac28ffe4328ce4701 build.
