### ISSUE TITLE
[Feature Request] Shaders and Controls.

### ISSUE THREAD

**Issue by JohnPalace** [mgba-emu/mgba#795]
Please add XBRZ filters/shaders.
https://sourceforge.net/projects/xbrz/

Also, please enable Speed Up/Fast-forwarding custom button and for it to have a "Hold" mode, along with the current "Toggle".

**Comment by endrift** [comment]
xBRZ will NOT be added due to licensing constraints and the fact that it cannot be implemented as a GPU shader.

Fast forward does have a hold mode, that's the default. It's just Tab at the moment.
