### ISSUE TITLE
SDL_VERSION_ATLEAST is not defined

### ISSUE THREAD

**Issue by mrpwhite** [mgba-emu/mgba#798]
/build/mgba-master/src/platform/qt/main.cpp:33:27: error: function-like macro 'SDL_VERSION_ATLEAST' is not defined
#if defined(BUILD_SDL) && SDL_VERSION_ATLEAST(2, 0, 0)

I am on OSx Sierra 10.12.5.

I honestly don't know what information would be useful for debugging this. I ran the brew install successfully. SDL2 is definitely installed. I searched around the repo and it doesn't look like SDL_VERSION_ATLEAST is defined anywhere, but I am not a C guy.

Any guidance is much appreciated!!!!!!

**Comment by endrift** [comment]
please run CMake again and tell me what the output is. It seems like SDL isn't getting included properly, somehow.

**Comment by barrowsx** [comment]
@mrpwhite I also had this issue (Mac OS Sierra 10.12.6) and found that, for whatever reason, installing SDL alongside SDL2 makes it compile properly. So basically just change your `brew install` to

`brew install cmake ffmpeg imagemagick libzip qt5 sdl2 libedit sdl`

and it should work.

@endrift here's the output from running CMake: https://pastebin.com/Q8RnMGji

**Comment by endrift** [comment]
Weird. Okay I think this is enough info for me to start acting on this.

**Comment by kode54** [comment]
You also need to install pkg-config for the current SDL2 script to work.

**Comment by endrift** [comment]
I'm pretty sure this is fixed now, along with a commit I just made.
