### ISSUE TITLE
[mgba-master] Don't clear oXoY Controllers from restart

### ISSUE THREAD

**Issue by slacknk** [mgba-emu/mgba#799]
mgba (Qt5) 0.6.0_b1.67 build from git20170715 - master

- Don't Clear Button and Clear Analog Controllers in oXoY from restart

Menu:Tools - Settings - Controllers
Click (Example) Up - Clear button and next yet click Up - clear analog
Apply - Ok - (Exit) Ctrl+Q

New start mgba-qt, Menu:Tools - Settings - Controllers, button Up don't clean(
and if action for Left-Right-Down too

**Comment by JMC47** [comment]
Confirmed.  I'll try to translate this to be a little easier to understand.

Using the up button in the controller configuration, clear everything from it.  Then, hit okay and close the emulator.  When you come back, it won't be cleared, there will still be inputs there.

**Comment by endrift** [comment]
Hm, I thought I'd fixed this already.
