### ISSUE TITLE
[Wii] Not issue, not bug

### ISSUE THREAD

**Issue by askotx** [mgba-emu/mgba#80]
I don't get antother way to say this: thank you. 
Thank you for make a great emulator that can run almost flawlessly on this forgotten platform.

Last night, I compiled a mgba core from libretro, then I down sample rate to 32000 on retroarch.cfg, then start a rom like DKC, DKC2, Metroid zero mission, Wario Land 4, Kirby Nigthmare in Dream Land  and all of them works like a charm.

Before yesterday compilation, I needed to turn off sound to get 60 FPS, and with sound it gets 35 FPS (DKC2), but now, it works sometimes from 45 to 60 FPS, it has a lot of improvement, others games get full 60 FPS (Metroid, Wario, Kirby), sometimes sounds get a little crakled, but I don't care, It almost work full 60 FPS with sound.

Again, thanks, thanks, thanks a lot for your work and effort.

**Comment by MoochMcGee** [comment]
Dude, go on the forums to say this. Not the issue tracker.

**Comment by endrift** [comment]
As much as I appreciate the thanks, @MoochMcGee is right. There are forums for a reason :smile: https://forums.mgba.io/, to be exact.
