### ISSUE TITLE
Mapping the Rewind to the game controller does not work.

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#800]
Mapping the Rewind to the game controller does not work. I can set it to a button but when I press it nothing happens. Windows 10 64 bit. mGBA-build-2017-07-15-win32-4693-2d49a41a30bca9ad47457ad8825fc13b9e82de81.

**Comment by Cibomatto2002** [comment]
I had to reboot the emulator for it to work but it's not Rewinding right if you press the ` key it will go back slow but if you press the button on the game pad it goes back to far it's hard for me to explain it.

**Comment by endrift** [comment]
Yeah you mapped Rewind instead of Rewind Held. Do Rewind Held instead.

**Comment by Cibomatto2002** [comment]
Thanks A lot that was it.
