### ISSUE TITLE
Chrono Trigger - Affine bg floor plane is shifted at wrong offset during bike race

### ISSUE THREAD

**Issue by yuriks** [mgba-emu/mgba#802]
During the bike race again Johnny in the future era, the ground plane seems to be shifted to an incorrect position during the race. It also moves strangely during parts when the camera is rotated.

version: 5f05662242ed37f20626e20b5b690a8cd1b7bd07
medusa screenshot:
![medusa_2017-07-16_23-13-25](https://user-images.githubusercontent.com/341401/28257393-6600e400-6a7f-11e7-97b2-038d8259a82f.png)

For reference, this is the same scene in melonDS:
![melonds_2017-07-16_23-27-14](https://user-images.githubusercontent.com/341401/28257399-6f8d2f7e-6a7f-11e7-89ee-8d854402d7ea.png)

**Comment by endrift** [comment]
Please provide a savegame. I think I might know what's causing this, but it's a bit hard to test.

**Comment by yuriks** [comment]
Video of me rotating the camera around during the race. Actually seems to be a scaling issue rather than an offset: [2017-07-16_23-36-16.zip](https://github.com/mgba-emu/mgba/files/1151732/2017-07-16_23-36-16.zip)

[Savegame](https://github.com/mgba-emu/mgba/files/1151735/3055.-.Chrono.Trigger.USA.En.Fr.zip) (First slot, just walk up into the area map and then use the jet bike. You can rotate the camera using L and R.)

**Comment by yuriks** [comment]
Might be related or the same as #700.

**Comment by endrift** [comment]
I'm pretty sure I know what the source of this issue is (and it's a known issue) but it will take...a fair bit of work to fix.

**Comment by yuriks** [comment]
Confirmed fixed.
