### ISSUE TITLE
GameBoy, bad sound emulation

### ISSUE THREAD

**Issue by SieKensou** [mgba-emu/mgba#803]
Hi, first of all I have to congratulate you for the great job you are doing with this emulator. I tested the new 0.6.0 yesterday and it's great too see the new improvements. I'm using the Wii port version.
I tested some GameBoy, GameBoy Color and GameBoy Advance games and I noticed that the Game Boy games doesn't sound very good. Some examples of the games I tested are: World Heroes 2 Jet (GB), Adventure Island (GB), Puchi Carat (GBC)... Do you think that the Game Boy sound could be better and improved for future versions?

**Comment by SieKensou** [comment]
When I tried to download from that link it saves a file called "mGBA-build-latest-wii.solitairetheme8" :/
No 7zip file or zip file...

**Comment by endrift** [comment]
Rename it. It's a 7z file, but your web browser screwed up.

**Comment by SieKensou** [comment]
Ok, that worked.
Tested now and I can heard the same issues. I tested Donkey Kong Land too and I can hear some cracks in the sound between screens too.

**Comment by endrift** [comment]
Related to #1016.

**Comment by endrift** [comment]
Does this still reproduce?

**Comment by SuperrSonic** [comment]
I just tested the latest nightly and did notice constant crackling, I think this is a port-specific problem as I couldn't hear the same issue in retroarch wii and pc versions.

**Comment by SieKensou** [comment]
Yes, I tried the latest version (from 2018-08-01) and the sound of GB and GBC is still very bad. Even the sound when the GameBoy logo from the bios appear sounds bad....

**Comment by endrift** [comment]
I'll try looking at the Wii port later; I'm not noticing the crackling on PC.

**Comment by endrift** [comment]
I'm able to reproduce this in Dolphin but I can't figure out what's going on. Before resampling everything looks fine. After resampling, things break. But only on the Wii, and the resampling code is the same in both places.

**Comment by endrift** [comment]
Fixed, at least within Dolphin. I'll reopen if it reproduces on hardware.

**Comment by SieKensou** [comment]
Nice! I have tested it and it sounds better than before, but the sound still has some problems. For example test the game Duck Tales and listen the first stage music for a while (you will notice again bad sound in some parts), In the same game, the music when you lose a life shows the problem.... and I notice it in other games too :(

**Comment by endrift** [comment]
That's probably #1036, not this one.

**Comment by SieKensou** [comment]
I think it is not exactly that one. I think it is related with some specific notes. Check the game I said if you can and you will hear it.
