### ISSUE TITLE
shortcuts only work after opening settings

### ISSUE THREAD

**Issue by cremno** [mgba-emu/mgba#804]
Tested on Windows with both 0.6 and the latest development build (0.7-4699-0f5dab6). Both keyboard and gamepad shortcuts will only work after the settings window was opened. Don't even have to close it or click OK/apply.

**Comment by JMC47** [comment]
Cannot reproduce - I'm able to use shortcuts as soon as a game is opened.

Please provide more info if possible.

**Comment by cremno** [comment]
I'm using the library (list view) to load a ROM. Apparently it's related to that because it works when loading a ROM in other ways (e.g. drag&drop). I've also noticed I don't even need to open a window, just a menu (File, Tools, etc.).

0.7-5219-353176b1, official Windows build

**Comment by endrift** [comment]
I'll try to look into this before releasing 0.7.

**Comment by endrift** [comment]
Can reproduce.
