### ISSUE TITLE
[Win 8.1, 0.6.0] OpenGL mode outputs black screen & flicker

### ISSUE THREAD

**Issue by Tharn** [mgba-emu/mgba#813]
Hi,

For this new version and the last one, I noticed that standard OpenGL mode will not work with my GMA 4500MHD chip using the most recent 8.15.10.2869 driver. It produces solid black screen output with the occasional flicker showing the graphics as they should be. This happens whether I use the 32 or 64 bit version of the emulator.

There's a similar issue for Linux (#383) but I would guess they're not related.

OpenGL 1.x legacy mode works fine. The chip is able to do OpenGL 2.1. That should be enough, right?

**Comment by endrift** [comment]
OpenGL mode uses features from 3.0 that may or may not have been present in older drivers, namely framebuffers. Just 2.1 support is not sufficient. Otherwise, 1.x should work fine, you just won't have shaders.

**Comment by Tharn** [comment]
Alright, cheers!
