### ISSUE TITLE
Saving in game and states crashes the MGBA in fire red

### ISSUE THREAD

**Issue by teiten** [mgba-emu/mgba#814]
It is impossible to save in the game normally without it crashing and its an 80% chance that using a save state crashes the emulator and fails to load.

**Comment by endrift** [comment]
Save state crashes are fixed, but I can't reproduce the in-game save crash.

**Comment by JMC47** [comment]
Tested Fire Red and saved before picking starters.  Was able to load fine and check the IVs of all three starters.

I saved a second time for good measure just to see if maybe the 80% chance didn't hit, but, that worked fine as well.

**Comment by Drizzt893** [comment]
Seconded, playing a leaf green nuzlocke and the game crashing on save regularly is really killing the hardcore feel of the challenge as I keep getting second chances to play more optimally.

**Comment by endrift** [comment]
This issue has been closed for nearly 5 years. The bug mentioned here is long since fixed. If you're also experiencing crashing, it's a completely different cause.
