### ISSUE TITLE
Savestates not saving/loading all of RAM? (GB / GBC)

### ISSUE THREAD

**Issue by anden11** [mgba-emu/mgba#815]
Branch: heads/0.6.0
Revision: f4c4be7b121556f47438dbac940186da4d4199d6

Running under Lubuntu 16.04 x86-64
I use the official build, https://github.com/mgba-emu/mgba/releases/download/0.6.0/mGBA-0.6.0-ubuntu64-xenial.tar.xz

I'm experiencing problems with the savestate feature while playing Warioland 2, where not all of the data seems to be loaded back into RAM. If I start up the emulator and load the ROM, then immediately load my savestate, the game will be very glitched (character falling through the floor and coins everywhere). If I allow the game to load its progress normally before loading the savestate (I assume loading the level I'm currently at into RAM) the game doesn't glitch out like this but appears to behave like normal.

I've attached both the savefile and savestate as per request.

[warioland 2 savefile and savestate.zip](https://github.com/mgba-emu/mgba/files/1156730/warioland.2.savefile.and.savestate.zip)

**Comment by endrift** [comment]
Confirmed. Bizarre.

**Comment by endrift** [comment]
Figured it out. This game uses the savedata as extra RAM. Make sure that Savestate Extra Data in the emulation settings has Savedata checked. You don't need to check it in load, as it'll load a temporary version when you load the state. That said, it will probably overwrite your savedata from loading old states as that temporary version gets written out permanently if the game actively writes back to it.
