### ISSUE TITLE
(Wii) Unstable UI

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#816]
Various ROMs give a "Load failed!", and I'm getting random hangs while using the UI. Tested nightly 57559610c022d4991a77183bdc084cabc5a283b8.

b71ffe711c4ccb485b3b1171d65a4e1449640397 seems to be the cause.

**Comment by endrift** [comment]
Extrems pointed out this might be related to compressed archives. Do you notice any difference between compressed and uncompressed ROMs?

**Comment by SuperrSonic** [comment]
So far no load fails when using uncompressed ROMs, but I still get random crashes regardless.

**Comment by endrift** [comment]
Are all of the load-failing ROMs 32MB uncompressed?

**Comment by SuperrSonic** [comment]
No, and some of the ones that still work are 32MB.

**Comment by endrift** [comment]
Worked around in 470dd7f5508866b8b54722966ff7395c5b8748d3
