### ISSUE TITLE
Add wiiu support

### ISSUE THREAD

**Issue by mariogamer2** [mgba-emu/mgba#819]
Not sure about this (maybe the libretro core support the wiiu already).

**Comment by zeromus** [comment]
Did some digging. Took a while, but here's what I managed to find
google mgba "wii u"
hit #1: wiiU retroarch mgba core
hit #2: endrift "no interest in wii U port"

**Comment by mariogamer2** [comment]
Wasn't sure thank.

**Comment by Saphiresurf** [comment]
dose links tho

**Comment by endrift** [comment]
That's just github autoexpanding anything that starts with a # and has a number after it.

But yeah, I'm not porting it to the Wii U.
