### ISSUE TITLE
Softlock in Tales of Phantasia (USA version)

### ISSUE THREAD

**Issue by sergiobenrocha2** [mgba-emu/mgba#82]
The libretro core restarts during the introduction sequence (just before the small guy hits the tall guy in the right).

With mgba-qt you get 200% of cpu usage, music continues but with crackling audio.

crc: 01A0FCA8

**Comment by endrift** [comment]
I've never been able to reproduce this, with or without the BIOS. What build were you using?

**Comment by sergiobenrocha2** [comment]
Builds from master branch. Linux x86-64.
