### ISSUE TITLE
Pokemon Pinball GBA stutters/stops

### ISSUE THREAD

**Issue by Tatsuya79** [mgba-emu/mgba#820]
mGBA 0.6.0
Windows 7 x64
Core i5-3570K, Nvidia GTX-770, OpenGL

Pokemon Pinball stutters strangely even though the fps counter shows a stable 60fps.

The Libretro core is even worse as the game runs slower really quickly until it completely hangs.

**Comment by endrift** [comment]
The GB one or the GBA one?

**Comment by Tatsuya79** [comment]
Sorry, forgot there was this one too, it's the GBA game.

**Comment by endrift** [comment]
Not having much luck reproducing this.

**Comment by Tatsuya79** [comment]
The default mGBA settings weren't smooth here but after enabling video + audio sync and disabling aero I got it smoother now.
That's perhaps only a retroarch core issue in the end, sorry to have bothered you.
I wonder why just with this game though...

**Comment by endrift** [comment]
Does this still reproduce?

**Comment by Tatsuya79** [comment]
Yes, still does the same to this day.
![bug](https://user-images.githubusercontent.com/6266038/46364064-ff81c200-c674-11e8-9f08-8d2a602628d7.jpg)

**Comment by endrift** [comment]
Will try to look into it later today.

**Comment by Tatsuya79** [comment]
I saw that issue: https://github.com/libretro/mgba/issues/107
and indeed it's caused by the rumble feature.
Disabling it [by commenting this line out](https://github.com/libretro/mgba/blob/master/src/platform/libretro/libretro.c#L566) makes the game acting without issue.

Also a bit unrelated but I'm noticing memory leaks with savestates, noticeable when using the run ahead feature.

**Comment by endrift** [comment]
The memory leaks were fixed a day or two ago.

**Comment by endrift** [comment]
I believe this is fixed in a8d991e24f12aa1930498af61f16fa2b098cc618.

**Comment by Tatsuya79** [comment]
Can confirm it's fixed.
Thank you! :)
