### ISSUE TITLE
Emulator crashes to desktop when attempting to load a save state

### ISSUE THREAD

**Issue by autofire372** [mgba-emu/mgba#823]
mGBA is currently crashing to desktop any time I try to load a save state in any game, be it GB, GBC, or GBA.

I am running mGBA 0.7-4709-ef82480 on  Windows 10.

[Here](https://pastebin.com/sMtVj0LT) is my config.ini.

You can disregard the gb,override setting; that was from a failed attempt to get Pokémon Blue to work properly in GBC mode, and removing it did not resolve the issue at hand.

**Comment by endrift** [comment]
Confirmed happening in Qt version on my Mac too.
