### ISSUE TITLE
3DS: GameBoy/Color screenshots are heavily corrupted

### ISSUE THREAD

**Issue by jpmac26** [mgba-emu/mgba#826]
I am using the v0.6.0 release of mGBA, playing on a New 3DS XL with Luma3DS v8.1, and I have encountered this issue on both the CIA and 3DSX builds of mGBA. I can confirm that this issue is NOT present on the Windows x64 version. I do not believe this is a regression introduced in v0.6.0, as I recall having this issue in version 0.5.2 as well. This issue also does not affect GBA games; their screenshots and savestate preview images look fine.

Whenever I attempt to load a savestate for an original GameBoy or GameBoy Color game, the preview image is always extremely corrupted and zoomed-in, it looks like the image is being interlaced horizontally and vertically, and the image is always a strange shade of dark blue and magenta. Using the "Take screenshot" option in the menu also produces images that are corrupted in this manner. However, these savestates still load just fine, even when trying them in the Windows version of mGBA. I have included some examples below alongside screenshots from the Windows version for comparison.

3DS (left), Windows (right):
![pokeprism_b211-1](https://user-images.githubusercontent.com/2925767/28591196-a6fdab76-7139-11e7-9901-7150c20eaadf.png) ![pokeprism_b211-2](https://user-images.githubusercontent.com/2925767/28591200-a9a1d4f6-7139-11e7-9820-51438610cb5c.png)
![pokemon red-0](https://user-images.githubusercontent.com/2925767/28591216-bf293cec-7139-11e7-93fd-0f4a7d52b69d.png) ![pokemon red-1](https://user-images.githubusercontent.com/2925767/28591217-c03169f2-7139-11e7-8e85-ef73bdfe8073.png)

**Comment by endrift** [comment]
I thought I fixed this at some point...

**Comment by PencilAmazing** [comment]
While you're fixing it, could you also make the recording tool easier to use? I had a hard time using it

**Comment by endrift** [comment]
Recording tool?

**Comment by jpmac26** [comment]
@PencilAmazing Do you mean the recording tool on the PC version? This issue is about screenshots in the 3DS version, which doesn't have a recording feature to my knowledge.
