### ISSUE TITLE
Zook Hero Z crashing mGBA on loading

### ISSUE THREAD

**Issue by LuigiBlood** [mgba-emu/mgba#831]
I'm using mGBA 0.6.0 as it is downloadable from the official website, running Windows 7 Ultimate SP1 (64-bit), AMD Athlon II x4 640 (4 GHz), and AMD Radeon HD 5700 Series.

As I'm saying, Zook Hero Z, upon loading (using Load ROM menu), crashes the emulator instantly. Doesn't even seem to reach emulation state.

**Comment by endrift** [comment]
Ah I see what's happening here. The game declares it has no SRAM and then...tries to access the SRAM. Which is null.
