### ISSUE TITLE
Auto Fire not working and auto Cheats not loading with save state on mGBA-build-2017-07-29-win32

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#832]
I just updated to the new nightly build mGBA-build-2017-07-29-win32-4743-e1bc79b83796d67d7817fe0883e2b0182dcfb2bb and Auto Fire is not working anymore and cheats will not auto load when loading a save state now if I go back to mGBA-build-2017-07-21-win32-4704-38e56597b5f6ef471f2b18e5eb268b8cdeed016a everything works correctly.

Also where does mGBA keep it's config file? I like to delete it when I get a new nightly build.

**Comment by endrift** [comment]
Ah, yeah, those are things it would make sense I could have broken recently.

Also: %APPDATA%/mGBA/config.ini

**Comment by endrift** [comment]
Cheat loading should work now, let me know.

**Comment by Cibomatto2002** [comment]
they are working. Thanks

**Comment by endrift** [comment]
Autofire fixed now too.

**Comment by Cibomatto2002** [comment]
Thanks
