### ISSUE TITLE
GBC Save States 3DS

### ISSUE THREAD

**Issue by Remobit** [mgba-emu/mgba#834]
Playing gbc games on 3DS (mGBA as 3dsx file if that matters) when the game saves (sav file) and I exit the app it stays normally.
If I load a savestate, save (.sav) then exit the app, it didn't save.
Surprisingly if I load a savestate, save (.sav), choose "exit game", then exit the app, the save stays normally.

**Comment by endrift** [comment]
Which version (e.g. 0.6.0 or a development build) and games have you tried?

**Comment by Remobit** [comment]
0.6.0
Noticed it with Warioland 2, then tested further with a pokemon crystal romhack.

**Comment by endrift** [comment]
Wario Land II is a bit weird with how it interacts with its savegames, but this...should work regardless.

**Comment by Remobit** [comment]
I've tested a bit more and it seems the "exit game" trick doesn't work always either. So looks like savestates make saving wonky in general.

**Comment by endrift** [comment]
Does this occur with GBA games as well?

**Comment by endrift** [comment]
I can actually confirm that this happens on desktop with GB games too
