### ISSUE TITLE
BIOS paths in Portable Mode

### ISSUE THREAD

**Issue by scottluker** [mgba-emu/mgba#838]
When using mGBA in portable mode, if the BIOS paths are in the same directory as mGBA then they should be a relative path rather than an absolute path. This will make mGBA fully portable because you won't have to manually change the paths.

Or another solution to this is to have mGBA check a folder which you can place the bios files in and will be automatically used.

**Comment by scottluker** [comment]
I know I can use `.\` on windows, just though this would help other people.

**Comment by endrift** [comment]
It should automatically look in the same directory as the config file. If that's not working in portable mode that's a bug.

**Comment by twoco** [comment]
If you use `./` or no prefix (e.g. only `bios/foo.bin` it tries to locate the file from the ROM directory. It's ok. But how to define the relative path from the application folder where the `mGBA.exe` is located? Maybe both solutions are useful. Relative path of ROM and relative path of application. Use case: Either load and save files in ROM directory (with optional subfolders) as it currently works. Or organize all in the application path (portable). This is currently only possible with absolute pathes. Or did I miss something?

`v0.10.2`

**Comment by endrift** [comment]
that sounds like a bug

**Comment by twoco** [comment]
Not sure if this is a bug. Because you maybe want relative path to ROM directory. But realtive path to the app (exe) folder is also a good option. But how to handle both. Or what is intended/expected?

**Comment by endrift** [comment]
Expected/intended is relative to the app folder.

**Comment by twoco** [comment]
Ok, I started the ROM by double click and open with (from Windows explorer). Not tried when open mGBA and open file manually.

**Comment by endrift** [comment]
Oh, I think that might be a different bug. I'd need to find the bug report for it though.

**Comment by endrift** [comment]
I believe it's #2826, which is fixed in dev but not in 0.10.2. Can you see what it does in a dev build?

**Comment by twoco** [comment]
I tested it now: 

- If you load ROM after starting mGBA, then the relative path works as expected (app folder).
- If you start mGBA with a ROM as paramter (open with; double click on file and link file with the exe), then relative path is rom folder (which is the issue).

**Comment by endrift** [comment]
In that case, it's already fixed, but won't be in 0.10.3, only 0.11.
