### ISSUE TITLE
Input is broken in Kirby's Dream Land 2 (USA, Europe)

### ISSUE THREAD

**Issue by vaguerant** [mgba-emu/mgba#839]
36c1fb59be4710543c4a5476a554757efe306ccd broke input in Kirby's Dream Land 2 (USA, Europe) (SGB Enhanced) for (Super) Game Boy. Interface-side inputs work fine, but the Game Boy buttons do not function.

**Comment by endrift** [comment]
This is probably because the SGB input polling is a hack at the moment. I'll take the time to fix it up soon.

**Comment by endrift** [comment]
My hypothesis was correct. I have a fix committed, will be pushing shortly.
