### ISSUE TITLE
Sprite export crash

### ISSUE THREAD

**Issue by Cj-Malone** [mgba-emu/mgba#841]
When exporting a sprite (via Tools, Sprites, Export) the game (Pokemon Emerald GBA) crashes, but not the program. I managed to do a quick fix myself by commenting out an interrupter, but I guess a real fix would actually be to resume the interrupt? Anyway this is my diff that got it to work.

```
diff --git a/src/platform/qt/ObjView.cpp b/src/platform/qt/ObjView.cpp
index 871a95cb..a6e356bc 100644
--- a/src/platform/qt/ObjView.cpp
+++ b/src/platform/qt/ObjView.cpp
@@ -248,7 +248,7 @@ void ObjView::updateTilesGB(bool force) {
 
 #ifdef USE_PNG
 void ObjView::exportObj() {
-       CoreController::Interrupter interrupter(m_controller);
+       // CoreController::Interrupter interrupter(m_controller);
        QString filename = GBAApp::app()->getSaveFileName(this, tr("Export sprite"),
                                                          tr("Portable Network Graphics (*.png)"));
        VFile* vf = VFileDevice::open(filename, O_WRONLY | O_CREAT | O_TRUNC);
```

**Comment by endrift** [comment]
Crashes what? The game?

**Comment by Cj-Malone** [comment]
After some more looking around it turns out it just pauses the game, not crashes. And doesn't resume after extraction. I presume it's paused to make sure the sprite in memory isn't altered during extraction?

It's a bit counter intuitive to have the game stay paused after extraction, I think it should resume automatically.

**Comment by endrift** [comment]
I can reproduce that issue. Investigating.
