### ISSUE TITLE
Writing to unknown register when loading a Gameboy game in Super Game boy

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#842]
![capture1-11-2017-2 06 54 am8-4-2017-9 57 13 am](https://user-images.githubusercontent.com/21169038/28974387-d1706a1e-78fb-11e7-9bcc-006934c4c29e.jpg)

[INFO] GB:	Resizing SRAM to 0 bytes
[STUB] GB I/O:	Writing to unknown register FF4F:00
[STUB] GB I/O:	Writing to unknown register FF68:00
[STUB] GB I/O:	Writing to unknown register FF6A:00
[STUB] GB I/O:	Writing to unknown register FF70:01
[STUB] GB I/O:	Writing to unknown register FF51:FF
[STUB] GB I/O:	Writing to unknown register FF52:FF
[STUB] GB I/O:	Writing to unknown register FF53:FF
[STUB] GB I/O:	Writing to unknown register FF54:FF
[DEBUG] GB Serial I/O:	Lockstep 0: Node init
[STUB] GB I/O:	Writing to unknown register FF44:00
[INFO] GB:	Resizing SRAM to 0 bytes
[STUB] GB I/O:	Writing to unknown register FF4F:00
[STUB] GB I/O:	Writing to unknown register FF68:00
[STUB] GB I/O:	Writing to unknown register FF6A:00
[STUB] GB I/O:	Writing to unknown register FF70:01
[STUB] GB I/O:	Writing to unknown register FF51:FF
[STUB] GB I/O:	Writing to unknown register FF52:FF
[STUB] GB I/O:	Writing to unknown register FF53:FF
[STUB] GB I/O:	Writing to unknown register FF54:FF
[DEBUG] GB Serial I/O:	Lockstep 0: Node init
[STUB] GB:	Unimplemented SGB palette overflow: 5555
[STUB] GB:	Unimplemented SGB palette overflow: 5555
[STUB] GB:	Unimplemented SGB palette overflow: 5555
[STUB] GB:	Unimplemented SGB palette overflow: 5555

**Comment by endrift** [comment]
Fixed in 41e00148bfa2e75ee72505030f4fd91fe5c13cfb, though doing this in the first place is of questionable utility.

**Comment by Cibomatto2002** [comment]
I was thinking if I loaded a gameboy game in super gameboy I would see something like this.
![1](https://user-images.githubusercontent.com/21169038/28975337-47577576-78ff-11e7-93b3-cd63ec8fc5a4.jpg)

**Comment by endrift** [comment]
Unfortunately most of those assets are on the SNES side, which is HLE emulated. Without the SNES ROM there's no much you can do there.
