### ISSUE TITLE
Wrong offset of the GB display when started from the command line with mgba-qt

### ISSUE THREAD

**Issue by linkmauve** [mgba-emu/mgba#843]
When I start a GB game by clicking File > Load File, everything is rendered correctly, but when I start it by giving its path as the first argument to mgba-qt it has a small offset which doesn’t change on resize.

Here is a screenshot demonstrating the first case (left) and the bug (right):
![wayland-screenshot](https://user-images.githubusercontent.com/7755816/28977765-aa1d29be-7943-11e7-903b-5e3787530456.png)

This is running 0.6.0 from the ArchLinux community repository, using X11.

**Comment by endrift** [comment]
Hmmm haven't seen this before, and I'm pretty sure it doesn't happen in master. Can you install mgba-qt-got from AUR and see if it reproduces?

**Comment by linkmauve** [comment]
I can actually reproduce on 0.7-6-40fb750.

**Comment by endrift** [comment]
weiiiird, because I CAN'T reproduce it on macOS. Will reboot into Arch shortly.

**Comment by endrift** [comment]
I can't reproduce this on Arch, but I've solved the Windows bug. The patch only applies to master though so I'll work on one for 0.6 branch too.

**Comment by linkmauve** [comment]
I confirm it works properly on master now, thanks!
