### ISSUE TITLE
The Select Button Takes Some Time To Work

### ISSUE THREAD

**Issue by John-Enigma** [mgba-emu/mgba#845]
I don't know if this happens to everybody, but the Select button is not refined like the other buttons. 

Every time I try to press it, it takes a bit of time for it to respond. 

Using Link's Awakening DX as an example, I tried to: 

- save the game (A + B + Start + Select at the same time), 
- tried to open the map, 
- tried to activate the status screen from the Pause Menu, 

and it's a piece of work, honestly. 

The other buttons are not like that. They're really responsive. I even checked my keyboard, and everything is fine.

**Comment by endrift** [comment]
Um. Menus are just slow in that game.

**Comment by John-Enigma** [comment]
Is not the menus per se. 
Whenever I press the Select button in other games, I have to press it like two times for it to work. 

It doesn't respond at the instant properly, @endrift. 

I've tested Mother 1+2 (English translation), and takes me like two times for the Select button to work.

**Comment by endrift** [comment]
Works fine on my machine. Select isn't handled at all specially compared to other buttons. Is this keyboard or controller? What are the mappings?

This is kind of needed for proper diagnosis.

**Comment by John-Enigma** [comment]
I use a keyboard. 

And these are my controls: 
![keyboard mapping](https://user-images.githubusercontent.com/22717497/28990849-2ff20482-7936-11e7-9574-6065391e6bb8.PNG)

**Comment by zeromus** [comment]
Check under your ' for sticky crumbs

**Comment by John-Enigma** [comment]
What do you think?

**Comment by zeromus** [comment]
Oh, then you may want to put some more crumbs in so it will stop working again.

Try clearing the controller binding for select, perhaps your gamepad is sitting on the floor propped up against the select button and it's conflicting with your keyboard

**Comment by endrift** [comment]
Have you tried binding it to another key?

**Comment by John-Enigma** [comment]
Okay. I changed the ' with a \ . 

The reason why it was weird, is because the ' key takes like two seconds for it to respond, just like in Word, or any other kind of app. Which is weird because I use that key in all kinds of emulators, and that waiting time never happened to me.

**Comment by John-Enigma** [comment]
What do you think of ' as a working key in mGBA, @endrift ?

**Comment by zeromus** [comment]
why the hell would it take 2 seconds to respond in any other app?  your system is weird.

**Comment by John-Enigma** [comment]
^You press the apostrophe (') key, it doesn't come out. 

You press the apostrophe key, plus another key, the (') key comes out. 

Maybe that's why it wasn't working. But I still don't get why it doesn't work. I've tested the (') key in other emulators with no problems whatsoever.

**Comment by zeromus** [comment]
Your keyboard is weird. It's your job to find out why. For all we know you have some 3rd party software installed that treats that key differently and attempts to detect when not to, and is failing to detect it for mGBA

**Comment by John-Enigma** [comment]
https://github.com/mgba-emu/mgba/issues/845#issuecomment-320382739 

Nope. My keyboard came with my Gateway desktop. Everything works as intended.

**Comment by zeromus** [comment]
then get your money back, since you have a system intended to run 3rd party "desktop enhancement" software that interferes with other programs. you could also try uninstalling everything that says "gateway", including the actual keyboard.

**Comment by GerbilSoft** [comment]
The keyboard layout is set up for "dead keys". As an example, if you press ' and then e, you'll get é.

**Comment by John-Enigma** [comment]
@GerbilSoft Well, I do have it set on United States - International. 

But just like you said, it could still happen.
