### ISSUE TITLE
Feature Request: mute audio while fast-forwarding

### ISSUE THREAD

**Issue by autofire372** [mgba-emu/mgba#846]
Revision 0.7-4752-36c1fb59 broke fast-forwarding; trying to fast-forward now results in a brief burst of speed, and then the game regresses to normal speed but with sound issues that, fortunately, do not persist when fast-forward is disabled.

EDIT: I have discovered another issue involving fast-forwarding: if fast-forward speed is set to anything other than unbounded, audio gets pitched up into a tinny screech.

**Comment by endrift** [comment]
Can't reproduce on macOS. What OS are you on?

**Comment by autofire372** [comment]
Windows 10 x64

**Comment by autofire372** [comment]
I've isolated the issue a bit further: it only occurs when the OpenGL video driver is used. Software and OGL 1.x both work fine.

**Comment by waddlesplash** [comment]
Can't reproduce on 0.6.0 on Win10 x64 here. I do note, though, that the first time I hit <TAB> to fast-forward it doesn't do anything, but the second and all subsequent times work just fine.

**Comment by autofire372** [comment]
waddlesplash, I never said the bug happened in 0.6.0. It only started in recent 0.7 dev builds.

**Comment by endrift** [comment]
Re: your edit, that's not a bug. It might be a bit undesirable (muting might be better) but it's not a bug.

**Comment by autofire372** [comment]
The bug I reported turned out to be an issue with my NVIDIA driver settings, so you can ignore that. Please keep this open as a feature request for the ability to mute audio while fast-forwarding.

**Comment by endrift** [comment]
See also #1143, which I'm going to implement at the same time.
