### ISSUE TITLE
mGBA crashing on launch

### ISSUE THREAD

**Issue by autofire372** [mgba-emu/mgba#847]
Revision 0.7-4778-d7fc097 caused persistent crashes on Windows when mGBA is launched with settings.ini present; if that file is not present, mGBA instead crashes when trying to access settings.

**Comment by endrift** [comment]
It's impossible for that revision to have caused this. I also can't reproduce, regardless. What OS?

**Comment by autofire372** [comment]
Windows 10 x64

**Comment by endrift** [comment]
Ok so that's when I rebuilt Qt for Win 10 x64. Hm.

**Comment by autofire372** [comment]
Can no longer reproduce; must've F'ed something up in my config. Deleting all config files resolved the issue.

**Comment by endrift** [comment]
This was actually an issue with the Qt build and AVX2. Should be fixed now.
