### ISSUE TITLE
Suggestion: Map viewing/exporting feature like VBA-M

### ISSUE THREAD

**Issue by mariomadproductions** [mgba-emu/mgba#849]
[screenshot of the feature in VBA-M](https://i.imgur.com/7Pf1Z9Y.png)

**Comment by endrift** [comment]
ok it's finally done

**Comment by mariomadproductions** [comment]
Thanks for adding this. I have a question about the feature though. In the window, the map appears like this (pink background, black box behind text).

![1](https://user-images.githubusercontent.com/9919020/31054168-dafb1f4e-a6a4-11e7-886d-fa50e020c890.png)

but when exported it appears like this (transparent background, no black box behind text)
![2](https://user-images.githubusercontent.com/9919020/31054173-de37c59a-a6a4-11e7-8a83-ca03d05f6765.png)

I assume the latter is correct, but why does it differ?

**Comment by endrift** [comment]
That just means the first entry in the palette for that tile (which is always transparent) has the RGB values set to black. I don't show the transparency in the viewer, only after exporting.
