### ISSUE TITLE
Garbled colors on most shaders

### ISSUE THREAD

**Issue by hoover1979** [mgba-emu/mgba#850]
The shaders used to work brilliantly, and I always used Xbr level 3, but all of a sudden if I enable most shaders all the colors are vastly wrong, greens where it's meant to be red, blue where it;'s meant to be orange, etc _(and I can't use Reshade for the hq4x shader, because Reshade 3.1 crashes MGBA)_.

The only way to get the colors right is to disable shaders completely, which due to the nature of the GBA's small screen, leaves an incredibly blocky image on my 27" screen.

I am guessing it may be an issue with the latest drivers for my GTX1080, as Nvidia are eclipsing AMD for shoddy drivers.  otherwise I am stumped.  the shaders were working, and now they arent.  I even tried a complete uninstall and reinstall of MGBA and even tried the nightly builds, but I get the same issue.

If you want a screenshot showing the color issues let me know and I will add a screenshot to my Deviantart page, and link it here. _(Photobucket has refused to complete uploading anything in a year for me)_  

Also if you need any more infomation to help identify what this issue is arising from, just ask me, and I'll do my best to provide any other relevant information requested.

**Hardware Specs:**

Windows 7 Professional 64bit on Kingston HyperX Fury SSD _(120Gb)_ 
ASUS Z97-k Mobo
Corsair HX850i Platinum Grade 850w PSU
Intel i7-4790k in turbo mode 4.4Ghz via BIOS XMP settings
Corsair H115i Liquid CPU Cooler
32Gb Corsair Vengeance pro 2400 DDR3 RAM _(set in XMP mode)_ 
8Gb Gigabyte Xtreme Gaming GTX1080 OC PCIe Waterforce GFX Card
Latest WHQL Nvidia Display Drivers _(at time of this post)_
Sound Blaster Zx PCIe Sound Card
Logitech Z906 THX Certified 5.1 Surrond Speakers and LFE
Seagate 8Tb Internal HDD
WD 4Tb internal HDD
WD Caviar 1.5Tb Internal HDD 
WD Elements 1Tb External USB 3.0 HDD
WD Elements 3Tb External USB 3.0 HDD
ASUS VG278 27" 120Hz 3D Monitor with Nvidia 3D Vision 2 _(tm)_ 
AVERMedia Volar Green USB2.0 HDTV Tuner
Targus Bluetooth 4.0 Adapter
SteelSeries Stratus XL Bluetooth Controller _(PC/Android version)_ 
Logitech K260 Wireless Keyboard 
ASUS PCE-AC68U AC1900 PCIe WiFi Card paired with:
ASUS RT-AC68U AC1900 Dual-Band Router on 5ghz band
Fractal Design XL-R2 Full Tower ATX Chassis

**Comment by endrift** [comment]
Was this triggered by a driver update or a new build of mGBA? Old builds of mGBA can be downloaded for reference.

**Comment by hoover1979** [comment]
I think it would be a driver update, as I had not updated MGBA.  and I checked again on the latest drivers in hope of the problem being fixed.  No dice.  The problem is if I revert drivers I then run the risk of new games not running until I update the drivers and break MGBA's shaders again.  

I used to use the level 3 XBR shader.  It was downright awesome and what was meant to be diagonal lines was a clean crisp diagonal line.  Now only the level 2 XBR and basic bilinear shader don't end up with the colors being completely obliterated, and on the level 2 XBR, what is meant to be diagonal lines is nowhere near as effective as the level 3.  it's like the difference between 6xBRZ and 2xBRZ resampling.  one is average to say the least and the other is impressive.  The problem is the impressive one now has weird colors, and now looks god aweful.

I wonder if there is a member of the MGBA team that has a GTX1080 (not a GTX1080ti) that can test the shaders, and if they get the same issue to recode some of them (especially the level 3 XBR) to work with the newer drivers (but the problem is another driver update could break them too). 

I find it quite frustrating as the only other emulator that has a similar looking shader (VBA-M) runs like a complete slideshow and has majow sound choppyness/garbling with the shader enabled, even on a 4.4Ghz 8 thread i7-4790k, 32gb corsair Vengeance Pro 2400 DDR3 RAM and a Gigabyte Xtreme Gaming GTX1080 Waterforce running in OC mode.  and as I have a 27" monitor running a GBA game in fullscreen without a shader like Level 3XBR is the epitome of blockyness.

I hope this can get resolved, and if the devs need any info (dxdiag, etc) they are welcome to contact me, so we can get to the bottom of this.

**Comment by zeromus** [comment]
_My other problem is if I revert drivers I then run the risk of new games not running until I update the drivers and break MGBA's shaders again._

If you don't perform the required test to determine whether the problem is in an updated driver, then you run the risk of mGBA never working again.

In the time it took you to write and edit all that 1000 times you could have downgraded the drivers, checked it, then updated them again.

**Comment by hoover1979** [comment]
I will try reverting the drivers incrementaly to see if drivers are an issue and if so, which drivers are the latest ones that work.  But I will have to do it in a few days time.  I am quite sick and spent the night in hospital and am in  a lot of pain and need to rest, so I am using the PC for watching movies until i recover.  then I will do the driver thing and report back.

**Comment by endrift** [comment]
I can confirm updating the drivers from 352.04 to 354.94 introduces this issue; therefore it is not an mGBA issue. Further, even if I wanted to fix the xBR-lv3 shader I couldn't as I don't know how it works. It's a straight port of @hyllian's Cg code to OpenGL.

<img width="1850" alt="382-05" src="https://user-images.githubusercontent.com/605502/29745374-ce910eba-8a6d-11e7-843d-bb92afb2cb90.PNG">
<img width="1851" alt="384-94" src="https://user-images.githubusercontent.com/605502/29745375-cea53908-8a6d-11e7-89d9-ab1151bc0ecd.PNG">
