### ISSUE TITLE
DS Screen rotation feature

### ISSUE THREAD

**Issue by Givralix** [mgba-emu/mgba#853]
Some DS games require the player to rotate the DS to the left or the right. Being able to rotate the screen in Medusa would make playing those games easier.

**Comment by zeromus** [comment]
Here's a list of open issues concerning rotation, which you can get by using "search" for "rotation". It now includes yours.

https://github.com/mgba-emu/mgba/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20rotation

**Comment by Givralix** [comment]
Oh, sorry.
