### ISSUE TITLE
Broken H-Blank HDMA Function

### ISSUE THREAD

**Issue by SnDream** [mgba-emu/mgba#855]
When writing $81 into $FF55, HDMA may send 30h bytes but not 20h bytes.
Wrting $82 may send 40h bytes and only $80 work correctly.
Other value untested.

Version: 0.6.0
Platform: Ubuntu 17.04 and Windows 7

**Comment by SnDream** [comment]
When writing into $FF55 between STAT mode 00, HDMA may send extra 10h bytes.
From Nintendo's Official Promramming Manual that HDMA should not be started at STAT mode 00 but official game Pocket Monsters Geum/Eun (Korea) does that and cause glitch on screen.

**Comment by endrift** [comment]
Thanks for finding this.
