### ISSUE TITLE
Metroid Zero Mission (J) Can't Fire Missile Upwards

### ISSUE THREAD

**Issue by bencecile** [mgba-emu/mgba#856]
I am trying to play Metroid Zero Mission, Japanese version, and I can't fire a missile upwards. This is a rather game breaking bug as it means you can get past the first mini boss.
*Specs*
- Branch: heads/0.6.0 (64 Bit)
- Revision: f4c4be7b121556f47438dbac940186da4d4199d6
- Windows 10 64 Bit
- Intel i5-6200u for CPU and Integrated Video
- OpenGL for Video
- SDL for sound
![Here is a GIF showing the bug](https://user-images.githubusercontent.com/5342848/29343461-3e7185c4-81ff-11e7-9ea7-ebcc595bc6b0.gif)

**Comment by zeromus** [comment]
Try using a gamepad instead of your keyboard which is unable to handle the required keys simultaneously.

**Comment by bencecile** [comment]
Thank you, that works!
