### ISSUE TITLE
Rhythm Tengoku crashes on Wii

### ISSUE THREAD

**Issue by RosalinaFan573** [mgba-emu/mgba#858]
I get a DSI exception with Rhythm Tengoku on the Wii version of mGBA. I tried the latest hourly and it still crashes.

**Comment by endrift** [comment]
When does it crash? Does it crash immediately?

**Comment by RosalinaFan573** [comment]
It crashes with a DSi Exception after it finishes loading

**Comment by GB-CG** [comment]
I've recently tried this with the English (Beta 10a) patch on 0.7-4887-f69b652e2 and it's working fine with me. My original Japanese rom's crc32 is 349D7025.

**Comment by endrift** [comment]
Please confirm is this issue is still present.

**Comment by endrift** [comment]
Closing due to lack of reply.
