### ISSUE TITLE
mGBA-build-2017-08-19-win32 Fast Forward is slower now.

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#859]
In mGBA-build-2017-08-19-win32-4803-8ee270f3f6b5d7e09fef98a374f37bbae947f4d2 Fast Forward is slower now. On older Development builds it was over 1000 FPS now it's like 300 FPS or so

**Comment by endrift** [comment]
please be more specific about how old "older" is.

**Comment by Cibomatto2002** [comment]
mGBA-nightly-2017-07-08-win32-70204e410c18785a27a39af538642cd3f54e2528 was faster for me.

**Comment by endrift** [comment]
Can you try builds in the middle? A bunch of them should be on the site.

**Comment by Cibomatto2002** [comment]
I tried mGBA-nightly-2016-12-09-win32-4085b9cdc5cce9397c349573bd6fcf53a3bae8ec and it seems about as fast as mGBA-nightly-2017-07-08-win32-70204e410c18785a27a39af538642cd3f54e2528.

I trying the Fast Forward on the game Metroid Zero (USA)

Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Pentium G3240 @ 3.10GHz
	Haswell 22nm Technology
RAM
	8.00GB Dual-Channel DDR3 @ 698MHz (10-10-10-25)
Motherboard
	Gigabyte Technology Co. Ltd. H81-D3 (SOCKET 0)
Graphics
	ELEFW328 (1360x768@60Hz)
	Intel HD Graphics (Gigabyte)
	1023MB NVIDIA GeForce GT 720 (EVGA)
	ForceWare version: 365.10
	SLI Disabled

**Comment by endrift** [comment]
Wrong direction. I meant BETWEEN 2017-07-08 and 2017-08-19 to help narrow down when it happened. Older does not provide any useful information.

**Comment by Cibomatto2002** [comment]
mGBA-build-2017-07-31-win32-4751-55679df8fc49fca3d5f8584d16b90e9bb734a922 was the last build that had the best FPS in Fast Forward. Starting with mGBA-build-2017-08-02-win32-4752-36c1fb59be4710543c4a5476a554757efe306ccd it got slower.

**Comment by endrift** [comment]
Please try this build to see if it's any better: https://s3.amazonaws.com/mgba/build/mGBA-build-2017-08-21-win32-4805-323a6326cd9d9f90f08e4ebd2c5b2f84fcdbd533.7z

**Comment by Cibomatto2002** [comment]
That work better thanks a lot.

**Comment by endrift** [comment]
Same performance as before the regression, or just closer?

**Comment by Cibomatto2002** [comment]
Same
