### ISSUE TITLE
The ability to change the file directories

### ISSUE THREAD

**Issue by Trexador96** [mgba-emu/mgba#86]
Im unable to change the savefile and cheats directory, It currently saves to the roms folder and I dont want clutter.

**Comment by karasuhebi** [comment]
I second this request. It'd be nice to keep the ROMs directory tidy, plus it would lower the barrier to entry for people moving from VBA and VBA-M since they wouldn't have to move their .sav files.

**Comment by endrift** [comment]
VBA stores them the same way as mGBA--this changed at some point in VBA-M though.

**Comment by karasuhebi** [comment]
Yeah sorry about that, I should have checked VBA's behavior before including it in the sentence. Fixed :)

**Comment by tony971** [comment]
Duplicate of https://endrift.com/mgba/bugs/show_bug.cgi?id=209

**Comment by endrift** [comment]
Fixed in a38beac307b7b42dbc5ad5806a92b91396bea555.
