### ISSUE TITLE
Portable Mode for Windows

### ISSUE THREAD

**Issue by Papermanzero** [mgba-emu/mgba#861]
Currently mgba for windows saves every settings in
C:\Users\'user'\AppData\Roaming\mGBA
However a portable mode would be beneficial to store all settings in the folder.
1) several instances of mGBA can be used (e.g. one for GBA games with dedicated settings and another one for GB Games and dedicated settings)
2) you can use mGBA on a usb drive.

**Comment by endrift** [comment]
This feature has existed for quite a while. There's a Make Portable option in the menu that will copy the config to the directory the exe is in and add a portable.ini file too. Just copy the exe to the flash drive, run it and select the option.

**Comment by Papermanzero** [comment]
'face-palm to myself'
I searched in the seetings for this option.

**Comment by endrift** [comment]
Yeah, it's not in settings, it's just in the file menu. It might be worthwhile to have a "select destination" option but that's about it
