### ISSUE TITLE
Odd frameskip value causes flickering.

### ISSUE THREAD

**Issue by easyaspi314** [mgba-emu/mgba#862]
mGBA version: 0.7-4807-a14126c9, also happens with 0.60.
Windows 10 Home (x86)
Dell Precision T3400
Intel Core 2 Duo E7400 @ 2.8GHz
4GB RAM (3.25 usable)
ATI FirePro v4800
Acer G235h

Basically, whenever I set the frameskip to an odd value, it starts flickering.

This happens on all games, including Pokémon Crystal and Pokémon Emerald, so it definitely isn't a ROM-specific issue.

![emerald skipping issue](https://user-images.githubusercontent.com/6258309/29781582-a662a202-8be7-11e7-865e-73c7a1aa1c9c.gif)

It isn't a great recording, but basically, every other frame shows a frame from earlier. 

I have tried toggling the Sync Audio and Sync Video options which have no effect except for a ridiculous speedup, and this also happens on all graphics backends.

I can provide more info if needed.

**Comment by endrift** [comment]
I was gonna say this looks like an 0.7 regression but...it happens in 0.6.0 too? Does changing the display driver have any effect?

**Comment by easyaspi314** [comment]
No, changing the driver doesn't have any effect.

Although, I'll double-check the 0.6 issue tomorrow. I could be wrong.
