### ISSUE TITLE
Changing GameBoy Hardware Generation

### ISSUE THREAD

**Issue by Papermanzero** [mgba-emu/mgba#863]
Some games like Shantae, Zelda Oracle Series etc. have a feature to detect the currently used Gameboy hardware. If certain GBC games are played on a GBA more features will be activated. Also the used color palette will be different. Currently it is not possible to change the used GameBoy hardware.
Depending on the game mGBA boot the appropiate hardware.

**Comment by endrift** [comment]
Already exists in the Override menu in 0.6 and a general setting is available (although I'm not sure it works atm) in 0.7.
