### ISSUE TITLE
Super Game Boy borders can't be disabled and option causes glitches

### ISSUE THREAD

**Issue by CharlesCorrin** [mgba-emu/mgba#868]
If you try to disable Super Game Boy borders in the options, it doesn't work. If you try to disable the option with a game running, it'll cause obvious screen glitching.

mGBA Revision: 4812-3ae911b
OS: Windows 10 64-bit

**Comment by endrift** [comment]
Partially fixed by b750c76d02af94646309a700c86c04faf6707b7d, though doing a reset still breaks it
