### ISSUE TITLE
Super Mario Advance 2 does not boot

### ISSUE THREAD

**Issue by Testsr** [mgba-emu/mgba#870]
This rom displays a white screen at startup and does not boot , with or without a bios.
On the log it shows "[GAME ERROR] GBA Memory:Out of bounds ROM Load16: 0x0D000000".  (0.7-4826-076ec733,Windows 10 64 bit)

**Comment by endrift** [comment]
Please don't upload ROMs.

**Comment by endrift** [comment]
...where did you download this build from? The latest official build is 0.7-4818-ca4d53f. There is no commit that corresponds with the version number you gave me.

**Comment by Testsr** [comment]
OKay the version number is corrected. Sorry.

**Comment by endrift** [comment]
oh ok that makes more sense.

Anyway it works fine on my laptop. Did you mess with the override settings at all?

**Comment by Testsr** [comment]
Is it the Newest build or  0.6?

**Comment by endrift** [comment]
I'm testing on newest build.

**Comment by Testsr** [comment]
Testing on newest. Does not work.

**Comment by Testsr** [comment]
Super Mario Advance 2:Super Mario world.

**Comment by Testsr** [comment]
How do you reset setting?

**Comment by Testsr** [comment]
Window 10 64 bit 1703

**Comment by CharlesCorrin** [comment]
I tested this game on the mGBA Windows 64-bit build, revision 4818-ca4d53f. I tested a verified dump from the North American and Australian region. CRC32 of the file is 5206880A.

Conclusion: The game works fine.

What is the checksum for your file? Can you test to see if it works in a real Game Boy Advance unit or the Game Boy Player attachment for GameCube?

**Comment by endrift** [comment]
Have you tried other games that work?

**Comment by Testsr** [comment]
Same CRC32.

**Comment by Testsr** [comment]
Gbata

**Comment by Testsr** [comment]
Sorry. Window 10 64 bit.

**Comment by Testsr** [comment]
ROM Load16

**Comment by Testsr** [comment]
Yes.

**Comment by Testsr** [comment]
Ubuntu maybe.

**Comment by zeromus** [comment]
try on another computer, to confirm you have settings on the computer youve been testing on which are breaking the emulator

**Comment by Testsr** [comment]
I Reset Computer and the thing boots now. Thank you.

**Comment by Testsr** [comment]
So sorry.
