### ISSUE TITLE
Mazes of Fate issues 

### ISSUE THREAD

**Issue by fanboy01** [mgba-emu/mgba#872]
When I try to load the game "Mazes of Fate", I'm greeted with the "Nintendo Health Warning" screen.  After trying to bypass that screen, two things happened:

1. The game completely freezes at the health screen and has weird audio issues.  I can shutdown the game with no problem.

2.  I tried to load the game again but it froze again and completely crashed mGBA.

This game works fine in VBA-M.

I'm using mGBA 0.6.0 on Windows 7

**Comment by zeromus** [comment]
Oddly it works in bizhawk, based on the mgba 0.6 release.

**Comment by CharlesCorrin** [comment]
It works fine for me with BIOS and without. I'm using the Windows 64-bit version, revision 4820-486b7ab. Please state your CRC32 and be sure it isn't your settings file being corrupt.

**Comment by fanboy01** [comment]
Ok, this game still won't load for me.  I tried the 64-bit version of mGBA (which I didn't know existed until today), and the game still wouldn't work!

A couple of new problems cropped up

1. I would come to the health warning screen. I pressed start to bypass it and instead, the game oddly resetted itself

2.  Tried to boot up game but it instantly failed with this error 

"The game has crashed with the following error:

Jumped to invalid address: 04E25EF0"

I got a similar error code with a different invalid address (I think) but I didn't write it down.

The rom CRC32 is 0B725A08.

Don't know if this will make a difference but...

Using Windows 7 64-bit with Aero turned on.

**Comment by CharlesCorrin** [comment]
That CRC32 is a good one and the same as the one I have.

Have you tried using a fresh config.ini file? Copy your old one outside the folder to keep the settings safe. You might need to check them to remember what you use/copy and paste folders, etcetera. Then delete the one the emulator is using now. Input the new settings through the UI as appropriate.

It might seem silly, but this trick worked for me in the past with mGBA. Recently the trick helped me with a MAMEUI update too. Oh, and try the same thing with mGBA's qt.ini file.

I don't know if Aero would cause any problems, as I use Windows 10.

**Comment by zeromus** [comment]
try a newer build

**Comment by endrift** [comment]
Actually I can reproduce this, but only in the SDL version.

It seems to have been broken by 9c23eb8428b2fd81d00c95ea1be56b508ba2b115.
