### ISSUE TITLE
A Metroid II Color Hack (from here: http://aderack.com/m2/) Gets Stuck On The BIOS Screen

### ISSUE THREAD

**Issue by John-Enigma** [mgba-emu/mgba#873]
This [Metroid II - Return of Samus color hack](http://aderack.com/m2/) apparently gets stuck on the GBC BIOS screen for some weird reason. 

I disabled the BIOS checkbox and it works perfectly.

**Comment by CharlesCorrin** [comment]
BGB (which along with Gambatte is one of the most accurate GB emulators) says this hack would not work on a real Game Boy. If that is so, then mGBA would be correct to not run it.

**Comment by endrift** [comment]
The patch is broken--it doesn't patch the checksum properly. Fixing the checksum makes it work.

**Comment by endrift** [comment]
To get it to boot properly change the byte at 0x14D in the patched ROM to 0xD5.

**Comment by John-Enigma** [comment]
Thanks @endrift! It got fixed. 

It boots with the BIOS properly now.
