### ISSUE TITLE
Super Game Boy borders doesn't work in Wii version

### ISSUE THREAD

**Issue by ruijtunes** [mgba-emu/mgba#874]
Super Game Boy borders don't work in the Wii version.

OS: Wii
Version: none work

**Comment by endrift** [comment]
Just to make sure, you've been trying development builds right? They don't work in any of the stable builds.

**Comment by ruijtunes** [comment]
Yes. I tried the development builds.

endrift <notifications@github.com> escreveu em seg, 18/09/2017 às 00:50 :

**Comment by endrift** [comment]
Looks like I can uh crash Dolphin trying to reproduce this.
