### ISSUE TITLE
Fairly OddParents: Breakin' da Rules crashes

### ISSUE THREAD

**Issue by SSWoodstock** [mgba-emu/mgba#876]
In mGBA 0.6.0, the GBA game The Fairly OddParents: Breakin' Da Rules crashes after selecting a difficulty, and you can't even play through the first level.
Tested on Windows 32-bit.

**Comment by endrift** [comment]
Regressed in 534d4fe5baffae9dca0dfe915c7c379752374ba4.

**Comment by RafaelOliveira71594** [comment]
Your ROM May Be Corrupted

**Comment by endrift** [comment]
The issue had already been resolved seven and a half years ago.
