### ISSUE TITLE
EEPROM8K file output size incorrect

### ISSUE THREAD

**Issue by cheatfreak47** [mgba-emu/mgba#877]
mGBA 6.0 Stable

Little Something I've noticed- Super Mario Advance seems to be creating an 8 kilobyte save file when the actual save is an EEPROM8K, meaning only 512 bytes (or 8Kbit) of data. Unsure if this affects other games with that save type, but figured I'd let you know. 

VBA-M gets this right by outputting a 512 byte file, as expected.

**Comment by endrift** [comment]
This affects all of the smaller-type EEPROM games. I've never bothered to make it work properly since it's such a minor issue. It should be an easy fix now that I've thought about how to do it though.
