### ISSUE TITLE
Pokemon Nameless FireRed project works

### ISSUE THREAD

**Issue by trbocode** [mgba-emu/mgba#879]
I know this is a weird issue, but I just had this game lock up on me on a 3DS (Before meeting oak), and as there are no known bugs in AGB_FIRM (to my knowlage), I assume this is the emulator's fault that it runs there. Libretro version used. Can you please debug and see what the hell is this romhack doing? Or is this out of the scope for this project (Since we're talking about romhacks)

**Comment by fox8091** [comment]
Ok, first, mGBA doesn't run under AGB_FIRM. Second, there likely isn't support provided for libretro's builds. Try an official one first, and if you can't reproduce, close please.

**Comment by trbocode** [comment]
@fox8091 I mean, I ran the libretro build on my Linux PC (Official hangs it when running anything, also a bug).
As AGB_FIRM is pretty much a real GBA, that means something in this build\Emulator is bad that it doesn't hang.

**Comment by endrift** [comment]
It breaks in the Qt version but not in the SDL version. Very strange.

**Comment by endrift** [comment]
I added a warning about the game hanging on real BIOS if you compress LZ77 data wrong, but I don't want the emulator to hang here so it "works" if you don't use BIOS.
