### ISSUE TITLE
[QUESTION] libjit

### ISSUE THREAD

**Issue by dimiro1** [mgba-emu/mgba#882]
Have you ever thought about using libjit[1] for jit implementation?

[1] https://www.gnu.org/software/libjit

**Comment by endrift** [comment]
I seem to recall looking into it before and being rather unimpressed with its design. I think I heard it's slow, but I may be thinking of something else. I can take another look but I'm not thrilled about this library.

@MerryMage care to weigh in, if you've heard of the library?

**Comment by MerryMage** [comment]
I've not actually used it myself. I've tended to prefer more control over output.
