### ISSUE TITLE
SRAM saves are incorrect size.

### ISSUE THREAD

**Issue by cheatfreak47** [mgba-emu/mgba#883]
SRAM / FRAM saves should be 32KB in size, fixing this would not break compatibility with VBA save either I don't think, as those simply pad out the extra 32KB with `FF` bytes, to fix that, simply accept 64KB saves for SRAM and when outputting a new save, overwrite it with 32KB.

This shouldn't matter really but I figured it was worth mentioning anyway.

**Comment by endrift** [comment]
...wait what

**Comment by cheatfreak47** [comment]
Yep, that's how it is, the Static RAM chip or Ferroelectric RAM chips used in GBA games are only ever have 32kb of actual storage, If games need 64KB of storage, they use FLASH512kbit (64KB) chips..

**Comment by endrift** [comment]
how did I never know that

**Comment by cheatfreak47** [comment]
`¯\(º_o)/¯`
I think VBA-M is still doing this wrong too actually, I should make an issue on their tracker
but I like mGBA more ^_^

**Comment by endrift** [comment]
I dug through a bunch of my SRAM saves and verified. I'm not sure how OOB works yet so I'm not gonna backport this to 0.6.1 until I do.

**Comment by cheatfreak47** [comment]
@endrift http://problemkaputt.de/gbatek.htm#gbacartbackupsramfram there's some really good data on this page if you want to read up sometime.

**Comment by endrift** [comment]
You say that as though I don't have that as a pinned tab and have for years ;)

**Comment by sergiobenrocha2** [comment]
Qt frontend is not changing from 64 to 32 kB automatically. You get 32 kB only with new saves.

**Comment by endrift** [comment]
Yeah, the frontend will never shrink files. It's not really a big deal I don't think.
