### ISSUE TITLE
Metroid Zero Mission Reversed Input

### ISSUE THREAD

**Issue by buvk** [mgba-emu/mgba#886]
While playing Metroid Zero Mission on 0.7-4831, I lost the ability to go left.  If I pressed left on my controller or keyboard, Samus would go right.

I am not sure if this is a glitch in the game, or a glitch in the emulator.  I have a save state if that helps.

**Comment by endrift** [comment]
This bug sounds reaaaaaally familiar...please do upload the save state.

**Comment by buvk** [comment]
[Metroid - Zero Mission (USA).ss1.txt](https://github.com/mgba-emu/mgba/files/1327681/Metroid.-.Zero.Mission.USA.ss1.txt)

Here you go.  Hopefully this works.  If I need to upload it elsewhere and link it, please let me know.

**Comment by endrift** [comment]
https://github.com/endrift/gbajs/issues/25 I found the old issue. Looks like I was never able to figure out why, but this state should help.

**Comment by endrift** [comment]
Since I haven't heard any reports of this in the last several years, I'm going to assume it's been fixed.
