### ISSUE TITLE
Exception When i try to open in homebrew launcher 

### ISSUE THREAD

**Issue by willshadows6628** [mgba-emu/mgba#888]
![22014819_1234507353349107_1856102074_n](https://user-images.githubusercontent.com/32298352/30858684-10a2f250-a297-11e7-90ca-150d0e7d659a.jpg)
![22047203_1234507350015774_1511857298_o](https://user-images.githubusercontent.com/32298352/30858685-10af3d6c-a297-11e7-95f8-4f0ea409b29c.jpg)

**Comment by endrift** [comment]
Development build or stable release?

**Comment by willshadows6628** [comment]
Stable Release. I've tried in some versions and the same has occurred in all,including in 0.6.0

**Comment by endrift** [comment]
Can't reproduce. Must have something to do with the files you have in the root of your SD card. Can you give me a list?

**Comment by willshadows6628** [comment]
![capturar](https://user-images.githubusercontent.com/32298352/30880361-bab2dab2-a2d8-11e7-8bb2-b494e562f502.PNG)
Thats is all i have in the root

**Comment by endrift** [comment]
Does this still happen with modern versions?

**Comment by endrift** [comment]
Closing due to lack of reply; assuming fixed.
