### ISSUE TITLE
[Windows] Default Window position hides title bar

### ISSUE THREAD

**Issue by FurbyTime** [mgba-emu/mgba#89]
Simple enough issue- Grabbed the emulator straight from the site, it's default position in the windows build makes it hide the title bar off screen, meaning you can't move the thing around without figuring out some way to make it reposition itself so you can get to the title bar.

**Comment by karasuhebi** [comment]
Known bug. Here's some workarounds:

Click on the right-side border and it should bring the rest of the window into the monitor.

Another workaround would be to right-click on the mGBA icon in your taskbar and click on 'Move', then use your keyboard arrow keys to move the window.

A shorter version of this workaround is to press Alt+Space to pull up a right-click menu which has 'Move' in it.

**Comment by endrift** [comment]
Fixed in 1f899737d9825f60e6713fed4ff6d368dda32e56. Wish I'd had more time to look at this yesterday.
