### ISSUE TITLE
Yellow Screen On Homebrew Launcher 

### ISSUE THREAD

**Issue by Bas25** [mgba-emu/mgba#891]
When I try to open mGBA on HBL, it gets freezed on a yellow screen. What can I do?
PD: I have an Old3Ds from USA in FW 11.4.

**Comment by endrift** [comment]
I’m pretty sure yellow screen is *hax payload’s fault, but I don’t know what it means. gspwn for the executable failing maybe? @smealum any insight? O3DS is too slow to run mGBA well regardless.

**Comment by Bas25** [comment]
Yeah,  I think the issue is with *hax payload, because also other apps don't work.

**Comment by Bas25** [comment]
Maybe I'll try to CFW my 3DS to play GB/GBC/GBA games using VC

**Comment by endrift** [comment]
Minus savestates that’ll work better anyway.

**Comment by Bas25** [comment]
Yes, I'll wait for payloads to be updated.

**Comment by fox8091** [comment]
Erm, even then that won't work. O3DS can't handle mGBA just because the O3DS too slow. And yes, yellow screen is completely *hax's fault. So, close?
