### ISSUE TITLE
Loading DX games won't boot with GBC bios enabled

### ISSUE THREAD

**Issue by bkacjios** [mgba-emu/mgba#894]
Using the latest release, 0.6.1, if you have gameboy color bios enabled, games like Links Awakening DX and Pokemon Yellow will not get past the bios splash.

**Comment by endrift** [comment]
All of these work for me. Are you sure your dumps are good?

**Comment by bkacjios** [comment]
Oh, I see what happened. I recently put these roms into the Emulator Goomba for my flashcart and modified the title to be more readable on my list of games.

Should changing the title within the header really stop it from working though?

**Comment by endrift** [comment]
Yep, exactly.
