### ISSUE TITLE
mGBA 0.6.1 Golden Sun 2 Fatal crash in battle

### ISSUE THREAD

**Issue by gadesx** [mgba-emu/mgba#897]
Big freeze-with sound glitching in Golden Sun 2 (S) happened me.

Rom name: Golden Sun - La Edad Perdida (ES) (FlashAdvance) [1162]
Save state in that moment, if it works for fix something.
[Golden Sun - La Edad Perdida save state 2](https://github.com/mgba-emu/mgba/files/1357129/Golden.Sun.-.La.Edad.Perdida.ES.FlashAdvance.1162.zip)

In that area the log always report
[GAME ERROR] GBA I/O:	Read from write-only I/O register: 0D0
[GAME ERROR] GBA I/O:	Read from write-only I/O register: 0C4

![golden sun - la edad perdida es flashadvance 1162 -0](https://user-images.githubusercontent.com/2506953/31195681-5d257890-a94b-11e7-9589-79a92b3bd23a.png)

**Comment by endrift** [comment]
Have you verified that it's a good dump? That sounds like a scene release to me...

**Comment by gadesx** [comment]
Now I'm changed to another rom, but I'm not sure that was a problem from that rom,
maybe some random obscure glitch, the Goodgba rom continue logs all time too
[GAME ERROR] GBA I/O: Read from write-only I/O register: 0D0
[GAME ERROR] GBA I/O: Read from write-only I/O register: 0C4

**Comment by endrift** [comment]
That being logged isn't unusual and isn't indicative of a real bug.

**Comment by vaguerant** [comment]
Rather than a scene release, I'd guess from the name that it's a version hacked to run on the Flash Advance Linker, an ancient flash cart that was around a long enough time ago that people were still calling them "linkers". Extremely unlikely to be a good dump. Who knows what they did to it.

**Comment by endrift** [comment]
Reproduces in 0.6.0.

**Comment by endrift** [comment]
Does not appear to reproduce in 0.5.0. Bisecting now.

**Comment by endrift** [comment]
Current best guess is that this was caused by the new timing system introduced shortly after 0.5.0.

**Comment by endrift** [comment]
Cannot reproduce on master. Please let me know if you can (with a known good ROM) and I'll reopen.
