### ISSUE TITLE
MGBA Stable 0.6.1 Bug list

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#898]
Hello Endrift.

**Here is my complete MGBA stable 0.6.1 bug list for  N3DS.

[MGBA_Stable_0_6_1_A_List.txt](https://github.com/mgba-emu/mgba/files/1372255/MGBA_Stable_0_6_1_A_List.txt)
[MGBA_Stable_0_6_1_B_List.txt](https://github.com/mgba-emu/mgba/files/1373180/MGBA_Stable_0_6_1_B_List.txt)
[MGBA_Stable_0_6_1_C_List.txt](https://github.com/mgba-emu/mgba/files/1375855/MGBA_Stable_0_6_1_C_List.txt)
[MGBA_Stable_0_6_1_D_List.txt](https://github.com/mgba-emu/mgba/files/1378204/MGBA_Stable_0_6_1_D_List.txt)
[MGBA_Stable_0_6_1_F_List.txt](https://github.com/mgba-emu/mgba/files/1380073/MGBA_Stable_0_6_1_F_List.txt)
[MGBA_Stable_0_6_1_H_List.txt](https://github.com/mgba-emu/mgba/files/1382114/MGBA_Stable_0_6_1_H_List.txt)
[MGBA_Stable_0_6_1_I_List.txt](https://github.com/mgba-emu/mgba/files/1382330/MGBA_Stable_0_6_1_I_List.txt)
[MGBA_Stable_0_6_1_J_List.txt](https://github.com/mgba-emu/mgba/files/1385221/MGBA_Stable_0_6_1_J_List.txt)
[MGBA_Stable_0_6_1_K_List.txt](https://github.com/mgba-emu/mgba/files/1385707/MGBA_Stable_0_6_1_K_List.txt)
[MGBA_Stable_0_6_1_L_List.txt](https://github.com/mgba-emu/mgba/files/1385708/MGBA_Stable_0_6_1_L_List.txt)
[MGBA_Stable_0_6_1_M_List.txt](https://github.com/mgba-emu/mgba/files/1385709/MGBA_Stable_0_6_1_M_List.txt)
[MGBA_Stable_0_6_1_N_List.txt](https://github.com/mgba-emu/mgba/files/1357204/MGBA_Stable_0_6_1_N_List.txt)
[MGBA_Stable_0_6_1_O_List.txt](https://github.com/mgba-emu/mgba/files/1357205/MGBA_Stable_0_6_1_O_List.txt)
[MGBA_Stable_0_6_1_P_List.txt](https://github.com/mgba-emu/mgba/files/1360372/MGBA_Stable_0_6_1_P_List.txt)
[MGBA_Stable_0_6_1_R_List.txt](https://github.com/mgba-emu/mgba/files/1360708/MGBA_Stable_0_6_1_R_List.txt)
[MGBA_Stable_0_6_1_S_List.txt](https://github.com/mgba-emu/mgba/files/1366373/MGBA_Stable_0_6_1_S_List.txt)
[MGBA_Stable_0_6_1_T_List.txt](https://github.com/mgba-emu/mgba/files/1366892/MGBA_Stable_0_6_1_T_List.txt)
[MGBA_Stable_0_6_1_U_List.txt](https://github.com/mgba-emu/mgba/files/1367042/MGBA_Stable_0_6_1_U_List.txt)
[MGBA_Stable_0_6_1_W_List.txt](https://github.com/mgba-emu/mgba/files/1369225/MGBA_Stable_0_6_1_W_List.txt)
[MGBA_Stable_0_6_1_Z_List.txt](https://github.com/mgba-emu/mgba/files/1369663/MGBA_Stable_0_6_1_Z_List.txt)

**Comment by waddlesplash** [comment]
If you can test all of these on mGBA desktop as well as N3DS, please make *individual* tickets for all the ones that reproduce on both. Otherwise it'll just be a lot of time that one of the developers has to spend going through all of these...

**Comment by Dodain47** [comment]
Sorry but i don´t have the time for testing on mgba desktop.  
The bugs are all early in the game. Like on the Titlescreen.

**Comment by endrift** [comment]
Of these I've confirmed the following:

- [ ] Cyberdrive Zoids - Kijuu no Senshi Hyuu (J) - White Screen. The Game won't boot. Unplayable.
- [ ] NFL Blitz 20-02 (U) - There are GFX Glitches during the Tactics Screen.
- [ ] Turbo Turtle Adventure (U) - Some GFX Glitches on the Titlescreen.

Many of the rest I didn't bother with because "it's slow on 3DS" isn't a bug.

**Comment by endrift** [comment]
Looks like the Zoids game uses BIOS calls that aren't implemented in the HLE BIOS. It works fine with official BIOS.

**Comment by Dodain47** [comment]
I see. I shouldn´t consider long loading times as bugs then.

**Comment by endrift** [comment]
NFL Blitz bug is indeed the same bug as #142. I need to write those DMA tests I've been putting off.

**Comment by benderscruffy** [comment]
i think this can be closed now
