### ISSUE TITLE
Wade Hixton's Counter Punch - Hired Help graphical glitches

### ISSUE THREAD

**Issue by Krusher97** [mgba-emu/mgba#900]
![counter punch](https://user-images.githubusercontent.com/25664221/31305551-1a62dd98-ab5a-11e7-8799-a8cee85e7cd5.gif)
The gif itself is missing some frames where the black bars appear on the helper sprite but its still there.

Steps to reproduce
1. Buy 40$ upgrade from the back alley
2. Talk to the Ringgirl in the bar and hire her
3. Press Select in a fight and start punching the opponent

**Comment by endrift** [comment]
Can confirm this happens in mGBA, but it also happens in other emulators so verification that this doesn't happen on hardware is appreciated.

**Comment by Krusher97** [comment]
I can't find any footage of this that specifies if its from the original hardware or not.

**Comment by endrift** [comment]
Confirmed occurs on hardware.
