### ISSUE TITLE
e-Reader Save Type is Wrong (Not a Request for Card Scan Support)

### ISSUE THREAD

**Issue by wildgoosespeeder** [mgba-emu/mgba#901]
I am not requesting e-Reader card scan support. I know that will arrive at some point (can't wait for when that feature becomes a thing for mGBA 👍 ). Just going to get that out of the way.

The problem I am experiencing is that there are ready-to-use saves, like on Zophar's Domain and [CaitSith2](https://www.caitsith2.com/ereader/saves.htm), like for Mario Party-e and even some homebrews, but mGBA likes to use the wrong save format during emulation, which it defaults to 64KB saves (Flash 512Kb), which corrupts the saves from the two websites. I did some testing in VBA (2004) and VBA-M, as those produced the same "e-Reader Memory Error" screens. I provided proper save overrides in the vba-over.ini file. The e-Reader uses 128KB saves (Flash 1Mb). The emulators stopped showing the "e-Reader Memory Error" screen and went to the title screen as expected, once the right override was specified.

The latest dev builds of mGBA have this issue and likely older stable builds. It would be nice to try the homebrews in mGBA.

**Comment by endrift** [comment]
I'm probably not going to fix this before I implement e-Reader at all.

**Comment by wildgoosespeeder** [comment]
How does that work in mGBA? I only understand VBA and VBA-M overrides in an INI file. I tried to do it in the GUI but can't get it to work.

**Comment by endrift** [comment]
Mooted by proper e-Reader support.

**Comment by wildgoosespeeder** [comment]
DUDE! This is amazing news! Just downloaded the latest development build. Time to move on from NO$GBA. Thanks for finally implementing!
