### ISSUE TITLE
DK: King of Swing - pause menu teleportation to the last world

### ISSUE THREAD

**Issue by eToThePi-i** [mgba-emu/mgba#902]
Yet another King of Swing glitch! This time, it's a bug that's been present throughout all versions of mGBA. It happens on every version of the game (U.S., Japanese, and European), as well. I'm running mGBA 0.6.1 on Windows 8.1. It doesn't happen on VBA-M, and I haven't seen any other mention of it, but I haven't verified it on an actual cartridge and handheld.

I've made a video demonstrating it [here](https://www.youtube.com/watch?v=jKzvXLJBuLI).

It's very reproducible; all you have to do is:

1. Enter any save file (new or old [back up your save file first if you care, so you don't get stuck.])
2. Enter Single-Player Jungle Jam.
3. Enter _any_ of the events (I've tested them all for this bug, including the ones that are only unlockable by codes).
4. Pause and scroll down (or up) to press "Select Event"
5. You are then teleported to the last world instead of going back to the "Select Event" screen

In an old save file, I've also had this happen with the "Return to Select Event" option at the end of an event, but I haven't been able to reproduce that.

_Edits: Clarification and expansion._

**Comment by zeromus** [comment]
You scrolled _up_ to "Select Event". That may be significant. Menus sometimes have bugs like that when you wrap around the wrong way and choose the last option.

**Comment by eToThePi-i** [comment]
@zeromus 

Actually, it happens whether you scroll up or down, I just happened to scroll up in the video.

**Comment by endrift** [comment]
Confirmed. This one is going to be *hell* to fix.

**Comment by endrift** [comment]
Dang this happens even as far back as 0.1.0. So much for trying to bisect a fix.

**Comment by eToThePi-i** [comment]
You weren't wrong when you said it would be hell to fix. I wish I knew more about emulator development and could help, but I'm only an amateur programmer at the moment.

**Comment by endrift** [comment]
I wrote this emulator and I'm still not sure how to debug it.

**Comment by eToThePi-i** [comment]
Yay! This was a pleasant surprise for the morning. Awesome work fixing the error, endrift!
