### ISSUE TITLE
3DS/Switch/Vita/Wii Cheat Support

### ISSUE THREAD

**Issue by Ninjistix** [mgba-emu/mgba#903]
was checking on here, the forums and website, but I can't find any info on how to use cheats on the 3DS, is it possible or not?

**Comment by endrift** [comment]
It’s not yet possible, but it is planned.

**Comment by Ninjistix** [comment]
oh okay, was kinda lost when i downloaded the cia on my n3ds

**Comment by goooroooX** [comment]
Guys, is cheat support implemented for 3DS version?

**Comment by endrift** [comment]
Using this as the main report for cheat support on the homebrew ports.

**Comment by endrift** [comment]
Initial support has been added for 3DS, Switch and Vita. Wii support pending. The UI needs work.

**Comment by endrift** [comment]
This has been fully implemented as of a few weeks ago and will be released with 0.10
