### ISSUE TITLE
Sonic Advance 1-3 Games - Save Types are Wrong

### ISSUE THREAD

**Issue by wildgoosespeeder** [mgba-emu/mgba#904]
Similar to #901.

I found out the saves for the Sonic Advance games are wrong, especially Sonic Advance 3. Sonic Advance 3 saves from [Zophar's Domain](https://www.zophar.net/search?search=sonic+advance) don't work in mGBA. Added entries to vba-over.ini in VBA (2004) and VBA-M, as those produce similar problems without the overrides, and the saves work properly. Here's the new entries:

 # Sonic Advance (U)
[ASOE]
flashSize=65536
saveType=3

# Sonic Advance 2 (U)
[A2NE]
flashSize=65536
saveType=3

# Sonic Advance 3 (U)
[B3SE]
flashSize=131072
saveType=3

These are untested on the European and Japanese versions, but are likely the same save types. Should I just create a general thread about save type issues in mGBA?

**Comment by endrift** [comment]
I have personally verified with a real cartridge that Sonic Advance 3 is actually 64kB, and all of them detect fine in mGBA.

The save file you downloaded for Sonic Advance 3 from Zophar is all zeroes. It's blank.

**Comment by wildgoosespeeder** [comment]
Huh. The weird thing is with the save from Zophar unlocks Knuckles, Cream, and Amy. I tried to force the save from Zophar to be 64KB and the emulator is rejecting it. Is there any way to rescue the wrong size save from Zophar, unless the save data was a hack of some kind?

**Comment by endrift** [comment]
The savedata is empty. There's nothing to save.

**Comment by wildgoosespeeder** [comment]
So weird. I guess plan B. [GameFAQs](https://www.gamefaqs.com/gba/918892-sonic-advance-3/saves) it is.
