### ISSUE TITLE
Unintended change of the language interface.

### ISSUE THREAD

**Issue by ShalokShalom** [mgba-emu/mgba#906]
EDIT: The interface was in German on the initial start and changed to English on the second.
I was in the settings menu in between and I did not touch the language settings there.

I think there is a setting, which unintentionally touches the language setting.

**Comment by rootfather** [comment]
What operating system and version of mGBA are you running?

When I use the latest mGBA codebase compiled with an up-to-date MSYS2 MinGW64 toolchain, at least on Windows 10 mGBA automatically detects that I am running the German version of Windows and thus applies the German locale right at the first start without any configuration.

**Comment by ShalokShalom** [comment]
KaOS, current (0.6.1)

**Comment by ShalokShalom** [comment]
To be honest, I think it was in German on the initial start and changed to English then.
I was in the settings menu in between, while I did not touch the language settings there.

**Comment by endrift** [comment]
huh I thought I fixed that bug

**Comment by ShalokShalom** [comment]
Oh, its well known. That is fine. 

I am not insane. 
Not here, at least. :smile:

**Comment by rootfather** [comment]
I re-checked this again and I can actually reproduce this issue on the latest master code.

The language changes back to English as soon as you change *any* setting in the settings dialog. Please note that if you open the Interface tab, you can see that it always falls back to English in the language selection dropdown menu.

This bug doesn't seem to appear when you select the UI language manually in the Interface tab, but only if you don't touch the language settings and rely on the auto detect feature.

**Comment by ShalokShalom** [comment]
Thanks a lot for testing.

**Comment by rootfather** [comment]
Any news on this? :)
