### ISSUE TITLE
F-Zero Maximum Velocity GSF set doesn't boot

### ISSUE THREAD

**Issue by kode54** [mgba-emu/mgba#907]
https://f.losno.co/f-zero_mv.zip contains a single ROM of the title music track.

It outputs the following to the log:

```
[WARN] GBA:Illegal opcode: 0000ebad
```

**Comment by vaguerant** [comment]
Locks up immediately after the bootROM on hardware (tested on DS Lite); literally immediately, just displays the Game Boy/Nintendo® splash indefinitely.

**Comment by kode54** [comment]
Idiot rippers. Apparently works in VBA.

**Comment by vaguerant** [comment]
I'm sorry, I forgot to fix the checksum in my initial test, the Game Boy splash lockup was obviously the checksum failing. Can confirm, however, that the ROM still locks up immediately after the splash: whitescreens with no audio output.
