### ISSUE TITLE
Gameboy game Bubsy II (USA) will not boot to title screen

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#912]
Gameboy game Bubsy II (USA) will not boot to title screen. the game will boot on VisualBoyAdvance-M v2.0.1 Emulator This is as far as it gets in mgba.

![capture10-1-2017-10 58 50 am10-1-2017-11 00 30 am10-1-2017-11 01 35 am10-17-2017-7 28 13 pm](https://user-images.githubusercontent.com/21169038/31695666-999ef780-b371-11e7-92e6-4e0a02231a18.jpg)

**Comment by endrift** [comment]
The game turns the screen off and then waits for either LY to be non-zero (doesn't happen) or an OAM IRQ on LYC (which has an invalid value)...hm

**Comment by endrift** [comment]
This is caused by a spurious STAT IRQ when writing to STAT at $097F.
