### ISSUE TITLE
GBA Cheats: PARv3 slide codes not functioning

### ISSUE THREAD

**Issue by Prof9** [mgba-emu/mgba#919]
Here are some valid PARv3 slide codes that don't work on mGBA in at least 168cad7. They're accepted in the code list, but don't seem to do any writes. I did cross check with GBATEK and the GameHacking FAQ this time.

## 8-bit slide
Write 0x08 bytes to 0x02000000 (inc 0x02) with value 0x01 (inc 0x10)
```
00000000 80200000
00000001 10080002
```

Should result in:
02000000: 01 00 11 00 21 00 31 00 41 00 51 00 61 00 71 00

## 16-bit slide
Write 0x08 halfwords to 0x02000010 (inc 0x01 * 2) with value 0x0000 (inc 0x01)
```
00000000 82200010
00000000 01080001
```

Should result in:
02000010: 00 00 01 00 02 00 03 00 04 00 05 00 06 00 07 00

## 32-bit slide
Write 0x04 words to 0x02000020 (inc 0x01 * 4) with value 0x00000000 (inc 0x01).
Final line works around a bug in the AR.
```
00000000 84200020
00000000 01040001
80000000 00000000
```

Should result in:
02000020: 00 00 00 00 01 00 00 00 02 00 00 00 03 00 00 00

**Comment by endrift** [comment]
Shoooould be fixed now. Let me know if I missed anything.
