### ISSUE TITLE
[Feature Request] Hotswapping support

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#92]
I'd like to be able to turn my controller on after mGBA launches and mGBA still recognize it. Thank you! :)

**Comment by endrift** [comment]
13dfb144e88290b0e747ac51391f0882e57ce4b2 adds basic support. It's still buggy and you have to open up the controller mapping window every time you plug a controller in.

**Comment by endrift** [comment]
Tracking remaining bugs with #201.

**Comment by karasuhebi** [comment]
>you have to open up the controller mapping window every time you plug a controller in.

So should I file another Issue to request this gets improved further to the point it just automatically detects it? Or is this already in your TODO somewhere?
