### ISSUE TITLE
[Feature Request] Allow separate directory for SAV paths

### ISSUE THREAD

**Issue by sora10pls** [mgba-emu/mgba#923]
Akin to VisualBoyAdvance, allow the user to define a certain path where all SAVs are located. Having the option is nice and allows for easy access to all save files in one directory, rather than having to potentially navigate through several different directories for a few save files.

**Comment by endrift** [comment]
This has existed for quite a while. Settings > Paths.

**Comment by sora10pls** [comment]
Ah, didn't even see the option surprisingly. Thank you!
