### ISSUE TITLE
Keyboard not being properly detected

### ISSUE THREAD

**Issue by david-simoes-93** [mgba-emu/mgba#925]
I'm running Linux Ubuntu 16.04, just compiled everything from source.

While the `Tab` key works (to fast forward) and the `\` key works (makes things go frame by frame), no other keys work. Neither `Z`, `X`, `Return` or `Shift` do anything. I'm not even sure how to debug this. 

My build has no menus in the game window (do I have to activate some flag when compiling?), so I cannot change controllers either. How can I fix this and what information should I provide to further debug this?

**Comment by endrift** [comment]
Sorry, this issue got lost somehow. To get the UI you need to build the Qt version (mgba-qt). Are you still having the issues described?
