### ISSUE TITLE
After restarting mGBA the controller resets to the first connected

### ISSUE THREAD

**Issue by Levan7** [mgba-emu/mgba#926]
I am using 0.7-4909 version and after shutting down and opening mGBA the controller resets to first one and i need to change it to the version that i have keys set every time i start it.

**Comment by tehFoxx0rz** [comment]
Hi, this seems to be quite an old issue, but it's the issue I'm having currently. Doesn't save the last controller used, or allow one to be set as a default.

I'm using 0.7.1 on PC,
Branch: heads/0.7.1
Revision: d93e042e5bb10341f7d9cc4832f287b1e2626779
from the About screen if that's helpful.

Thanks very much.

**Comment by endrift** [comment]
This should be fixed in the latest dev build. Please let me know, I wasn't able to test it as thoroughly as I wanted.

**Comment by Levan7** [comment]
@endrift Well i did some testing and the controls were saved after changes.
So i guess the issue was fix
