### ISSUE TITLE
it lags on windows 7 but not 10

### ISSUE THREAD

**Issue by gamesoulus** [mgba-emu/mgba#929]
i have been trying all types of roms to see if it was the roms or my pc. i found out it lags just on windows 7 .it runs fine on windows 10 with no problems, so what give? i have try all versions of mgba and they all lags, and version 6 lags so hard with multiplayer it unplayable. but on 10 it just fine. what is making it lag on windows 7? i have a buff pc and it lags. funny thing is that the windows 10 i have is weaker then the 7 i have. does anyone know what going on?

7 specs are as follows
[8GB of ram. processor is a 3.33GHz. operating system 64 bit and just upgrade to a stronger graphics card ]

10 spec are as follows
[4GB of ram. processor is a 2.70GHz. operating system 32 bit}

**Comment by endrift** [comment]
Try adjusting audio settings, especially buffer size, or changing sync settings.
