### ISSUE TITLE
[Compilation Failure] cheats.c - error: ‘struct mCore’ has no member named ‘dirs’

### ISSUE THREAD

**Issue by Enverex** [mgba-emu/mgba#933]
Not sure exactly when this started happening, but the core is failing to compile for me at the moment. The actual failure section is...

	/var/tmp/makepkg/libretro-mgba-git/src/mgba/src/core/cheats.c: In function ‘mCheatAutosave’:
	/var/tmp/makepkg/libretro-mgba-git/src/mgba/src/core/cheats.c:261:55: error: ‘struct mCore’ has no member named ‘dirs’
	  struct VFile* vf = mDirectorySetOpenSuffix(&device->p->dirs, device->p->dirs.cheats, ".cheats", O_WRONLY | O_CREAT | O_TRUNC);
														   ^~
	/var/tmp/makepkg/libretro-mgba-git/src/mgba/src/core/cheats.c:261:72: error: ‘struct mCore’ has no member named ‘dirs’
	  struct VFile* vf = mDirectorySetOpenSuffix(&device->p->dirs, device->p->dirs.cheats, ".cheats", O_WRONLY | O_CREAT | O_TRUNC);
																			^~
	make[2]: *** [CMakeFiles/mgba_libretro.dir/build.make:87: CMakeFiles/mgba_libretro.dir/src/core/cheats.c.o] Error 1
	make[2]: *** Waiting for unfinished jobs....

Using the build line:
`cmake . -DBUILD_LIBRETRO=1 -DBUILD_QT=0 -DBUILD_SDL=0 -DBUILD_SHARED=1 -DBUILD_STATIC=0 -DUSE_GDB_STUB=0 -USE_DEBUGGERS=0 -USE_EDITLINE=0`

**Comment by endrift** [comment]
This is a pretty new failure. I can fix this pretty easily.

**Comment by endrift** [comment]
I believe I fixed this and forgot to close the bug. Can you check?

**Comment by Enverex** [comment]
Confirmed, it's working fine now. Thanks.
