### ISSUE TITLE
[Feature request] Add support for (S)RAM auto-saving

### ISSUE THREAD

**Issue by rootfather** [mgba-emu/mgba#937]
I noticed that in the latest release, byuu added support for RAM auto-saving to higan. There's some discussion about it on the byuu board: https://board.byuu.org/viewtopic.php?f=4&t=1868

I think this would be a nice addition for mGBA too... what do you think?

**Comment by endrift** [comment]
I've actually thought about doing this before, especially on 3DS where the battery is subject to death, but I never got around to it.

**Comment by endrift** [comment]
Initial work here: https://github.com/endrift/mgba/commit/9c03a8bd59e8db12767f365597f3903fd50e11d9

Only supports 3DS at the moment.

**Comment by endrift** [comment]
Merged.

**Comment by rootfather** [comment]
Thanks a lot for implementing this!
