### ISSUE TITLE
DKC2 lagging

### ISSUE THREAD

**Issue by bob12111** [mgba-emu/mgba#938]
Anybody tried the GBA version of Donkey Kong Country 2 on mgba?  I have had trouble with it lagging and the music getting choppy.  The game gets particularly sluggish in levels such as Lockjaw's Locker and Rambi Rumble.  I'm using the latest version (I think), but I'm using it on the SNES Classic Edition, so could it be something related to that?

**Comment by endrift** [comment]
What version is that? I don't know how powerful the SNES classic is so it might just not quite be fast enough.

**Comment by benderscruffy** [comment]
i havent had any problems so far 
i think this can be closed
