### ISSUE TITLE
Alt+Return doesn't toggle fullscreen when there's no ROM loaded

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#94]
<s>As of at least 0.3.0, when you press Alt+Return, nothing happens when there's no ROM loaded. Strangely enough if you go into the Edit shortcuts window and rebind the Toggle fullscreen action to the same exact key combination, it'll work just fine.</s>

Going as far back as at least 0.3.0 (haven't bothered with older versions), Alt+Return doesn't make mGBA go fullscreen unless you click inside the display window or on one of the menu options to give it focus.

OS: Windows 8.1 x64
Build at time of writing: 0.4-2479

**EDIT:** The bug is still reproducible in 0.4-2873.

**EDIT 10/12/15:** Further investigation revealed that this is (apparently) a focus issue. I crossed out the old description as to avoid confusion.

**Comment by endrift** [comment]
Even just hitting tab before hitting Alt-Enter fixes this, but I can't seem to figure out why the shortcut is getting eaten. It's pretty minor though.

**Comment by karasuhebi** [comment]
Don't know when this was fixed but as of 0.5.2 Alt+Return works just fine even when a ROM is not loaded into mGBA. This issue is safe to be closed.
