### ISSUE TITLE
Load .sav files from other emulators?

### ISSUE THREAD

**Issue by leewdch** [mgba-emu/mgba#942]
I played for some time on the gambatte emulator and now I switched to mGBA but I can't load my previous sav files. Is this normal?

**Comment by rootfather** [comment]
Doesn't have each emulator it's own save file format? I never heard that save files are interchangeable between emulators...

**Comment by hhiru** [comment]
I used a bunch of emulators in the past and they generally use .sav files. Also I previously switched from android emulators to windows emulators and the load saves worked correctly

**Comment by zeromus** [comment]
No, it's not normal. I just loaded a DW3 save file from bizhawk's gambatte core into mgba 0.6.1. You are probably trying the one game whose save data is emulated differently between the emulators.

**Comment by hhiru** [comment]
For instance I'm trying to import my Pokémon Silver sav file. I guess I just used an android port of my windows emulator in the past so that's why the sav file worked back then. What about save states? I don't mind starting the game over since it was a 1d old sav. I guess devs can't really make sav files compatible with every single emulator out there..

**Comment by endrift** [comment]
Savestates are completely incompatible.

Savegames should be apart from a handful of cases:
- MBC2 and MBC7 saves would need to be converted
- MBC3+RTC might have some issues (but shouldn't)
- Exotic MBCs aren't really supported

This is an MBC3+RTC case but in theory it should work. Can you send the sav?

**Comment by kargaroc** [comment]
This would require writing savestate loading code for each format.  That being said, it's totally possible.

**Comment by endrift** [comment]
Uh, no, it's not. The inner workings of each emulator are different. Even if you wrote the savestate loading code there's no guarantee that it would actually map to the inner workings of a different emulator.

**Comment by endrift** [comment]
Closing due to lack of response.
