### ISSUE TITLE
Video Inverted

### ISSUE THREAD

**Issue by inukaze** [mgba-emu/mgba#945]
Hi there i have the follow problem with the lastest version 

[![mgba_video_inverso.png](https://s17.postimg.org/m8pssbmtr/mgba_video_inverso.png)](https://postimg.org/image/nazzav5mz/)

Is upside down, and horizontal mirror.  :V 

And in the options i can't find nothing to put "horizontal mirror" and/or "upsidedown video" or something like that, for fix it.

**Comment by rootfather** [comment]
Have you loaded any shaders? Please also provide your graphics hardware and the used driver revisions.

**Comment by zeromus** [comment]
FYI that's only upside down.

**Comment by inukaze** [comment]
No, i dont have any shader yet. is not upside down, the horizontal is inverted too, inside the game

**Comment by endrift** [comment]
This is because your GPU drivers claim to support glFramebuffer but don't. Switch to OpenGL 1.x mode.

**Comment by inukaze** [comment]
Thanks you the opengl 1.x works :D
