### ISSUE TITLE
Lag after playing for short time

### ISSUE THREAD

**Issue by kenny-wettlaufer** [mgba-emu/mgba#947]
Hello, I've been using MGBA for quite some time now, after its been opened for a while it starts to lag - I am using the latest version built from source-code, on Debian 9.3, I get this lag on other Debian-based distros as well, seems to be regardless of kernel.
How do I uninstall it from source? is there an uninstall script somewhere? make uninstall doesn't work, I'm going to try out the stable version in the debian repos... Tried to use checkinstall but it fails.

**Comment by kenny-wettlaufer** [comment]
...will that uninstall it???

**Comment by endrift** [comment]
No, there is no automated way to uninstall it.

**Comment by kenny-wettlaufer** [comment]
Ok well how can I uninstall it? I don't want to have to re-do my entire computer just so I can install a different version of a gameboy emulator...

**Comment by endrift** [comment]
um

doesn't apt have an "ignore file conflicts" option? Use thata.

**Comment by kenny-wettlaufer** [comment]
???????? I don't know what that means... Why is there no uninstall script??? So I have no choice but to completely re-do my entire computer if I want to use the stable version in the deb repos??? -.-

**Comment by endrift** [comment]
There are no uninstall scripts because CMake doesn't generate them

if you think you need to reinstall because you can't figure out how to resolve file conflicts that's not my problem.

**Comment by kenny-wettlaufer** [comment]
Its not your problem that you don't have an uninstall script for your emulator? Wow that's rich. I'll just use VBAM, whatever, asshole.

**Comment by kenny-wettlaufer** [comment]
Fucking retard, you can't even make a functioning gameboy emulator that runs worth a fuck. Neckbeard loser.

**Comment by endrift** [comment]
dang ad hominems are really great

grow up and learn how to use you own OS before complaining that it's someone else's problem that you don't know how to use it
