### ISSUE TITLE
Improperly compressed LZ77 data. Real BIOS would hang.

### ISSUE THREAD

**Issue by Connor37** [mgba-emu/mgba#948]
Playing Fire Emblem - Fuuin no Tsurugi (English Patched). The game loads the intro, then crashes.
![image](https://user-images.githubusercontent.com/8341213/34323851-11ea7408-e85b-11e7-9f0c-72681a3089c3.png)

**Comment by endrift** [comment]
Does the patch work on real hardware?

**Comment by Connor37** [comment]
Sorry, my mistake, something must went wrong when I patch the rom using IPSWin.

Closed.
