### ISSUE TITLE
Buildbot: README_DE.html is emptly

### ISSUE THREAD

**Issue by rootfather** [mgba-emu/mgba#950]
It seems that something goes wrong while creating the README_DE.html. The file currently distributed by the buildbot is basically empty, besides `<meta charset="UTF-8">`.

**Comment by endrift** [comment]
I'll take a look in the morning, but for future reference buildbot issues go in this repo: mgba-emu/mgba-infrastructure

**Comment by endrift** [comment]
Scratch that, it was an issue with the mGBA installation process, so this was the right repo.
