### ISSUE TITLE
Game Overrides not Picking the right Gameboy model 

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#951]
mGBA-build-2017-12-25-win32-4947-500d613452d74d04e9df52201dfd610da35268d2. Game Overrides keeps picking Super Gameboy when playing a Gameboy Game. It makes using the quick save useless because it picks the wrong model.

**Comment by endrift** [comment]
You set the default Game Boy model to Super Game Boy in settings. I saw you post a screenshot of it weeks ago.
