### ISSUE TITLE
Final Fantasy Adventure intro crash

### ISSUE THREAD

**Issue by SCMidna** [mgba-emu/mgba#954]
On Windows 10, using version 0.6.1 of the emulator, the introduction sequence of Final Fantasy Adventure consistently crashes the emulator after the title graphic disappears and the third line of text scrolls onscreen.

**Comment by endrift** [comment]
Works for me. Do you have a good dump? What region?

**Comment by SCMidna** [comment]
Not sure if it's a good dump or not, but it's US region by definition (JP is Seiken Densetsu, PAL is Mystic Quest). I'll try a different ROM, though.

**Comment by Cibomatto2002** [comment]
It crashes on me as well. If you skip the into it plays.        Crc/SHA1 18c78b3a

Here is a video of it crashing. https://www.youtube.com/watch?v=PsHk69lBaJo&feature=youtu.be

**Comment by endrift** [comment]
Strange that this isn't crashing for me. I'll look a bit deeper.

**Comment by endrift** [comment]
Ok I got a configuration where it crashes. I know what's going wrong and how to fix it.
