### ISSUE TITLE
Skip BIOS intro not working

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#955]
Skip BIOS intro not working. mGBA-build-2018-01-08-win32-4978-a796c167e432c7106d5d892dc4917a4a38240a7f

**Comment by endrift** [comment]
Works for me. What's your config look like?

**Comment by endrift** [comment]
Or are you talking about GB/C games?

**Comment by endrift** [comment]
I just added support for GB/C games, though it's kinda pointless since using the BIOS doesn't actually do anything if you're skipping it directly.

**Comment by Cibomatto2002** [comment]
I thought when skipping the BIOS it would skip the BIOS screen and just boot up to the game right off. Here is my config.

[ports.qt]
gbc.bios=D:/Emulators and Codes/Game Boy Advance/BIOS/GBC BIOS.BIN
preload=0
sgb.bios=
width=480
useBios=1
audioBuffers=1536
lockAspectRatio=0
volume=256
shader=
rewindSave=1
savestatePath=D:/Emulators and Codes/Game Boy Advance/Saves
screenshotPath=C:/Users/Jason/Desktop
libraryStyle=0
fastForwardRatio=-1
sgb.borders=1
sampleRate=44100
mute=0
rewindBufferCapacity=300
allowOpposingDirections=0
suspendScreensaver=1
savegamePath=D:/Emulators and Codes/Game Boy Advance/Saves
patchPath=
idleOptimization=ignore
showFps=1
cheatAutosave=1
lastDirectory=D:/Roms/Game Boy Advance ROMS
gba.bios=D:/Emulators and Codes/Game Boy Advance/BIOS/GBA BIOS.BIN
audioSync=1
frameskip=0
fpsTarget=60
cheatsPath=D:/Emulators and Codes/Game Boy Advance/Cheat
skipBios=1
rewindEnable=0
loadStateExtdata=9
autofireThreshold=1
cheatAutoload=1
gb.bios=D:/Emulators and Codes/Game Boy Advance/BIOS/GB BIOS.BIN
videoSync=0
pauseOnFocusLost=0
showLibrary=0
height=320
fullscreen=0
lockIntegerScaling=0
resampleVideo=1
saveStateExtdata=31

[gba.input.SDLB]
keyR=7
keyL=6
axisUpAxis=-1
hat0Right=4
gyroSensitivity=2.2e+009
keyStart=9
keyLeft=-1
keyDown=-1
hat0Left=5
axisLeftAxis=-0
keyB=2
keyUp=-1
hat0Down=7
axisRightValue=12288
axisRightAxis=+0
axisUpValue=-12544
axisDownAxis=+1
gyroAxisX=0
tiltAxisX=2
axisDownValue=12032
keyA=1
keyRight=-1
device0=Generic   USB  Joystick  
hat0Up=6
gyroAxisY=1
axisLeftValue=-12288
keySelect=8
tiltAxisY=3

[gba.input.QT_K]
keyR=83
keyL=65
keyStart=16777220
keyLeft=16777234
keyDown=16777237
keyB=90
keyUp=16777235
keyA=88
keyRight=16777236
keySelect=16777219

[gba.input-profile.Generic   USB  Joystick  ]
keyR=7
keyL=6
axisUpAxis=-1
hat0Right=4
gyroSensitivity=2.2e+009
keyStart=9
keyLeft=-1
keyDown=-1
hat0Left=5
axisLeftAxis=-0
keyB=2
keyUp=-1
hat0Down=7
axisRightValue=12288
axisRightAxis=+0
axisUpValue=-12544
axisDownAxis=+1
gyroAxisX=0
tiltAxisX=2
axisDownValue=12032
keyA=1
keyRight=-1
hat0Up=6
gyroAxisY=1
axisLeftValue=-12288
keySelect=8
tiltAxisY=3

**Comment by endrift** [comment]
If this was for GB/C games try the latest build. It wasn't implemented for those until just now. Also booting a GB game with GBC BIOS skipped is probably broken; I haven't tested it yet.

**Comment by Cibomatto2002** [comment]
It works thanks. I was using the Game Boy BIOS.
