### ISSUE TITLE
(3DS) Better support to select bios 

### ISSUE THREAD

**Issue by angelhp** [mgba-emu/mgba#956]
In news versions it is only possible to select the bios of gba . 
 From the menu they can not be selected.

**Comment by endrift** [comment]
I'm sorry, I'm not sure I understand the request. Better how?

**Comment by angelhp** [comment]
Be able to select each bios separately in the gui.
For example : In menu
GBA bios 
GBC bios
GB bios
SGB bios
Look like the PC versions ,
and independently choose each

**Comment by endrift** [comment]
That's what I thought, but I wasn't sure. This shouldn't be too hard to add.

**Comment by angelhp** [comment]
Perfect then , 
thank you very much for listening to my requests endrift =)

**Comment by endrift** [comment]
Added. Not particularly well tested though, so let me know.
