### ISSUE TITLE
Super Duper Sumos occasionally freezes for a few seconds 

### ISSUE THREAD

**Issue by kurayami6** [mgba-emu/mgba#957]
When playing Super Duper Sumos on GBA, the game will occasionally freeze for a few seconds and then start working again. 

Using the latest version of mGBA. Windows 7, i5, GTX 970.

**Comment by Zerowalker** [comment]
Might be experiencing the same thing, just playing through Minish Cap and had random freezes the entire gameplay.

Latest nightly and Stable of the time.

**Comment by endrift** [comment]
Closing due to lack of additional info.
