### ISSUE TITLE
Double Dragon (USA, Europe) Cheat code stays on

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#962]
Game Boy. In Double Dragon (USA, Europe) MD5 545DE5C311259B7F7EC313A9D58CF4B4 The One Hit Kills (Bosses die in 3 hits) code will stay on even if the code is disabled. mGBA-build-2018-01-10 win32-4987-715efc63bd7178fc5a0058588b81de03fe74bc6d  
[Double Dragon (USA, Europe).zip](https://github.com/mgba-emu/mgba/files/1629647/Double.Dragon.USA.Europe.zip)

**Comment by zeromus** [comment]
You should confirm this on hardware or other emulators/builds. Cheats work by breaking the game; sometimes games, once broken, stay broken. This is a much more likely explanation than mgba doing something wrong, which would be likely to apply to a bunch of other cheats.

**Comment by endrift** [comment]
The codes in question are game genie, which means they're ROM patches.

**Comment by Cibomatto2002** [comment]
In vba-m it works correct. vbam-2.0.1
