### ISSUE TITLE
[3DS] Will not run on latest build (6.1) or Nightly; Red screen

### ISSUE THREAD

**Issue by lankylilimps** [mgba-emu/mgba#965]
Ive tried to run 6.1 and the latest Nightly on my 3ds, but neither work. It seems to load but freezes with a red screen on the bottom. It can run 6.0 perfectly fine, though I would prefer to run the latest version if possible.
I have a N3ds on the latest firmware (11.6.0.) Im using the .3dsx and have no access to cfw. Any other info needed please let me know.

**Comment by endrift** [comment]
Did you include the .xml file?

**Comment by lankylilimps** [comment]
Yes, I tried the .xml with 6.1 and the Nightly. Neither seemed to produce a different result.

**Comment by endrift** [comment]
Can I see the layout out of your /3ds folder? I don't have a New 3DS without cfw on it so I can't test this easily.

**Comment by lankylilimps** [comment]
Sure thing. Heres the /3ds folder
![image](https://user-images.githubusercontent.com/35511568/35136521-b888ff16-fca9-11e7-969c-51b6bc4b8d6e.png)
And here's the /mgba folder. Version 6.0 is in here atm
![image](https://user-images.githubusercontent.com/35511568/35136571-f5ed1676-fca9-11e7-8653-e02aaf57b739.png)

**Comment by endrift** [comment]
Can you try replacing the contents of `mgba.xml` with this:

```xml
<targets selectable="true"> 
</targets>
```

then selecting Face Raiders when starting mGBA from the HBL?

**Comment by lankylilimps** [comment]
Just tried it 4 times (Changed the files to 6.1) The selection works and loads up like how it would before. Top screen flashes a few colors, loading text shows up, and it results in a red bottom screen and regular black top screen. Once, though, a glitchy-looking top screen showed, but not sure if that's important.

**Comment by endrift** [comment]
Can you try selecting Download Play instead?

**Comment by lankylilimps** [comment]
Seems like the same result. Sometimes it'll immediately go to red bottom screen + glitchy top screen, but I think that depends on which entrypoint I used.

**Comment by endrift** [comment]
For all three? That's really disappointing. I'm not sure I have a better solution :/ I might have to try to trim down the build.

**Comment by endrift** [comment]
I'm gonna try a few things after lunch. I can send you updated files when I have them.

**Comment by lankylilimps** [comment]
Okay, thanks a bunch

**Comment by endrift** [comment]
@smealum any idea why o3DS Face Raiders works but n3DS doesn't?

**Comment by endrift** [comment]
Try this xml file:

```xml
<targets selectable="false">
    <title mediatype="0">0004001000020e00</title>
    <title mediatype="0">0004001000021e00</title>
    <title mediatype="0">0004001000022e00</title>
    <title mediatype="0">0004001000026e00</title>
    <title mediatype="0">0004001000027e00</title>
    <title mediatype="0">0004001000028e00</title>
</targets>
```

**Comment by lankylilimps** [comment]
Same result :( Seems to load up slightly slower, but still freezes w/ red screen.

**Comment by endrift** [comment]
Weird. Does selecting AR Games manually work?

**Comment by lankylilimps** [comment]
Should I change the .xml to where I can select AR games?

**Comment by endrift** [comment]
Yes, please.

**Comment by lankylilimps** [comment]
Ok, I just realized the .xml file was named wrong (.xml extension was in the name) and used the last one you sent. Looks like it works now! 
Sorry for the hassle but thank you for helping :)

**Comment by endrift** [comment]
Thanks for testing! I only just now got a setup that works for testing on my end, but it looks like it's solved now.

**Comment by lankylilimps** [comment]
Not a problem. Glad I could be a help too!
