### ISSUE TITLE
Mario Golf - Advance Tour (USA)

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#969]
Game stops and can't play on. Here is a Video and a Quick save. SHA-1: 157058590CFB1D1CB83A3AFAC4847C2169F360A7

mGBA-build-2018-01-21-win32-5003-789a84d2e25b2a6e7df0bb86351ec81726313eed

https://www.youtube.com/watch?v=CUakXBt6kOE&feature=youtu.be

[Mario Golf - Advance Tour (USA).zip](https://github.com/mgba-emu/mgba/files/1650261/Mario.Golf.-.Advance.Tour.USA.zip)

**Comment by endrift** [comment]
Possible dupe of #115, but with more information?

**Comment by Cibomatto2002** [comment]
Had no idea is was already reported.

**Comment by endrift** [comment]
After I looked closer I realized it's not actually a dupe. The game is actually crashing.

**Comment by JMC47** [comment]
I used the savestate provided and it crashed.  This is what I found in the logs upon crashing.

[WARN] GBA:	Illegal opcode: 0000e855

If I turn on the game error logs, mGBA itself will segfault before I even get there.

**Comment by endrift** [comment]
@JMC47 said this is fixed, @Cibomatto2002 please confirm.

**Comment by JMC47** [comment]
Note: savestates made with the "glitch" loaded will still error out, but, in about ~5 hours of play + more with new savestates.

This should probably be closed.

**Comment by Cibomatto2002** [comment]
It's working now Thanks.
