### ISSUE TITLE
every game i try running has no video

### ISSUE THREAD

**Issue by R08Y** [mgba-emu/mgba#970]
just a black screen on the emulator. but it has the audio

**Comment by endrift** [comment]
Try switching the display driver to OpenGL 1.x

**Comment by soldair** [comment]
this worked for me! thanks

**Comment by JMC47** [comment]
Is there anything suggesting this is an actual mGBA bug and not just the hardware having issues?

**Comment by endrift** [comment]
Closing due to lack of info.

**Comment by Heath123** [comment]
I have the same issue but it only works with software rendering. Arch Linux, Ryzen 7 5700U, Mesa open-source drivers

**Comment by endrift** [comment]
@Heath123 There are many things that could lead to this. This is a _very_ old bug report and probably their specific issue is fixed. Please file a new bug and make sure to attach the zip generated by File > Report bug.

**Comment by Heath123** [comment]
Created #2463
