### ISSUE TITLE
0.6.1 Vita crashes on start

### ISSUE THREAD

**Issue by Cathora** [mgba-emu/mgba#972]
Using mgba on Vita and whenever I open it, it seems to crash. The directory head opens (ux0:data) with clock working, but no directory to scroll through. Works until I press a button, then it crashes the app (C2-12828-1) and saves the core file.

All my files are properly in ux0:data in a folder called "GBA ROMS". If it helps, I'm using Henkaku enso via a sd2vita. Tried the latest stable release, and the new nightly.

**Comment by endrift** [comment]
I've never gotten my sd2vita working (I think it's a fake) so I don't think I'll have much luck debugging this.

**Comment by Cathora** [comment]
Thanks for the very quick response (and the title change, my bad). It's okay, just wanted to let you know. Great work on the app, and on Dolphin.

**Comment by endrift** [comment]
Can you see if the latest build fixes this?

**Comment by Cathora** [comment]
Wow, it works! Thanks, it's working great now. The audio is choppy, but I'm sure there's a fix out there in the config
