### ISSUE TITLE
Diacritic characters present in a path do not work via command line

### ISSUE THREAD

**Issue by Data0tter** [mgba-emu/mgba#974]
Build: 0.6.1
OS: Windows 10

When trying to launch a rom in mGBA via the command line, diacritic characters in the path cause it to fail.

When trying, the error 'The system cannot find the path specified.' is recieved

![cmderror](https://user-images.githubusercontent.com/35880961/35482380-2181f188-042c-11e8-924e-3a0a2d725338.PNG)

**Comment by rootfather** [comment]
Does it work when you put the path to the rom in ""?

**Comment by Data0tter** [comment]
The rom and emulator were both in "".

I've updated with an image of the error I recieved.

**Comment by endrift** [comment]
The error you received appears to have been because you pasted a line starting with `[1/8]:` after the line that runs the emulator.

**Comment by endrift** [comment]
I believe this was fixed years ago in c364a6527a83d22bdd79e77286d0b53b0b624746. Please open a new report if you still have this issue.
