### ISSUE TITLE
Super Mario Land 2 (v1.0) - missing status bar

### ISSUE THREAD

**Issue by SimpleTease** [mgba-emu/mgba#977]
Hi, using the retroarch win32 mgba version (2018-01-29 date -- 0.6.1 17973ea). During in-game play, the status bar at the bottom of the screen is empty; it should display lives, coins, timer.

Also having problems with savestates. Example is have mario go down 'B' game pipe. Savestate and loadstate later on. He falls through the pipe and wraps around at the top of the screen. More glitchy things can happen when switching between the "pipe load screen" and other in-game areas.

**Comment by endrift** [comment]
While the first issue was fixed in master (which has not yet been merged into libretro, nor probably will be for a while), the second is an issue with how savestates are handled between mGBA and libretro, and will require reworking. It works fine in the standalone version.

**Comment by SimpleTease** [comment]
Thank you. I'll use Vista for playing the standalone app in the meantime.

**Comment by endrift** [comment]
This should be fixed now.
