### ISSUE TITLE
Qt: Remove "Enable rewind" setting

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#98]
A rewind history of 0 states is functionally equivalent. The check box is just clutter. (Split from #83 )

**Comment by endrift** [comment]
The idea here was to be able to switch rewind on or off, perhaps temporarily, without screwing with your actual rewind settings at all. A master switch, as it were.

**Comment by tony971** [comment]
Ahh. Well then... Doesn't seem like anything I would toggle but I guess the option should be there. I just never considered it to be a dynamic setting.

**Comment by tony971** [comment]
Ahh. Well then... Doesn't seem like anything I would toggle but I guess the option should be there. I just never considered it to be a dynamic setting.
