### ISSUE TITLE
Medusa - Qt build error in MemoryModel.cpp

### ISSUE THREAD

**Issue by ShalokShalom** [mgba-emu/mgba#980]
This happens with current Qt and the Git build of Medusa: 
https://gist.github.com/ShalokShalom/3d6e2d390fc3c379a8cd6d023b638002#file-gistfile1-txt-L729

**Comment by endrift** [comment]
This was fixed on master. I'll try to merge master soon

**Comment by ShalokShalom** [comment]
Thanks a lot.

**Comment by endrift** [comment]
Merged master yesterday. Default settings crash (oops) but if you disable autosave it works.

**Comment by ShalokShalom** [comment]
How to disable autosave? I build by adapting existing PKGBUILDs, so I am happy if that works at all. 
https://git.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/mgba

Can I simply fork and disable it somewhere in the source?

**Comment by endrift** [comment]
It's under Setting > Interface

**Comment by ShalokShalom** [comment]
Oh, so you mean. I thought the build breaks. thanks
