### ISSUE TITLE
The xbr-lv3 shader is broken on Ubuntu 16.04

### ISSUE THREAD

**Issue by TheEssenceOfDarkness** [mgba-emu/mgba#983]
I have no idea why, but for some reason xbr-lv3 will not work on my ubuntu machine at all.
![xbr-lv3](https://user-images.githubusercontent.com/15368682/35713525-cdfcc14c-0795-11e8-8491-8e6785c0c6db.png)

xbr-lv2 will work fine however:

![xbr-lv2](https://user-images.githubusercontent.com/15368682/35713551-edce3816-0795-11e8-98b4-04b5eee430e3.png)

Since you are probably going to need info about my GPU, here is the output from glxinfo:

[glxinfo.log](https://github.com/mgba-emu/mgba/files/1687882/glxinfo.log)

**Comment by endrift** [comment]
Unfortunately this is most likely a driver bug. Try the xBR shaders in RetroArch to see if you have the same issue.

**Comment by TheEssenceOfDarkness** [comment]
I tried it in retroarch, and the only xbr shader having issues is xbr-lv3. I am assuming my driver is having issues with this *one* shader
