### ISSUE TITLE
The mGBA window isn't visible

### ISSUE THREAD

**Issue by RetroGameReaper** [mgba-emu/mgba#984]
Recently mGBA hasn't been visible. If I start a game through Launchbox, I can hear the music, but I can't see anything. Last week I unplugged one my monitors and it was fine. When it did it again I tried unplugging the monitor once more but to no avail. I'd like it if someone could help me fix it.

**Comment by endrift** [comment]
Do you know which frontend Launchbox uses? SDL or Qt?

**Comment by endrift** [comment]
Does this still reproduce?

**Comment by endrift** [comment]
Closing due to lack of reply.
