### ISSUE TITLE
Audio is off globally

### ISSUE THREAD

**Issue by arkazal** [mgba-emu/mgba#996]
The sound (mostly music when I say that) is terrible in Magical Houshin. I've experienced this on mGBA 0.6.1 and 0.6.0. I run Windows 7. Unfortunately it's a little difficult for me to give an example of this or describe the sound. The easiest thing to do in order to hear how it should sound is to load the game in VBA-next.  But if there's some way I can help further, let me know.

**Comment by arkazal** [comment]
So I'm updating this with some more info. Basically, audio really isn't good in a lot of games.

In F-Zero Maximum Velocity, the audio is off in several instances. For example, the beeps when the race is starting are way louder than everything else. Also, the Stark Farm music has the bassline way louder than everything else.

In Kurukuru Kururin, on the map music, the part of the music that keeps the "rhythm" is way louder than it should be, it pretty much overpowers the rest of the song.

In Magical Houshin, most songs sound like they are in a tin can.

Also, sound across the board seems slightly quieter than VBA, but not just by volume but in the way that it just seems a tad muffled.

These three games that I tested I also own physically. When I play them on the Game Boy Player through my Gamecube, they sound exactly like they do when I play it in VBA-next. Before switching to mGBA, I only used VBA-next and never noticed the audio because it's exactly like when I play on real hardware. But when I switched to mGBA, I find myself noticing the audio all the time.

Would audio clips help somehow? I don't want to upload things to Youtube because that turns out bad.

**Comment by endrift** [comment]
Yeah, some audio comparisons would help. Thanks.

**Comment by dobyrch** [comment]
I'm not sure if this is related (as it affects a GBC game), but I noticed that some of the music in Pokemon Gold/Silver differs from other emulators.

In [these samples](https://github.com/mgba-emu/mgba/files/2363358/samples.zip), Gambatte and SameBoy sound the same, but the light tapping noise in the background sounds more like a metallic buzzing noise in mGBA. The audio in mGBA is also noticeably louder than the other two.

**Comment by endrift** [comment]
Closing seeing as I've done a lot of audio work since this and I'm pretty sure @arkazal [isn't going to comment further](http://tasvideos.org/forum/viewtopic.php?p=468568#468568) (although I'll be pleasantly surprised if they do).
